### ISSUE TITLE
pod 'Blah', :head causes iTC rejection — because version is set to "HEAD based on X.Y.Z"

### ISSUE THREAD

**Issue by fatuhoku** [CocoaPods/CocoaPods#4428] opened 2015-10-22 15:51 UTC
Reproduction:

1. Create a new project with `Podfile` with `pod 'SVProgressHUD', :head` as its contents.
2. `pod install`
3. Distribute this project's IPA to TestFlight.

Expected result: the app should be accepted by iTC.
Actual result: the app is rejected by iTC, because a sub-module versions need to look like `A.B.C` now.

The issue whenever you use `:head`, the pod target's Version is set to a string that looks like: `HEAD based on 1.1.3`: 

![screen shot 2015-10-22 at 16 44 25](https://cloud.githubusercontent.com/assets/430233/10670394/339c8fea-78dd-11e5-8841-115d0507cfc7.png)

This used to be okay, but now is no longer acceptable by iTC because all sub-frameworks' versions are validated against the `A.B.C` format as well.

I think this is related to the new iTC validation rules mentioned in #4421 in part.

**Comment by orta** [comment] 2015-10-22 15:56
For now this is basically a dupe of #4421 - it will have the same answer. In the mean time check out my podfile post_install to fix it.

**Closed by orta** 2015-10-22 15:56 UTC
