### ISSUE TITLE
Create a local pod with c++ library

### ISSUE THREAD

**Issue by fphcare** [CocoaPods/CocoaPods#5688] opened 2016-07-27 21:58 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

**To build a framework** 

1 ) Created a cocoaTouch framework with objective C 
2 ) Added Pod for using 'PromiseKit/Promise', '1.4' in the framework
3 ) The framework contains some c++ files
4 ) The framework is build success

**To convert the framework to a local pod**

1 ) Created a specs file using pod spec create command 
2) Following is the detail of my spec file

Pod::Spec.new do |s|
  s.name         = "SampleLibrary"
  s.version      = "1.0.0"
  s.summary      = "SampleLibrary. ...."
  s.author       = { "Tony Mu" => "" }
  s.platform     = :ios, "8.0"
  s.source       = { :git => "...", :tag => s.version }

  s.source_files  = "SampleLibrary/**/*.{h,m,mm,cpp,c}"
  s.resources = "SampleLibrary/**/*.{xml}"
  s.libraries = "xml2", "c++"

  s.xcconfig = { "HEADER_SEARCH_PATHS" => "$(SDKROOT)/usr/include/libxml2" }
  s.dependency 'PromiseKit/Promise', '1.4'
  s.dependency 'OCMock', '~> 3.1'
end

**Installed the SampleLibrary to App from pod**

1 ) The following is my Podfile in the app 

platform :ios, '8.1'

workspace 'SampleApp'

target 'SampleApp' do
  use_frameworks!
  
  pod 'Alamofire'
  pod 'AlamofireObjectMapper', '~> 3.0'
	pod 'PromiseKit/Promise', '1.4'
  pod 'SampleLibrary', :path => '../SampleLibrary/'
end

2 ) run Pod install, the SampleLibaray has been installed to the app 

3) Try to build the project

## What did you expect to happen?

Build success 

## What happened instead?

The build errors from Pod SmapleLibrary c++ file header : #include '<'string '>' is not found.
 
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a53feaffd45afec1afb752c65e40a0f281ad6b5b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0

## Project that demonstrates the issue

**Comment by neonichu** [comment] 2016-07-30 09:42
Please share a project which reproduces this issue. We have no way to debug where the build errors you're describing are coming from.

**Comment by schillerGao** [comment] 2016-08-05 02:11
hi，guy, how do you solve this problem in the end?
I had happened a problem like you.  I created my private pod , it included a dependency named "Googleprotobuf", a c++ dependency . Finally , I excuted "pod install"  in another project to install this private pod . The project build failed . 
Error: "Googleprotobuf" #include <cstddef>  file not found ---> common.h  .

**Comment by fphcare** [comment] 2016-08-05 02:22
Hey schiller,
We haven't solved this problem. As neonichu said, I am going to submit a demo project for him to look at this issue. 

At moment, we are just using framework instead private pod. I will let u know if the problem has been solved.

**Comment by schillerGao** [comment] 2016-08-05 04:01
Thank you very much for replying ! I had been blocked here for two days. I think it maybe I lost some configurations in our  pod specification file. But I do not sure.

**Comment by schillerGao** [comment] 2016-08-07 05:40
@fphcare , finally , I solved my problem. I found that  In an objective-c file I had a import an oc file named "Common.h", which in the Googleprotobuf it also has a c++ file name 'common.h', although the initial alphabet is 'c' and 'C',  it still cannot find the correct one when compiling.  
In the end , I changed the name of my OC file 'Common.h' to 'SFCommon.h' and it build successfully.

**Comment by fphcare** [comment] 2016-08-09 00:45
Good Job Schiller ! I will review our project and see if it has same issue. Thanks for letting me know.

**Comment by neonichu** [comment] 2016-08-22 20:48
Closing this, because I don't think there unfortunately isn't anything actionable we can do here.

**Closed by neonichu** 2016-08-22 20:48 UTC
Labels: s1:awaiting input

**Comment by tveritinova** [comment] 2017-05-06 20:25
Hello! Can you help me? I want to use [DEST library](https://github.com/cheind/dest) by cocoa pods in my iOS app. I tried to use .spec file like this: 
`Pod::Spec.new do |s|
  s.name             = 'dest'
  s.version          = 'v0.8'
  s.summary          = ' One Millisecond Deformable Shape Tracking Library'

  s.description      = <<-DESC
Deformable Shape Tracking (DEST) is a C++ library providing high performance 2D shape tracking leveraging machine learning methods. The video below shows the real-time capabilities of DEST in annotating video sequences / still images with facial landmarks.
                       DESC

  s.homepage         = 'https://github.com/cheind/dest'
  s.license          = { :type => 'BSD', :file => 'LICENSE' }
  s.author           = { 'cheind' => 'christoph.heindl@gmail.com' }
  s.source           = { :git => 'https://github.com/cheind/dest.git', :tag => "v0.8" }

  s.ios.deployment_target = '8.0'

  s.source_files = 'dest/Classes/**/*'

end`

But I have  'ArgumentError - Malformed version number string v0.8' error
