### ISSUE TITLE
pod try BEMCheckBox stacktrace

### ISSUE THREAD

**Issue by mwbgrob** [CocoaPods/CocoaPods#9415] opened 2019-12-17 11:29 UTC
### Command

```
/usr/local/bin/pod try BEMCheckBox
```

### Report

* What did you do?

pod try BEMCheckBox

* What did you expect to happen?

* What happened instead?

Stack trace

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment] 2019-12-17 17:57
Duplicate of https://github.com/CocoaPods/cocoapods-try/issues/63 and yes this is a bug and a known issue.

**Closed by dnkoutso** 2019-12-17 17:57 UTC
