### ISSUE TITLE
Permanent no-integrate (Carthage) mode

### ISSUE THREAD

**Issue by andreyvit** [CocoaPods/CocoaPods#4431] opened 2015-10-23 07:39 UTC
The advent of `use_frameworks!` means that very often, integration can boil down to adding the frameworks to the Embedded Binaries section of the project file. All the complicated stuff CocoaPods adds (configuration files, build steps) isn't really needed, and I'd really prefer to keep it out of my projects.

Would be nice to have CocoaPods:

* (best option) add to Embedded Binaries automatically and skip the other integration steps
* (also acceptable) do nothing (i.e. skip integration via an option in `Podfile`)
* (nice addition) warn if a pod requires additional build settings beyond what's possible to put into a framework

I think the relative popularity of Carthage shows that there's a demand for such a mode. Besides, don't we all want CocoaPods to be as unobtrusive as possible?

Here's a workaround I use right now:

* create a workspace with an additional dummy project that CocoaPods integrates with
* manually add CocoaPods-provided frameworks to the real project

**Comment by orta** [comment] 2015-10-23 07:41
We have [CocoaPods-Rome](https://github.com/neonichu/Rome/) which can do this for you. Other than that this is mostly a duplicate of https://github.com/CocoaPods/CocoaPods/issues/3589 so I'm closing it  I'm afraid.

**Closed by orta** 2015-10-23 07:41 UTC

**Comment by andreyvit** [comment] 2015-10-23 07:44
@orta Awesome, thank you!
