### ISSUE TITLE
pod install or update error, not work on Xcode 7

### ISSUE THREAD

**Issue by hit1983** [CocoaPods/CocoaPods#4209] opened 2015-09-18 11:24 UTC
Hi,
I am trying to execute pod install or update with Xcode 7, there is an error occur:

  
[MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8227/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x1040e30c0>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x000000010462aa5c -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x000000010462a1e9 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010462a455 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000010462a3b7 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x0000000107191f5c IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x0000000109da8eb9 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x0000000109daaa3e +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff8bc68f44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6

**Comment by segiddins** [comment] 2015-09-18 11:59
What version of CocoaPods and Xcodeproj are you using? This should've been fixed in the latest several versions of xcodeproj.

**Comment by zxcq99** [comment] 2015-09-18 18:50
Got same issue. I use CocaPods 0.36.0 and Xcodeproj 0.27.2

**Comment by hanluner** [comment] 2015-09-19 10:03
I got the same problem.

**Comment by neonichu** [comment] 2015-09-19 11:09
This is a dupe of  #3829 — you have to update to the right version of Xcodeproj for this to work.

**Closed by neonichu** 2015-09-19 11:09 UTC

**Comment by stephanebruckert** [comment] 2015-09-23 20:47
You need to update Cocoapod:

    sudo gem install cocoapods

**Comment by aksswami** [comment] 2015-09-24 04:11
I have updated my cocoapods(0.38.2) gem and xcodeproj(0.27.2), but still getting error:-
```
- Writing Xcode project file to `Pods/Pods.xcodeproj`
2015-09-24 09:40:27.969 ruby[12098:428715] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8227/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fb9adbd99d0>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x000000011038ca5c -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x000000011038c1e9 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000011038c455 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000011038c3b7 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x00000001118c5f5c IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000011451deb9 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x000000011451fa3e +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff8da7df44 ffi_call_unix64 (in libffi.dylib)
[1]    12098 abort      pod install --verbose
```

**Comment by Feanore** [comment] 2015-09-24 12:01
Сocoapods(0.38.2) gem and xcodeproj(0.27.2)
Also getting this error

2015-09-24 17:58:17.944 ruby[55544:1638355] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8227/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fbfbc549f10>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x000000010d5fea5c -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x000000010d5fe1e9 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010d5fe455 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000010d5fe3b7 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x000000010f2c5f5c IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x0000000111edceb9 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x0000000111edea3e +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff8e5c7f44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6

**Comment by segiddins** [comment] 2015-09-24 15:05
What version of Xcode are you using, @Feanore & @aksswami ?

**Comment by zxcq99** [comment] 2015-09-24 18:01
I had same issue because I had both Xcode 6.4 and 7 installed next to each other. Nothing was helping until I changed xcode's path using xcode-select and set it to Xcode 6.4.

**Comment by aksswami** [comment] 2015-09-26 11:24
I was able tot solve the problem by removing everything related to cocoapods(All cocoapods gem) and than reinstalling latest cocoapod. But I didn't understand what was the problem. Previously also I updated my cocoapod.

Some steps which helped me solve my problem:-
- run 'gem list --local | grep cocoapods' to find all cocoa pods installed on machine
- 'gem uninstall' everything returned by step2 
- '[sudo] gem uninstall cocoapods'
- '[sudo] gem install cocoapods'

Hope it help someone else. (I am using XCode 7 GM)

**Comment by FrantzdyRomain** [comment] 2015-09-27 02:01
I ran 'sudo gem uninstall cocoapods"
and then
'sudo gem install cocoapods'
i am running 7.1 beta

**Comment by iphone4peru** [comment] 2015-09-28 20:41
that is the correct way
uninstall cocoapods gems (all) , at terminal $ sudo gem uninstall cocoapods
then
$ sudo gem install cocoapods
then
$ pod init
then 
edit Podfile using textedit for example 
(paste at the endline:
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps')

then at terminal finish 
$ pod install

thank you for your help to everyone in this list

**Comment by coreygoodermote** [comment] 2015-10-28 20:41
Getting the following on pods 0.39.0, xcodeproj 0.28.2, and Xcode 7.1. I've tried uninstalling and reinstalling to no avail. 

Generating Pods project
2015-10-28 16:38:39.152 ruby[1523:12722] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-9079/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7ff0bb9fa450>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x0000000109dd5f96 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x0000000109dd5723 _DVTAssertionHandler (in DVTFoundation)
  2  0x0000000109dd598f _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x0000000109dd58f1 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x000000010ba456fd IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000010e278081 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x000000010e279c06 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff86ee3f44 ffi_call_unix64 (in libffi.dylib)

**Comment by segiddins** [comment] 2015-10-29 01:22
What build of Xcode are you running? This should all be fixed, so please open a new issue over on Xcodeproj if you can reliably reproduce this.

**Comment by zinwalin** [comment] 2015-11-11 09:34
gem install xcodeproj -v 0.24.3   
it works for me.

**Comment by shehabic** [comment] 2015-11-29 19:34
I have the same issue,  Xcode 7.1, Cocoapods 0.36, xcodeproj. 0.28.2 

Downloading dependencies
Installing AFNetworking 2.6.3 (was 2.5.4)
Installing CarbonKit 2.0.0 (was 1.1.2)
Using MBProgressHUD (0.9.1)
Using MMDrawerController (0.6.0)
Using XLPagerTabStrip (1.1.1)
Generating Pods project
2015-11-29 20:33:14.426 ruby[41480:4223687] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-9079/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7f9b4cb22460>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x000000010deccf96 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x000000010decc723 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010decc98f _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000010decc8f1 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x000000010fb3f6fd IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000011231a081 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x000000011231bc06 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff9138ef44 ffi_call_unix64 (in libffi.dylib)
[1]    41480 abort      pod update
