### ISSUE TITLE
Changing PRODUCT_NAME variable breaks the pod installation

### ISSUE THREAD

**Issue by mjstelly** [CocoaPods/CocoaPods#8480] opened 2019-02-02 03:21 UTC
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Apple required us to change the `PRODUCT_NAME` variable from `mobile_gtm` to `Seek Health`. This change broke the build. I tried running `pod install` to fix it.

## What did you expect to happen?
I expected the pods to get updated.

## What happened instead?

I received the error message which included this template.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 10b4c460ec39be7af40e6af180fd510484dc4f0f
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Seek Health' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for Seek Health
  pod 'FBSDKCoreKit', '4.38.0'
  pod 'FacebookSDK', '4.38.0'
  pod 'FBSDKShareKit', '4.38.0'
  pod 'FBSDKLoginKit', '4.38.0'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

end
```

## Project that demonstrates the issue
The project is private. I cannot link it to a public site.

**Comment by mjstelly** [comment] 2019-02-02 03:33
I changed PRODUCT_NAME in the `info.plist` 
```
<string>Seek Health</string>
```
In contents.xcworkspacedata`
```
<FileRef
      location = "group:/Users/michael.stelly/Documents/projects/mobile_gtm/ios/Seek Health.xcodeproj">
   </FileRef>```
and in `xschememanagement.plist`
```
<key>Pods-Seek Health.xcscheme_^#shared#^_</key>
```

**Comment by dnkoutso** [comment] 2019-02-02 03:38
But that is your own app not the generated one by Pods. What is error message?

**Comment by mjstelly** [comment] 2019-02-02 03:39
Cocoapods obviously couldn't handle a two-word name change 
```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "remoteInfo", found "H"
   #  -------------------------------------------
   #                    proxyType = 1;
   #                    remoteGlobalIDString = 13B07F861A680F5B00A75B9A;
118>                    remoteInfo = Seek Health;
```

**Comment by dnkoutso** [comment] 2019-02-02 03:46
Now we are getting somewhere...

Can you wrap that value with quotes `""` if it has a space it needs to be. You can edit your xcodeproj directly.

**Comment by mjstelly** [comment] 2019-02-02 03:55
There are 54 references to the name in that file: one commented reference for every one like `path = "Seek Health.app";` Is there a base reference in that file or in the app which can update all of them. If I can find the base reference for PRODUCT_NAME and correct that, will the change propagate throughout the app?

**Comment by dnkoutso** [comment] 2019-02-02 03:59
I dunno it is your project. You can use find/replace easily I am sure.

@mjstelly at this point I do not think this is a CocoaPods issue. Yes it is an integration issue and the message clearly says where the problem is. 

I am going to preemptively close this issue and I will re-open only if we can find a bug within CocoaPods library.

**Closed by dnkoutso** 2019-02-02 03:59 UTC
Labels: s1:awaiting input
