### ISSUE TITLE
Recommended Practice for spec naming of an Objective-C and Swift library variant

### ISSUE THREAD

**Issue by cvasilak** [CocoaPods/CocoaPods#3025] opened 2015-01-09 13:45 UTC
Hi all and thank you for the hard work to bring Swift support!

Currently we are in a process of releasing a podspec for Swift variant version of an obj-c library. I would like to ask if there is a recommended approach for naming a podspec if a library exists in both worlds.

In particular currently the name of our spec for the obj-c version is as the following
```
 s.name         = "AeroGear-Push"
```
whereas I declared for the Swift version the following:

```
 s.name         = "AeroGear-Push-Swift'
 s.module_name  = "AeroGearPush"
```

This will allow when browsing the cocoapods.org site for the library to come up in both versions that is:

```
AeroGear-Push
AeroGear-Push-Swift
```

but as far as a user is concerned when using the Swift version (and because the ``` s.module_name```  directive), to import the library as:

```
import AeroGearPush
```

This works great from my tests but would like to ask if that is the recommended approach or there is something else that I possible miss.

Keep up the good work!

**Comment by orta** [comment] 2015-01-09 14:19
Closing as duplicate of https://github.com/CocoaPods/CocoaPods/issues/3016

**Closed by orta** 2015-01-09 14:19 UTC
