### ISSUE TITLE
Updated xcodeproject generates generic archive

### ISSUE THREAD

**Issue by mark2b** [CocoaPods/CocoaPods#4160] opened 2015-09-10 20:30 UTC
After updating to CocoaPods 0.39.0.beta.4, Xcode Build Archive builds generic archive (can not be uploaded to AppStore)
Rolling back to release 0.38 fix it

**Comment by segiddins** [comment] 2015-09-10 21:13
This is a known issue with beta 4.

**Comment by ZuYuanZhou** [comment] 2015-09-11 03:05
My god, struggle several hours in this issue...

**Comment by neonichu** [comment] 2015-09-11 10:03
Closing as a duplicate of #4119

**Closed by neonichu** 2015-09-11 10:03 UTC
