### ISSUE TITLE
iOS Pod not installing using react native terminal

### ISSUE THREAD

**Issue by CRupesh** [CocoaPods/CocoaPods#10760] opened 2021-07-05 13:29 UTC
Hello guys,
I am facing some weird issue while doing pod install. Not sure whats going wrong. I've been trying multiple ways to fix this issue by clearing npm caches or by upgrading cocoapods and pod projects too and etc. but not that lucky to resolve this issue.

JSON::ParserError - 767: unexpected token at '{
  "name": "SDWebImage",
  "version": "5.7.2",
  "platforms": {
    "osx": "10.10",
    "ios": "8.0",
    "tvos": "9.0",
    "watchos": "2.0"
  },
  "license": "MIT",
  "summary": "Asynchronous image downloader with cache'

My react native version is 
react-native-cli: 2.0.1
react-native: 0.64.2

And my Xcode version is 12.5.1 (12E507)

Please help!!!

**Comment by paulb777** [comment] 2021-07-05 14:44
Possible duplicate of #10640.  Please follow the issue template if you need additional help.

**Comment by dnkoutso** [comment] 2021-07-05 18:49
What @paulb777 , try `rm -rf ~/.cocoapods/repos` and try again.

**Closed by dnkoutso** 2021-07-05 18:49 UTC

**Comment by CRupesh** [comment] 2021-07-06 05:52
> What @paulb777 , try `rm -rf ~/.cocoapods/repos` and try again.

Thanks @dnkoutso , it worked :)
