### ISSUE TITLE
Please provide support for linting multiple pods at the same time

### ISSUE THREAD

**Issue by Buju77** [CocoaPods/CocoaPods#3663] opened 2015-06-09 13:02 UTC
Sometimes we are working on 2 or more separate internal pods in parallel. But when we try to lint both pods at the same time to save us some time, both linting will fail.

So currently we have to lint the pods in sequence one after another. This obviously takes up some time because we have many pods.

Does `pod lib lint` use some kind of shared temp folder? Would be nice if each pod lib lint has its own temp folder so we can lint multiple pods in parallel.

**Comment by segiddins** [comment] 2015-06-09 17:56
Can you please share a reproduction script to demonstrate the failures so we can investigate?

**Comment by Buju77** [comment] 2015-06-09 20:24
hmm its pretty hard to provide example projects to demonstrate it. both of our linting pods have dependency to other internal pods. and I don't want to share our code here ;)

have to think of a good way to provide example projects.

**Comment by segiddins** [comment] 2015-07-05 20:05
Closing due to lack of reproduction steps.

**Closed by segiddins** 2015-07-05 20:05 UTC
Labels: s1:awaiting input
