### ISSUE TITLE
XCode 6.3 "No such module"

### ISSUE THREAD

**Issue by sarunw** [CocoaPods/CocoaPods#3128] opened 2015-02-10 07:07 UTC
I try Swift In XCode 6.3 with pod version 0.36.0.beta.2 when I try to install `Facebook-iOS-SDK` pod  and `import FacebookSDK` in the project it show up this message `No such module 'FacebookSDK` seem its not compatible with XCode 6.3 beta.

**Comment by orta** [comment] 2015-02-10 17:28
Dupe of https://github.com/CocoaPods/CocoaPods/issues/3106

**Closed by orta** 2015-02-10 17:28 UTC
