### ISSUE TITLE
fatal: unable to access Specs.git

### ISSUE THREAD

**Issue by dumoko** [CocoaPods/CocoaPods#6053] opened 2016-10-18 13:11 UTC
- [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

We're trying to use a new pod, therefore we're trying to run `pod repo update`
## What happened?

```
=> pod repo update
  Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
  fatal: unable to access 'https://github.com/CocoaPods/Specs.git/': transfer closed with outstanding read data remaining
```

It happens all the day. What is the issue?

**Comment by jshier** [comment] 2016-10-18 16:53
Yes, the specs repo is especially slow right now, and has been since last night. Finally time to move to sharded version?

**Comment by singcodes** [comment] 2016-10-19 03:15
I testing just with 'git clone https://github.com/CocoaPods/Specs.git'. 
It's not working too.

**Comment by andyyhope** [comment] 2016-10-19 03:30
Having the same issue.
`pod repo update --verbose`

```
Updating spec repo `master`
  $ /usr/bin/git -C /Users/andyyhope/.cocoapods/repos/master pull --ff-only
  fatal: unable to access 'https://github.com/CocoaPods/Specs.git/': transfer closed with outstanding read data remaining
```

**Comment by chrisdhaan** [comment] 2016-10-19 07:09
Im having the same issue. Have tried completely uninstalling and reinstalling. Any updates?

**Comment by qooarleo** [comment] 2016-10-19 07:29
Same here, any update?

**Comment by bahadiraurea** [comment] 2016-10-19 09:24
Any update please?

**Comment by orta** [comment] 2016-10-19 09:34
Sharding the repo will bring down the stress on GitHub's servers ( as we mentioned in the [blog post](http://blog.cocoapods.org/Master-Spec-Repo-Rate-Limiting-Post-Mortem/) ) but it's a destructive move to both the Specs repo and the trunk db - which also forces _everyone_ to migrate to 1.x versions of CocoaPods. So we don't want rush that.

Ideally, once we're sure that the the sharing has gone successfully, we can also look at reducing the amount of commits on the main branch, meaning that the commits transferred should be reduced.

We were planning on doing this post-1.1.0, https://github.com/CocoaPods/trunk.cocoapods.org/pull/187 - that's taking long than expected, however it should be very soon. No-one works full time on CocoaPods.

WRT the timeouts only GitHub staff know the actual reason for why they are timing out I'm afraid.

**Comment by andyyhope** [comment] 2016-10-19 09:38
Thanks Orta!

**Comment by primax79** [comment] 2016-10-19 10:46
i think that the problem is related to this

https://github.com/CocoaPods/CocoaPods/issues/4989#issuecomment-193772935

**Comment by bahadiraurea** [comment] 2016-10-19 11:00
Thanks orta hope it will be resolved asap

**Comment by benasher44** [comment] 2016-11-07 21:07
Just a heads up that this is happening soon!

http://blog.cocoapods.org/Sharding/

Cheers!

**Comment by orta** [comment] 2016-11-17 10:00
And has happened 👍

**Closed by orta** 2016-11-17 10:00 UTC
