### ISSUE TITLE
Error on command 'Pod Install'

### ISSUE THREAD

**Issue by IBRAHIMBNC** [CocoaPods/CocoaPods#12113] opened 2023-10-26 07:15 UTC
### Command

```
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.13.0
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.6 (22G120)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '13.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['SWIFT_VERSION'] = '5'
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def flutter_root
  generated_xcode_build_settings_path = File.expand_path(File.join('..', 'Flutter', 'Generated.xcconfig'), __FILE__)
  unless File.exist?(generated_xcode_build_settings_path)
    raise "#{generated_xcode_build_settings_path} must exist. If you're running pod install manually, make sure flutter pub get is executed first"
  end

  File.foreach(generated_xcode_build_settings_path) do |line|
    matches = line.match(/FLUTTER_ROOT\=(.*)/)
    return matches[1].strip if matches
  end
  raise "FLUTTER_ROOT not found in #{generated_xcode_build_settings_path}. Try deleting Generated.xcconfig, then run flutter pub get"
end

require File.expand_path(File.join('packages', 'flutter_tools', 'bin', 'podhelper'), flutter_root)

flutter_ios_podfile_setup

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  pod 'FirebaseFirestore', :git => 'https://github.com/invertase/firestore-ios-sdk-frameworks.git', :tag => '10.12.0'
  flutter_install_all_ios_pods File.dirname(File.realpath(__FILE__))
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    flutter_additional_ios_build_settings(target)
    target.build_configurations.each do |config|

      # You can enable the permissions needed here. For example to enable camera
      # permission, just remove the `#` character in front so it looks like this:
      #
      # ## dart: PermissionGroup.camera
      # 'PERMISSION_CAMERA=1'
      #
      #  Preprocessor definitions can be found in: https://github.com/Baseflow/flutter-permission-handler/blob/master/permission_handler_apple/ios/Classes/PermissionHandlerEnums.h
      config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= [
        '$(inherited)',

        ## dart: PermissionGroup.calendar
        # 'PERMISSION_EVENTS=1',

        ## dart: PermissionGroup.reminders
        # 'PERMISSION_REMINDERS=1',

        ## dart: PermissionGroup.contacts
        # 'PERMISSION_CONTACTS=1',

        ## dart: PermissionGroup.camera
        'PERMISSION_CAMERA=1',

        # dart: PermissionGroup.microphone
        'PERMISSION_MICROPHONE=1',

        ## dart: PermissionGroup.speech
        # 'PERMISSION_SPEECH_RECOGNIZER=1',

        ## dart: PermissionGroup.photos
        # 'PERMISSION_PHOTOS=1',

        ## dart: [PermissionGroup.location, PermissionGroup.locationAlways, PermissionGroup.locationWhenInUse]
        # 'PERMISSION_LOCATION=1',

        ## dart: PermissionGroup.notification
        # 'PERMISSION_NOTIFICATIONS=1',

        ## dart: PermissionGroup.mediaLibrary
        # 'PERMISSION_MEDIA_LIBRARY=1',

        ## dart: PermissionGroup.sensors
        # 'PERMISSION_SENSORS=1',   

        ## dart: PermissionGroup.bluetooth
        # 'PERMISSION_BLUETOOTH=1',

        ## dart: PermissionGroup.appTrackingTransparency
        # 'PERMISSION_APP_TRACKING_TRANSPARENCY=1',

        ## dart: PermissionGroup.criticalAlerts
        # 'PERMISSION_CRITICAL_ALERTS=1'
      ]

    end 
    # End of the permission_handler configuration
  end
  installer.generated_projects.each do |project| 
    project.targets.each do |target| 
      target.build_configurations.each do |config| 
        config.build_settings["DEVELOPMENT_TEAM"] = "49P6QGXPCL" 
      end
    end
  end
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/ibrahimnisar/.cocoapods/repos/trunk/Specs/1/d/9/AgoraRtcEngine_iOS/4.2.3/AgoraRtcEngine_iOS.podspec.json'.

unexpected token at ''
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification.rb:752:in `from_string'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification.rb:726:in `from_file'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/source.rb:188:in `specification'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification/set.rb:56:in `each'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/cdn_source.rb:216:in `search'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-core-1.13.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:165:in `search_for'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:267:in `each'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:267:in `sort_by'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:267:in `sort_by!'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/resolver.rb:94:in `resolve'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:422:in `analyze'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/user_interface.rb:64:in `section'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/installer.rb:162:in `install!'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command/install.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/lib/cocoapods/command.rb:52:in `run'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/gems/cocoapods-1.13.0/bin/pod:55:in `<top (required)>'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/bin/pod:25:in `load'
/opt/homebrew/Cellar/cocoapods/1.13.0/libexec/bin/pod:25:in `<main>'
```

**Comment by fernandoths98** [comment] 2023-10-26 08:37
the same as the issue I am currently experiencing

**Comment by vpotapchik** [comment] 2023-10-26 09:15
have the same issue: 
JSON::ParserError - Failed to parse JSON at file: '/Users/valera/.cocoapods/repos/trunk/Specs/4/e/9/AppLovinMediationVungleAdapter/7.1.0.1/AppLovinMediationVungleAdapter.podspec.json'.

unexpected token at ''

CocoaPods : 1.13.0
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 14.0 (23A344)
       Xcode : 15.0.1 (15A507)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2_1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs @ d92af6d5e34d204a95d31f23718886b6d67ee952

               trunk - CDN - https://cdn.cocoapods.org/

**Comment by vpotapchik** [comment] 2023-10-26 09:54
I checked the file where the error occurs on my machine. The file is empty. When updating the cocoapods repository, the contents of the file are not downloaded.
For my project I fixed this by commenting out the source line 'https://cdn.cocoapods.org/' in the PodFile of the project.

**Comment by IBRAHIMBNC** [comment] 2023-10-26 10:04
> I checked the file where the error occurs on my machine. The file is empty. When updating the cocoapods repository, the contents of the file are not downloaded. For my project I fixed this by commenting out the source line 'https://cdn.cocoapods.org/' in the PodFile of the project.
> 
> #source 'https://cdn.cocoapods.org/' source 'https://github.com/CocoaPods/Specs.git'
> 
> platform :ios, '12.0'

**Comment by IBRAHIMBNC** [comment] 2023-10-26 10:06
there is no such line  'https://cdn.cocoapods.org/' is my Podfile

**Comment by vpotapchik** [comment] 2023-10-26 10:09
@IBRAHIMBNC  can you try to add "source 'https://github.com/CocoaPods/Specs.git'" to your file?

**Comment by fernandoths98** [comment] 2023-10-26 10:18
the same error and then this is my error from pod install on my mac m1 : 

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/apple/.rbenv/versions/3.1.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.14.0
        Ruby : ruby 3.1.4p223 (2023-03-30 revision 957bb7cb81) [arm64-darwin22]
    RubyGems : 3.3.26
        Host : macOS 13.0 (22A380)
       Xcode : 14.3.1 (14E300c)
         Git : git version 2.39.2 (Apple Git-143)
Ruby lib dir : /Users/apple/.rbenv/versions/3.1.4/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'my_crm' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  pod 'Firebase', :modular_headers => true
      pod 'FirebaseCore', :modular_headers => true
      pod 'GoogleUtilities', :modular_headers => true
      $RNFirebaseAsStaticFramework = true

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'my_crmTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

### Error

```
JSON::ParserError - Failed to parse JSON at file: '/Users/apple/.cocoapods/repos/trunk/Specs/0/b/5/PromisesObjC/2.3.1/PromisesObjC.podspec.json'.

859: unexpected token at ''
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/json.rb:66:in `rescue in from_json'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification.rb:752:in `from_string'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification.rb:726:in `from_file'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source.rb:188:in `specification'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:56:in `each'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-core-1.14.0/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `each'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_by!'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:60:in `block in sort_dependencies'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:77:in `with_no_such_dependency_error_handling'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/delegates/specification_provider.rb:59:in `sort_dependencies'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:744:in `require_nested_dependencies_for'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:727:in `activate_new_spec'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:684:in `attempt_to_activate'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolution.rb:182:in `resolve'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/molinillo-0.8.0/lib/molinillo/resolver.rb:43:in `resolve'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:1082:in `block in resolve_dependencies'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:1080:in `resolve_dependencies'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/installer/analyzer.rb:125:in `analyze'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:422:in `analyze'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:244:in `block in resolve_dependencies'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:243:in `resolve_dependencies'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/installer.rb:162:in `install!'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/lib/cocoapods/command.rb:52:in `run'
/Users/apple/.rbenv/versions/3.1.4/lib/ruby/gems/3.1.0/gems/cocoapods-1.14.0/bin/pod:55:in `<top (required)>'
/Users/apple/.rbenv/versions/3.1.4/bin/pod:25:in `load'
/Users/apple/.rbenv/versions/3.1.4/bin/pod:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by orta** [comment] 2023-10-26 10:29
Probably a dupe of https://github.com/CocoaPods/CocoaPods/issues/12110

**Closed by orta** 2023-10-26 10:29 UTC
