### ISSUE TITLE
RuntimeError - [Xcodeproj] Consistency issue: build setting `SDKROOT` has multiple values: `{"Debug"=>"iphoneos10.0", "Release"=>"iphoneos"}`

### ISSUE THREAD

**Issue by pbojinov** [CocoaPods/CocoaPods#6495] opened 2017-02-20 00:49 UTC
# Report

## What did you do?

Run `pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

A RuntimeError occurred.

### Error

```
RuntimeError - [Xcodeproj] Consistency issue: build setting `SDKROOT` has multiple values: `{"Debug"=>"iphoneos10.0", "Release"=>"iphoneos"}`
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object/native_target.rb:79:in `common_resolved_build_setting'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object/native_target.rb:86:in `sdk'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project/object/native_target.rb:92:in `platform_name'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/target_mapper.rb:27:in `block (2 levels) in pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/target_mapper.rb:20:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb:36:in `block (2 levels) in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0/lib/cocoapods_plugin.rb:32:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:109:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:109:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:101:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/hooks_manager.rb:100:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:493:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:472:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:121:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6453485567380e73347ac512e2408671f09a547a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
 platform :ios, '9.3'

target '[REDACTED]' do
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
use_frameworks!

  # Pods for [REDACTED]

pod 'UIScrollView-InfiniteScroll'
pod 'Firebase/Core'
pod 'Firebase/Storage'
pod 'Firebase/Database'
pod 'Firebase/Auth'
pod 'Firebase/RemoteConfig'
pod 'Fabric'
pod 'Crashlytics'
pod 'GoogleSignIn'

# Your 'node_modules' directory is probably in the root of your project,
# but if not, adjust the `:path` accordingly
pod 'React', :path => 'node_modules/react-native', :subspecs => [
'Core',
'RCTActionSheet',
'RCTAnimation',
'RCTCameraRoll',
'RCTGeolocation',
'RCTImage',
'RCTNetwork',
'RCTPushNotification',
'RCTSettings',
'RCTText',
'RCTVibration',
'RCTLinkingIOS',
'RCTWebSocket', # needed for debugging
'RCTTest'
# Add any other subspecs you want to use in your project
]

end
```

**Comment by pbojinov** [comment] 2017-02-20 00:50
When I look at my build settings, they are set to 9.3, which matches the platform in the podfile. Any idea how to change the build setting `SDKROOT` to prevent the multiple values?

**Comment by benasher44** [comment] 2017-03-26 16:55
@pbojinov ah so it's likely that one of the pods / subspecs you added has added a build setting like this. You'll have to go through each of the pods in your Podfile, look at their specs, and see which of them has added `xcconfig`, `user_target_xcconfig`, or `pod_target_xcconfig` settings that match the settings in the error you're seeing. You can also try adding and removing different pods from your Podfile to see if you can narrow it down to a specific set of pods that's causing the issue to help your search.

I'm going to close this, since this isn't an issue that we would fix by patching CocoaPods, and this is more of an error caused by an unfortunate combination of pods. Apologies for the delayed response, and have a great day!

**Closed by benasher44** 2017-03-26 16:55 UTC
