### ISSUE TITLE
[Feature Support]On-Demand Resource

### ISSUE THREAD

**Issue by JunyiXie** [CocoaPods/CocoaPods#9621] opened 2020-03-18 09:06 UTC
[Feature Request] On-Demand Resource Support  https://github.com/CocoaPods/CocoaPods/issues/9606

PR:
https://github.com/CocoaPods/CocoaPods/pull/9620

depand on 
Core: https://github.com/CocoaPods/Core/pull/622
Xcodeproj: https://github.com/CocoaPods/Xcodeproj/pull/742

**Comment by dnkoutso** [comment] 2020-04-03 07:06
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9606 No need for separate issue.

**Closed by dnkoutso** 2020-04-03 07:06 UTC
Labels: t1:enhancement
