### ISSUE TITLE
"can't locate file for: -lc++" build error with cocoapods 0.34.4

### ISSUE THREAD

**Issue by lyahdav** [CocoaPods/CocoaPods#2704] opened 2014-10-20 19:25 UTC
We recently tried upgrading from cocoapods 0.34.2 to 0.34.4. After upgrading, running `pod install` works fine, but then trying to build our app gives this error on a static library project:
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lc++
error: /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lc++ is not an object file (not allowed in a library)

If we downgrade to 0.34.2 it fixes the issue. What's weird is the -lc++ flag still exists when using 0.34.2, just for some reason the build doesn't error out. My guess is that the latest cocoapods is changing some other build settings that cause this issue.

Looking at the changelog, if I had to guess, I'd say it's due to the commit for https://github.com/CocoaPods/CocoaPods/issues/2666.

**Comment by michaelmelanson** [comment] 2015-01-16 19:43
I'm seeing issue #2904 (a duplicate of this one) in my setup. I've created a pod which depends on CocoaHTTPServer (links with `-lxml2`) and SSZipArchive (links with `-lz`), among other pods that don't matter here.

I include that pod in a project's Podfile via a `podspec` line in the main target. This target produces a static library, and I get the same errors that @paolonl reported, only for `libxml2` and `libz`. The project's `Pods-ProjectName.debug.xcconfig` (and `.release`) files contains `-l"xml2" -l"z"`. Removing them manually fixes the errors, but that's a bad workaround.

I have a second project, an iOS application, which includes the same pod. It can do so just fine (because the `.app` target is dynamically linked).

**Comment by Sivasuthan** [comment] 2015-02-21 02:07
I have the same issue as lyahdav all work 0.34.2 but its not working if I upgrade. Does anyone have proper solutions? Thanks

**Comment by gagarwal** [comment] 2015-03-26 19:42
Any update on this issue. I am using Cocoapods v0.36.0 and still the same issue with my Static Library target.

**Comment by danie11am** [comment] 2015-03-31 02:59
In a project of mine, the whole team stays in 0.34.1 because of this issue.

**Comment by themackworth** [comment] 2015-04-02 17:34
@Sivasuthan @gagarwal @danie11am If any of you have the time, check out https://github.com/CocoaPods/CocoaPods/issues/2747#issuecomment-68267620 for what works needs to be done to fix this.  The only thing that looks annoying is fixing the integration tests.

**Comment by atmikev** [comment] 2015-06-04 17:38
Any updates?

**Comment by knox** [comment] 2015-06-10 10:30
This workaround works for me

    post_install do |installer|
    
      support_files_group = installer.project.support_files_group.groups[0]
      source_tree = File.join(installer.sandbox_root, support_files_group.path) 
    
      support_files_group.files.each do |file|
    
        next unless file.path.end_with?('.xcconfig')
        xcconfig_path = File.join(source_tree, file.path)
        xcconfig = File.read(xcconfig_path)
        newXcconfig = xcconfig.gsub(/\ -l"stdc\+\+"/, '')
        File.open(xcconfig_path, "w") { |file| file << newXcconfig }
    
      end
    
    end

**Comment by rgal75** [comment] 2015-06-10 15:11
We had to remain on version 0.34.2 due to this issue. However, today we realized that the min Cocoapods version has changed to 0.35.0.
Do you have any suggestions how to solve this "contradiction"? 0.34.2 is no more supported but 0.35.0 has this issue...

**Comment by neonichu** [comment] 2015-06-10 17:03
@rgal75 see [this comment](https://github.com/CocoaPods/Specs/issues/13170#issuecomment-110826335)

**Comment by segiddins** [comment] 2015-06-17 17:05
Closed by https://github.com/CocoaPods/CocoaPods/issues/3677.

**Closed by segiddins** 2015-06-17 17:05 UTC
Labels: t2:defect
