### ISSUE TITLE
Xcode generated warning to update the Pods project to use whole module optimization

### ISSUE THREAD

**Issue by Chris-Corea** [CocoaPods/CocoaPods#8063] opened 2018-08-30 19:16 UTC
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expect to happen?

I expected Xcode to not generate a warning suggesting to update the Pods project to use "recommended settings."

## What happened instead?

Xcode generated a warning suggesting to update the Pods project to use "recommended settings."  Specifically, in my Swift project, the suggestion is to enable whole module optimization (build setting `SWIFT_OPTIMIZATION_LEVEL`). 

### Stack

```
   CocoaPods : 1.6.0.beta.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ de1dc11533e59cac2cbdeb80d3a0fd4d7670f77a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.1'

target 'CocoaPods_TestProject' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for CocoaPods_TestProject
  pod 'SnapKit'
  pod 'XCGLogger'

end
```

## Project that demonstrates the issue

https://github.com/Chris-Corea/CocoaPods-Issue

**Comment by Chris-Corea** [comment] 2018-08-30 19:19
My issue describes the same issue as mentioned in #7944, however, aside from using `1.6.0.beta.1`, I thought it would be useful to mention that my xcodeproj version is 1.6.0.

```
› xcodeproj --version
1.6.0
```

**Comment by amorde** [comment] 2018-08-30 19:20
Thanks Chris! I'll try to repro with your sample project

**Comment by amorde** [comment] 2018-08-30 19:58
Looks like both Xcode 9 and Xcode 10 want this:

```
 'SWIFT_COMPILATION_MODE'            => '-Owholemodule',
```

but https://github.com/CocoaPods/Xcodeproj/pull/578 updated the settings to this:

```
 'SWIFT_COMPILATION_MODE'            => 'wholemodule',
 'SWIFT_OPTIMIZATION_LEVEL'          => '-O',
```

when I looked into #7944 I had it reversed. @segiddins any ideas on what's going on here? I can also repro this by creating a new project in the Xcode 10 beta.

**Comment by dnkoutso** [comment] 2018-08-30 20:56
I believe this is a dup of https://github.com/CocoaPods/CocoaPods/issues/7206

**Comment by amorde** [comment] 2018-08-30 23:07
Partially, but that was encompassing a lot of stuff that is now fixed

**Comment by segiddins** [comment] 2018-08-31 03:41
I generated the settings with the update from Xcode script, but it's possible the latest betas have changed the default

**Comment by amorde** [comment] 2018-08-31 04:01
Make sense

**Comment by amorde** [comment] 2018-09-01 23:32
Dug into this some more.

Both Xcode 9.4 and 10 use these settings when creating a new iOS app target or static library:

```
 'SWIFT_COMPILATION_MODE'            => 'wholemodule',
 'SWIFT_OPTIMIZATION_LEVEL'          => '-O',
```

but when creating a framework, it does this instead:

```
 'SWIFT_COMPILATION_MODE'            => '-Owholemodule',
```

still trying to figure out why it does so (I can't seem to find that in any of the project templates built into Xcode) but this feels like an Xcode bug to me. Swift 4.1 replaced `-Owholemodule` with a separate `-whole-module` flag (see [here](https://swift.org/blog/osize/)), and this is reflected in Xcode's `SWIFT_COMPILATION_MODE` setting.

So it seems that Xcode wants to stick with the old settings for frameworks only. You can test this by removing `use_frameworks!` in a Podfile that generating the warning, and the warning will go away

**Comment by dnkoutso** [comment] 2018-09-21 06:31
Should this still remain open?

**Comment by amorde** [comment] 2018-09-21 17:33
Checked again on Xcode 10, now the frameworks are behaving correctly but now Xcode wants the project itself to specify these settings. Will look into this some more

**Comment by amorde** [comment] 2018-09-21 23:59
Doesn't appear to happen in a fresh project - @Chris-Corea  can you confirm the issue no longer occurs on Xcode 10? (release build, 10A255)

**Comment by Chris-Corea** [comment] 2018-09-24 20:06
I can still reproduce this with Xcode 10 (release build, 10A255). Attached is a screenshot.

![screen shot 2018-09-24 at 1 03 24 pm](https://user-images.githubusercontent.com/1231808/45976094-ae315d00-bffa-11e8-9c26-d82c4132196f.png)

**Comment by amorde** [comment] 2018-09-24 20:43
darn, ok, will keep digging 😞

**Comment by amorde** [comment] 2018-09-28 06:06
I think I finally found the issue - PR incoming soon

**Comment by amorde** [comment] 2018-09-28 07:06
Confirmed that https://github.com/CocoaPods/Xcodeproj/pull/611 fixes the issue with your example project 🙌

**Closed** 2018-09-30 18:17 UTC
