### ISSUE TITLE
incompatible character encodings: UTF-8 and ASCII-8BIT when exec `pod search`

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#5338] opened 2016-05-16 13:15 UTC
Cocoapods 1.0.0, I run the command `pod search xxx`, I got a error: 
```
➜  pod search TBCalendar
bundler: failed to load command: pod (/Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/bin/pod)
Encoding::CompatibilityError: incompatible character encodings: UTF-8 and ASCII-8BIT
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface/error_report.rb:13:in `report'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:64:in `report_error'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/claide-1.0.0/lib/claide/command.rb:396:in `handle_exception'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/claide-1.0.0/lib/claide/command.rb:337:in `rescue in run'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/claide-1.0.0/lib/claide/command.rb:325:in `run'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/bin/pod:22:in `load'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/bin/pod:22:in `<top (required)>'
```

I check the code, and comment the rescue, I get the error:
```
➜  pod search TBCalendar
JSON::ParserError: 757: unexpected token at '()":["※ikemen"],"※":["※ikemen"],"{$0.text":["※ikemen"],"\"Name\"}":["※ikemen"],"🔒":["🔒"],"auth.":["🔒"],"🕕":["🕕"],"Büglingc":["🕕"]}}'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/json-1.8.3/lib/json/common.rb:155:in `parse'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source/manager.rb:251:in `stored_search_index'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source/manager.rb:187:in `updated_search_index'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-core-1.0.0/lib/cocoapods-core/source/manager.rb:118:in `search_by_name'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:87:in `local_search'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-search-1.0.0/lib/cocoapods-search/command/search.rb:63:in `run'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/bin/pod:22:in `load'
  /Users/whirlwind/.tbenv/1.0.0/vendor/bundle/ruby/2.1.0/bin/pod:22:in `<top (required)>'
```

How to do about it?

**Comment by segiddins** [comment] 2016-05-16 13:46
@manuyavuz looks like we might need to be more careful about string encoding in the cocoapods-search plugin.

**Comment by Whirlwind** [comment] 2016-05-17 02:39
I think that it is cocoapods-core when store index.

**Comment by manuyavuz** [comment] 2016-05-20 10:21
@Whirlwind could you share the contents of `~/Library/Caches/CocoaPods/search_index.json` file?

I've tried the same scenario but did not experience that kind of an error. I need to look into the contents of the json file.

**Comment by Whirlwind** [comment] 2016-05-23 06:57
[search_index.json.zip](https://github.com/CocoaPods/CocoaPods/files/276921/search_index.json.zip)
@manuyavuz

**Comment by manuyavuz** [comment] 2016-05-23 12:41
Interesting, you seem to have 3 spec repos with exact contents with the following names:

- master
- test-mirror
- alibaba-inc-specs-mirror

Are there really forks of master repo? If so, why do you need such a usage?

Other than that, the error seems to be caused from a weird copy paste behavior at the tail of the file:

```
"UILabel()":["※ikemen"],"※":["※ikemen"],"{$0.text":["※ikemen"],"\"Name\"}":["※ikemen"],"🔒":["🔒"],"auth.":["🔒"],"🕕":["🕕"],"Büglingc":["🕕"]}}()":["※ikemen"],"※":["※ikemen"],"{$0.text":["※ikemen"],"\"Name\"}":["※ikemen"],"🔒":["🔒"],"auth.":["🔒"],"🕕":["🕕"],"Büglingc":["🕕"]}}
```

Following part is repeated which causes invalid JSON:

```
()":["※ikemen"],"※":["※ikemen"],"{$0.text":["※ikemen"],"\"Name\"}":["※ikemen"],"🔒":["🔒"],"auth.":["🔒"],"🕕":["🕕"],"Büglingc":["🕕"]}}
```

Is there any chance where you accidentally manually copy/pasted the set of characters above? I see no way to programmatically generate such a JSON file with current code.

Also, could you try again by first deleting `~/Library/Caches/CocoaPods/search_index.json` file then running `pod search xxx` command again, and waiting until it finishes it's job?

**Comment by Whirlwind** [comment] 2016-05-24 06:34
It works after I delete the json and run the `pod search xx` !

I think it is because that last time I interrupt the build process over `Control + C`, then the CP build the json two times.

**Comment by manuyavuz** [comment] 2016-05-24 08:52
Can you send the output of `pod repo` here? I'll check if there is any anomaly in generated json file.

You don't need to send URLs, only names will suffice.

**Comment by manuyavuz** [comment] 2016-06-13 09:14
Closing for now because I can't reproduce this weird case myself, and your problem is solved.

**Closed by manuyavuz** 2016-06-13 09:14 UTC
Labels: s1:awaiting input

**Comment by chilli-cheng** [comment] 2016-07-29 07:25
nice, I solve the problem, thx

**Comment by yangzq007** [comment] 2017-05-26 02:47
delete the file `~/Library/Caches/CocoaPods/search_index.json` works
