### ISSUE TITLE
Unable to parse Podfile.lock error on Pod install/update

### ISSUE THREAD

**Issue by adarshroy** [CocoaPods/CocoaPods#7241] opened 2017-11-29 05:14 UTC
Not able to update/ install pods. 
Error is 'Unable to parse Podfile.lock file'
Last pod installed was:  pod 'googleapis', :path => '.' 
After that the issue started coming.

**Error Log** 

```
[!] ERROR: Parsing unable to continue due to parsing error:
contained in the file located at /Users/ios/Documents/Projects/DemoProject4/Podfile.lock
PODS:

!ProtoCompiler (3.0.2):
Protobuf (~> 3.0)
!ProtoCompiler-gRPCPlugin (1.0.2):
!ProtoCompiler (= 3.0.2)
gRPC-ProtoRPC (= 1.0.2)
Alamofire (4.5.1)
BoringSSL (7.0):
BoringSSL/Implementation (= 7.0)
BoringSSL/Interface (= 7.0)
BoringSSL/Implementation (7.0):
BoringSSL/Interface (= 7.0)
BoringSSL/Interface (7.0)
googleapis (0.0.1):
!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)
googleapis/Messages (= 0.0.1)
googleapis/Services (= 0.0.1)
googleapis/Messages (0.0.1):
!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)
Protobuf
googleapis/Services (0.0.1):
!ProtoCompiler-gRPCPlugin (~> 1.0.0-pre1.1)
googleapis/Messages
gRPC-ProtoRPC
gRPC (1.0.2):
gRPC-Core (= 1.0.2)
gRPC-RxLibrary (= 1.0.2)
gRPC-Core (1.0.2):
gRPC-Core/Implementation (= 1.0.2)
gRPC-Core/Interface (= 1.0.2)
gRPC-Core/Implementation (1.0.2):
BoringSSL (~> 7.0)
gRPC-Core/Interface (= 1.0.2)
gRPC-Core/Interface (1.0.2)
gRPC-ProtoRPC (1.0.2):
gRPC (= 1.0.2)
gRPC-RxLibrary (= 1.0.2)
Protobuf (~> 3.0)
gRPC-RxLibrary (1.0.2)
Protobuf (3.5.0)
DEPENDENCIES:

Alamofire
googleapis (from .)
EXTERNAL SOURCES:
googleapis:
:path: .

SPEC CHECKSUMS:
!ProtoCompiler: cfad9cbe5299a4923b1c3c8f150818c91efd0b6d
!ProtoCompiler-gRPCPlugin: ee00d28bb35b26e2657f239833b8f2aa66724f96
Alamofire: 2d95912bf4c34f164fdfc335872e8c312acaea4a
BoringSSL: 50035b9d9eeff5529587311782fc57c00ebf13ae
googleapis: daa20dca7a0097c6c3316fdfd888e0ba1b7c8921
gRPC: dd3a91e0fb770b9fc4f43d1292fb19f2a2e04158
gRPC-Core: cc4a7613190ff0bc60a0c1e702ef07cd3f868ae6
gRPC-ProtoRPC: 11533510522a5e9627883a597a796cfe6bef05f3
gRPC-RxLibrary: 02cc70b76bc0c5bc622ba27595cca2598d9fe528
Protobuf: 8a9838fba8dae3389230e1b7f8c104aa32389c03

PODFILE CHECKSUM: bba8f9c22e10518c7ea6f79ab0fb8177c097b5f5

COCOAPODS: 1.4.0.beta.2
```

**Comment by orta** [comment] 2017-11-29 19:07
Dupe of https://github.com/CocoaPods/CocoaPods/issues/6955

**Closed by orta** 2017-11-29 19:07 UTC
