### ISSUE TITLE
Linking with static lib containing c++ code fails in 1.1.1 but works in 0.39.0

### ISSUE THREAD

**Issue by johanlantz** [CocoaPods/CocoaPods#6155] opened 2016-11-10 22:04 UTC
I have a static lib that contains pure C and C++ files and I use cocoapods to manage it.

The user of this native lib is a objective-c library which is then in turn used by the App layer. So it looks like:

App
objective-c middleware
native-layer (C/C++)

The problem I am having today is publishing the middleware pod. I do the pod repo push of the native layer library and it works just fine. However when I do the same on the middleware layer the linking with the native layer fails.

ℹ Please replace this with what you did.  
- pod repo push of the C and C++ pod works fine.
- Linking in i386 when doing pod repo push for the middleware layer fails for the C++ functions in the native layer (I guess the symbol decoration might not be handled correctly, could some c++ flag be missing?).
- It works in 0.39.0 but not in 1.1.1 (I could confirm this thanks to the wonderful option of running pod _0.39.0_ pod repo push ...)

## What did you expect to happen?
My pod should be published using 1.1.1

## What happened instead?
When linking I got errors such as:
Undefined symbols for architecture i386:
  "operator new(unsigned long)", referenced from:
      rapidjson:: etc

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A320)
       Xcode : 8.1 (8B62)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : hi-yarn-tugo-specs - git@pdihub.hi.inet:yarn/tugo-specs.git @ a13fe33f4c972e049d92cb18ecbdc3ac6ddc9ba8
               hi-yarn-tugo-specs-1 - https://pdihub.hi.inet/yarn/tugo-specs.git @ 57e1387e8b50d6853effb2b29410c4aee5aac43e
               hi-yarn-tugo-specs-2 - https://pdihub.hi.inet/yarn/tugo-specs/ @ c1522858f7bf520af7a1d6ecee1238fa46ee34cb
               master - https://github.com/CocoaPods/Specs.git @ b86c1df19e85c019bfcabf5d56d18349f4eda174

## Project that demonstrates the issue
I do not have one I can share publicly at the moment.

**Comment by orta** [comment] 2016-11-17 09:52
I'd recommend `pod spec lint --no-clean` and looking inside the temp project folder to derive what is stopping the linter from passing on 1.x, or to create a small sample project that you can share with us.

**Comment by ntnmrndn** [comment] 2016-12-22 06:22
This sounds like a duplicate of https://github.com/CocoaPods/CocoaPods/issues/5152

**Comment by dnkoutso** [comment] 2017-02-04 07:47
This should be fixed by https://github.com/CocoaPods/CocoaPods/pull/6420

**Closed** 2017-02-05 17:27 UTC
Labels: s1:awaiting input
