### ISSUE TITLE
Xcode 7 archive "appstore" type iOS App, archive file will go to “Other items” tab

### ISSUE THREAD

**Issue by davidlin7876** [CocoaPods/CocoaPods#4228] opened 2015-09-21 07:49 UTC
0.39.0 beta4 is wrong,

0.38.2 is right

**Comment by SpacyRicochet** [comment] 2015-09-21 08:20
I'm having the same issue, so a couple of questions for things we can check together;

* Is it a Swift project?
* Are you supporting iOS 7?
* Are you using `use_frameworks!`

**Comment by danielgalasko** [comment] 2015-09-21 09:14
Take a look at #4021 , I had to rollback to beta 3. Wasn't working on 0.38.2 either

**Comment by SpacyRicochet** [comment] 2015-09-21 10:38
Going back to 0.38.2 fixed it for me, though I'm tangling with other issues now. 

@danielgalasko Why are you not using `use_frameworks!` if you target 8 and higher?

**Comment by danielgalasko** [comment] 2015-09-21 10:40
@SpacyRicochet because one of the Pods Im using has a dependency which uses a vendor static library:( Will look to try and get it installed without pods but I haven't gotten to that yet

**Comment by danielgalasko** [comment] 2015-09-21 10:40
FYI Apparently this is now fixed with #4217

**Comment by neonichu** [comment] 2015-09-21 12:43
Looks like this is a dupe of #4119

**Closed by neonichu** 2015-09-21 12:43 UTC
