### ISSUE TITLE
name of folder in private spec when use "pod update" at the first time

### ISSUE THREAD

**Issue by KeimyPlaza** [CocoaPods/CocoaPods#6427] opened 2017-01-19 15:48 UTC
Hi, first sorry that maybe it isn't a real bug, but i don't find the answer.

# Report

## What did you do?

I have a new clone project in local machine.
I will do a "pod update", because is the first time to execute this command before we use private specs repo

The private repo Specs are in https://www.miserver/project/Specs.git
In the podfile are the line " source 'https://www.miserver/project/Specs.git' " after cocoapods/Specs

Before execute "pod update" it pull Specs repo in  ~/.cocoapods/repos/miserver-project-specs folder

## What did you expect to happen?

We expect that de folder pulled in ~/.cocoapods/repos/ must be "Specs"

## What happened instead?

The folder was "miserver-project-specs"

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1217)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c4487c57270d1252a96b7fe063c2e66c71e1fccf
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '9.0'

source 'https://www.miserver/project/Specs.git'
source 'https://github.com/CocoaPods/Specs.git'

# Comment this line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

def pods_list

  # Pods for TestPrivate
  pod 'miframework'
  pod 'CocoaLumberjack/Swft'
  
end

target 'TestPrivate' do

  pods_list

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

**Comment by benasher44** [comment] 2017-01-19 16:47
Hi @KeimyPlaza! This is expected behavior: the specs repo having a name that's name-spaced based on the git URL. Is this causing a particular issue?

**Comment by KeimyPlaza** [comment] 2017-01-19 21:15
Hi @benasher44 thanks for your answer.

When you use command "pod repo add NAME URL [BRANCH]', you can set a NAME but if the "pod update" is adding the Spec in your repo, maybe can ask the NAME.

Maybe is a nice to have!!

Thanks you so much.

**Comment by benasher44** [comment] 2017-01-19 23:34
I'm not really sure what you mean. The NAME argument is so that you can refer to in in future pod commands, but the name of the folder is based on the URL.

Can you provide more details as to why it might be useful to be able to control the name of the folder in `~/.cocoapods/repos`?

**Comment by KeimyPlaza** [comment] 2017-01-19 23:50
ok course.

When I've a clean machine, with pods installed, only have folder `~/.cocoapods/repos/master`

Run `pod repo add Specs https://www.miserver/project/Specs.git`

Now there are 2 folders:

`~/.cocoapods/repos/master`
`~/.cocoapods/repos/Specs`

Why the folder is not `~/.cocoapods/repos/miserver-project-Specs`? Is is based on the URL

We're developing enterprise apps as a framework and the documentation that we must to do, it can't be exactly if the developer add repo manually or is adding by first pod update.

Thanks a lot!

**Comment by benasher44** [comment] 2017-01-20 02:48
Wait so it did get named Specs? In your issue description, you said it was named miserver-project-specs

**Comment by KeimyPlaza** [comment] 2017-01-20 07:01
Hi @benasher44 

I say you 2 actions with in my opinion 2 different results:

Always start action with local machine with new install cocoapods

A) `pod update`

1. run command `pod update` from folder project
2. Is added a repo specs in `~/.cocoapods/repos/miserver-project-Specs`

B) `pod repo add`

1. run command `pod repo add Specs https://www.miserver/project/Specs.git` from any folder
2. Is added a repo specs in '~/.cocoapods/repos/Specs'

I hope to explain better this time.

Thanks for your time

**Comment by DanToml** [comment] 2017-01-23 00:34
@KeimyPlaza I'd recommend not providing the name parameter in your documentation to prevent local conflicts with users configurations.

A happens because CocoaPods will search for a repository with the given source URL, it won't find one so it will clone it with the generated name. There is no way to force a name in a Podfile.

B happens because you manually add the repo. It will then be found and used in a pod install/update scenario.

**Comment by DanToml** [comment] 2017-01-23 00:36
Closing because this doesn't appear to be an actual bug

**Closed by DanToml** 2017-01-23 00:36 UTC

**Comment by benasher44** [comment] 2017-01-23 15:38
@DanToml thanks for the explanation! <3

**Comment by KeimyPlaza** [comment] 2017-01-23 18:22
Thanks you too much.

Let's follow your suggestion.

**Comment by hyfclimber** [comment] 2019-05-20 13:45
@endocrimes  the Aliyun repo can do it .the source url is https://github.com/aliyun/aliyun-specs, and the repo name is 'aliyun'  . And my repo named 'x', but generated 'domain-dir1-dir2-dir3-x' in the ''~/.cocoapods/repos' when 'pod update'.  How can I prevent the prefix?
