### ISSUE TITLE
Failure when uploading 2 podspecs where the 2nd one depends on the 1st one

### ISSUE THREAD

**Issue by lucatorella** [CocoaPods/CocoaPods#9502] opened 2020-01-23 08:36 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have 2 frameworks that depends on each other. Let's call them `FrameworkCore.framework` and `FrameworkMore.framework`. They share the same release cycle, so when version 6.1.2 is released both versions are pushed and `FrameworkMore.framework` will require version 6.1.2 of `FrameworkCore.framework`.

To upload the 2 frameworks I am using `pod trunk push xxx.podspec`

## What did you expect to happen?

I expect both frameworks to be uploaded successfully.

## What happened instead?

The first framework is uploaded correctly
```
--------------------------------------------------------------------------------
 🎉  Congrats

 🚀  FrameworkCore (6.1.2) successfully published
 📅  January 22nd, 18:39
 🌎  https://cocoapods.org/pods/FrameworkCore
 👍  Tell your friends!
--------------------------------------------------------------------------------
```

The second one fails because the dependency cannot be found:

```
Validating podspec
 -> FrameworkMore (6.1.2)
    - ERROR | [iOS] unknown: Encountered an unknown error (CocoaPods could not find compatible versions for pod "FrameworkCore":
  In Podfile:
    FrameworkMore (from `.../FrameworkMore.podspec`) was resolved to 6.1.2, which depends on
      FrameworkCore (= 6.1.2)
```

I added a huge delay (10 min) in my CI script to avoid this failure, but is there a better approach or something else I can do?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.5p114 (2019-10-01 revision 67812) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.14.6 (18G2022)
       Xcode : 11.3 (11C29)
         Git : git version 2.25.0
Ruby lib dir : /usr/local/Cellar/ruby/2.6.5/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 4525667108911797fa6905ca3ae29cd1dc6bdd19
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment] 2020-01-23 17:37
See this issue https://github.com/CocoaPods/CocoaPods/issues/9497.

Please use the `git` based solution that the CDN is backed from to ensure eventual consistency.

**Comment by lucatorella** [comment] 2020-01-24 14:40
I checked the other issue (sorry for the duplicate issue, I actually searched!) but it's not clear what I have to do. How do I use the `git` based solution?

**Comment by dnkoutso** [comment] 2020-01-24 16:30
Just add `source 'https://github.com/CocoaPods/Specs.git'` to your `Podfile` or `pod repo add cocoapods-master 'https://github.com/CocoaPods/Specs.git'` if I remember from the top of my head and use that source.

The CDN source is based on that git repo so its not going away. Its just slower to clone and update.

Going to close for now and we can continue discussion further and re-open if we find a bug or enhancement we can make.

**Comment by lucatorella** [comment] 2020-01-24 19:12
I’ve no `Podfile`. I just have 2 podspecs that I need to `pod trunk push`

**Comment by lucatorella** [comment] 2020-01-24 19:14
Maybe I know what you mean. I guess that `pod trunk push` creates a project and a Podfile to validate the spec. So yes, I can’t change the Podfile but I can do `pod repo add cocoapods-master 'https://github.com/CocoaPods/Specs.git'` before pushing. Is that right?

**Comment by dnkoutso** [comment] 2020-01-24 19:18
yes do `pod repo add ...` once and then when you do `pod trunk push` pass in `--sources` with `cocoapods-master`. This way cocoapods will use that source update it and "see" the other pod that was just published.

**Comment by lucatorella** [comment] 2020-01-24 19:36
Great, I will try that. Thanks!

**Comment by paulb777** [comment] 2020-01-28 19:42
@dnkoutso `pod trunk push` does not have a `--sources` option. Is there another way to specify?

**Comment by dnkoutso** [comment] 2020-01-28 19:46
hm I must have confused it with `pod repo push`... Looks like trunk defaults to using CDN I think ... as seen here https://github.com/CocoaPods/cocoapods-trunk/blob/master/lib/pod/command/trunk/push.rb#L147

@igor-makarov perhaps we can update this to look for the git based repo first then CDN if it does not exist?

**Comment by lucatorella** [comment] 2020-01-28 22:16
the nat the moment there is no real solution except `sleep(600)` 🙁

**Comment by paulb777** [comment] 2020-03-22 16:36
Duplicate of #9497. PR pending.

**Closed by paulb777** 2020-03-22 16:36 UTC
Labels: s7:workaround available

**Comment by lucatorella** [comment] 2020-11-05 10:29
I removed the `sleep(600)` and I'm using the new `--synchronous` options. It works great in most cases, at least in the past, but recently it's failing like 50% of the time.
