### ISSUE TITLE
0.39.0.beta.1: Include of non-modular header with GoogleMaps

### ISSUE THREAD

**Issue by jshier** [CocoaPods/CocoaPods#4088] opened 2015-08-26 19:54 UTC
Using the 0.39.0 beta, I'm still getting the issue introduced in 0.38 when I try to build my test target. 
```
<module-includes>:1:9: note: in file included from <module-includes>:1:
#import "/Users/jshier/Desktop/app/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GoogleMaps.h"
        ^
/Users/jshier/Desktop/app/Pods/GoogleMaps/Frameworks/GoogleMaps.framework/Headers/GoogleMaps.h:13:9: error: include of non-modular header inside framework module 'GoogleMaps'
#import <GoogleMaps/GMSAddress.h>
```
This occurs for each header in the `GoogleMaps.h` file.

Here's my Podfile:

```ruby
platform :ios, '7.1'

target :'APP', :exclusive => true do
  pod 'MBProgressHUD', '~> 0.9.1'
  pod 'UrbanAirship-iOS-SDK', '~> 6.2.0'
  pod 'GoogleMaps', '~> 1.10.0'
end

target :'APPTests', :exclusive => true do
  pod 'OHHTTPStubs'
end

target :'APPUITests', :exclusive => true do
  pod 'OHHTTPStubs'
end
```

**Comment by segiddins** [comment] 2015-08-26 20:38
This looks like a duplicate of https://github.com/CocoaPods/CocoaPods/issues/3847?

**Comment by jshier** [comment] 2015-08-26 21:25
Sorry. Guess I thought it was a new issue since #3832 was supposed to resolve issues like this, right? But yes, it's the same issue.

**Comment by segiddins** [comment] 2015-08-26 21:54
Nope, #3847 is still open.

**Closed by segiddins** 2015-08-26 21:54 UTC
