### ISSUE TITLE
Importing Swift code in Objective-C classes not possible with generated umbrella header

### ISSUE THREAD

**Issue by sbhklr** [CocoaPods/CocoaPods#3767] opened 2015-07-02 21:19 UTC
I'm developing a multi platform pod named `OSCEKit` that contains both Swift and objective-c code. I would like to import a swift class in an objective-c class. That means I will have to import it using `#import <OSCEKit/OSCEKit-Swift.h>`. The generated swift header includes an import statement of what it thinks is the umbrella header `#import <OSCEKit/OSCEKit.h>`. Alright, so I thought I can just create and add `OSCEKit.h` and include the actual umbrella header inside that header file: `#import <OSCEKit/OSCEKit-umbrella.h>`. However, this umbrella header will be generated and be named by CP according to the target that uses this pod, so I cannot rely on this filename. This is where I'm stuck. Is "mix and match" actually possible in this scenario? The only solution I see is that I write a custom modulemap for each platform which includes a custom umbrella header for each platform.

**Comment by segiddins** [comment] 2015-07-06 02:29
`#import <OSCEKit/OSCEKit-umbrella.h>` should be stable?

**Comment by sbhklr** [comment] 2015-07-06 21:50
@segiddins Not with the current release version of CP. The umbrella headers are named according to the target that integrates the pod (e.g. Pods-OSCEKitDemo-OSCEKit-umbrella.h). Maybe that changes with de-duplication #3550, I haven't tried that yet.

**Comment by neonichu** [comment] 2015-07-17 09:18
This is mainly an Xcode issue, because the generated Swift compatibility header uses a fixed header name instead of the actual umbrella header. Do we know if this has been fixed in Xcode 7?

**Comment by jeremiegirault** [comment] 2015-07-21 08:39
I tested in xcode 7 beta 3 and the issue is still present. Seems it not going to change soon, the -Swift.h file is hardcoded to import Framework/Framework.h

**Comment by neonichu** [comment] 2015-07-21 08:42
@jeremiegirault thanks for checking that out. Do you know of existing radars on it? If not, we should definitely create and dupe one for it.

Regardless of that, we should handle this inside CP as well, for the time being. 

cc @mrackwitz

**Comment by jeremiegirault** [comment] 2015-07-23 10:20
I did not find a radar about this issue. This seems like a framework convention

**Comment by rasmusth** [comment] 2015-09-18 08:56
I would love to see something on this :)

**Comment by king7532** [comment] 2015-09-21 20:49
I 2nd that.  Any workarounds to hack it for development purposes?

**Comment by jeremiegirault** [comment] 2015-09-21 20:51
I did not manage to workaround this

**Comment by rasmusth** [comment] 2015-09-21 20:54
You can define the umbrella header manually from within your podspec. Unfortunately this will result in you losing the automatically generated one.

**Comment by segiddins** [comment] 2015-09-25 15:38
Is there any reason we can't just make the umbrella header `module_name.h` when that file doesn't exist, and acquiesce to the existing one if it does?

**Comment by orta** [comment] 2015-09-25 15:46
that feels like the answer to me

**Comment by mrackwitz** [comment] 2015-09-25 15:54
It's breaking semantic change, which will be difficult to introduce, but it seems at this point necessary. In addition, we should make sure that all public headers are listed explicitly in the modulemap, if not the header was explicitly declared in the podspec as umbrella header. Otherwise there would be likely pods, which would have a broken public interface.

**Comment by segiddins** [comment] 2015-09-25 16:01
I agree that at this point it seems necessary.

**Comment by czechboy0** [comment] 2015-10-03 10:28
Is there any more known info about this? Because currently this issue makes adding pods like ReactiveCocoa (4) impossible to have as your spec's dependency. Let me know if I can help out to get this in faster! :+1:

**Comment by segiddins** [comment] 2015-10-03 11:54
@czechboy0 at this point, all the info is here, it just needs to be implemented.

**Comment by neonichu** [comment] 2015-10-05 13:35
@segiddins @mrackwitz how about this: we will continue generating the umbrella header for pure Swift or pure ObjC Pods, but use existing headers for mixed Pods. This way, we shouldn't break any Pods which are already working.

**Comment by segiddins** [comment] 2015-10-05 13:38
@neonichu it won't work for objc pods imported in swift, iirc.

**Comment by neonichu** [comment] 2015-10-05 14:19
@segiddins those seem to work perfectly fine for me — the only issue lies in the generated `*-Swift.h` header, AFAIK

**Comment by segiddins** [comment] 2015-10-05 15:49
Ah ok. I'd still rather we use the project's own umbrella header, and withhttps://github.com/CocoaPods/CocoaPods/pull/4105 it'd even be validated, so ¯\_(ツ)_/¯

**Comment by zierka** [comment] 2016-05-12 14:29
Any update on this? I may have the same issue:

I created a dynamic framework where I use both swift and objective-c classes. The framework project builds fine, and works with my iOS app when I embed the built `MyFramework.framework` file, but when I install it with cocoapods, the iOS app stops build-time at the framework in the generated swift header file (`MyFramework-Swift.h`) at `#import <MyFramework/MyFramework.h>` saying that the file isn't found.

**Comment by sbhklr** [comment] 2016-05-22 21:47
How about we let CP create the `<Framework/Framework.h>` file if it doesn't exist yet and put an import statement of the actual umbrella header there `#import <Framework/Framework-umbrella.h>`? Probably not the most elegant solution but it would satisfy the compiler when processing the `Framework-Swift.h` header file.

**Comment by ihsancse** [comment] 2016-07-22 12:46
I have very simple solution for this. 
Go to Menu-->Window-->Projects-->Select Your project-->Click arrow of derive data-->Delete the folder

**Comment by fcy** [comment] 2016-08-25 00:28
I'm not totally sure if I understood the consensus here, specially related to the generate `-Swift.h` file. Did CocoaPods decided that importing `module_name.h` is an Xcode bug and won't be fixed? So the only official solution is to not use the generated module map and have my own with the umbrella header name that Xcode likes?

**Comment by neonichu** [comment] 2016-08-25 08:40
While it may be an Xcode bug, it is still an open issue we want to address. Nobody has gotten around to fixing it, yet, though.

**Comment by nicksnyder** [comment] 2016-09-07 17:45
@zierka What was your problem and how did you solve it? I have a similar problem.

@rhummelmose Can you elaborate on how you worked around this? Defining a custom umbrella header implies a custom module map, right?

**Comment by sbhklr** [comment] 2016-09-08 08:09
@nicksnyder To avoid dependency issues from Swift to ObjC files I created a `MyFramework.h` file and include the .h files required by the Swift files there. This header file serves as the umbrella header. In the ObjC files I imported the generated Swift Interface header like `<MyFramework/MyFramework-Swift.h>`
Not the most elegant solution, but it does the trick.

**Comment by jervine10** [comment] 2016-10-18 19:19
Is it possible to get this posted in a StackOverflow question with a successful answer?

**Comment by sbhklr** [comment] 2016-10-19 07:34
@jervine10 All information is here. Not sure how StackOverflow can help.

**Comment by mjholgate** [comment] 2016-11-11 15:25
I'm not sure if this is actually a CocoaPods bug. The Apple documentation here https://developer.apple.com/library/content/documentation/Swift/Conceptual/BuildingCocoaApps/MixandMatch.html#//apple_ref/doc/uid/TP40014216-CH10-ID122 states:

>  Note that the Swift interfaces in the generated header include references to all of the Objective-C types used in them. If you use your own Objective-C types in your Swift code, make sure to import the Objective-C headers for those types before importing the Swift generated header into the Objective-C .m file you want to access the Swift code from.

That implies that the user is responsible for these imports.

**Comment by bioche** [comment] 2016-11-20 00:25
I've been running into this issue lately on a module that mixes Obj-C & Swift. I got it solved by adding the following `Framework/Framework.h` : 

`#if __has_include("Framework-umbrella.h")`
`#import "Framework-umbrella.h"`
`#endif`

As the generated umbrella header naming seems to be stable now, it's a working solution.
However I think @mjholgate solution is a good one as it's in the apple docs and modules can be compilable on their own. ( For this last solution, we still need `Framework/Framework.h` to exist even if it's empty. )

**Comment by sbhklr** [comment] 2017-01-11 21:33
@bioche Thx for sharing your solution. Since my framework supports both iOS and macOS I had to go for a slightly modified solution:
```
#if __has_include(<Framework/Framework-iOS-umbrella.h>) && TARGET_OS_IPHONE
#import <Framework/Framework-iOS-umbrella.h>
#endif

#if __has_include(<Framework/Framework-OSX-umbrella.h>) && !TARGET_OS_IPHONE
#import <Framework/Framework-OSX-umbrella.h>
#endif
```

**Closed** 2017-01-11 21:34 UTC
Labels: d2:moderate, s4:awaiting validation, t2:defect

**Comment by DaveLiu888** [comment] 2017-08-23 20:39
Any word on this ? I am getting non modular imports from generated Swift.h :[

**Comment by rob-keepsafe** [comment] 2018-11-14 16:45
To my knowledge, this is still an issue (especially with the CocoaPods v1.5 static library support which doesn't seem to support custom modulemaps so far).

Since all other issues link to this one and this one was closed out, can we please re-open?

**Comment by JoachimK** [comment] 2018-12-28 14:33
Can confirm that this is still an issue.

I tried the following workarounds:
- Create an additional `<MyPod/MyPod.h>` header that just does `#import <MyPod/MyPod-umbrella.h>` (the header generated by CocoaPods). This will generate an Xcode/Swift compiler warning, as we now have a public header (`MyPod.h`) that is not imported in the designated Umbrella-header.
- To get rid of that warning, I specified my own module-map that specifies `MyPod.h` as the `umbrella header`. I just copied over the one generated by CocoaPods, referenced it from the podspec via `spec.module_map` and changed `"MyPod-umbrella.h"` to `"MyPod"`. This seems to work, except now Cocoapods doesn't generate an umbrella-header for me anymore, so my import of `MyPod-umbrella.h` inside `MyPod.h` fails. If I understand it correctly I'd now have to create an umbrella header manually and that's a big hassle. :(

**Comment by domdop** [comment] 2018-12-28 14:40
Ich bin derzeit nicht im Büro. Ich kehre zurück am  02.01.2019.
Ich werde Ihre Nachricht nach meiner Rückkehr beantworten.

Die Rückmeldung bezieht sich auf ein Mail mit folgendem Thema:
Re: [CocoaPods/CocoaPods] Importing Swift code in Objective-C classes not
possible with generated umbrella header (#3767)

____________________________________________________________________________________________
Gesendet (c) GRZ/RACON Linz 2018 Agent 'Abwesenheit'

----------------------------------------
Raiffeisen Software GmbH
Firmenbuchnummer: 86804d, Landesgericht Linz
DVR: 0572934, UID: ATU 36961105

Der Austausch von Nachrichten mit dem oben angeführten Absender via E-Mail
dient ausschließlich Informationszwecken. Rechtsgeschäftliche Erklärungen
dürfen über dieses Medium nicht ausgetauscht werden.
Correspondence with above mentioned sender via e-mail is only for
information purposes. This medium is not to be used for the exchange of
legally-binding communications.
----------------------------------------

**Comment by kylejm** [comment] 2019-04-01 11:51
For mixed Swift/Obj-C frameworks, could CocoaPods use the custom `module.modulemap` if there's one defined? And use the existing umbrella header?

Maybe I'm missing something obvious, but I think, for our case at least, we don't need CocoaPods to create a module map or a header file since we have defined both.

**Comment by KeerthijesusMCA7** [comment] 2019-06-16 04:57
`hi, `where to replace this code "<OSCEKit/OSCEKit-umbrella.h>". and #import <OSCEKit/OSCEKit-Swift.h>  will be also generated in derived data only and in the framework where can i find this file and replaces the code  from <OSCEKit/OSCEKit-Swift.h> to  "<OSCEKit/OSCEKit-umbrella.h>"  

While i creating my own pod of the project i got this error.  please reply as soon as possible.
![Screenshot 2019-06-15 at 10 47 02 PM](https://user-images.githubusercontent.com/31469944/59559278-245e6f80-9021-11e9-8423-d77e850e8ba8.png)

**Comment by sirghi** [comment] 2020-06-23 08:24
So, as a Cocoapods fix, would removing the `-umbrella` suffix from the umbrella header be acceptable?

+1 on this issue. And besides, the fact that Xcode uses `Framework/Framework.h` for this purpose, I see it as a convention that everyone using Xcode should follow, not a bug on their side.

**Comment by ddaddy** [comment] 2020-09-06 14:43
Not sure if this is the same issue here, but with Xcode 12 now enabling the `Double Quoted import` compiler warning, I need my umbrella header to use angled imports instead of quotes.
Is there a way to override how the umbrella is generated?

**Comment by paulb777** [comment] 2020-09-06 14:52
@ddaddy See #9902.  CocoaPods 1.10 will disable the warning in the generated Pods project.

**Comment by ddaddy** [comment] 2020-09-06 15:08
> @ddaddy See #9902.  CocoaPods 1.10 will disable the warning in the generated Pods project.

I'm not sure disabling the warning is the answer. There's a reason Apple has decided to enable it in the first place.

**Comment by dinesh547** [comment] 2021-05-26 12:55
Can confirm Same issue still exists.
I am using swift and .m file in podspec and this issue is still happening.
Any idea from experts how to solve this?

**Comment by c0d3runn3r** [comment] 2022-07-20 16:57
I have an Objective C framework pod that has a Swift framework pod as a dependency.  For the outer (ObjC) pod, `#import <MySwiftPod/MySwiftPod-Swift.h>` works fine in XCode, but `pod spec lint MyObjCPod.podspec` results in ` fatal error: 'MySwiftPod-Swift.h' file not found`

**Comment by mrousavy** [comment] 2024-07-26 18:53
Sorry for commenting on an old issue, but @c0d3runn3r what was the solution to your problem? I'm guessing you'd need to import the Umbrella header instead in your second pod, right?
The -Swift.h file is not visible outside of the current pod, so you need to import the umbrella one instead
