### ISSUE TITLE
Warning when using Pod Install with Facebook SDK

### ISSUE THREAD

**Issue by QuanHuynhM** [CocoaPods/CocoaPods#9983] opened 2020-08-16 12:14 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

I am currently receiving some warnings when installing pods with "pod install"

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

[!] The Unity-iPhone [Release] target overrides the OTHER_LDFLAGS build setting defined in Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.release.xcconfig'. This can lead to problems with the CocoaPods installation - Use the $(inherited)` flag, or
- Remove the build settings from the target.

[!] The Unity-iPhone [ReleaseForProfiling] target overrides the OTHER_LDFLAGS build setting defined in Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.releaseforprofiling.xcconfig'. This can lead to problems with the CocoaPods installation - Use the $(inherited)` flag, or
- Remove the build settings from the target.

[!] The Unity-iPhone [ReleaseForRunning] target overrides the OTHER_LDFLAGS build setting defined in Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.releaseforrunning.xcconfig'. This can lead to problems with the CocoaPods installation - Use the $(inherited)` flag, or
- Remove the build settings from the target.

[!] The Unity-iPhone [Debug] target overrides the OTHER_LDFLAGS build setting defined in Pods/Target Support Files/Pods-Unity-iPhone/Pods-Unity-iPhone.debug.xcconfig'. This can lead to problems with the CocoaPods installation - Use the $(inherited)` flag, or
- Remove the build settings from the target.

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0

**Comment by dnkoutso** [comment] 2020-08-16 17:54
Yes the warning message clearly says what to do. Open `OTHER_LDFLAGS` in your target and either add $inherited or delete your own setting so the cocoapods one can work.

Closing as this appears to be working properly and as intended.

**Closed by dnkoutso** 2020-08-16 17:54 UTC
