### ISSUE TITLE
Frameworks missing in child target

### ISSUE THREAD

**Issue by OmarPedraza** [CocoaPods/CocoaPods#6669] opened 2017-04-20 10:05 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

After running **'pod install'**, I tried to build my project but test target has failed due to linker error after not finding a framework that's included in my _Podfile_.

## What did you expect to happen?

The main and test targets compiles as expected.

## What happened instead?

The test target build fails because Xcode is not able to find a framework included in the _Podfile_ and included in that target using **inherit! :search_paths**

This seems to be related with #5173 that should be solved in #5514 and included in version 1.2.1, but it's not working for me unless I explicitly add those dependencies in the test target.

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.2 (8E2002)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f47e4edea7370729329800e350820187355bc9e3
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Podfile
source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!
use_frameworks!

platform :ios, '9.0'

def defaults
    pod 'AdobeMobileSDK'
    pod 'AFDownloadRequestOperation', '~> 2.0'
    pod 'AFNetworking', '~> 2.6.3'
    pod 'AFURLConnectionByteSpeedMeasure', '~> 1.0'
    pod 'AppsFlyerFramework'
    pod 'CocoaHTTPServer'
    pod 'CocoaLumberjack', '~> 1.9.2' # Max version compatible with CocoaHTTPServer
    pod 'Crashlytics'
    pod 'Fabric'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'Firebase'
    pod 'Gigya-iOS-SDK'
    pod 'Google/Analytics'
    pod 'google-cast-sdk'
    pod 'GSKeychain'
    pod 'HockeySDK'
    pod 'libextobjc'
    pod 'RMStore', :git => 'https://github.com/tschmitz/RMStore', :branch => 'patch-1' # Movida: AppReceiptVerifier OpenSSL dependency is gone and not updated in the official repository
    pod 'RMStore/AppReceiptVerifier', :git => 'https://github.com/tschmitz/RMStore', :branch => 'patch-1' # Movida: AppReceiptVerifier OpenSSL dependency is gone and not updated in the official repository
    pod 'SDWebImage'
    pod 'TTTAttributedLabel'
    pod 'UrbanAirship-iOS-SDK'
    pod 'XMLDictionary'
end

target 'hayu' do
    defaults
end

target 'hayu Release' do
    defaults

    target 'hayuTests' do
        inherit! :search_paths

#pod 'Gigya-iOS-SDK' # Movida: removing this duplicated line breaks the build, a CocoaPods update would solve it
#       pod 'GSKeychain' # Movida: removing this duplicated line breaks the build, a CocoaPods update would solve it
        pod 'Kiwi'
        pod 'OHHTTPStubs'
    end
end

# Disable bitcode for Kiwi target
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
            config.build_settings['CODE_SIGNING_REQUIRED'] = 'NO'
            config.build_settings['ENABLE_BITCODE'] = 'NO'
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ''
        end
    end
end
```

## Project that demonstrates the issue

Sorry, but it's not an open source project and I can't share it with you.

Here you have a couple of screenshots with the errors:

![screen shot 2017-04-20 at 11 59 47](https://cloud.githubusercontent.com/assets/1285953/25225265/18018d2a-25c1-11e7-8923-133cc221be49.png)

![screen shot 2017-04-20 at 12 03 48](https://cloud.githubusercontent.com/assets/1285953/25225369/77821238-25c1-11e7-820c-be207ea20175.png)

**Comment by Raesu** [comment] 2017-04-22 03:17
I have a similar issue and have a repo to reproduce it. Run `pod install` on this repo (https://github.com/Raesu/Demo-Proj), and build. Similar `_OBJC_CLASS` linker errors.

I created the project, added a framework as a subtarget, and created File.swift (in case that is helpful).

@OmarPedraza How were you able to solve the issue? Can you explain using my demo project?

**Comment by OmarPedraza** [comment] 2017-04-27 09:49
@Raesu, as you can see commented in my Podfile, having the GSKeychain pod into test target avoids this kind of error.

**Comment by raspu** [comment] 2017-05-09 09:37
I am also having an equivalent issue with 1.2.1, but on my case even explicitly adding the pod to the test target won't fix it. It seems the issue is on the generated `xcconfig` files. 

This is the Podfile I am using for testing:

```ruby
platform :ios, '9.0'

target 'podTestA' do
  use_frameworks!
  pod ‘ComScore’	

  target 'podTestATests' do
    inherit! :search_paths
    pod ‘ComScore’
  end

end
```

Which is generating these files:

**Pods-podTestA.debug.xcconfig** (The release version is exactly the same)
```bash
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/ComScore/ComScore/iOS"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/ComScore"
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
OTHER_CFLAGS = $(inherited)  -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/ComScore"
OTHER_LDFLAGS = $(inherited) -ObjC -l"c++" -framework "ComScore" -framework "Security" -framework "SystemConfiguration"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
```

**Pods-podTestATests.debug.xcconfig** (The release version is exactly the same)
```bash
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/ComScore/ComScore/iOS"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/ComScore"
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
OTHER_CFLAGS = $(inherited)  -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/ComScore"
OTHER_LDFLAGS = $(inherited) -l"c++" -framework "Security" -framework "SystemConfiguration"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_PODFILE_DIR_PATH = ${SRCROOT}/.
PODS_ROOT = ${SRCROOT}/Pods
```

As you can see the Unit tests version (`Pods-podTestATests.debug.xcconfig`) is missing the framework and it's associated flags (`-ObjC -framework "ComScore"`):
```bash
OTHER_LDFLAGS = $(inherited) -l"c++" -framework "Security" -framework "SystemConfiguration"
```
 Manually adding them fixes the issue for me.

**Comment by dnkoutso** [comment] 2017-05-09 14:47
I can take a look. But generally in 1.2.1 if you use `inherit! search_paths` the test target will *not* inherit the same vendored static or dynamic libraries in terms of linker flags. That is because you will be shipping duplicate symbols in your test bundle *and* your app.

**Comment by raspu** [comment] 2017-05-10 08:09
@dnkoutso I see, so how do you make sure that the libraries are linked with the test target?

**Comment by ffittschen** [comment] 2017-08-12 16:05
I would also like to know the answer to @raspu's question, since I'm facing the same problem. Putting the `pod 'SomePod' ~> 4.2` in the child targets forces me to search and replace every version number that is associated with `SomePod` as soon as I decide to update that pod, which is inconvenient and not what the inheritance should be about, right?

**Comment by orta** [comment] 2017-08-12 16:07
I'm not sure about the specifics to this issue, but you can use a variable in Ruby to assign the same version between them, or just do it once I imagine.

**Comment by OmarPedraza** [comment] 2017-08-17 07:20
In my case, since GSKeychain repo has been finally deleted, I decided to remove that framework from my project and no more duplicity is needed.

**Comment by raspu** [comment] 2017-08-17 07:30
@raspu I think my problem was that I am adding a static library, so all its symbols are copied into the app binary on compilation time, and this means that they are not accessible to the test binary.

**Closed** 2017-11-22 09:19 UTC
Labels: s1:awaiting input
