### ISSUE TITLE
Error `pod update` - iOS Share Extension

### ISSUE THREAD

**Issue by bdparrish** [CocoaPods/CocoaPods#3201] opened 2015-02-28 22:06 UTC
Recently I added a Share Extension to my iOS application and went to update my pods and received the error depicted below...

### Report

* What did you do?
pod update

* What did you expect to happen?
update all pod dependencies

* What happened instead?
failed - error occurred (SystemStackError - stack level too deep)

### Stack

```
   CocoaPods : 0.35.0
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin13]
    RubyGems : 2.0.14
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4d8b3ce80e372cfb15564c0696024618551fb389
```

### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.2
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.1'

xcodeproj 'App'

link_with 'App', 'App Tests'

pod 'Facebook-iOS-SDK',     :head
pod 'RestKit',              '~> 0.20.0'
pod 'TPKeyboardAvoiding',   '~> 1.1'
pod 'MHPrettyDate',         :head
pod 'SVProgressHUD',        :head
pod 'SDWebImage',           '~>3.6'
pod 'CocoaLumberjack',      '~> 1.9'
pod 'UIAlertView-Blocks',   :head
pod 'BFPaperCheckbox',      '~> 1.2.4'
```

### Error

```
SystemStackError - stack level too deep
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.20.2/lib/xcodeproj/project/object_attributes.rb:139
```

**Comment by kylef** [comment] 2015-03-30 18:56
I've successfully `pod install`-ed with this Podfile using an freshly created project with a share extension and I'm unable to reproduce any error.

Can you provide full steps to reproduce or an example project exhibiting this problem @bdparrish?

**Comment by neonichu** [comment] 2015-05-10 02:41
Since there was reaction for a long time, we can close this.

**Closed by neonichu** 2015-05-10 02:41 UTC
Labels: s1:awaiting input, t2:defect
