### ISSUE TITLE
Problem with Hockeyapp

### ISSUE THREAD

**Issue by erema** [CocoaPods/CocoaPods#5358] opened 2016-05-18 09:20 UTC
error: Resource "/Users/xxx/Library/Developer/Xcode/DerivedData/xxx-bgszvlzstziakddnkornjorikbox/Build/Products/Adhoc-iphoneos/HockeySDK-Source/HockeySDKResources.bundle" not found. Run 'pod install' to update the copy resources script

example project is attached.

[pod-example 2.zip](https://github.com/CocoaPods/CocoaPods/files/270062/pod-example.2.zip)

**Comment by neonichu** [comment] 2016-05-18 09:42
I can't reproduce this error when building the given project. Your error mentions a build configuration called "Adhoc" that doesn't even exist in the example, how are you building it to produce that error?

**Comment by erema** [comment] 2016-05-18 09:46
xcodebuild -workspace pod-example.xcworkspace -scheme pod-example -configuration Adhoc clean build CONFIGURATION_BUILD_DIR={ABSOLUTE_PATH}

**Comment by neonichu** [comment] 2016-05-18 11:48
That also works fine for me, using Xcode 7.3.1. The error seems very strange to me, as the project does not have an "Adhoc" configuration and falls back to building with "Release" when running `xcodebuild`.

**Comment by erema** [comment] 2016-05-18 11:57
You can try "xcodebuild -workspace pod-example.xcworkspace -scheme pod-example -configuration Release clean build CONFIGURATION_BUILD_DIR=/Users/XXX/XXX/pod-example/build" in terminal, an d you will see a fail.

**Comment by neonichu** [comment] 2016-05-18 12:14
I see the issue now. By only overwriting `CONFIGURATION_BUILD_DIR`, the expectations of the copy resources script are no longer met. I think overwriting `BUILD_DIR` or `SYMROOT` would be better here.

@mrackwitz should we document somewhere that just overwriting `CONFIGURATION_BUILD_DIR` no longer works? Seeing also #5323

**Comment by mrackwitz** [comment] 2016-05-19 16:54
Yes! I think that would be a good idea. I was thinking that this could be handled by a blog article explaining the new scoping, but that seems to be to temporary to be the only place. We should put that somewhere in the guides as well.

**Comment by fabb** [comment] 2016-06-13 10:26
Same issue here with pod ATInternet-iOS-ObjC-SDK/iOS

**Comment by akarpodinis** [comment] 2016-06-28 15:20
> Yes! I think that would be a good idea. I was thinking that this could be handled by a blog article explaining the new scoping, but that seems to be to temporary to be the only place. We should put that somewhere in the guides as well.

Were the guides updated?  Can a link be left here?

**Comment by Coeur** [comment] 2016-06-29 08:22
I tried many different configurations for Jenkins:

no custom SYMROOT
no custom BUILD_DIR
CONFIGURATION_BUILD_DIR=${WORKSPACE}/build
-> FAILURE
> error: Resource "/Users/Shared/Jenkins/Home/jobs/SECRET/workspace/build/MobileDev-iphoneos/SECRET/SECRET.bundle" not found. Run 'pod install' to update the copy resources script.

no custom SYMROOT
BUILD_DIR=${WORKSPACE}/build
no custom CONFIGURATION_BUILD_DIR
-> FAILURE
> ** BUILD SUCCEEDED **
> 
> FATAL: Build directory does not exist at > /Users/Shared/Jenkins/Home/jobs/SECRET/workspace/SECRET/build/MobileDev-iphoneos. Potential configuration issue.
> Build step 'Xcode' marked build as failure
> Finished: FAILURE

no custom SYMROOT
BUILD_DIR=${WORKSPACE}/build
CONFIGURATION_BUILD_DIR=${WORKSPACE}/build
-> FAILURE
> error: Resource "/Users/Shared/Jenkins/Home/jobs/SECRET/workspace/build/MobileDev-iphoneos/SECRET/SECRET.bundle" not found. Run 'pod install' to update the copy resources script.

no custom SYMROOT
no custom BUILD_DIR
no custom CONFIGURATION_BUILD_DIR
-> FAILURE
> ** BUILD SUCCEEDED **
> 
> FATAL: Build directory does not exist at /Users/Shared/Jenkins/Home/jobs/SECRET/workspace/SECRET/build/MobileDev-iphoneos. Potential configuration issue.
> Build step 'Xcode' marked build as failure
> Finished: FAILURE

SYMROOT=${WORKSPACE}/build
no custom BUILD_DIR
no custom CONFIGURATION_BUILD_DIR
-> SUCCESS

SYMROOT=${WORKSPACE}/build
BUILD_DIR=${WORKSPACE}/build
no custom CONFIGURATION_BUILD_DIR
-> SUCCESS

SYMROOT=${WORKSPACE}/build
no custom BUILD_DIR
CONFIGURATION_BUILD_DIR=${WORKSPACE}/build
-> FAILURE
> error: Resource "/Users/Shared/Jenkins/Home/jobs/SECRET/workspace/build/MobileDev-iphoneos/SECRET/SECRET.bundle" not found. Run 'pod install' to update the copy resources script.

So, in my case, in Jenkins config:
* SYMROOT must be set
* BUILD_DIR has no incidence
* CONFIGURATION_BUILD_DIR must not be set

**Comment by neonichu** [comment] 2016-06-29 08:50
@Coeur Thanks for the investigation. Would you be interested in writing up a paragraph on how to configure Jenkins correctly which we could include in the guides?

**Comment by Coeur** [comment] 2016-06-29 11:35
It was attempts at fixing CI configuration. I do not know what all those settings do in reality, so I may be giving wrong advices. Let's hear more feedback from @DarrylBayliss, @tlandsmancars, @faken, @Chren, @zinndesign, ...

**Comment by zinndesign** [comment] 2016-06-29 15:10
@Coeur - thanks for looking into this and the detailed write-up... makes me wish we were using Jenkins. Unfortunately, I'm dealing with an inherited in-house app builder application written in Perl. If I omit the overwrite of `CONFIGURATION_BUILD_DIR`, the build succeeds but the process breaks in multiple other places - so I'm still looking for a solution that allows overwriting that value in settings, e.g.
```
my %settings = ( VALID_ARCHS             => 'armv6 armv7 i386',
	PROVISIONING_PROFILE    => $plist->{UUID}->value,
	CODE_SIGN_IDENTITY      => $codeSignID,
	CONFIGURATION_BUILD_DIR => "${build_path}/build",
	CONFIGURATION_TEMP_DIR  => "${build_path}/temp",
	VALIDATE_PRODUCT        => 'YES');
```
Will continue to test on my end, but open to additional feedback from everyone - especially anyone who's managed to make this work with a custom `CONFIGURATION_BUILD_DIR` setting.

**Comment by pavel-zdenek** [comment] 2016-08-02 12:24
As i lost 1.5 day on this myself (one of the cases where you know _exactly_ what to google only after you fix it), i can add some knowledge: The `PODS_CONFIGURATION_BUILD_DIR` env used in "Copy Pods Resources" step (that is `Pods-*-resources.sh` script) ignores `CONFIGURATION_BUILD_DIR` and is constructed freshly from `$BUILD_DIR` - see any related xcconfig in Pods. So in my case setting `BUILD_DIR` did the right thing. The only disadvantage is a need for constructing an equivalent of `CONFIGURATION_BUILD_DIR` manually - that is adding `${CONFIGURATION}${EFFECTIVE_PLATFORM_NAME}` to it. It's still the path where the app and dSYMs land, not in `BUILD_DIR` directly.

**Comment by jmfriend** [comment] 2016-08-02 14:41
I'm seeing the same error with HockeyApp as reported here, but I don't understand from the previous comments what I need to do to get around this error. Sorry if my lack of understanding of cocoapods  is preventing me from understanding something that is obvious to everyone else. Would just love to know what I need to do.

**Comment by pavel-zdenek** [comment] 2016-08-02 15:42
@jmfriend are you building through CI or Xcode? Are you aware of manual modifications to the xcodebuild/xctool command?

**Comment by jmfriend** [comment] 2016-08-02 15:45
I’m building through Xcode just by using the Xcode guy. I’m not running xcodebuild/xctool on the command line. I’ve not used those or made manual modifications to those commands.

**Comment by pavel-zdenek** [comment] 2016-08-02 17:13
@jmfriend what's the origin of the project you're building? Hacking someone else's work, or made yourself from scratch? You see, this issue arises when there are modifications to the default xcodebuild invocation. Most frequently through some CI service scripting. So your case is suspicious.

**Comment by jmfriend** [comment] 2016-08-02 18:24
@pavel-zdenek <https://github.com/pavel-zdenek>, it’s my project (although a couple of other people have worked on it over the years). I originally started the project in 2008, so it’s old. There’s target for building one version of the app that does not work (and gives this hockeyapp error), and another target for building a different version of the app that does work. There’s not any modifications to the xcodebuild.

**Comment by Coeur** [comment] 2016-08-04 07:21
Our team is moving away from Jenkins and are now using a [Gymfile](https://github.com/fastlane/fastlane/tree/master/gym).

**Comment by jmfriend** [comment] 2016-08-05 08:40
turns out my issue was resolved by using a new Xcode scheme. Something in the old scheme was preventing pod libraries from being copied into the build folder.

**Comment by cfedak** [comment] 2016-08-11 16:47
Just wanted to chime in that @Coeur 's solution worked for me on a teamcity installation where I'm using fastlane's xcodebuild command to produce a simulator build for functional testing.  Thanks!

**Comment by neildavis** [comment] 2016-10-06 12:28
Hit this today after (finally!) upgrading from cocoapods 0.39 -> 1.0.1 and using HockeySDK-Source. 
Happens under Jenkins CI with overridden ```CONFIGURATION_BUILD_DIR```
@Coeur 's solution of using ```SYMROOT``` instead allows builds to succeed, but we have multiple Jenkins jobs setup like this, all of which look in the ```CONFIGURATION_BUILD_DIR``` for the dSYM and app artifacts, which of course then move to a config+platform sub dir.
Guess I'll have to change all my job conifgurations :(
Thanks to everyone on this thread for helping diagnose the issue.
Since this issue is still open, does anybody know if this is likely to be fixed?

**Comment by nogueirad88** [comment] 2016-11-01 17:23
After 14h i found this issue, @Coeur 's solution of setting only SYMROOT=${WORKSPACE}/build solve this problem, thanks

**Comment by diidu** [comment] 2017-01-27 10:42
@Coeur 's solution of setting only SYMROOT=${WORKSPACE}/build worked for me also. Though I realized that setting CONFIGURATION_BUILD_DIR to "${SYMROOT}/Debug" or similar does not break it. However, I ran into a problem that while archive creation succeeds, the archive is malformed, missing the archive specific root level Info.plist file. Any idea on how to solve this or if it is even related?

**Comment by dryganets** [comment] 2017-04-06 00:23
Is there any other way to fix this issue?
We really need to specify CONFIGURATION_BUILD_DIR on our application server as we have a workspace approach build server and build agent is allowed to write only to the current workspace.

Any chance to get this fixed?

**Comment by Coeur** [comment] 2017-04-06 02:34
@dryganets as written above, you can use your own script instead of Jenkins Xcode plugin.
Then all the paths will be your responsibility.

Example:
```
SCHEME="MyScheme-Debug"
EXPORT_OPTION_PLIST="my_export.plist"
XCODE="/Applications/Xcode.app"
XCODEBUILD="Scripts/xcbuild-safe.sh"

# archiving
ARCHIVE_DAY=$(date +%Y-%m-%d)
ARCHIVE_TIME=$(date +%H.%M.%S)
ARCHIVE_PATH="~/Library/Developer/Xcode/Archives/${ARCHIVE_DAY}/MyApp ${ARCHIVE_DAY} ${ARCHIVE_TIME}.xcarchive"
set -o pipefail \
    && DEVELOPER_DIR="${XCODE}" ${XCODEBUILD} -workspace MyApp.xcworkspace \
    -scheme ${SCHEME} \
    -destination 'generic/platform=iOS' \
    -archivePath "${ARCHIVE_PATH}" \
    clean archive \
    | xcpretty

# exporting
EXPORT_PATH="build/${SCHEME}"
rm -rf "${EXPORT_PATH}"
mkdir -p "${EXPORT_PATH}"
set -o pipefail \
    && DEVELOPER_DIR="${XCODE}" ${XCODEBUILD} -exportArchive \
    -archivePath "${ARCHIVE_PATH}" \
    -exportPath "${EXPORT_PATH}" \
    -exportOptionsPlist "${EXPORT_OPTION_PLIST}"
```

...where `xcbuild-safe.sh` is coming from https://github.com/fastlane/fastlane/blob/master/gym/lib/assets/wrap_xcodebuild/xcbuild-safe.sh

**Comment by dryganets** [comment] 2017-04-06 06:01
I'm not using Jenkins I have direct call to xcode build. I wonder if there is a clear recipe how to override CONFIGURATION_BUILD_DIR and still have pods working. 
It seems like a few people solved this problem already. 
I need to customize the output directory, maybe it's not the optimal way. I'm new to iOS development, Sorry.

**Closed** 2017-07-17 10:25 UTC
Labels: s1:awaiting input
