### ISSUE TITLE
Missing Bundle File

### ISSUE THREAD

**Issue by Aadeshp** [CocoaPods/CocoaPods#3118] opened 2015-02-08 06:05 UTC
The issue I am getting is below:

```
/Users/.../Pods/${BUILT_PRODUCTS_DIR}/APMultiMenu.bundle
building file list ... rsync: link_stat "/Users/.../Pods/${BUILT_PRODUCTS_DIR}/APMultiMenu.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

I have updated the cocoapods gem as well, and tried various other things but no luck. Anyone have any ideas?

**Comment by segiddins** [comment] 2015-02-08 06:18
This is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/3082, which has been fixed.

**Closed by segiddins** 2015-02-08 06:18 UTC
