### ISSUE TITLE
<realm/util/features.h> not found

### ISSUE THREAD

**Issue by gkaimakas** [CocoaPods/CocoaPods#4754] opened 2016-01-12 12:37 UTC
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

I upgraded to version 1.0.0-beta.2 today and run pod install on my project that until yesterday worked great. When the installation was complete I got an error from Realm that `<realm/util/features.h> was not found`. I cleaned the project and tried again but the error persisted. I then deleted the .xcworkspace, podfile.lock and pods folder, run `pod install` again but the error didn't go again. I reverted back to version 0.39.0 and then I got the following errors when I ran `pod install`.

I had to follow the procedure described here to make my project build again without errors  [#3092](https://github.com/realm/realm-cocoa/issues/3092#issuecomment-170893079)

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 219cc1b1b6eaa7874e11a38b53f54d60a820ff5d
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '8.1'
use_frameworks!

target 'Jokes' do

    pod 'Alamofire', '~> 3.0'
    pod 'AlamofireImage', '~> 2.0'
    pod 'Armchair', '~> 0.1.1'
    pod 'Crashlytics'
    pod 'EZLoadingActivity'
    pod 'Fabric'
    pod 'Ion', :git => 'https://github.com/gkaimakas/Ion.git', :tag => '0.1.1'
    pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
    pod 'RealmSwift'
    pod 'SwiftyDrop', '~>2.0'
    pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
    pod 'SwiftyUserDefaults'

end

target 'JokesTests' do

    pod 'Quick', '~> 0.8.0'
    pod 'Nimble', '3.0.0'

end
```

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007f83d16477b8>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by orta** [comment] 2016-01-12 12:43
Dupe of #4741

**Comment by iGranDav** [comment] 2016-01-15 13:20
@orta the issue after reverting to cocoa pods 0.39 is indeed a duplicate of #4741 but the original issue with the import which is not working on Realm as a dynamic framework with Cocoapods 1.0.0.beta2 isn't marked as pending anywhere :/

Corresponding issue in Realm repository is https://github.com/realm/realm-cocoa/issues/3052

**Comment by orta** [comment] 2016-01-15 13:37
Makes sense :+1:

**Comment by enricenrich** [comment] 2016-01-21 23:43
Any update on this? @orta

**Comment by orta** [comment] 2016-01-22 14:18
This is on realm's end, see https://github.com/realm/realm-cocoa/issues/3052

**Comment by segiddins** [comment] 2016-03-13 00:09
I think we can close this, as the linked-to realm issue has been closed.

**Closed by segiddins** 2016-03-13 00:09 UTC
