### ISSUE TITLE
Path passed to install_resource is incorrect for Hockey App

### ISSUE THREAD

**Issue by tlandsmancars** [CocoaPods/CocoaPods#5396] opened 2016-05-23 20:48 UTC
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Tried to do a Jenkins build after updating project with CocoaPods 1.0.0

## What did you expected to happen?
Build to succeed.

## What happened instead?

Build Failed

The issue appears to be that the PODS_CONFIGURATION_BUILD_DIR variable in Pods-Target-resource.sh is creating an incorrect path.  this is the same issue others have reported here https://github.com/CocoaPods/CocoaPods/issues/4963.  that issue was closed but seems like the problem is persisting.  

Here's a code snippet: 
if [[ "$CONFIGURATION" == "AdHoc" ]]; then
  install_resource "GoogleAppIndexing/Resources/GoogleAppIndexingResources.bundle"
  install_resource "$PODS_CONFIGURATION_BUILD_DIR/HockeySDK/HockeySDKResources.bundle"
  install_resource "IQKeyboardManager/IQKeyBoardManager/Resources/IQKeyboardManager.bundle"
  install_resource "SVProgressHUD/SVProgressHUD/SVProgressHUD.bundle"
fi

Note HockeySDK is the only one with PODS_CONFIGURATION_BUILD_DIR.  Its the only one failing.

**Comment by segiddins** [comment] 2016-05-23 20:49
What command are you using to build? Note that you need to set `BUILD_DIR` instead of `CONFIGURATION_BUILD_DIR`.

**Comment by neonichu** [comment] 2016-05-24 02:55
Likely a duplicate of #5358

**Comment by tlandsmancars** [comment] 2016-05-24 14:42
Yes, its the same issue as #5358.

**Closed** 2016-05-24 15:02 UTC
Labels: s1:awaiting input
