### ISSUE TITLE
In a podspec, is there a way to know that whether the podfile declares use_frameworks

### ISSUE THREAD

**Issue by Tony1023** [CocoaPods/CocoaPods#9050] opened 2019-07-25 19:21 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Written a pod spec that runs different codegen commands depending on whether or not to `use_frameworks`

Is there a way to add an if branch on whether or not `use_frameworks!` is declared in the `Podfile`?

**Comment by dnkoutso** [comment] 2019-07-25 19:23
No there is no way. And this is by design. Pod authors at least currently have no way to specify how their pod is packaged as a framework or a static library and this decision is left to consumers.

We are looking into 1.8.x or 1.9.x to enhance this. Closing for now and we continue this discussion further.

**Comment by dnkoutso** [comment] 2019-07-25 19:24
You can also include a `script_phase` to do a bunch of stuff during `xcodebuild` invocation including loading the users or pods project and inspecting that.

**Comment by dnkoutso** [comment] 2019-07-25 19:24
you can perhaps read `MACH-O-TYPE` in your script phase.

**Closed by dnkoutso** 2019-07-25 19:23 UTC
Labels: t4:question

**Comment by Tony1023** [comment] 2019-07-25 19:55
@dnkoutso Thanks for your suggestions. Will look into that later. But is there a way to actively pass custom args from Podfile to podspec? Like `pod ‘mypod’ :path => ‘path’, :args => ‘args’`? I can make the podfiles stick to this protocol.

**Comment by dnkoutso** [comment] 2019-07-25 20:08
you cannot pass args today but you _can_ add a [script_phase](https://guides.cocoapods.org/syntax/podspec.html#script_phases) in you `podspec` that will run as part of `xcodebuild` during compilation.

From there you can access the Xcode build environment including `MACH-O-TYPE`
