### ISSUE TITLE
Error pushing pod - build.sh: No such file or directory.

### ISSUE THREAD

**Issue by pepibumur** [CocoaPods/CocoaPods#5922] opened 2016-09-21 07:31 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I tried to push the pod from the tag `3.0.0-alpha.1` of [SugarRecord](from https://github.com/carambalabs/SugarRecord). I did it with

```
pod trunk push --allow-wwarnings --verbose
```

*Note: Using CocoaPods 1.1.0 release candidate 2`

## What did you expect to happen?

Start validating the pod and return an error only in case the validation fails.

## What happened instead?

I got an error when the script started validating complaining about a script not found:

```bash
⋊> ~/c/SugarRecord on master ◦ pod trunk push --verbose --allow-warnings                                                                                                                                                                                     09:25:25

[!] Found podspec `SugarRecord.podspec`

Updating spec repo `master`
Validating podspec
    SugarRecord (3.0.0-alpha.1) - Analyzing on iOS 8.0 platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods-App`: (``)

Fetching external sources
-> Fetching podspec for `SugarRecord` from `/Users/pedropinerabuendia/code/SugarRecord/SugarRecord.podspec`

Resolving dependencies of

Comparing resolved specification to the sandbox manifest
  A Realm
  A RealmSwift
  A Result
  A SugarRecord

Downloading dependencies

-> Installing Realm (1.1.0)
 > Git download
 > Git download
     $ /Applications/Xcode.app/Contents/Developer/usr/bin/git clone https://github.com/realm/realm-cocoa.git /var/folders/gh/0gdypwb52wqck30b67x95_7r0000gp/T/d20160921-57794-6rva7h --template= --single-branch --depth 1 --branch v1.1.0
     Cloning into '/var/folders/gh/0gdypwb52wqck30b67x95_7r0000gp/T/d20160921-57794-6rva7h'...
     Note: checking out '5fbb4ce86b0679c2ced0babd2f1cfaf33f5dd68f'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b <new-branch-name>

     $ /Applications/Xcode.app/Contents/Developer/usr/bin/git submodule update --init --recursive
 > Running prepare command
   $ /bin/bash -c  set -e sh build.sh cocoapods-setup
   sh: build.sh: No such file or directory
 -> SugarRecord (3.0.0-alpha.1)
    - ERROR | [iOS] unknown: Encountered an unknown error (/bin/bash -c
set -e
sh build.sh cocoapods-setup

sh: build.sh: No such file or directory

/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/executable.rb:69:in `execute_command'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/executable.rb:27:in `block in executable'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:66:in `block (2 levels) in run_prepare_command'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `chdir'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:60:in `block in run_prepare_command'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:59:in `run_prepare_command'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_preparer.rb:37:in `prepare!'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:202:in `copy_and_clean'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:159:in `block (2 levels) in uncached_pod'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:157:in `each'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:157:in `block in uncached_pod'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:181:in `in_tmpdir'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:153:in `uncached_pod'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/downloader.rb:42:in `download'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_installer.rb:120:in `download_source'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/pod_source_installer.rb:60:in `install!'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:355:in `install_source_of_pod'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:322:in `block (2 levels) in install_pod_sources'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:85:in `titled_section'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:321:in `block in install_pod_sources'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:313:in `each'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:313:in `install_pod_sources'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:159:in `block in download_dependencies'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:157:in `download_dependencies'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/validator.rb:384:in `block in download_pod'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/validator.rb:384:in `each'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/validator.rb:384:in `download_pod'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/validator.rb:280:in `block in perform_extensive_analysis'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/validator.rb:274:in `each'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/validator.rb:274:in `perform_extensive_analysis'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/validator.rb:79:in `validate'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:109:in `validate_podspec'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:61:in `run'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/bin/pod:23:in `load'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/bin/pod:23:in `<main>'
) during validation.

[!] The spec did not pass validation, due to 1 error.

/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:111:in `validate_podspec'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:61:in `run'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/bin/pod:23:in `load'
/Users/pedropinerabuendia/.rbenv/versions/2.3.0/bin/pod:23:in `<main>'
```

> Note: I noticed that after that failure the remote git repository was replaced by the CocoaPods specs one.

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9aef650ebcccbc4d5870c013bd736753a4fd5fdd
               soundcloud - git@github.com:soundcloud/ios-privatepods.git @ 4d47c387046e90f722178087686d6f5a763f2545
```

### Installation Source

```
Executable Path: /Users/pedropinerabuendia/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.1
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/carambalabs/sugarrecord

**Comment by neonichu** [comment] 2016-09-21 09:56
I think `build.sh` is a part of the Realm Pod, but in any case, it looks like here the `chdir` problem still happens :/

Could you please retry after setting the `FORK_XCODE_WRITING` environment variable to `true`? This uses an alternative, slower implementation that should never be affected by the `chdir` problem.

**Comment by pepibumur** [comment] 2016-09-21 11:45
It worked with that variable @neonichu . Is this then a Realm bug in their CocoaPods setup?

**Comment by neonichu** [comment] 2016-09-21 12:21
Nah, it's definitely an issue inside CP

**Comment by PetresS** [comment] 2016-09-21 14:45
hey,

at first i want to ask where i can find this "FORK_XCODE_WRITING" variable.
On my printenv-list there is no "FORK_XCODE_WRITING" listed.

The next point is that i have a "pod repo push"-error, too.

I'm using xcode 8 and cocoapods-1.1.0.rc.2

I've created a completly new xcode project with **no** individual content. At next i created the podfile and the .podspec (with pod init & pod spec create test).
In .podspec i edited s.source to my git-repo.

now i call:
pod repo push cocoapodsSpecRepo test.podspec --allow-warnings

and this is the result:
```
Validating spec
 -> test
 -> test (0.0.1)
    - ERROR | license: Sample license type.
    - WARN  | homepage: The homepage has not been updated from default
    - WARN  | summary: The summary is not meaningful.
    - ERROR | description: The description is empty.
    - WARN  | url: There was a problem validating the URL http://EXAMPLE/test.
    - ERROR | [OSX] unknown: Encountered an unknown error (Unable to create a source with URL git@gitlab.gruppe.de:iOS/cocoapodsSpecRepo.git) during validation.

[!] The `test.podspec` specification does not validate.
ERROR: Build failed: exit status 1
```

and the --verbose output is:
```
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/sources_manager.rb:42:in `find_or_create_source_with_url'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:654:in `block in sources'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `map'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:653:in `sources'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:144:in `resolve_dependencies'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `block in download_pod'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `each'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:373:in `download_pod'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:269:in `block in perform_extensive_analysis'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `each'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:81:in `validate'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/push.rb:125:in `block in validate_podspec_files'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/push.rb:119:in `each'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/push.rb:119:in `validate_podspec_files'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/push.rb:64:in `run'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/bin/pod:23:in `load'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/bin/pod:23:in `<main>'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
) during validation.

[!] The `test.podspec` specification does not validate.

/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/push.rb:130:in `block in validate_podspec_files'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/push.rb:119:in `each'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/push.rb:119:in `validate_podspec_files'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command/repo/push.rb:64:in `run'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/bin/pod:23:in `load'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/bin/pod:23:in `<main>'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `eval'
/Users/gitlabcirunner/.rvm/gems/ruby-2.3.1/bin/ruby_executable_hooks:15:in `<main>'
ERROR: Build failed: exit status 1
```

**Comment by DenHeadless** [comment] 2016-09-24 09:21
I can confirm FORK_XCODE_WRITING fixes the issue. For some reason I only have problems with Realm/RealmSwift dependency, and have been able to successfully push other CocoaPods with dependencies to trunk.

However pod, that has a RealmSwift dependency, has been consistently failing until i found this issue. After that, i was able to successfully push my CocoaPod to trunk:

```bash
FORK_XCODE_WRITING=true pod trunk push DTModelStorage.podspec
```

**Comment by PetresS** [comment] 2016-09-27 12:46
heyhey,

i tryed with: 
`FORK_XCODE_WRITING=true pod repo push cocoapodsSpecRepo test.podspec --allow-warnings`

and i still have the same "specification"-problem

**Comment by neonichu** [comment] 2016-09-28 13:37
Looks like this is actually a duplicate of the older #5873

**Closed by neonichu** 2016-09-28 13:37 UTC
Labels: s1:awaiting input
