### ISSUE TITLE
Support custom header files

### ISSUE THREAD

**Issue by knox** [CocoaPods/CocoaPods#3708] opened 2015-06-20 15:59 UTC
I am trying to package a blob of legacy code into a nice podspec. This legacy code has some special header files and even using ```#import "something.cpp"``` so i came up with the following podspec (simplified example):

    s.source_files  = 'Classes/**/*.{h,hpp,c,cpp,mm}',
                      'Classes/something/filewithoutextension',
                      'Classes/something/anotherfilewithoutextension'

      s.private_header_files = 'Classes/something/*.h',
                           'Classes/something/filewithoutextension',
                           'Classes/something/anotherfilewithoutextension',
                           'Classes/something/file.cpp',
                           'Classes/another/export_priv.h'

The good thing is that this podspec works well when used from local path but unfortunately it does not lint because these special header files are not symlinked:

    The pattern matches non-header files

I have also tried to add custom ```HEADER_SEARCH_PATH```  in my spec's ```xconfig``` but that does not work well due to the fact that the actual path varies when the pod is included from a local path

      'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/MyPod/Classes/something"',

How can i create a podspec that lints even with these custom of header files without making changes to the legacy code?

**Comment by neonichu** [comment] 2015-06-21 01:53
I would recommend changing the import statements in your legacy code via `prepare_command` ([see guides](https://guides.cocoapods.org/syntax/podspec.html#prepare_command)) - that way you can keep upstream unchanged but still fix those header issues for the podspec.

**Comment by waTeim** [comment] 2015-07-29 09:44
I have a similar problem with an wrapped C++ library.  Arbitrary file extensions (or no extension) are perfectly fine in C++. Also, (same project) there are multiple files with the same file name but at located in different directories which is also completely legal and expected because they are uniquely identified by path (no flattening).  How to disable these checks?  or is Xcode doing this (recently upgraded to version 6.4)?  

Relevant:

     s.vendored_libraries = 'lib/*.a'
     s.xcconfig = { 'HEADER_SEARCH_PATHS' => '"$(PODS_ROOT)/odb/include"' }
     s.private_header_files = s.source_files =
       'include/**/*.{h,hxx,txx,ixx,options}',
       'include/**/**/*.{h,hxx,txx,ixx,options}',
       'include/**/**/**/*.{h,hxx,txx,ixx,options}'
       'include/**/**/**/**/*.{h,hxx,txx,ixx,options}'
     s.header_mappings_dir = 'include'

**Comment by waTeim** [comment] 2015-07-29 20:14
An update.  I just read thad frameworks are nothing more than renamed static library + a particular directory structure.  Can the workaround simply be that?  Turn the whole thing into a framework?

**Comment by waTeim** [comment] 2015-08-01 18:31
Need an answer here.  Something that can done immediately.  A workaround is ok (e.g hack the code so that the check is disabled).  Maybe something where the list of allowed extensions is arbitrarily? The prepare_command idea is not viable.

**Comment by segiddins** [comment] 2015-08-25 07:34
The 'hack' is to rename those files with a `prepare_command` to something that looks like a valid header extension

**Comment by waTeim** [comment] 2015-09-15 00:46
NO.  That would be thousands of files from a 3rd party of unknown structure that MUST be named the way they are named because that's the way the 3rd party wants them. As I said this is C++, all extensions are valid.  Speaking of valid, what valid reason do you have to require this?  Is this enforced somehow by Xcode?  I don't think so. Xcode supports C++ does it not?  It's the Cocoapods framework that is invalid when it insists on a particular C++ file naming scheme.

The hack I want is how to I remove the check.  I don't need you to do it, just a little guidance, something like "that check is implemented here, comment it", and "when this section of code runs, it currently assumes that file has an extension in the list and it causes an error comment that too and do nothing with it" and the will be the correct behavior.

Or like I said, just a little guidance in making a vendored framework.  That's supported too, right?  All I have is a .a and some arbitrary header files.  I don't need/want to compile anything in the Pods I need to compile against them and link to them, that's it.

**Comment by orta** [comment] 2015-09-15 13:12
@waTeim you really should tone down the aggression in your posts. "Need an answer here", "NO". You're asking people to spend their free time helping you, and not giving much incentive for people to do that.

**Comment by waTeim** [comment] 2015-09-15 20:08
@orta If my belligerence is too much then I guess take it simply as (semi) constructive feedback and be done with it, but in so doing consider my viewpoint of someone just trying to use Cocoapods in a simple though atypical way and a history of (from my perspective) being ignored, and an ever escalating tone just to get someone to respond while at the same time having to deal with arbitrary rule changes like these that make sense from the normal XCode Objective-C/Swift perspective while disadvantaging with no workaround and no documentation someone using C++.

At least I thought I had already provided sufficient information to indicate 
* lib is way too intricate to even think about modifying (note the depth of the include tree).
* undergoes arbitrary changes that are internally consistent but would break any sort of modification (from a 3rd party).
* is already perfectly valid
* there are actually 0 source files, only a .a and some header files, the directive `s.source_files =`  exists because header files are not copied unless they are also source files [for reference](https://groups.google.com/forum/#!searchin/cocoapods/wateim/cocoapods/XqkV6mYyXos/DMyL4UWSZIUJ)  -- heh odb again.
* i realized this is was catching you off guards so was willing to  privately hack the source to disable the feature while you thought about it.
* was willing to reverse course and adopt the new vendored_frameworks feature, but the documentation is centered around compilation of source (inapplicable), just needed some indication if it were at all possible.

And what do I get in response?  -- you guys telling me to do the thing I just told you I could not do.  
Yea, I'm mad.

**Comment by segiddins** [comment] 2015-09-16 00:25
Sorry if you're mad, but we build CocoaPods in our spare time. It's never been meant to be a monolithic project that supports every possible project setup, nor have we ever claimed it as such. Getting mad at us certainly won't help get the problem solved, and it disinclines us from looking at this issue compared to the others people are filing. 

Please be respectful of the fact that Orta, myself, and the rest of the CocoaPods team do this as a hobby, for free, and don't attack us.

**Comment by waTeim** [comment] 2015-09-16 01:35
Haha, I feel there might be some culture-clash going on here because this reads like one of those sorry-not-sorry responses.  But, I feel you, you started with a small project under control and now it's too big to keep tabs on and some things are getting missed and you don't have the resources to deal with them in a timely manner.   Meanwhile I have unrealistic expectations.  BTW the note about "something needing to be done immediately" was accurate, I had to abandon what I was doing; it's ok though the backup was to keep what had been previously done and that still works. I didn't know that at the time however.

Ok so let's set that aside ... objectively:  

The issue is that though most C++ projects do restrict themselves to a standard set of file extensions, there is no requirement to do so. For whatever reason the author has decided that it would be even
more confusing (and misleading) to try to shoe horn them in.  Strict enforcement of such rules
effectively blocks the consumption of these kind of external libraries.  It looks like both the original 
author and I have exactly the same needs.  External compilation of a library to be included with the Cocopods mechanism, we both think this (this issue) is the way to accomplish it since that's historically
been supported.

I think if this were to be taken up, it could be addressed in the following way.

### Option 1
* some default behavior (perhaps as it exists now).
* some sort of command line option to pod and/or some override in the podspec
* under the conditions of relaxing the rules above, then there's a default rule is to do nothing with the source
* as an extra not required but could be thought about later is a set of default rules (copy, ignore) something like that.
* extending from above, it would be nice to have some rule to not treat unrecognized source as source to XCode to prevent the annoying warning messages.

### Option 2
Remove the requirement that header files must also be source files.  The only reason that we are
encountering this problem is that there's no way to infer how to create a build rule from unknown extensions.  But neither the original author nor I need that, because there's no build that needs to happen, it all occurs outside Xcode.  It's the source code in the XCode project that uses the header
files and links to the lib.

### Option 3
On the other hand. If creating a framework is a better  approach, that's fine and this ceases to be an issue or requirement, but I have not found enough documentation to determine if it's possible.  We
could use some help here.

**Comment by neonichu** [comment] 2015-10-06 00:09
Option 3 seems to be your best bet. 

You can see an example for the use of `vendored_frameworks` here: <https://github.com/layerhq/releases-ios/blob/master/LayerKit.podspec>. Another option would be utilising `prepare_command` similar to OpenSSL: <https://github.com/FredericJacobs/OpenSSL-Pod/blob/master/1.0.204.1/OpenSSL.podspec#L14>

**Closed by neonichu** 2015-10-06 00:09 UTC
Labels: t3:discussion

**Comment by maross** [comment] 2017-05-15 09:04
Does Cocoapods support header files with no extension? 
Which kind of reges should I use in order to filter them?
Thanks all

**Comment by ccwinner** [comment] 2018-04-19 01:36
I met the same problem while dealing with C++ headers with no extension, the headers are all within a self-wrapped repository which keeps being updated with a third-party repo., so the renamed trick is not a good idea.

**Comment by mozeryansky** [comment] 2018-08-10 21:55
The correct solution to this is to tell the Xcodeproj of other valid header extensions. Right now it's a hard coded list:
- https://github.com/CocoaPods/CocoaPods/blob/43d3bc24c54dbce30a5a4fc57a38ff6f5a3cfccf/lib/cocoapods/sandbox/file_accessor.rb#L12
- https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb#L419

There should be a way for me to specify custom extensions.

My current trick is to add the files as resources, so the files will be copied to the Pod folder but not included in the compile phase.
