### ISSUE TITLE
0.39.beta1 installation

### ISSUE THREAD

**Issue by MickeyHub** [CocoaPods/CocoaPods#4085] opened 2015-08-26 14:38 UTC
Users/mac/.rvm/rubies/ruby-2.2-head/lib/ruby/site_ruby/2.2.0/rubygems/core_ext/kernel_require.rb:128:in `require': cannot load such file -- cocoapods/gem_version (LoadError)

**Comment by twc-rhedin** [comment] 2015-08-26 14:44
+1

**Comment by AnthonyMDev** [comment] 2015-08-26 16:51
+1 after update to new beta, all `pod` commands result in the following error:

````
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- cocoapods/gem_version (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.1/lib/cocoapods.rb:21:in `<module:Pod>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.1/lib/cocoapods.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.1/bin/pod:25:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
````

**Comment by segiddins** [comment] 2015-08-26 16:58
I can't reproduce this on my local machine... can you verify that this is an issue introduced in 0.39.0.beta.1?

**Comment by AnthonyMDev** [comment] 2015-08-26 17:42
This issue did not exist until I updated to 0.39.0.beta.1
In order to use Cocoapods i had to uninstall all versions then re-install 0.38.2

**Comment by segiddins** [comment] 2015-08-26 17:44
It seems like a rubygems issues to me... what's the output of `gem --version`?

**Comment by segiddins** [comment] 2015-08-26 17:46
Also, can you share the contents of `/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.1/bin/pod:25` ? Thanks!

**Comment by AnthonyMDev** [comment] 2015-08-26 17:49
gem version in `2.0.14`
I've uninstalled the beta version so I don't have that folder contents anymore.

**Comment by segiddins** [comment] 2015-08-26 17:58
Does running `pod _0.39.0.beta.1_` work? I think this is a bug in RubyGems thats been fixed for at least a year, fwiw

**Comment by AnthonyMDev** [comment] 2015-08-26 19:45
After updating to the newest version of RubyGems and then re-installing cocoa pods `0.39.0.beta.1`, cocoa pods will now work, but I'm getting the following warning on `pod update`:

````
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.0/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.0/lib/cocoapods_plugin.rb
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:121:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
````

**Comment by AnthonyMDev** [comment] 2015-08-26 19:47
Running `pod _0.39.0.beta.1_` results in the same original error that I posted.

**Comment by mobiletoly** [comment] 2015-08-26 20:27
Seems like it is a problem with access permissions, e.g.:

$ ls -alF /Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0.beta.1/lib/cocoapods-core/specification

...
...
-rw-------   1 root  wheel  46924 Aug 26 13:08 dsl.rb
...

dsl.rb (and other rb files) are accessible by root only. Running "sudo pod" works but obviously not the best solution. Running chmod for all .rb files to add "rw" permission to all .rb files works as well, but annoying. Hopefully it will be fixed soon.

**Comment by segiddins** [comment] 2015-08-26 20:39
This sounds like a borked Ruby / RubyGems installation to me, rather than a CocoaPods issue?

**Comment by segiddins** [comment] 2015-08-26 20:47
This is odd... `git` isn't showing me those file permissions having changed since the last release

**Comment by mobiletoly** [comment] 2015-08-26 21:00
BTW, I have published a little "tutorial" that explains how to stop using system-wide ruby. This should help in stopping using "sudo" all the time with gems (so you could use "gem install cocoapods" instead of "sudo gem install cocoapods"). Once you do it, you are not going to see permissions error for 0.39.0.beta.1 (and other version):

http://stackoverflow.com/questions/25165016/cant-get-to-work-cocoapods-and-yosemite/32236562#32236562

That is a right thing to do anyway, sudo shouldn't be used for something like "gem install" unless it is really necessary.

**Comment by orta** [comment] 2015-08-26 21:49
This is not a system ruby vs rvm/brew install ruby/whatever debate, the first poster uses RVM, and some of the latter are using system ruby. 

So far I've ran `gem install cocoapods --pre` on three machines and had no problems.

``` sh
~ ⏛  gem install cocoapods --pre
Fetching: cocoapods-core-0.39.0.beta.1.gem (100%)
Successfully installed cocoapods-core-0.39.0.beta.1
Fetching: xcodeproj-0.27.0.gem (100%)
Successfully installed xcodeproj-0.27.0
Fetching: cocoapods-downloader-0.9.2.gem (100%)
Successfully installed cocoapods-downloader-0.9.2
Fetching: cocoapods-stats-0.6.0.gem (100%)
Successfully installed cocoapods-stats-0.6.0
Fetching: cocoapods-try-0.5.0.gem (100%)
Successfully installed cocoapods-try-0.5.0
Fetching: cocoapods-trunk-0.6.2.gem (100%)
Successfully installed cocoapods-trunk-0.6.2
Fetching: cocoapods-0.39.0.beta.1.gem (100%)
Successfully installed cocoapods-0.39.0.beta.1
7 gems installed

~ ⏛  pod try Google
Updating spec repositories
```

At a guess, @AnthonyMDev @MickeyHub @twc-rhedin are you using El Cap?

**Comment by AnthonyMDev** [comment] 2015-08-26 21:53
@orta I'm using Yosemite.

@mobiletoly 's solution worked for me. But I don't think that every user should or will know to stop using the system-wide ruby.

**Comment by idokleinman** [comment] 2015-08-27 00:27
+1 happens here too
OSX 10.10.5

**Comment by segiddins** [comment] 2015-08-27 00:33
No need for any more :+1:s -- I'm going to release a beta 2 shortly that should see this fixed.

**Comment by segiddins** [comment] 2015-08-27 03:40
Will be fixed in 0.39.0.beta.2, which I'm releasing right now.

**Closed by segiddins** 2015-08-27 03:40 UTC

**Comment by mohitsharma0690** [comment] 2015-08-27 18:42
I still seem to have this issue on 0.39.beta2 

```
>> pod --version

Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require': cannot load such file -- cocoapods/command/repo/add (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command/repo.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:54:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:22:in `<class:Command>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:16:in `<module:Pod>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:11:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/bin/pod:44:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
```

My `gem version is 2.4.8`

@mobiletoly solution didn't work for me. I seem to have the right permissions.

**Comment by segiddins** [comment] 2015-08-27 19:23
Yup, there's a new issue for beta 2

**Comment by Grubas7** [comment] 2015-08-27 20:31
I have same problem as @mohitsharma0690.

**Comment by toriaezunama** [comment] 2015-08-27 21:10
+1

**Comment by segiddins** [comment] 2015-08-27 21:13
Please, stop :+1:-ing. We know this is an issue, we have a new issue opened for related issues in Beta 2, and we're working on it.

**Comment by dstimm-gpfw** [comment] 2015-08-28 00:59
FUCK

**Comment by dstimm-gpfw** [comment] 2015-08-28 00:59
How do I fix?

**Comment by Grubas7** [comment] 2015-08-28 08:30
@dstimm-gpfw install beta 3. Works for me.

**Comment by marcelohammes** [comment] 2015-08-29 19:30
Install beta 3 works for pod update command.
But now I can't build the project.

The old errors now are Warnings and when I try build i got the error "Undefined symbols for architecture armv7".

I already check the "valids architectures", the "Build Active Architecture Only" and the "Other Linker Flags"

It is weird that those libraries are not being automatically retrieved/found (usually it does).
![image](https://cloud.githubusercontent.com/assets/936095/9563920/d7bab4f0-4e6a-11e5-8e11-1393cef50bc5.png)
