### ISSUE TITLE
Specifying a platform does not set targeted iOS version for installed pods

### ISSUE THREAD

**Issue by jbelkins** [CocoaPods/CocoaPods#8165] opened 2018-10-08 17:30 UTC
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I updated the following line at the top of my Podfile (in global space) to specify iOS 11.0 instead of 10.0:
```
platform :ios, "11.0"
```

## What did you expect to happen?

When archiving, I expected all of my Pods to build 64-bit only, based on the specified iOS target version of 11.0.

## What happened instead?

My pods built architectures (32- and/or 64-bit) based on the supported iOS version specified in their respective podspecs.
Using a post-install hook to set `config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.0'` for every pod's build configurations, I was able to make each pod build only 64-bit.

So, should the `platform` Podspec command set the targeted iOS version for all pods in the affected target(s)?  My understanding is that it should; but I'm not sure if this is intended behavior or a bug.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.4p296 (2018-03-28 revision 63013) [x86_64-darwin17]
    RubyGems : 2.6.14.1
        Host : Mac OS X 10.14 (18A391)
       Xcode : 10.0 (10A255)
         Git : git version 2.17.1 (Apple Git-112)
Ruby lib dir : /Users/josh/.rubies/ruby-2.4.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 987a7421e4aa664f11f910372621a4b61df32833
```

### Installation Source

```
Executable Path: /Users/josh/.gem/ruby/2.4.4/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment] 2018-10-08 17:34
I believe this is fixed in 1.6.0.beta.1 already https://github.com/CocoaPods/CocoaPods/pull/7932

**Comment by amorde** [comment] 2018-10-08 17:59
Yup it should be - can you try out the beta? You can install it with [Bundler](https://bundler.io) or with `gem install cocoapods --pre`

**Comment by jbelkins** [comment] 2018-10-08 18:47
I did the following:
- Specified Cocoapods version `1.6.0.beta.1` in my `Gemfile`
- Ran a `bundle install`
- Removed the post-install hook that sets `IPHONEOS_DEPLOYMENT_TARGET` to "11.0" from my `Podfile`
- Erased my workspace's `Pods` directory to ensure the install was clean
- Ran `bundle exec pod install`
After the install, my pod targets once again have versions as set in their podspecs, not "11.0" as specified in my Podfile.

Anything else to check?

**Comment by amorde** [comment] 2018-10-08 18:55
What is the deployment target of your project set to?

**Comment by jbelkins** [comment] 2018-10-08 18:57
Every target in my project is set to iOS Deployment Target of 11.0

**Comment by amorde** [comment] 2018-10-08 19:37
Ok, thanks. Sounds like something is off here. Do have a sample project I could test on? 

Also from [this comment](
https://github.com/CocoaPods/CocoaPods/issues/8165#issuecomment-427940598) it sounds like the issue is actually that the pods are using an incorrect deployment target (should be 11.0, instead is using the podspec-defined version) - is that correct?

**Comment by jbelkins** [comment] 2018-10-08 20:09
I can't post the project where I am having this issue; I'll have to create a sample and try to reproduce.

And yes, that is correct, I expect that setting a target iOS version in my `Podfile` using the `platform` directive should adjust my installed pods' target iOS version to the same.  If that is not how Cocoapods is intended to behave, that's OK; it's possible that I misunderstand the intended effect of `platform` in my `Podfile`.

(This reached my attention because after setting iOS 11.0 as the targeted iOS version in my `Podfile` and throughout my app, several of my installed pods were still building 32-bit binaries.  When Xcode sees that iOS 11.0 or higher is targeted, it removes `armv7` from the architectures, and sure enough several of my pods were targeting versions from iOS 8.0 to 10.0.)

**Comment by jbelkins** [comment] 2018-10-11 22:49
Sorry for the delay; here is a demo project repo:
https://github.com/jbelkins/TargetVersionSample
It is configured with Cocoapods 1.6.0.beta.1 and the Braintree pod (I don't think it matters what you use as a pod; the locked version of Braintree targets iOS 7.0 though.)

- Clone this repo, then do a `bundle install` and `bundle exec pod install` within.
- Open `TargetVersionSample.xcworkspace` in Xcode 10.
- In the file navigator, select the `Pods` project file, then within select the Braintree target.
- Select Build Settings and look at the setting for "iOS Deployment Target".
- It will be "iOS 8.0".  I would expect it to be "iOS 11.0" based on the platform setting in the Podfile.

Now, uncomment the indicated line in the Podfile and `bundle exec pod install` again.
Braintree's iOS deployment target will now be "iOS 11.0", but I don't think it should be necessary to override a build setting this way to get the pod's targeted iOS version to match the project's.

**Comment by amorde** [comment] 2018-10-12 00:07
Thank you for the sample, I'll look into it when I find some time

**Comment by amorde** [comment] 2019-01-23 22:58
I still haven't gotten the chance to look into this yet

**Comment by amorde** [comment] 2019-01-29 03:14
Ok, so I've confirmed what you described is happening, but I also am not sure if the expected behavior here is to set the deployment target of all pods included in the target to the platform you specified.

Currently CocoaPods checks the deployment target specified by the Podspec, and uses that or the minimum available (ex. if `use_frameworks!` is specified then it must be at least iOS `8.0`)

This is the place that determines the platform to set for Pod targets:

https://github.com/CocoaPods/CocoaPods/blob/6b079100644b2d3ac8266ce3644e21c8028a2dec/lib/cocoapods/installer/analyzer.rb#L751-L775

Where we _do_ use the platform specified in the Podfile is on the `Pods.xcodeproj` as well as the Aggregate Target (`Pods-MyApp.framework`)

This is an easy fix if it is decided that the current behavior is incorrect

**Comment by amorde** [comment] 2019-01-29 03:16
Also, just realized this is a duplicate of #7314 - that issue has some additional discussion around it

**Closed** 2019-05-06 04:21 UTC
Labels: s1:awaiting input
