### ISSUE TITLE
WatchKit 1 Extension Not Copying Needed Swift Libs

### ISSUE THREAD

**Issue by bassrock** [CocoaPods/CocoaPods#4192] opened 2015-09-17 03:01 UTC
While working an a WatchKit 1 app with Cocopaods, the libswiftWatchKit.dylib is not getting copied and getting this error:
```
dyld: Library not loaded: @rpath/libswiftWatchKit.dylib
  Referenced from: /Users/daniel/Library/Developer/CoreSimulator/Devices/D4E5A57F-314E-411C-B18C-37E3E43A7F5A/data/Containers/Bundle/Application/E9C6903C-EB7D-46B9-99D6-DAB53646BC93/Acme.app/PlugIns/Acme WatchKit 1 Extension.appex/Acme WatchKit 1 Extension
  Reason: image not found
```

I had to manually add the following to the WatchKit 1 Extension Frameworks phase for it to load:

```
    echo "rsync -auv \"${SWIFT_STDLIB_PATH}/libswiftWatchKit.dylib\" \"${destination}\""
    rsync -auv "${SWIFT_STDLIB_PATH}/libswiftWatchKit.dylib" "${destination}"
    code_sign_if_enabled "${destination}/libswiftWatchKit.dylib"
```

**Comment by bassrock** [comment] 2015-09-19 03:50
This is on cocoapods 0.38.2 and on the 39.0beta4 btw

**Comment by segiddins** [comment] 2015-09-25 03:12
This is actually a duplicate of https://github.com/CocoaPods/CocoaPods/issues/4188, even though they manifest in different ways.

**Closed by segiddins** 2015-09-25 03:12 UTC
