### ISSUE TITLE
An error occurred! Help me!~

### ISSUE THREAD

**Issue by tuananhit91** [CocoaPods/CocoaPods#4226] opened 2015-09-21 03:33 UTC
Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=No+such+file+or+directory+%40+rb_file_s_stat+-+%2FUsers%2Fbmxstudio1%2FDesktop%2FiMusicPlayerDemo%2FPods%2FHeaders%2FPrivate%2FAFNetworking%2FUIActivityIndicatorView%2BAFNetworking.h&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

[!] Your Podfile has had smart quotes sanitised. To avoid issues in the future, you should not use TextEdit for editing it. If you are not using TextEdit, you should turn off smart quotes in your editor of choice.

**Comment by segiddins** [comment] 2015-09-21 12:23
Please share the entire error report, what you've posted doesn't quite have enough info for us to debug. Thanks!

**Comment by mailat** [comment] 2015-09-21 12:31
We have the same problem with a build which was working great until yesterday:

```
/usr/bin/pod install
```

### Report

* What did you do?
We just did a normal build. Latest stable version of Xcode, MacOS and cocoapods.

* What did you expect to happen?
The build to be created.

* What happened instead?
The error bellow which makes no sense because the file is a symbolic file.

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.10.5 (14F27)
       Xcode : 7.0 (7A220)
         Git : git version 2.2.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1919174d6b46acc65069d345cf6f71b99460489c
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '7.0'
pod 'AFNetworking', '~> 2.6'
pod 'MBProgressHUD', '0.8'
pod 'Facebook-iOS-SDK', '3.18.0'
pod 'UICKeyChainStore', '1.0.4'
pod 'QuickBlox', '~> 2.0'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'SWTableViewCell', '~> 0.3.7'
pod 'Fabric','1.2.8'
pod 'Crashlytics','3.0.11'
```

### Error

```
Errno::ENOENT - No such file or directory - /Users/appsbuilder/dev/workspace/OURPROJECT-iOS/Pods/BuildHeaders/AFNetworking/AFHTTPRequestOperation.h
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `symbolic_modes_to_i'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:926:in `fu_mode'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment] 2015-09-21 12:44
Looks like a dupe of #4227

**Closed by neonichu** 2015-09-21 12:44 UTC
