### ISSUE TITLE
Cocoa pods 0.36.* won't work with GoogleAnalytics-iOS-SDK dependency.

### ISSUE THREAD

**Issue by rckoenes** [CocoaPods/CocoaPods#3346] opened 2015-04-01 08:58 UTC
So I have the following private pod specs, which was validating in Cocoapods 0.35
Since I've upgraded to 0.36 it will not validate any more.
I can't seem to find the TagManager object for the 

```
Ld /var/folders/9r/y21mxssd6rgf6gbrlhqsqv5m0000gp/T/CocoaPods/Lint/build/Pods.build/Release-iphonesimulator/Pods-RKTagManager.build/Objects-normal/x86_64/RKTagManager normal x86_64
    cd /var/folders/9r/y21mxssd6rgf6gbrlhqsqv5m0000gp/T/CocoaPods/Lint/Pods
    export IPHONEOS_DEPLOYMENT_TARGET=5.1.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/Users/remmeltkoenes/.rbenv/bin:/usr/local/sbin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/texbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -dynamiclib -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.2.sdk -L/var/folders/9r/y21mxssd6rgf6gbrlhqsqv5m0000gp/T/CocoaPods/Lint/build/Release-iphonesimulator/Pods -F/var/folders/9r/y21mxssd6rgf6gbrlhqsqv5m0000gp/T/CocoaPods/Lint/build/Release-iphonesimulator/Pods -filelist /var/folders/9r/y21mxssd6rgf6gbrlhqsqv5m0000gp/T/CocoaPods/Lint/build/Pods.build/Release-iphonesimulator/Pods-RKTagManager.build/Objects-normal/x86_64/RKTagManager.LinkFileList -install_name @rpath/RKTagManager.framework/RKTagManager -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -Xlinker -objc_abi_version -Xlinker 2 -ObjC -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -mios-simulator-version-min=5.1.1 -framework Foundation -framework GoogleAnalytics_iOS_SDK -single_module -compatibility_version 1 -current_version 1 -Xlinker -dependency_info -Xlinker /var/folders/9r/y21mxssd6rgf6gbrlhqsqv5m0000gp/T/CocoaPods/Lint/build/Pods.build/Release-iphonesimulator/Pods-RKTagManager.build/Objects-normal/x86_64/RKTagManager_dependency_info.dat -o /var/folders/9r/y21mxssd6rgf6gbrlhqsqv5m0000gp/T/CocoaPods/Lint/build/Pods.build/Release-iphonesimulator/Pods-RKTagManager.build/Objects-normal/x86_64/RKTagManager
ld: warning: embedded dylibs/frameworks only run on iOS 8 or later
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_TAGManager", referenced from:
      objc-class-ref in RKTagManager.o
ld: symbol(s) not found for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

** BUILD FAILED **
```

Here is the pod spec
```
{
  "name": "RKTagManager",
  "version": "0.0.1",
  "summary": "Google TagManager wrapper.",
  "license": {
    "type" : "Closed Source",
    "text" : "This library is as is, not warrenty of any kind."
  },
  "platforms": {
    "ios": "5.1.1"
  },
  "requires_arc" : true,
  "source": {
    "hg": "private",
    "revision" : "RKTagManager-0.0.1"
  },
  "dependencies": {
    "GoogleAnalytics-iOS-SDK": []
  },
  "source_files": [
      "Source/RKTagManager/*.{h,m}"
  ]
}
```

**Comment by neonichu** [comment] 2015-04-01 13:16
Pretty sure this is a duplicate of #3106 - reexporting symbols does not work for certain vendored static libraries, it appears that the GoogleAnalytics-iOS-SDK pod is one of them. This only affects targets using frameworks, though.

By default CocoaPods >= 0.36.0 lints pods as frameworks, you can still lint as a static library using `--use-libraries`.

**Closed by neonichu** 2015-04-01 13:16 UTC

**Comment by mfrawley** [comment] 2015-05-05 10:15
This information is extremely important, and for all intents and purposes is buried. I had a pod compiling perfectly in XCode, but failing to link, of course only in Cocoapods.
  I read multiple GH issues similar to this without finding this nugget of information, then eventually after much frustration happened upon this thread, imho --use-libraries needs to be better explained, this tells me nothing:

```
--use-libraries    Linter uses static libraries to install the spec
```
Constructively, it could have an additonal note with a link to here or a note about it being related to "reexporting symbols does not work for certain vendored static libraries". Thoughts?

**Comment by neonichu** [comment] 2015-05-05 11:15
IMO, that would be still too vague to be useful for most people. Ideally, I'd like to list what makes those libraries "special". Can you share some more information about your pod?

BTW, CocoaPods 0.37.0 will link more vendored static libraries directly against the application target, see  #3468 for more information.

**Comment by mfrawley** [comment] 2015-05-05 11:58
Ah, that's great. I am using 0.36.3 as I thought 0.37.x was still unstable. We'll upgrade as soon as we can.
  Our pod is just part of an app, with views/controllers and has a dependency on GoogleAnalytics for behaviour tracking. I tried specifying the Google-analytics-iOS SDK as a dependency in the podspec and then tried manually vendoring. Obviously both approaches failed to lint without but work with the --use-libraries flag.

**Comment by neonichu** [comment] 2015-05-05 12:06
Ah, I see - the 0.37 changes won't really help you there. Transitive dependencies on static libraries are simply not possible for the common case with frameworks, this will be eventually solved by using dynamic libraries for closed source Pods.

Maybe we can link to a guides page from the usage info of `--use-libraries` which explains in which cases frameworks won't really work? cc @orta

**Comment by orta** [comment] 2015-05-05 12:29
is it something we can detect? right now a lot of this documentation is in Marius' blog posts introducing frameworks

**Comment by neonichu** [comment] 2015-05-05 12:58
Wouldn't know how to detect the reexporting symbols issue, it's not really distinguishable from symbols simply not existing.

The information is all there somewhere, but as @mfrawley, I'm wondering if we somehow can convey that linting with `--use-libraries` is the way to go for some cases from the linter help.

**Comment by jdolan** [comment] 2015-10-27 17:21
I would say the `--use-libraries` information even in this ticket is under-documented. Where does that flag go? In the Podfile? On the `pod install` command line?

I'm dealing with a stubborn Google Analytics pod that is preventing my tests from linking, and I'm totally stuck.

**Comment by orta** [comment] 2015-10-27 17:25
Use libraries is for library authors during a `pod spec lint` or `pod  trunk xx` not for consumers. By not including `use_frameworks!` in your podfile you are using libraries.

**Comment by ExoticObjects** [comment] 2016-01-23 21:12
If there is documentation for --use-libraries anywhere, I sure can't find it.
