### ISSUE TITLE
CocoaPods Dev Pods should show folder structures based on the deepest common ancestor to all source-files

### ISSUE THREAD

**Issue by olegmelnik** [CocoaPods/CocoaPods#4719] opened 2016-01-03 21:22 UTC
I created new cocoapod project by using `pod lib create`, changed folder name, edited spec file and updated example project. 

In the screenshot you can see that the extra folders have been created. What is my mistake and how to correct it? 

Thanks a lot...

![2016-01-04 0 18 02](https://cloud.githubusercontent.com/assets/7072397/12080819/b191e36c-b278-11e5-8bda-9569795d536b.png)

**Comment by orta** [comment] 2016-01-03 21:26
CocoaPods creates these folder based off the subspecs, this doesn't seem like expected behaviour though, are you using the 1.0 beta?

**Comment by olezko46** [comment] 2016-01-03 21:31
@orta No, Im using 0.39.0

**Comment by neonichu** [comment] 2016-01-04 09:24
The groups are created based on subspecs and on-disk structure, how does the on-disk structure look like for your Pod?

**Comment by olezko46** [comment] 2016-01-04 09:56
@neonichu Look...
![2016-01-04 12 56 04](https://cloud.githubusercontent.com/assets/7072397/12087245/926b7196-b2e2-11e5-9437-6a279ab3f688.png)

**Comment by neonichu** [comment] 2016-01-04 10:13
I think it works the way it's supposed to, top-level you have "IGKit" as it is the name of the pod, the next part of the path is constructed from the subspec names and finally you have another "IGKit" because that is the on-disk location of the files in question.

**Comment by orta** [comment] 2016-01-04 10:22
I think it's worth applying 2 filters in the dev pod folder structure that: 

* Removes the root folder if it happens to be the same as a Pod, 
* Matches the default for `pod lib create` = `Pod/Classes`.

**Comment by neonichu** [comment] 2016-01-04 10:28
Maybe we could drop any root path that is shared between all files instead, so we could also catch things like "Sources", "Code", etc.

**Comment by orta** [comment] 2016-01-04 10:28
That is a much better approach :+1:

**Comment by olezko46** [comment] 2016-01-04 10:33
@neonichu nice idea but how to fix my problem? :smiley:

**Comment by orta** [comment] 2016-01-04 10:34
You'd have to either move all of your files to the root folder, or implement what we're talking about above in  a PR and use that branch.

**Comment by olezko46** [comment] 2016-01-04 10:45
@orta Thanks, it works great, but I still think that to keep all the classes in the root is bad idea. Lool at [AFNetworking](https://github.com/AFNetworking/AFNetworking) for example. All classes are placed at AFNetworking folder and project tree you can see on the screenshot 

![2016-01-04 13 44 14](https://cloud.githubusercontent.com/assets/7072397/12088087/485ac0f0-b2e9-11e5-8f27-59c2a1ee3a1b.png)

**Comment by orta** [comment] 2016-01-04 10:46
You're comparing read-only pods vs development Pods. This would only affect Dev Pods. AFNetworking ( And FastEasyMapping / FBSnapshotTestCase ) and normal pods, which only create hierarchies on subspecs.

**Comment by olezko46** [comment] 2016-01-04 10:46
@orta More precisely, it is not a bad idea. Its a bad practice

**Comment by orta** [comment] 2016-01-04 10:47
> @orta More precisely, it is not a bad idea. Its a bad practice

I agree, but you asked how you could fix it now.

**Comment by olezko46** [comment] 2016-01-04 10:50
@orta And how It will look on "production"? (I'm developing private pod for my company. Just want to make it look great) :smile:

**Comment by orta** [comment] 2016-01-04 10:52
As a normal pod, all of the files are flat per spec/subspec like you see in AFNetworking.

**Comment by olezko46** [comment] 2016-01-04 10:54
@orta Like my project?
![2016-01-04 13 54 27](https://cloud.githubusercontent.com/assets/7072397/12088262/b3418e66-b2ea-11e5-9505-a88765166450.png)

**Comment by orta** [comment] 2016-01-04 11:04
@olezko46 this isn't a support forum it's our issues for bugs/feature requests and this is going off-topic now, feel free to experiment and come back if you have problems.

**Comment by olezko46** [comment] 2016-01-04 11:06
@orta ok, thanks :+1:

**Comment by orta** [comment] 2016-01-04 11:45
This should stay open, we should figure out what to do with this:

> Maybe we could drop any root path that is shared between all files instead, so we could also catch things like "Sources", "Code", etc.

**Comment by orta** [comment] 2016-04-03 20:19
I think I'm happy moving this from discussion, I don't think anyone would argue against using the common ancestor as the root folder.

**Comment by amorde** [comment] 2017-02-28 23:27
@orta Stumbled across this issue and wanted to chime in that it would be a much loved feature for the shared root path to be hidden across dev pods. 

If no one is currently working on this I could look into it, but it's been a while since I've looked at the codebase

**Comment by orta** [comment] 2017-02-28 23:28
Give it a shot 👍

**Comment by amorde** [comment] 2017-02-28 23:33
Could you point me to a relevant area of the code to give me a head start? :p

**Comment by orta** [comment] 2017-02-28 23:45
I genuinely have no idea, it would very likely be inside cocoapods/cocoapods look for target generation, then specifically start looking for an area around developer or path based pods. Not sure of the internal terminology for that feature.

**Closed** 2017-07-10 19:43 UTC
Labels: d2:moderate, s2:confirmed, t1:enhancement
