### ISSUE TITLE
Unable to install Cocoapods

### ISSUE THREAD

**Issue by AdityaGoyal1999** [CocoaPods/CocoaPods#9663] opened 2020-03-30 03:40 UTC
<b><h2> This is the error I'm getting when I'm trying to install Cocoapods.</h2></b>
Error installing cocoapods:
	ERROR: Failed to build gem native extension.

    current directory: /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2/ext/ffi_c
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/bin/ruby -r ./siteconf20200330-8267-hpu1jf.rb extconf.rb
/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/2.3.0/universal-darwin18/rbconfig.rb:215: warning: Insecure world writable dir /Library/Ruby/Gems/2.3.0 in PATH, mode 040777
mkmf.rb can't find header files for ruby at /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h

extconf failed, exit code 1

Gem files will remain installed in /Library/Ruby/Gems/2.3.0/gems/ffi-1.12.2 for inspection.
Results logged to /Library/Ruby/Gems/2.3.0/extensions/universal-darwin-18/2.3.0/ffi-1.12.2/gem_make.out

<hr>
The system wasn't able to find ruby.h file but when I digged a little deep, I found out that there is no folder like include in the location specified(/System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib/ruby/include/ruby.h). I even tried to manually add the folder but the system didn't give me permission for that even when I used sudo command.

**Comment by dnkoutso** [comment] 2020-03-30 04:18
Looks like a duplicate of https://github.com/CocoaPods/CocoaPods/issues/9641. Please use a different version of Ruby like 2.6.x.

Closing as a duplicate.

**Closed by dnkoutso** 2020-03-30 04:18 UTC

**Comment by AdityaGoyal1999** [comment] 2020-03-30 05:16
Thanks!
