### ISSUE TITLE
pod install UrbanAirship-iOS-SDK failed

### ISSUE THREAD

**Issue by TianleZhang** [CocoaPods/CocoaPods#9403] opened 2019-12-12 15:58 UTC
I can not install latest UrbanAirship-iOS-SDK 12.1.2 via cocoapods. I did a `pod try` and here is the outcome.

### Command

```
/usr/local/bin/pod try UrbanAirship-iOS-SDK
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3 (11C29)
         Git : git version 2.24.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ c7da27888b5a124c378afe17694c4ff82097bc62
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# DO NOT MODIFY -- auto-generated by Apache Cordova
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '10.0'
use_frameworks!
target 'VVNL' do
	project 'VVNL.xcodeproj'
	pod 'UrbanAirship-iOS-SDK', '~> 12.1'
        pod 'FBSDKCoreKit', '5.2.3'
	pod 'FBSDKLoginKit', '5.2.3'
	pod 'FBSDKShareKit', '5.2.3'
	pod 'TealiumIOS', '~> 5.3.2'
	pod 'TealiumIOSLifecycle', '~> 5.3.2'
end
```

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by Toppole69** [comment] 2019-12-12 20:11
****

**Comment by dnkoutso** [comment] 2019-12-12 20:17
Not sure whats happening here, I was able to successfully `pod install` the same set of pods. Can you upload a sample app with clear reproducible steps?

**Comment by dnkoutso** [comment] 2019-12-12 20:17
Oh nevermind you did a `pod try` as I see.

This is a duplicate of https://github.com/CocoaPods/cocoapods-try/issues/63 and is a known issue.

Closing as dup.

**Closed by dnkoutso** 2019-12-12 20:17 UTC

**Comment by TianleZhang** [comment] 2019-12-13 08:30
Hi I also tried pod install and I got following error
```
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "UrbanAirship-iOS-SDK":
  In Podfile:
    UrbanAirship-iOS-SDK (~> 12.1.2)

Specs satisfying the `UrbanAirship-iOS-SDK (~> 12.1.2)` dependency were found, but they required a higher minimum deployment target.
```

**Comment by TianleZhang** [comment] 2019-12-13 10:15
Never mind, I found the issue, UA stop supporting iOS 10 and we still do
