### ISSUE TITLE
CocoaPods pod install issue (Windows)

### ISSUE THREAD

**Issue by JoseLu-Dev** [CocoaPods/CocoaPods#10036] opened 2020-09-06 00:57 UTC
### Command

```
C:/Ruby26-x64/bin/pod install
```

### Report

* What did you do?

run "pod install" command

* What did you expect to happen?

install pod dependencies correctly

* What happened instead?

error could not open library 'libcurl'

### Stack

```
   CocoaPods : 1.10.0.beta.2
        Ruby : ruby 2.6.6p146 (2020-03-31 revision 67876) [x64-mingw32]
    RubyGems : 3.0.3
        Host : Unable to find an executable (No such file or directory - sw_vers)  ()
       Xcode : -version) ()
         Git : git version 2.28.0.windows.1
Ruby lib dir : C:/Ruby26-x64/lib
Repositories :
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '4.0'

target 'Runner' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Runner

end

# add the Firebase pod for Google Analytics
pod 'Firebase/Analytics'
# add pods for any other desired Firebase products
# https://firebase.google.com/docs/ios/setup#available-pods
```

### Error

```
LoadError - Could not open library 'libcurl': No se puede encontrar el módulo especificado.
.
Could not open library 'libcurl.dll': No se puede encontrar el módulo especificado.
.
Could not open library 'libcurl.so.4': No se puede encontrar el módulo especificado.
.
Could not open library 'libcurl.so.4.dll': No se puede encontrar el módulo especificado.

C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.13.1-x64-mingw32/lib/ffi/library.rb:145:in `block in ffi_lib'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.13.1-x64-mingw32/lib/ffi/library.rb:99:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ffi-1.13.1-x64-mingw32/lib/ffi/library.rb:99:in `ffi_lib'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:7:in `<module:Curl>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:2:in `<module:Ethon>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curls/settings.rb:1:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:27:in `<module:Curl>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:13:in `<module:Ethon>'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon/curl.rb:8:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:15:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:177:in `map'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:177:in `sources'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:414:in `analyze'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/installer.rb:160:in `install!'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/command/install.rb:52:in `run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/lib/cocoapods/command.rb:52:in `run'
C:/Ruby26-x64/lib/ruby/gems/2.6.0/gems/cocoapods-1.10.0.beta.2/bin/pod:55:in `<top (required)>'
C:/Ruby26-x64/bin/pod:23:in `load'
C:/Ruby26-x64/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment] 2020-09-06 01:50
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9955

**Closed by dnkoutso** 2020-09-06 01:50 UTC

**Comment by Anna-Vyde** [comment] 2021-03-22 16:35
Not sure this is actually a duplicate of #9955, I don't get the same errors in that issue but still get this one

**Comment by Kevinscki** [comment] 2025-01-08 05:38
look for a curl binary (online) enter the binary folder rename the dll (libcurl-x64.dll) to libcurl.dll
