### ISSUE TITLE
Pod spec lint fails validation with seemingly irrelevant error

### ISSUE THREAD

**Issue by crow** [CocoaPods/CocoaPods#5244] opened 2016-05-03 23:46 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran pod lib lint (passed)
Ran pod spec lint (did not pass) with error:
 -> Segment-UrbanAirship (1.0.0)
    - ERROR | [OSX] unknown: Encountered an unknown error (The platform of the target `Pods` (OS X 10.6) is not compatible with `Analytics (3.0.7)`, which does not support `osx`.) during validation.

## What did you expected to happen?

I expected pod lib lint and pod spec lint to both validate the pod with the same results. 

I expected the issue to have something to do with the listed platforms in the relevant pod's specs. None of the relevant podspecs support osx, yet the error implicates an osx compatibility issue.

## What happened instead?

pod spec lint failed with the following error:
    - ERROR | [OSX] unknown: Encountered an unknown error (The platform of the target `Pods` (OS X 10.6) is not compatible with `Analytics (3.0.7)`, which does not support `osx`.) during validation.

## Podfile

no podfile (pod spec lint)

here is the failing podspec:

```
{
  "name": "Segment-UrbanAirship",
  "documentation_url": "https://github.com/urbanairship/ios-segment-integration",
  "version": "1.0.0",
  "license": "Apache",
  "summary": "Urban Airship Integration for Segment's analytics-ios library.",
  "homepage": "https://github.com/urbanairship/ios-segment-integration",
  "authors": {
    "Urban Airship": "support@urbanairship.com"
  },
  "source": {
    "git": "https://github.com/urbanairship/ios-segment-integration.git",
    "tag": "1.0.0"
  },
  "platforms": {
    "ios": "8.0"
  },
  "requires_arc": true,
  "source_files": "Pod/Classes/**/*",
  "dependencies" : {
   "Analytics": [
      "~> 3.0.0"
    ],
    "UrbanAirship-iOS-SDK": [
      "~> 7.1.0"
    ]
  }
}
```

here is a very similar podspec that passes:

```
{
  "name": "Segment-Mixpanel",
  "version": "1.0.3",
  "summary": "Mixpanel Integration for Segment's analytics-ios library.",
  "description": "Analytics for iOS provides a single API that lets you\nintegrate with over 100s of tools.\n\nThis is the Mixpanel integration for the iOS library.",
  "homepage": "http://segment.com/",
  "license": {
    "type": "MIT"
  },
  "authors": {
    "Segment": "friends@segment.com"
  },
  "source": {
    "git": "https://github.com/segment-integrations/analytics-ios-integration-mixpanel.git",
    "tag": "1.0.3"
  },
  "social_media_url": "https://twitter.com/segment",
  "platforms": {
    "ios": "8.0"
  },
  "requires_arc": true,
  "source_files": "Pod/Classes/**/*",
  "dependencies": {
    "Analytics": [
      "~> 3.0.0"
    ],
    "Mixpanel": [
      "~> 2.9.0"
    ]
  }
}
```

Here is the podspec of the Urban Airship dependency:

```
{
  "name": "UrbanAirship-iOS-SDK",
  "documentation_url": "http://docs.urbanairship.com/reference/libraries/ios/7.1.0/",
  "version": "7.1.0",
  "license": "BSD",
   "platforms": {
    "ios": "8.0"
  },
  "summary": "A simple way to integrate Urban Airship services into your iOS applications.",
  "homepage": "https://github.com/urbanairship/ua-ios-pod",
  "authors": {
    "Urban Airship": "support@urbanairship.com"
  },
  "source": {
    "git": "https://github.com/urbanairship/ua-ios-pod.git",
    "tag": "7.1.0"
  },
  "module_name": "AirshipKit",
  "requires_arc": true,
  "source_files": [
    "Airship/AirshipLib.h",
    "Airship/{Common,External,Inbox,Push}/**/*.h",
    "UADummySource.m"
  ],
  "vendored_libraries": [
    "Airship/**.a"
  ],
  "libraries": [
    "z",
    "sqlite3"
  ],
  "resources": [
      "Airship/AirshipResources.bundle"
    ], 
  "frameworks": [
    "CFNetwork",
    "CoreGraphics",
    "Foundation",
    "MobileCoreServices",
    "Security",
    "SystemConfiguration",
    "UIKit",
    "CoreTelephony",
    "CoreLocation",
    "PassKit",
    "CoreData"
  ],
  "pod_target_xcconfig" : {
     "OTHER_LDFLAGS": "-ObjC -lz -lsqlite3"
  }
}
```

Here is the podspec of the Analytics dependency:
```
{
  "name": "Analytics",
  "version": "3.0.7",
  "summary": "The hassle-free way to add analytics to your iOS app.",
  "description": "Analytics for iOS provides a single API that lets you\nintegrate with over 100s of tools.",
  "homepage": "http://segment.com/",
  "license": {
    "type": "MIT"
  },
  "authors": {
    "Segment": "friends@segment.com"
  },
  "source": {
    "git": "https://github.com/segmentio/analytics-ios.git",
    "tag": "3.0.7"
  },
  "social_media_url": "https://twitter.com/segment",
  "platforms": {
    "ios": "8.0"
  },
  "requires_arc": true,
  "source_files": "Pod/Classes/**/*"
}
```

**Comment by segiddins** [comment] 2016-05-03 23:59
Which CocoaPods version are you using?

**Comment by segiddins** [comment] 2016-05-04 00:08
I cannot reproduce this using CocoaPods master.

**Comment by crow** [comment] 2016-05-04 17:02
cocoapods version 0.39.0

**Comment by segiddins** [comment] 2016-05-04 17:10
@crow running `pod spec lint Segment-UrbanAirship.podspec.json` passes for me, could you please write up a script we can use to reproduce the issue? Thanks!

**Comment by crow** [comment] 2016-05-04 17:12
pod spec lint fails, pod spec lint <filename> passes

**Comment by segiddins** [comment] 2016-05-04 17:16
`pod spec lint` also passes for me locally

**Comment by crow** [comment] 2016-05-04 17:16
The directory only has the one podspec present - directory can be viewed [here].(https://github.com/urbanairship/ios-segment-integration)

**Comment by crow** [comment] 2016-05-04 17:21
[Screen capture](https://drive.google.com/file/d/0B-3kQWEuRP5gOFdwbm9rMElaSUk/view?usp=sharing)

**Comment by segiddins** [comment] 2016-05-04 17:22
Confirmed -- this is happening because of the pod specs in `Example/Pods/Local Podspecs/` which is a bug.

**Comment by segiddins** [comment] 2016-05-04 19:44
Closed by https://github.com/CocoaPods/CocoaPods/commit/c3a755bf60ef57a2a4cde99f9272d18abd0b3ce0.

**Closed by segiddins** 2016-05-04 19:44 UTC
Labels: s3:detailed, t2:defect
