### ISSUE TITLE
Cocoapods website search is down

### ISSUE THREAD

**Issue by pmiotto** [CocoaPods/CocoaPods#6681] opened 2017-04-26 03:38 UTC
## What did you do?

Went to cocoapods.org and searched for any pod

## What did you expect to happen?

A list of matching pods

## What happened instead?

Nothing. no search results

**Comment by dnkoutso** [comment] 2017-04-26 17:09
The search service was down. Closing.

**Closed by dnkoutso** 2017-04-26 17:09 UTC

**Comment by 98chimp** [comment] 2017-04-29 20:36
i think this issue needs to re-opened as the issue is still persisting
i've tried both Chrome and Safari on a MBP running macOS 10.12.4 and still getting no results for any search term I type.

**Comment by ihyousafzai** [comment] 2017-05-06 19:01
Website search not working.No search results.

**Comment by ravinleague** [comment] 2017-06-15 21:36
XMLHttpRequest cannot load https://search.cocoapods.org/api/v1/pods.picky.hash.json?query=slide+show&ids=20&offset=0&sort=quality. No 'Access-Control-Allow-Origin' header is present on the requested resource. Origin 'https://cocoapods.org' is therefore not allowed access. The response had HTTP status code 503.
