### ISSUE TITLE
NO image copied using cocoa pod v1.0

### ISSUE THREAD

**Issue by kepeifeng** [CocoaPods/CocoaPods#4851] opened 2016-02-02 07:10 UTC
I am using this pod: https://github.com/chiunam/CTAssetsPickerController
I believe the config is correct. But the bundle is empty. NO file specified under resource_bundles is copied.

**Comment by orta** [comment] 2016-02-02 10:15
Can you please create a demo showing the bug?

**Comment by asharma-atx** [comment] 2016-02-04 04:12
I was experiencing a similar issue. Upgrading to 1.0.beta.3 fixed the issue for me.

**Comment by segiddins** [comment] 2016-02-04 04:35
Awesome, thanks for letting us know @asharma-atx !

**Comment by kepeifeng** [comment] 2016-02-15 02:06
Upgrading to 1.0 beta 3 fixed a little bit. but not all. In my case. the resource_bundles contains two items:

- 'CTAssetsPickerController' => ['CTAssetsPickerController/Resources/CTAssetsPicker.xcassets/\*/\*.png'
- 'CTAssetsPickerController/Resources/\*.lproj'

but only the later one is copied. @asharma-atx @segiddins 

The demo is here: https://github.com/kepeifeng/CTAssetsPickerController

**Comment by segiddins** [comment] 2016-02-15 02:44
@efirestone mind taking a look at this one?

**Comment by efirestone** [comment] 2016-02-15 03:23
Yup, happy to. Might not be until tomorrow though. Thanks for the reproducible case @asharma-atx!

**Comment by efirestone** [comment] 2016-02-15 03:45
I didn't dig too much into what was going wrong with the original version, although I have some guesses. I did look into it, and the following should give you exactly what you want:
```
  spec.resource_bundles      = { 'CTAssetsPickerController' => ['CTAssetsPickerController/Resources/**/*'] }
```

Note that this didn't work before, but does as of 1.0.0.beta.3. This also results in a better formatted Xcode project, where your xcasset catalog is fully compiled and your strings are localized, along with some other fixes which won't affect your project.

Let me know if that resolves your issue.

**Comment by kepeifeng** [comment] 2016-02-15 07:34
@efirestone thanks for your suggestion. I did get an _assets.car_ file within the bundle file now. But I still unable to load images from the that bundle. 

I found this workaround helps:

```
  spec.resource_bundles      = { 'CTAssetsPickerController' => ['CTAssetsPickerController/Resources/*.lproj'] }
  spec.resources =  'CTAssetsPickerController/Resources/CTAssetsPicker.xcassets'
```

Everything works now. However, I found something weird. There are two _assets.car_ within the framework. one under roof folder and the other under bundle folder.

![screen shot 2016-02-15 at 3 31 57 pm](https://cloud.githubusercontent.com/assets/295086/13042199/47b3f7da-d3f9-11e5-8240-fccf7703defd.png)
![screen shot 2016-02-15 at 3 31 53 pm](https://cloud.githubusercontent.com/assets/295086/13042202/4bdaec06-d3f9-11e5-92d5-ebfa694746e6.png)

**Comment by kepeifeng** [comment] 2016-02-15 10:04
UPDATE
the method I mentioned only works while using framework.
And the the method mentioned by @efirestone  will work for static library.

**Comment by efirestone** [comment] 2016-02-15 17:51
For the duplicate `Assets.car` file in the `.framework`, I didn't see that, so I suspect it's just an artifact from a previous build where you used `.resources = `. Try deleting it and see if it comes back.

It looks like the resources bundle is embedded in the framework, so you should be able to do something like:
```
        NSBundle *containingBundle = [NSBundle bundleForClass:[ClassInFramework class]];
        NSURL *bundleURL = [containingBundle URLForResource:@"CTAssetsPickerController" withExtension:@"bundle"];
        NSBundle *bundle = [NSBundle bundleWithURL:bundleURL];
```

Then you can use `bundle` to look up the images using `+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]`. This should work for both static and dynamic frameworks, as `containingBundle` will be the main bundle for static libraries, and the framework bundle for dynamic ones.

We commonly add a category like this to our frameworks:

(.h)
```
#import <Foundation/Foundation.h>


@interface NSBundle (CTAssetsPickerControllerAdditions)

+ (NSBundle *)CT_assetsPickerControllerResourcesBundle;

@end
```

(.m)
```
@interface CTAssetsPickerControllerBundleFinderClass : NSObject
@end


@implementation CTAssetsPickerControllerBundleFinderClass
@end


@implementation NSBundle (CTAssetsPickerControllerAdditions)

+ (NSBundle *)CT_assetsPickerControllerResourcesBundle;
{
    static NSBundle *bundle = nil;

    static dispatch_once_t onceToken;
    dispatch_once(&onceToken, ^{
        NSBundle *containingBundle = [NSBundle bundleForClass:[CTAssetsPickerControllerBundleFinderClass class]];
        NSURL *bundleURL = [containingBundle URLForResource:@"CTAssetsPickerController" withExtension:@"bundle"];

        NSAssert(bundleURL != nil, @"Could not find resource bundle for CTAssetsPickerController.");

        bundle = [NSBundle bundleWithURL:bundleURL];
    });

    return bundle;
}

@end
```

@segiddins - When using `resource_bundles` in dynamic frameworks, is it expected that the resources are added directly to the framework (`MyFramework.framework/MyImage.png`), or that there's a resources bundle within the framework (`MyFramework.framework/MyResources.bundle/MyImage.png`). I would suspect the latter, which means this is all work as expected.

**Comment by asharma-atx** [comment] 2016-02-15 21:02
@segiddins @efirestone - No problem, glad I could help.

@efirestone @kepeifeng - After reading through this discussion I went back and tried using my private CocoaPod in a test project with the `use_framework!` flag in the Podfile. Unfortunately, I was unable to load image assets. In the test project, if I unlock and modify the pod's NSBundle category to log out the bundle, I can see that the bundle exist:

`bundleTest[5637:1947336] Bundle: NSBundle </var/containers/Bundle/Application/20071A5C-738C-429B-81DC-6CE9B0C1B882/bundleTest.app/Frameworks/ASMessenger.framework/ASMessenger.bundle> (not yet loaded)`

Furthermore, I can see that the bundle does not contain the necessary assets by revealing the bundle in Finder and viewing the bundles contents.

@efirestone, I have my setup basically identical to what you've described in your prior comments. That said, I know that is is not very helpful info without an example app to take a look at. I've actually been planning on releasing the private CocoaPod I've been experiencing this with, so I'm going to release a pre-release version before the end of tomorrow so you can take a look if you'd like.

You also mentioned that "in dynamic frameworks, is it expected that the resources are added directly to the framework." Just to be clear, the files (or file types) inside the folder(s) pointed at in the pod spec (specs.resource_bundles) file are should be automatically copied into the bundle during the pod install, correct? Or do we need to do something to ensure that they are copied over?

Details:
- Images assets are loaded properly if they are part of a static library.
- I'm using .xcassets
- CocoaPods beta 1.0.beta.3

**Comment by segiddins** [comment] 2016-02-16 00:01
@efirestone yes, thats exactly what's expected. @asharma-atx I'm going to ask you to open up a new issue if you can reproduce this in an app you can share

**Comment by efirestone** [comment] 2016-02-16 03:54
@asharma-atx - As soon as you can open source your sample, let's open a new issue. Until then, how are you loading images from the xcassets catalog? Can you provide an example of the `UIImage` method call? Or are you doing it from a XIB/Storyboard?

**Comment by asharma-atx** [comment] 2016-02-16 05:42
@segiddins @efirestone: I've pre-released the CocoaPod [here](https://github.com/asharma-atx/ASMessenger). I've also created issue [#4897] (https://github.com/CocoaPods/CocoaPods/issues/4897), which carefully details the problem.

Thank you both for your help!

**Comment by segiddins** [comment] 2016-04-14 21:41
This ought to be fixed now in master, I think?

**Comment by neonichu** [comment] 2016-05-01 16:54
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Comment by neonichu** [comment] 2016-05-11 10:44
Looks like this is actually still an issue, see #5281

**Comment by chunpinglai** [comment] 2016-09-21 10:14
Still an issue.
After install, xcworkspace still contain CTAssetsPicker.xcassets.
![screen shot 2016-09-21 at 5 34 28 pm](https://cloud.githubusercontent.com/assets/3890368/18707033/e3712b6e-8026-11e6-96d9-372d1f13c59f.png)
But the file is in documents. 
![screen shot 2016-09-21 at 6 08 42 pm](https://cloud.githubusercontent.com/assets/3890368/18707040/e907cf2e-8026-11e6-90a9-ff8d47a537e3.png)

**Closed** 2017-07-13 10:13 UTC
Labels: s1:awaiting input
