### ISSUE TITLE
🆘 [!] CDN: trunk Repo update failed

### ISSUE THREAD

**Issue by vandadnp** [CocoaPods/CocoaPods#10528] opened 2021-03-18 06:38 UTC
Hi

I am using Cocoapods 1.10.1 and when I do the following:

```bundle exec pod install```

I get the following error:

```bundle exec pod install
Analyzing dependencies
[!] CDN: trunk Repo update failed - 2 error(s):
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/8/e/9/RxCoreData/0.3.0/RxCoreData.podspec.json Response: 429 429: Too Many Requests
CDN: trunk URL couldn't be downloaded: https://cdn.jsdelivr.net/cocoa/Specs/8/e/9/RxCoreData/1.0.0/RxCoreData.podspec.json Response: 429 429: Too Many Requests
```

I try to open the failing URL in my browser and I see this:

<img width="664" alt="image" src="https://user-images.githubusercontent.com/759524/111583402-a498a280-87bc-11eb-8321-5a17c98d4c25.png">

This issue started happening this morning, just an hour ago. I have never had this issue before

I have also tried using the following in my Podfile

```source 'https://github.com/CocoaPods/Specs.git'```

But I keep getting CDN errors

I've switched to Wifi and then back to Ethernet and nothing helps. I even tried sharing network from my phone to my computer to see if it's my network causing the problem but it isn't.

**Comment by peppesapienza** [comment] 2021-03-18 06:48
Hi guys,

I'm having the same issue locally and on Azure DevOps Pipeline

<img width="1202" alt="Screen Shot 2021-03-18 at 5 45 52 pm" src="https://user-images.githubusercontent.com/10370753/111584486-059e9580-8812-11eb-8721-a5482b32c107.png">

I also tried to add `source 'https://cdn.cocoapods.org/'` to my Podfile

Thanks

**Comment by budioktaviyan** [comment] 2021-03-18 06:54
Same here, got similar issue on serveral pods, like this one

https://cdn.jsdelivr.net/cocoa/Specs/5/b/f/ImageViewer/1.0/ImageViewer.podspec.json

**Comment by vandadnp** [comment] 2021-03-18 06:56
> Same here, got similar issue on serveral pods, like this one
> 
> https://cdn.jsdelivr.net/cocoa/Specs/5/b/f/ImageViewer/1.0/ImageViewer.podspec.json

I can open that particular URL and strange enough I can now open the original URL that I couldn't open previously

But it's failing on this one for me now

https://cdn.jsdelivr.net/cocoa/Specs/a/4/f/Giphy/1.2.5/Giphy.podspec.json

They seem to have some CDN issues

**Comment by vandadnp** [comment] 2021-03-18 07:12
Some of the CDN problems have been fixed as of the time of this writing unfortunately replaced by other problems:

```bundle exec pod update --repo-update
Update all pods
Updating local specs repositories
Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "Firebase/Crashlytics":
  In Podfile:
    Firebase/Crashlytics (= 7.8.0)

None of your spec sources contain a spec satisfying the dependency: `Firebase/Crashlytics (= 7.8.0)`.

You have either:
 * mistyped the name or version.
 * not added the source repo that hosts the Podspec to your Podfile.```

Crashlytics 7.8.0 is the latest release of Crashlytics and should exist

**Comment by sainianil** [comment] 2021-03-18 07:31
I'm also facing similar issues for the last two days. Sometime it'll work properly however sometime it won't. Today since morning it is not working. Just got 2 successful builds and the issue started re-appearing again.
<img width="1174" alt="Screenshot 2021-03-18 at 12 58 20 PM" src="https://user-images.githubusercontent.com/10446286/111588814-0cb1ad80-87ea-11eb-87ab-fc87c34f0547.png">

**Comment by awaisiosdev** [comment] 2021-03-18 07:34
We are also having a similar problem. It started happening for us in this morning. We are using cocoa pods 1.10.0 

<img width="813" alt="Screenshot 2021-03-18 at 9 34 18" src="https://user-images.githubusercontent.com/47972960/111589128-209ae680-87cd-11eb-986a-97766e0e44bb.png">

**Comment by vandadnp** [comment] 2021-03-18 07:44
<img width="1279" alt="image" src="https://user-images.githubusercontent.com/759524/111590244-25a86780-87c6-11eb-95ad-62cfbd96457e.png">

**Comment by bangfika** [comment] 2021-03-18 07:49
I faced the same issue. It was ok yesterday!

**Comment by sohail-dragon** [comment] 2021-03-18 08:03
We're facing the same issue. Any workaround? 
![image](https://user-images.githubusercontent.com/44570378/111592209-712d3680-8803-11eb-91f6-e3072d36ab04.png)

**Comment by DanielIzhevsk** [comment] 2021-03-18 08:06
Have got the same issue this morning.

![image](https://user-images.githubusercontent.com/16633950/111592527-f69bf100-87d9-11eb-8e27-00a3e04adba8.png)

**Comment by Albert221** [comment] 2021-03-18 08:33
Same error persisting on Bitrise CI/CD

**Comment by ds300** [comment] 2021-03-18 09:02
We're seeing the same issue at Artsy on CircleCI 

![image](https://user-images.githubusercontent.com/1242537/111599885-aff1cb00-87c8-11eb-9e53-cd7fdf5dbe3b.png)

**Comment by DanielIzhevsk** [comment] 2021-03-18 09:05
Temporary workaround:
1. Add this to top of your Podfile:
`source 'https://github.com/CocoaPods/Specs.git`
2. Remove `Podfile.lock` and `Pods folder`
3. Run `pod install --repo-update`

**Comment by vandadnp** [comment] 2021-03-18 09:08
> Temporary workaround:
> 
> 1. Add this to top of your Podfile:
>    `source 'https://github.com/CocoaPods/Specs.git'`
> 2. Remove `Podfile.lock` and `Pods folder`
> 3. Run `pod install --repo-update`
> 
> After that, you can push this changes to your repository.

That doesn’t work for us. The old non CDN spec repo doesn’t include the latest pod specs and fails in building for us

**Comment by StefanBouwer** [comment] 2021-03-18 09:28
> Temporary workaround:
> 
> 1. Add this to top of your Podfile:
>    `source 'https://github.com/CocoaPods/Specs.git'`
> 2. Remove `Podfile.lock` and `Pods folder`
> 3. Run `pod install --repo-update`
> 
> After that, you can push this changes to your repository.

This also did not work for us. We are experiencing the same issue with dependencies like AFNetworking, Firebase, OCMock, etc.

**Comment by gklka** [comment] 2021-03-18 09:31
> Temporary workaround:
> 
> 1. Add this to top of your Podfile:
>    `source 'https://github.com/CocoaPods/Specs.git'`
> 2. Remove `Podfile.lock` and `Pods folder`
> 3. Run `pod install --repo-update`
> 
> After that, you can push this changes to your repository.

Worked for 3 of my projects.

**Comment by slajar** [comment] 2021-03-18 09:32
I have the same issue in Azure devops. Sometimes it works sometimes it fails :/ 
I assume the CDN is way too picky regarding IP blocks and their requests, since a lot of people are using the same Build Agent with the same IP.

**Comment by sohail-dragon** [comment] 2021-03-18 09:36
Temporary work around worked for us but I understand it's not ideal. Still need to find a fix for the cdn.

**Comment by jimaek** [comment] 2021-03-18 09:47
Can you please attach the HTTP headers when getting that error?
We definitely dont rate-limit, so I am guessing that error is proxied from the origin and we simply show it.

**Comment by slajar** [comment] 2021-03-18 09:51
@jimaek how do I get those HTTP headers from cocoa pods?

**Comment by Albert221** [comment] 2021-03-18 11:18
Looks like the problem is gone. Thanks!

**Comment by vandadnp** [comment] 2021-03-18 11:21
The problem seems to have been resolved now for me too, thank you.

**Comment by budioktaviyan** [comment] 2021-03-19 06:07
Yup, the problem has been solved for me too, could you please close the issue ?

**Closed** 2021-03-19 06:33 UTC

**Comment by VanTigranyan** [comment] 2021-04-13 07:45
> Temporary workaround:
> 
> 1. Add this to top of your Podfile:
>    `source 'https://github.com/CocoaPods/Specs.git'`
> 2. Remove `Podfile.lock` and `Pods folder`
> 3. Run `pod install --repo-update`
> 
> After that, you can push this changes to your repository.

Didn't work for me too. Hangs on installation forever without any progress.

**Comment by hakota** [comment] 2021-04-13 07:55
@VanTigranyan 

Try this.

1.  Add this to top of your Podfile: 
    `source 'https://github.com/CocoaPods/Specs.git'`
2. Run `pod repo remove trunk`
3. Run `pod install`

**Comment by JonathanDSoto** [comment] 2024-05-02 04:28
https://github.com/CocoaPods/CocoaPods/issues/11939 
solution here!
