### ISSUE TITLE
Copy Pods Resources phase breaks archives in Xcode 7β6

### ISSUE THREAD

**Issue by bnickel** [CocoaPods/CocoaPods#4087] opened 2015-08-26 18:40 UTC
In Xcode 7β6 with CocoaPods 0.38.2, if an app extension uses CocoaPods, an empty /Products/{TARGET}.appex is placed in archives (both command line and in Xcode), causing Xcode and xcodebuild to treat it like a multi-bundle archive and prevent IPA export or uploading to the app store.

Commenting out the script in Copy Pods Resources fixes the issue.

I will upload an example project but here's the Podfile for now:

```ruby
platform :ios, '8.0'
use_frameworks!

target 'Extension', :exclusive => true do
    pod 'Bite'
end
```

**Comment by bnickel** [comment] 2015-08-26 18:54
Here's the example project: https://github.com/bnickel/CocoaPods-Issue4087

If you archive it, you will see that it's placed in Other Items rather than iOS Apps and that you have limited export options.  If you look inside the archive in Finder, there's a zero byte extension at `Products/Extension.appex`.  As mentioned above, commenting out Copy Pods Resources removes this folder and fixes the archive.

**Comment by segiddins** [comment] 2015-08-26 20:29
Thanks for the example project! We'll try and look into what, in particular, in the copy resources script, is causing this.

**Comment by Automatt** [comment] 2015-08-27 00:45
I'm experiencing this as well -- Could I ask where is Copy Pods Resources located to comment out in order to work around this?

**Comment by davidmcnerney** [comment] 2015-09-04 21:52
+1 seeing the same

**Comment by andrewloyola** [comment] 2015-09-08 19:29
I'm seeing the same as well. confirmed that removing Copy Pods Resources from the extension's Build Phases seems to fix the problem

**Comment by dustfire** [comment] 2015-09-09 23:54
+1

**Comment by segiddins** [comment] 2015-09-09 23:55
please don't `:+1:` -- we've acknowledged that this is a bug, and a PR to fix it would be much appreciated :)

**Comment by dustfire** [comment] 2015-09-09 23:56
:) sorry -1...

**Comment by mrezk** [comment] 2015-09-11 14:34
I guess this is the exact same issue as: https://github.com/CocoaPods/CocoaPods/issues/4021

@bnickel you can try using CocoaPods v0.39.beta.3

**Comment by daniel-hightail** [comment] 2015-09-16 00:57
Having the same issue with Xcode7 GM

**Comment by danielgalasko** [comment] 2015-09-17 13:04
@mrezk thanks, the downgrade to beta 3 solved my issue

**Comment by segiddins** [comment] 2015-10-06 00:43
This is probably caused by the same thing as https://github.com/CocoaPods/CocoaPods/issues/4178

**Comment by benghazala** [comment] 2015-10-27 11:09
+1

**Comment by danielgalasko** [comment] 2015-10-27 11:13
Please can everyone stop adding +1. This issue has been resolved. See #4119. If this is broken for you on the latest version of pods please file a new issue

@segiddins can we close this issue?

**Closed** 2015-10-27 11:14 UTC
Labels: s3:detailed, t2:defect
