### ISSUE TITLE
No such file or directory @ rb_sysopen error for one signal 

### ISSUE THREAD

**Issue by newbieflutter** [CocoaPods/CocoaPods#9393] opened 2019-12-08 05:24 UTC
Hi,
    I am running this pod install command I am getting this whole error as below. I have tried to manually put the onesignal.podspec.json into the folder but get deleted each time I run pod install command again ? What is the best solution to this?

Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/mypc/Desktop/mytest/ios/Pods/Local Podspecs/onesignal.podspec.json
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:646:in `read'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/specification.rb:646:in `checksum'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/lockfile.rb:533:in `block in generate_checksums'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/lockfile.rb:532:in `each'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/lockfile.rb:532:in `generate_checksums'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-core-1.8.4/lib/cocoapods-core/lockfile.rb:428:in `generate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:744:in `generate_lockfile'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:752:in `write_lockfiles'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:299:in `generate_pods_project'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:173:in `integrate'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer.rb:162:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

Here is my full pod file.

```
# Uncomment this line to define a global platform for your project
# platform :ios, '9.0'

# CocoaPods analytics sends network stats synchronously affecting flutter build latency.
ENV['COCOAPODS_DISABLE_STATS'] = 'true'

project 'Runner', {
  'Debug' => :debug,
  'Profile' => :release,
  'Release' => :release,
}

def parse_KV_file(file, separator='=')
  file_abs_path = File.expand_path(file)
  if !File.exists? file_abs_path
    return [];
  end
  generated_key_values = {}
  skip_line_start_symbols = ["#", "/"]
  File.foreach(file_abs_path) do |line|
    next if skip_line_start_symbols.any? { |symbol| line =~ /^\s*#{symbol}/ }
    plugin = line.split(pattern=separator)
    if plugin.length == 2
      podname = plugin[0].strip()
      path = plugin[1].strip()
      podpath = File.expand_path("#{path}", file_abs_path)
      generated_key_values[podname] = podpath
    else
      puts "Invalid plugin specification: #{line}"
    end
  end
  generated_key_values
end

target 'Runner' do
  use_frameworks!
  use_modular_headers!
  
  # Flutter Pod

  copied_flutter_dir = File.join(__dir__, 'Flutter')
  copied_framework_path = File.join(copied_flutter_dir, 'Flutter.framework')
  copied_podspec_path = File.join(copied_flutter_dir, 'Flutter.podspec')
  unless File.exist?(copied_framework_path) && File.exist?(copied_podspec_path)
    # Copy Flutter.framework and Flutter.podspec to Flutter/ to have something to link against if the xcode backend script has not run yet.
    # That script will copy the correct debug/profile/release version of the framework based on the currently selected Xcode configuration.
    # CocoaPods will not embed the framework on pod install (before any build phases can generate) if the dylib does not exist.

    generated_xcode_build_settings_path = File.join(copied_flutter_dir, 'Generated.xcconfig')
    unless File.exist?(generated_xcode_build_settings_path)
      raise "Generated.xcconfig must exist. If you're running pod install manually, make sure flutter pub get is executed first"
    end
    generated_xcode_build_settings = parse_KV_file(generated_xcode_build_settings_path)
    cached_framework_dir = generated_xcode_build_settings['FLUTTER_FRAMEWORK_DIR'];

    unless File.exist?(copied_framework_path)
      FileUtils.cp_r(File.join(cached_framework_dir, 'Flutter.framework'), copied_flutter_dir)
    end
    unless File.exist?(copied_podspec_path)
      FileUtils.cp(File.join(cached_framework_dir, 'Flutter.podspec'), copied_flutter_dir)
    end
  end

  # Keep pod path relative so it can be checked into Podfile.lock.
  pod 'Flutter', :path => 'Flutter'

  # Plugin Pods

  # Prepare symlinks folder. We use symlinks to avoid having Podfile.lock
  # referring to absolute paths on developers' machines.
  system('rm -rf .symlinks')
  system('mkdir -p .symlinks/plugins')
  plugin_pods = parse_KV_file('../.flutter-plugins')
  plugin_pods.each do |name, path|
    symlink = File.join('.symlinks', 'plugins', name)
    File.symlink(path, symlink)
    pod name, :path => File.join(symlink, 'ios')
  end
end

# Prevent CocoaPods from embedding a second Flutter framework and causing an error with the new Xcode build system.
install! 'cocoapods', :disable_input_output_paths => true

target 'OneSignalNotificationServiceExtension' do
  use_frameworks!
  pod 'OneSignal', '>= 2.9.3', '< 3.0'
end


post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end


```

**Comment by iamacup** [comment] 2019-12-09 11:28
I wonder if its related to https://github.com/CocoaPods/CocoaPods/issues/9214

**Comment by newbieflutter** [comment] 2019-12-09 17:34
Hi IAmcup,
                   I am not too sure that issue is related to react native not flutter and also my issue is with one signal though ?

**Comment by dnkoutso** [comment] 2019-12-09 17:40
We need _clear_ reproducible steps on this issue with a project _without_ Flutter or ReactNative in order for us to narrow down the issue in CocoaPods and prove that it is indeed an issue with CocoaPods.

**Comment by newbieflutter** [comment] 2019-12-09 17:44
Hi dnkoutso,
                     So please let me know how to product a project without flutter cause I am trying my best to debug it too. How to differentiate it with just CocoaPods? I suspect it cause of the upgrade of cocoapods too like the other thread. Actually how will the upgrade impact.

**Comment by dnkoutso** [comment] 2019-12-09 18:37
Just use CocoaPods without flutter I am not sure of what you are asking. Create an iOS project integrate it with CocoaPods and try to reproduce the issue here.

**Comment by newbieflutter** [comment] 2019-12-10 05:55
Hi ,
      Ok I created a blank ios app and followed this link https://documentation.onesignal.com/docs/ios-sdk-setup. One thing missing is this 1.6 Open NotificationService.m or NotificationService.swift and replace the whole file contents with the below code. I could not find this. But there after I went into the folder did pod init and put in this pod 'OneSignal', '>= 2.11.2', '< 3.0' and lastly I ran pod install. Seems to be running with no issue.So I guess the issue is with flutter is it? What could be the issue is it the flutter or one signal not working with flutter on this new cocoapod version? Infact I have downgrade my cocoapod to 1.8.3 but still same issue

**Comment by dnkoutso** [comment] 2019-12-10 07:36
This seems like an issue caused by Flutter.

**Comment by newbieflutter** [comment] 2019-12-10 14:33
@dnkoutso so where should I take this issue to next ? Where do you suggest?

**Comment by dnkoutso** [comment] 2019-12-10 16:15
File an issue with Flutter? Dig in manually and see where the error is?

**Comment by newbieflutter** [comment] 2019-12-11 04:19
Hi @dnkoutso ,
                           Yes I have dig manually what I found is that this file is missing onesignal.podspec.json. So even I put in manually there but when I ran pod install its deleted again why ya ? Actually could it be issue with one signal itself? Maybe they never updated the cocoapods for onesignal for flutter?

**Comment by dnkoutso** [comment] 2019-12-11 04:21
the pod probably has no issue. Are you still invoking a Flutter command or `pod install` directly? 

still need a sample app here to be able to diagnose.

**Comment by newbieflutter** [comment] 2019-12-11 04:27
I ran the pod install directly from terminal. How to send you the sample app cause you said run a pure ios app and that works.

**Comment by dnkoutso** [comment] 2019-12-11 04:27
I do not know and I cannot reproduce here so this might be a Flutter issue. I am inclined to close this for now.

**Comment by newbieflutter** [comment] 2019-12-11 04:28
ok I will open first with open with one signal.

**Comment by dnkoutso** [comment] 2019-12-11 04:29
Thanks! let me know how it goes and if we show its a CocoaPods issues I'd be happy to investigate/fix.

**Comment by newbieflutter** [comment] 2019-12-11 04:29
Cause I am also not sure about cocoapod. Actually what is the main function of the cocoapods?

**Closed by dnkoutso** 2019-12-11 04:29 UTC
Labels: s6:need sample

**Comment by dnkoutso** [comment] 2019-12-11 04:30
its a dependency manager for iOS.

**Comment by newbieflutter** [comment] 2019-12-11 04:32
So it pulls the dependency for ios. I guess in that case maybe 1.8.4 cocoapods is not compatible with open signal?
