### ISSUE TITLE
Updating Homebrew... Error: libffi not installed

### ISSUE THREAD

**Issue by kangpeter5** [CocoaPods/CocoaPods#10469] opened 2021-02-26 22:53 UTC
I tried running `brew upgrade libffi` and `arch -x86_64 brew upgrade libffi`(I'm using M1) and got `Updating Homebrew...
Error: libffi not installed`.

Trying `export LDFLAGS="-L/usr/local/opt/libffi/lib"` & `export PKG_CONFIG_PATH="/usr/local/opt/libffi/lib/pkgconfig"` Did not help.

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.10.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin20]
    RubyGems : 3.0.3
        Host : macOS 11.2.1 (20D74)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'


platform :ios, '10.0'


abstract_target 'KSxNYU' do
  
  # React Native Maps dependencies
  rn_maps_path = '../node_modules/react-native-maps'
  pod 'react-native-google-maps', :path => rn_maps_path
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  
  config = use_native_modules!
  use_react_native!(:path => config["reactNativePath"])
  
  # Enables Flipper.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work and
  # you should disable these next few lines.
  use_flipper!
  pod 'RNPermissions', :path => '../node_modules/react-native-permissions'

  pod 'react-native-in-app-review', :path => '../node_modules/react-native-in-app-review'

  post_install do |installer|
    flipper_post_install(installer)
  end
  
  permissions_path = '../node_modules/react-native-permissions/ios'
  pod 'Permission-Camera', :path => "#{permissions_path}/Camera.podspec"
  pod 'Permission-LocationWhenInUse', :path => "#{permissions_path}/LocationWhenInUse.podspec"
  pod 'Permission-Notifications', :path => "#{permissions_path}/Notifications.podspec"
  
  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
  
  
  target 'KSxNYU-Production' do
  end

  target 'KSxNYU-Staging' do
  end

end


#post_install do |installer|
#    installer.pods_project.targets.each do |target|
#        if target.name == 'RNInputMask'
#            target.build_configurations.each do |config|
#                config.build_settings['SWIFT_VERSION'] = '4.2.1'
#            end
#        end
#    end
#end



## Pods for Kettle
#  pod 'React', :path => '../node_modules/react-native/'
#  pod 'React-Core', :path => '../node_modules/react-native/React'
#  pod 'React-DevSupport', :path => '../node_modules/react-native/React'
#  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
#  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
#  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
#  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
#  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
#  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
#  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
#  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
#  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
#  pod 'React-RCTWebSocket', :path => '../node_modules/react-native/Libraries/WebSocket'
#
#  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
#  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
#  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
#  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
#  pod 'yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
#
#  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
#  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
#  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
#
#  use_native_modules!
#  pod 'RNReanimated', :path => '../node_modules/react-native-reanimated'
#  pod 'RNGestureHandler', :path => '../node_modules/react-native-gesture-handler'
#  pod 'RNScreens', :path => '../node_modules/react-native-screens'
#  pod 'react-native-splash-screen', :path => '../node_modules/react-native-splash-screen'
#  pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'
#  pod 'react-native-mapbox-gl', :path => '../node_modules/@mapbox/react-native-mapbox-gl'
#
#  pod 'react-native-geolocation', :path => '../node_modules/@react-native-community/geolocation'
#
#  pod 'RNInputMask', :path => '../node_modules/react-native-text-input-mask/ios/InputMask'
#
#  pod '@mauron85_react-native-background-geolocation', :path => '../node_modules/@mauron85/react-native-background-geolocation'
  
#  pod 'Firebase/Core', '~> 6.3.0'
#  pod 'Fabric', '~> 1.10.2'
#  pod 'Crashlytics', '~> 3.13.2'
```

### Error

```
LoadError - dlsym(0x7f855d5c07a0, Init_ffi_c): symbol not found - /Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi_c.bundle
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:6:in `rescue in <top (required)>'
/Library/Ruby/Gems/2.6.0/gems/ffi-1.14.2/lib/ffi.rb:3:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib/ruby/2.6.0/rubygems/core_ext/kernel_require.rb:54:in `require'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:74:in `cdn_url?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:36:in `create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/sources_manager.rb:21:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:178:in `block in sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `map'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:177:in `sources'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1073:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by oleg-moseyko** [comment] 2021-03-15 17:31
$ yarn add react-native-fast-image
yarn add v1.22.5
warning package-lock.json found. Your project contains lock files generated by tools other than Yarn. It is advised not to mix package managers in order to avoid resolution inconsistencies caused by unsynchronized lock files. To clear this warning, remove package-lock.json.
[1/4] 🔍 Resolving packages...
[2/4] 🚚 Fetching packages...
[3/4] 🔗 Linking dependencies...
warning " > @react-native-community/cameraroll@4.0.2" has incorrect peer dependency "react-native@>=0.60 <=0.62".
[4/4] 🔨 Building fresh packages...
success Saved lockfile.
success Saved 3 new dependencies.
info Direct dependencies
├─ @react-native-community/cameraroll@4.0.2
├─ react-native-fast-image@8.3.4
└─ react-native-image-pan-zoom@2.1.12
info All dependencies
├─ @react-native-community/cameraroll@4.0.2
├─ react-native-fast-image@8.3.4
└─ react-native-image-pan-zoom@2.1.12
✨ Done in 20.58s.

$ npx pod-install
npx: installed 1 in 1.458s
Scanning for pods...
1.10.1

pod install
Installing unimodules:
expo-application@2.4.1 from ../node_modules/expo-application/ios
expo-constants@9.3.5 from ../node_modules/expo-constants/ios
expo-error-recovery@1.4.0 from ../node_modules/expo-error-recovery/ios
expo-file-system@9.3.0 from ../node_modules/expo-file-system/ios
expo-font@8.4.0 from ../node_modules/expo-font/ios
expo-image-loader@1.3.0 from ../node_modules/expo-image-loader/ios
expo-keep-awake@8.4.0 from ../node_modules/expo-keep-awake/ios
expo-linear-gradient@8.4.0 from ../node_modules/expo-linear-gradient/ios
expo-location@10.0.0 from ../node_modules/expo-location/ios
expo-permissions@10.0.0 from ../node_modules/expo-permissions/ios
expo-secure-store@9.3.0 from ../node_modules/expo-secure-store/ios
expo-splash-screen@0.8.1 from ../node_modules/expo-splash-screen/ios
expo-sqlite@8.5.0 from ../node_modules/expo-sqlite/ios
expo-updates@0.4.2 from ../node_modules/expo-updates/ios
unimodules-app-loader@1.4.0 from ../node_modules/unimodules-app-loader/ios
unimodules-barcode-scanner-interface@5.4.0 from ../node_modules/unimodules-barcode-scanner-interface/ios
unimodules-camera-interface@5.4.0 from ../node_modules/unimodules-camera-interface/ios
unimodules-constants-interface@5.4.0 from ../node_modules/unimodules-constants-interface/ios
unimodules-core@6.0.0 from ../node_modules/@unimodules/core/ios
unimodules-face-detector-interface@5.4.0 from ../node_modules/unimodules-face-detector-interface/ios
unimodules-file-system-interface@5.4.0 from ../node_modules/unimodules-file-system-interface/ios
unimodules-font-interface@5.4.0 from ../node_modules/unimodules-font-interface/ios
unimodules-image-loader-interface@5.4.0 from ../node_modules/unimodules-image-loader-interface/ios
unimodules-permissions-interface@5.4.0 from ../node_modules/unimodules-permissions-interface/ios
unimodules-react-native-adapter@5.7.0 from ../node_modules/@unimodules/react-native-adapter/ios
unimodules-sensors-interface@5.4.0 from ../node_modules/unimodules-sensors-interface/ios
unimodules-task-manager-interface@5.4.0 from ../node_modules/unimodules-task-manager-interface/ios

Auto-linking React Native modules for target fast: RNFastImage, RNGestureHandler, RNReanimated, RNScreens, and react-native-cameraroll
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

Command
/Applications/MAMP/Library/bin/pod install
Report
What did you do?

What did you expect to happen?

What happened instead?

Stack
   CocoaPods : 1.10.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [x86_64-darwin14]
    RubyGems : 2.5.2.3
        Host : macOS 11.0.1 (20B50)
       Xcode : 12.3 (12C33)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Applications/MAMP/Library/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
Plugins
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
Podfile
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/react-native-unimodules/cocoapods.rb'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, '11.0'

target 'fast' do
  use_unimodules!
  config = use_native_modules!

  use_react_native!(:path => config["reactNativePath"])

  # Uncomment the code below to enable Flipper.
  #
  # You should not install Flipper in CI environments when creating release
  # builds, this will lead to significantly slower build times.
  #
  # Note that if you have use_frameworks! enabled, Flipper will not work.
  #
  #  use_flipper!
  #  post_install do |installer|
  #    flipper_post_install(installer)
  #  end
  pod 'react-native-cameraroll', :path => '../node_modules/@react-native-community/cameraroll'

end
Error
LoadError - dlopen(/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.15.0/lib/ffi_c.bundle, 9): no suitable image found.  Did find:
        /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.15.0/lib/ffi_c.bundle: code signature in (/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.15.0/lib/ffi_c.bundle) not valid for use in process using Library Validation: mapped file has no cdhash, completely unsigned? Code has to be at least ad-hoc signed. - /Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.15.0/lib/ffi_c.bundle
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.15.0/lib/ffi.rb:6:in `rescue in <top (required)>'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ffi-1.15.0/lib/ffi.rb:3:in `<top (required)>'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:120:in `require'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/ethon-0.12.0/lib/ethon.rb:2:in `<top (required)>'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/typhoeus-1.4.0/lib/typhoeus.rb:2:in `<top (required)>'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Applications/MAMP/Library/lib/ruby/2.3.0/rubygems/core_ext/kernel_require.rb:68:in `require'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:440:in `download_typhoeus_impl_async'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:372:in `download_and_save_with_retries_async'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:365:in `download_file_async'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:131:in `block (2 levels) in versions'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:124:in `map'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:124:in `block in versions'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:479:in `concurrent_requests_catching_errors'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:121:in `versions'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:99:in `block in versions_by_source'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:98:in `each'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:98:in `each_with_object'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:98:in `versions_by_source'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-core-1.10.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `each'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:754:in `push_state_for_requirements'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:746:in `require_nested_dependencies_for'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:729:in `activate_new_spec'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:686:in `attempt_to_activate'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:254:in `process_topmost_state'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:182:in `resolve'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1074:in `block in resolve_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:1072:in `resolve_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:414:in `analyze'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:239:in `block in resolve_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/user_interface.rb:64:in `section'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:238:in `resolve_dependencies'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/installer.rb:160:in `install!'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/command/install.rb:52:in `run'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/lib/cocoapods/command.rb:52:in `run'
/Applications/MAMP/Library/lib/ruby/gems/2.3.0/gems/cocoapods-1.10.1/bin/pod:55:in `<top (required)>'
/Applications/MAMP/Library/bin/pod:22:in `load'
/Applications/MAMP/Library/bin/pod:22:in `<main>'
――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=dlopen%28%2FApplications%2FMAMP%2FLibrary%2Flib%2Fruby%2Fgems%2F2.3.0%2Fgems%2Fffi-1.15.0%2Flib%2Fffi_c.bundle%2C+9%29%3A+no+suitable+image+found.++Did+find%3A%0A%09%2FApplications%2FMAMP%2FLibrary%2Flib%2Fruby%2Fgems%2F2.3.0%2Fgems%2Fffi-1.15.0%2Flib%2Fffi_c.bundle%3A+code+signature+in+%28%2FApplications%2FMAMP%2FLibrary%2Flib%2Fruby%2Fgems%2F2.3.0%2Fgems%2Fffi-1.15.0%2Flib%2Fffi_c.bundle%29+not+valid+for+use+in+process+using+Library+Validation%3A+mapped+file+has+no+cdhash%2C+completely+unsigned%3F+Code+has+to+be+at+least+ad-hoc+signed.+-+%2FApplications%2FMAMP%2FLibrary%2Flib%2Fruby%2Fgems%2F2.3.0%2Fgems%2Fffi-1.15.0%2Flib%2Fffi_c.bundle&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...

Aborting run
An unexpected error was encountered. Please report it as a bug:
CocoaPodsError: The command pod install failed
└─ Cause: Error: pod exited with non-zero code: 1
at CocoaPodsPackageManager._installAsync (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:85286)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async CocoaPodsPackageManager.installAsync (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:84649)
at async runAsync (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:109680)
at async /Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:109766 {
code: 'COMMAND_FAILED',
cause: Error: pod exited with non-zero code: 1
at ChildProcess.h (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:1073)
at Object.onceWrapper (events.js:421:26)
at ChildProcess.emit (events.js:314:20)
at maybeClose (internal/child_process.js:1047:16)
at Process.ChildProcess._handle.onexit (internal/child_process.js:287:5)
...
at Object.spawnAsync [as default] (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:558)
at CocoaPodsPackageManager._runAsync (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:86068)
at CocoaPodsPackageManager._installAsync (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:84933)
at CocoaPodsPackageManager.installAsync (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:84660)
at runAsync (/Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:109688)
at processTicksAndRejections (internal/process/task_queues.js:93:5)
at async /Users/olegmoseyko/.npm/_npx/54993/lib/node_modules/pod-install/build/index.js:2:109766 {
pid: 55020,
output: [
'',
"Searching for inspections failed: undefined method map' for nil:NilClass\n" + 'Did you mean? tap\n' ], stdout: '', stderr: "Searching for inspections failed: undefined method map' for nil:NilClass\n" +
'Did you mean? tap\n',
status: 1,
signal: null
},
isPackageManagerError: true
}

**Comment by dnkoutso** [comment] 2021-08-05 07:12
closing `ffi` related issues.

Please `gem update ffi` and `gem update ethon` which I Heard may have fixed some of these issues.

**Closed by dnkoutso** 2021-08-05 07:12 UTC
