### ISSUE TITLE
faild to pod repo push 

### ISSUE THREAD

**Issue by mrkizy** [CocoaPods/CocoaPods#11923] opened 2023-05-29 09:13 UTC
after updating  xcode to 14.3 version , I tried to  publish a  lib to the private cocoapods repo, the terminal showed it failed , beacuse of the follow errors:
<img width="1065" alt="image" src="https://github.com/CocoaPods/CocoaPods/assets/7277246/ac973186-d099-4b5c-8ca9-7459e0b1e58e">

i know how to fix it if building a program in xcode, but i have no idea to fix it when publishing a lib with the `pod repo push` command

**Comment by paulb777** [comment] 2023-05-29 13:27
This is a duplicate of #11839.

Workaround is to update the minimum platform versions in the podspec (and dependencies) or continue to use Xcode 14.2

**Closed by paulb777** 2023-05-29 13:27 UTC
