### ISSUE TITLE
`Target 'XXX' has frameworks with conflicting names` using 1.1.0.beta.1

### ISSUE THREAD

**Issue by jrmiddle** [CocoaPods/CocoaPods#5643] opened 2016-07-19 17:21 UTC
- [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

Run `pod install` with the `podfile` copied below.
## What did you expect to happen?

Pods install without issue
## What happened instead?

Pods failed to install, with error `[!] The XXXX target has frameworks with conflicting names: alamofireoauth2.`
## CocoaPods Environment

cocoapods 1.1.0.beta.1
## Project that demonstrates the issue

Problem occurs when attempting to install an AlamoFireOauth2 fork at https://github.com/jrmiddle/AlamofireOauth2/tree/extension-support.  The revised podspec contains two subspecs, `AlamofireOauth2/Core` and `AlamofireOauth2/ApplicationSupport`.
## Example Podfile

``` ruby
use_frameworks!

def base_pods
    pod "Alamofire", "3.4.1"
    pod "AlamofireObjectMapper", "3.0.0"
    pod "PromiseKit", "3.2.0"
    pod "PySwiftyRegex", "0.2.2"
end

def app_pods
    base_pods
    pod "SDWebImage", "3.8.1"
    pod "UIActivityIndicator-for-SDWebImage", "1.2"
    pod "UIActivityIndicator-for-SDWebImage+UIButton", "1.2"
    pod "AlamofireOauth2/ApplicationSupport", :git => 'https://github.com/jrmiddle/AlamofireOauth2.git', :branch     => 'extension-support', :commit => '949d35b5f92af59c56a5b591ea8c3dbccd3da0e0'
    pod "AutolayoutSupport", "0.1.5"
end

def share_extension_pods
    pod "AlamofireOauth2/Core", :git => 'https://github.com/jrmiddle/AlamofireOauth2.git', :branch => 'extension-support', :commit => '949d35b5f92af59c56a5b591ea8c3dbccd3da0e0'
    base_pods
end

target 'App' do
    platform :ios, '9.3'
    app_pods
end

target 'ShareExtension' do
    platform :ios, '9.3'
    share_extension_pods
end
```
## Other Notes
- When I used this podspec and podfile using 1.0.0.beta.3 (yeah, I was behind), the Pods-\* frameworks for those subspecs did not link against `KeychainAccess` (at least), so builds failed.
- When I updated to 1.1.0.beta.1, pod install failed with the message reported above.
- Cocoapods `1.0.1` successfully installs the subspecs, and I'm able to build.

**Comment by neonichu** [comment] 2016-07-19 18:44
In 1.0.1, pods declared for app extensions were never embedded in the host app, so essentially the pods you declared for the "ShareExtension" target didn't really matter.

I think it makes sense that this Podfile can't be integrated as there is no way for the two different configurations of "AlamofireOauth2" to exist in the same host app. However, the error message should probably reflect that this is a matter of selecting conflicting sets of subspecs.

**Comment by jrmiddle** [comment] 2016-07-19 21:18
Ah, that makes sense, thanks. That's what happens when one's mental model is wrong. Alternative, non-subspec approach taken and effective.

Yes, the conflicting subspec message would have been really helpful, but I understand what's going on now. Thanks again!

**Comment by dfed** [comment] 2016-07-27 23:59
Shout out to @jrmiddle for posting this. Just saved me a boatload of time.

**Comment by jonasman** [comment] 2016-09-06 17:13
I have this problem but only when using subspecs

Example:

````ruby
target 'Portfolio' do
	use_frameworks!
	
	pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0', submodules: true
	pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-3'
	pod 'SwiftyStoreKit', :git => 'https://github.com/neoplastic/SwiftyStoreKit.git', :branch => 'swift-3.0'
	pod 'Google/Analytics'

end

target 'StocksKit' do
	use_frameworks!
	
	pod 'ObjectMapper', :git => 'https://github.com/Hearst-DD/ObjectMapper.git', :branch => 'swift-3'
	pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0', submodules: true
	pod 'PromiseKit/OMGHTTPURLRQ', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0', submodules: true  --> Commenting this line works, but ofc the project doesn't compile
	
end

target 'PortfolioWidget' do
	use_frameworks!
	
	pod 'PromiseKit', :git => 'https://github.com/mxcl/PromiseKit.git', :branch => 'swift-3.0', submodules: true
	
end
````

**Comment by mseijas** [comment] 2016-09-15 01:34
Same problem here as @jonasman - referenced in https://github.com/mixpanel/mixpanel-iphone/issues/572

This is my podfile:
```
platform :ios, :deployment_target => '9.0'
use_frameworks!

def shared_pods
    pod 'SnapKit'
    pod 'Alamofire'
    pod 'ObjectMapper', '~> 1.3'
    pod 'AlamofireObjectMapper', '~> 3.0'
    
    pod 'Realm', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', submodules: true
    pod 'RealmSwift', :git => 'https://github.com/realm/realm-cocoa.git', :branch => 'master', submodules: true

    pod 'Firebase'
    pod 'Firebase/Core'
end

target 'Main' do
    shared_pods
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'Mixpanel'
    pod 'SDWebImage', '~>3.8'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'TwitterKit'
 end

target 'keyboard' do
    shared_pods
    pod 'Mixpanel/AppExtension'
end
```

**Comment by mltk96** [comment] 2016-09-16 20:58
any updates?

**Comment by yarneo** [comment] 2016-09-20 21:33
+1

**Comment by yarneo** [comment] 2016-09-22 00:10
This issue seems to have been introduced in the 1.1.0 beta versions, and does not exist in version 1.0.1. Unfortunately, in 1.0.1 there is the other issue where the run script for embedding the pods isn't added. Therefore the current workaround is to install using 1.0.1 and then adding the run script manually.

That workaround however will only work if the pods in your podfile work well with v1.0.1, and as it seems, Alamofire requires a pod version of at least 1.1.0. I'm really hoping this issue will be resolved soon, as it is stopping people from having the same library in both their extension and their app.

**Comment by neonichu** [comment] 2016-09-23 12:09
Please give some attention to [this comment](https://github.com/CocoaPods/CocoaPods/issues/5643#issuecomment-233727907).

It is and has been for a long time impossible to have two different variants of the same framework for your app and your extension, because embedding frameworks into an extension will be rejected by iTunes Connect. The issue is solely about the error message, not about the error itself. If your goal is to have two different copies of the same framework, please file radars.

**Comment by orta** [comment] 2016-11-17 10:08
Closing as radars are the only way to fix this

**Closed** 2016-11-17 10:08 UTC
Labels: t2:defect
