### ISSUE TITLE
Adding -ObjC to the linker flags for all vendored_frameworks makes dead code stripping very difficult

### ISSUE THREAD

**Issue by perotinus** [CocoaPods/CocoaPods#4101] opened 2015-08-28 18:48 UTC
The team that builds the GoogleMobileAds pod is trying to reduce their binary size by taking advantage of dead code stripping. The latest beta version of Cocoapods adds ```-ObjC``` to the linker flags if there is a vendored framework, which stands to significantly hinder these efforts.

What can we do about this? Is there a way we can work around this, so that ```vendored_frameworks``` that want dead code stripping can allow it?

**Comment by samdmarshall** [comment] 2015-08-29 00:20
Due to the dynamic nature of ObjC, there really isn't a way to work around this other than move non-ObjC code into non-ObjC files. -ObjC will forcefully load any and all code that exists in Objective-C objects into the final binary. If you want to strip dead code then this should be done via writing C or C++ code in separate files. Otherwise there is no way around this short of breaking all the code in this pod in question into separate smaller modules. Sorry there aren't better options for this.

**Comment by neonichu** [comment] 2015-08-29 15:09
Considering that vendored frameworks should be moving to be dynamic, I'd be reluctant for us to add additional functionality for static ones. Especially considering `-ObjC` used to be there unconditionally until 0.38 anyways (see #3537), but not having it there for vendored frameworks caused a bunch of problems with many of them, because of the reasons @samdmarshall mentioned.

**Comment by perotinus** [comment] 2015-09-01 17:09
That makes sense. However, we're working internally to reduce the size of our libraries by making sure that our code works in the absence of ```-ObjC```. It's more complicated to make this work, but it's possible to make an Objective C library that does not require ```-ObjC```. The developer that is working on this had suggested using ```-force_load``` for libraries that need it instead of ```-ObjC```, which affects all libraries. If we put together a PR, would that be a possible way forward?

As an alternative, could we add a way for static vendored pods to specify that they don't require ```-ObjC```. If all the pods have this 'I don't need ```-ObjC``` flag, then CocoaPods could leave it out. Though, I'm not sure this would help in practice, because one vendored pod that doesn't set this flag would affect everyone else's build.

As much as I'd love to move to dynamic bitcode frameworks, we can't do that until our users have moved away from supporting iOS 7, which I don't think will happen for a while.

**Comment by segiddins** [comment] 2015-09-01 17:19
I'm not sure that this _really_ requires us to do anything -- there are tradeoffs between using static and dynamic libraries, and this is just one of them.

**Comment by samdmarshall** [comment] 2015-09-01 17:27
The issue that will arise is that `-force_load` and `-ObjC` are not the same functionality and make assumptions of the target library in question. The behavior of `-force_load` will load *all* members of a static library, whereas `-ObjC` only loads members that contain Objective-C code. This distinction is extremely important to make considering excess code that gets shipped in many pre-built libraries. While it may seems suitable here, changing the default expectation may cause conflicts elsewhere as a result of including duplicate symbols due to this behavior change.

**Comment by perotinus** [comment] 2015-09-01 22:10
I thought that the behavior of -ObjC was to load all members of static libraries that contain Objective C code. That's what ```ld```'s documentation says:

    $ man ld
    ...
    -ObjC       Loads all members of static archive libraries that implement an Objective-C class or category.
    ...

So, say you have three libraries:

- ```libCPPOnly.a```
- ```libObjCWithCPP.a```
- ```libObjCOnly.a```

If you use ```ld -ObjC -lCPPOnly -lObjCWithCPP -lObjCOnly```, that will fully load ```libObjCWithCPP.a``` and ```libObjCOnly.a```, but let the linker determine what from ```libCPPOnly.a``` is necessary. This is the same as ```ld -lCPPOnly -force_load /path/to/libObjCWithCPP.a -force_load /path/to/libObcCOnly.a```

I think that replacing ```-ObjC``` with ```-force_load``` doesn't change how the linker behaves.

This certainly isn't necessary, but it also makes apps larger than necessary, which is not ideal for app developers who have to stay under a certain size limit but still need to support older versions of iOS. If CocoaPods can support this, it would be a boon for developers who can take advantage of it.

**Comment by segiddins** [comment] 2015-09-01 22:24
I believe @samdmarshall is correct here in stating that `-ObjC` and `-force_load` behave differently, as `-ObjC` only loads the particular _object_ files that have ObjC code in them, not the entire archive.

**Comment by perotinus** [comment] 2015-09-01 23:44
Interesting. I guess the "that" clause in the linker documentation can be read in two ways: it either refers back to the "members" or "archives". I read it the latter way, but it looks like the former way is correct, based on my tests in https://github.com/perotinus/ObjCForceLoadTest .

Sorry for the confusion!

**Closed** 2015-09-01 23:44 UTC
Labels: t3:discussion

**Comment by s-atif-jamil** [comment] 2019-09-15 18:27
Hi, I have same problem I have .a library in my custom pod which required -ObjC flag. That static library has some objective c and c++ code.  

If I directly add that library with project and put -ObjC flag on Other Linker flags. It working fine.

But if I put in my custom Pod its failed on runtime with this error
2019-09-15 14:26:30.371962-0400 -[NSConcreteData gzippedData]: unrecognized selector sent to instance 0x282dfed00
2019-09-15 14:26:30.750582-0400 *** Terminating app due to uncaught exception 'NSInvalidArgumentException', reason: '-[NSConcreteData gzippedData]: unrecognized selector sent to instance 0x282dfed00'

**Comment by paulb777** [comment] 2019-09-15 18:58
@s-atif-jamil Without `-ObjC` category implementations get stripped and that is likely the cause of the `unrecognized selector`.

**Comment by s-atif-jamil** [comment] 2019-09-16 02:21
Hi Paul,

Thanks for your response. Yes I knew that `-ObjC` flag is the problem but I was not able to set properly. Because that library is in subspec of my custom pods. My main custom pods is written Swift but I have multiple subspecs 3rd party libraries. Some are in ObjectiveC and some are in swift.  After some trial and error I was able to find that if I put `-ObjC` in target setting of my custom Pod then it will worked fine not in Pods-xxxx Target.

After that I follow that doc  https://guides.cocoapods.org/syntax/podspec.html#pod_target_xcconfig

> s.subspec 'SomeCPPLibrary' do |my_sub_library|
> ...
> my_sub_library.pod_target_xcconfig = { 'OTHER_LDFLAGS' => '-ObjC' }
> end

But then I am getting different errors like   
> "_OBJC_CLASS_$_AVMetadataMachineReadableCodeObject", referenced from:

and to solve that I need to add on my main specs
> s.frameworks = 'AVFoundation', 'CoreLocation'

Anyway it's working now. Really appreciate for your feedback
