### ISSUE TITLE
Cocoapods not adding the "Check Pods Manifext.lock" and "Copy Pods Resources" build phases to my static lib

### ISSUE THREAD

**Issue by khanmdv** [CocoaPods/CocoaPods#3336] opened 2015-03-31 01:02 UTC
Hi,

I am using Cocoapods version 0.35. I am trying to build a static library. My podspec mentions few dependencies and I have a demo app which links against the static library. When I do a pod install cocoapods fetches the dependent libraries but it does not set the PODS_ROOT. It also does not also add  "Check Pods Manifext.lock" and "Copy Pods Resources" build phases to my static lib target. 

Now my static lib is unable to refer to any external depencecies as it is unable to find the project.

Any help would be appreciated.

**Comment by kylef** [comment] 2015-03-31 02:40
It's a bit hard to debug this with such little information. Can you provide full steps to reproduce or create an example project demonstrating the issue you are having?

**Comment by neonichu** [comment] 2015-05-10 02:43
Since there was reaction for a long time, we can close this.

**Closed by neonichu** 2015-05-10 02:43 UTC
Labels: s1:awaiting input
