### ISSUE TITLE
[Feature] Support `weak_dependency` DSL in podspec

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8990] opened 2019-07-11 07:15 UTC
Case 1:

I have a debug tool which named `MyDebugTools`, it is a debug tool and will not release to appstore. So I always to use it in my Podfile:

```
pod 'MyDebugTools`, :configurations => ['Debug']
```

Now, I have another pod, it will support debug somethings by the debug tool. So I must import the debug tool into the pod:
```
#import "MyDebugTools.h"
```

Because I import the header in the `MyDebugTools`, I need to set the pod's dependency:
```
spec.dependency "MyDebugTools"
```

If I did, the `MyDebugTools` will included in all configurations!
So I think I need a `weak_dependency`, if the dependency exists, cocoapods will add the it into my header search path. If it non-exists, I will check it by `#has_include("MyDebugTools")`.

Case 2:
I have a pod, it will dependency another pod, and it is OPTIONAL! But I need the set the dependency version if the dependency exists.
```
spec.weak_dependency "OtherPod", "~>2.0"
```
So the `OtherPod` allow non-exists, but if it exists, it must match `~>2.0`.

Have an other better idea?

**Comment by amorde** [comment] 2019-07-11 17:52
Dupe of #6017 - this hasn't been implemented as it is a significant amount of work and no one has taken up the task.

Regarding your specific case, could you not use a Subspec for the debug utilities? You can conditionally include the debug spec using `:configurations`, and only include the base spec in the other configurations

**Comment by dnkoutso** [comment] 2019-07-11 17:54
closing as dup!

**Closed by dnkoutso** 2019-07-11 17:54 UTC
