### ISSUE TITLE
[0.36.0.beta.2] Debugging swift pods

### ISSUE THREAD

**Issue by sergdort** [CocoaPods/CocoaPods#3138] opened 2015-02-12 16:40 UTC
Don't know, is it an issue ( or I do something wrong ) but I can't see local  and instance var while debugging swift pods
![screen shot 2015-02-12 at 18 38 51](https://cloud.githubusercontent.com/assets/4622322/6171923/7b66dce4-b2e6-11e4-9e80-57d742fbdb20.png)

**Comment by segiddins** [comment] 2015-02-12 17:02
What happens if you `po value` there?

**Comment by foscomputerservices** [comment] 2015-02-12 18:37
I'm having much the same problem (Xcode Version 6.2 (6C121) - Cocoapods 0.36.0.beta.2). 

![lldb-crash](https://cloud.githubusercontent.com/assets/2438421/6174211/ed119bb0-b2b2-11e4-8144-08d1348df216.png)


Project is a swift project, contains 1 swift pod and multiple other non-swift pods.

Here's a gist with the full lldb text (it's huge 5227 lines):  https://gist.github.com/2fd6ea856b050e157e9f.git

**Comment by sergdort** [comment] 2015-02-12 19:03
So, let me clarify: I am trying to create my own swift POD.
When I do: po position I got this : po position
error: <EXPR>:1:1: error: use of unresolved identifier 'position'
position

![screen shot 2015-02-12 at 21 02 37](https://cloud.githubusercontent.com/assets/4622322/6174867/89b6fe96-b2fa-11e4-8860-eac523987bde.png)

**Comment by ide** [comment] 2015-02-17 19:58
@sergdort Try adding a dummy reference to `position` so it's retained.

```swift
let position = CGPoint(x: x, y: contentView.center.u)
println(position) // set breakpoint here -- after position is defined but before it is released
```

I believe there is a good chance CocoaPods is fine here and you're seeing the beta state of Swift.

**Comment by sergdort** [comment] 2015-02-17 20:18
@ide I’m pretty sure that problem here is because of developing pods via new feature of cocoapods “use_frameforks!” , because to handle this I’ve added that file as a target to another test project (without copy it) and it works fine.

![screen shot 2015-02-17 at 22 17 59](https://cloud.githubusercontent.com/assets/4622322/6236370/e35c6278-b6f2-11e4-813f-926ef0063264.png)

**Comment by ide** [comment] 2015-02-17 20:21
@sergdort the code in your most recent example retains a reference to `position` while the others released it. Have you tried debugging that exact code after building it as a framework?

**Comment by sergdort** [comment] 2015-02-17 20:23
Sorry, probably it was kind of bug, because after updating of xcode it works fine

**Comment by kylef** [comment] 2015-02-18 23:43
I've certainly experience some strange issues with lldb and Swift together. Breakpoints seem to break in the wrong place causing the variables to be incorrect to what you see in the current scope.

Perhaps try running `bt` to get a backtrace and compare where your breakpoint is to where lldb actually braked.

From the sound of it, this isn't a problem in CocoaPods and most likely an Xcode issue.

**Comment by kylef** [comment] 2015-02-19 00:52
This might actually be related to https://github.com/CocoaPods/CocoaPods/issues/3092.

**Comment by chrisco314** [comment] 2015-02-20 17:16
This is an exact duplicate of #3092. As noted in #3092, the work around is to remove the local include paths that cause the compiler to find the headers in the Pods directory instead of the generated "modular" location in DerivedData.

There was a separate problem, #3062, where cocoapods had the Debug / Release settings reversed and also stripped symbols on copy for debug builds.  Combined, these caused the stack pointer to jump around when trying to debug what was actually optimized release code, stripped of symbols.

In addition, as of Xcode 6.1, there was a crash bug in Xcode when it tried to look up missing symbols.

**Comment by kylef** [comment] 2015-02-20 17:18
Closing as a duplicate.

**Closed by kylef** 2015-02-20 17:18 UTC
Labels: s1:awaiting input
