### ISSUE TITLE
Pod with iOS and OSX support fails to to install resource bundle on iOS.

### ISSUE THREAD

**Issue by brianpartridge** [CocoaPods/CocoaPods#3227] opened 2015-03-04 16:38 UTC
I have an iOS test app consuming my pod which has iOS and OSX support and provides a resource bundle.  After installing, the resource bundle's target is configured to install to the default `CONFIGURATION_BUILD_DIR` which at and build time installs to `<DerivedData>/MyApp/Build/Products/Debug`.  

So when the script in the 'Copy Pods Resource' build phase in my test app runs, it looks for the the bundle in `BUILT_PRODUCTS_DIR` which resolves to `<DerivedData>/MyApp/Build/Products/Debug-iphonesimulator`. However, since the resource bundle is not there, the build fails.

Is this something that can be fixed in the Podfile config, or is it a legit bug with the generated Resource bundle target configuration?

**Comment by neonichu** [comment] 2015-03-04 16:52
The `BUILT_PRODUCTS_DIR` is different depending on which platform you are building for: *Debug* for OS X, *Debug-iphoneos` for iOS devices and `Debug-iphonesimulator` for iOS simulators. This is not really reflected inside Xcode's UI, though.

Does the 'Copy Pods Resource' phase actually fail for you or is this just an observation? Using the `resource_bundle` attribute works just fine in one of my projects.

**Comment by brianpartridge** [comment] 2015-03-04 16:56
That build phase actually fails because the Resource bundle isn't where it expects it to be:
```
PhaseScriptExecution Copy\ Pods\ Resources /Users/brianpartridge/Library/Developer/Xcode/DerivedData/CubeCoreTests-ezqzcrjlesvprxbkufdofqplgyap/Build/Intermediates/CubeCoreTests.build/Debug-iphonesimulator/CubeCore\ iOS\ Tests.build/Script-8482C8064E710D76CF9765C3.sh
    cd /Users/brianpartridge/src/cubecore
    /bin/sh -c \"/Users/brianpartridge/Library/Developer/Xcode/DerivedData/CubeCoreTests-ezqzcrjlesvprxbkufdofqplgyap/Build/Intermediates/CubeCoreTests.build/Debug-iphonesimulator/CubeCore\ iOS\ Tests.build/Script-8482C8064E710D76CF9765C3.sh\"

/Users/brianpartridge/Library/Developer/Xcode/DerivedData/CubeCoreTests-ezqzcrjlesvprxbkufdofqplgyap/Build/Products/Debug-iphonesimulator/CubeCoreResources.bundle
building file list ... rsync: link_stat "/Users/brianpartridge/Library/Developer/Xcode/DerivedData/CubeCoreTests-ezqzcrjlesvprxbkufdofqplgyap/Build/Products/Debug-iphonesimulator/CubeCoreResources.bundle" failed: No such file or directory (2)
done

sent 29 bytes  received 20 bytes  98.00 bytes/sec
total size is 0  speedup is 0.00
rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-42/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23
```

**Comment by neonichu** [comment] 2015-03-04 17:00
Could you share the podspec?

**Comment by brianpartridge** [comment] 2015-03-04 17:03
```
Pod::Spec.new do |s|
  s.name         = "CubeCore"

  # [snip]
  
  s.ios.deployment_target = "6.0"
  s.osx.deployment_target = "10.8"
  
  s.source_files = "CubeCore"
  s.private_header_files = "CubeCore/*_Internal.h"
  s.prefix_header_file = "Other/CubeCore-Prefix.pch"
  
  s.resource_bundle = { "CubeCoreResources" => ["Resources/CubeCoreResources/*"]}

end
```

I also tried `s.ios.resource_bundle` and `s.osx.resource_bundle` but it didn't seem to make a difference.

**Comment by brianpartridge** [comment] 2015-03-04 20:55
For now, I'm working around this in my consumer app by adding this `Run Script Build Phase` before `Copy Pods Resources`.  It's not great because the consumer needs to know the resource bundles, but it will work for as a temporary workaround.

```
GENERAL_BUILT_PRODUCTS_DIR=${BUILT_PRODUCTS_DIR%$EFFECTIVE_PLATFORM_NAME}
cp -r "${GENERAL_BUILT_PRODUCTS_DIR}/CubeCoreResources.bundle" "${BUILT_PRODUCTS_DIR}/CubeCoreResources.bundle"
```

**Comment by neonichu** [comment] 2015-03-05 10:36
Unfortunately, I have been unable to reproduce this. What does your resource bundle target show as base SDK?

**Comment by brianpartridge** [comment] 2015-03-05 14:41
Will post a demo project shortly.

**Comment by brianpartridge** [comment] 2015-03-05 16:29
Please take a look at this: https://github.com/brianpartridge/CubeApp
Building OSX works fine, but iOS fails due to the resource bundle issue.

**Comment by neonichu** [comment] 2015-03-05 16:49
Thanks for the example, the problem is exhibited by having both an OS X and an iOS target in the same Podfile.

This is a bug indeed in 0.35, because only one bundle target is being created with OS X deployment target. It is already fixed in 0.36, though, where we create multiple bundle targets.

**Closed by neonichu** 2015-03-05 16:49 UTC

**Comment by brianpartridge** [comment] 2015-03-05 16:53
Awesome, I just confirmed that this works as expected with pod 0.36.0.rc.1. Thanks so much for looking into this with me.

**Comment by Whirlwind** [comment] 2015-07-29 08:47
I got same error in v0.38.2.

```
pod "MWPhotoBrowser", "2.1.1"
```

I got error: 
```
/Users/whirlwind/Library/Developer/Xcode/DerivedData/Taobao4iPad-bdewgbqgebdtgqevabxmlvsfjedb/Build/Products/Debug-iphonesimulator/MWPhotoBrowser.bundle

building file list ... rsync: link_stat "/Users/whirlwind/Library/Developer/Xcode/DerivedData/Taobao4iPad-bdewgbqgebdtgqevabxmlvsfjedb/Build/Products/Debug-iphonesimulator/MWPhotoBrowser.bundle" failed: No such file or directory (2)
```

I check the `install_resouce` in `copy-resource.sh`
```
  install_resource "${BUILT_PRODUCTS_DIR}/MWPhotoBrowser.bundle"
```
