### ISSUE TITLE
pod repo update - fails on TravisCI Xcode 11.1 and above images

### ISSUE THREAD

**Issue by dlbuckley** [CocoaPods/CocoaPods#9259] opened 2019-10-15 14:01 UTC
### Command

```
/Users/travis/.rvm/gems/ruby-2.6.4/bin/pod repo update
```

### Report

We use TravisCI as our CI solution and have not had any issues when running cocoa pods on their Xcode 11 image. We tried updating to their Xcode 11.1 image (also tried Xcode 11.2 image) a few days ago and encountered an error (detailed below).

I reached out to Travis support as I suspected that it might be down to a change they made on their side between building the images, but their support engineer (Mustafa Ergul) has denied that there is anything wrong on their side and are insisting it's a cocoapods issue.

So I'm open to some pointers on this one if anyone has any good ideas?

### Stack

```

   CocoaPods : 1.8.3
        Ruby : ruby 2.6.4p104 (2019-08-28 revision 67798) [x86_64-darwin18]
    RubyGems : 3.0.6
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 11.2 (11B41)
         Git : git version 2.23.0

Ruby lib dir : /Users/travis/.rvm/rubies/ruby-2.6.4/lib

Repositories : 

```
### Plugins

```

claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/travis/.cocoapods/repos/Spec_Lock
/Users/travis/.rvm/gems/ruby-2.6.4/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `initialize'
/Users/travis/.rvm/gems/ruby-2.6.4/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `open'
/Users/travis/.rvm/gems/ruby-2.6.4/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `update'
/Users/travis/.rvm/gems/ruby-2.6.4/gems/cocoapods-1.8.3/lib/cocoapods/command/repo/update.rb:23:in `run'
/Users/travis/.rvm/gems/ruby-2.6.4/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/travis/.rvm/gems/ruby-2.6.4/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
/Users/travis/.rvm/gems/ruby-2.6.4/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
/Users/travis/.rvm/gems/ruby-2.6.4/bin/pod:23:in `load'
/Users/travis/.rvm/gems/ruby-2.6.4/bin/pod:23:in `<main>'
/Users/travis/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `eval'
/Users/travis/.rvm/gems/ruby-2.6.4/bin/ruby_executable_hooks:24:in `<main>'
```

**Comment by dnkoutso** [comment] 2019-10-15 14:03
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9216 and has been fixed for 1.8.4 already.

Workaround run `pod install` at least once.

**Closed by dnkoutso** 2019-10-15 14:03 UTC

**Comment by dlbuckley** [comment] 2019-10-15 14:05
Well talk about a speedy response! Sorry to waste your time @dnkoutso, thanks for the fix.

**Comment by tsimbalar** [comment] 2019-11-05 15:04
I've opened a topic in the Travis Community forums : https://travis-ci.community/t/pod-repo-update-fails-on-image-xcode-11/5788 ....
