### ISSUE TITLE
 Class <XxXXx> is implemented in both.Problem with Test target.

### ISSUE THREAD

**Issue by viniciusmo** [CocoaPods/CocoaPods#4355] opened 2015-10-09 19:14 UTC
Hi,

I'm having some problems to perform my unit tests . When I run my unit tests , all classes are duplicated.

Example output from Xcode console:

![Xcode Console output](http://s7.postimg.org/gbpeztvuj/Screen_Shot_2015_10_09_at_4_08_09_PM.png)

My Podfile

    source 'git@github.com:CocoaPods/Specs.git'
	platform :ios, "8.0"

	inhibit_all_warnings!

	def fabric_pods
	    pod 'Digits'
	    pod 'TwitterCore'
	    pod 'Crashlytics'
	    pod 'Fabric'
	end

	def movile_pods
	    pod 'AFNetworking'
	end

	def ui_pods
	    pod 'JSQMessagesViewController',:git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
	    pod 'UIActionSheet+Blocks'
	    pod 'NYTPhotoViewer'
	    pod 'UIAlertView+Blocks'
	    pod 'UIAlertController+Blocks'
	    pod 'MBProgressHUD'
	    pod 'SDWebImage'
	end

	def project_pods
	    pod 'Parse'
	    pod 'FBSDKCoreKit'
	    pod 'Mixpanel'
	    pod 'DeepLinkKit'
	    pod 'Flurry-iOS-SDK'
	end

	fabric_pods
	movile_pods
	ui_pods
	project_pods

	link_with 'Resolve', 'Resolve Tests'

Version CocoaPods`0.38.2`

**Comment by segiddins** [comment] 2015-10-09 19:15
You shouldn't be linking your pods to your test target, only your app target.

**Comment by viniciusmo** [comment] 2015-10-09 19:27
When I remove the link_with of the test target , the error continues.

**Comment by segiddins** [comment] 2015-10-09 19:31
What if you do

```ruby
target 'Resolve' do
  # ... pods
end
```

If not, could you please try running https://github.com/kylef/cocoapods-deintegrate and installing again?

**Comment by viniciusmo** [comment] 2015-10-09 20:24
I did the following steps:
 


I updated my Podfile for:

    source 'git@github.com:CocoaPods/Specs.git'
	platform :ios, "8.0"

	inhibit_all_warnings!

	def fabric_pods
	    pod 'Digits'
	    pod 'TwitterCore'
	    pod 'Crashlytics'
	    pod 'Fabric'
	end

	def movile_pods
	    pod 'AFNetworking'
	end

	def ui_pods
	    pod 'JSQMessagesViewController',:git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
	    pod 'UIActionSheet+Blocks'
	    pod 'NYTPhotoViewer'
	    pod 'UIAlertView+Blocks'
	    pod 'UIAlertController+Blocks'
	    pod 'MBProgressHUD'
	    pod 'SDWebImage'
	end

	def project_pods
	    pod 'Parse'
	    pod 'FBSDKCoreKit'
	    pod 'Mixpanel'
	    pod 'DeepLinkKit'
	    pod 'Flurry-iOS-SDK'
	end

	fabric_pods
	movile_pods
	ui_pods
	project_pods

	target :Resolve do
	    fabric_pods
	    movile_pods
	    ui_pods
	    project_pods
	end

 - I run the command `pod deintegrate`

Result:

![](http://s24.postimg.org/jghpgvegl/Screen_Shot_2015_10_09_at_5_14_58_PM.png)

**Comment by segiddins** [comment] 2015-10-09 20:28
And did you re-install after de-integrating?

**Comment by viniciusmo** [comment] 2015-10-09 20:33
Yes

**Comment by segiddins** [comment] 2015-10-09 20:33
And what it you do `#import <Mantle/Mantle.h>` ? If that doesn't fix things, please share a project we can use to debug.

**Comment by viniciusmo** [comment] 2015-10-09 20:42
Not working :( 

![enter image description here](http://s11.postimg.org/ytdkwsur7/Screen_Shot_2015_10_09_at_5_40_19_PM.png)

And i can't share my project :(

**Comment by segiddins** [comment] 2015-10-09 20:46
In that case, we'll have to close the issue, as there's nothing really we can do :(

**Comment by viniciusmo** [comment] 2015-10-09 20:48
Ok,thanks :)

**Comment by viniciusmo** [comment] 2015-10-10 17:16
@segiddins 

I created the simple project with a problem:

https://drive.google.com/file/d/0ByA6RybAn585Vm83by1lNXJ6aTQ/view

**Comment by neonichu** [comment] 2015-10-11 17:06
Cannot reproduce the problem with CP 0.39.0

**Comment by bixbarton** [comment] 2015-10-12 22:16
I'm also seeing the duplicated pod classes, only with Xcode7 and only when testing.

Wonder what is causing this?

**Comment by viniciusmo** [comment] 2015-10-13 13:28
Same problem with 0.39.0.
@neonichu  You 'run' my project with testing mode?

**Comment by viniciusmo** [comment] 2015-10-14 18:05
@neonichu @segiddins 

If you remove the target of link_with of tests the error is ' Header not found ' . If I leave the link_with in my PodFile , all classes are duplicated and my tests fail.

![enter image description here](http://s30.postimg.org/mdx4ppya7/Untitled.gif)

**Comment by farrakha** [comment] 2015-10-14 19:51
We are seeing the exact same issue. It only occurs with Xcode 7 when running tests and reproducible with 0.37.2, 0.38.2 and 0.39. Tried just about everything to resolve it with no luck.

**Comment by neonichu** [comment] 2015-10-16 08:07
Right, the problem you're seeing is actually #1411 — the solution is still the same: at least one dependency is required for CP to integrate the test target at all, once you add one, the header search path will be set up correctly for the test target.

**Closed by neonichu** 2015-10-16 08:07 UTC
Labels: s1:awaiting input

**Comment by ripperhe** [comment] 2017-03-22 08:06
same problem with 1.1.1
