### ISSUE TITLE
Error in integrating Cocoapdos with static library

### ISSUE THREAD

**Issue by shshnk28** [CocoaPods/CocoaPods#3480] opened 2015-05-01 05:06 UTC
I am trying to integrate `AFNetworking` using Cocoapods in my static library. This static library builds against my main project.I want `AFNetworking` to be available for one target of my static library project and two targets of my main project. After integrating cocoapods static library builds fine but when I try to build my main project I get this error.

    error: /Applications/Xcode 6.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: can't locate file for: -lPods-AFNetworking
    error: /Applications/Xcode 6.2.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/libtool: file: -lPods-AFNetworking is not an object file (not allowed in a library)

Here are the contents of Pods debug config file

    GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
    HEADER_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/AFNetworking"
    OTHER_CFLAGS = $(inherited) -isystem "${PODS_ROOT}/Headers/Public" -isystem "${PODS_ROOT}/Headers/Public/AFNetworking"
    OTHER_LDFLAGS = $(inherited) -ObjC -l"Pods-AFNetworking" -framework "CoreGraphics" -framework "MobileCoreServices" -framework "Security" -framework "SystemConfiguration"
    OTHER_LIBTOOLFLAGS = $(OTHER_LDFLAGS)
    PODS_ROOT = ${SRCROOT}/Pods

here are the contents of my pod file.

    # Uncomment this line to define a global platform for your project
    # platform :ios, '7.0'

    link_with 'Target-(staticLibProject)', 'Target1-(MainProject)' , 'Target2 (MainProject)'
    source 'https://github.com/CocoaPods/Specs.git'
    platform :ios, '7.0'
    pod 'AFNetworking', '~> 2.5'

**Comment by neonichu** [comment] 2015-05-01 07:35
This is a duplicate of #2747

**Closed by neonichu** 2015-05-01 07:35 UTC
