### ISSUE TITLE
Realm not compiling in pod version 1.0.0.beta.8

### ISSUE THREAD

**Issue by royherma** [CocoaPods/CocoaPods#5197] opened 2016-04-25 17:47 UTC
# Report

## What did you do?

Run `pod install`

## What did you expected to happen?

Expected project to compile and run

## What happened instead?

Pod `Realm` is unable to compile, throwing error `realm/util/features.h` file not found

## Podfile
```
platform :ios, '9.0'
use_frameworks!

target 'ProjectName' do
  pod 'AFNetworking', '~> 2.6', :inhibit_warnings => true
  pod 'Analytics', '3.0.4-alpha', :inhibit_warnings => true
  pod 'CocoaLumberjack', '2.1.0-beta'
  pod 'Crashlytics', '~> 3.3'
  pod 'Fabric', '~> 1.5'
  pod 'Google/SignIn'
  pod 'Heap', '~> 2.2'
  pod 'Intercom', '~> 2.3'
  pod 'JSQMessagesViewController', '~> 7.2'
  pod 'Mixpanel', '~> 2.9', :inhibit_warnings => true
  pod 'Outbound', '~> 0.1'
  pod 'Realm+JSON', '0.2.14'
  pod 'SDWebImage', '~> 3.7', :inhibit_warnings => true
  pod 'SevenSwitch', '~> 1.4'
  pod 'SimpleKeychain', '~> 0.7.0'
  pod 'TSMessages', '~> 0.9', :inhibit_warnings => true
  pod 'XLForm', '~> 3.0', :inhibit_warnings => true
  pod 'SimpleKeychain', '~> 0.7.0'
  pod 'UITextView+Placeholder', '~> 1.1.1'
  pod 'ChameleonFramework', '~> 2.1.0' , :inhibit_warnings => true
  pod 'Segment-Amplitude'
  
  #Outlook
  pod 'ADALiOS', '~> 1.2.1'
  pod 'Office365/Outlook', '= 0.9.1'
  pod 'Office365/Discovery', '= 0.9.1'

end
```

**Comment by segiddins** [comment] 2016-04-25 18:58
@mrackwitz any interest?

**Comment by mrackwitz** [comment] 2016-04-25 19:44
Hey @royherma, have you tried to nuke derived data and build completely clean from scratch?

**Comment by royherma** [comment] 2016-04-25 20:08
@mrackwitz yep, ran pod `deintegrate || rm -rf Pods` followed by `pod install`

**Comment by mrackwitz** [comment] 2016-04-26 14:07
@royherma: Have you tried to clear the CocoaPods cache by `pod cache clean`?

**Comment by mrackwitz** [comment] 2016-05-13 12:31
I'm going to close this issue for now as you didn't came back with further info and I'm unable to reproduce it. If it should persist or re-appear for you or anyone else, please feel free to open an issue over at the [realm-cocoa](https://github.com/realm/realm-cocoa) repository and I'll do my best to assist you there.

**Closed by mrackwitz** 2016-05-13 12:31 UTC
Labels: s1:awaiting input
