### ISSUE TITLE
Invalid archive produced when using "Archive" in Xcode 7 GM (with watchkit extension)

### ISSUE THREAD

**Issue by mrezk** [CocoaPods/CocoaPods#4021] opened 2015-08-13 18:21 UTC
🌈The issue can be reproduced with a slighly modified version of this repo's watchOS example ([link](https://github.com/mrezk/CocoaPods/tree/mod/examples/watchOS%20Example)).
I had to modify the original version since I could not make it build.

After successfully archiving the app, the sample project archive is listed as "other items" and with type "Generic Xcode Archive":<img width="512" alt="screenshot 2015-08-13 15 05 58" src="https://cloud.githubusercontent.com/assets/1587829/9257649/0f960d70-41cd-11e5-907c-cd4991d44c05.png">

When inspecting the generated archive, the first strange thing is that the key ApplicationProperties is missing on `Info.plist` file:
<img width="512" alt="screenshot 2015-08-13 15 06 32" src="https://cloud.githubusercontent.com/assets/1587829/9257648/0f95ddbe-41cd-11e5-99d5-0ba9640f5d3a.png">

Moreover, `Products` folder includes the `watchOSSample WatchKit Extension.appex`, which is also weird:
<img width="512" alt="screenshot 2015-08-13 15 06 46" src="https://cloud.githubusercontent.com/assets/1587829/9257650/0f968638-41cd-11e5-860d-d3e31c907935.png">

Finally, if I remove the "Copy Pods Resources" and "Check Pods Manifests.lock" from the watchkit extension target build phases, I get a valid archive.

**Comment by PorterHoskins** [comment] 2015-08-14 16:41
+1

**Comment by skydivedan** [comment] 2015-08-14 19:12
+1

**Comment by segiddins** [comment] 2015-08-15 00:55
@mrezk so my guess then is that it's an issue with us creating `${CONFIGURATION_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}` ...

**Comment by TravisCrist** [comment] 2015-08-15 03:36
+1  
I believe this is the cause of the issue I wrote up on stackoverflow [Xcode 7 will NOT build a valid Archive from the same project that builds a valid archive in Xcode 6](http://stackoverflow.com/questions/32002764/xcode-7-will-not-build-a-valid-archive-from-the-same-project-that-builds-a-valid). It could be Apple as well, I have not ruled that out as the root cause.

**Comment by livsik** [comment] 2015-08-18 14:25
+1
Removing "copy pod resources" from extension target solves the problem.
The problem is only reproduced in XCode 7 + cocoapods 0.38.2

**Comment by davidmcnerney** [comment] 2015-08-18 22:51
+1 same experience here, removing the two build phases mentioned above also fixed it for me.

**Comment by TravisCrist** [comment] 2015-08-19 03:03
Update, tried, the removal of "copy pod resources" from my today extension target and that resolved the issue for me as well.

**Comment by skydivedan** [comment] 2015-08-19 13:23
I've had success getting the latest cocoapods master from github. I had to re-install the "xcode tools" first. But it looks like 0.39 (or 0.38.3?) will fix the issue.

**Comment by mrezk** [comment] 2015-08-24 18:50
@skydivedan great find! I can confirm that this issue is solved on the master version.

**Comment by pakmee** [comment] 2015-09-10 19:06
Hi I've tried the above but am still having issues archiving on Xcode 7 with the watch extension. My archive is always a generic one. I have the watch extension and an action extension. I have no issues with Xcode 6.

**Comment by mrezk** [comment] 2015-09-10 19:15
@pakmee I built a CocoaPods gem from following commit https://github.com/CocoaPods/CocoaPods/commit/5f9e19c11867eefa937e01000f5c5781c71e1edd. You can find it [here](https://dl.dropboxusercontent.com/u/2444087/cocoapods-0.38.2.gem).

After installing the gem, run `pod install` and try to build again. Make sure you don't  have a newer version than 0.38.2 installed.

Please let me know if this helps!

**Comment by mrezk** [comment] 2015-09-10 20:17
@segiddins just tried to archive with `0.39.0.beta.4` and I am still getting and invalid archive. But due to different reasons:

Products directory includes `usr/local/include` (looks exactly like [this issue](https://github.com/CocoaPods/CocoaPods/issues/747))

And `Info.plist` file is still messed up (ApplicationProperties key is missing).

Any clues on this mutating issue?

**Comment by pakmee** [comment] 2015-09-10 20:18
Hi thanks for the gem. I am now getting linking errors. I am looking into it. Been banging my head for the whole day :(

**Comment by pakmee** [comment] 2015-09-10 20:39
hey @mrezk I got it working with Beta 3. Beta 4 is also broken. Need to check what changed there but this seems to be related to this issue : https://github.com/CocoaPods/CocoaPods/issues/4119

**Comment by larryonoff** [comment] 2015-09-13 18:39
fixed updating into 0.39.0.beta.3, but not 0.39.0.beta.4

**Comment by nhattieunhatkiem** [comment] 2015-09-14 15:46
removing "copy pod resources" work on my case too

**Comment by garohussenjian** [comment] 2015-09-14 16:42
For me, the most direct workaround was to drag "Public" headers to "Project" for Header build phase in each Pod target. Some of the other workarounds mentioned in this thread might have unwanted side-effects.

**Comment by michelalbers** [comment] 2015-09-15 11:22
Removing copy pod resources from today extension and watchkit extension did the trick! +1

**Comment by ConfusedVorlon** [comment] 2015-09-15 21:43
+1 (so I get notified on progress)

**Comment by jhollida24** [comment] 2015-09-16 02:27
also commenting, to observe progress

**Comment by derjohng** [comment] 2015-09-16 02:35
Removing copy pod resources from today extension and watchkit extension +1

**Comment by TinyBun** [comment] 2015-09-16 13:52
This issue can be reproduced on 0.39.0.beta.4, with Xcode 6.4

I have tried both suggested methods -  
1. Remove copy pods resources and check pods manifest.lock from build phases 
2. Move all "Public" headers to "Project" headers for Headers build phase

Both methods can generate the correct archive.

**Comment by ebfio** [comment] 2015-09-16 14:00
+1, removing the Copy Pod Resources and Move Public to Project headers did the trick, Cocoapods 0.39.0 b4.

**Comment by danielgalasko** [comment] 2015-09-17 12:56
Can indeed confirm that running an install with beta 3: `sudo gem install cocoapods -v 0.39.0.beta.3 --verbose` I can generate a valid archive

**Comment by PaulEhrhardt** [comment] 2015-09-18 14:27
+1 me too, hat to uninstall the previous cocoa pods before installing the beta

**Comment by sehugg** [comment] 2015-09-18 16:04
+1 downgrading did the trick.

**Comment by wilferrel** [comment] 2015-09-18 21:33
+1 in uninstalling all versions prior to installing version that @danielgalasko  suggested. I also removed copy pod resources from Extension Build phase steps

**Comment by garohussenjian** [comment] 2015-09-18 21:51
@ebfio You both removed Copy Pod Resources and Move Public to Project headers... was this necessary? Was removing resources build phase necessary to resolve the issue? I'm curious b/c I was able to archive w/o removing the Pod resources, just moving the headers. (also reverting to 0.38.2 and rebuilding the Pods seems to work) ;-)

**Comment by ebfio** [comment] 2015-09-18 21:58
Hey @garohussenjian!

Yep, I had to do both. My project is Swift + Objective-C + C++, so that could be the issue. And even 0.38.2 doesn't fix the problem for me :(

Say hi to everybody there ;)

**Comment by jhabdas** [comment] 2015-09-19 00:26
@pakmee thanks for linking that issue. After some hours of debugging I'd tried many things including tweaking build settings and rolling back my CocoaPods installation. But was able to get the expected iOS App archive by following the [sage advice](https://github.com/CocoaPods/CocoaPods/issues/4119#issuecomment-137169818) of @tomislav in #4119.

**Comment by jun1st** [comment] 2015-09-20 02:13
+1 downgrade to beta3 did the trick

**Comment by fguchelaar** [comment] 2015-09-20 19:05
+1 beta3 solved my issue. Sadly it took me almost an entire Sunday, before I *stumbled* upon this page...

**Comment by lewis-smith** [comment] 2015-09-20 20:06
Removing copy pod resources from today extension and watchkit extension did the trick for me.

**Comment by georgbachmann** [comment] 2015-09-21 09:10
+1 AWESOME :) Why didn't I read that earlier... lost half a day and now it finally works again!!!! Thanks so much!!!!

**Comment by xpact** [comment] 2015-09-21 20:58
downgrading to cocoapods-0.39.0.beta.3 did the trick

**Comment by floriankrueger** [comment] 2015-09-24 08:36
just in case somebody is using the Xcode Server C.I. and receives the message (after successful build)

```
Build Service Warning Creating installable product failed: xcodebuild exited with status 6
```

<img width="518" alt="screen shot 2015-09-24 at 08 45 19" src="https://cloud.githubusercontent.com/assets/646386/10068823/f6370dd8-62a7-11e5-887f-3c4ec7857c8d.png">

downgrading to cocoapods 0.38.2 did the trick for me.

**Comment by Lucien** [comment] 2015-09-24 16:56
+1 0.39.0.beta.3 works and 0.39.0.beta.4 generates a Generic Xcode Archive

**Comment by Jules2010** [comment] 2015-09-24 19:36
Doing a complete uninstall the install of release version works for me, phew, spent a couple of hours on this.
```
sudo gem uninstall cocoapods
sudo gem uninstall cocoapods-core
sudo gem uninstall cocoapods-downloader
sudo gem install cocoapods
```

**Comment by aksonov** [comment] 2015-09-24 20:08
+1, the same

**Comment by macecchi** [comment] 2015-09-24 20:27
+1. I did the complete uninstall as @Jules2010 pointed out and downgraded to 0.38.2, which worked.

**Comment by sirnacnud** [comment] 2015-09-25 15:03
I had to upgrade from 0.38.2 to 0.39.0.beta.3 in order to generate a valid archive.

**Comment by efremidze** [comment] 2015-09-25 22:02
+1 0.39.0.beta.3 archives perfectly!

**Comment by ADSolutions** [comment] 2015-09-26 14:31
+1, same thing

**Comment by segiddins** [comment] 2015-09-26 15:26
Since this is fixed in the betas, I'm going to close this issue for now. Thanks so much to everyone for chiming in!

**Closed by segiddins** 2015-09-26 15:26 UTC

**Comment by rocxteady** [comment] 2015-09-26 15:39
I was using Beta 4. When I change the deployment target to 8.0 It archives without any issues. But when change it to 7.0, it can't archive correctly.

But like mentioned above, when I change Cocoapods version to Beta 3, there is no problem anymore.

**Comment by aksonov** [comment] 2015-09-26 15:52
@segiddins But Beta 4 contains this bug! Beta 3 - doesn't.

**Comment by segiddins** [comment] 2015-09-26 15:54
@aksonov beta 4 has a different bug that is already being addressed.

**Comment by knightcode** [comment] 2015-09-27 01:58
with 0.30.0-beta-4, I only had to move Public and Private headers to Project

**Comment by paulz** [comment] 2015-09-27 07:57
+1 
with cocoapods (0.39.0.beta.4) Xcode 7 creates Generic Xcode Archive that can't be uploaded to AppStore.
I've downgraded to cocoapods (0.39.0.beta.3) by using Gemfile entry:
```gem 'cocoapods', '= 0.39.0.beta.3'```
then run ```pod install```
and now Xcode 7 creates valid iOS App Archive

**Comment by zfdang** [comment] 2015-09-28 13:50
+1 bug with 0.39.0.beta.4 & xcode 7

**Comment by itlijunjie** [comment] 2015-09-28 15:53
+1 0.39.0.beta.3 archives perfectly!

**Comment by Mazorati** [comment] 2015-10-01 14:36
+1 Xcode generate "Generic Xcode Archive"
cocoapods 0.38.2

**Comment by yaalaa** [comment] 2015-10-01 18:36
+1 0.39.0.beta.3 (+uninstall other versions) archives perfectly!

**Comment by BeanDu** [comment] 2015-10-21 12:26
+1

**Comment by edwardmp** [comment] 2015-11-06 02:23
+1 Xcode generates "Generic Xcode Archive"
