### ISSUE TITLE
Using a CocoaPod with a dependency that has a subspec and then using that dependency subspec directly causes "file not found" on import (1.0.0.rc.1)

### ISSUE THREAD

**Issue by vinceis1337** [CocoaPods/CocoaPods#5241] opened 2016-05-03 20:09 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Pod 1: RMNCommon
   -Has subspec 'ImagePicker' which contains a dependency on PEPhotoCropEditor
   -Has subspec 'Network' which contains a dependency on Reachability

Pod 2: RMNCitadelClient which contains a dependency on RMNCommon/Network

Project: test project
   -Uses pod 'RMNCitadelClient'
   -Uses pod 'RMNCommon/ImagePicker'

## What did you expected to happen?

Pods should install and compile.

## What happened instead?

![screen shot 2016-05-03 at 3 02 22 pm](https://cloud.githubusercontent.com/assets/5994871/14996547/21b412a2-1140-11e6-9a21-85ca1c5077bf.png)
![screen shot 2016-05-03 at 3 07 52 pm](https://cloud.githubusercontent.com/assets/5994871/14996690/db6c394a-1140-11e6-92d5-1e8dac373e3a.png)
When building test project, RMNCitadelClient is showing error 'PECropViewController.h' file not found only INSIDE the test project.

![screen shot 2016-05-03 at 3 05 57 pm](https://cloud.githubusercontent.com/assets/5994871/14996641/99df5084-1140-11e6-932a-171404b2ad92.png)
RMNCitadelClient builds successfully.

![screen shot 2016-05-03 at 3 03 38 pm](https://cloud.githubusercontent.com/assets/5994871/14996581/4b63c160-1140-11e6-81af-d71db7284c1c.png)
RMNCommon project compiles successfully.

Please note that RMNCitadelClient does NOT use ImagePicker subspec or use PEPhotoCropEditor at all!

## Podfile

RMNCommon Podfile
```ruby
source 'redacted specs url'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

xcodeproj 'RMNCommon.xcodeproj'

target 'RMNCommon' do
  pod 'SVProgressHUD','0.9', :inhibit_warnings => true
  pod 'PEPhotoCropEditor', '1.3', :inhibit_warnings => true
  pod 'Reachability', '3.2', :inhibit_warnings => true
  pod 'Base32', '~> 1.1'
  pod 'UICKeyChainStore', '2.0.6'
  
  # internally-managed specs
  pod 'Haversine', '0.0.1'
end
```

RMNCommon Podspec
```ruby
Pod::Spec.new do |s|
  s.name         = "RMNCommon"
  s.version      = "1.1.12"
  s.summary      = "redacted summary"
  s.homepage     = "redacted homepage"
  s.license      = { :type => 'Copyright (c)', :file => 'LICENSE.txt' }
  s.authors      = { redacted authors }

  s.source       = { redacted source url }

  s.ios.deployment_target = '8.0'
  s.osx.deployment_target = '10.9'

  # ――― MULTI-PLATFORM VALUES ――――――――――――――――――――――――――――――――――――――――――――――――― #

  s.exclude_files = 'RMNCommon/Exclude'
  s.xcconfig       = { 'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/"' }
  s.requires_arc = true

  # --- Subspecs --- #

  s.subspec 'Base' do |base|
    base.source_files = 'RMNCommon/RMNBase/**/*.{h,m}'
    base.dependency 'Base32', '~> 1.1'
  end

  s.subspec 'Models' do |models|
    models.source_files = 'RMNCommon/RMNModels/**/*.{h,m}'
    models.dependency 'UICKeyChainStore', '2.0.6'
  end

  s.subspec 'ImagePicker' do |imagePicker|
    imagePicker.source_files = 'RMNCommon/RMNImagePicker/**/*.{h,m}'
    imagePicker.dependency 'RMNCommon/Base'
    imagePicker.dependency 'RMNCommon/UIKit'
    imagePicker.dependency 'PEPhotoCropEditor', '1.3'
  end

  s.subspec 'LocationManager' do |locationManager|
    locationManager.source_files = 'RMNCommon/RMNLocationManager/**/*.{h,m}'
    locationManager.dependency 'RMNCommon/Base'
    locationManager.dependency 'Haversine', '0.0.1'
  end

  s.subspec 'Mapping' do |mapping|
    mapping.frameworks = 'MapKit'
    mapping.source_files = 'RMNCommon/RMNMapping/**/*.{h,m}'
  end

  s.subspec 'Network' do |network|
    network.source_files = 'RMNCommon/RMNNetwork/**/*.{h,m}'
    network.dependency 'RMNCommon/Base'
    network.dependency 'Reachability', '3.2'
  end

  s.subspec 'Twitter' do |twitter|
    twitter.source_files = 'RMNCommon/RMNTwitter/**/*.{h,m}'
    twitter.frameworks  = 'Accounts', 'Twitter'
  end

  s.subspec 'UIKit' do |uikit|
    uikit.source_files = 'RMNCommon/RMNUIKit/**/*.{h,m}'
    uikit.resources = ['RMNCommon/RMNUIKit/*.{xib,otf,ttf}']
    uikit.dependency 'RMNCommon/Base'
  end

  s.subspec 'WebBrowser' do |webBrowser|
    webBrowser.source_files = 'RMNCommon/RMNWebBrowser/**/*.{h,m}'
    webBrowser.resources = ['RMNCommon/RMNWebBrowser/*.xib', 'RMNCommon/RMNWebBrowser/images/*.png']
    webBrowser.dependency 'RMNCommon/Base'
    webBrowser.dependency 'RMNCommon/UIKit'
    webBrowser.dependency 'RMNCommon/Network'
  end

end
```

RMNCitadelClient Podfile
```ruby
inhibit_all_warnings!
source 'https://github.com/CocoaPods/Specs.git'
source 'redacted specs url'

platform :ios, '8.0'
use_frameworks!

def common_pods
    pod 'CocoaLumberjack', '~> 2.2'
    pod 'UrbanAirship-iOS-SDK', '~> 7.0'
    pod 'OCMock', '~> 3.1.2'
    pod 'RMNCommon/Network', :path => "../../rmn-common-ios"
end

target 'RMNCitadelClient' do
    common_pods
end

target 'RMNCitadelClientTests' do
    common_pods
end
```

RMNCitadelClient Podspec
```ruby
Pod::Spec.new do |sdk|
  sdk.name          = 'RMNCitadelClient'
  sdk.version       = '2.0.0'
  sdk.author        = { redacted }
  sdk.license       = { :type  => 'MIT', :file => 'LICENSE' }
  sdk.homepage      = redacted hompage
  sdk.source        = { repo url redacted }
  sdk.summary       = 'iOS Citadel client SDK.'
  sdk.description   = 'redacted description'

  sdk.ios.deployment_target = '7.0'
  sdk.osx.deployment_target = '10.9'

  sdk.dependency 'CocoaLumberjack', '~> 2.2'
  sdk.dependency 'UrbanAirship-iOS-SDK', '~> 7.0'
  sdk.dependency 'OCMock', '~> 3.1.2'
  sdk.dependency 'RMNCommon/Network', '~> 1.1.12'
  sdk.requires_arc  = true
  sdk.xcconfig      = {
    'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/" "$(PLATFORM_DIR)/Developer/Library/Frameworks"'
  }

  sdk.source_files  = 'RMNCitadelClient/*'
  sdk.resources     = 'RMNCitadelClient/schemas.bundle'
end
```

Test Project Podfile
```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'

source 'redacted specs url'
source 'https://github.com/CocoaPods/Specs.git'


use_frameworks!


target 'test' do
	pod 'RMNCommon/ImagePicker', :path => "../rmn-common-ios"
	pod 'RMNCitadelClient', :path => "../citadel/ios-client-sdk"
end

target 'test WatchKit 1 Extension' do

end

target 'test WatchKit 1 App' do

end

target 'testTests' do

end

target 'testUITests' do

end
```

**Comment by vinceis1337** [comment] 2016-05-03 20:18
If I remove the ImagePicker subspec pod (comment it out):

```ruby
pod 'RMNCommon/ImagePicker', :path => "../rmn-common-ios"
```
to
```ruby
#pod 'RMNCommon/ImagePicker', :path => "../rmn-common-ios"
```

test project builds successfully.

**Comment by fcy** [comment] 2016-05-04 02:06
I think I have a similar problem. I switched my project to use `use_frameworks!` and I started getting file not found from all the subspecs.

**Comment by segiddins** [comment] 2016-05-04 06:41
Can you please try and reduce this to a runnable project where the podspecs don't set custom frameworks search paths? Thanks!

**Comment by vinceis1337** [comment] 2016-05-04 15:02
@segiddins I removed these portions:

RMNCommon
```ruby
  s.xcconfig       = { 'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/"' }
```

RMNCitadelClient
```ruby
  sdk.xcconfig      = {
    'FRAMEWORK_SEARCH_PATHS' => '"$(PODS_ROOT)/" "$(PLATFORM_DIR)/Developer/Library/Frameworks"'
  }
```

The same error occurred.

![](https://cloud.githubusercontent.com/assets/5994871/14996690/db6c394a-1140-11e6-92d5-1e8dac373e3a.png)

**Comment by segiddins** [comment] 2016-05-04 15:17
Ok, but we still need a project we can use to debug.

**Comment by vinceis1337** [comment] 2016-05-04 16:12
@segiddins Oh I see. I'll try to get it set up for you soon.

**Comment by segiddins** [comment] 2016-05-09 03:25
https://github.com/CocoaPods/CocoaPods/issues/5266 might fix this

**Comment by neonichu** [comment] 2016-05-15 13:59
Closing, because we never got a reproducible project.

**Closed by neonichu** 2016-05-15 13:59 UTC
Labels: s1:awaiting input
