### ISSUE TITLE
Pod Install Error ? SSzipArchive into a CFTypeRef

### ISSUE THREAD

**Issue by ttoggaiman** [CocoaPods/CocoaPods#5955] opened 2016-09-26 02:21 UTC
> ℹ Please fill out this template when filing an issue.
> All lines beginning with an ℹ symbol instruct you with
> what info we expect.  
> Please remove this line and all above before submitting.

> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
>
> Xcode 8 Status: Only works with CocoaPods 1.1.0
> Swift 3: You need to add a `.swift-version` file, see the CHANGELOG
> China: Use https://gems.ruby-china.org/ instead of https://gems.ruby-china.org/ for the RC see #5910

* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Pod install

## What did you expect to happen?
install all pod correctly

## What happened instead?

I got error

![1](https://cloud.githubusercontent.com/assets/22382653/18820716/fc524444-83da-11e6-8a12-0295434bd17d.png)
![2](https://cloud.githubusercontent.com/assets/22382653/18820719/ffc4f5d6-83da-11e6-8d7d-7fea03013bf1.png)

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/test/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8ac5bc733e158d348e33e236df43b9ac71c93fde
```

### Installation Source

```
Executable Path: /Users/test/.rvm/rubies/ruby-2.2.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :osx, '10.9'
use_frameworks!

target 'RealmConverter' do
pod 'Realm'
pod 'PathKit', '~> 0.6.0' # 0.7+ requires swift 3
pod 'CSwiftV'
pod 'TGSpreadsheetWriter'

target 'RealmConverterTests'
end


post_install do |installer|
installer.pods_project.targets.each do |target|
target.build_configurations.each do |config|
config.build_settings['SWIFT_VERSION'] = '2.3'
end
end
end
```

## Project that demonstrates the issue
my text build with xcode 8, swift 2.2(legacy swift check) 
i have download realm convert project
(https://github.com/realm/realm-cocoa-converter)
but i got error with  pod install..

**Comment by MP0w** [comment] 2016-09-26 13:53
Most likely duplicate of: https://github.com/CocoaPods/CocoaPods/issues?utf8=✓&q=is%3Aissue%20into%20a%20CFTypeRef

**Comment by DanToml** [comment] 2016-10-02 07:27
This is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/5037.
It is a bug in Ruby's FFI implementation in 2.2.0 -> 2.2.2, please use 2.2.3+

**Closed by DanToml** 2016-10-02 07:27 UTC
