### ISSUE TITLE
pod install installs public pod instead of private pod

### ISSUE THREAD

**Issue by deathByLiche** [CocoaPods/CocoaPods#7979] opened 2018-08-06 18:35 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run 'pod install'

## What did you expect to happen?

Install private pod 'A'

## What happened instead?

Installed public pod 'B' instead of private pod 'A', where public pod 'B' has same name as private pod 'A'.

Private pod 'A' also depends on other private pods and a public pod, and both the current project and private pod 'A' have my CustomPodspecRepo source above the default public CocoaPod spec repo.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.4
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.15.2 (Apple Git-101.1)
Ruby lib dir : /Users/jhall/.rvm/rubies/ruby-2.5.0/lib
Repositories : cocoapod-specs - git@myCustomSpecsRepo.git @ 71b2f81ec8aae258b5c0197d3cd4bc9c459d67ab
               master - https://github.com/CocoaPods/Specs.git @ bba16a5b7ef88b72e9e97e5e4e82e80c1716b8b8
```

### Installation Source

```
Executable Path: /Users/jhall/.rvm/gems/ruby-2.5.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'git@myCustomSpecsRepo.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!

platform :ios, '10.0'

abstract_target 'MyProjPods' do

	pod 'MyPrivatePod', '~> 1.0'

	target 'MyProj'
        target 'MyProjTests'
end
```

**Comment by dnkoutso** [comment] 2018-08-06 18:39
Hey there @deathByLiche thanks for the report. This is currently a duplicate of https://github.com/CocoaPods/CocoaPods/issues/7354 and has a related PR open https://github.com/CocoaPods/Molinillo/pull/98 (which we need to move to this project instead).

As a workaround please use `pod 'PodName', '~> 1.0', :source => 'source_url_here'` to force a specific source for the pod that belongs to two repos.

I am going to close this as duplicate but feel free to comment here with additional thoughts

**Closed by dnkoutso** 2018-08-06 18:39 UTC

**Comment by deathByLiche** [comment] 2018-08-06 19:27
Oh nice I missed that in my search. Thanks!

**Comment by muhasturk** [comment] 2020-04-20 13:00
Just a quick note, you should use CDN spec source like below

```ruby
source 'git@myCustomSpecsRepo.git'
source 'https://cdn.cocoapods.org/'
```
