### ISSUE TITLE
UITests target missing '📦 Embed Pods Frameworks' build step

### ISSUE THREAD

**Issue by joridor** [CocoaPods/CocoaPods#5370] opened 2016-05-19 13:13 UTC
# Report
Cocoapods frameworks (eg Swift-pods) that are defined for the UITests target are missing at runtime.
And give an error that looks like:
`XCTRunner[53330:4433829] The bundle “FailingUITests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.`

## What did you do?
in the Podfile, define target for the UITests
```
target 'FailingUITests' do
	pod 'FooBarSwiftLibrary' 
end
```
Run UITests; will crash at startup.

**## Solution**

1. Goto project settings
2. Select UITests
3. Go to the 'Build Phases'-tab
4. Click +
5. Add script step '📦 Embed Pods Frameworks'
 with contents `"${SRCROOT}/Pods/Target Support Files/Pods-UITests/Pods-UITests-frameworks.sh"`
(replacing UITests with the UITest target name)

## Environment

   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.4
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 592641cd6ece0f6763c48149199d8e7069bd7485
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, :deployment_target => '8.0'

use_frameworks!

def all_pods
   pod 'ABC'
   pod 'DEF'
end

target 'application' do
    all_pods
end

target 'applicationTests' do
    all_pods
    pod 'OHHTTPStubs'
end

target 'UITests' do
	pod 'XCTest-AwesomeLibrary'
end

```

**Comment by orta** [comment] 2016-05-19 13:14
Closing as duplicate of https://github.com/CocoaPods/CocoaPods/issues/5250 - thanks @joridor

**Closed by orta** 2016-05-19 13:14 UTC

**Comment by joridor** [comment] 2016-05-19 13:16
Oops, did a quick search but couldn't find a simular issue. :)

**Comment by JANGCondorLabs** [comment] 2018-10-03 14:57
doesn't work
