### ISSUE TITLE
NameError - uninitialized constant Pod::TrunkSource

### ISSUE THREAD

**Issue by Jason-Stan-Lee** [CocoaPods/CocoaPods#9401] opened 2019-12-11 08:10 UTC
### Command

```
/usr/local/bin/pod trunk push JSLTransitionLib.podspec --allow-warnings
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.15.2 (19C32e)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2_1/lib
Repositories : aliyun - https://github.com/aliyun/aliyun-specs.git @ xxxxxxxxxxxxxxxxxxxxxxxxx
               master - https://github.com/CocoaPods/Specs.git @ xxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxxx

```

### Plugins

```
cocoapods-amimono     : 0.0.10
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NameError - uninitialized constant Pod::TrunkSource
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:147:in `update_master_repo'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-trunk-1.4.1/lib/pod/command/trunk/push.rb:69:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.4.0/gems/cocoapods-1.6.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by dnkoutso** [comment] 2019-12-11 18:15
Duplicate of https://github.com/CocoaPods/cocoapods-trunk/issues/142.

Workaround available at the duplicate.

**Closed by dnkoutso** 2019-12-11 18:15 UTC
