### ISSUE TITLE
Xcode7.0 won't archive to "iOS Apps". Goes to "Other Items" instead

### ISSUE THREAD

**Issue by archerLj** [CocoaPods/CocoaPods#4274] opened 2015-09-28 07:39 UTC
COCOAPODS: 0.39.0.beta.4 (recently updated from 0.38.0)
XCODE: Version 7.0 (7A220)

it works okay before i update my Xcode to 7.0. but after i update my Xcode, i add "pod 'MBProgressHUD', '~> 0.9'" and execute 'pod install'. and then Xcode cannot archive to "iOS Apps".
i saw the same issue at https://github.com/CocoaPods/CocoaPods/issues/4125
but their methods didn't work on my project.

when i reverted my cocoapods to 0.39.0.beta.3 or 0.38.0. it works worse, Xcode shows 'archive succeded', but there's nothing happend then. no archive window pop up.

Is there some methods can solve this issue?

**Comment by michaelochs** [comment] 2015-09-28 11:07
This looks like a duplicate of #4178. Basically you can fix this by removing the copy pod resources build phase from your watch extension. (or maybe other extensions)

**Comment by neonichu** [comment] 2015-09-28 11:31
The issue could also be #4119 — in any case, both are already tracked.

**Closed by neonichu** 2015-09-28 11:31 UTC

**Comment by archerLj** [comment] 2015-09-29 01:45
i removed copy pod resources and it's really worked. thx guys. ^_^
