### ISSUE TITLE
New versions of Cocoapods seem to take a while to propagate

### ISSUE THREAD

**Issue by michaeleisel** [CocoaPods/CocoaPods#11684] opened 2022-12-07 23:20 UTC
When I push a new version of one of my pods, ZippyJSONCFamily, with `pod trunk push ...`, and then try to depend on that new version in the .podspec of another pod, ZippyJSON, and then try to push that .podspec with `pod trunk push ...`, it tells me it can't find the new version of the dependency ZippyJSONCFamily, even after running `pod repo update`. It seems to take a non-negligible amount of time, I haven't measured but maybe 0.5-2 hours. It would be awesome if it could be made faster. Or am I just missing some command to update my caches?

**Comment by orta** [comment] 2022-12-08 16:26
The trunk via CDN is very aggressive in its server-side caching and unlikely to ever get faster, it's a free resource which we don't want to abuse. You can always get the most up-to-date version of a dependency by using the git based trunk (e.g. the default) but that obviously comes with its own tradeoffs.

**Comment by michaeleisel** [comment] 2022-12-08 18:37
Can I tell `pod trunk` to use the git based trunk? If so, how?

**Comment by orta** [comment] 2022-12-08 19:04
Don't include a CDN `source` in your podfile

**Comment by michaeleisel** [comment] 2022-12-08 19:15
I'm not sure I understand. `pod trunk` is given a path to a .podspec, not a Podfile

**Comment by michaeleisel** [comment] 2022-12-08 22:35
There's no Podfile for me to edit in this situation, because this is not a `pod install`, this is `pod trunk push MyPod.podspec`. When running that command, it does its own fetching of pods. Perhaps it generates a Podfile internally to do this, but if so, it doesn't seem clear how I could alter the contents of it when it's generated.

**Comment by paulb777** [comment] 2022-12-09 00:13
This is a duplicate of #9497 that was addressed by https://github.com/CocoaPods/cocoapods-trunk/pull/147

There is still a bit of latency when using the `--synchronized` option, but much less, and I've never had a retry fail.

**Closed** 2022-12-09 00:13 UTC
