### ISSUE TITLE
watchOS subspec 'does not support watchos'

### ISSUE THREAD

**Issue by mikaoj** [CocoaPods/CocoaPods#4208] opened 2015-09-18 07:55 UTC
Hi!

I'm trying to install a subspec for my watchkit extension and it fails. Saying that it doesn't support watchOS, although it does.
```shell
target 'blablabla watch Extension' do
  platform :watchos, '2.0'
  pod 'AFNetworking/NSURLSession', '2.6.0'
end
```

```shell
[!] The platform of the target `blablabla watch Extension` (watchOS 2.0) is not compatible with `AFNetworking/NSURLSession (2.6.0)`, which does not support `watchos`.
```
The NSURLSession subspec does support watchOS.
If I change my podfile to install the entire AFNetworking pod it works:
```shell
target 'blablabla watch Extension' do
  platform :watchos, '2.0'
  pod 'AFNetworking', '2.6.0'
end
```

cocoapods 0.38 and 0.39.0.beta.4

**Comment by neonichu** [comment] 2015-09-18 09:04
Looks like as if the JSON serialisation for podspecs dropped the `watchos` platform — in the specs repo, it is missing: <https://github.com/CocoaPods/Specs/blob/master/Specs/AFNetworking/2.6.0/AFNetworking.podspec.json#L64-L67>

**Comment by segiddins** [comment] 2015-09-18 11:56
Is the production deploy of trunk running the latest CocoaPods core version?

**Comment by neonichu** [comment] 2015-09-18 16:04
Not sure, but it seems like the serialisation for the top-level spec worked correctly: <https://github.com/CocoaPods/Specs/blob/master/Specs/AFNetworking/2.6.0/AFNetworking.podspec.json#L23>

**Comment by segiddins** [comment] 2015-09-25 01:29
Not a bug -- fixed in AFNetworking by https://github.com/AFNetworking/AFNetworking/commit/a44c8a4d0f75a54acfa3dc378c881166fc91cde8.

**Closed by segiddins** 2015-09-25 01:29 UTC
Labels: t2:defect

**Comment by neonichu** [comment] 2015-09-25 08:26
semver, why do we have it? :disappointed:

**Comment by mikaoj** [comment] 2015-09-25 08:37
```shell
ss.watchos.deployment_target = '2.0'
```
Was a part of the podspec when I created this issue, that commit is from aug 19.

**Comment by neonichu** [comment] 2015-09-25 08:40
@mikaoj they changed the podspec in the GH repo after submitting it to trunk, so those two diverge.
