### ISSUE TITLE
v1.0.0-rc.1: Swift pod that depends on ObjC pod fails to build

### ISSUE THREAD

**Issue by Adlai-Holler** [CocoaPods/CocoaPods#5230] opened 2016-04-30 22:55 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Create a Swift pod https://github.com/Tripstr/AsyncDisplayKitExtensions that extends (depends on) Objective-C pod https://github.com/facebook/AsyncDisplayKit . Run `pod install` on the demo project.

## What did you expected to happen?

The project builds.

## What happened instead?

Project fails to build because AsyncDisplayKit pod fails to build.
<img width="1512" alt="screen shot 2016-04-30 at 3 53 31 pm" src="https://cloud.githubusercontent.com/assets/2466893/14939016/e1cf0620-0eeb-11e6-832e-ec1550364590.png">

## Podfile

```ruby
platform :ios, '8.0'

use_frameworks!

target "SwiftKittens" do
	pod 'AsyncDisplayKit', '~> 1.9.7.2'
	pod 'AsyncDisplayKitExtensions', :path => '..'
end
```

**Comment by neonichu** [comment] 2016-05-01 16:42
Unfortunately, I wasn't able to reproduce the issue with the project you provided, it builds just fine for me after running `pod install` with the RC. Deleting Derived Data might help? I was using Xcode 7.3.1 to build.

**Comment by muhasturk** [comment] 2016-05-01 18:32
Maybe releated https://github.com/CocoaPods/CocoaPods/issues/4950

**Comment by neonichu** [comment] 2016-05-12 00:16
Closing this, since we couldn't reproduce it with the provided example.

**Closed by neonichu** 2016-05-12 00:16 UTC
Labels: s1:awaiting input
