### ISSUE TITLE
Error installing development pod with non-ascii paths

### ISSUE THREAD

**Issue by TAKeanice** [CocoaPods/CocoaPods#3930] opened 2015-07-29 11:04 UTC
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?
Installing an development pod (https://github.com/SocialbitGmbH/SwiftAddressBook) in its sample project which was just cloned from git, with `use_frameworks!`, and nothing else inside the Podfile. Cocoapod version was just updated through `sudo gem install cocoapods`, uninstalling and re-installing fully did not help either.

* What did you expect to happen?
`pod install` installs pod as usual

* What happened instead?
`pod install` crashed

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.5.0
Ruby lib dir : /usr/local/Cellar/ruby/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e230d92a344abee990e7d87881984e9dc1abe22e
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '8.0'
link_with "SwiftAddressBookExample", "SwiftAddressBookTests"
use_frameworks!
pod "SwiftAddressBook", :path => "../"
```

### Error

```
NoMethodError - undefined method `gsub' for nil:NilClass
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:58:in `block in read_file_system'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:58:in `map'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:58:in `read_file_system'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:31:in `files'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:117:in `relative_glob'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/path_list.rb:79:in `glob'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:314:in `expanded_paths'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:285:in `paths_for_attribute'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/sandbox/file_accessor.rb:81:in `source_files'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/target/pod_target.rb:111:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/target/pod_target.rb:111:in `flat_map'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/target/pod_target.rb:111:in `should_build?'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:377:in `block (3 levels) in verify_no_duplicate_framework_names'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:377:in `select'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:377:in `block (2 levels) in verify_no_duplicate_framework_names'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:373:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:373:in `block in verify_no_duplicate_framework_names'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:372:in `each'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:372:in `verify_no_duplicate_framework_names'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:107:in `install!'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/usr/local/lib/ruby/gems/2.2.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment] 2015-07-29 11:56
hm, unsure why this happens for you — I cannot reproduce it when cloning the project and doing a `pod install`. Could you try moving your Pods folder away, just to check if its current state is causing the issue.

**Comment by TAKeanice** [comment] 2015-07-29 12:47
I have cloned once again, then executed `pod install`, which failed, then deleted the Pods folder and did another `pod install` which failed again. What´s happening is always the same:

```
pod install
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `SwiftAddressBook` from `../`
Downloading dependencies
Installing SwiftAddressBook (0.4.3)
[the markdown template]
[!] Oh no, an error occurred.
[some more error help output]
```

What is the `gsub` method? Can it be my ruby installation? I have not changed it, but maybe something was broken somehow...

**Comment by TAKeanice** [comment] 2015-07-29 13:01
yup... Worked with
```
ruby --version
ruby 2.1.6p336 (2015-04-13 revision 50298) [x86_64-darwin14.0]
```
like this:
```
Updating local specs repositories
Analyzing dependencies
Fetching podspec for `SwiftAddressBook` from `../`
Downloading dependencies
Installing SwiftAddressBook (0.4.3)
Generating Pods project
Integrating client project
Sending stats
```

**Comment by neonichu** [comment] 2015-07-29 13:13
:sob: — thanks for this discovery

**Comment by TAKeanice** [comment] 2015-07-29 13:29
You seem not to like the fact that the new ruby version breaks your code... Sorry :/

**Comment by neonichu** [comment] 2015-07-29 13:32
It's not your fault :) — even more weird is that I have a build of Ruby 2.2 which doesn't exhibit this, but will dig a bit deeper.

**Comment by TAKeanice** [comment] 2015-07-29 14:06
It´s the current ruby version installed from Homebrew, if that helps

**Comment by neonichu** [comment] 2015-07-29 15:31
Unfortunately, I can't reproduce this, even when building ruby with Homebrew — which gives me the same exact version you have.

**Comment by TAKeanice** [comment] 2015-07-29 21:32
Ok, after installing and uninstalling ruby and cocoapods several times and retrying pod install each time, I´m running into other similar-but-not-same errors. Something about my installation of cocoapods or ruby must be terribly corrupted - maybe even the homebrew installation itself. I have to say that I have two user accounts on my mac, which both exhibit strange behavior. Most probably it is about file access permissions... I will investigate the issues further and will comment here as soon as I have found a solution.

**Comment by neonichu** [comment] 2015-08-09 18:01
Will close this as we cannot reproduce it on our end so far.

**Comment by TAKeanice** [comment] 2015-08-09 19:51
Fine. I did not have enough time to fix my installation so far. If I can reproduce the problem, I will provide a more detailed description upon reopening.

**Comment by neonichu** [comment] 2015-08-09 20:46
Sure, if you can provide more info, we can reopen this.

**Comment by TAKeanice** [comment] 2015-08-24 17:36
I can´t help myself but comment here again. I will not reopen, but I am desperately searching for help related to the very same bug I reported above. It cannot be resolved, by uninstalling (and cleaning) the complete Cocoapods installation, as well as the complete Ruby installation. If there is any place I can start looking for the root of this issue, please let me know! I am completely unexperienced with Ruby, but search suggests that some instance that is created during runtime is no string, thus the `gsub` method cannot be called on it. How can I narrow it down and debug a little more intelligent, so that I find out where that instance comes from?
Another hint would be the podfile once again:

```
platform :ios, '8.0'
link_with "SwiftAddressBookExample", "SwiftAddressBookTests"
use_frameworks!
pod "SwiftAddressBook", :path => "../"
```

It fails only when installing the local pod. Replacing 

`pod "SwiftAddressBook", :path => "../"`
with
`pod "SwiftAddressBook"`

makes it work.

**Comment by TAKeanice** [comment] 2015-08-24 17:37
... because it was an earlier version of the repository (0.4.4, now it´s 0.4.5). I will investigate the changes happened since that

**Comment by neonichu** [comment] 2015-08-24 18:05
Does this also occur for you using the system ruby?

**Comment by TAKeanice** [comment] 2015-08-24 18:10
After some trial and error with different parameters that can influence the result, I discovered that the path of the pod matters. The one I always get the error in is `/Users/tassilokarge/Documents/persönliche Dokumente/kreatives, Ideen & Pläne/Computer`. (please don´t judge me for the ampersand and the spaces and the `ä` in the filename, this directory originates from quite some time ago). I have tried to reproduce that issue in another directory, and it seems not possible to get the same result (i have created a directory `/Users/tassilokarge/filename,with,comma&,ä and spaces/`, moved the folder into it, and it worked, then moved it back, it stopped working). There is no difference in access rights. I am completely clueless...

**Comment by neonichu** [comment] 2015-08-24 18:11
Ah, this sounds interesting — maybe there's some kind of issue with non-ASCII characters, I'll poke around a bit.

**Comment by TAKeanice** [comment] 2015-08-24 18:12
As I said, there is no non-ascii char that made it fail in the other folder. But I will also investigate further...

**Comment by TAKeanice** [comment] 2015-08-25 03:41
I have another few hints:
- Working: `/Users/tassilokarge/kreatives, Ideen & Pläne/Computer/`
- Working: `/Users/tassilokarge/Documents/persönliche Dokumente/Kreatives_ideen_plaene/Computer/`
- Not working: `/Users/tassilokarge/Documents/persönliche Dokumente/kreatives, Ideen & Pläne/Computer/`
- Not working: `/Users/tassilokarge/Documents/persönliche Dokumente/kreatives, Ideen &Pläne/Computer/`
- Not working: `/Users/tassilokarge/Documents/persönliche Dokumente/kreatives, Ideen, Pläne/Computer/`
- Not working: `/Users/tassilokarge/Documents/persönliche Dokumente/kreatives,Ideen,Pläne/Computer/`
- Working: `/Users/tassilokarge/Documents/persönliche Dokumente/kreatives,Ideen,Pläne/`
- Working: `/Users/tassilokarge/Documents/persönliche Dokumente/kreatives,Ideen,Plaene/Computer/`

Seems to be tricky - non-ascii plus order of the characters or something like that. Like those iOS Crash bugs where some arabic letters and numbers lead to an irreversible crash :smiley:

**Comment by neonichu** [comment] 2016-05-02 08:47
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Closed by neonichu** 2016-05-02 08:47 UTC
