### ISSUE TITLE
Error in 1.0.0.beat.6: No such file or directory

### ISSUE THREAD

**Issue by parleer** [CocoaPods/CocoaPods#5054] opened 2016-03-18 05:00 UTC
# Report

Cocoapods 0.39.0 works fine, but Cocoapods 1.0.0.beat.6 results in the following compilation error:

> error: /Users/me/Library/Developer/Xcode/DerivedData/MyApp-eavcqvuyfoaigcdewzjocnqnvmqn/Build/Products/Debug-iphonesimulator/TOWebViewController/TOWebViewControllerLocalizable.bundle: No such file or directory

## Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!
target 'MyApp' do
    pod 'Alamofire', '~> 3.0'
    pod 'TOWebViewController', '~> 2.0.5'
end
```

**Comment by JayZhao** [comment] 2016-03-18 17:40
This bug is happening again...

**Comment by mrackwitz** [comment] 2016-03-20 09:39
That's a duplicate of #5034.

**Closed by mrackwitz** 2016-03-20 09:39 UTC

**Comment by ryderjack** [comment] 2016-12-20 19:54
resolved?

**Comment by benasher44** [comment] 2016-12-20 21:47
Hi @ryderjack! Thanks for reporting this! Unfortunately, there's not enough information here for us to help you. If you could file a new ticket and fully fill out the issue template, we'd be happy to help. Have a great day!
