### ISSUE TITLE
Doesn't work at all!!!

### ISSUE THREAD

**Issue by gerchicov-bp** [CocoaPods/CocoaPods#4037] opened 2015-08-19 09:34 UTC
Whatever I do I get the following error:
```Unable to satisfy the following requirements:```

Examples (even if I don't specify a concrete version and a link to their repositories):
```pod 'PromiseKit'```
```pod 'BrightFutures'```

**Comment by amorde** [comment] 2015-08-19 10:43
Hello,

Could you provide some details as to what exactly isn't working? Such as an error message. "Doesn't work at all" isn't much to go off of.

I have successfully created a project from scratch with the following in the `Podfile`:

```
use_frameworks!

pod 'PromiseKit'
pod 'BrightFutures'
```

and it works just fine.

**Comment by gerchicov-bp** [comment] 2015-08-19 10:52
I have found out that the problem is my project is not the app it is an ```xcode plugin``` (a template from ```Alcatraz```). But I can't find any workable method how to import ```PromiseKit``` even when it supports ```Cocoapods```, ```Carthage``` and simply importing of the comiled framework - nothing works(

**Comment by neonichu** [comment] 2015-08-19 17:33
Are you saying you're trying to build an Xcode plugin with dependencies? That won't actually work anyway, because Alcatraz doesn't support workspaces.

**Comment by gerchicov-bp** [comment] 2015-08-20 07:37
Yes, I try to use the framework for plugin project.
No, it is not connected with Alcatraz (Alcatraz is just one from ways to download xcode plugin template)

**Comment by neonichu** [comment] 2015-08-25 09:27
I didn't mean that it was, just that using CocoaPods for a plugin to be distributed via Alcatraz won't work in the end.

Anyway, this is probably a dupe of #3926, so you should check your deployment targets.

**Closed by neonichu** 2015-08-25 09:27 UTC
Labels: s1:awaiting input

**Comment by gerchicov-bp** [comment] 2015-08-25 09:36
1)Perfect. You link to the another issue which is different and both of them now closed. Did you solve it to make it closed?
2)Again Alcatraz is just a way to download the plugin project. So in your language if your cocoapods code has bugs after it was downloaded via git client then it is a problem of git client only, isn't it? If you still answer "yes" then why do the same errors occur with other git clients too?

**Comment by orta** [comment] 2015-08-25 11:18
1, yes we did, but it's only in master and hasn't been released. Note the "closed by PR https://github.com/CocoaPods/CocoaPods/issues/3953" 
2, He's saying that the alcatraz tool doesn't support generating plugins via workspaces, only via xcodeprojects. It will work fine if you clone and open the workspace obviously.
