### ISSUE TITLE
resource_bundle with updated files is not copied during incremental compilation

### ISSUE THREAD

**Issue by voidless** [CocoaPods/CocoaPods#8881] opened 2019-06-06 12:56 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

resource_bundle with updated files is not copied during "[CP] Copy Pods Resources" step during incremental compilation

## What did you do?

- set up a project with local podspec with configured resource_bundle
- run project to see contents of a file in the bundle
- change the file in the bundle
- run project to see contents of a file in the bundle again

## What did you expect to happen?

app should display new contents of the file

## What happened instead?

app displays old contents of the file, from the first compilation

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.5 (18F203)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7d537a8698ce43f9f408e7270bf8467b2ec7deef
```

### Installation Source

```
Executable Path: /Users/user/develop/resourcebundlebug/vendor/bundle/ruby/2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, :deployment_target => '10.0'
use_frameworks!

target 'resourcebundlebug' do

  pod 'Resourcepod', path: 'Resourcepod', :inhibit_warnings => false

end
```

It also reproduces with cocoapods 1.6.1

## Project that demonstrates the issue

https://github.com/voidless/cocoapods-resource-bundle-bug

**Comment by dnkoutso** [comment] 2019-06-06 14:38
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/8122.

Bug that has been reported to Apple and in Xcode with new build system. Apple provided a new build setting in Xcode 11 which still does not work.

To fix your issue now disable input/output paths in your `Podfile`.

**Closed by dnkoutso** 2019-06-06 14:38 UTC
