### ISSUE TITLE
NoMethodError - undefined method `version' for nil:NilClass

### ISSUE THREAD

**Issue by mystikxkemix** [CocoaPods/CocoaPods#5996] opened 2016-10-04 08:09 UTC
### Command

```
/usr/local/bin/pod list
```

### Report

* What did you do?
pod list

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1_1/lib
Repositories : CocoaPods - https://github.com/CocoaPods/CocoaPods.git @ b6143c3e2095d689531112764492545f842c0cce
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'Versus' do

pod 'Alamofire', '~> 4.0'

end

target 'VersusTests' do

end

target 'VersusUITests' do

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

### Error

```
NoMethodError - undefined method `version' for nil:NilClass
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:209:in `pod'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/list.rb:24:in `block in run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/list.rb:24:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/list.rb:24:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by orta** [comment] 2016-10-11 06:23
Thanks for the issue, looks like a dupe of https://github.com/CocoaPods/CocoaPods/issues/5449

**Closed by orta** 2016-10-11 06:23 UTC
