### ISSUE TITLE
NoMethodError - undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by Sebastien2422** [CocoaPods/CocoaPods#5525] opened 2016-06-15 18:11 UTC
- [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report
## What did you do?

 Run `pod install`
## What did you expect to happen?

for all pods to be installed

pod 'AWSAutoScaling'
pod 'AWSCloudWatch'
pod 'AWSCognito'
pod 'AWSCognitoIdentityProvider'
pod 'AWSDynamoDB'
pod 'AWSEC2'
pod 'AWSElasticLoadBalancing'
pod 'AWSIoT'
pod 'AWSKinesis'
pod 'AWSLambda'
pod 'AWSMachineLearning'
pod 'AWSMobileAnalytics'
pod 'AWSS3'
pod 'AWSSES'
pod 'AWSSimpleDB'
pod 'AWSSNS'
pod 'AWSSQS'

Install all pod dependencies correctly.
### Error

```
NoMethodError - undefined method `path' for nil:NilClass
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object/native_target.rb:462:in `block in add_file_references'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object/native_target.rb:461:in `map'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/xcodeproj-1.1.0/lib/xcodeproj/project/object/native_target.rb:461:in `add_file_references'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:91:in `block (2 levels) in add_files_to_build_phases'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:87:in `each'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:87:in `block in add_files_to_build_phases'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:76:in `each'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:76:in `add_files_to_build_phases'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:21:in `block in install!'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:621:in `block (2 levels) in install_libraries'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:619:in `each'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:619:in `block in install_libraries'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:618:in `install_libraries'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:170:in `block in generate_pods_project'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/Cellar/cocoapods/1.0.1/libexec/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/Cellar/cocoapods/1.0.1/libexec/bin/pod:23:in `load'
/usr/local/Cellar/cocoapods/1.0.1/libexec/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment] 2016-06-16 00:25
Looks like a duplicate of #5427

**Comment by Sebastien2422** [comment] 2016-06-16 00:47
Their solution did not work for me.

**Closed** 2016-11-09 00:19 UTC
