### ISSUE TITLE
I can't push new version when I changed my GitHub username.

### ISSUE THREAD

**Issue by iTofu** [CocoaPods/CocoaPods#5109] opened 2016-04-01 11:22 UTC
like this:

````
[!] You are not allowed to push new versions for this pod.
````

**Comment by LeoGod** [comment] 2016-04-01 11:26
git since:
https://github.com/LeoiOS/LCNavigationController.git
to:
https://github.com/LeoGod/LCNavigationController.git

**Comment by segiddins** [comment] 2016-04-01 16:51
Is it possible this is a duplicate of https://github.com/CocoaPods/trunk.cocoapods.org/issues/172?

**Comment by iTofu** [comment] 2016-04-05 02:46
Thank you! let me see.

**Comment by iTofu** [comment] 2016-04-05 02:53
Nono, it doesn't work...

Please see this:

````ruby
bogon:~ Leo$ cd /Users/Leo/Documents/github/LCActionSheet 
bogon:LCActionSheet Leo$ pod lib lint

 -> LCActionSheet (1.2.1)

LCActionSheet passed validation.
bogon:LCActionSheet Leo$ git add -A
bogon:LCActionSheet Leo$ git commmit -m 'Release 1.2.2.'
git: 'commmit' is not a git command. See 'git --help'.

Did you mean this?
	commit
bogon:LCActionSheet Leo$ git commit -m 'Release 1.2.2.'
[master a4ab4ed] Release 1.2.2.
 3 files changed, 19 insertions(+), 15 deletions(-)
bogon:LCActionSheet Leo$ git tag 1.2.2
bogon:LCActionSheet Leo$ git push --tags
remote: Invalid username or password.
fatal: Authentication failed for 'https://github.com/LeoGod/LCActionSheet.git/'
bogon:LCActionSheet Leo$ git push --tags
Username for 'https://github.com': iTofu
Password for 'https://iTofu@github.com': 
Counting objects: 5, done.
Delta compression using up to 4 threads.
Compressing objects: 100% (5/5), done.
Writing objects: 100% (5/5), 594 bytes | 0 bytes/s, done.
Total 5 (delta 4), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/iTofu/LCActionSheet.git
To https://github.com/LeoGod/LCActionSheet.git
 * [new tag]         1.2.2 -> 1.2.2
bogon:LCActionSheet Leo$ git push origin master
Total 0 (delta 0), reused 0 (delta 0)
remote: This repository moved. Please use the new location:
remote:   https://github.com/iTofu/LCActionSheet.git
To https://github.com/LeoGod/LCActionSheet.git
   cdfce6f..a4ab4ed  master -> master
bogon:LCActionSheet Leo$ pod trunk register devtip@163.com 'Leo'
[!] Please verify the session by clicking the link in the verification email that has been sent to devtip@163.com
bogon:LCActionSheet Leo$ pod spec lint

 -> LCActionSheet (1.2.2)

Analyzed 1 podspec.

LCActionSheet.podspec passed validation.

bogon:LCActionSheet Leo$ pod trunk push LCActionSheet.podspec
Updating spec repo `master`

CocoaPods 1.0.0.beta.6 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Validating podspec
 -> LCActionSheet (1.2.2)

[!] You are not allowed to push new versions for this pod.
bogon:LCActionSheet Leo$ 
````

**Comment by iTofu** [comment] 2016-04-05 02:53
:(

**Comment by segiddins** [comment] 2016-04-05 02:57
And can you verify that you own the pod in question on trunk? Is it listed when you run `pod trunk me`?

**Comment by iTofu** [comment] 2016-04-05 03:02
Thank you very much! I see, because I changed my email address... I became another user...
How should I change my email address?

**Comment by segiddins** [comment] 2016-04-05 03:05
You can run `pod trunk login` to login as the old email and add the new email to the pod

**Closed by segiddins** 2016-04-05 03:05 UTC
Labels: s1:awaiting input

**Comment by iTofu** [comment] 2016-04-05 03:09
Many thanks, last question :)

````ruby
bogon:LCActionSheet Leo$ pod trunk login leoios@sina.com
[!] Unknown command: `login`
Did you mean: info
````

**Comment by iTofu** [comment] 2016-04-05 03:17
@segiddins :)

**Comment by segiddins** [comment] 2016-04-05 03:27
Sorry, its `pod trunk register`

**Comment by iTofu** [comment] 2016-04-05 03:34
It's nothing. I could finish it now.
Just login and than run `pod trunk add-owner [Pod Name] [Another account email]`, like `pod trunk add-owner LCActionSheet devtip@163.com`.
But there are many Pod repositories, a bit slow...
