### ISSUE TITLE
xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist. With Xcode8/Swift3.0/CocoaPods 1.1.0.beta.2

### ISSUE THREAD

**Issue by magic3584** [CocoaPods/CocoaPods#5900] opened 2016-09-19 09:31 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

 `pod trunk push`

## What did you expect to happen?

push my codes

## What happened instead?

``` ruby
- ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
- NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.
```
### Stack

```
   CocoaPods : 1.1.0.beta.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.9.0
Ruby lib dir : /Users/wang/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 631188212213dd5668d469d91cdba409b9c26dcb
```

### Installation Source

```
Executable Path: /Users/wang/.rvm/rubies/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## I have tried
* `Use Legacy Swift Language Version`  build setting to  `No`
*  `echo "3.0" > .swift-version` before `pod trunk push`

## Other
Yesterday it was fine with Xcode 7.3.1/Swift 2.3.

**Comment by lfarah** [comment] 2016-09-19 09:40
Duplicate of #5843

**Comment by neonichu** [comment] 2016-09-19 19:12
This has been fixed by the latest release candidates, I believe.

**Closed by neonichu** 2016-09-19 19:12 UTC

**Comment by magic3584** [comment] 2016-09-20 01:33
It did't work on me.

1. `git clone my repository`
2. change **s.version="2.0.3"**
3. `git tag` and `git push`
4. `set the new version to 2.0.3` and `set the new tag to 2.0.3`
5. `pod trunk push` it shows
 ``` ruby
 - ERROR | [iOS] unknown: Encountered an unknown error (Must be in the root of the repo  (/Users/wang/.cocoapods/repos/master), instead in  /Users/wang/Documents/wang/LWChannelManager.) during validation.
 ```

6. `pod trunk me`
7. `pod trunk push`
``` ruby
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.
```

Pod version is **1.1.0.beta.2**
Is there something wrong? Thanks!
@lfarah @neonichu

**Comment by AngryBaby** [comment] 2016-09-20 10:33
@neonichu i update cocoapods to v1.1.0.beta.2, but It did't work on me.
`
yuhamdeMacBook-Pro:FHOpenShare yuham$ pod --version
1.1.0.beta.2
yuhamdeMacBook-Pro:FHOpenShare yuham$ pod lib lint

 -> FHOpenShare (0.1.6)
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

[!] FHOpenShare did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.`

**Comment by neonichu** [comment] 2016-09-20 11:14
You need to use 1.1.0.rc.2 for this to work, possibly you're running into the same issue as #5910

**Comment by magic3584** [comment] 2016-09-21 01:34
Yeah, I made it! Thanks!

**Comment by AngryBaby** [comment] 2016-09-21 07:56
@neonichu thanks it work it

**Comment by cepages** [comment] 2016-09-28 18:12
I fixed the same error message updating a private pod, with XCode 8 working :)

Thanks @neonichu
