### ISSUE TITLE
[Pod Install] ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES & SWIFT_VERSION

### ISSUE THREAD

**Issue by gorbat-o** [CocoaPods/CocoaPods#6008] opened 2016-10-07 10:34 UTC
Hey,

## What did you do?
Run `pod install` or `pod update`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
i've warning which i cant suppress :/ i've tried a lot of things found on issues or on stackoverflow but don't work ..
<img width="1871" alt="capture d ecran 2016-10-07 a 12 32 03" src="https://cloud.githubusercontent.com/assets/7542553/19187146/1f77e624-8c8a-11e6-89d1-d627e22298c9.png">

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4a0336df28b9fe5b1536a44adc3677ad0b7f247a
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# coding: utf-8
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

target 'Movie Finder' do
    pod 'RxSwift', '~> 3.0.0-beta.1'
    pod 'RxCocoa', '~> 3.0.0-beta.1'
    pod 'RxViewModel', :git => 'https://github.com/gregpardo/RxViewModel.git', :branch => 'swift3'
    pod 'Alamofire'
    pod 'SwiftyJSON'
    pod 'KiiCloud'
    pod 'SpeedLog', :git => 'https://github.com/coutar-t/SpeedLog', :branch => 'swift3'
    pod 'Eureka', '~> 2.0.0-beta.1'
    pod 'MantleModal', :git => 'https://github.com/canalesb93/MantleModal.git', :commit => 'f6ea15a1e4b9ca1ae4ce48c7ceba5cec54dc5b29'
    pod 'TextFieldEffects'
    pod 'RAMAnimatedTabBarController'
    #pod 'VBPiledView'
    pod 'Pager'
    #pod 'Hakuba'
    pod 'DisplaySwitcher'
    pod 'ImageLoader'
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            #config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            #config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            #config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
            #config.build_settings['GCC_OPTIMIZATION_LEVEL'] = '3'
            config.build_settings['SWIFT_VERSION'] = '3.0'
        end
    end
end
```

## Project that demonstrates the issue
it's only an issue with CocoaPods the tool.

Thanks for help

**Comment by benasher44** [comment] 2016-10-07 12:23
This is a duplicate of #5981. Closing. Thanks for filing!

**Closed by benasher44** 2016-10-07 12:23 UTC

**Comment by gorbat-o** [comment] 2016-10-07 15:21
i don't understand what i need to do more with this thread. not working for me the "deleting settings"

**Comment by benasher44** [comment] 2016-10-07 15:24
Yep this is a know issue that is going to be fixed soon.

**Comment by gorbat-o** [comment] 2016-10-07 15:26
Oh ok, sorry
I did not understand that
See ya thanks

**Comment by benasher44** [comment] 2016-10-07 15:28
No prob! Here's the PR if it's not already linked somewhere: #5933
