### ISSUE TITLE
Errno::EEXIST - File exists with XCode 8 migrating to Swift 2.3

### ISSUE THREAD

**Issue by dimitryvin** [CocoaPods/CocoaPods#5834] opened 2016-09-09 16:35 UTC
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

Run pod install

* What did you expect to happen?

For it to setup the project like before

* What happened instead?

Failed with Errno::EEXIST - File exists - /Users/dimitryvin/Developer/Repos/stem-ios/Stem/Pods/Target Support Files/AFNetworking

### Stack

```
   CocoaPods : 1.1.0.beta.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12 (16A313a)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 227e9778abe84e9a549ff67e86fd1baeea05f065
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

def shared

pod 'ContactsPicker', :git => 'https://github.com/stems/EPContactsPicker.git'
use_frameworks!
pod 'Fabric'
pod 'Crashlytics'
pod 'Alamofire'
pod 'Parse'
pod 'MaterialControls', :git => 'https://github.com/stems/Material-Controls-For-iOS.git'
pod 'FXPageControl'
pod 'Material', '1.37.3'
pod 'Charts'
pod 'libPhoneNumber-iOS', '~> 0.8'
pod 'Intercom'
pod 'FPPicker'
pod 'EasyTipView', :git => 'https://github.com/eyegroove/EasyTipView.git'
pod 'Google/Analytics'
pod 'Cartography'
end

target 'stem' do
    shared
end

target 'stem-staging' do
    shared
end

target 'stem-sandbox' do
    shared
end
```

### Error

```
Errno::EEXIST - File exists - /Users/dimitryvin/Developer/Repos/stem-ios/Stem/Pods/Target Support Files/AFNetworking
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/installer.rb:115:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by DanToml** [comment] 2016-09-09 18:13
This is caused by the dir.chdir issue, a fix has been merged in Xcodeproj and will be released in RC 1. Please check #5825 for updates.

**Closed by DanToml** 2016-09-09 18:13 UTC

**Comment by dimitryvin** [comment] 2016-09-10 22:40
I'm still getting this issue with ```1.1.0.rc.1```

**Comment by vysotsky** [comment] 2016-09-12 10:49
The same issue for me when using  1.1.0.rc.1
Is there a solution available?

**Comment by Antondomashnev** [comment] 2016-09-13 08:13
Same for me

**Comment by benasher44** [comment] 2016-09-13 14:43
Hm. Could someone post a sample project? Hard to say what this could be without one.

**Comment by Coeur** [comment] 2016-09-14 01:22
same issue when using 1.1.0.rc.2

**Comment by Coeur** [comment] 2016-09-14 01:40
My bad, I figured out my issue while trying to create a sample: with multiple targets, we must make sure that all of them are using the same Swift version.

Maybe Cocoapods 1.1 could detect and raise a specific warning when one target is using Swift 2.3 and another is using Swift 3.0.

**Comment by benasher44** [comment] 2016-09-14 14:47
Going to continue discussion of the related issue in #5864
