### ISSUE TITLE
pod update fail

### ISSUE THREAD

**Issue by hatjs880328** [CocoaPods/CocoaPods#9246] opened 2019-10-11 12:46 UTC
```
   CocoaPods : 1.8.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.1 (11A1027)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : 
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
Errno::ENOENT - No such file or directory @ rb_sysopen - /Users/wenzhengshan/.cocoapods/repos/Spec_Lock
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.3/lib/cocoapods/sources_manager.rb:118:in `update'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.3/lib/cocoapods/command/repo/update.rb:23:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.8.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

**Comment by hatjs880328** [comment] 2019-10-11 12:46
pod repo update fail

**Comment by hatjs880328** [comment] 2019-10-11 12:49
can't understand why so much issue ,, the repo ? ????

**Comment by dnkoutso** [comment] 2019-10-11 13:15
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9216 fixed.

**Closed by dnkoutso** 2019-10-11 13:15 UTC
