### ISSUE TITLE
Podspec does not validate - include of non-modular header inside framework module

### ISSUE THREAD

**Issue by bradhilton** [CocoaPods/CocoaPods#4517] opened 2015-11-07 23:01 UTC
I have been unable to push a new version of my pod [Convertible](https://github.com/bradhilton/Convertible). I have been getting the following validation error:
```
- ERROR | xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
- NOTE  | xcodebuild:  <module-includes>:1:9: note: in file included from <module-includes>:1:
- NOTE  | xcodebuild:  Target Support Files/Convertible/Convertible-umbrella.h:3:9: note: in file included from Target Support Files/Convertible/Convertible-umbrella.h:3:
- ERROR | xcodebuild:  Convertible/Convertible/Convertible.h:10:9: error: include of non-modular header inside framework module 'Convertible.Convertible'
- NOTE  | xcodebuild:  <unknown>:0: error: could not build Objective-C module 'Convertible'
```
My header file has another Swift CocoaPod dependency and looked like so:
```
#import <Foundation/Foundation.h>
#import <SwiftKVC/SwiftKVC.h>
```
I also tried it as the following with no luck:
```
#import <Foundation/Foundation.h>
@import SwiftKVC;
```
Here's my podspec:
```ruby
Pod::Spec.new do |s|
  s.name         = "Convertible"
  s.version      = "0.9.1"
  s.summary      = "Swift Framework For Conversions Between JSON, Data And More"
  s.description  = <<-DESC
                    Converting your basic types and models to-and-from JSON, binary data, etc. is a common task in application development.
                    Convertible defines a collection of Swift protocols and implementations that makes the conversion process easy, so you don't have to write boilerplate code.
                   DESC
  s.homepage     = "https://github.com/bradhilton/Convertible"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author       = { "Brad Hilton" => "brad@skyvive.com" }
  s.source       = { :git => "https://github.com/bradhilton/Convertible.git", :tag => "0.9.1" }

  s.ios.deployment_target = "8.0"
  s.osx.deployment_target = "10.9"

  s.source_files  = "Convertible", "Convertible/**/*.{swift,h,m}"
  s.ios.exclude_files = "Convertible/**/NSImage+Convertible.swift"
  s.osx.exclude_files = "Convertible/**/UIImage+Convertible.swift"
  s.requires_arc = true
  s.dependency 'SwiftKVC', '~> 1.0.0'
end
```
Any idea what's going on? I only recently starting having this issue and I think it coincides with the release of Xcode 7.1. Thanks in advance.

**Comment by segiddins** [comment] 2015-11-08 00:16
This might be fixed by my PR that stops copying the build headers for frameworks.

**Comment by neonichu** [comment] 2015-11-08 18:47
Duplicate of #4420

**Closed by neonichu** 2015-11-08 18:47 UTC
