### ISSUE TITLE
Couldn't install Pods

### ISSUE THREAD

**Issue by rmnbozhchenko** [CocoaPods/CocoaPods#6648] opened 2017-04-13 11:07 UTC
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.6.11
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.1 (8E1000a)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 89600fb90a0a9cd98f8d8330b542d3dfc23cb7de
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, "9.0"
use_frameworks!

target "Patient Access" do
pod 'Overcoat', '~>4.0.0-beta.1'
pod 'KVOController', '~>1.2.0'
pod 'Fabric'
pod 'Crashlytics', '~>3.8.4'
pod 'KeychainAccess', '~>3.0.1'
end
```

### Error

```
Nanaimo::Reader::ParseError - [!] Dictionary missing ';' after key-value pair for "objects", found ""
   #  -------------------------------------------
   #  	rootObject = F81C8B511E9BC1FE00E77C63 /* Project object */;
   #  }
722>  
      ^
   #  -------------------------------------------

/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:284:in `raise_parser_error'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:198:in `parse_dictionary'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:131:in `parse_object'
/Library/Ruby/Gems/2.0.0/gems/nanaimo-0.2.3/lib/nanaimo/reader.rb:106:in `parse!'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/plist.rb:27:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.4/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:874:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:873:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:873:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:868:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5B%21%5D+Dictionary+missing+%27%3B%27+after+key-value+pair+for+%22objects%22%2C+found+%22%22%0A+++%23++-------------------------------------------%0A+++%23++%09rootObject+%3D+F81C8B511E9BC1FE00E77C63+%2F%2A+Project+object+%2A%2F%3B%0A+++%23++%7D%0A722%3E++%0A++++++%5E%0A+++%23++-------------------------------------------%0A&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - Ore Dictionary entries
   https://github.com/EnderKing123/Extra-Ores/pull/1 [open] [0 comments]
   2 weeks ago

 - units missing from Unit Dictionary
   https://github.com/NCEAS/z-test-issues/issues/357 [open] [4 comments]
   4 weeks ago

 - Basic dictionaries
   https://github.com/Shen-Language/shen-sources/issues/20 [open] [8 comments]
   3 weeks ago

and 23237 more at:
https://github.com/cocoapods/cocoapods/search?q=[!]%20Dictionary%20missing%20';'%20after%20key-value%20pair%20for%20%22objects%22,%20found%20%22%22%0A%20%20%20%23%20%20-------------------------------------------%0A%20%20%20%23%20%20%09rootObject%20=%20F81C8B511E9BC1FE00E77C63%20/*%20Project%20object%20*/;%0A%20%20%20%23%20%20%7D%0A722%3E%20%20%0A%20%20%20%20%20%20%5E%0A%20%20%20%23%20%20-------------------------------------------%0A&type=Issues&utf8=✓

**Comment by benasher44** [comment] 2017-04-26 17:27
Hi there! Thanks for the report! This does sound like a bug, but it's unfortunately one that is near impossible to debug without a sample project. Could you please provide one? Thanks so much!

**Comment by cm-notify** [comment] 2017-05-04 02:33
@benasher44 This is due to an incorrect project file could be a result of merging. 

I'm correctly experiencing the same issue.

**Comment by fengxing1** [comment] 2017-05-09 15:36
I get the same issue, diffent mac get code ,a result of merging

**Comment by cm-notify** [comment] 2017-05-10 02:05
@benasher44 @fengxing1 

Couldn't find this page after I have made a comment.

My solution is using a ruby library "Kin":
https://github.com/Karumi/Kin

Which does xcode project checking, it will indicate which line in the xcode project file contain invalid characters etc. With this tool I managed to investigate and diagnose the issue, finding out the exact line.

**Comment by benasher44** [comment] 2017-05-17 15:57
@cm-notify thanks for posting that helpful tool! I'm going to close this out, since we don't have any way of reproducing it for this issue, but I encourage others to try out that tool if they encounter this issue.

**Closed by benasher44** 2017-05-17 15:57 UTC
Labels: s1:awaiting input

**Comment by narutojone1218** [comment] 2019-02-15 00:58
I'm currectly experiencing the same issue.

**Comment by MarcSteven** [comment] 2019-05-08 07:21
Yeah I met this issue again ,can you find the solution to solve it completely???
