### ISSUE TITLE
public_header_files not work when use :path.

### ISSUE THREAD

**Issue by dev-gao** [CocoaPods/CocoaPods#6530] opened 2017-03-02 12:50 UTC
In pod A's podspec file: I wrote 
`s.public_header_files = "PodName/Module/ModuleProtocol/**/*.h"`
When I depend this pod in main project with :git, it work well. ：
`pod 'PodName', :git => 'https://git.xx.x.x.x.com/xxxxx/Podname.git'`
But when I depend this pod in main project with :path, it went wrong:
`pod 'PodName', :path => '/Users/GaoYu/Podlibs_Root/Podname'`

The main project's 'Build Phases -> Headers' went wrong: In the Headers all headers became 'project' other than public or private. But when use :git it works well.

**Comment by benasher44** [comment] 2017-03-11 17:06
Hi @dev-gao! Thanks for the report! This appears to be a duplicate of #5790, so I'm going to close this one. If you have more to add, please add any further details to that issue. Thanks again, and have a great day!

**Closed by benasher44** 2017-03-11 17:06 UTC
