### ISSUE TITLE
Framework target with pods copies Swift runtime dylibs

### ISSUE THREAD

**Issue by a2** [CocoaPods/CocoaPods#3311] opened 2015-03-23 23:47 UTC
According to [@jckarter on Twitter](https://twitter.com/jckarter/status/580153393747918848), a framework must share its Swift runtime with its host app. Therefore, it doesn't make much sense for CocoaPods to be copying Swift dylibs into the framework because its enclosing application will already have them.

**Comment by segiddins** [comment] 2015-03-24 02:36
It's only ever should be copied to the enclosing app

**Comment by a2** [comment] 2015-03-24 11:15
The framework copying shell script copies the dylibs. I'm not at my computer now but I can get more helpful information for you in 30 minutes.

**Comment by segiddins** [comment] 2015-03-24 13:54
Yes, it copies the dylibs, but it should only leave one copy of them per application. 

-Samuel E. Giddins

On Mar 24, 2015, at 4:15 AM, Alexsander Akers <notifications@github.com> wrote:

The framework copying shell script copies the dylibs. I'm not at my computer now but I can get more helpful information for you in 30 minutes.

**Comment by a2** [comment] 2015-03-24 14:07
The generated [Pods-ArexKit-frameworks.sh](https://github.com/a2/arex-7/blob/1f61af134ac3fd947bbe50c8a50970430c5ef777/Pods/Target%20Support%20Files/Pods-ArexKit/Pods-ArexKit-frameworks.sh#L27-L38) file in a2/arex-7@1f61af134ac3fd947bbe50c8a50970430c5ef777 embeds the Swift dylibs into the ArexKit.framework build product.

**Comment by neonichu** [comment] 2015-03-24 19:52
So, the problem is that while the "Embed Pods frameworks" script only copies the libraries once, it does so per **user target**. 

In this case, they get embedded into ArexKit.framework by its script and then again by the Arex application target when running the second script.

I guess we can't really skip framework targets in general, because a Swift framework might be embedded into an Objective-C app? Maybe the script could delete them from embedded content?

Anyways, for the time being, the best workaround is probably making ArexKit a CocoaPod itself.

**Comment by mrackwitz** [comment] 2015-09-07 16:43
This seems to be fixed by #3489 for new installations a while ago and with #4028 for existing installations as well.

**Closed by mrackwitz** 2015-09-07 16:43 UTC
Labels: t2:defect
