### ISSUE TITLE
Header search path issues  -  use_frameworks! & a 'vendored_libraries' podspec, Cocoapods 0.38

### ISSUE THREAD

**Issue by darrenclark** [CocoaPods/CocoaPods#3854] opened 2015-07-21 15:30 UTC
🌈

**CocoaPods Version**: 0.38

**Issue:**  Can't `#import` header files from a Pod that is headers + static library when using frameworks (`use_frameworks!`).  Specifically, I'm trying use the GoogleAnalytics pod (https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleAnalytics/3.12.0/GoogleAnalytics.podspec.json to be exact)

**Demo Project**:  https://github.com/darrenclark/miniature-octo-dangerzone

- See `ViewController.m` where I attempt to import a header from GoogleAnalytics pod.  Upon building you should get an error that it cannot find the header file.

**Other Comments**

Judging by the `.xcconfig` file generated by CocoaPods, it looks like it was working about half way (as it added the `-lGoogleAnalytics` linker flag) but didn't quite add the correct header search path to `OTHER_CFLAGS`.  See:  https://github.com/darrenclark/miniature-octo-dangerzone/blob/master/Pods/Target%20Support%20Files/Pods/Pods.debug.xcconfig#L4-L5

**Comment by darrenclark** [comment] 2015-07-21 17:17
A temporary fix for anyone else experiencing this issue is to manually add the header search paths (pointing to within the `Pods/` directory) for any affected pods.

For example, in my case I added `$(SRCROOT)/Pods/GoogleAnalytics/Headers/Public/` to my target's header search paths, then updated my `#imports` accordingly (ie.:  changed `#import <GoogleAnalytics/GAI.h>` to `#import "GAI.h"`

**Comment by perotinus** [comment] 2015-07-21 20:17
More discussion of this problem in #3857.

**Comment by neonichu** [comment] 2015-07-22 11:41
Closing this as a duplicate of #3857.

**Closed by neonichu** 2015-07-22 11:41 UTC
