### ISSUE TITLE
Archiving iOS application adds warnings to project when using use_frameworks!

### ISSUE THREAD

**Issue by akitchen** [CocoaPods/CocoaPods#3559] opened 2015-05-13 23:25 UTC
When using ```use_frameworks!```, archiving an application (e.g. signing for distribution) results in warnings added to the project -- "Umbrella header for module 'my pod dependency' does not include header 'Pods-MyTarget-MyPodDependency-umbrella.h'.

This is unfortunate, as the build will fail if treating warnings as errors.  Also unfortunately, one is not able to suppress the ```-Wincomplete-umbrella``` warning using ```#pragma clang diagnostic```

Therefore, it does not seem to be possible to use ```use_frameworks!``` in combination with ```-Werror```

**Comment by segiddins** [comment] 2015-05-14 03:56
Can you give us steps to reproduce this issue?

**Comment by neonichu** [comment] 2015-05-14 07:19
Can you please check if this is the known issue #3200 or a new one? To reiterate, the known issue occurs when you archive an application with an extension which shares dependencies with the host target.

**Comment by akitchen** [comment] 2015-05-15 04:22
@neonichu /cc @segiddins - I don't think this is the exact same issue as #3200 - there is no swift code in this project or its dependencies.  However these issues may be related.  We have an iOS framework and application with common dependencies provided by a ruby method in the Podfile.

Also, when the archive is created Xcode doesn't see it as valid and doesn't show it in the organizer, though it does contain a functioning app bundle.  I believe this has come up in other issues as well, such as early in the repro steps for #3493 .

HTH

**Comment by neonichu** [comment] 2015-05-15 08:18
The "Swift" in the title of that issue is misleading, it's about frameworks being shared by different targets which are being archived together in general. So with the additional details, it appears to me to be a duplicate of #3200. A potential fix is developed in #3550, but it's not quite ready, yet.

**Closed by neonichu** 2015-05-15 08:18 UTC
Labels: s1:awaiting input
