### ISSUE TITLE
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Crashlytics">

### ISSUE THREAD

**Issue by wangqianjun** [CocoaPods/CocoaPods#5566] opened 2016-06-26 04:03 UTC
### Command

```
/usr/local/bin/pod install --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin14]
    RubyGems : 2.5.1
        Host : Mac OS X 10.10.5 (14F1902)
       Xcode : 7.2.1 (7C1002)
         Git : git version 1.8.4
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 25a66ed84650f0c5637dec0096e0731d3c576f49
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

link_with ['YH_Mall_iPhone','YH_Mall_iPhone_Pre','YH_Mall_iPhoneTests']

def import_pods

    pod 'Crashlytics'
    pod 'Fabric'
    pod 'GVUserDefaults', '~> 1.0.1'
    pod 'JTSHardwareInfo', '~> 0.0.1'
    pod 'JSPatch', :git => 'https://github.com/bang590/JSPatch.git', :tag => '0.2'
    pod 'MSDKDns', :git => 'https://git.oschina.net/cuckoo/YH_HttpDns.git', :tag => '1.2'
    pod 'Masonry', '~> 1.0.0'
    pod 'PinYin4Objc', '~> 1.1.1'
    pod 'YYModel', '~> 0.9.12'

end

def import_pods_react
    pod 'React', :path => '../YH_Mall_React/node_modules/react-native', :subspecs => [
    'Core',
    'RCTImage',
    'RCTNetwork',
    'RCTText',
    'RCTWebSocket',
    # Add any other subspecs you want to use in your project
    ]
end

import_pods

target 'YH_Mall_iPhone_C1' do
    import_pods
    import_pods_react
end

target 'YH_Mall_iPhone_C2' do
    import_pods
    import_pods_react
end

target 'YH_Mall_iPhone_C3' do
    import_pods
    import_pods_react
end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Crashlytics">
Did you mean?  to_query
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by orta** [comment] 2016-06-26 04:30
Dupe of https://github.com/CocoaPods/CocoaPods/issues/4689 - please use the latest versions of CocoaPods if you are using the latest builds of ruby.

**Closed by orta** 2016-06-26 04:30 UTC
