### ISSUE TITLE
some pods cache exception when some projects install at same time in same machine

### ISSUE THREAD

**Issue by charlesdbs** [CocoaPods/CocoaPods#6500] opened 2017-02-21 02:48 UTC
## What did you do?

pod install 

## What did you expect to happen?

This scene is not necessarily appear， when I have some projects pod install at same time in same machine, sometimes some Pods lost files in cache dir ~/Library/Caches/CocoaPods/Pods.  I guess do not have evidence, maybe other pod install clean operation  when this pod install copy operation。
this cause some files not found where execute xcodebuild command.
  At least I can pod install  when just one project execute pod install.

## CocoaPods Environment

ℹ Please replace this with the output of `pod env`.
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.5p319 (2016-04-26 revision 54774) [x86_64-darwin16]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.12.1 (16B2657)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /usr/local/Cellar/ruby22/2.2.5_2/lib

**Comment by benasher44** [comment] 2017-02-21 14:51
Hi there! Thanks for the report! I believe this is a duplicate of #6280, so I'm going to close this. If you have any extra info, please chime in on the thread there. Have a great day!

**Closed by benasher44** 2017-02-21 14:51 UTC
