### ISSUE TITLE
Invalid archive produced when using "Archive" in Xcode

### ISSUE THREAD

**Issue by darrenclark** [CocoaPods/CocoaPods#3645] opened 2015-06-03 16:42 UTC
Setup a demo project that reproduces the issues here:  https://github.com/darrenclark/ducking-archer

Basically, Debug/Run builds work fine, however when I go to archive the app, it doesn't successfully archive it (just silently fails).

The project has 3 parts of interest:

- `ducking-archer`  - the main app target, includes `AFNetworking` pod

- WatchKit extension - no pods

- `DataKit` target - shared framework for shared classes between main app & WatchKit extension, includes `AFNetworking` pod

I also applied some fixes so far to try to get it building.

- patching in `APP_EXTENSION_SAFE_API` via `post_install` hook (see related issue #3644)

- disabling 'Parallelize build' in the scheme.

I'm totally fine adding some workarounds to my `post_install` hook or wherever until an official fix is available.  If anyone has any ideas?

**Comment by neonichu** [comment] 2015-06-03 17:42
Thanks for sharing this detailed example project - it does not fail silently, but this is basically a duplicate of #3493, though. We will eventually be able to fix this with the changes in #3550, but they are not ready, yet.

A possible workaround might be moving `DataKit` into a development pod of its own, see <https://github.com/a2/arex-7/blob/master/ArexKit.podspec> and its project for some inspiration.

**Closed by neonichu** 2015-06-03 17:42 UTC

**Comment by darrenclark** [comment] 2015-06-03 17:49
@neonichu  Hmm, it seems to build & archive without errors when I'm archiving it, were you getting build errors?

Either way, I'll try moving DataKit into it's own podspec, thanks!

**Comment by neonichu** [comment] 2015-06-03 17:51
@darrenclark sorry, what I meant is that the project in the duplicated issue doesn't fail silently, but both issues still share the same root cause.

**Comment by darrenclark** [comment] 2015-06-03 18:27
@neonichu   Ahh

Unfortunately separating it out into its own podspec didn't work.

I read through the linked issues/PRs.  So the basic issue is the duplicated frameworks?

**Comment by neonichu** [comment] 2015-06-03 18:30
Yah, exactly. When archiving, the subdirectories we create per target don't exist, breaking Xcode in interesting ways in the process.

**Comment by darrenclark** [comment] 2015-06-03 18:32
Ah k, thanks!
