### ISSUE TITLE
The new version you'd love us to try doesn't work at all.

### ISSUE THREAD

**Issue by revolter** [CocoaPods/CocoaPods#6385] opened 2017-01-08 19:46 UTC
> pod install
Analyzing dependencies

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/revolt/.gems/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.0.beta.3
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 66d53298403a937d4f453061205efe6f17cbb7e4
```

### Plugins

```
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.1.2
cocoapods-try          : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Readly' do
	# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
	use_frameworks!

	# Pods for Readly
	pod 'Fabric'
	pod 'Crashlytics'

	pod 'FLEX', '~> 2.0', :configurations => ['Debug']

	pod 'FolioReaderKit', :git => 'https://github.com/revolter/FolioReaderKit.git', :commit => '90ce3882'

	target 'ReadlyTests' do
		inherit! :search_paths

		# Pods for testing
	end
end
```

### Error

```
LoadError - cannot load such file -- nanaimo
/Users/revolt/.gems/gems/xcodeproj-1.4.1/lib/xcodeproj/plist.rb:23:in `read_from_path'
/Users/revolt/.gems/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Users/revolt/.gems/gems/xcodeproj-1.4.1/lib/xcodeproj/project.rb:102:in `open'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer/analyzer.rb:851:in `block (2 levels) in inspect_targets_to_integrate'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer/analyzer.rb:850:in `each'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer/analyzer.rb:850:in `block in inspect_targets_to_integrate'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer/analyzer.rb:845:in `inspect_targets_to_integrate'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer.rb:236:in `analyze'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/user_interface.rb:64:in `section'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/installer.rb:110:in `install!'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/command/install.rb:37:in `run'
/Users/revolt/.gems/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/lib/cocoapods/command.rb:52:in `run'
/Users/revolt/.gems/gems/cocoapods-1.2.0.beta.3/bin/pod:55:in `<top (required)>'
/Users/revolt/.gems/bin/pod:23:in `load'
/Users/revolt/.gems/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=cannot+load+such+file+--+nanaimo&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6214 [open] [24 comments]
   4 hours ago

 - help!   cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6312 [closed] [6 comments]
   a week ago

 - LoadError - cannot load such file -- nanaimo
   https://github.com/CocoaPods/CocoaPods/issues/6281 [closed] [5 comments]
   2 days ago

and 7 more at:
https://github.com/cocoapods/cocoapods/search?q=cannot%20load%20such%20file%20--%20nanaimo&type=Issues&utf8=✓

**Comment by orta** [comment] 2017-01-08 20:22
The three issues raised inside the error search results will help you, this is a dupe of them.

**Closed by orta** 2017-01-08 20:22 UTC
