### ISSUE TITLE
Why do Pods linked statically include all other pods header search paths?

### ISSUE THREAD

**Issue by mjholgate** [CocoaPods/CocoaPods#5941] opened 2016-09-23 15:05 UTC
I just noticed that when linking with static libraries rather than frameworks, that CocoaPods appears to add ALL other pods' header search paths to each target configuration.

For example, AFNetworking.podspec only has a tiny number of dependencies, but it's target seems to include all of those in the workspace (see my screenshot attached).

I believe this may be slowing down our build, as we've found by removing other header search paths the build is much quicker.

Is this behaviour intended, and what is its reason?

Many thanks!

![screenshot_499](https://cloud.githubusercontent.com/assets/1170271/18790646/810f4082-81a7-11e6-837c-26a898e8ace2.png)

**Comment by dnkoutso** [comment] 2016-09-23 21:23
+1 is a large project of ours each invocation to clang is huge because of this.

**Comment by dnkoutso** [comment] 2016-09-24 00:07
@mjholgate after a bit of digging I managed to come up with a fix to properly setup `pod_target.rb` to include the right header search paths. The problem is this doesn't deal with transitive dependencies so this will require every transitive dependency to be included in your podspec for your library.

Can some of the CocoaPods maintainers weigh in for the original question and strategy they would prefer to implement, if any?

**Comment by dnkoutso** [comment] 2016-09-24 00:58
@mjholgate I spent sometime to perform a fix in `pod_target.rb` seems very straight forward and it works. I am uncertain why CocoaPods maintainers decided to go that route, unless it was just naive and there was no reason.

**Comment by orta** [comment] 2016-09-24 06:54
At a guess, if something like that is straight forward - we probably did it that way at first then found we had to change for a myriad of reasons - given the scope of the project. It could be worth looking inside the history for the file around there to see why changes were made

**Comment by mjholgate** [comment] 2016-09-24 10:27
@dnkoutso Nice one! I'd definitely be interested to try your patch to see what effect it has on performance. You mentioned that this would force podspecs to include their transitive dependencies, but that sounds like that is the right thing to do anyway? I guess it might break a lot of existing setups though!

**Comment by orta** [comment] 2016-09-24 10:56
> force podspecs to include their transitive dependencies, but that sounds like that is the right thing to do anyway

We do this for frameworks, so that's not a blocker 👍

**Comment by orta** [comment] 2016-09-24 10:57
Well, strictly speaking Apple does this for frameworks.

**Comment by mjholgate** [comment] 2016-09-24 11:57
👍

**Comment by dnkoutso** [comment] 2016-09-24 15:14
Well I did update the patch to add header search paths for all direct *and* transitive dependencies. I think I can have a PR today. 

If this is changed to require podspecs to include all their transitive dependencies this might warrant a CocoaPods 2.0 version right?

**Comment by mjholgate** [comment] 2016-09-24 17:08
Awesome, I'll give this a try and let you know the results!

I was thinking a bit more about this, and I guess in some cases a pod might need to #import transitive dependencies in its public interface, while in other situations the dependencies are only needed to build the pod itself.

Does this mean it might make sense (in a later version obviously) to extend the Podspec DSL to indicate whether a dependency should re-exported or not?

**Comment by neonichu** [comment] 2016-09-26 17:48
Pods need to declare any direct use of dependencies anyway if they're built with `use_frameworks`, so I don't think this would be a breaking change necessarily.

**Comment by dnkoutso** [comment] 2017-05-23 17:38
I'll be reviving this perhaps for a 1.3.0.beta.1 release.

**Comment by dnkoutso** [comment] 2017-12-14 04:23
This is going to go out with 1.5.0. I'll be finishing the PR.

**Comment by pencilcheck** [comment] 2018-04-09 21:52
In 1.5.0 it will not generate pods correctly for React headers, reverting to 1.4.0 resolve that issue for now. I get errors such as `"React/RCTViewManager.h" not found` Turns out that in 1.5.0: The generated header search path for the pods project for react one is not included somehow, therefore the react/react/* headers are not found.

It is kinda funny to find this issue and it seems so relevant to the issue I'm currently facing. I'm not sure if this is a regression or a migration over to the new method which i'm not sure if I'm doing it right from 1.4.0. If someone can find out why that would be awesome.

**Comment by dnkoutso** [comment] 2018-04-09 22:28
for 1.5.0 and without modular headers this seems you are missing a dependency in your `podspec`, `s.dependency`.

By the way I am closing this issue as it has now shipped.

**Closed by dnkoutso** 2018-04-09 22:28 UTC
Labels: t1:enhancement, t3:discussion
