### ISSUE TITLE
CocoaPods 0.36.X breaks custom configurations

### ISSUE THREAD

**Issue by irace** [CocoaPods/CocoaPods#3441] opened 2015-04-21 16:05 UTC
If using a custom configuration (i.e. _not_ “Release” or “Debug”), the `Intermediate Build Files Path`, `Per-configuration Intermedia Build Files Path`, and `Path to Link Map File` values are incorrect for the static libraries that CocoaPods 0.36.X generates. 

This results in the following error:

> `ld: Library not found for -lPods-application-DevelopmentPodName`
> `clang: error: linker command failed with exit code 1 (use -v to see invocation)`

This is a regression that works correctly in 0.35.0.

**Comment by segiddins** [comment] 2015-04-21 16:24
@irace what version of CocoaPods are you using? Can you share a Podfile that consistently reproduces the issue?

**Comment by irace** [comment] 2015-04-21 16:30
0.36.4. A Podfile wouldn't be sufficient since according to @neonichu (he’s able to reproduce), it only happens with custom Xcode configurations.

If I have time later today I will try to attach an Xcode project that reproduces the issue.

**Comment by irace** [comment] 2015-04-21 22:09
Upon closer look, @neonichu does _not_ actually think he has a reproduction case. He did see an error but it resolved itself upon running `pod install` again, which is not the case for us.

I will try to isolate in a sample project tomorrow.

**Comment by segiddins** [comment] 2015-04-21 22:10
@irace have you tried de-integrating (using `cocoapods-deintegrate`) and then running `pod install` again? It might be an upgrade issue?

**Comment by irace** [comment] 2015-04-21 22:22
@segiddins Will try this tomorrow, thank you for your help.

**Comment by irace** [comment] 2015-04-22 14:47
After running `cocoapods-deintegrate`, I still get incorrect `Intermediate Build Files Path`, `Per-configuration Intermedia Build Files Path`, and `Path to Link Map File` values for all of our custom configurations:

![screen shot 2015-04-22 at 10 36 53 am](https://cloud.githubusercontent.com/assets/399560/7277032/8a6c1eae-e8db-11e4-94b5-18d9b272ef7c.png)

**Comment by irace** [comment] 2015-04-22 15:11
> After running cocoapods-deintegrate, I still get incorrect Intermediate Build Files Path, Per-configuration Intermedia Build Files Path, and Path to Link Map File values for all of our custom configurations:

_That said_, archiving one of those custom schemes *does* seem to work after running `pod reintegrate` and re-integrating, where it did _not_ work beforehand. Those strange paths still scare me though.

**Comment by neonichu** [comment] 2015-04-22 15:14
The "scary" (:ghost:) paths might relate to #3183 - maybe @samdmarshall knows something about it.

**Comment by samdmarshall** [comment] 2015-04-22 15:33
The changes I made to support the legacy locations would only come into play if the "legacy" option was selected. If that is the case, this would work out of the box with the default setup. As discussed with @alloy on that: if you were to use those settings it would be up to you for correct configuration. If there is a example repo I should be able to look at this in a few hours or this weekend.

**Comment by irace** [comment] 2015-04-22 16:52
> The changes I made to support the legacy locations would only come into play if the "legacy" option was selected.

What “legacy” option is this exactly? It’s possible we have it selected but are unaware. Thanks @samdmarshall.

**Comment by samdmarshall** [comment] 2015-04-22 18:24
http://samdmarshall.com/blog/managing_xcode.html#builddir-legacy, it dictates the location of where your built products go and it is assigned per user. If it is enabled then your build-related paths are as shown in the project file -- otherwise they are stored in derived data or user specified paths.

**Comment by irace** [comment] 2015-04-22 18:31
Cool, thanks for clarifying @samdmarshall. We don’t appear to have that enabled so this appears unrelated to your changes.

To reiterate, after deintegrating, we now **are** able to archive using a custom scheme. The weird paths still make me :confused: though.

**Comment by samdmarshall** [comment] 2015-04-22 18:37
You are right, some of those paths look off, see here: http://pewpewthespells.com/blog/buildsettings.html#ld_map_file_path for the default value, you might want to check how you have that configured to see what is messing up.

**Comment by irace** [comment] 2015-04-22 19:09
So it basically looks like the following variables are “wrong” for custom configurations in Pods.xcodeproj. I don’t know where they get set, though:

* `TARGET_TEMP_DIR`
* `SYMROOT`
* `PROJECT_TEMP_DIR`

**Comment by samdmarshall** [comment] 2015-04-22 19:15
`SYMROOT` should be using something that resolves to `../build` so that the Legacy option puts all the built products from the user's project and the Pods project into the same directories. `PROJECT_TEMP_DIR` uses `SYMROOT` so that might be expected, and `TARGET_TEMP_DIR` uses `PROJECT_TEMP_DIR` underneath so that might be explained by my change unless SYMROOT is drastically different. (I think we ended up implementing `SYMROOT` to be set to `$(PODS_DIR)/../build` by default?)

**Comment by irace** [comment] 2015-04-22 19:18
@samdmarshall If there’s any specific information I can provide for you, please let me know what I can do to help. I don’t understand these variables well enough to dig into how or where they are set, or why they have different values for custom configurations vs. default configurations.

**Comment by samdmarshall** [comment] 2015-04-22 19:29
If you could upload an example workspace that exhibits the same issues I can dig into what is going wrong here.

**Comment by segiddins** [comment] 2015-07-06 02:22
Closing this since we never got a project that reproduces the issue.

**Closed by segiddins** 2015-07-06 02:22 UTC
