### ISSUE TITLE
error running 0.39.0.beta1

### ISSUE THREAD

**Issue by idokleinman** [CocoaPods/CocoaPods#4089] opened 2015-08-27 00:26 UTC
Whatever I try I get:
```
> pod lib lint
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- cocoapods/gem_version (LoadError)
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.1/lib/cocoapods.rb:21:in `<module:Pod>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.1/lib/cocoapods.rb:17:in `<top (required)>'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.1/bin/pod:25:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment] 2015-08-27 00:32
Closing as a duplicate of https://github.com/CocoaPods/CocoaPods/issues/4085.

**Closed by segiddins** 2015-08-27 00:32 UTC
