### ISSUE TITLE
resource_bundle regression from 0.39.0

### ISSUE THREAD

**Issue by futuretap** [CocoaPods/CocoaPods#4965] opened 2016-03-02 10:08 UTC
# Report

## What did you do?

I created an empty test project with this Podfile and ran `pod install`:

```
platform :ios, '7.0'
target 'SettingsDemo' do
  pod 'InAppSettingsKit'
end
```

## What did you expected to happen?

The project should build successfully.

## What happened instead?

The Xcode build fails with:

`error: Resource "/Users/gentz/Library/Developer/Xcode/DerivedData/SettingsDemo-blanesryeeyuisbemeulhscxmdsl/Build/Products/Debug-iphonesimulator/InAppSettingsKit.bundle" not found. Run 'pod install' to update the copy resources script.
`

## Notes
This worked fine in cocoapods-0.39.0 and fails in 1.0.0.beta.4.

I believe this line in the podspec is the culprit:

	s.resource_bundles		= {"InAppSettingsKit" => "InAppSettingsKit/Resources/*"}

However, I don't see a bug in there. This [proposed solution](https://github.com/futuretap/InAppSettingsKit/issues/332) doesn't make sense imo because CocoaPods should handle the bundle generation transparently.

I should add that I experimented with various modifications of the `resource_bundles` line in my podspec:

	s.resource_bundle		= {"InAppSettingsKit" => 'InAppSettingsKit/Resources/**/*'}
	s.resource_bundle		= {"InAppSettingsKit" => 'InAppSettingsKit/Resources/*.lproj'}
	s.resource_bundle		= {"InAppSettingsKit" => 'InAppSettingsKit/Resources/*.lproj/*'}
	s.resource_bundles		= {"InAppSettingsKit" => ['InAppSettingsKit/Resources/*.lproj']}

None of them fixes the issue.

**Comment by liuwin7** [comment] 2016-03-02 10:23
Waiting for fixing it up!
Thanks in advance!

**Comment by segiddins** [comment] 2016-03-02 14:01
@efirestone any ideas on this one?

**Comment by Coeur** [comment] 2016-03-03 10:20
Same issue here: it's a regression from beta3 to beta4.

**Comment by Coeur** [comment] 2016-03-03 10:24
With beta3:
* bundle is in `Debug-iphonesimulator/InAppSettingsKit.bundle`

With beta4:
* bundle is in `Debug-iphonesimulator/InAppSettingsKit/InAppSettingsKit.bundle` but script is looking in `Debug-iphonesimulator/InAppSettingsKit.bundle`

**Comment by efirestone** [comment] 2016-03-03 18:11
This looks like the same issue as https://github.com/CocoaPods/CocoaPods/issues/4963

**Comment by segiddins** [comment] 2016-03-03 18:20
In that case, it ought to be fixed on master?

**Comment by max-potapov** [comment] 2016-03-04 12:56
Had a similar issue with current beta: ```Resource "/Users/max/Library/Developer/Xcode/DerivedData/Fresh-gluzjqextiefxmekhrdlooclrbck/Build/Products/Debug-iphonesimulator/MWPhotoBrowser.bundle" not found. Run 'pod install' to update the copy resources script.```

Installed bundle from master (a4961a6) and now it works.

**Comment by dral3x** [comment] 2016-03-10 16:54
Same here loading `HockeySDK` pod

**Comment by segiddins** [comment] 2016-03-10 17:02
Can y'all check on 1.0.0.beta.5? If that doesn't fix things, a PR fixing the copy resources script would be much appreciated ;)

**Comment by dral3x** [comment] 2016-03-10 17:06
I am using the latest beta 5 @segiddins

**Comment by segiddins** [comment] 2016-03-10 17:14
OK, in that case someone will have to come up with a fix, since I'm focused on other areas of CocoaPods for the time being

**Comment by Coeur** [comment] 2016-03-11 02:31
Hi.

The Beta4 issue was only affecting pods with a `resources` or `resource_bundles` in their .podspec. If you don't need any resource, removing the line from your .podspec will workaround the issue for Beta4.

For Beta5, issue seems fixed for me. But if you happen to have a corrupted installation from Beta4, you might want to delete the `~/Library/Developer/Xcode/DerivedData/` folder.

**Comment by lumaxis** [comment] 2016-03-11 10:09
@Coeur I can not confirm this. I'm still seeing this issue with a clean `DerivedData` folder and using 1.0.0beta.5.

**Comment by Coeur** [comment] 2016-03-11 11:54
Can you provide a sample project with the issue?

**Comment by dral3x** [comment] 2016-03-11 11:57
@Coeur try an empty project with this podfile
```
platform :ios, '8.0'
use_frameworks!

target 'TestApp' do
    pod 'HockeySDK', '3.8.5'
end
```

**Comment by mrackwitz** [comment] 2016-03-11 19:10
This is actually a duplicate of #4963. Closing this now in favor of the other issue. As stated already there, I'm working right now on a fix.

**Closed by mrackwitz** 2016-03-11 19:10 UTC
Labels: s2:confirmed, t2:defect
