### ISSUE TITLE
Validate `pod` directive options and print meaningful error.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#995] opened 2013-04-23 09:07 UTC
See #994 for an example (combined use of `:podspec` and `:git`).

**Comment by k0nserv** [comment] 2015-06-05 15:50
I can't reproduce the original issue. The podfile I am using 


```ruby
platform :ios, '8.0'

pod 'AFNetworking' 

target :Test do
    pod 'SDWebImage'
    pod 'Facebook-iOS-SDK', :podspec => "https://raw.githubusercontent.com/CocoaPods/Specs/master/Specs/Facebook-iOS-SDK/4.1.0/Facebook-iOS-SDK.podspec.json", 
                            :git => "https://github.com/facebook/facebook-ios-sdk.git", :commit => "fc1cde21ae7359255b59a24e4845a7da97ee3ec8"
end
```

installs without issue. I have a basic `PodfileValidator` implemented that could catch this issue, but I am not sure if it still is an issue

**Comment by segiddins** [comment] 2015-06-05 16:53
@k0nserv that's a bug if that works...

**Comment by k0nserv** [comment] 2015-06-05 16:56
Okay then I guess I'll continue. So both `podspec` and `path` are illegal in combination with any of the supported downloaders?

**Comment by segiddins** [comment] 2015-06-05 16:57
yup!

**Comment by k0nserv** [comment] 2015-06-21 12:22
Closing with the merge of #3676

**Closed by k0nserv** 2015-06-21 12:22 UTC
Labels: d1:easy, s2:confirmed, t1:enhancement
