### ISSUE TITLE
pod OS X 10.11 ElCapitan issue

### ISSUE THREAD

**Issue by chlebta** [CocoaPods/CocoaPods#4307] opened 2015-10-02 15:25 UTC
After Updating to OS X 10.11 ElCapitan  I get this when I run pod install : 
```
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
```
any helps ?

**Comment by segiddins** [comment] 2015-10-02 19:31
This is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/4302.

**Closed by segiddins** 2015-10-02 19:31 UTC
