### ISSUE TITLE
NoMethodError - undefined method `path' for nil:NilClass

### ISSUE THREAD

**Issue by cuddergambino** [CocoaPods/CocoaPods#5897] opened 2016-09-18 17:58 UTC
### Command

```
/Users/cuddergambino/.rbenv/versions/2.2.3/bin/pod install
```

### Report

* What did you do?

Recently updated to Xcode 8 and converted library to Swift 3. Ran `pod install` in the Example app directory

* What did you expect to happen?

The project to properly update itself

* What happened instead?

The error shows up and the example app doesn't recognize the cocoapod. Similar to issue #4887

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/cuddergambino/.rbenv/versions/2.2.3/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fee4e0653bae3149c44a48d6aa76b4a9e4c42ebb
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'DopamineKit_Example' do
    pod 'DopamineKit', :path => '../'
    
    target 'DopamineKit_Tests' do
        inherit! :search_paths
        
    end
end

post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name == 'DopamineKit'
            target.build_configurations.each do |config|
                if config.name == 'Debug'
                    config.build_settings['OTHER_SWIFT_FLAGS'] = '-DDEBUG'
                end
            end
        end
    end
end
```

### Error

```
NoMethodError - undefined method `path' for nil:NilClass
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/native_target.rb:462:in `block in add_file_references'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/native_target.rb:461:in `map'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/xcodeproj-1.3.1/lib/xcodeproj/project/object/native_target.rb:461:in `add_file_references'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:110:in `block in add_files_to_build_phases'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:86:in `each'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:86:in `add_files_to_build_phases'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:23:in `block in install!'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:115:in `install!'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Users/cuddergambino/.rbenv/versions/2.2.3/lib/ruby/gems/2.2.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/Users/cuddergambino/.rbenv/versions/2.2.3/bin/pod:23:in `load'
/Users/cuddergambino/.rbenv/versions/2.2.3/bin/pod:23:in `<main>'
```

**Comment by neonichu** [comment] 2016-09-20 11:23
Are you able to share a project which reproduces the issue?

**Comment by benasher44** [comment] 2016-10-17 04:50
This looks like a dup of #5623, which has more information about how to diagnose and fix the root cause. Going to close this one.

**Closed by benasher44** 2016-10-17 04:50 UTC
Labels: s1:awaiting input
