### ISSUE TITLE
JSON::ParserError - 809: unexpected token at '

### ISSUE THREAD

**Issue by riteshDeopa** [CocoaPods/CocoaPods#10640] opened 2021-05-08 16:12 UTC
### Command

```
/Users/getitrent/.rvm/rubies/ruby-2.6.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin20]
    RubyGems : 3.0.9
        Host : macOS 11.2.1 (20D75)
       Xcode : 12.4 (12D4e)
         Git : git version 2.24.3 (Apple Git-128)
Ruby lib dir : /Users/getitrent/.rvm/rubies/ruby-2.6.0/lib
Repositories : dni-mercury - git - git@github.com:DNI-Mercury/luna-apple-podspecs.git @ ea9398c1a1aba6c0adced215b5d2d6e2ac2c4708

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
DEPLOYMENT_TARGET = '12.0'
PROJECT = 'Client/Client.xcodeproj'

workspace 'DPlus'

source 'git@github.com:DNI-Mercury/luna-apple-podspecs.git'
source 'https://cdn.cocoapods.org/'

use_frameworks!
# Abstract target for clients
# Please see `github.com/dni-mercury/luna-apple-podspecs for a list of available pods and their dependencies.
abstract_target 'ClientPods' do

  ## 3rd Party
  pod 'Nuke', '9.2.4'
  pod 'ReachabilitySwift'
  pod 'Mux-Stats-Core', '3.1.0'
  pod 'KeychainAccess', '4.2.1'

  abstract_target 'ios' do
    pod 'BlueShift-iOS-SDK', '2.1.12'
    pod 'NewRelicAgent', '6.9.0'
    pod 'Branch', '0.36.0'
    pod 'KochavaTrackeriOS', '4.0'
    pod 'KochavaAdNetworkiOS', '4.0'

    target 'emea-ios' do
      platform :ios, DEPLOYMENT_TARGET
      project PROJECT
      pod 'OneTrust-CMP-XCFramework', '6.11.0.0'
    end

    target 'us-ios' do
      platform :ios, DEPLOYMENT_TARGET
      project PROJECT
    end
  end

  abstract_target 'notification-service-ios' do
    pod 'BlueShift-iOS-Extension-SDK', '2.1.12'

    target 'emea-notification-service-ios' do
      platform :ios, DEPLOYMENT_TARGET
      project PROJECT
    end

    target 'us-notification-service-ios' do
      platform :ios, DEPLOYMENT_TARGET
      project PROJECT
    end
  end

  abstract_target 'tvos' do
    pod 'NewRelicAgentTVOS', '6.10.0'
  
    target 'emea-tvos' do
      platform :tvos, DEPLOYMENT_TARGET
      project PROJECT
      pod 'OneTrust-CMP-tvOS-XCFramework', '6.8.0.0'
    end
    
    target 'us-tvos' do
      platform :tvos, DEPLOYMENT_TARGET
      project PROJECT
    end
  end
  
  abstract_target 'top-shelf-tvos' do

    target 'us-top-shelf-tvos' do
      platform :tvos, DEPLOYMENT_TARGET
      project PROJECT
    end
    
    target 'emea-top-shelf-tvos' do
      platform :tvos, DEPLOYMENT_TARGET
      project PROJECT
    end

  end

end

# Abstract target for test pods.
abstract_target 'TestPods' do

  use_frameworks!

  target 'emea-ios-tests' do
    platform :ios, DEPLOYMENT_TARGET
    project PROJECT
    pod 'KochavaTrackeriOS', '4.0'
    pod 'KochavaAdNetworkiOS', '4.0'
  end
  
  target 'us-ios-tests' do
    platform :ios, DEPLOYMENT_TARGET
    project PROJECT
    pod 'KochavaTrackeriOS', '4.0'
    pod 'KochavaAdNetworkiOS', '4.0'
  end

  target 'emea-tvos-tests' do
    platform :tvos, DEPLOYMENT_TARGET
    project PROJECT
  end

  target 'us-tvos-tests' do
    platform :tvos, DEPLOYMENT_TARGET
    project PROJECT
  end

end
```

### Error

```
JSON::ParserError - 809: unexpected token at ''
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/json-2.5.1/lib/json/common.rb:216:in `parse'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/json.rb:61:in `from_json'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:742:in `from_string'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification.rb:716:in `from_file'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source.rb:186:in `specification'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:58:in `block in specification_name'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:56:in `each'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/specification/set.rb:56:in `specification_name'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/cdn_source.rb:216:in `search'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-core-1.9.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:416:in `create_set_from_sources'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:385:in `find_cached_set'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:360:in `specifications_for_dependency'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:165:in `search_for'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:274:in `block in sort_dependencies'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `each'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_by'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:267:in `sort_dependencies'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:53:in `block in sort_dependencies'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:70:in `with_no_such_dependency_error_handling'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/delegates/specification_provider.rb:52:in `sort_dependencies'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:288:in `initial_state'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:210:in `start_resolution'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolution.rb:168:in `resolve'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/molinillo-0.6.6/lib/molinillo/resolver.rb:43:in `resolve'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/resolver.rb:94:in `resolve'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1065:in `block in resolve_dependencies'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:1063:in `resolve_dependencies'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer/analyzer.rb:124:in `analyze'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:410:in `analyze'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:235:in `block in resolve_dependencies'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:64:in `section'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:234:in `resolve_dependencies'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/installer.rb:156:in `install!'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command/install.rb:52:in `run'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/lib/ruby/gems/2.6.0/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/bin/pod:23:in `load'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/bin/pod:23:in `<main>'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/bin/ruby_executable_hooks:22:in `eval'
/Users/getitrent/.rvm/rubies/ruby-2.6.0/bin/ruby_executable_hooks:22:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by paulb777** [comment] 2021-05-08 17:48
Possible duplicate of #10118. See https://github.com/CocoaPods/CocoaPods/issues/10118#issuecomment-703243433

**Comment by dnkoutso** [comment] 2021-07-02 00:36
You are also using an older version of cocoapods, please upgrade to 1.10.1 which fixes some issues around CDN.

**Closed by dnkoutso** 2021-07-02 00:36 UTC
