### ISSUE TITLE
Use $(PROJECT_FILE_PATH) instead of $(SRCROOT)

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#9365] opened 2019-11-25 08:09 UTC
I have a project from others, and it have a strange problem:
```
export PROJECT_FILE_PATH=/Users/whirlwind/Documents/Developer/A/B/C/D/E/F/G.xcodeproj
export SRCROOT=/Users/whirlwind/Documents/Developer/A/B/C
export PROJECT_DIR=/Users/whirlwind/Documents/Developer/A/B/C
export PODS_ROOT=/Users/whirlwind/Documents/Developer/A/B/C/Pods
```
The `$(SRCROOT)` is NOT the directory of the project! It cause the `$(PODS_ROOT)` will use a error path. ( The `$(PODS_ROOT)` should be `/Users/whirlwind/Documents/Developer/A/B/C/D/E/F/Pods`)

I double check the `G.xcodeproj/project.pbxproj`, I found the settings:
```

/* Begin PBXProject section */
		E4238CC8B4774D8A8802BCCE /* Project object */ = {
			isa = PBXProject;
			mainGroup = EA804AF9E8CA4DEB82082C1A;
			productRefGroup = CE9B265E153D40ADB3BF907B /* Products */;
			projectDirPath = ../../../../../../; 
			projectRoot = "";
		};
/* End PBXProject section */
```

The `projectDirPath` is the `./../../../../../`, and it will cause the `SRCROOT` is not the directory of project. But the CocoaPods set the `PODS_ROOT` to the relative path from the project file.

**Comment by amorde** [comment] 2019-11-25 21:39
What is the error you are seeing in this example?

**Comment by Whirlwind** [comment] 2019-11-26 03:15
In the disk, the directory are:
```
The CocoaPods sandbox: /A/B/C/D/E/F/Pods
The CocoaPods Podfile: /A/B/C/D/E/F/Podfile
The Xcode Project: /A/B/C/D/E/F/G.xcodeproj
```
The Xcode Environment Information from the build log:
```
export PROJECT_FILE_PATH=/A/B/C/D/E/F/G.xcodeproj
export SRCROOT=/A/B/C
export PROJECT_DIR=/A/B/C
export PODS_ROOT=/A/B/C/Pods
```
First, the `Pods` group in user project will have an error relative path, include the `Pods-xxx.xcconfig` path. The `G.xcodeproj`'s path is `/A/B/C/D/E/F/G.xcodeproj`, the `Pods` group's relative path is `Pods`. But the `Pods` group will use a full path: `/A/B/C/Pods`, it is not the correct path `/A/B/C/D/E/F/Pods`.

After I change the `Pods` group relative path to `D/E/F/Pods`, the xcconfig will works.

Second, The `PODS_ROOT` have an error path, it will causes the `Check the CocoaPods manifest` script could not find the `Podfile.lock` and `Pods/Manifest.lock`, so it will cause an build error.

Then, all `HEADER_SEARCH_PATH` and so on, which use the `PODS_ROOT`, will not works.

**Comment by Whirlwind** [comment] 2019-11-26 03:21
You can try to edit any project in a text editor:
```
/* Begin PBXProject section */
		E4238CC8B4774D8A8802BCCE /* Project object */ = {
			isa = PBXProject;
			mainGroup = EA804AF9E8CA4DEB82082C1A;
			productRefGroup = CE9B265E153D40ADB3BF907B /* Products */;
			projectDirPath = ../../../../../../;  // <-- Change this to any path
			projectRoot = "";
		};
/* End PBXProject section */
```
You will reproduce the this issue. It seems that the Xcode allow change the root directory by the `projectDirPath`, and it will effects the `SRCROOT`.

**Comment by dnkoutso** [comment] 2019-12-03 18:15
So basically the issue here that if someone uses a custom `PROJECT_FILE_PATH` then we should prefer that? If there is no custom `PROJECT_FILE_PATH` does it mean that `PROJECT_FILE_PATH == SRCROOT`?

**Comment by amorde** [comment] 2019-12-04 00:40
It seems odd that `PROJECT_DIR` is not `/A/B/C/D/E/F` in your example. I would think that would be the correct value to use to get the desired behavior

**Comment by Whirlwind** [comment] 2019-12-04 10:16
`It seems odd that PROJECT_DIR is not /A/B/C/D/E/F in your example.`

Yes, you are right.

The `projectDirPath` in the project is modified by some tools. They are using the `cmake` to create this project file.

I don't know that how to create the project by the cmake, but I think that sandbox relative path maybe wrong. The `SRCROOT` is different  from the `PROJECT_FILE_PATH`.

**Comment by paulb777** [comment] 2020-02-21 00:09
This is likely a duplicate of #6268 and the unfinished PRs for it may apply here as well.

**Comment by paulb777** [comment] 2020-02-21 19:20
Closing as a duplicate of #6268.  Please follow that issue.

**Closed by paulb777** 2020-02-21 19:20 UTC
