### ISSUE TITLE
After a pod update, the script "[CP] Check Pods Manifest.lock" always moves to the highest position in the Build Phases for a project.

### ISSUE THREAD

**Issue by azav** [CocoaPods/CocoaPods#8686] opened 2019-04-09 15:57 UTC
CocoaPods: 1.6.1
Xcode: 10.1

Summary
Once a pod update is performed, the Build Phase shell script "[CP] Check Pods Manifest.lock" moves before all other scripts in the target.

Steps to Reproduce
1. Look at your target's Build Phases and move the "[CP] Check Pods Manifest.lock" script from its position at the top of the build phases.
2. Perform a pod update.

Results
"[CP] Check Pods Manifest.lock" is now at the top of the target's Build Phases.

Expected
The script should stay where it was placed in the build script order.

Problem
I've written my own script which handles the install of the pods binary, initial pod installs and pod updates upon a manifest mismatch.  The "[CP] Check Pods Manifest.lock" script continually moving to the top of the build phase order and continually reappearing defeats the purpose of my much more complete script.
How can this script be permanently removed or the automatic reorder disabled?

**Comment by dnkoutso** [comment] 2019-04-09 16:54
The script by design is meant to be first for CocoaPods to function properly.

This has not changed afaik so I am not sure what is happening. It seems you are performing something custom here which you can very easily delete or re-order the script phase. Easily via a `post_install` hook or if you do your own scripting then easily using Xcodeproj gem.

I am going to close this as it does not appear to be actionable for us. I *will* re-open it though if we figure out perhaps an enhancement can be implemented here.

**Closed by dnkoutso** 2019-04-09 16:54 UTC

**Comment by azav** [comment] 2019-04-09 17:14
Thanks for the prompt response.  I know it has not changed, but the issue is that I wrote a script that handles whether to install the pod binary, perform a pod install (on a fresh clone of our source) or perform a pod update.  I want my script to take the place of "[CP] Check Pods Manifest.lock", but I can't do that since it keeps appearing and moving to the top of the Build Phases.  

Now, it may be very easy _for you_ to move the script to a different location via a post install hook or by scripting my own xcodeproj gem, but I don't know ruby and can't expect my team to have Xcodeproj installed.  

If you know how to move the script or delete the script could you please share that info with me so I can add it to a post build script? 



The "[CP] Check Pods Manifest.lock" file only checks if there is a difference in the locks and then tells you to perform the update yourself and stops the build.  I don't know why this is essential for CocoaPods to operate.  

If there was an option in the pod file to not reorder the Build Phases or not insert "[CP] Check Pods Manifest.lock" that would also solve this for me and anyone else who wants to write a more substantial script.

The problem with "[CP] Check Pods Manifest.lock" is that it stops the build if there is a mismatch and there is no way to change its functionality, delete it or tell it to stop doing that if it keeps being reinserted and moved to the top of the list.  

I'll send you my spec for my replacement script in a reply unless you have another preferred means of contact.

Thanks.

**Comment by azav** [comment] 2019-04-09 17:20
Note: this is an older spec.  I have added a check for the CocoaPods binary using `which` at the start of my script.


Handling pods and builds after clones and pulls from a fresh repo.

Xcode Project Pods Variables:
PODS_PODFILE_DIR_PATH for podfile.lock: 
~/.jenkins/workspace/MyAwesomeProject-iOS-test/

PODS_ROOT for Manifest.lock: 
~/.jenkins/workspace/MyAwesomeProject-iOS-test/Pods

Manifest.lock is in the /Pods directory within the source root directory.
Podfile.lock is in the source root directory.

Project relevant file/folder structure:
Project.xcworkspace
Project.xcodeproj
Pod-file
Podfile.lock
/Pods
/Pods/Manifest.lock
/Pods/Pods.xcodeproj

Project Relevant File/Folder Differences
Project.xcworkspace	- Always present.	
Project.xcodeproj	- Always present.
Podfile	- Always present.
Podfile.lock	- Always present.
/Pods	- Present after a pod install.
/Pods/Manifest.lock	- Present after a pod install.
/Pods/Pods.xcodeproj	- Present after a pod install.

Project.xcworkspace	- Always present.	
Project.xcodeproj	- Always present.
Podfile	- Always present.
Podfile.lock	- Always present.
/Pods	- Present after a pod install.
/Pods/Manifest.lock	- Different from Podfile.lock if Pods have changed, have been added or removed.
/Pods/Pods.xcodeproj	- Present after a pod install.


Cases
1. A fresh clone from the remote repo just completed.
- /Pods folder is missing.
- /Pods/Pods.xcodeproj file is missing.
- /Pods/Manifest.lock folder is missing.
- Podfile.lock is present.
Course of Action
- pod install
- pod update (¿¿?? Is this required on the first check out/clone?)

2. A pod has been added or removed and a pull from remote just completed.
- /Pods folder is present.
- /Pods/Pods.xcodeproj file is present.
- /Pods/Manifest.lock folder is present.
- Podfile.lock is present.
- There is a difference between Manifest.lock and Podfile.lock.
Course of Action
- pod update

3. A pod has been updated and a pull from remote just completed.
- /Pods folder is present.
- /Pods/Pods.xcodeproj file is present.
- /Pods/Manifest.lock folder is present.
- Podfile.lock is present.
- There is a difference between Manifest.lock and Podfile.lock.
Course of Action
- pod update

4. No pod has been added/removed or updated and a pull from remote just completed.
- Pods folder is present.
- /Pods/Pods.xcodeproj file is present.
- /Pods/Manifest.lock folder is present.
- Podfile.lock is present.
- There is no difference between Manifest.lock and Podfile.lock.
Course of Action
- Proceed with build.

Process
- Clone a fresh copy of the MyAwesomeProject repo.
git clone ssh://MyAwesomeCompany@vs-ssh.visualstudio.com:22/DefaultCollection/MyAwesomeProject/_ssh/MyAwesomeProject-ios
- Select the My Awesome Project scheme and set the Simulator iPhone 8 Plus as the target device.
- Command B.  Expect this to fail.
- Check for presence of /Pods, /Pods/Manifest.lock, and /Pods/Pods.xcodeproj.  If any are missing, perform a pod install from /usr/local/bin/pod
- If those files are present, perform a diff on Podfile.lock and /Pods/Manifest.lock as in the current [CP] Check Pods Manifest.lock build script
- Continue with build.

Caveats
- Running this from an Xcode build script will mangle the pod install unless the following is added to the top of a build script.
export LANG=en_US.UTF-8
export LANGUAGE=en_US.UTF-8
export LC_ALL=en_US.UTF-8
- ($SRCROOT) must be passed in to a build script that will attempt to handle this.

Questions
- $(DERIVED_FILE_DIR)/Pods-myAwesomeProject-checkManifestLockResult.txt - is this used at all?

**Comment by dnkoutso** [comment] 2019-04-09 17:21
Yes I can share with you. 

> can't expect my team to have Xcodeproj installed.

If they use CocoaPods they already have it installed because CocoaPods depends on it.

**Comment by azav** [comment] 2019-04-09 18:36
OK so how do you do it?  Which tool?  Is there a place where I can read the docs for it?

Thanks again.

**Comment by dnkoutso** [comment] 2019-04-09 19:11
Look into project https://github.com/CocoaPods/Xcodeproj

Here's a start, type `irb`:

```ruby
require 'xcodeproj'
project = Xcodeproj::Project.open('path/to/YourProject.xcodeproj')
target = project.targets[0]
puts target.build_phases
# ... delete it here
project.save
```
