### ISSUE TITLE
Feature request: If Podfile is empty avoid creating a workspace

### ISSUE THREAD

**Issue by 3lvis** [CocoaPods/CocoaPods#4417] opened 2015-10-21 09:27 UTC
If the `Podfile` is empty it would be great if CocoaPods did nothing.

**Comment by neonichu** [comment] 2015-10-21 10:51
This seems like a duplicate of #3617

**Closed by neonichu** 2015-10-21 10:51 UTC

**Comment by 3lvis** [comment] 2015-10-21 10:55
Thanks <3
