### ISSUE TITLE
Subspec can't set module_name/module_map

### ISSUE THREAD

**Issue by stephencelis** [CocoaPods/CocoaPods#3979] opened 2015-08-07 04:27 UTC
I was trying to organize a podspec to use a different module name and module map depending on which subspec is used. _E.g._,

``` rb
# installs SQLite.framework, with SQLite module (using custom SQLite module map).
pod 'SQLite.swift/SQLite'

# installs SQLiteCipher.framework, with SQLiteCipher module (using custom SQLiteCipher
# module map).
pod 'SQLite.swift/SQLiteCipher'
```

See: https://github.com/stephencelis/SQLite.swift/blob/swift-2/SQLite.swift.podspec#L35-L57 (particularly the commented-out lines in each subspec, which don't work)

I'd love CocoaPods installation to behave the same as other means (_e.g._ Carthage, manually).

Is there a better way of achieving this that works today? Or does CocoaPods need to be updated to support custom module names and maps at the subspec level?

**Comment by segiddins** [comment] 2015-08-07 04:30
Nope, best bet there is two separate pods if you want them to be two separate frameworks.

**Comment by stephencelis** [comment] 2015-08-07 04:37
:disappointed: The framework is almost identical. The name is differentiated based on the core being linked to SQLCipher rather than the built-in SQLite library (and thus has a slightly expanded API). Using different framework names is required both:

- to avoid confusion in a sub-project with multiple targets that would share the same name, and
- to support Carthage, which also requires target names to be unique

Maybe there's a better way that I'm not thinking of? Maintaining 2 separate branches/repos would be even more cumbersome.

If I have to use 2 separate pods, is this possible in a single repo? The installation fragmentation I'm seeing with CocoaPods is unfortunate.

**Comment by segiddins** [comment] 2015-08-07 04:38
You can keep as many pods as you want in a repo, just make sure the podspecs are in the root.

**Comment by stephencelis** [comment] 2015-08-07 04:50
Wouldn't that mean they'd show up as separate pods on CocoaPods.org once submitted? That would be even more confusing. Is it really not possible to support different module names and module maps at the subspec level? This seems like it's a bug that could be fixed.

**Comment by segiddins** [comment] 2015-08-07 04:51
It's not a bug-- each pod is meant to be its own module.

**Comment by stephencelis** [comment] 2015-08-07 04:52
It's still its own module. Its name would merely differ depending on the flavor installed.

**Comment by segiddins** [comment] 2015-08-07 04:55
I guess that's just not the way CocoaPods was built to work? I don't really know what else to say

**Comment by stephencelis** [comment] 2015-08-07 04:59
I feel like I'm failing to communicate the issue well. SQLite.swift is a framework that provides a Swift wrapper over SQLite3. There is a variation that supports encryption via SQLCipher. They are really a single library/pod, though. It would never make sense to install both of them in the same project.

In order to support this well when installed as a sub-project, it must have a different target name (for disambiguation). Without having separate target names it becomes easy to link to the wrong target depending on the end developer's needs.

In order to support Carthage at all, it must also have a different target name (so that the products don't clobber one another).

I've tried to make a SQLiteCipher.framework that extends SQLite.framework, but due to build setting and linker requirements, I've found that it's just not possible.

CocoaPods supports overriding the module name and module map in the first place. And CocoaPods supports overriding almost every other setting via subspecs, so why not support the overriding of these two?

**Comment by stephencelis** [comment] 2015-08-07 05:02
If you have any other suggestions, I'm all ears. Maintaining different docs for import usage via CocoaPods installation just feels bad :cry:

**Comment by segiddins** [comment] 2015-08-07 05:04
Because those are so called 'root attributes' -- they apply to the whole pod, and subspecs don't get to override them. As to why that's the case for `module_name`, it's because there's an invariant then, when pods are installed as frameworks and via source, you can `import ModuleName` and get that pod. What would happen if you installed two subspecs that had different module names? And your root spec and a subspec had different names? What if different source files were in each subspec? What could CocoaPods reasonably do besides build two different modules there? But that also wouldn't work, because subspecs are presumed to be compiled in the same target, and not in different frameworks.

**Comment by Tokuriku** [comment] 2016-01-05 13:09
That's all good and fine but there is a small situation arising from Swift..
In Objective-C, you can modularize your code in libraries and importing the header from the needed libraries in a different subspec. With frameworks, you're really stuck. There's no way to import them elegantly since when the pod creates the global framework, it packs all subspecs in the same "framework". All the imports in the subspecs break :/

**Comment by neonichu** [comment] 2016-05-02 08:46
Let's close this as the discussion never went anywhere.

**Closed by neonichu** 2016-05-02 08:46 UTC
Labels: t3:discussion
