### ISSUE TITLE
Library not loaded error

### ISSUE THREAD

**Issue by robertodias180** [CocoaPods/CocoaPods#3956] opened 2015-08-03 11:07 UTC
after updating to the new version of pods i am getting this error on iOS 8. Any ideia?

dyld: Library not loaded: @rpath/FBSDKCoreKit.framework/FBSDKCoreKit
  Referenced from: /private/var/mobile/Containers/Bundle/Application/A3460D62-63D7-471E-A014-CD495B55F152/Game.app/Game
  Reason: image not found
(lldb)

**Comment by neonichu** [comment] 2015-08-03 11:19
Probably a dupe of #3661 — please give more info if it isn't, see <https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#bug-reports>

**Closed by neonichu** 2015-08-03 11:19 UTC

**Comment by robertodias180** [comment] 2015-08-03 11:25
not sure since it only happen on iOS8. on my iPhone 4 (iOS7) everything run ok

**Comment by robertodias180** [comment] 2015-08-03 14:11
not sure if this will help. But i created a new project from scratch with the same podfile and it compiled perfectly.
