### ISSUE TITLE
Duplicating a build configuration creates a linker error

### ISSUE THREAD

**Issue by alper** [CocoaPods/CocoaPods#5246] opened 2016-05-04 10:06 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I duplicated a scheme and build configuration to set a couple of user defined variables.
I closed everything and ran `pod install`.
I reopened the workspace.

## What did you expected to happen?

I expected no changes to happen.

## What happened instead?

ld: framework not found Pods_XXXXXX
clang: error: linker command failed with exit code 1 (use -v to see invocation)

I found somebody else with the exact same problem here: 
http://stackoverflow.com/questions/33075962/cocoapods-for-swift-linker-command-failed-for-release-scheme

It turns out duplicating a configuration requires an extra setting as documented here (took some digging): http://guides.cocoapods.org/syntax/podfile.html#project
But that DSL isn't super clear. I found the workaround below to be simpler.

## Workaround

* `pod deintegrate`
* `rm *.xcworkspace`
* `pod install`

**Comment by neonichu** [comment] 2016-05-04 11:17
Which version of CocoaPods did you use? If it was 0.39, could you please check if you're seeing the same with 1.0 RC1?

**Comment by alper** [comment] 2016-05-04 11:58
Sorry to not put that there, I am on: 1.0.0.beta.7

**Comment by alper** [comment] 2016-05-04 12:28
I just reconstructed the entire project since fastlane/scan was failing too and I guess everything went wrong because of a target I renamed early on. But still it is weird that everything would work up until the point where I duplicated the scheme and configuration.

I'll close this unless you think this has a deeper reason.

**Comment by alper** [comment] 2016-05-04 13:16
Ok. I did the same thing with the new project: duplicate scheme and configuration. Same problem.

**Comment by segiddins** [comment] 2016-05-04 13:45
You'll have to share a project that reproduces this issue for us to be able to debug it. Thanks!

**Comment by neonichu** [comment] 2016-05-15 13:58
Closing, because we never got a reproducible project.

**Closed by neonichu** 2016-05-15 13:58 UTC
Labels: s1:awaiting input
