### ISSUE TITLE
`pod install` crashes after updating Jenkins box to Xcode 7

### ISSUE THREAD

**Issue by kballard** [CocoaPods/CocoaPods#4151] opened 2015-09-09 23:46 UTC
After we updated our Jenkins box to Xcode 7, any attempt to run `pod install` by triggering a build results in Cocoapods crashing:

```
2015-09-09 15:55:46.751 ruby[57574:3210820] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8223/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7fead309bb30>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x000000010fe13a5c -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x000000010fe131e9 _DVTAssertionHandler (in DVTFoundation)
  2  0x000000010fe13455 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x000000010fe133b7 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x0000000112242f5c IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x0000000114e9aeb9 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x0000000114e9ca3e +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff855caf44 ffi_call_unix64 (in libffi.dylib)
/var/folders/z5/5h4lhm4n4wd5864ybzj6zbc40000gp/T/hudson6256408094762204666.sh: line 5: 57574 Abort trap: 6           pod install
```

It doesn't crash if I SSH into the machine and run `pod install` manually, and it doesn't crash on my local machine.

This happens with both Cocoapods 0.38.2 and 0.39.0.beta.3.

**Comment by neonichu** [comment] 2015-09-10 00:02
Looks like a duplicate of #3829 to me — I don't see any relevant changes in either 7.0 GM or 7.1 beta

**Closed by neonichu** 2015-09-10 00:02 UTC

**Comment by kballard** [comment] 2015-09-10 00:08
@neonichu I already have the latest `xcodeproj` version (`0.27.2`) installed, so that doesn't help.

**Comment by kballard** [comment] 2015-09-10 00:10
Unless the instructions there were to *backdate* `xcodeproj`? (there's no indication as to whether the given version, `0.24.3`, was the current version at that time)

And if the intent really is to backdate it, then that makes this an active issue with a potential workaround, as opposed to a fixed issue.

**Comment by kballard** [comment] 2015-09-10 00:24
I just tried backdating it. Installing `0.24.3` by itself doesn't fix anything (not surprisingly, as cocoapods won't magically use it), and attempting to uninstall newer versions tells me that that `cocoapods-0.38.2` depends on `xcodeproj ~> 0.26.3` so I can't backdate without breaking cocoapods.

**Comment by neonichu** [comment] 2015-09-10 00:27
Can you see any difference in installed gems between the machines it is working on and those were it's not? Are they all using the same Xcode versions?

**Comment by neonichu** [comment] 2015-09-10 00:27
Scratch that, you said it does not crash when logged in via SSH.

**Comment by kballard** [comment] 2015-09-10 00:28
Correct, I don't know what's different about triggering the build from the Jenkins interface, since it should be building as the exact same "jenkins" user I've SSH'd in as.

**Comment by neonichu** [comment] 2015-09-10 01:00
Could you please double-check both have the same environment, so that actually the same versions of CocoaPods and Xcode are used? Apart from that, I don't see a way of fixing this without being able to reproduce it or know the cause. 

We're planning an opt-out of the native serialisation, see CocoaPods/Xcodeproj#276 — until that has happened, I can only recommend modifying it yourself as a workaround, see <https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/plist_helper.rb#L47>

**Comment by kballard** [comment] 2015-09-10 01:15
I checked the environment Jenkins listed for the build, none of the environment variables it sets should have any effect on Xcode AFAICT. And there's only one version of Xcode installed (Xcode 7) at this point, and only one version of the cocoapods tool installed (0.38.2).

I will look into modifying it by hand tomorrow. Thanks for the link.

**Comment by kballard** [comment] 2015-09-10 18:35
After digging through all of this, I'm a bit embarrassed to admit that it turns out your dupe was correct. I don't know how it got set up this way, but the Jenkins box was using `rvm` to manage Ruby for almost everything, *except* for Jenkins. Jenkins itself was using the system Ruby (I guess it doesn't source the normal profile files even though it's running shell commands as the jenkins user). And the system Ruby had `xcodeproj` version `0.23.0` installed (and a similarly older version of the other cocoapods-related gems).

I'm actually rather surprised that `pod` did not print a notice saying that cocoapods was out of date. It only gave the notice I see locally requesting that I upgrade to the beta. I guess that's suppressing the normal suggestion that I should upgrade to the latest version?

**Comment by neonichu** [comment] 2015-09-11 15:16
Yah, I think you'll see the beta note instead. Might be better to show that one is running an outdated stable instead if that is the case, as this seems more relevant.
