### ISSUE TITLE
Error installing hermes-engine

### ISSUE THREAD

**Issue by itsJohnSolomon** [CocoaPods/CocoaPods#12255] opened 2024-02-05 05:30 UTC
### Command

```
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.0
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [x86_64-darwin21]
    RubyGems : 3.5.5
        Host : macOS 12.7.3 (21H1015)
       Xcode : 14.2 (14C18)
         Git : git version 2.37.1 (Apple Git-137.1)
Ruby lib dir : /usr/local/Cellar/ruby/3.2.2_1/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
require_relative '../node_modules/react-native/scripts/react_native_pods'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'einvestment' do
  config = use_native_modules!

  # Flags change depending on the env values.
  flags = get_default_flags()

  use_react_native!(
    :path => config[:reactNativePath],
    # Hermes is now enabled by default. Disable by setting this flag to false.
    # Upcoming versions of React Native may rely on get_default_flags(), but
    # we make it explicit here to aid in the React Native upgrade process.
    :hermes_enabled => flags[:hermes_enabled],
    :fabric_enabled => flags[:fabric_enabled],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )

  target 'einvestmentTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    react_native_post_install(
      installer,
      # Set `mac_catalyst_enabled` to `true` in order to apply patches
      # necessary for Mac Catalyst builds
      :mac_catalyst_enabled => false
    )
    __apply_Xcode_12_5_M1_post_install_workaround(installer)
  end
end
```

### Error

```
Errno::EEXIST - File exists @ syserr_fail2_in - /Users/john/Library/Caches/CocoaPods/Pods/External/hermes-engine/1093ead2a8c068cdef04abc8f93419c7-4438d/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/Resources
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2266:in `symlink'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2266:in `copy'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:1058:in `block in copy_entry'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2397:in `wrap_traverse'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2400:in `block in wrap_traverse'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2399:in `each'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2399:in `wrap_traverse'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:1055:in `copy_entry'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:1000:in `block in cp_r'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2481:in `block in fu_each_src_dest'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2490:in `block in fu_each_src_dest0'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2488:in `each'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2488:in `fu_each_src_dest0'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:2479:in `fu_each_src_dest'
/usr/local/Cellar/ruby/3.2.2_1/lib/ruby/3.2.0/fileutils.rb:999:in `cp_r'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:343:in `block (2 levels) in copy_files'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in `each'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in `block in copy_files'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:128:in `lock'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:332:in `copy_files'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:269:in `block (2 levels) in uncached_pod'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in `each'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in `block in uncached_pod'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:291:in `in_tmpdir'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader.rb:42:in `download'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:67:in `install!'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:621:in `install_source_of_pod'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:539:in `block (2 levels) in install_pod_sources'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:538:in `block in install_pod_sources'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `each'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `install_pod_sources'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:258:in `block in download_dependencies'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:257:in `download_dependencies'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:163:in `install!'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/lib/cocoapods/command.rb:52:in `run'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/gems/cocoapods-1.15.0/bin/pod:55:in `<top (required)>'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/bin/pod:25:in `load'
/Users/john/ReactNativeProjects/einvestment/vendor/bundle/ruby/3.2.0/bin/pod:25:in `<top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `load'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:58:in `kernel_load'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli/exec.rb:23:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:451:in `exec'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/command.rb:28:in `run'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/invocation.rb:127:in `invoke_command'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor.rb:527:in `dispatch'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:34:in `dispatch'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/vendor/thor/lib/thor/base.rb:584:in `start'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/cli.rb:28:in `start'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:28:in `block in <top (required)>'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/lib/bundler/friendly_errors.rb:117:in `with_friendly_errors'
/usr/local/lib/ruby/gems/3.2.0/gems/bundler-2.5.5/exe/bundle:20:in `<top (required)>'
/usr/local/opt/ruby/bin/bundle:25:in `load'
/usr/local/opt/ruby/bin/bundle:25:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=File+exists+%40+syserr_fail2_in+-+%2FUsers%2Fjohn%2FLibrary%2FCaches%2FCocoaPods%2FPods%2FExternal%2Fhermes-engine%2F1093ead2a8c068cdef04abc8f93419c7-4438d%2Fdestroot%2FLibrary%2FFrameworks%2Funiversal%2Fhermes.xcframework%2Fios-arm64_x86_64-maccatalyst%2Fhermes.framework%2FResources&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
Found no similar issues. To create a new issue, please visit:
https://github.com/cocoapods/cocoapods/issues/new

**Comment by rambaliga** [comment] 2024-02-05 05:52
We are facing the same issue since a couple of days through our Azure Pipelines. The pod install fails with the same error, rerunning the pipeline works sometimes. Please help with a quick fix.

**Comment by tomtom260** [comment] 2024-02-05 08:07
I'm Facing the same issue as well

**Comment by rasmussvane** [comment] 2024-02-05 10:46
Same issue

**Comment by yksa** [comment] 2024-02-05 15:19
same issue

**Comment by paulb777** [comment] 2024-02-05 15:49
Dupe of #12226

**Closed by paulb777** 2024-02-05 15:49 UTC
