### ISSUE TITLE
mismatched PODS_FRAMEWORK_BUILD_PATH when building multiple targets and watchos

### ISSUE THREAD

**Issue by dmueller39** [CocoaPods/CocoaPods#4231] opened 2015-09-21 15:49 UTC
After looking at https://github.com/CocoaPods/CocoaPods/issues/2907 I created a Podfile that looked like this:

```
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!

platform :ios, '8.0'

# the main target
target 'SamplePod_Example' do
  pod "SamplePod", :path => "../"
  #As an example, Bolts cannot be used in an app extension
  pod Bolts
end

# a today app extension
target 'SamplePod_ExampleToday' do
  pod "SamplePod", :path => "../"
end

# testing
target 'SamplePod_Tests' do
  pod "SamplePod", :path => "../"
  pod 'Specta'
  pod 'Expecta'
end

# a watchos target
target 'SamplePod_ExampleWatchOS Extension' do
  platform :watchos, '2.0'
  pod "SamplePod", :path => "../"
end
```

However this creates xcconfig files with the following set for PODS_FRAMEWORK_BUILD_PATH:

Pods-SamplePod_Example-SamplePod.xcconfig (where the SamplePod is put when it is created for ios)

    PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-SamplePod_Example
    
Pods-SamplePod_Example.debug.xcconfig (where the SamplePod_Example target expects the SamplePod framework)

    PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-SamplePod_Example
    
Pods-SamplePod_ExampleToday.debug.xcconfig (where the SamplePod_ExampleToday target expects the SamplePod framework)

    PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-SamplePod_ExampleToday
    
Pods-SamplePod_Tests.debug.xcconfig (where the SamplePod_Tests target expects the SamplePod framework)

    PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-SamplePod_Tests

As you can see the SamplePod_ExampleToday and SamplePod_Tests are looking in the wrong location for the SamplePod framework.

These watchos settings work because there is only one target:

Pods-SamplePod_ExampleWatchOS Extension-SamplePod.xcconfig (where the SamplePod is put when it is created for watchos)

    PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-SamplePod_ExampleWatchOS Extension

Pods-SamplePod_ExampleWatchOS Extension.debug.xcconfig (where the SamplePod_ExampleWatchOS Extension target expects the SamplePod framework)
    
    PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-SamplePod_ExampleWatchOS Extension

Additionally, if I remove all the watchos targets from the Podfile and the project, and run `pod install` then everything is set up correctly.

**Comment by neonichu** [comment] 2015-09-21 17:10
This looks like a target deduplication issue, could you try out disabling it (https://github.com/CocoaPods/CocoaPods/blob/master/CHANGELOG.md#highlighted-enhancement-that-needs-testing) and report back?

**Comment by dmueller39** [comment] 2015-09-21 18:47
After setting `deduplicate_targets: false` and running `pod install` I was able to successfully compile the project.

**Comment by mhuusko5** [comment] 2015-09-22 15:43
I'm having the same/similar issue. `deduplicate_targets: false` fixed it, but this is oh so inconvenient given that it has to be set per machine.

**Comment by neonichu** [comment] 2015-09-22 16:37
@mhuusko5 please also post your Podfile

**Comment by mhuusko5** [comment] 2015-09-22 16:48
```ruby
workspace 'RAMedia'

source 'https://github.com/CocoaPods/Specs.git'

xcodeproj 'RAMedia/RAMedia.xcodeproj'
xcodeproj 'RAMediaExample/RAMediaExample.xcodeproj'

use_frameworks!

target :RAMediaiOS do
  xcodeproj 'RAMedia/RAMedia.xcodeproj'
  platform :ios, '8.0'

  pod 'NSPointerArray+M5Additions', '~> 1.1.0'
  pod 'M5ApplicationMemoryWarning', '~> 1.1.0'
  pod 'M5ApplicationOpenURL', '~> 1.0.0'
  pod 'M5Enum', '~> 1.1.0'
  pod 'M5SelectorMap', '~> 1.1.0'
  pod 'M5Dispatch', '~> 1.3.0'
  pod 'M5TypeSafety', '~> 1.1.0'
  pod 'M5KeyPath', '~> 1.0.0'

  pod 'SoundCloud-Cocoa-API', '~> 1.1.0'
  pod 'Spotify-iOS-SDK', '~> 0.8.0'
end

target :RAMediaMac do
  xcodeproj 'RAMedia/RAMedia.xcodeproj'
  platform :osx, '10.9'

  pod 'NSPointerArray+M5Additions', '~> 1.1.0'
  pod 'M5ApplicationMemoryWarning', '~> 1.1.0'
  pod 'M5ApplicationOpenURL', '~> 1.0.0'
  pod 'M5Enum', '~> 1.1.0'
  pod 'M5SelectorMap', '~> 1.1.0'
  pod 'M5Dispatch', '~> 1.3.0'
  pod 'M5TypeSafety', '~> 1.1.0'
  pod 'M5KeyPath', '~> 1.0.0'

  pod 'SoundCloud-Cocoa-API', '~> 1.1.0'
end

target :RAMediaExampleiOS do
  xcodeproj 'RAMediaExample/RAMediaExample.xcodeproj'
  platform :ios, '8.0'

  pod 'RAMedia', :path => './'
end

target :RAMediaExampleMac do
  xcodeproj 'RAMediaExample/RAMediaExample.xcodeproj'
  platform :osx, '10.9'

  pod 'RAMedia', :path => './'
end
```

thanks!

**Comment by dmueller39** [comment] 2015-09-22 17:13
@mhuusko5 we get around this by committing the Pods directory (which we were doing already). Its the responsibility of anyone calling `pod install` to ensure the project is in a compilable state then. Not sure if that helps you.

**Comment by C4Grey** [comment] 2015-09-25 12:33
I also had a similar issue(#4254) and setting the deduplicate_targets param to false is helpful, but it is increasing compilation time and it looks like a bit of hack...

**Comment by segiddins** [comment] 2015-09-25 14:32
@mrackwitz might this be fixed by either of your two PRs that improves deduplication?

**Comment by mrackwitz** [comment] 2015-09-25 14:39
Yes, this is a duplicate of #4034. Closed in favor of that one. It would be fixed by both. Feedback on #4146 and #4147 would be appreciated.

**Closed by mrackwitz** 2015-09-25 14:39 UTC
