### ISSUE TITLE
Use `git clone --progress` in verbose mode

### ISSUE THREAD

**Issue by phlippieb** [CocoaPods/CocoaPods#5937] opened 2016-09-23 07:23 UTC
> Before you start, are you using the CocoaPods beta release?
> a lot has changed with Xcode 8 that is not backwards compatible.
No

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod install --verbose`

## What did you expect to happen?

See useful information about the install process, specifically regarding downloads

## What happened instead?

Some pods install using `wget` and _do_ show download progress, which is nice if it looks like the install command got stuck. But for git clones, no progress is shown. Git 2.10 supports a `--progress` option, which will show download progress.

## CocoaPods Environment

Anything containing
```
pod 'AsyncDisplayKit'
```

**Comment by orta** [comment] 2016-09-23 07:25
There's a PR for this that ended up getting a bit lost by the wayside, https://github.com/CocoaPods/CocoaPods/pull/5297 you're welcome to try and take the mantle and finish it up? In the mean time, I'm going to close this issues as a dupe of that PR

**Closed by orta** 2016-09-23 07:25 UTC

**Comment by phlippieb** [comment] 2016-09-23 07:36
Cool! I'll clone and have a look.

**Comment by whalemare** [comment] 2023-03-11 10:30
<img width="1039" alt="Снимок экрана 2023-03-11 в 13 29 38" src="https://user-images.githubusercontent.com/9128731/224479268-4f0ee7de-5f1e-4ca3-aecf-d4b32ddbb83b.png">

So we still have no `--progress` flag when using `pod install --verbose` :(
