### ISSUE TITLE
Archive fails with code signing issue

### ISSUE THREAD

**Issue by seboslaw** [CocoaPods/CocoaPods#3156] opened 2015-02-17 12:53 UTC
Hey guys,

I'm trying to archive a new iOS 8.1 project that is mainly Swift and has 2 embedded frameworks (1 to wrap the API, 1 for custom controls). The Podfile for the project is as follows:

```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

target 'LingoJam' do
pod 'ReactiveCocoa', '2.4.4' # objc
pod 'SwiftyJSON', '2.1.3' #Swift
pod 'Alamofire', '~> 1.1.3' #Swift
pod 'Dollar', '~> 2.1.0' #Swift
pod 'Voltron', '~> 0.2.1' #objc
end

target 'LingoJamTests' do

end

target 'LingoJamFramework' do
    pod 'SwiftyJSON', '2.1.3' #Swift
    pod 'Dollar', '~> 2.1.0' #Swift
end

target 'LingoJamFrameworkTests' do    
    pod 'SwiftyJSON', '2.1.3' #Swift
    pod 'Dollar', '~> 2.1.0' #Swift
end
```
Since I want to use Apple's TestFlight (for now), the setup for my main project is:
- Code Signing Identity => iOS Developer
- Provisioning Profile => Automatic

I've tried using both 0.36.0.beta.1 and 0.36.0.beta.2, but neither succeeds in generating a Pods project that can be archived in XCode 6.1.1.
When trying to archive I get code signing errors like the following:

```
CodeSign /Users/svogelsang/Development/work/LingoJam/iOS/LingoJam/Build/Intermediates/ArchiveIntermediates/LingoJam/IntermediateBuildFilesPath/UninstalledProducts/Dollar.framework
    cd /Users/svogelsang/Development/work/LingoJam/iOS/LingoJam/Pods
    export CODESIGN_ALLOCATE=/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/codesign_allocate
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    
Signing Identity:     "iPhone Developer: Sebastian Vogelsang (N2F7M2B849)"

    /usr/bin/codesign --force --sign 9722FB761A6CA85426D200AEDA1D821A3CB6D902 /Users/svogelsang/Development/work/LingoJam/iOS/LingoJam/Build/Intermediates/ArchiveIntermediates/LingoJam/IntermediateBuildFilesPath/UninstalledProducts/Dollar.framework

/Users/svogelsang/Development/work/LingoJam/iOS/LingoJam/Build/Intermediates/ArchiveIntermediates/LingoJam/IntermediateBuildFilesPath/UninstalledProducts/Dollar.framework: No such file or directory
Command /usr/bin/codesign failed with exit code 1
```

**Comment by bassrock** [comment] 2015-02-20 01:31
:+1:  same issue here. As well on 6.2 beta with a watch kit app

**Comment by bassrock** [comment] 2015-02-21 03:32
I have found that it also may have something to do with permissions. I have tried on all versions of Xcode that apple has out right now:

```
/Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/lipo: can't move temporary file: /Users/daniel/Library/Developer/Xcode/DerivedData/TestApp-hjdhmoxqwxxmxtguevgikvldevvj/Build/Intermediates/ArchiveIntermediates/TestApp Release/IntermediateBuildFilesPath/UninstalledProducts/CryptoSwift.framework/CryptoSwift to file: /Users/daniel/Library/Developer/Xcode/DerivedData/TestApp-hjdhmoxqwxxmxtguevgikvldevvj/Build/Intermediates/ArchiveIntermediates/TestApp Release/IntermediateBuildFilesPath/UninstalledProducts/CryptoSwift.framework/CryptoSwift.lipo (No such file or directory)
```

This error I believe causes the code signing error because if I look at the build logs some of the Cocoapod frameworks do get signed. @seboslaw you getting this lipo error to?

**Comment by bassrock** [comment] 2015-02-21 03:35
And then If i run the failed command in my terminal window it runs fine. So either it must be running before the file exists in the build directory, would be my guess.

**Comment by neonichu** [comment] 2015-02-24 00:52
This sounds like some kind of Xcode issue :sob:  - CocoaPods does not run `lipo` by itself. Would be great if we could get a reproducable project for :satellite: if that is really the case.

**Comment by bassrock** [comment] 2015-02-24 00:54
I got it to work by removing all my cocopod frameworks from any target except my main app. So its something with using cocpoads frameworks on a framework. Will see if I can get a demo together tonight.

**Comment by neonichu** [comment] 2015-02-24 00:58
@bassrock awesome :+1:

**Comment by bassrock** [comment] 2015-02-24 07:21
can't seem to get ti to duplicate now. It may have been an issue switching between these 3 Xcode versions.

**Comment by bassrock** [comment] 2015-02-26 00:55
@neonichu so now I am able to reproduce it but to the extent of this original issue. Cocoapods sets the release code signing identity of all the pod frameworks to iOS Developer instead of iOS Distribution.

**Comment by kylef** [comment] 2015-03-02 18:40
This should be fixed by https://github.com/CocoaPods/CocoaPods/pull/3188 in CocoaPods 0.36.0.rc.1.

**Comment by Kurry** [comment] 2015-03-03 16:47
I still get this error with CocoaPods 0.36.0.rc.1.

**Comment by Kurry** [comment] 2015-03-03 18:25
This is definitely fixed in CocoaPods 0.36.0.rc.1., was able to create an adhoc ipa for a swift app using cocoapods and it ran on my phone.

**Comment by Kurry** [comment] 2015-03-03 21:43
@kylef can you leave this ticket open I think there is a separate but related issue?

**Comment by kylef** [comment] 2015-03-03 21:46
@Kurry If you wasn't talking about this issue, then what was you talking about when you said the following:

> **This is definitely fixed** in CocoaPods 0.36.0.rc.1

**Comment by Kurry** [comment] 2015-03-03 21:49
@kylef I'm not exactly sure its fixed if you have two identities with the same name in your keychain. I was going to verify that and get back to you. The code signing identity, seemed correct at first glance, but I'm not sure what happens when you have two identities with the same name.

**Comment by Kurry** [comment] 2015-03-03 21:52
@kylef Sorry I never answered your question. What I was saying was definitely fixed was that `CODE_SIGNING_IDENTITY` does change in the RC and does not keep the hardcoded value.

**Comment by Kurry** [comment] 2015-03-03 22:25
@kylef All set, I just tried archiving with each of my distribution signing identities with the same name, and it completed successfully on XCode 6.1.1.

**Comment by undrtone** [comment] 2015-03-04 06:25
Hi - we're also seeing this CodeSign error, with Cocoapods 0.36.0.rc.1 and Xcode 6.2 beta 5. It seems to occur with Swift frameworks (`use_frameworks!`) when two or more targets include the same CocoaPod with dependencies.  Debug builds run as expected, but Release builds (Archive) don't.

I made a [sample project](https://github.com/undrtone/LipoBugDemo) which reproduces the error, hope it is helpful.  Thanks -michael

**Comment by Kurry** [comment] 2015-03-04 18:21
@undrtone Have you ever seen an error like this? I'm trying to build this app for hockey app with an enterprise provisioning profile. It install correctly onto my phone but crashes on launch.

```
Mar  4 13:15:16 iPhone-5 kernel[0] <Notice>: xpcproxy[32555] Container: /private/var/mobile/Containers/Data/Application/924F56A7-E30A-4552-AB64-343CD8C54AA4 (sandbox)
Mar  4 13:15:16 iPhone-5 kernel[0] <Notice>: AMFI: SeatGuru(pid 32555) - [deny-mmap] mapped file has no team identifier and is not a platform binary: /private/var/mobile/Containers/Bundle/Application/F8A68AF5-1A46-4539-A5FC-6FD3E28AA8E3/SeatGuru.app/Frameworks/libswiftCore.dylib
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: task_set_exception_ports(B07, 400, D03, 0, 0) failed with error (4: (os/kern) invalid argument)
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Notice>: ReportCrash acting against PID 32555
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Notice>: Formulating crash report for process SeatGuru[32555]
Mar  4 13:15:16 iPhone-5 com.apple.xpc.launchd[1] (UIKitApplication:com.tripadvisor.taflights.SeatGuru[0x99af][32555]) <Notice>: Service exited due to signal: Trace/BPT trap: 5
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Not saving crash log because we have reached the limit for logs to store on disk.  Sync or otherwise clear logs from /var/mobile/Library/Logs/CrashReporter to save new logs.
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Could not save crash report to disk!
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Incident Identifier: 7A97A2E7-1B98-4D74-9FB0-662DE1B622BC
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: CrashReporter Key:   b5a23334cdfc9418855a2c9d3aed06dab3c6ce5d
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Hardware Model:      iPhone7,2
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Process:             SeatGuru [32555]
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Path:                /private/var/mobile/Containers/Bundle/Application/F8A68AF5-1A46-4539-A5FC-6FD3E28AA8E3/SeatGuru.app/SeatGuru
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Identifier:          SeatGuru
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Version:             ???
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Code Type:           ARM-64 (Native)
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Parent Process:      launchd [1]
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Date/Time:           2015-03-04 13:15:16.341 -0500
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Launch Time:         2015-03-04 13:15:16.317 -0500
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: OS Version:          iOS 8.1.3 (12B466)
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Report Version:      105
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Exception Codes: 0x0000000000000001, 0x00000001200dd088
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Triggered by Thread:  0
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Dyld Error Message:
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>:   Library not loaded: @rpath/libswiftCore.dylib
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>:   Referenced from: /private/var/mobile/Containers/Bundle/Application/F8A68AF5-1A46-4539-A5FC-6FD3E28AA8E3/SeatGuru.app/SeatGuru
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>:   Reason: no suitable image found.  Did find:
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 	/private/var/mobile/Containers/Bundle/Application/F8A68AF5-1A46-4539-A5FC-6FD3E28AA8E3/SeatGuru.app/Frameworks/libswiftCore.dylib: mmap() error 1 at address=0x100510000, size=0x0018C000 segment=__TEXT in Segment::map() mapping /private/var/mobile/Containers/Bundle/Application/F8A68AF5-1A46-4539-A5FC-6FD3E28AA8E3/SeatGuru.app/Frameworks/libswiftCore.dylib
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>:   Dyld Version: 353.9
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: Binary Images:
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x1200dc000 - 0x120103fff dyld arm64  <21c893f791653e989e1c3e15446d772b> /usr/lib/dyld
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x181d0c000 - 0x181d3afff Accounts arm64  <2508d336b9893176ad4e1bc67ff04188> /System/Library/Frameworks/Accounts.framework/Accounts
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x181d3c000 - 0x181d3cfff AdSupport arm64  <977faefc983d3d72ad5e531740e4130a> /System/Library/Frameworks/AdSupport.framework/AdSupport
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x1820dc000 - 0x182399fff AudioToolbox arm64  <f0b739a395993b808d66e85e1a6e9f18> /System/Library/Frameworks/AudioToolbox.framework/AudioToolbox
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x182538000 - 0x182743fff CFNetwork arm64  <68adcebf440d30769bd2d67adc7932a2> /System/Library/Frameworks/CFNetwork.framework/CFNetwork
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x182888000 - 0x182ac6fff CoreData arm64  <33c0d795a45e35c9affed5cf9d83a8a1> /System/Library/Frameworks/CoreData.framework/CoreData
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x182ac8000 - 0x182e24fff CoreFoundation arm64  <83a9627362333366a8543e8c2d28166e> /System/Library/Frameworks/CoreFoundation.framework/CoreFoundation
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x182e28000 - 0x182f8afff CoreGraphics arm64  <7a02a2d0b69f3706b3cb91726db6f8af> /System/Library/Frameworks/CoreGraphics.framework/CoreGraphics
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x183334000 - 0x183391fff CoreLocation arm64  <6fd7bd8116a63a8fafda547c6380a19b> /System/Library/Frameworks/CoreLocation.framework/CoreLocation
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x18355c000 - 0x1835cdfff CoreTelephony arm64  <f99cf601387938d3808c32e97a9a30cf> /System/Library/Frameworks/CoreTelephony.framework/CoreTelephony
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x1839cc000 - 0x183c20fff Foundation arm64  <e596bd80bcc83f15aca36a7ef014f457> /System/Library/Frameworks/Foundation.framework/Foundation
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x185398000 - 0x18546bfff MessageUI arm64  <f307aec0262838e1ad1302805c8a025c> /System/Library/Frameworks/MessageUI.framework/MessageUI
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x1854e0000 - 0x18558cfff MobileCoreServices arm64  <21a27692c6393c00a8f8f2bbd3ccb23c> /System/Library/Frameworks/MobileCoreServices.framework/MobileCoreServices
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x186ce4000 - 0x186e68fff QuartzCore arm64  <313aba56d17e30d1b68b2fdfda1820f8> /System/Library/Frameworks/QuartzCore.framework/QuartzCore
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x1870fc000 - 0x18714efff Security arm64  <cb64d037f82a3f0a92ab63708334c938> /System/Library/Frameworks/Security.framework/Security
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x187150000 - 0x1871dbfff Social arm64  <928581a049c3306abe816e5113d652ae> /System/Library/Frameworks/Social.framework/Social
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x187314000 - 0x187387fff SystemConfiguration arm64  <cbcb5237ab8637aebf0cb493aaa4af92> /System/Library/Frameworks/SystemConfiguration.framework/SystemConfiguration
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x18738c000 - 0x187d01fff UIKit arm64  <a1283daa6f5a33048ab9d29d91f62c09> /System/Library/Frameworks/UIKit.framework/UIKit
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x192820000 - 0x192821fff libSystem.B.dylib arm64  <882b19bba06d348d97fcdaf545163f47> /usr/lib/libSystem.B.dylib
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x192a9c000 - 0x192aacfff libbz2.1.0.dylib arm64  <f6ec1b6a4719369aa059ee3269823a2d> /usr/lib/libbz2.1.0.dylib
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x193330000 - 0x19352cfff libobjc.A.dylib arm64  <e6224d745a023588af8e5bb67498139a> /usr/lib/libobjc.A.dylib
Mar  4 13:15:16 iPhone-5 ReportCrash[32556] <Error>: 0x1938ec000 - 0x1938fdfff libz.1.dylib arm64  <2a347410b967358289e8256c913714de> /usr/lib/libz.1.dylib
Mar  4 13:15:16 iPhone-5 SpringBoard[53] <Warning>: Application 'UIKitApplication:com.tripadvisor.taflights.SeatGuru[0x99af]' crashed.
Mar  4 13:15:16 iPhone-5 wifid[5096] <Notice>: WiFi:[447185716.510914]: Async scan requested by "locationd" for 1 iterations with maxage=0 priority normal on en0
Mar  4 13:15:16 iPhone-5 wifid[5096] <Notice>: WiFi:[447185716.511266]: Enqueuing command type: "Scan" pending commands: 0
Mar  4 13:15:16 iPhone-5 wifid[5096] <Notice>: WiFi:[447185716.511415]: Dequeuing command type: "Scan" pending commands: 0
Mar  4 13:15:16 iPhone-5 wifid[5096] <Notice>: WiFi:[447185716.511517]: Attempting Apple80211ScanAsync on en0
Mar  4 13:15:16 iPhone-5 wifid[5096] <Notice>: WiFi:[447185716.974364]: Completed Apple80211ScanAsync on en0 (0)
Mar  4 13:15:16 iPhone-5 wifid[5096] <Notice>: WiFi:[447185716.978998]: Async scan request completed for "locationd" (0)
```

**Comment by orta** [comment] 2015-03-05 15:53
@undrtone thanks for the example project!

**Comment by shnhrrsn** [comment] 2015-03-28 21:09
I ran into this in a project where I had the same pod dep targeted to my main app and a shared framework.

I was able to workaround it by removing the targets from the shared framework + stripping all pod related settings from the framework's build settings and then having it link against the main app's pod framework.  This'll do for now, but IMO cocoapods should probably have logic to detect this scenario and share the framework between targets instead of duping them

**Comment by Maxim-38RUS-Zabelin** [comment] 2015-04-01 12:11
Hey guys,

It seems I've found a solution to the original issue: disabling 'Parallelize Build' gets the job done. As far as I see, assembled, any pod (framework) is always disposed in the same directory on the file system. Enabled, 'Parallelize Build' makes the Xcode share this directory among multiple threads; that's where the problem manifests itself: while one thread is compiling a binary, another one makes an attempt to execute 'codesign'.

Hope this helps.

**Comment by tannernelson** [comment] 2015-04-08 16:20
Any update on this?

I'm having the same issue when trying to Archive with this Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

link_with 'Decode', 'DecodeKit', 'Nearby'

target 'Decode' do
    pod 'BeckonKit', :path => '/Users/tanner/Blue Bite/beckon-kit/cocoapod'
    pod 'UriBeacon'
    pod 'Alamofire'
end

target 'DecodeKit' do
   pod 'Alamofire'
end

target 'Nearby' do
    pod 'UriBeacon'
    pod 'Alamofire'
end

post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        if !target.to_s.include? 'Pods-Decode-'
            puts target
            target.build_configurations.each do |config|
                config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'YES'
            end
        end
    end
end
```

**Comment by neonichu** [comment] 2015-04-08 17:33
@tannernelson have you tried turning of 'Parallelize Build' as suggested by @Maxim-38RUS-Zabelin?

**Comment by tannernelson** [comment] 2015-04-08 18:26
@neonichu Yes, that seems to have fixed it. It looks like a separate issue was getting in the way of that working earlier when I tried it.

Creating a new Xcode project, dragging my existing files over, and running `pod install` then turning off Parallelize Build worked in case anyone finds themselves in the same situation.

I can also confirm that re-enabling Parallelize Build caused archiving to start failing again with this error: 
```
/Users/tanner/Library/Developer/Xcode/DerivedData/Decode-genukxqntqxvstbnnsqprsmlajwb/Build/Intermediates/ArchiveIntermediates/Decode/IntermediateBuildFilesPath/UninstalledProducts/Alamofire.framework: main executable failed strict validation
Command /usr/bin/codesign failed with exit code 1
```

For anyone having difficulty finding Parallelize Build:
Product > Scheme > Edit Scheme > Select Build on the left > Build Options > Parallelize Build Off

Thanks @neonichu !

**Comment by apouche** [comment] 2015-05-14 12:28
I had the same issue described by OP and for only one target but I found a better workaround than disabling parallel builds (which actually didn't work for me). The issue was coming from the fact that the `CODE_SIGN_IDENTITY` was set to `iPhone Developer` which is no good for archiving.

adding:

```
post_install do |installer_representation|
    installer_representation.project.targets.each do |target|
        if target.to_s.include? 'Pods'
            target.build_configurations.each do |config|
            	if !config.to_s.include? 'Debug'
            		config.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = 'iPhone Distribution'
            	end
            end
        end
    end
end
```
to the `Podfile` solved the issue

**Comment by mwcbrent** [comment] 2015-05-30 22:43
I'm running into this issue as well with this:

```
platform :ios, '8.0'

target 'foo' do
  pod 'KikAPI'
  
  use_frameworks!
  pod 'HanekeSwift'
  pod 'ReactKit'
  pod 'SugarRecord/CoreData', :git => 'https://github.com/SugarRecord/SugarRecord.git'
end

target 'fooTests' do

end

target 'fooextension' do
    use_frameworks!
    pod 'HanekeSwift'
    pod 'ReactKit'
    pod 'SugarRecord/CoreData', :git => 'https://github.com/SugarRecord/SugarRecord.git'
end

```
Both my project and ReactKit use SwiftTask. Is that related in some way as @shnhrrsn experienced?  I'm not sure how to do what he did to resolve it.  I'm running 0.37.2.

**Comment by efremidze** [comment] 2015-06-20 03:15
I'm running into this issue too

**Comment by hborders** [comment] 2015-08-18 16:56
@apouche's solution worked for me, but I had to change it for 0.38.2. `project` -> `pods_project` [1].

```ruby
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.to_s.include? 'Pods'
            target.build_configurations.each do |config|
                if !config.to_s.include? 'Debug'
                    config.build_settings['CODE_SIGN_IDENTITY[sdk=iphoneos*]'] = 'iPhone Distribution'
                end
            end
        end
    end
end
```

[1] http://blog.cocoapods.org/CocoaPods-0.38/#breaking-change-to-the-hooks-api

**Comment by neonichu** [comment] 2015-08-19 17:44
Let's close this, as discussed in #3198, `post_install` is the right way to specify custom code signing settings.

**Closed by neonichu** 2015-08-19 17:44 UTC

**Comment by Exilz** [comment] 2018-10-11 08:56
Glad to see I'm not the only one struggling with this 3 years later.

**Comment by mennahmostafa** [comment] 2021-09-16 19:27
Still going on...6 years later!
