### ISSUE TITLE
0.38.1 - Erro when set 'OTHER_LDFLAGS' => '-lc++',

### ISSUE THREAD

**Issue by prsolucoes** [CocoaPods/CocoaPods#3894] opened 2015-07-24 18:43 UTC
Hi,

After update to cocoapods 0.38.1, we are getting error in pods that have the line:
```'OTHER_LDFLAGS' => '-lc++'```

The projects are created without this parameter(i checked it verifying diff between the two projects). When i use cocoapods 0.38.0 it is working nice. What the problem with cocoapods 0.38.1 when set this parameter?

The pods with error is:
https://github.com/AlexDenisov/iActiveRecord

The pod file with error is:
https://github.com/AlexDenisov/iActiveRecord/blob/master/iActiveRecord.podspec

Thanks.

**Comment by neonichu** [comment] 2015-07-25 00:02
Unfortunately, I can't reproduce this with a simple project using iActiveRecord, so we will need more information. Please give us the actual error you're seeing, the Podfile or ideally an example project which exhibits the issue.

**Comment by segiddins** [comment] 2015-07-26 05:14
Also, can you verify if the issue is still present in 0.38.2?

**Comment by neonichu** [comment] 2015-08-09 18:00
@prsolucoes closing for now, we can reopen if you give us the necessary information to reproduce.

**Closed by neonichu** 2015-08-09 18:00 UTC
Labels: s1:awaiting input
