### ISSUE TITLE
Swift Pod causes errors in Obj-C pod

### ISSUE THREAD

**Issue by WCByrne** [CocoaPods/CocoaPods#3097] opened 2015-02-02 16:49 UTC
I am fairly new to creating Pods and it seems doing so with swift is still being worked out. I have my pod building correctly and working in a test project but it seems to be causing conflicts with other pods in the same project. 

Without any swift pods added everything builds fine. After adding one, running pod update, and building again, I get errors in some of the other pods. 

For some details, Two pods that *get* the errors are [pubNub](https://github.com/pubnub/objective-c) and [Parse-UI](https://github.com/ParsePlatform/ParseUI-iOS). I tried my swift pod and [SwiftyJSON](https://github.com/SwiftyJSON/SwiftyJSON/tree/master/Source) and both are *causing* the compile errors in the other two. Parse-UI for example gets a number of undefined symbols for some of their static variables.

In a project that is not using Parse-UI or PubNub, I am able to use my pod just fine. 

Not sure if this is an error on the Swift pod or an error in CocoaPods.

**Comment by segiddins** [comment] 2015-02-02 17:00
It's likely errors with the pods that are unable to compile as frameworks.

**Comment by WCByrne** [comment] 2015-02-02 17:08
What would that be in this case? They all work individually but when combined errors start popping up. I'm also seeing a compile error 'Ambiguous use of function' for any uses of a class extension in my pod. It's as if it is getting access to 2 copies of the class and not sure which to use.

**Comment by lammertw** [comment] 2015-02-05 07:00
I'm also having problems like this. I created a test project for this: https://github.com/lammertw/PodTests

It's having the Alamofire as Swift framework. Without it, it works fine. But with it I get errors with Parse-UI:
```
Undefined symbols for architecture arm64:
  "_kPFErrorInvalidEmailAddress", referenced from:
      -[PFSignUpViewController _signUpDidFailWithError:] in PFSignUpViewController.o
  "_kPFErrorUsernameMissing", referenced from:
      -[PFSignUpViewController _signUpDidFailWithError:] in PFSignUpViewController.o
  "_kPFErrorUserEmailTaken", referenced from:
      -[PFSignUpViewController _signUpDidFailWithError:] in PFSignUpViewController.o
  "_OBJC_CLASS_$_Parse", referenced from:
      objc-class-ref in PFQueryCollectionViewController.o
      objc-class-ref in PFQueryTableViewController.o
  "_kPFErrorCacheMiss", referenced from:
      ___53-[PFQueryCollectionViewController loadObjects:clear:]_block_invoke in PFQueryCollectionViewController.o
      ___48-[PFQueryTableViewController loadObjects:clear:]_block_invoke in PFQueryTableViewController.o
  "_OBJC_CLASS_$_PFProduct", referenced from:
      objc-class-ref in PFProductTableViewController.o
     (maybe you meant: _OBJC_CLASS_$_PFProductTableViewController)
  "_kPFErrorUsernameTaken", referenced from:
      -[PFSignUpViewController _signUpDidFailWithError:] in PFSignUpViewController.o
  "_kPFErrorUserEmailMissing", referenced from:
      -[PFSignUpViewController _signUpDidFailWithError:] in PFSignUpViewController.o
  "_OBJC_CLASS_$_PFTwitterUtils", referenced from:
      objc-class-ref in PFLogInViewController.o
  "_OBJC_CLASS_$_PFQuery", referenced from:
      objc-class-ref in PFQueryCollectionViewController.o
      objc-class-ref in PFQueryTableViewController.o
     (maybe you meant: _OBJC_CLASS_$_PFQueryCollectionViewController, _OBJC_CLASS_$_PFQueryTableViewController )
  "_OBJC_CLASS_$_PFUser", referenced from:
      objc-class-ref in PFLogInViewController.o
      objc-class-ref in PFSignUpViewController.o
  "_OBJC_CLASS_$_PFPurchase", referenced from:
      objc-class-ref in PFProductTableViewController.o
     (maybe you meant: _OBJC_CLASS_$_PFPurchaseTableViewCell)
  "_kPFErrorUserPasswordMissing", referenced from:
      -[PFSignUpViewController _signUpDidFailWithError:] in PFSignUpViewController.o
  "_OBJC_CLASS_$_BFTaskCompletionSource", referenced from:
      objc-class-ref in PFImageView.o
  "_kPFErrorInvalidImageData", referenced from:
      ___32-[PFImageView loadInBackground:]_block_invoke30 in PFImageView.o
  "_kPFErrorUnsavedFile", referenced from:
      -[PFImageView loadInBackground:] in PFImageView.o
  "_PFParseErrorDomain", referenced from:
      -[PFImageView loadInBackground:] in PFImageView.o
      ___32-[PFImageView loadInBackground:]_block_invoke30 in PFImageView.o
      -[PFSignUpViewController _signUpAction] in PFSignUpViewController.o
      -[PFSignUpViewController _signUpDidFailWithError:] in PFSignUpViewController.o
ld: symbol(s) not found for architecture arm64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by neonichu** [comment] 2015-02-05 08:52
The issues with Parse are very likely the same as #3106, as it is also distributed as a `vendored_framework`.

**Comment by neonichu** [comment] 2015-02-05 09:03
FWIW, pubNub lints just fine as a framework.

@WCByrne Please add more information to this ticket, like the actual errors you are seeing regarding pubNub, Podfiles, example project, etc.

**Comment by kylef** [comment] 2015-02-21 17:34
Closing as a duplicate of #3106.

**Closed by kylef** 2015-02-21 17:34 UTC
Labels: Frameworks, s1:awaiting input
