### ISSUE TITLE
Resource "XXXX.bundle" not found. Run 'pod install' to update the copy resources script.

### ISSUE THREAD

**Issue by JayZhao** [CocoaPods/CocoaPods#4984] opened 2016-03-05 16:59 UTC
# Report

## What did you do?

After I updated to **1.0.0.beta.4** and **clean the project's derived data**, this error raised and can not be fixed by running 'pod install'.

## What did you expected to happen?

Everything should be OK

## What happened instead?

error: Resource "/Users/XXXXX/Library/Developer/Xcode/DerivedData/XXXXX-hbmmkyekecifpxgniimqcqsczuqn/Build/Products/Debug-iphonesimulator/MWPhotoBrowser.bundle" not found. Run 'pod install' to update the copy resources script.

I've tested and found out that **all resource bundles are not working**.

## Podfile

platform :ios, '8.1'

inhibit_all_warnings!

target 'XXXXX' do
    pod 'AFNetworking'
    pod 'NSDictionary+Accessors'
    pod 'SDWebImage'
    pod 'LiveFrost'
    pod 'TSMessages'
    pod 'FormatterKit'
    pod 'iRate'
    pod 'SocketRocket'
    pod 'CargoBay'
    pod 'MWPhotoBrowser'
    pod 'NZCircularImageView'
    pod 'JTNumberScrollAnimatedView'
    pod 'SCLAlertView-Objective-C'
    pod 'Adjust'
    pod 'PopoverView'
    pod 'Appsee'
    pod 'SGNavigationProgress'
    pod 'SVPullToRefresh'
    pod 'AMPopTip'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'MZFormSheetPresentationController'
    pod 'TCMobileProvision'
    pod 'JSBadgeView'
    pod 'JSQMessagesViewController', :git => 'https://github.com/jessesquires/JSQMessagesViewController.git', :branch => 'develop'
    pod 'QBImagePickerController'
end

**Comment by segiddins** [comment] 2016-03-06 22:07
@mrackwitz is this a duplicate of the other resource issues found in beta 4?

**Comment by appveng3r** [comment] 2016-03-09 06:36
@segiddins sounds to me like it. It looks similar to #4963

**Closed** 2016-03-09 14:02 UTC
