### ISSUE TITLE
📦  is causing FileMerge to no longer work.

### ISSUE THREAD

**Issue by TheGuardian117** [CocoaPods/CocoaPods#5374] opened 2016-05-19 21:46 UTC
My team just updated to cocoapods version 1.0. I was on a side branch at the time. I merged develop into my side branch, when I noticed a merge conflict with project.pbxproj. After hitting "Launch External Merge Tool" the FileMerge popup appears, but the FileMerge application is not responding. Nothing I do can make it work with FileMerge. Another member of my team used a different merge tool, and that didn't cause any issues. I think the emojiis breaking FileMerge.

I found that this feature was added with this pull request https://github.com/CocoaPods/CocoaPods/pull/4985. 

I would recommend removing the code that added this feature.

**Comment by samdmarshall** [comment] 2016-05-19 22:34
From what I understand of your issue, this isn't a problem with CocoaPods but a failure of the FileMerge utility. If you have a reproduction case then I strongly recommend that you file a radar with Apple about it. The fact that there is emoji in the file seems purely coincidental because in-fact, FileMerge performs a comparison on the file no different from the comparison action it does against your source files. The `pbxproj` file itself does support emoji and unicode as denoted at the top of the file marking it as UTF-8 encoding. With that information in hand I don't understand how this is a CocoaPods problem that necessitates a revert of the commit that was made to add this in the first place.

**Comment by TheGuardian117** [comment] 2016-05-19 23:24
You are correct that it is a failure of FileMerge. After doing more research on the problem, I've found out that this happens when a line with an emoji is the line that has a conflict. It doesn't matter what the emoji is. The problem that this causes is that for people just updating (like myself) who are working on a team (like myself) may have a merge conflict on this file. After they upgrade, there shouldn't be a problem. 

Now, I realize that if the repo get's updated to remove the emoji, this issue might still come up for other people while merging back. Honestly, I'm surprised that no one else brought this issue up in the past few months since 1.0's been released. 

I agree that this is also an Apple issue, and until they can fix the issue, and give the changes to us, more people using cocoapods may be affected by this issue. It's a very obscure issue, and while googling this issue, there was absolutely no information as to why FileMerge was suddenly broken. If I didn't notice the emoji while looking at what's changed in Source Tree, I would have lost money more work hours trying to figure out why my branch is broken, and the rest of my teams branches aren't.

What you guys do with this information is up to you. My team has added a script that removes the project, so we can move forward unaffected by what you guys decide. But other people might have problems too. And it's a breaking problem.

**Comment by samdmarshall** [comment] 2016-05-20 19:42
To leave a record for anyone else that runs into this issue: I filed a radar last week on this issue (though I didn't know it at the time) as rdar://26267762 where I submitted sample files that reproduce the issue.

**Comment by TheGuardian117** [comment] 2016-05-20 20:23
I also created a bug report for Apple. I don't know if/when they're going to fix this issue.

**Comment by samdmarshall** [comment] 2016-05-20 21:01
Thank you! I really hope this gets fixed soon, I'm starting to use Kaleidoscope in the mean time.

**Comment by segiddins** [comment] 2016-05-23 16:55
This has been changed on master.

**Closed by segiddins** 2016-05-23 16:55 UTC

**Comment by AliSoftware** [comment] 2016-05-23 20:22
For reference the associated PR fixing it is #5382
