### ISSUE TITLE
Xcode7.3 dyld: Library not loaded

### ISSUE THREAD

**Issue by tonespy** [CocoaPods/CocoaPods#5183] opened 2016-04-21 11:44 UTC
I've been working on my Simulator throughout the development of my App, then I decided to make my test on iOS devices. Then, I started running into this

    dyld: Library not loaded: @rpath/AFNetworking.framework/AFNetworking
    Referenced from: /var/containers/Bundle/Application/D204992A-FBED-4E71-A2F7-6EDF6E63D4C0/App.app/App
    Reason: no suitable image found.  Did find:
	/private/var/containers/Bundle/Application/D204992A-FBED-4E71-A2F7-6EDF6E63D4C0/App.app/Frameworks/AFNetworking.framework/AFNetworking: mmap() errno=1 validating first page of '/private/var/containers/Bundle/Application/D204992A-FBED-4E71-A2F7-6EDF6E63D4C0/App.app/Frameworks/AFNetworking.framework/AFNetworking'

And after looking through many SO questions and gone through `cocoapod's`github gists which were all based on Last year's posts, so I updated my cocoapods to the beta 1.0.0Beata-8 and then I started having a `Parsefacebookutils` header errors in my Xcode7.3. So, I disabled bitcode, and set Non-Modular to yes and the error persists, so I switch back to the stable 0.39 of `Cocoapods` and I'm back here. I added `Pods framework` to the `Embedded Frameworks` in my App Target. Checked my `Build Phases` for `📦 Check Pods Manifest.lock, 📦 Embed Pods Frameworks, 📦 Copy Pods Resources` they exist. My `Runpath Search Paths` has `@executable_path/Frameworks` in it. And I've cleared my derived data too. So, I'm confused on what I need to do

     platform :ios, '9.3'
     # Uncomment this line if you're using Swift
     !use_frameworks!
     inhibit_all_warnings!

     #link_with 'MyApp'
     target 'MyApp' do
        pod 'Parse'
        pod 'ParseFacebookUtilsV4'
        pod 'FBSDKCoreKit'
        pod 'FBSDKLoginKit'
        pod 'FBSDKShareKit'
        pod 'Crashlytics'
        pod 'Stripe'
        pod 'Fabric'
        pod 'AFNetworking'
        pod 'SDWebImage'
        pod 'IDMPhotoBrowser'#, :git => 'git://github.com/netherlol/IDMPhotoBrowser.git'
        pod 'BlocksKit'
        pod 'DKImagePickerController' , "~> 2.4.3"
        pod 'DateTools'
        pod 'JSQMessagesViewController'
        pod "CreditCardValidator"
        pod "RappleProgressHUD"
      end

      target 'MyAppTests' do

      end

      target 'MyAppUITests' do

       end

**Comment by neonichu** [comment] 2016-04-21 13:03
Sounds like a duplicate of #4294, which turned out to be a code signing issue. If it turns out that isn't the case, please share an Xcode project which reproduces the issue.

**Closed by neonichu** 2016-04-21 13:03 UTC
