### ISSUE TITLE
Change to development pods do not support incremental build

### ISSUE THREAD

**Issue by siuying** [CocoaPods/CocoaPods#8898] opened 2019-06-12 06:58 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Create a project integrated with cocoapods, using "development" pods. 

Change source code of  "development" pods and then run the project.

## What did you expect to happen?

Development pods change should be reflected to the simulator.

## What happened instead?

Development pods change are not reflected until we do a clean build.

*This problem only happens with "New Build System" enabled.*

Based on Xcode logs, the changed code do seems recompiled, the copy framework script do seems do something. 

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/siuying/.rvm/rubies/ruby-2.6.3/lib
Repositories : cocoapods - https://github.com/CocoaPods/Old-Specs @ 6e256ccc84aad851d401fabb79b2c0f9e09bb875
               master - https://github.com/CocoaPods/Specs.git @ cccfd675d046639849151ece0e4c6fd67458b113
```

### Installation Source

```
Executable Path: /Users/siuying/.rvm/gems/ruby-2.6.3/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '12.0'

target 'IncrementalChange' do
  use_frameworks!

  pod 'Utils', :path => './Utils/'
  pod 'SwiftProtobuf'
end
```

## Project that demonstrates the issue

To test the problem, download the project and make sure "New Build System" is being used. Then try to run the project. Console should print some message.

Then make change to `Greeter.swift` in the workspace (e.g. change the value printed) and run the project again.

Expected: We see the change being reflected.
Actual: The change do not seems reflected until we do a clean build.

- [A sample project to demonstrate this issue](https://github.com/CocoaPods/CocoaPods/files/3279955/IncrementalChange.zip)
- [A similar project without cocoapods](https://github.com/CocoaPods/CocoaPods/files/3279934/IncrementalChangeSimple.zip)

**Comment by dnkoutso** [comment] 2019-06-12 07:40
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/8073.

Bug in Xcode, turn off input_output_paths

**Closed by dnkoutso** 2019-06-12 07:40 UTC

**Comment by siuying** [comment] 2019-06-12 09:57
thanks a lot
