### ISSUE TITLE
multiple Groups and duplicate UUID with watchOS 2 project

### ISSUE THREAD

**Issue by seboslaw** [CocoaPods/CocoaPods#4326] opened 2015-10-06 11:12 UTC
Hey guys,

I tried setting up a brand new watchOS 2 project (incl. parent iOS app), but ran into some trouble with Cocoapods (0.39.rc.1). 

Consider the following Podfile:

```
# Uncomment this line to define a global platform for your project
platform :ios, '8.4'
# Uncomment this line if you're using Swift
use_frameworks!


target 'cocoapodsTest' do
  pod 'ReactiveCocoa', '2.4.7'
  pod 'PSUpdateApp'
  pod 'Alamofire'
end

target 'cocoapodsTestUITests' do

end

target 'cocoapodsTest WatchKit App' do

end

target 'cocoapodsTest WatchKit Extension' do
    platform :watchos, '2.0'
    pod 'Alamofire'
end
```
Running pod install I get the following:

```
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (2.6.0)
Installing Alamofire (2.0.2)
Installing PSUpdateApp (2.0.5)
Installing ReactiveCocoa (2.4.7)
Generating Pods project
2015-10-06 13:07:13.175 ruby[54907:498303] warning:  The file reference for "Alamofire.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
Integrating client project

[!] Please close any current Xcode sessions and use `cocoapodsTest.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There are 3 dependencies from the Podfile and 4 total pods installed.

[!] [Xcodeproj] Generated duplicate UUIDs:

PBXFileReference -- /mainGroup/children/children:displayName:AFNetworking.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:AFNetworking.framework,path:AFNetworking.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Alamofire.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Alamofire.framework,path:Alamofire.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Alamofire.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Alamofire.framework,path:Alamofire.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_cocoapodsTest.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_cocoapodsTest.framework,path:Pods_cocoapodsTest.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_cocoapodsTest_WatchKit_Extension.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_cocoapodsTest_WatchKit_Extension.framework,path:Pods_cocoapodsTest_WatchKit_Extension.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:PSUpdateApp.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:PSUpdateApp.framework,path:PSUpdateApp.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:ReactiveCocoa.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:ReactiveCocoa.framework,path:ReactiveCocoa.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Products,isa:PBXGroup,name:Products,sourceTree:<group>,/Products/children/displayName:Alamofire.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Alamofire.framework,path:Alamofire.framework,sourceTree:BUILT_PRODUCTS_DIR,/Products/Alamofire.framework
```

What's the way to make this work?

**Comment by segiddins** [comment] 2015-10-06 14:29
Those should all only be warnings, so everything should still be working

**Comment by seboslaw** [comment] 2015-10-06 14:48
Hm, upon archiving I get the following message within XCode:

```
/Users/me/test/cocoapodsTest/Pods/<module-includes>:1:1: Umbrella header for module 'Alamofire' does not include header 'Pods-cocoapodsTest WatchKit Extension-Alamofire-umbrella.h'
```
Within in the console I see:
```
06.10.15 16:45:58,145 Xcode[1499]: Cannot make directory /Users/me/Library/Developer/Xcode/Archives/2015-10-06/cocoapodsTest 06.10.15, 16.45.xcarchive/dSYMs/Alamofire.framework.dSYM: File exists
```

**Comment by neonichu** [comment] 2015-10-07 19:08
have you turned off target deduplication by any chance?

**Comment by seboslaw** [comment] 2015-10-07 20:54
Hey @neonichu, I just tried rebuilding with your sample project (native-watchOS-example). With target reduplication turned off I get the same error as mentioned above when running `pod install`.
When trying to archive, instead of building and not opening the Organizer, I now get errors like:

```
ld: building for watchOS, but linking against dylib built for iOS, file '/Users/svogelsang/Library/Developer/Xcode/DerivedData/watchOSsample-edkvasdtczykwgftgcjlvvkynfvt/Build/Intermediates/ArchiveIntermediates/watchOSsample/BuildProductsPath/Release-watchos/Pods-watchOSsample WatchKit Extension/Alamofire.framework/Alamofire' for architecture armv7k
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by neonichu** [comment] 2015-10-07 21:41
@seboslaw yep, I was asking because it needs to be turned on (default) to work properly with extensions.

**Comment by seboslaw** [comment] 2015-10-07 21:43
ah, ok. Well with it turned on I get the results described at the top of this thread ;)

**Comment by Arclite** [comment] 2015-10-08 06:00
I'm seeing similar results on 0.39.rc.1. Both warnings go away if I disable deterministic UUIDs (`COCOAPODS_DISABLE_DETERMINISTIC_UUIDS`). I can attach my Podfile/podspec (I'm using a locally-installed pod) if it helps.

**Comment by segiddins** [comment] 2015-10-08 06:42
Yeah, to debug duplicate UUID bugs a sample project is necessary, but unfortunately those are kind of at the bottom of my todo list at the moment.

**Comment by neonichu** [comment] 2015-10-08 08:02
@seboslaw not really, the watch sample project works just fine for me

**Comment by seboslaw** [comment] 2015-10-08 08:30
@neonichu hm....so without any modifications you don't get the warnings above when doing `pod install` and you're able to archive without any problems?

**Comment by swissdev** [comment] 2015-10-12 09:17
We are currently experience the same issue and can't archive the project now.. We have a project with an extension and a watchos 2 app. ...dSym: File exists..

**Comment by swissdev** [comment] 2015-10-12 11:39
After hours of trial and error... The problem occurs when adding a Watch Extension Target in the podfile. It doesn't work anymore. If we remove the extension target everything works fine.. But we need some pods in the extension..

This works:
target 'Landi-Watch Extension' do
    platform :watchos, '2.0'
end

This not:
target 'Landi-Watch Extension' do
    platform :watchos, '2.0'
    pod 'Alamofire', '~> 2.0'
end

**Comment by iGranDav** [comment] 2015-10-16 12:04
Hey guys,

Managed to reproduce it with tvOS. Added a demo project to help.
https://github.com/iGranDav/CocoaPods_Issue-4326

Please re-open this issue

**Comment by Spacelapp** [comment] 2015-11-09 21:42
Same problem......

**Comment by buithuyen** [comment] 2016-01-11 09:06
Same for me

```ruby
use_frameworks!

def shared_pods
pod 'AFNetworking'
end

target 'WatchPod' do
platform :ios, '9.0'
shared_pods
end

target 'WatchApp Extension' do
platform :watchos, '2.0'
shared_pods
end
```

```ruby
CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
2016-01-11 16:03:08.452 ruby[23276:1660954] warning:  The file reference for "AFNetworking.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
Removing Mantle
Downloading dependencies
Using AFNetworking (3.0.4)
Generating Pods project
Integrating client project
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

[!] [Xcodeproj] Generated duplicate UUIDs:

PBXFileReference -- /mainGroup/children/children:displayName:AFNetworking.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:AFNetworking.framework,path:AFNetworking.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:AFNetworking.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:AFNetworking.framework,path:AFNetworking.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_WatchApp_Extension.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_WatchApp_Extension.framework,path:Pods_WatchApp_Extension.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_WatchPod.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_WatchPod.framework,path:Pods_WatchPod.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Products,isa:PBXGroup,name:Products,sourceTree:<group>,/Products/children/displayName:AFNetworking.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:AFNetworking.framework,path:AFNetworking.framework,sourceTree:BUILT_PRODUCTS_DIR,/Products/AFNetworking.framework
```

**Comment by manuelmarcos** [comment] 2016-01-14 17:14
:+1: Same problem here as @buithuyen

**Comment by segiddins** [comment] 2016-01-14 17:24
Can any of y'all see if this is fixed in the 1.9 beta? I'm fairly sure it is.

**Comment by manuelmarcos** [comment] 2016-01-14 18:22
I am sorry @segiddins  but I actually just tried in a brand new project using pod version 0.39.0 and it all worked fine.
The pod file looks like this:
```
source 'https://github.com/CocoaPods/Specs.git'
# Podfile

def shared_pods
    pod 'Alamofire', '~> 3.0'
end
 
target 'ribotTeam' do
    platform :ios, '9.0'
    use_frameworks!
    shared_pods
end
 
target 'ribotTeamtvOS' do
    platform :tvos, '9.0'
    use_frameworks!
    shared_pods
end
```

I believe this solution should also be valid for @buithuyen , @Spacelapp and @iGranDav ...

Cheers.

**Comment by buithuyen** [comment] 2016-01-15 02:15
@manuelmarcos :+1: It works for me as below:

```
target 'AppDemo' do
pod 'Realm','0.94.1'
pod 'AFNetworking','2.6.3'
pod 'SDWebImage'
end

target 'Watch Extension' do
use_frameworks!
platform :watchos, '2.0'
pod 'Realm','0.94.1'
pod 'AFNetworking','2.6.3'
end
```

**Comment by manuelmarcos** [comment] 2016-01-15 09:59
Glad to hear it is working for you @buithuyen 
Perhaps we can close this issue? @AliSoftware ? 
Thanks guys!

**Comment by iGranDav** [comment] 2016-01-15 10:47
This works perfectly for me also guys thanks! :+1:

**Closed** 2016-01-15 10:49 UTC
Labels: s2:confirmed

**Comment by cobear25** [comment] 2016-02-11 23:46
I have the same problem but I don't see what's wrong with my podfile:
```
source 'https://github.com/CocoaPods/Specs.git'

def common_pods
  pod 'Alamofire', '~> 3.0'
  pod 'Raven', :git => 'https://github.com/getsentry/raven-objc.git', :tag => '1.0.1'
  pod 'SwiftyJSON', :git => 'https://github.com/SwiftyJSON/SwiftyJSON.git'
  pod 'SDWebImage', '~> 3.7.5'
  pod 'JSQCoreDataKit'
  pod 'MBProgressHUD', :git => 'https://github.com/smejkpa7/MBProgressHUD.git'
end

target 'Proj' do
  use_frameworks!
  platform :ios, '8.0'
  common_pods
end

target 'ProjTvOS' do
  use_frameworks!
  platform :tvos, '9.0'
  common_pods
end
```

**Comment by manuelmarcos** [comment] 2016-02-12 10:10
Hey! Lets see if we can fix this. Few questions @cobear25 

1.- Are you sure that all common pods support both platforms?
2.- Are you sure your targets names are exactly the same as define in Xcode?
3.- Are you running the latest version of cocoapods?
4.- Could you paste some more info? (Stack trace error) 

Cheers

**Comment by FelixII** [comment] 2016-02-13 14:50
I'm having the same problem with CocoaPods 0.39.0, which leads to a linker error upon archiving the app (build runs fine). Here's my podfile:

	source 'https://github.com/CocoaPods/Specs.git'
	use_frameworks!

	target 'App' do
		platform :ios, '8.2'
		pod 'Fabric'
		pod 'Crashlytics'
		pod 'RealmSwift'
	end

	target 'Watch Extension' do
		platform :watchos, '2.0'
		pod 'RealmSwift'
	end

Adding "RealmSwift" to my watch extension causes my today and share extensions to fail linking:

    ld: framework not found Realm for architecture armv7
    clang: error: linker command failed with exit code 1 (use -v to see invocation)

Upgrading to CocoaPods 1.0.0 beta3 resolves the error messages in CocoaPods, but this version is unfortunately not yet compatible with Realm, see https://github.com/realm/realm-cocoa/issues/3052

**Comment by JanGorman** [comment] 2016-02-17 13:24
Same issue here and CocoaPods beta doesn't fix this either. It starts popping up as soon as I add `use_frameworks!` to one of the targets. I cannot set all targets to `use_frameworks!` because the iOS `target has transitive dependencies that include static binaries`. 

Consider the following simplified example:

```ruby
def common_pods
  pod 'AFNetworking`
end

target `iOS` do
  common_pods
  …
end

target `tvOS` do
  use_frameworks! #as soon as I add this here, I get the warning about multiple groups. Without this, it works fine
  common_pods
  …
end
```
