### ISSUE TITLE
XCFrameworks slice selection fails in multiple ways

### ISSUE THREAD

**Issue by lowip** [CocoaPods/CocoaPods#10026] opened 2020-09-02 18:41 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Integrating a pod distributed as a xcframework.

## What did you expect to happen?

The xcframework pod to be handled properly by Cocoapods and for the target to compile without errors.

## What happened instead?

The shell script generated by [copy_xcframework_script.rb](https://github.com/CocoaPods/CocoaPods/blob/1.10.0.beta.2/lib/cocoapods/generator/copy_xcframework_script.rb) does not handle all xcframeworks correctly. 

### Example 1
Given the following xcframework:
```
SampleXCFramework.xcframework
├── Info.plist
├── ios-arm64
│   └── SampleXCFramework.framework
│       └── ...
└── ios-arm64_x86_64-simulator
    └── SampleXCFramework.framework
        └── ...
```
When compiling on a device or using the _Any iOS Device_ destination. The pod's `copy_xcframework_script.rb` will select the simulator slice instead of the device slice.

<img width="664" alt="Screen Shot 2020-09-02 at 2 13 57 PM" src="https://user-images.githubusercontent.com/503337/92020808-bb970c00-ed26-11ea-8bdb-812230114234.png">

This leads to the following compilation error on the target:
```
Building for iOS, but linking in dylib file (.../SampleXCFramework.framework/SampleXCFramework) built for iOS Simulator, file '.../SampleXCFramework.framework/SampleXCFramework' for architecture arm64
```

### Example 2

Given the following xcframework:

```
AppboyKit.xcframework
├── Info.plist
├── ios-arm64_armv7
│   ├── Headers
│   │   └── ...
│   └── libAppboyKitLibrary.a
└── ios-arm64_i386_x86_64-simulator
    ├── Headers
    │   └── ...
    └── libAppboyKitLibrary.a
```
When compiling on a device or using the _Any iOS Device_ destination. The pod's `copy_xcframework_script.rb` will fail to select a slice in the xcframework:
```
[CP] Unable to find matching .xcframework slice in '.../AppboyKit.xcframework AppboyKit library ios-arm64_i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (armv7 arm64).
```
As you can see, the slice `ios-arm64_armv7` contains all the architectures needed (`armv7 arm64`). The script fails to select this slice due to the following regex:
```bash
# This regex matches all possible variants of the arch in the folder name:
# Let's say the folder name is: ios-armv7_armv7s_arm64_arm64e/CoconutLib.framework
# We match the following: -armv7_, _armv7s_, _arm64_ and _arm64e/.
# If we have a specific variant: ios-i386_x86_64-simulator/CoconutLib.framework
# We match the following: -i386_ and _x86_64-
local target_arch_regex="[_\-]${target_arch}[\/_\-]"
```
That regex fails to match the target architecture in the string `ios-arm64_armv7`. A possible fix for that regex is: 
```bash
"[_\-]${target_arch}([\/_\-]|$)"
```

### Notes
In both examples, the xcframeworks were:
- generated using _Xcode 12 beta 6_
- tested and work correctly when integrated manually into an Xcode project

### Stack

```
   CocoaPods : 1.10.0.beta.2
        Ruby : ruby 2.6.1p33 (2019-01-30 revision 66950) [x86_64-darwin19]
    RubyGems : 3.0.1
        Host : Mac OS X 10.15.6 (19G2021)
       Xcode : 12.0 (12A8189n)
         Git : git version 2.28.0
Ruby lib dir : /Users/louis.bur/.rbenv/versions/2.6.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ a73178d31cff733dba361b7b9332648ff995121d

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/louis.bur/.rbenv/versions/2.6.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '14.0'
project 'SampleApp.xcodeproj'

target :SampleApp do
  pod 'SampleXCFramework', :path => './'
end
```

## Project that demonstrates the issue

[Example 1 - SampleXCFramework.zip](https://github.com/CocoaPods/CocoaPods/files/5164152/SampleXCFramework.zip)
[Example 2 - AppboyKit.xcframework.zip](https://drive.google.com/file/d/1-DI6O0pfUPlZfhpy82kzZp_-WKSaHtF7/view?usp=sharing)

**Comment by dnkoutso** [comment] 2020-09-02 18:43
Yes! great issue report. If we need to update the regex care to open a PR for it? Target branch `1-10-stable` so it ships with 1.10.x

**Comment by dnkoutso** [comment] 2020-09-02 18:46
@lowip also would be awesome to expand our test surface area with the sample xcframeworks to ensure no regressions.

**Comment by lowip** [comment] 2020-09-02 20:47
@dnkoutso I'm preparing a PR.

**Comment by dnkoutso** [comment] 2020-09-11 18:49
This was merged.

**Closed by dnkoutso** 2020-09-11 18:49 UTC
Labels: t2:defect

**Comment by trevinwisaksana** [comment] 2020-12-01 02:15
I believe this bug or at least a variation of it might still be occurring. I'm getting a build issue **only on my Development configuration** because Cocoapods is selected the wrong slice of the XCFramework. 

<img width="975" alt="Screen Shot 2020-12-01 at 09 07 38" src="https://user-images.githubusercontent.com/20000813/100688390-d116e300-33b4-11eb-89a4-1e4271405d3b.png">

It correctly selected the correct slice at first as shown on the logs. But then notice that it's still looking for the x86_64 architecture in the ios-arm64_armv7 folder.
`missing required architecture x86_64 in file Pods/Crisp/Crisp.xcframework/ios-arm64_armv7/Crisp.framework/Crisp (2 slices)`

I'm using Xcode 12.2 to generate this.

**Comment by ManueGE** [comment] 2020-12-03 17:56
We have the same problem. The simulator tries to build using `x86_64` and won't build.

**Comment by perrosnk** [comment] 2020-12-18 11:46
@trevinwisaksana Did you find a solution to that?

**Comment by ManueGE** [comment] 2020-12-18 11:50
@perrosnk 

My solution was adding this to the bottom of the Podfile


```  
xcframeworks = ['PodName1', 'PodName2']  # pods which are xcframeworks
installer.pods_project.targets.each do |target|
      if xcframeworks.include? target.name
          target.build_configurations.each do |config|
              config.build_settings['ARCHS'] = ["$(ARCHS_STANDARD)", "i386", "x86_64"]
          end
      end
  end
```

**Comment by perrosnk** [comment] 2020-12-18 13:53
@ManueGE did you add this to `post_install do |installer|` or `pre_install do |installer|`?
Thank you very much

**Comment by ManueGE** [comment] 2020-12-18 17:24
@perrosnk `post_install`. Updated my answer.

**Comment by perrosnk** [comment] 2020-12-18 17:32
@ManueGE Thank you very much for your help. Unfortunately it doesn't work for me. It seems that xcode still tries to use the ios slice of the XCFrameworks that doesn't contain the x86_64 architecture. I have no idea why that is the case!

**Comment by trevinwisaksana** [comment] 2020-12-19 11:16
> @trevinwisaksana Did you find a solution to that?

I haven't found a long term solution to this. But I found a stop gap one by deleting the `ios-arm64_armv7` folder in the ExampleFramework.xcframework folder when building for a simulator. You can find it in the Pods folder of your project. However, you need to `pod deintegrate` and `pod install` if you want to archive or build for a device. Yes, this is annoying and not ideal. But if you need a quick solution this works

**Comment by banane** [comment] 2021-01-10 04:51
I'm having a similar issue- on CircleCi/remote, it's building for simulator all the time, never for device. Locally, it builds for device, but on CircleCI, it builds for simulator. I see the warning, and the failure (when try to verify on upload with app store).

**Comment by tplester** [comment] 2021-03-11 05:19
@trevinwisaksana I had this same issue with the AppCenter Cocoapod today. I fixed it by removing an recursive path (`$(SRCROOT)/**`) from the Framework Search Path in the target (though it could also be in the project) Build Settings.

The recursive path was causing XCode to add every folder into the Link step including (incorrectly) the architecture folders inside of the xcframework, and using those paths it would find the wrong architecture framework. You can tell if this is the case by looking at the Link step log
![image](https://user-images.githubusercontent.com/36178559/110739250-e4bfc880-8284-11eb-8051-9f7037c9d0bc.png)
 for paths similar to this:
```
-FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_arm64e_armv7_armv7s
-FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_i386_x86_64-simulator
-FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_x86_64-maccatalyst
-FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/macos-arm64_x86_64
-FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/tvos-arm64
-FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/tvos-arm64_x86_64-simulator
```

**Comment by trevinwisaksana** [comment] 2021-03-12 03:16
@tplester it works! Thank you so much for this!

**Comment by m1entus** [comment] 2021-04-01 19:29
If you still facing this issue i had to exclude arm64 from build settings like this:
```
if target.name == "AgoraRtcEngine_iOS"
        config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "arm64"
      end
```

**Comment by markus-mohemian** [comment] 2021-04-14 19:57
> @trevinwisaksana I had this same issue with the AppCenter Cocoapod today. I fixed it by removing an recursive path (`$(SRCROOT)/**`) from the Framework Search Path in the target (though it could also be in the project) Build Settings.
> 
> The recursive path was causing XCode to add every folder into the Link step including (incorrectly) the architecture folders inside of the xcframework, and using those paths it would find the wrong architecture framework. You can tell if this is the case by looking at the Link step log
> ![image](https://user-images.githubusercontent.com/36178559/110739250-e4bfc880-8284-11eb-8051-9f7037c9d0bc.png)
> for paths similar to this:
> 
> ```
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_arm64e_armv7_armv7s
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_i386_x86_64-simulator
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_x86_64-maccatalyst
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/macos-arm64_x86_64
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/tvos-arm64
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/tvos-arm64_x86_64-simulator
> ```

Saved my day! Big thanks. Turned out that I recursively added all folders in my entire project to search paths. 🙈

**Comment by Tibbs** [comment] 2021-07-16 13:14
> @trevinwisaksana I had this same issue with the AppCenter Cocoapod today. I fixed it by removing an recursive path (`$(SRCROOT)/**`) from the Framework Search Path in the target (though it could also be in the project) Build Settings.
> 
> The recursive path was causing XCode to add every folder into the Link step including (incorrectly) the architecture folders inside of the xcframework, and using those paths it would find the wrong architecture framework. You can tell if this is the case by looking at the Link step log
> ![image](https://user-images.githubusercontent.com/36178559/110739250-e4bfc880-8284-11eb-8051-9f7037c9d0bc.png)
> for paths similar to this:
> 
> ```
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_arm64e_armv7_armv7s
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_i386_x86_64-simulator
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_x86_64-maccatalyst
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/macos-arm64_x86_64
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/tvos-arm64
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/tvos-arm64_x86_64-simulator
> ```
@markus-mohemian Thank you very much for sharing this
I have been struggling with this issue for months. I was only able to test my apps on a device. One of my projects had the error and none of the solutions I found online worked. I deleted  $(SRCROOT) from the projects Framework Search Path and now it works perfectly.

**Comment by herbertvuijk** [comment] 2023-09-04 13:57
> @trevinwisaksana I had this same issue with the AppCenter Cocoapod today. I fixed it by removing an recursive path (`$(SRCROOT)/**`) from the Framework Search Path in the target (though it could also be in the project) Build Settings.
> 
> The recursive path was causing XCode to add every folder into the Link step including (incorrectly) the architecture folders inside of the xcframework, and using those paths it would find the wrong architecture framework. You can tell if this is the case by looking at the Link step log ![image](https://user-images.githubusercontent.com/36178559/110739250-e4bfc880-8284-11eb-8051-9f7037c9d0bc.png) for paths similar to this:
> 
> ```
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_arm64e_armv7_armv7s
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_i386_x86_64-simulator
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/ios-arm64_x86_64-maccatalyst
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/macos-arm64_x86_64
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/tvos-arm64
> -FPods/AppCenter/AppCenter-SDK-Apple/AppCenter.xcframework/tvos-arm64_x86_64-simulator
> ```

OMG. Thank you so much. I've have been looking for a solution for 2 days, didn't even know how to Google the problem. I found out if I removed the ios arm 64 slice, it would finally pick the simulator one. After i realized this I could google the problem better (chat GPT was of NO help). You saved my day! Thanks.
