### ISSUE TITLE
cocoapods-deintegrate NoMethodError - undefined method `include?' for nil:NilClass

### ISSUE THREAD

**Issue by scottdelly** [CocoaPods/CocoaPods#5238] opened 2016-05-03 00:12 UTC
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?
Updated to cocoapods 1rc1 and ran pod install

* What did you expect to happen?
Pods to install and hopefully work better with Xcode 7

* What happened instead?
Install failed almost immediately with the following error

### Stack

```
   CocoaPods : 1.0.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5037697d46b3ddc9e6d80074c6b6f88d18d33ce6
```

### Plugins

```
cocoapods-browser      : 0.1.5
cocoapods-deintegrate  : 1.0.0.rc.1
cocoapods-dependencies : 0.5.2
cocoapods-plugins      : 1.0.0.rc.1
cocoapods-podfile_info : 1.0.0
cocoapods-search       : 1.0.0.rc.1
cocoapods-stats        : 1.0.0.rc.1
cocoapods-trunk        : 1.0.0.rc.1
cocoapods-try          : 1.0.0.rc.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
inhibit_all_warnings!
use_frameworks!

def shared_pods
    # NetowrkStack
    pod 'Alamofire'
    pod 'Decodable'

    # Analytics and install attribution
    pod 'Mixpanel'
end

target 'ios-app' do
    platform :ios, '8.0'

    shared_pods

    # NetowrkStack
    pod 'RestKit'

    # Analytics and install attribution
    pod 'mopub-ios-sdk'
    pod 'Branch'

    # 3rd Party Login and Sharing
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'TwitterKit'
    pod 'TwitterCore'
    
    # Crash Handling and Beta Distribution
    pod 'Fabric'
    pod 'Crashlytics'

    # Front-End
    pod 'AsyncDisplayKit'
    pod 'SVProgressHUD'
    pod 'DateTools'

    # Back-end
    pod 'PubNub', '~>4.0'
    pod 'YapDatabase'
    pod 'WebASDKImageManager'

    # Utilities
    pod 'Reveal-iOS-SDK', :configurations => ['Develop', 'Staging']
    pod 'Buglife', :configurations => ['Develop', 'Staging']
    pod 'netfox', :configurations => ['Develop', 'Staging']
    pod 'Toucan'

    # Unused
#    pod 'BonMot'
#    pod 'ResponseDetective'
#    pod 'Sync'
end

target 'WatchKit Extension' do
    platform :watchos, '2.0'
    shared_pods
end

post_install do |installer|
    puts("Update debug pod settings to speed up build time")
    Dir.glob(File.join("Pods", "**", "Pods*{develop,Private}.xcconfig")).each do |file|
        File.open(file, 'a') { |f| f.puts "\nDEBUG_INFORMATION_FORMAT = dwarf" }
    end
end
```

### Error

```
NoMethodError - undefined method `include?' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:57:in `block in deintegrate_shell_script_phase'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:56:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:56:in `deintegrate_shell_script_phase'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:22:in `block in deintegrate_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:21:in `deintegrate_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:8:in `block (2 levels) in deintegrate_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:7:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:7:in `block in deintegrate_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:6:in `deintegrate_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:499:in `block (3 levels) in deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/config.rb:39:in `with_changes'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:499:in `block (2 levels) in deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:498:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:498:in `block in deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:495:in `deintegrate_if_different_major_version'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:132:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:131:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:113:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.rc.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.rc.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment] 2016-05-03 00:14
This is a duplicate of #5236.

**Closed by segiddins** 2016-05-03 00:14 UTC

**Comment by jinjorge** [comment] 2016-05-03 07:31
was also running into this issue with v1.0.0.rc.1

reverted back to 
```
cocoapods (1.0.0.beta.8)
cocoapods-core (1.0.0.beta.8)
cocoapods-deintegrate (1.0.0.beta.1)
cocoapods-downloader (1.0.0.beta.3)
cocoapods-plugins (1.0.0.beta.1)
cocoapods-search (1.0.0.beta.2)
cocoapods-stats (1.0.0.beta.4)
cocoapods-trunk (1.0.0.beta.4)
cocoapods-try (1.0.0.beta.4)
```
and can run pod install relatively reliably.

The proposed workaround in #5236 does not apply in that this was already in the pod file
```
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
```

**Comment by kwerle** [comment] 2016-05-03 17:46
Same:

source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

pod 'Fabric'
pod 'Crashlytics'
pod 'Google/SignIn'
pod 'Alamofire', '~> 2.0'
pod 'Google/SignIn'

**Comment by segiddins** [comment] 2016-05-03 17:57
This is presumably fixed on master of cocoapods-deintegrate but o can't be sure due to the lack of a reproduction case

**Comment by dillonykyang** [comment] 2016-05-06 22:53
I have the same issue here

````ruby
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!

target 'VRSDK' do
	platform :ios, '8.0'
	pod 'Crashlytics'
	pod 'Fabric'
	pod 'SDK', :path => '../sdk-ios'
end
```

### Error

```
NoMethodError - undefined method `include?' for nil:NilClass
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:57:in `block in deintegrate_shell_script_phase'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:56:in `select'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:56:in `deintegrate_shell_script_phase'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:22:in `block in deintegrate_target'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:21:in `deintegrate_target'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:8:in `block (2 levels) in deintegrate_project'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:7:in `each'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:7:in `block in deintegrate_project'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-deintegrate-1.0.0.rc.1/lib/cocoapods/deintegrator.rb:6:in `deintegrate_project'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:499:in `block (3 levels) in deintegrate_if_different_major_version'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/config.rb:39:in `with_changes'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:499:in `block (2 levels) in deintegrate_if_different_major_version'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:498:in `each'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:498:in `block in deintegrate_if_different_major_version'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:63:in `section'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:495:in `deintegrate_if_different_major_version'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:132:in `block in prepare'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/user_interface.rb:144:in `message'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:131:in `prepare'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/installer.rb:113:in `install!'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command/install.rb:37:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/claide-1.0.0.rc.1/lib/claide/command.rb:334:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/lib/cocoapods/command.rb:50:in `run'
/Applications/CocoaPods.app/Contents/Resources/bundle/lib/ruby/gems/2.2.0/gems/cocoapods-1.0.0.rc.1/bin/pod:55:in `<top (required)>'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `load'
/Applications/CocoaPods.app/Contents/Resources/bundle/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――`

**Comment by segiddins** [comment] 2016-05-06 23:53
@dillonykyang try upgrading to RC 2
