### ISSUE TITLE
Bug: Errno::EEXIST - File exists Pods/Target Support Files/AWSCore

### ISSUE THREAD

**Issue by albertbori** [CocoaPods/CocoaPods#5918] opened 2016-09-20 19:30 UTC
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do? _I upgraded to 1.1.rc.2 and tried to install the pods for xcode 8 compatibility_

* What did you expect to happen? _A succesful install with xcode 8 compatibility_

* What happened instead? _Install crashed with the info below_

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8b02734da207a1bf91bab7be033641cb26b3a2e5
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
project 'MyCompany/MyCompany.xcodeproj'
platform :ios, '9.0'
use_frameworks!

def base_pods
    pod 'MBProgressHUD', '~> 0.8'
    pod 'ActionSheetPicker-3.0'
    #pod 'MyContactPicker', :git => "https://github.com/MyCompany/MyCompany-ios-contactpicker"
    pod 'MyContactPicker', :path => '../MyCompany-ios-contactpicker'
    pod 'SDWebImage'
    #pod 'Reachability'
    pod 'TMReachability', :git => 'https://github.com/albertbori/Reachability'
    #pod 'TMReachability', :path => '../Reachability'
    pod 'Locksmith', :git => 'https://github.com/matthewpalmer/Locksmith/', :branch => "swift-2.3"
    pod 'TCMobileProvision', :git => "https://github.com/tcurdt/TCMobileProvision"
    pod 'MMMarkdown', :git => "https://github.com/albertbori/MMMarkdown"
    pod 'GMImagePicker', :git => 'https://github.com/albertbori/GMImagePicker', :branch => "kif-support"
    #pod 'GMImagePicker', :path => '../GMImagePicker'
    pod 'AWSMobileAnalytics'
    pod 'Marshal', :git => "https://github.com/utahiosmac/Marshal", :branch => "swift2_3"
    pod "ImagePickerSheetController", :git => "https://github.com/lbrndnr/ImagePickerSheetController", :branch => "swift2.3-improvements"
    pod 'SevenSwitch', :path => '../SevenSwitch'
    pod 'CMPopTipView'
    pod 'UIBarButtonItem-Badge', :git => 'https://github.com/mikeMTOL/UIBarButtonItem-Badge'
end

target 'MyCompany' do
    base_pods
    
    target 'UnitTests' do
        inherit! :search_paths
    end
end

target 'MyCompanyUserTest' do
    base_pods
end

target 'AutomatedTests' do
    pod 'KIF', '~> 3.0', :configurations => ['Debug', 'QA']
    #pod 'SwiftAddressBook', :git => 'https://github.com/SocialbitGmbH/SwiftAddressBook.git'
    pod 'SwiftAddressBook', :path => '../SwiftAddressBook'
end

#corrects code signing issues in the Pods project
post_install do |installer|
    installer.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
            config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
            config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
        end
    end
end
```

### Error

```
Errno::EEXIST - File exists - /Users/albertbori/dev/MyCompany-ios/Pods/Target Support Files/AWSCore
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:115:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

**Comment by benasher44** [comment] 2016-09-20 19:54
This is a duplicate of #5864. An improvement to the error message here is coming out soon, which will help debug this. Make sure the proper Swift version is set at the project level or in each of your target's that requires Swift pods.

**Closed by benasher44** 2016-09-20 19:54 UTC
