### ISSUE TITLE
Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons

### ISSUE THREAD

**Issue by KiranMantana** [CocoaPods/CocoaPods#7383] opened 2018-01-31 11:50 UTC
Team,

Using, Xcode 9.2 CocoaPods 1.4.0 Mac OS (10.13.2)  Ruby 2.3.0

When running the app getting a compilation error (Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons). We are getting the similar issue in Jenkins as well, I have two builds in the same path with different names, One build is working fine and other getting a Compilation error. 

We are facing similar issues in Jenkins as well, most of the people suggesting to change the path. But it is not working every time. What is the solution for it.

Not able to execute Script for Resources
**Run Custome Shell '[CP] Copy Pod Resources**

![issue](https://user-images.githubusercontent.com/7392665/35621555-bb7ff192-06aa-11e8-9407-ca8beeedf2a6.png)

**Comment by nianran** [comment] 2018-01-31 12:39
I have the same issue.
I think this issue may be assciated with the [pr](https://github.com/CocoaPods/CocoaPods/commit/9046e78eec9c61c17da75c4473b32433cd823276) and the [issue](https://github.com/CocoaPods/CocoaPods/issues/6936)

**Comment by nianran** [comment] 2018-01-31 12:40
ENV:
cocoapods: 1.4.0(release)
xcode version 9.2 (9C40b)
ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin17]

pod install -> no error
when I build the project, build failed
the problem says:
"Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below."

OK, I compare pod 1.3.1 to 1.4.0.
when I reset xxx.xcodeproj/project.pbxproj to the 1.3.1 version, build success.

OK, show the diff.
1.3.1:
outputPaths = (
"${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}",
);

1.4.0
outputPaths = (
"${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.xib",
"${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.js",
"${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.xcassert",
"${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.mob",
"${TARGET_BUILD_DIR}/${UNLOCALIZED_RESOURCES_FOLDER_PATH}/xxxx.bundle",
........(more and more)
);

I can't reproduce the phenomenon in demo. sorry.

**Comment by KiranMantana** [comment] 2018-01-31 13:53
I am also facing the same issue. Any solution to fix it

**Comment by dnkoutso** [comment] 2018-01-31 16:11
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/7383.

This is because there are too many input and output paths on a target, `env` has a limit on how many it can have.

Closing this issue since #7383 exists.

**Closed by dnkoutso** 2018-01-31 16:11 UTC

**Comment by dnkoutso** [comment] 2018-01-31 16:13
Unfortunately this is an issue with CocoaPods 1.4.0, you can use 1.3.1 in the meantime or create a `post_install` hook that removes input and output paths from your targets but it will slow down a bit recompilations. There is also a radar filed with Apple at https://bugreport.apple.com/web/?problemID=36831832

**Comment by dnkoutso** [comment] 2018-01-31 19:43
Fixed with https://github.com/CocoaPods/CocoaPods/pull/7384 will be released in the next version of cocoapods. Please use bundler if you want to point to a specific SHA to get the fix earlier.

**Comment by nianran** [comment] 2018-02-01 01:41
THX.

**Comment by EricYang851013** [comment] 2018-03-15 14:50
@dnkoutso ，may I ask how to  removes input and output paths from my targets？

**Comment by dnkoutso** [comment] 2018-03-15 14:52
use latest version from master. If you have more than 1000 it will remove them automatically until Apple fixes the problem.

**Comment by EricYang851013** [comment] 2018-03-16 06:09
THX.

**Comment by KiranMantana** [comment] 2018-03-16 07:17
@dnkoutso How can we install master, Will link work?

http://guides.cocoapods.org/using/unreleased-features

Or is there any other links to do it

**Comment by segiddins** [comment] 2018-03-17 23:30
@KiranMantana that’s it

**Comment by yanzhiwei147** [comment] 2018-04-28 11:35
Sorry, this issue continue to occur.

I try change the file `lib/cocoapods/installer/user_project_integrator/target_integrator.rb`:
1. Set `MAX_INPUT_OUTPUT_PATHS  = 200`, this issue resolved. 
2. Set `MAX_INPUT_OUTPUT_PATHS  = 1000`, this issue reappear.

My project own about 348 item `resource.bundle`, but each input like `"${PODS_ROOT}/../myapp/Resources/i18n/com.xx.yy.component.my-exam-player_i18n.bundle"` . So i guess because the export path was too long. 

Suggest we can calculate the file path length while generate the input or output files.

**Comment by yanzhiwei147** [comment] 2019-04-15 02:34
This issue still continue to occur at version 1.6.1. What can i do for it? example should provide sample project demo?

**Comment by blick9** [comment] 2019-09-03 05:49
```
Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below.
```

This happens occur when the total path length is too long.

**change the folder name** or total location directory, shorter then before.

**Comment by blick9** [comment] 2019-09-03 05:58
```
Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below.
```

This happens occur when the total path length is too long.

**change the folder name** or location of directory, shorter then before.

**Comment by hendych** [comment] 2019-11-25 06:33
Occured to me. 
I remember Xcode have this issue too. The error is `unable to spawn process, argument list too long`.

Although this issue fixed on Xcode 11. But when using Xcode 11, now my build fails on `Copy Pods Resources` phase with error
```
Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes
```

**Comment by hrushie** [comment] 2020-05-01 17:43
Hello team, 

Our team is facing this issue since long time, do we have any fix that I am missing?

**Comment by sudebsm** [comment] 2020-05-06 06:52
> Hello team,
> 
> Our team is facing this issue since long time, do we have any fix that I am missing?

I also facing this issue 
After changing the folder path to desktop its working fine.
like this 
/Users/Me/Documents/MyProject and I changed to /Users/Me/Desktop/MyProject
