### ISSUE TITLE
[1.6.0.beta.1] podspec checksum for `:podspec` is inconsistent across installs

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#8021] opened 2018-08-17 06:51 UTC
Podfile:
```
pod 'A', :path=> 'xx/A/'
pod 'B', :podspec=> 'xx/B.podspec'
```
There are two pods in the Podfile. I found that CP get the checksum of podspec will have different logic:

If the pod use the `path`, CP get the checksum of `xx/A/A.podspec`.
If the pod use the `podspec`, CP get the checksum of `Pods/Local Podspecs/B.podspec.json`, instead of `xx/B.podspec`.

The logic for the `path` seams that be changed from the v1.5. I remember that its logic is same with `podspec` at past. I think the logic which get the checksum of origin podspec file is correct way. So, should we also change the logic of `podspec`?

**Comment by dnkoutso** [comment] 2018-08-17 07:33
A few things:

a) why is this a problem?
b) I have not noticed any differences in checksums
c) can you please file with https://github.com/CocoaPods/Core instead?
d) sample always helps if you can provide one showing difference between 1.5.x and 1.6.x

**Comment by Whirlwind** [comment] 2018-08-19 06:44
@dnkoutso  I test Cocoapods v1.6.0.beta.1, there is a checksum changed in the Podfile.lock.

You could try it as my step:

1. `rm -rf Pods` to remove the sandbox if you installed before.
2. use the `pod 'xx', :podspec=>'xx'` DSL. eg: `pod 'glog', :podspec => '../RNBundle/ios_pods/react-native-official-55/third-party-podspecs/GLog.podspec'`
3. run `pod install`, CP will write the checksum of `GLog.podspec` into `Podfile.lock`.
4. run `pod install` again, CP will write the checksum of `Pods/Local Podspecs/glog.podspec.json` into the `Podfile.lock`.

the step 3 and 4 will get different value from different files.

**Comment by dnkoutso** [comment] 2018-08-19 08:10
@Whirlwind I am inclined to close this issue. You are right that it moved but it might actually be OK.

Again besides the diff what problem does this cause to you?

**Comment by Whirlwind** [comment] 2018-08-19 08:13
There is a bug to cause to me.

> run pod install, CP will write the checksum of GLog.podspec into Podfile.lock.
> run pod install again, CP will write the checksum of Pods/Local Podspecs/glog.podspec.json into the Podfile.lock.

This is the key step. If this bug is fixed, it maybe OK to me.

**Comment by Whirlwind** [comment] 2018-08-19 08:15
By the way, the `integration` tests could not test some cases, eg: `install` twice times, there is nothing should be changed.

**Comment by dnkoutso** [comment] 2018-08-19 08:26
Hm ok interesting we will have to check for beta.2. We do not get this problem at all.

**Comment by dnkoutso** [comment] 2018-08-19 08:27
Might be a bug only with ` :podspec =>...`

**Comment by Whirlwind** [comment] 2018-08-19 08:31
Could you add a support to `re-install ` in the integrate test? I have a test for the `install`, and I must write same test for the `re-install` to validate the files are same with last install.

**Comment by Whirlwind** [comment] 2018-08-19 08:34
I test the `:path`, it works fine. So it is a bug only with `:podspec`.

**Comment by Whirlwind** [comment] 2018-08-19 10:50
I check the code, when re-install the pods, the Podfile do not changed. So CP will not fetch the external source for the pod with `podspec`, and CP will not call `store_podspec` in the `Pod::ExternalSources::PodspecSource`.

So when podfile do not changed, the sandbox will not have any podspec path in the `Sandbox->@stored_podspecs` and `Sandbox->development_pods`.
```

    def specification(name)
      @stored_podspecs[name] ||= if file = specification_path(name)
                                   original_path = development_pods[name]
                                   Specification.from_file(original_path || file)
      end
    end
```

In this method, `@stored_podspecs[name]` and `original_path` is all nil, so CP get the path from the sandbox directory `Pods/Local Podspecs/`.

If user install at first, the `PodspecSource` will call `Sandbox::store_podspec` to add origin path into `@stored_podspecs`.

**Comment by segiddins** [comment] 2018-10-10 17:07
Is there an example project that reproduces the issue?

**Comment by dnkoutso** [comment] 2018-10-10 17:39
@Whirlwind I tried to make a Sample here but I was unable to reproduce.

**Comment by dnkoutso** [comment] 2018-10-10 17:43
nm I got it.

[ChecksumIssue.zip](https://github.com/CocoaPods/CocoaPods/files/2465784/ChecksumIssue.zip)

**Comment by segiddins** [comment] 2018-10-11 17:47
@Whirlwind please try out https://github.com/CocoaPods/CocoaPods/pull/8178

**Closed** 2018-10-12 17:54 UTC
Labels: s2:confirmed, t2:defect

**Comment by Whirlwind** [comment] 2018-10-23 14:15
I don't understand that why CP get the checksum from the `Pods/Local Podspecs/xxx.podspec.json`, instead of the origin podspec file.

It causes the Podfile.lock would be changed from v1.5.3.

**Comment by segiddins** [comment] 2018-10-23 16:31
Because the JSON contains the logical contents of the Podfile, and we do want the checksum to change if the evaluated ruby code has changed
