### ISSUE TITLE
Flutter MacOs WARNING: CocoaPods requires your terminal to be using UTF-8 encoding

### ISSUE THREAD

**Issue by longol** [CocoaPods/CocoaPods#9347] opened 2019-11-14 22:18 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Flutter project for macOS using Visual Studio. Click on Debug, also when using flutter run -d macOS

## What did you expect to happen?

Project to compile

## What happened instead?

Compile fails with errors

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.2.1 (11B53)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

import 'package:flutter/material.dart';
import 'package:flutter/foundation.dart'
  show debugDefaultTargetPlatformOverride;
// import 'package:flutter/services.dart';
// import 'package:url_launcher/url_launcher.dart';
import 'package:universal_io/prefer_universal/io.dart';
// import 'package:universal_html/prefer_universal/html.dart' as html;

void main() {
  debugDefaultTargetPlatformOverride = TargetPlatform.fuchsia;
  runApp(MyApp());
} 

class MyApp extends StatelessWidget {
  // This widget is the root of your application.
  @override
  Widget build(BuildContext context) {
    return MaterialApp(
      title: 'Flutter Demo',
      theme: ThemeData(
        // This is the theme of your application.
        //
        // Try running your application with "flutter run". You'll see the
        // application has a blue toolbar. Then, without quitting the app, try
        // changing the primarySwatch below to Colors.green and then invoke
        // "hot reload" (press "r" in the console where you ran "flutter run",
        // or simply save your changes to "hot reload" in a Flutter IDE).
        // Notice that the counter didn't reset back to zero; the application
        // is not restarted.
        primarySwatch: Colors.blue,
      ),
      home: MyHomePage(title: 'Flutter Demo Home Page'),
    );
  }
}

class MyHomePage extends StatefulWidget {
  MyHomePage({Key key, this.title}) : super(key: key);

  // This widget is the home page of your application. It is stateful, meaning
  // that it has a State object (defined below) that contains fields that affect
  // how it looks.

  // This class is the configuration for the state. It holds the values (in this
  // case the title) provided by the parent (in this case the App widget) and
  // used by the build method of the State. Fields in a Widget subclass are
  // always marked "final".

  final String title;

  @override
  _MyHomePageState createState() => _MyHomePageState();
}

class _MyHomePageState extends State<MyHomePage> {
  int _counter = 0;

  void _incrementCounter() {
    setState(() {
      // This call to setState tells the Flutter framework that something has
      // changed in this State, which causes it to rerun the build method below
      // so that the display can reflect the updated values. If we changed
      // _counter without calling setState(), then the build method would not be
      // called again, and so nothing would appear to happen.
      _counter++;
    });
 
  }

  @override
  Widget build(BuildContext context) {
    // This method is rerun every time setState is called, for instance as done
    // by the _incrementCounter method above.
    //
    // The Flutter framework has been optimized to make rerunning build methods
    // fast, so that you can just rebuild anything that needs updating rather
    // than having to individually change instances of widgets.

    // void _launchURL(String url) async {
    //   html.window.open(url, "Recording Today");
    // }   

    _launchURL(String url) async {
      // print("DEBUG: A");
      // if (Platform.isAndroid || Platform.isIOS) {
        // print("DEBUG: B");
        // if (await canLaunch(url)) {
        //   await launch(url);
        // } else {
        //   throw 'Could not launch $url';
        // }
      // } else /*if (kIsWeb)*/ { 
        // print("DEBUG: C");
        // html.document.window.location.href = url;
      // }      
    }

    return Scaffold(
      appBar: AppBar(
        // Here we take the value from the MyHomePage object that was created by
        // the App.build method, and use it to set our appbar title.
        title: Row(
          mainAxisAlignment: MainAxisAlignment.start, 
          children: <Widget>[
            Image(image: AssetImage('images/RecTodayIcon1024.png'), width: 50),
            SizedBox(width: 5),
            Text("Recording Today"),
          ],
        )
      ),
      body: Center(
        // Center is a layout widget. It takes a single child and positions it
        // in the middle of the parent.
        child: Column(
          // Column is also a layout widget. It takes a list of children and
          // arranges them vertically. By default, it sizes itself to fit its
          // children horizontally, and tries to be as tall as its parent.
          //
          // Invoke "debug painting" (press "p" in the console, choose the
          // "Toggle Debug Paint" action from the Flutter Inspector in Android
          // Studio, or the "Toggle Debug Paint" command in Visual Studio Code)
          // to see the wireframe for each widget.
          //
          // Column has various properties to control how it sizes itself and
          // how it positions its children. Here we use mainAxisAlignment to
          // center the children vertically; the main axis here is the vertical
          // axis because Columns are vertical (the cross axis would be
          // horizontal).
          mainAxisAlignment: MainAxisAlignment.center,
          children: <Widget>[
            RaisedButton(
              onPressed: () {
                _launchURL('smb://lcp1-smb.content.linkedin.biz/Production/Projects/Video/Video In Progress');
              },
              child: Text('VIP Folder'),
            ),
            Image(image: AssetImage('images/RecTodayIcon1024.png'), width: 200,),
            Text(
              'You have pushed the button this many times',
            ),
            Text(
              '$_counter',
              style: Theme.of(context).textTheme.display1,
            ),
          ],
        ),
      ),
      floatingActionButton: FloatingActionButton(
        onPressed: _incrementCounter,
        tooltip: 'Increment',
        child: Icon(Icons.add),
      ), // This trailing comma makes auto-formatting nicer for build methods.
    );
  }
}

**Comment by dnkoutso** [comment] 2019-11-14 22:35
Please file a bug with Flutter repo. CocoaPods warns about this intentionally and its not going to change. 

Closing as we get many issues for Flutter/ReactNative that are not issues in CocoaPods.

**Closed by dnkoutso** 2019-11-14 22:35 UTC

**Comment by DanTup** [comment] 2019-11-27 12:34
@dnkoutso I work on the Flutter extension for VS Code and this issue has been reported to me a few times. Today I hit the issue myself and was able to dig into it a bit more. It's complicated to fix from VS Code because Flutter is not running in a terminal, it's being spawned as a process from a NodeJS process (the VS Code extension host).

On macOS, the `LANG` env variable is set in the terminal app and not for processes that are spawned outside of the terminal (eg. if you launch VS Code from the dock).

Adding new env variables is ofcourse simple, however setting `LANG` to include `en-US` on a users machine for the whole Flutter process may introduce side effects if there are other processes that base their behaviour on this (if their machine is not `en_US` at the system level). From nodejs there isn't a great way to get underlying system locale to reconstruct a suitable `LANG` variable (or at least, the API for it works in VS Code's main process, but [not in the extension host](https://github.com/microsoft/vscode/issues/85675) where extension code runs).

It's possible this could be handled in Flutter be having it set `LANG` if it's not already set when spawning CocoaPods (forcing it to `en_US.UTF-8` - there would have less impact than setting it for the whole Flutter process). However, I wondered if it might make sense to try and fix here (as if it affects other projects too like ReactiveNative, they'd all need to make similar changes).

If I understood the error correctly, the issue is that Ruby uses `LANG` to set the default encoding when reading files. If it's not set, it uses ANSII/ASCII which fails when reading UTF-8 files. I'm not *at all* familiar with Ruby but I saw that there are some functions to read files that allow an encoding to be supplied (for ex. https://ruby-doc.org/core-2.6.5/IO.html#method-c-read) and I wondered if they'd help here? Is it possible to read the files as UTF-8 rather than relying on Ruby's default encoding and avoid this issue?

I'm happy to try and send a PR if you think this would work and it seems like a reasonable change to you.

Thanks!
