### ISSUE TITLE
Add another layer of integration testing.

### ISSUE THREAD

**Issue by alloy** [CocoaPods/CocoaPods#3891] opened 2015-07-24 15:36 UTC
Sometimes issues only surface in larger real apps, so it might be a good idea to run `pod install` _and_ `xcodebuild archive` on those as part of CI.

Objective-C apps:
* Frameworks: https://github.com/artsy/eigen/tree/master
* Static libraries: https://github.com/artsy/eigen/tree/2.0.1

Swift apps:
* Frameworks: https://github.com/artsy/eidolon/tree/master
* Static libraries: https://github.com/artsy/eidolon/tree/3.1.1
* http://github.com/apiaryio/polls-app
* https://github.com/kylef/Starship

There’s probably more open-source apps, please add them as comments. We specifically need apps that  have larger Podfiles.

**Comment by jhersh** [comment] 2015-07-24 16:05
[MUDRammer: A Modern MUD Client](https://github.com/splinesoft/MUDRammer) — [Podfile](https://github.com/splinesoft/MUDRammer/blob/master/src/Podfile)

**Comment by neonichu** [comment] 2015-07-25 00:04
Signal is probably a good candidate: https://github.com/WhisperSystems/Signal-iOS

It uses things like OpenSSL which are rather quirky and can't use frameworks.

**Comment by andrew** [comment] 2015-07-26 17:30
Here's some potentially useful data I was able to pull from the https://libraries.io database, it hasn't indexed all of GitHub yet but most of the popular/interesting repos so it may have missed some.

**10 open source Objective-C repos with biggest number of dependencies in Podfile:**

- https://github.com/wordpress-mobile/WordPress-iOS
- https://github.com/artsy/eigen
- https://github.com/inaturalist/INaturalistIOS
- https://github.com/evanspa/PEFuelPurchase-Model
- https://github.com/guardianproject/securereader_ios
- https://github.com/hyperoslo/Form
- https://github.com/auth0/Lock.iOS-OSX
- https://github.com/braintree/braintree_ios
- https://github.com/loopj/bugsnag-example-apps
- https://github.com/contentful/product-catalogue-ios

**10 open source Swift repos with biggest number of dependencies in Podfile:**

- https://github.com/artsy/eidolon
- https://github.com/asm-products/gig-radio-ios
- https://github.com/netguru/roomguru
- https://github.com/TalkingBibles/Talking-Bible-iOS
- https://github.com/asm-products/giraff-ios
- https://github.com/neonichu/CoolSpot
- https://github.com/apiaryio/polls-app
- https://github.com/imWildCat/V2EX-iOS-ObjC
- https://github.com/erkie/ApiModel
- https://github.com/bradjasper/RadialMenu

**Top 10 most popular (stars) open source Objective-C repos with a Podfile:**

- https://github.com/AFNetworking/AFNetworking
- https://github.com/rs/SDWebImage
- https://github.com/RestKit/RestKit
- https://github.com/SnapKit/Masonry
- https://github.com/supermarin/Alcatraz
- https://github.com/jessesquires/JSQMessagesViewController
- https://github.com/facebook/AsyncDisplayKit
- https://github.com/kevinzhow/PNChart
- https://github.com/slackhq/SlackTextViewController
- https://github.com/eczarny/spectacle

**Top 10 most popular (stars) open source Swift repos with a Podfile:**

- https://github.com/onevcat/Kingfisher
- https://github.com/pNre/ExSwift
- https://github.com/SugarRecord/SugarRecord
- https://github.com/bennyguitar/News-YC---iPhone
- https://github.com/artsy/eidolon
- https://github.com/amitburst/HackerNews
- https://github.com/stakes/Frameless
- https://github.com/tnantoka/edhita
- https://github.com/wantedly/swift-rss-sample
- https://github.com/andreacremaschi/GEOSwift

**Comment by orta** [comment] 2015-07-26 17:36
This is a super useful resource outside of this issue also, thanks!

**Comment by neonichu** [comment] 2015-08-10 17:46
So, to tackle this I'm thinking the following:

- Pick out some apps from this issue which actually build fine and look like they won't break builds too often, ideally they have CI in place themselves
- For each one of them, create a YAML file which describes where to fetch them from, build steps and required Xcode version. Something like this:

```yaml
---
source: https://github.com/artsy/eigen.git
build:
- make build
xcode: 6.3
```

- Build a small tool which takes that YAML file as an input, clones the project and performs builds.
- The tool does a build using the latest stable version of CP for `pod install` to verify the project even still builds — if that fails, abort because we can't actually see regressions with something that already doesn't work.
- The tool does a build where it nukes any existing "Pods" directory and does a `pod install` using whatever version we want to release (this is supposed to verify a "clean" install)
- The tool does another build where it first installs using the latest stable version of CP and then another install using the version we want to release (this is supposed to verify an upgrade install)
- The tool shouldn't be too smart to keep it low maintenance, it would only know how to run `pod install`, shell out to `git` for fetching projects and use xcode-select to pick the right Xcode version. **How** projects are build will be encoded in the build steps only.

Thoughts?

**Comment by segiddins** [comment] 2015-08-10 17:53
:+1:

**Comment by neonichu** [comment] 2015-08-10 21:12
Started this here: <https://github.com/neonichu/cocoapods-regression>

**Comment by segiddins** [comment] 2016-03-11 21:05
I think we ought to close this -- experimentation with cocoapods-regression showed how impractical this is.

**Comment by neonichu** [comment] 2016-05-01 17:16
Let's close this for now, indeed. :+1:

**Closed by neonichu** 2016-05-01 17:16 UTC
Labels: d3:hard, t3:discussion
