### ISSUE TITLE
Pods `project.pbxproj` gets modified after opening up Xcode 10.2

### ISSUE THREAD

**Issue by PatrickDotStar** [CocoaPods/CocoaPods#8689] opened 2019-04-10 07:41 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Xcode 10.2 is closed
2. run `pod install`
3. `project.pbxproj` should be unchanged if no changes were made in podfile
4. open project in Xcode 10.2
5. `project.pbxproj` gets modified (some properties are added/deleted, see screens)

## What did you expect to happen?

`pod install` modifies `project.pbxproj` only once (if changes were made in podfile) and after opening up Xcode 10.2 `project.pbxproj` does not get modified again.
It did not modify the file with previous version of Xcode 10.2

## What happened instead?

Xcode 10.2 modifies the Pods `project.pbxproj` file after opening up the project

## CocoaPods Environment

We are currently using CocoaPods 1.5.3 but I experienced the same issues with version 1.6.1 and 1.7.0 beta 3

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.6.2p47 (2019-03-13 revision 67232) [x86_64-darwin18]
    RubyGems : 3.0.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.21.0
Ruby lib dir : /usr/local/Cellar/ruby/2.6.2/lib
```

## Changes Xcode 10.2 makes after opening up

The `name` properties get removed
<img width="468" alt="removedName" src="https://user-images.githubusercontent.com/10392878/55859561-9f635f80-5b72-11e9-86a9-b76013d61630.png">
<img width="239" alt="removedName2" src="https://user-images.githubusercontent.com/10392878/55859565-a1c5b980-5b72-11e9-890e-8d6eee85e41b.png">

A bunch of new `knownRegions` are added altough we just had `en` before
<img width="273" alt="addedKnownRegions" src="https://user-images.githubusercontent.com/10392878/55859571-a38f7d00-5b72-11e9-8e96-22e389a72943.png">

We set some custom configs in our Podfile but Xcode 10.2 then just overrides it

```
target.build_configurations.each do |config|
	if config.name == 'Debug'
		config.build_settings['SWIFT_COMPILATION_MODE'] = 'wholemodule'
		config.build_settings['SWIFT_OPTIMIZATION_LEVEL'] = '-Onone'
	end
end
```
<img width="367" alt="overridesCustomChanges" src="https://user-images.githubusercontent.com/10392878/55859575-a4c0aa00-5b72-11e9-9821-b8b5850cc61c.png">

## Conclusion

So yeah, I am not exactly sure if this is a problem (if this is problem at all?) with CocoaPods or Xcode and I also don't know which `project.pbxproj` is the correct one. 
Because if anyone in our team makes a `pod install` and then commits the changes without having the project open in Xcode 10.2, the `project.pbxproj` file gets modified again for any other team member who then pulls these changes.
Any help, ideas and proposals would be appreciated.

**Comment by dnkoutso** [comment] 2019-04-21 14:25
Can you please upload it as a sample app?

**Comment by alex-kovalenko** [comment] 2019-04-24 17:59
I have the same issue. There is a sample project I created to illustrate the issue - https://github.com/alex-kovalenko/Sample-8689. 

The issue seems to be related to how localized strings are defined in the Podspec file.

Changing 
`s.resources = [
    'Resources/Strings/**/*'
  ]`
to
`
s.resources = [
    'Resources/Strings/*.lproj'
  ]
`
in the https://github.com/alex-kovalenko/Sample-8689/blob/master/Framework/Framework.podspec fixes the problem.

**Comment by PatrickDotStar** [comment] 2019-04-25 07:30
Thanks for your sample @alex-kovalenko . 
I was only able to reproduce this issue with our companies project. Neither with a fresh one nor with my private projects.

**Comment by okalentiev** [comment] 2019-04-26 09:19
It looks like this happens once when upgrading from the Xcode 10.1 to Xcode 10.2. After accepting the changes, Xcode is not modifying anything else and seems to be working without issues.

**Comment by PatrickDotStar** [comment] 2019-04-26 12:57
@okalentiev but when you run `pod install` again when Xcode 10.2 is closed it should modifie the file again.

**Comment by jwilliams-handy** [comment] 2019-05-04 00:51
The exact same thing is happening to me as well in my project. Any time I open the project after a `pod install` in Xcode 10.2 the same kind of changes in the pbxproj file. This is the first version of Xcode where I've noticed this happening. It's inhibiting our developers from getting on the latest version of Xcode to develop our project.

**Comment by jwilliams-handy** [comment] 2019-05-04 00:52
This is happening as of the latest cocoa pods RC 1.7.0.rc.1

**Comment by jwilliams-handy** [comment] 2019-06-05 20:37
Still happening on 10.2.1. It's happening for one of my projects but not the other. The solution proposed by @alex-kovalenko is patching Podspecs which I do not own. Are there any other suggestions for this issue?

**Comment by alex-kovalenko** [comment] 2019-06-05 21:54
@jwilliams-handy as a temporary workaround you could create your own version of third-party podspecs. We maintain few 3rd party specs in our private podspec repository.

**Comment by jwilliams-handy** [comment] 2019-07-30 17:10
@alex-kovalenko I've checked some of the specs that are displaying that issue and they don't have similar declarations as you referenced earlier.

I also have 2 applications which share a lot of the same Pods but I only see this issue in one of the applications so I don't think this is the full solution.

I found this issue: https://github.com/CocoaPods/CocoaPods/issues/8494 which seems related but I still can't get this to stop happening.

**Comment by jwilliams-handy** [comment] 2019-07-30 17:11
@dnkoutso would you have any other suggestions?

**Comment by dnkoutso** [comment] 2019-07-30 17:17
Not from the top of my head sorry.

**Comment by alex-kovalenko** [comment] 2019-07-30 18:12
> @alex-kovalenko I've checked some of the specs that are displaying that issue and they don't have similar declarations as you referenced earlier.
> 
> I also have 2 applications which share a lot of the same Pods but I only see this issue in one of the applications so I don't think this is the full solution.
> 
> I found this issue: #8494 which seems related but I still can't get this to stop happening.

Yeah, there are other issues as well. I had to disable pods in my project one by one until I found few causing the issue. Then I had to compare what was different in the podspec files between problematic and working pods. That's how I found this workaround and steps to reproduce.

**Comment by jwilliams-handy** [comment] 2019-07-30 19:30
@alex-kovalenko I took your advice and started removing Pods one by one. I was able to reduce the issue to the Stripe SDK. I tried updating to their latest version with no luck so I started going through the history to see when this started happening by essentially changing the version number until the Xcode changes stopped happening. I was able to find the culprit being the version change from `v8.0.4` -> `v8.0.5`. There's no diff in [each](https://github.com/CocoaPods/Specs/blob/master/Specs/c/e/7/Stripe/8.0.4/Stripe.podspec.json) [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/c/e/7/Stripe/8.0.5/Stripe.podspec.json) except for version.

I forked the repo and created branches so I could compare the code underneath and see if something there that started causing this issue. A comparison can be found here: https://github.com/jwilliams-handy/stripe-ios/compare/8.0.4...jwilliams-handy:8.0.5. It looks like they added some localization files and the issue is what you mentioned before @alex-kovalenko with the `resources` setting. I found the guide on creating a private Spec repo but how would you make sure the `Stripe` in the private repo takes precedence or do you just change the name?

@dnkoutso is this something that can be fixed from the Cocoapods side or do we need to reach out to the developer of this pod?

**Comment by alex-kovalenko** [comment] 2019-07-30 20:58
> @alex-kovalenko I took your advice and started removing Pods one by one. I was able to reduce the issue to the Stripe SDK. I tried updating to their latest version with no luck so I started going through the history to see when this started happening by essentially changing the version number until the Xcode changes stopped happening. I was able to find the culprit being the version change from `v8.0.4` -> `v8.0.5`. There's no diff in [each](https://github.com/CocoaPods/Specs/blob/master/Specs/c/e/7/Stripe/8.0.4/Stripe.podspec.json) [podspec](https://github.com/CocoaPods/Specs/blob/master/Specs/c/e/7/Stripe/8.0.5/Stripe.podspec.json) except for version.
> 
> I forked the repo and created branches so I could compare the code underneath and see if something there that started causing this issue. A comparison can be found here: [jwilliams-handy/stripe-ios@8.0.4...jwilliams-handy:8.0.5](https://github.com/jwilliams-handy/stripe-ios/compare/8.0.4...jwilliams-handy:8.0.5). It looks like they added some localization files and the issue is what you mentioned before @alex-kovalenko with the `resources` setting. I found the guide on creating a private Spec repo but how would you make sure the `Stripe` in the private repo takes precedence or do you just change the name?
> 
> @dnkoutso is this something that can be fixed from the Cocoapods side or do we need to reach out to the developer of this pod?
you can specify your own private Podspec repo in the Podfile:
`
source 'ssh://git@bitbucket.com/private/private-spec.git'
source 'https://github.com/cocoapods/specs.git'
source 'https://github.com/SomeOther/iOSSomeOther.git'
`

> I took your advice and started removing Pods one by one. I was able to reduce the issue to the Stripe SDK.

I looked into their Podspec file, and it looks like they use **resource bundles**: [Stripe.podspec, L17](https://github.com/jwilliams-handy/stripe-ios/blob/master/Stripe.podspec#L17).

 I've seen that causing this issue as well, and I could not find a workaround for it.

**Comment by jwilliams-handy** [comment] 2019-07-31 23:34
@alex-kovalenko meaning you tried the exact same thing you proposed above but with `resource_bundle` instead of `resources` but couldn't get it to work anyway? Also, was going to try the private spec repo thing. Is the way to do that to just fork the stripe repo, update the `.podspec` and then push the version change to my private spec repo?

I'd love to take a look at the underlying code but I'm not sure where to look to see how that setting gets parsed and implemented by Cocoapods. I looked in a couple repos like `Xcodeproj` with no success. 

Anyone familiar with what actually translates this particular setting if I wanted to poke around?

**Comment by alex-kovalenko** [comment] 2019-07-31 23:44
> meaning you tried the exact same thing you proposed above but with `resource_bundle` instead of `resources` but couldn't get it to work anyway?

Yes, we've attempted to convert one framework from using resources to resource bundles. That transition introduced this issue as well.

**Comment by jwilliams-handy** [comment] 2019-08-01 15:10
I found this [pull request](https://github.com/CocoaPods/CocoaPods/pull/4635) from @efirestone in 2015 which seems to be related. Trying to at least start here to look at potential issues/solutions.

**Comment by dnkoutso** [comment] 2019-12-20 05:43
we might be re-doing all of `resources` DSL for 1.10.0 I am moving this issue there.

**Closed** 2020-03-26 06:36 UTC
Labels: s1:awaiting input

**Comment by ArtSabintsev** [comment] 2020-06-17 03:10
Sorry for opening this thread, I am still seeing this issue in Xcode 11 (all version), with compiled binaries, like Crashlytics, Usabila, NewRelicAgent, etc. Those podspecs do not define resources. Any assistance here would be appreciated if anyone has solved the problem.

**Comment by tachtevrenidis** [comment] 2020-06-26 23:14
> Sorry for opening this thread and re-pinging you all, but I am still seeing this issue in Xcode 11 (all versions), with compiled binaries, like Crashlytics, Usabila, NewRelicAgent, etc. Those podspecs do not define resources. Any assistance here would be appreciated if anyone has solved the problem.

I have the same issue...

**Comment by hendych** [comment] 2020-07-22 07:57
Version 1.10 beta has been released. Is this issue has been fixed? Didn't see in the release note though

**Comment by ASLYBZ** [comment] 2021-07-26 02:41
> > Sorry for opening this thread and re-pinging you all, but I am still seeing this issue in Xcode 11 (all versions), with compiled binaries, like Crashlytics, Usabila, NewRelicAgent, etc. Those podspecs do not define resources. Any assistance here would be appreciated if anyone has solved the problem.
> 
> I have the same issue...

me too
