### ISSUE TITLE
Xcode does not found symbols for architecture x86_64 using XCFrameworks

### ISSUE THREAD

**Issue by LFuryk** [CocoaPods/CocoaPods#9549] opened 2020-02-20 20:03 UTC
# Report

## What did you do?

Xcode (11.2.1 & 11.3.1) is having issues to found x86_64 architecture symbols while using XCFrameworks distributed by Cocoapods. The problem is that the architecture is inside the XCFramework.

To generate the XCFramework I made two Archives:

For iOS:

`xcodebuild archive -scheme MyPod -target  MyPod -destination="generic/platform=iOS" -archivePath build/ios.xcarchive -derivedDataPath /tmp/iphoneos -sdk iphoneos SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`

For iOS Simulator:

`xcodebuild archive -scheme MyPod  -target  MyPod -destination="generic/platform=iOS Simulator" -archivePath build/iossimulator.xcarchive -derivedDataPath /tmp/iphoneos -sdk iphonesimulator SKIP_INSTALL=NO BUILD_LIBRARIES_FOR_DISTRIBUTION=YES`

Then I generated the XCFramework:

`xcodebuild -create-xcframework -framework ./build/ios.xcarchive/Products/Library/Frameworks/MyPod.framework -framework ./build/iossimulator.xcarchive/Products/Library/Frameworks/MyPod.framework -output xcframework/MyPod.xcframework`

Here is the XCFramework created where we can see the two architectures: [XCFramework preview](https://i.stack.imgur.com/7EyvK.png)

Once it was created, I distributed it by CocoaPods (1.9.0.beta.3). So my .podspec looks like:

```
s.subspec "Vendored" do |framework|
    framework.vendored_framework = 'xcframework/MyPod.xcframework'
  end
```

Then I consumed it in another project, and when compiling, it fails because it can't find the architecture for the simulator (on devices it works)

The log I got is the following:

```
ld: warning: ignoring file /Path/To/MyProject/Pods/MyPod/xcframework/MyPod.xcframework/ios-armv7_arm64/MyPod.framework/MyPod, missing required architecture x86_64 in file /Path/To/MyProject/Pods/MyPod/xcframework/MyPod.xcframework/ios-armv7_arm64/MyPod.framework/MyPod (2 slices)
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$MyPod", referenced from:
      objc-class-ref in SomeClass.o
ld: symbol(s) not found for architecture x86_64
```

It's looks like xcodebuild always go to the ios-armv7_arm64 folder instead the ios-i386_x86_64-simulator one.

P.D: The XCFramework works when adding manually to the project

Thank you!

**Comment by amorde** [comment] 2020-02-20 20:10
Within the build log, can you look for a `Selected xcframework slice` and check which slice the prepare artifacts script selected? (I will try it myself with your project but can't at the moment)

**Comment by rakeshchander** [comment] 2020-02-25 10:05
Did you get it resolved?

**Comment by rakeshchander** [comment] 2020-02-26 03:28
@dnkoutso Please find attached sample code having One Local Pod reference for one xcframework - it compiles fine for device but gives error when compile for simulator.
This is a framework code which needs this framework as dependency.

Additionally, In another project - which is an app - the same xcframework works fine for both device & simulator.

Please review and let me know if any other details are required.
[LaunchPad_Module_iOS.zip](https://github.com/CocoaPods/CocoaPods/files/4253303/LaunchPad_Module_iOS.zip)

**Comment by amorde** [comment] 2020-02-26 04:23
@rakeshchander thanks for the sample - looks like the sample you provided matches https://github.com/CocoaPods/CocoaPods/issues/9525

@LFuryk are you integrating an xcframework into framework target or an app?

**Comment by LFuryk** [comment] 2020-02-28 13:42
Thank you @rakeshchander for the example! I'm still working on mine.. 

@amorde answering your question, its the same issue as rakes said. When I integrate inside another framework the error shows. when integrating into an app it works for both (device & simuluator)

**Comment by amorde** [comment] 2020-03-01 00:27
Ah okay, thanks. I'm going to close this as a dupe of #9525, but thank you for the report + sample!

**Closed by amorde** 2020-03-01 00:27 UTC
