### ISSUE TITLE
pod install gets TypeError - no implicit conversion of nil into String

### ISSUE THREAD

**Issue by fortesdev** [CocoaPods/CocoaPods#3333] opened 2015-03-30 13:33 UTC
### Command

```
/Users/ios.build/.rvm/gems/ruby-2.2.0/bin/pod install
```

### Report

* What did you do?
Just cloned our source code, set cocoapods and run "pod install"
* What did you expect to happen?
Install pods. Note that the same configuration and project works fine in other computers (with older cocoapods versions)
* What happened instead?
Pods not installed, and error as below

### Stack

```
   CocoaPods : 0.36.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.10.2 (14C109)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /Users/ios.build/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b7b7873581146a143b66f8d2d65b56b218aa2e07
```

### Plugins

```
cocoapods-plugins : 0.4.1
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.3
```

### Podfile

```ruby
platform :ios, :deployment_target => "7.0"
pod 'CorePlot', '~> 1.4'
pod 'Accept', :path => ENV['POD_ACCEPT']
pod 'SecureNSUserDefaults', '~> 1.0.0'
pod 'CHCSVParser', '~> 2.1'
pod 'ZXingObjC', '~> 3.0'

link_with 'iCashier', 'iCashierTests'

post_install do |installer_representation|
  installer_representation.project.targets.each do |target|
#   if target.name == 'Pods-Accept'
    target.build_configurations.each do |config|
		s = config.build_settings['GCC_PREPROCESSOR_DEFINITIONS']
		s ||= [ '$(inherited)']
		config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] = s 
        if config.name != 'Distribution'
	        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DEV_MODE_ENABLED=1' 
		else
	        config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'DEV_MODE_ENABLED=0'
        end
    end    
#   end 
   target.build_configurations.each do |config|
	   config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
   end
  end
end
```

### Error

```
TypeError - no implicit conversion of nil into String
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/external_sources/abstract_external_source.rb:68:in `extname'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/external_sources/abstract_external_source.rb:68:in `normalized_podspec_path'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/external_sources/path_source.rb:46:in `podspec_path'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/external_sources/path_source.rb:14:in `block in fetch'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/external_sources/path_source.rb:13:in `fetch'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:189:in `analyze'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:111:in `block in resolve_dependencies'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:110:in `resolve_dependencies'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/installer.rb:90:in `install!'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/lib/cocoapods/command.rb:46:in `run'
/Users/ios.build/.rvm/gems/ruby-2.2.0/gems/cocoapods-0.36.1/bin/pod:44:in `<top (required)>'
/Users/ios.build/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/ios.build/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/ios.build/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/ios.build/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by neonichu** [comment] 2015-03-30 13:47
Most likely cause is

```
pod 'Accept', :path => ENV['POD_ACCEPT']
```

and you actually do not have that variable in your environment.

**Comment by kylef** [comment] 2015-03-30 13:49
That's it, and it's a duplicate of #3320 (which is also fixed in master).

**Closed by kylef** 2015-03-30 13:49 UTC
Labels: s1:awaiting input
