### ISSUE TITLE
Cocoapods doesnt download header files

### ISSUE THREAD

**Issue by pikaboo** [CocoaPods/CocoaPods#4562] opened 2015-11-19 20:12 UTC
when i run pod update
I do not get the headerfiles for some reason,
only LICENSE files and markdown files if any
the rest of the folder is empty, though at one time it contained the header files of the given library..

using cocoapod 0.39.0 [image]

![image](https://i.imgur.com/fTGMW47.png)

**Comment by segiddins** [comment] 2015-11-19 23:40
Can you please provide all the information asked for in the contributing guidelines, such as a project that reproduces this issue?

**Comment by pikaboo** [comment] 2015-11-20 05:32
How to reproduce
          pod 'Fabric'
          pod 'Crashlytics'
          pod 'JSONModel'
          pod 'CRToast', '~> 0.0.7'
          pod 'FontAwesomeKit'
          pod 'PKRevealController'
          pod 'Google/Analytics'
          pod 'FMDB/standalone/FTS'

pod install
delete contents of pods project manually (which is what happens when i don't check in the pods project into git, and then clone the project into a new folder)
run pod update
-in theory it should recreate the entire contents of pods project
it recreates only part of the pods project

to fix the project the hard way :
pod --verbose cache clean --all
pod repo remove master
pod --verbose setup
pod --verbose install

**Comment by neonichu** [comment] 2015-11-20 09:02
Can't reproduce this with the given instructions, the sandbox looks identical to an initial `pod install`.

**Comment by neonichu** [comment] 2015-11-26 13:57
Closing because it wasn't reproducible for us.

**Closed by neonichu** 2015-11-26 13:57 UTC
Labels: s1:awaiting input
