### ISSUE TITLE
Codesign fails for explicit app id, Swift project with Swift pod, use_frameworks!

### ISSUE THREAD

**Issue by joshuafinch** [CocoaPods/CocoaPods#4015] opened 2015-08-12 10:59 UTC
Hi there,

I'm trying to archive the project from the command line using an explicit app id `com.mycompany.appname`

`xcodebuild -scheme MyScheme -workspace MyWorkspace.xcworkspace CODE_SIGN_IDENTITY="iPhone Distribution: Some Company (SOMETHING)" PROVISIONING_PROFILE=33fd4574-08ae-447f-a7fb-e345f16e4AAA clean archive -archivePath archiveOutputs/`

> === BUILD TARGET ISO8601IntervalRecurrence OF PROJECT Pods WITH CONFIGURATION Release ===
>
> Check dependencies
> Code Sign error: Provisioning profile does not match bundle identifier: The provisioning profile specified in your build settings (“My Profile Name”) has an AppID of “com.mycompany.appname” which does not match your bundle identifier “org.cocoapods.ISO8601IntervalRecurrence”.
CodeSign error: code signing is required for product type 'Framework' in SDK 'iOS 8.4'
> 
> ** ARCHIVE FAILED **

This only occurs because the PROVISIONING_PROFILE I am attempting to use is explicit, as opposed to wildcard, and therefore cannot match "org.cocoapods..."

**Comment by neonichu** [comment] 2015-08-12 13:06
Looks like a duplicate of #3369, please check if `APP_PROFILE` works for you.

**Closed by neonichu** 2015-08-12 13:06 UTC
