### ISSUE TITLE
The famous third-party framework does not include i386, how can I pass the "pod lib lint"?

### ISSUE THREAD

**Issue by mdsb100** [CocoaPods/CocoaPods#6074] opened 2016-10-24 12:21 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I create a pod repo include the famous third-party framework. The framework does not include i386.

The framework is [TencentOpenAPI](http://qzonestyle.gtimg.cn/qzone/vas/opensns/res/doc/iOS_SDK_V3.1.0.zip). 

You must know Tencent in China! I have to use it in my pod repo!

## What did you expect to happen?

How can I pass the ```pod lib lint```? May I ignore the building of i386?

## What happened instead?

When I run ```pod lib lint```, it failed by missing i386 symbols.

## CocoaPods Environment

```
### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/apple/.rvm/rubies/ruby-2.3.0/lib
Repositories : baidao-ios-ytx-pod-specs - http://gitlab.baidao.com/ios/ytx-pod-specs.git @ ccb4920607fd89f6ac85adb958e06571bfb9d9a6
               master - https://github.com/CocoaPods/Specs.git @ 58cb4955df65e47d5a5405c9e139b81d3a8b472c
```

### Installation Source

```
Executable Path: /Users/apple/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```
```

## Project that demonstrates the issue
[TencentOpenAPI](http://qzonestyle.gtimg.cn/qzone/vas/opensns/res/doc/iOS_SDK_V3.1.0.zip)

**Comment by orta** [comment] 2016-10-24 12:26
This is realistically a dupe of https://github.com/CocoaPods/CocoaPods/issues/5854

**Comment by benasher44** [comment] 2016-10-24 12:30
Yep! I'm going to close this, since it's a dup. I'd like to look at this issue soon, so it's on my radar. Feel free to add any new info to #5854. Thanks for filing!

**Closed by benasher44** 2016-10-24 12:30 UTC
