### ISSUE TITLE
Error when updating pods after cocoa-pods update

### ISSUE THREAD

**Issue by mohamedadly** [CocoaPods/CocoaPods#3969] opened 2015-08-05 08:41 UTC
### Command

```
/usr/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.4 (14E46)
       Xcode : 6.4 (6E35b)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e8f37e3bcbf22a416c39032d5c334a325d257139
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.3.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'

pod 'libPusher'
pod 'NYSegmentedControl'
pod 'JVFloatLabeledTextField'
pod 'TSMessages'
pod 'AFNetworking'
pod 'JSQMessagesViewController'
pod 'ChameleonFramework'
pod 'M13ProgressSuite'
pod 'AMPopTip'
pod 'LPPopupListView'
pod 'MHPrettyDate'
pod 'SVProgressHUD'
pod 'M13BadgeView'
pod 'SDWebImage'
pod 'AWSS3'
pod 'UIImage+Additions'
pod 'BFKit'
pod 'SevenSwitch', '~> 1.4'
pod 'JBWebViewController'
pod 'Parse'
pod 'FMDB'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
```

### Error

```
Errno::ENOENT - No such file or directory - /Users/madly/Documents/DEV/Frontend-iOS-Application/Pods/HockeySDK/Support/HockeySDKTests/OCHamcrestIOS.framework/Headers
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:905:in `symbolic_modes_to_i'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:926:in `fu_mode'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1000:in `block (2 levels) in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1460:in `preorder_traverse'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:998:in `block in chmod_R'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:997:in `chmod_R'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:117:in `block in prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:116:in `prepare'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:103:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by aldo-jlaurenstin** [comment] 2015-08-05 23:05
Any solution for this?

**Comment by mohamedadly** [comment] 2015-08-08 09:45
I had to delete all my installed pods and re-install them again.

**Comment by neonichu** [comment] 2015-08-09 17:32
This is a dupe of #3967

**Closed by neonichu** 2015-08-09 17:32 UTC
