### ISSUE TITLE
Issue with pod that contains a resource_bundle

### ISSUE THREAD

**Issue by idokleinman** [CocoaPods/CocoaPods#4077] opened 2015-08-26 02:17 UTC
My "SparkSetup" pod podspec contains a subspec for a resource bundle:

    s.subspec 'Resources' do |resources|
        resources.resource_bundle = {'SparkSetup' => ['Resources/**/*']}
    end

the Resources folder contains assets catalog of format Images.xcassets (normal xcode format)
My project contains the main lib target and resource-bundle target which contains the storyboard and the asset catalog file.

when trying to `pod lib lint` I get:

```
2015-08-25 18:51:56.495 ruby[12181:184219] warning:  The file reference for "Contents.json" is a member of multiple groups ("1.imageset" and "2.imageset"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
2015-08-25 18:51:56.495 ruby[12181:184219] warning:  The file reference for "Contents.json" is a member of multiple groups ("2.imageset" and "3.imageset"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
2015-08-25 18:51:56.495 ruby[12181:184219] warning:  The file reference for "Contents.json" is a member of multiple groups ("3.imageset" and "AppIcon.appiconset"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
...<redacted>

PBXFileReference -- /targets/buildConfigurationList:buildConfigurations:baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,baseConfigurationReference:|,buildSettings:|,displayName:|,isa:|,name:|,,defaultConfigurationIsVisible:0,defaultConfigurationName:Release,displayName:ConfigurationList,isa:XCConfigurationList,,buildPhases:buildActionMask:2147483647,displayName:SourcesBuildPhase,files:,isa:PBXSourcesBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildActionMask:2147483647,displayName:FrameworksBuildPhase,files:,isa:PBXFrameworksBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildActionMask:2147483647,displayName:ResourcesBuildPhase,files:|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,|,isa:PBXResourcesBuildPhase,runOnlyForDeploymentPostprocessing:0,,buildRules:,dependencies:,displayName:SparkSetup-SparkSetup,isa:PBXNativeTarget,name:SparkSetup-SparkSetup,productName:SparkSetup-SparkSetup,productReference:displayName:SparkSetup.bundle,explicitFileType:wrapper.cfbundle,includeInIndex:0,isa:PBXFileReference,name:SparkSetup.bundle,path:SparkSetup.bundle,sourceTree:BUILT_PRODUCTS_DIR,,productType:com.apple.product-type.bundle,/buildPhases/buildActionMask:2147483647,displayName:ResourcesBuildPhase,files:displayName:1-1.png,fileRef:displayName:|,includeInIndex:|,isa:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:1.imageset,fileRef:displayName:|,includeInIndex:|,isa:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName:1.png,fileRef:displayName:|,includeInIndex:|,isa:|,path:|,sourceTree:|,,isa:PBXBuildFile,,displayName
...<redacted>
```

tool fails and returns an error so I cannot publish the pod.
It used to work fine few cocoapods tool versions ago (don't remember if 0.36 or earlier)

Any ideas?

**Comment by segiddins** [comment] 2015-08-26 03:01
Can you please share the whole podspec so we can try and lint and reproduce the issue? Thanks!

**Comment by idokleinman** [comment] 2015-08-27 00:19
```
Pod::Spec.new do |s|
    s.name             = "SparkSetup"
    s.version          = "0.3.0"
    s.summary          = "Particle iOS Device Setup library for easy integration of setup process for Particle devices in your app"
    s.description      = <<-DESC
                        Particle (formerly Spark) Device Setup library for integrating setup process of Particle devices in your app
                        This library will allow you to easily invoke a standalone setup wizard UI for setting up
                        Particle devices (photon) from within your app. Setup UI look & feel can be easily customized with custom brand
                        logos/colors/fonts/texts and instructional video.
                        DESC
    s.homepage         = "https://github.com/spark/spark-setup-ios"
    s.screenshots      = "http://i58.tinypic.com/15yhdeb.jpg"
    s.license          = 'Apache 2.0'
    s.author           = { "Particle" => "ido@particle.io" }
    s.source           = { :git => "https://github.com/spark/spark-setup-ios.git", :tag => s.version.to_s }
    s.social_media_url = 'https://twitter.com/particle'

    s.platform     = :ios, '8.0'
    s.requires_arc = true

    s.public_header_files = 'Classes/*.h'
    s.source_files  = 'Classes/*.h'
    
    s.subspec 'Resources' do |resources|
        resources.resource_bundle = {'SparkSetup' => ['Resources/**/*.{png,storyboard}']}
    end

    s.subspec 'Core' do |core|
        core.source_files  = 'Classes/User/**/*.{h,m}', 'Classes/UI/**/*'
        core.dependency 'Spark-SDK'
        core.dependency 'SparkSetup/Comm'
        core.dependency 'SparkSetup/Resources'
        core.ios.frameworks    = 'UIKit'
    end

    s.subspec 'Comm' do |comm|
        comm.source_files  = 'Classes/Comm/**/*'
        comm.ios.frameworks    = 'SystemConfiguration', 'Security'
    end



end
```

**Comment by segiddins** [comment] 2015-08-29 18:43
I can't reproduce this using the `master` branches of `SparkSetup` and CocoaPods.

**Comment by chstraube** [comment] 2015-08-29 19:57
Viele Grüße
Christoph Straube

**Comment by manonthemoon42** [comment] 2015-09-29 22:18
@idokleinman Any news about your issue ?

**Comment by segiddins** [comment] 2015-09-29 22:45
Closing since we are never able to reproduce.

**Closed by segiddins** 2015-09-29 22:45 UTC
Labels: s1:awaiting input
