### ISSUE TITLE
REGRESSION: Using Framework target for dynamic libs alongside static target

### ISSUE THREAD

**Issue by flovilmart** [CocoaPods/CocoaPods#6028] opened 2016-10-12 13:57 UTC
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

With CocoaPods v1.0.1, we use an App target and a Framework target. 
For historical reasons, we *need* to have static dependencies for the app target and we use the framework target for the Swift based frameworks. This is a workaround that I recently setup in order for us to have both `use_frameworks!` and not on the same project.

Please see demo project [here](https://github.com/flovilmart/CPDemo): 

When updating to CocoaPods v1.1.0.rc.3, this behaviour was broken, and now running `pod install`  aborts with the following message:

<img width="566" alt="capture d ecran 2016-10-11 a 11 03 30" src="https://cloud.githubusercontent.com/assets/364568/19312259/a2dd2bc2-905f-11e6-9f64-dd5a21684dbf.png">

## What did you expect to happen?

The changes in 1.1.0 should be backward compatible, or at least, make sure the 'hack' is still effective.
Framework targets (as dependencies of the app target) should not be blocked from building.

## What happened instead?

CocoaPods prevents installation of the dependencies as it's strictly enforcing that all targets in the project should either be `use_frameworks!` or not.

### Stack

```
   CocoaPods : 1.1.0.rc.3
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A320)
       Xcode : 8.0 (8A218a)
         Git : git version 2.5.0
Ruby lib dir : /Users/florent/.rvm/rubies/ruby-2.3.0/lib
Repositories : ampme - git@github.com:AmpMe/ampme-podspecs.git @ 8459bcd86da9e3436940e86842405f6b31b8a28d
               master - https://github.com/CocoaPods/Specs.git @ 43398c1104bc10866505e74e6e3b09201c78be47
               mirego - git@github.com:mirego/MCPodSpecs.git @ e54518d6119d2c915dda85a357d37c3346c2559f
```

### Installation Source

```
Executable Path: /Users/florent/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.0.beta.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/flovilmart/CPDemo

**Comment by flovilmart** [comment] 2016-10-12 14:05
@benasher44 In order to make that 'hack' possible there are a few things that one need to do in the project settings:

1. Link frameworks dependencies against the Host project
2. Update the FRAMEWORK_SEARCH_PATH for each target to `"$PODS_CONFIGURATION_BUILD_DIR/[TARGET_NAME]"`
3. Add a script phase: `"${SRCROOT}/Pods/Target Support Files/Pods-CPDemoFWRK/Pods-CPDemoFWRK-frameworks.sh"`

I believe this could be automated by cocoa pods, and would allow us to have non framework dependencies alongside framework dependencies, through a framework target (which actually could very well be the `Pods_TARGET.framework`.

**Comment by benasher44** [comment] 2016-10-12 14:43
@flovilmart as part of 1.1.0, we're adding improved support for frameworks. This means that when you have a framework target, we'll embed all of its pods into the target where your framework is embedded as well. Unfortunately, that does mean that this check/error has to stay. But, I think this means you can remove the extra script phases and things you added. I think we actually might just support the setup you're asking about officially now. Can you try removing the "hacks" you mention there and see if it now "just works"?

**Comment by benasher44** [comment] 2016-10-12 14:43
You'll also need to move the `use_frameworks!` line to the top level in the Podfile.

**Comment by benasher44** [comment] 2016-10-12 14:45
Oh I'm not sure about the "For historical reasons, we need to have static dependencies…" though. If you can't use `use_frameworks!` there, then I'm not sure there's much we can do. You can have a look at throwing together a plugin like this one: https://github.com/orta/cocoapods-expert-difficulty to subvert any checks you think are okay to bypass.

**Comment by flovilmart** [comment] 2016-10-12 15:28
@benasher44 "For historical reasons, we need to have static dependencies…" yes, we need to as we use j2objc and it's a statically compiled library distributed as a `.a` file. I'm not sure we want to use j2objc from source, nor if we can have our vendor use that lib from source either. 

I'll try to use the use framework on top and see how it goes with your suggestion.

**Comment by flovilmart** [comment] 2016-10-12 15:29
That's what I thought: `[!] The 'Pods-Amp' target has transitive dependencies that include static binaries: (/Users/florent/src/ampme/ampme-ios/Pods/J2ObjC@mirego/dist/lib/libjre_emul.a)`

**Comment by benasher44** [comment] 2016-10-12 15:35
You could make a custom podfile for your static lib, and then CocoaPods will handle it properly. Then you can use the :podspec syntax in your Podfile to specify that one.

**Comment by benasher44** [comment] 2016-10-12 15:36
Checkout the vendored library podspec options.

**Comment by flovilmart** [comment] 2016-10-12 15:39
already specified as vendored library I believe: https://gist.github.com/flovilmart/8096520c64227fc0547e0e4c8e32cb8f

**Comment by dnkoutso** [comment] 2016-10-12 15:40
We did not hit this regression but overall we've been hit by the "all or nothing" approach of CocoaPods in terms of mixing Frameworks with static libs. 

It seems that all pods are linked to the top level (app) target rather than the framework itself. 

It would be nice in a later version mixing static libs with frameworks to be better supported.

**Comment by benasher44** [comment] 2016-10-12 15:44
Hm okay. I recommend going with the plugin approach then.

**Comment by flovilmart** [comment] 2016-10-12 15:45
> mixing static libs with frameworks to be better supported. 

That's actually supported through the configuration of a secondary target and some additional configuration in the host. Having the frameworks embedded into the target would definitely help.

**Comment by flovilmart** [comment] 2016-10-12 15:49
@benasher44 what's the rationale for the error? the reasoning and what use case should it cover? AFAIU this error would not be yielded if I was using a separate project with a single framework target right?

**Comment by benasher44** [comment] 2016-10-12 17:37
Here's a [long thread that discusses the issues around supporting static and dynamic deps.](https://github.com/CocoaPods/CocoaPods/issues/2926).

The reason for this error here is because of the way framework dependencies work. AFAIK, you can't dynamically link frameworks into another framework. So instead, what we do is make any target that wants to link the framework managed by cocoapods (because it's in your Podfile) also link the pods that one depends on. For this to be possible, both the framework target and the target linking the framework target have to use the same linking method.

> So instead, what we do is make any target that wants to link the framework managed by cocoapods (because it's in your Podfile) also link the pods that one depends on.

This is sort of what you did by adding those hacks. You made the non-framework target run the  embed script of the framework target, which just embeds the frameworks into the app. So it seems that whether you want to or not, or other target is already using dynamic linking / frameworks.

Does this make sense?

**Comment by flovilmart** [comment] 2016-10-12 17:48
> other target is already using dynamic linking

It's using static linking, as it's linking against `libPods.a`

> AFAIK, you can't dynamically link frameworks into another framework

You're right, but you can do embedding, embedding the child framework targets would work and remove the need for my hack. I'll poke around later today, with a fork of the current master and see if I can create a behaviour that would benefit both worlds.

I'm 100% comfortable with keeping my framework target that would be responsible for all the dynamically linkable frameworks, but what would be nice, it to have the embedding happening, so this way I could reference `import MyFramework.SubFramework` or 

```
import MyFramework

let obj = SubFramework.Class()
```

**Comment by benasher44** [comment] 2016-10-12 17:59
Hm okay. We might be able to support embedding, but I don't have time to work on that kind of  support anytime soon (i.e. next 2-3 weeks). And I think because of the edge cases around pods being shared by multiple targets, I'd probably implement this as a plugin that people could opt-in to. We went with not embedding, since that solution works in more cases, like with extensions where the App Store will reject your app if your extensions have embedded frameworks. For now, it seems your workarounds are the following:

- Manually handle integrating pods into your framework target, so that CocoaPods doesn't know about it and won't try to "help" you
- Fork and modify the linked plugin to help subvert CocoaPods checks that you don't want in your scenario

**Comment by flovilmart** [comment] 2016-10-12 18:06
By skipping: [analyze_host_targets_in_podfile](https://github.com/CocoaPods/CocoaPods/blob/b1094a8a02cb7a1cd09550fea4a1bedc04094e31/lib/cocoapods/installer/analyzer.rb#L360) AND [verify_framework_usage](https://github.com/CocoaPods/CocoaPods/blob/b1094a8a02cb7a1cd09550fea4a1bedc04094e31/lib/cocoapods/installer.rb#L439)

I managed to get the whole thing working, removing all the custom build flags and configuration as well...

**Comment by flovilmart** [comment] 2016-10-12 18:11
Agreed that embedding is not the solution after that discovery. Do you think you'd accept a pull request for 1.1.0 that would add a `authorize_mix_dependencies!` or something in those likes that would let CP go through it and skip the relevant checks?

**Comment by benasher44** [comment] 2016-10-12 18:48
I think we'd be more open to a plugin that allows this behavior, since it feels somewhat special/edge-case-y. The big benefit of a plugin here is that it's a great opportunity to test out something like this without adding new Podfile DSL.

**Comment by flovilmart** [comment] 2016-10-12 19:18
OK for the plugin, but still, that's troubling that the behaviour I expect is 100% functional when dropping those checks. That makes me think, if the behaviour I expect is purposefully rejected but functional, why reject it in the 1st place ?

**Comment by flovilmart** [comment] 2016-10-12 19:46
@benasher44 just to be sure would that be 'correct' https://github.com/flovilmart/cocoapods-mix-frameworks/blob/master/lib/cocoapods-mix-frameworks/lib/mix.rb

**Comment by benasher44** [comment] 2016-10-12 19:52
It's functional in this case, but it doesn't cover cases like extensions which are handle the same way (fall in the category of targets that require a parent target). This also doesn't consider what happens when your framework and another target share a dependency but the other target doesn't use your framework.

I realize that this happened to work previous to 1.1.0, but we didn't have much support for frameworks integration at all previously.

**Comment by benasher44** [comment] 2016-10-12 19:58
Plugin looks good!

**Comment by flovilmart** [comment] 2016-10-12 20:00
Plugin is published as a gem, if I find time, id like to get a better understanding of the cases we want to explicitely reject, and implicitely support. 

Thanks for your time! You guys are doing a tremendous job.

**Comment by benasher44** [comment] 2016-10-12 20:08
No problem! Thank you!

**Comment by k06a** [comment] 2016-10-13 22:08
@flovilmart please tell how to use this plugin in podspec?

**Comment by flovilmart** [comment] 2016-10-13 22:56
That's in the Podfile actually, that would be:


`plugin "cocoapods-mix-frameworks"`

Install it with 

`gem install cocoapods-mix-frameworks`

**Comment by k06a** [comment] 2016-10-14 04:21
@flovilmart thanks, but I have a problem with pushing podspec to trunk, because of dependency: https://github.com/CocoaPods/CocoaPods/issues/6036

**Comment by flovilmart** [comment] 2016-10-14 11:25
Again, that plugin has no effect for a Podspec, it acts on the Podfile

**Comment by benasher44** [comment] 2016-10-14 14:39
Going to close this:

- There's a workaround plugin to help when you know you want to subvert this check.
- Supporting this particular case isn't possible, especially considering another case like when framework A (a target in the Podfile) should embed framework B, but another target (in the Podfile) wants to share framework B but not framework A.
- The error here is important in most extension/framework scenarios to help people resolve conflicts between the Podfile and targets in their projects.

**Closed by benasher44** 2016-10-14 14:39 UTC
Labels: frameworks, t3:discussion

**Comment by benasher44** [comment] 2016-10-14 14:41
Thanks for hashing this out!

**Comment by flovilmart** [comment] 2016-10-14 14:50
> Supporting this particular case isn't possible, especially considering another case like when framework A (a target in the Podfile) should embed framework B, but another target (in the Podfile) wants to share framework B but not framework A. 

@benasher44 I believe when you propagate all frameworks to the App target, that should correctly work as in the end, that would just end up dynamically linking at runtime in the App target. Maybe we can make an exception if that's an app target?

**Comment by benasher44** [comment] 2016-10-14 15:00
I think my main issue is here is that the app target scenario doesn't feel like a special case to me. That seems like the common case. The scenario in this issue where one target can't have `use_frameworks!` seems like the special case, and this scenario is already well by dropping in this plugin (as hacky as some plugins may seem).

**Comment by flovilmart** [comment] 2016-10-14 15:19
Yeah, I'd probably make a PR to reduce the number of skipped checks with the plugin, notably to isolate just that line: https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/installer/analyzer.rb#L335
