### ISSUE TITLE
about pod

### ISSUE THREAD

**Issue by harryzjm** [CocoaPods/CocoaPods#4345] opened 2015-10-08 16:01 UTC
Yesterday , I had install OS X EI  
pod is disappear, So I uninstall cocoapod, and want to reinstall cocoapod again, But gem is broken to install cocoapods  
So I install rvm, and install ruby 2.2.1, and then , install cocoapods success  
But , When I try to 'pod install '  is error  

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.3.0dev (2015-10-07 trunk 52075) [x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /Users/Hares/.rvm/rubies/ruby-head/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
pod 'ReactiveCocoa', '~> 2.5'
pod 'JHChainableAnimations', '~> 1.2.0'
pod 'Masonry', '~> 0.6.1'
pod 'pop', '~> 1.0.7'
pod 'CocoaLumberjack', '~> 2.0.0'
pod 'RNThemeManager', '~> 0.1.0'
pod 'AFNetworking', '~> 2.5.4'
pod 'Reachability', '~> 3.2'
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworking">
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:63:in `tap'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/Hares/.rvm/gems/ruby-head/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/Hares/.rvm/gems/ruby-head/bin/pod:23:in `load'
/Users/Hares/.rvm/gems/ruby-head/bin/pod:23:in `<main>'
/Users/Hares/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
/Users/Hares/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

---TEMPLATE---

[!] Oh no, an error occurred.

Please help me ,Thanks a lot

**Comment by segiddins** [comment] 2015-10-08 23:07
I can't reproduce this with the given Podfile -- could you share a complete project that exhibits the issue? Thanks!

**Comment by harryzjm** [comment] 2015-10-11 13:10
@segiddins Thank you for your respond  
I have try another project. it is also go run. the error is blow:
Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Finding Podfile changes
  - AFJSONRPCClient
  - AFNetworking
  - ASIHTTPRequest
  - FMDB
  - Masonry
  - PureLayout
  - ReactiveCocoa
  - SSKeychain
  - pop

Resolving dependencies of `Podfile`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/Hares/.rvm/gems/ruby-head/bin/pod install --verbose --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.3.0dev (2015-10-07 trunk 52075) [x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11 (15A284)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /Users/Hares/.rvm/rubies/ruby-head/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f5895a1a94758ae2f9a261315246f1e2560bc1a2
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

pod 'AFJSONRPCClient', '~> 2.1.1'
pod 'PureLayout', '~> 2.0.6'
pod 'ASIHTTPRequest', '~> 1.8.2'
pod 'AFNetworking', '~> 2.5.4'
pod 'FMDB', '~> 2.5'
pod 'SSKeychain', '~> 1.2.3'
pod 'Masonry', '~> 0.6.2'
pod 'ReactiveCocoa', '~> 2.5'
pod 'pop', '~> 1.0.7'
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFJSONRPCClient">
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:63:in `tap'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:535:in `block in resolve_dependencies'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:533:in `resolve_dependencies'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:210:in `analyze'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:133:in `block in resolve_dependencies'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:132:in `resolve_dependencies'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:104:in `install!'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/Users/Hares/.rvm/gems/ruby-head/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Users/Hares/.rvm/gems/ruby-head/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/Users/Hares/.rvm/gems/ruby-head/bin/pod:23:in `load'
/Users/Hares/.rvm/gems/ruby-head/bin/pod:23:in `<main>'
/Users/Hares/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
/Users/Hares/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by harryzjm** [comment] 2015-10-11 13:14
@segiddins I think, This has no relationship for the project,  before I install OS X EI, all project is right, When I after install it, all thing went wrong

**Comment by hirakujira** [comment] 2015-10-12 13:38
Same here

Analyzing dependencies

Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MicroLearning`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MicroLearningTests`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MicroLearningUITests`: (``)

Resolving dependencies of `Podfile`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/Hiraku/.rvm/rubies/ruby-head/bin/pod install --verbose --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0dev (2015-09-15 trunk 51867) [x86_64-darwin15]
    RubyGems : 2.5.0
        Host : Mac OS X 10.11.1 (15B30a)
       Xcode : 7.0.1 (7A1001)
         Git : git version 2.3.8 (Apple Git-58)
Ruby lib dir : /Users/Hiraku/.rvm/rubies/ruby-head/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a1997a2c25d18e3bf0f0b58dcebb83d6e74a1a43
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!

target 'xxxxx' do
	pod 'MBAutoGrowingTextView', '~> 0.1.0'
end

target 'xxxx' do

end

target 'xxx' do

end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="MBAutoGrowingTextView">
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/Hiraku/.rvm/gems/ruby-head@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/Hiraku/.rvm/rubies/ruby-head/bin/pod:23:in `load'
/Users/Hiraku/.rvm/rubies/ruby-head/bin/pod:23:in `<main>'
/Users/Hiraku/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `eval'
/Users/Hiraku/.rvm/gems/ruby-head/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

**Comment by segiddins** [comment] 2015-10-12 15:43
I'm guessing this has to do with both of you running Ruby master, I'm building it right now so I can investigate but I already have a really simple fix in mind.

**Comment by harryzjm** [comment] 2015-10-13 14:50
@segiddins @hirakujira  I found a way to solve this problem  
1.  gem uninstall cocoapods
2.  install ruby 2.2.0 (this problem is occur in ruby 2.3, I am sure this, I used rvm to install ruby 2.2.0)
3.  gem install cocoapods
All thing is ok

**Comment by segiddins** [comment] 2015-10-13 14:52
Yeah, this has already been fixed on master

**Comment by pjc0247** [comment] 2015-10-30 01:37
Is there any pre-release version including this fix?

The latest version of Pod(0.39.0) seems still unresolved.

**Comment by segiddins** [comment] 2015-10-30 01:38
No, as I said, this is fixed on master but there hasn't been a release since 0.39

**Comment by pjc0247** [comment] 2015-10-30 01:40
Understood,
Thank you for the super quick response.

**Comment by susemi99** [comment] 2015-12-26 08:17
same issue.

I did
* install ruby 2.3.0 by rbenv
* install only cocoapods
* run pod update

### Command

```
/Users/susemi99/.rbenv/versions/2.3.0/bin/pod update
```

### Report

* What did you do? 

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/susemi99/.rbenv/versions/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 680c7d0538241a7c4a5ea732cdc9375ee9f7a2a0
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks! 

pod 'RealmSwift'
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Realm">
Did you mean?  to_query
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/susemi99/.rbenv/versions/2.3.0/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/susemi99/.rbenv/versions/2.3.0/bin/pod:23:in `load'
/Users/susemi99/.rbenv/versions/2.3.0/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment] 2015-12-26 14:18
@susemi99 this issue is fixed on master

**Comment by hieuvo** [comment] 2016-03-05 11:45
I got the same issue, downgrade ruby to 2.2.1 will help

**Comment by adrianbrink** [comment] 2016-03-19 18:00
On ruby 2.4 this issue appears again :-(

**Comment by sharat** [comment] 2016-03-19 19:33
Took the pain to install Ruby `2.2.4` with rbenv.

**Comment by orta** [comment] 2016-03-19 23:14
This is fixed in the 1.0 betas, please don't comment unless you have something new to add.

**Closed by orta** 2016-03-19 23:14 UTC
Labels: d1:easy, s4:awaiting validation, t2:defect

**Comment by saturne** [comment] 2016-03-24 19:29
Hi. I understand that this issue has been fixed in master but what are the steps that I need to take to correct this in terminal?

**Comment by sharat** [comment] 2016-03-25 16:19
I have couple of observations to share. 

- My project runs on Xcode 7.2. 
- I competely uninstalled the gem and removed the all depended gems as well. 
- Installed cocoapds again with `sudo gem install cocoapods --pre`
- Pod has upgrade the project determining serious changes in the pod. `pod install` was successful and all gems were updated. 
- Compiling code mentioned pbxcp file not found error.

I'm not quite sure what to do with it. I have installed Ruby 2.2.4 with rbenv. Installed the stable release gem after removing all previous installations. The issue has been resolved with that. Anyone else faced similar issues?

**Comment by ukd1** [comment] 2016-04-01 02:06
is this ever being releaseS?

**Comment by segiddins** [comment] 2016-04-01 02:25
@ukd1 yeah, it's been released in the 1.0 betas for the past few months

**Comment by wkoszek** [comment] 2016-04-10 08:12
I have nothing new to add. My issue is exactly the same as other guys explained: El Capitain + Ruby 2.3.0 installed with RVM. Is `gem install cocoapods` unsupported? Seems like I need to do install with `--pre` not to hit this with 2.3.0.

**Comment by relong1379** [comment] 2016-04-26 01:48
How to fix it


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1ba2bc3280b3ecb0d9821622e8b30ee69d8eba56
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '7.0'
inhibit_all_warnings!
# Uncomment this line if you're using Swift
# use_frameworks!

target 'YuanDing' do

pod 'AFNetworking', '~> 3.0'
pod 'SDWebImage', '~> 3.7'
pod 'MJRefresh'
pod 'MJExtension'
pod 'FMDB', '2.5'
pod 'Masonry', '~> 0.6.2'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'UMengAnalytics'
pod 'SSKeychain', '1.2.3'
pod 'CocoaLumberjack', '~> 2.2.0'
pod 'JDStatusBarNotification', '~> 1.5.3'
pod 'HMSegmentedControl', '~> 1.5.2'
pod 'YYKit', '~> 0.9.11'

end

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworking">
Did you mean?  to_query
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

**Comment by vrao423** [comment] 2016-05-09 22:09
@orta @segiddins currently having this issue. would be nice if the fix was backported to current release version.

**Comment by viniciodeltoro** [comment] 2016-07-13 02:07
I was having the same issue and updating cococapods to 1.1.0.beta.1 fixed the issue. I'm using Ruby 2.3.1
