### ISSUE TITLE
JSON::ParserError - 416: unexpected token at '{       "name": "Button'

### ISSUE THREAD

**Issue by NomanTassawar** [CocoaPods/CocoaPods#9673] opened 2020-04-01 14:00 UTC
# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod install`

## What did you expect to happen?

ℹ Install all pod dependencies correctly. 

## CocoaPods Environment

ℹ
### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.4 (19E266)
       Xcode : 11.4 (11E146)
         Git : git version 2.24.1 (Apple Git-126)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'Gatekeyper' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for Gatekeyper
pod 'MaterialComponents/TextFields'
pod 'RYFloatingInput'
pod 'MaterialComponents/TextFields+ColorThemer'
pod 'MaterialComponents/schemes/Color'
pod 'CryptoSwift', '~> 1.0'
pod 'ReachabilitySwift’, ‘~> 3’
pod 'SwiftDate'
pod 'MBProgressHUD', '~> 1.1.0'
pod 'Alamofire', '~> 4.0'
pod 'SwiftyJSON', '~> 4.0'
pod "SkeletonView"

pod 'Firebase/Analytics'

# Pods for PodTest
pod 'Fabric', '~> 1.10.2'
pod 'Crashlytics', '~> 3.14.0'

end
```

**Comment by dnkoutso** [comment] 2020-04-01 16:03
Marking as duplicate of https://github.com/CocoaPods/CocoaPods/issues/9672 please continue discussion there.

**Closed by dnkoutso** 2020-04-01 16:03 UTC

**Comment by NomanTassawar** [comment] 2020-05-21 00:48
> Marking as duplicate of #9672 please continue discussion there.

Thanks @dnkoutso for your help.
I solved this problem by specifying version of Pod in Podfile
pod 'MaterialComponents/TextControls+FilledTextFields', '~> 109.4.0'
