### ISSUE TITLE
include of non-modular header inside framework module

### ISSUE THREAD

**Issue by aleph7** [CocoaPods/CocoaPods#4452] opened 2015-10-27 05:30 UTC
When trying to update the pod spec of my iOS/OSX Swift framework I get `HDF5Kit.h:11:9: error: include of non-modular header inside framework module 'HDF5Kit.HDF5Kit'`. I double checked that all those headers are marked as public. It works fine in Xcode. Also, version 0.0.4 works fine just a few commits ago. Any ideas?

repo: https://github.com/aleph7/HDF5Kit
pod spec: https://github.com/aleph7/HDF5Kit/blob/master/HDF5Kit.podspec
pod --version: 0.39.0

**Comment by segiddins** [comment] 2015-10-27 05:38
This is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/4420, and seems to be caused by some breaking change that shipped in Xcode 7.1.

**Closed by segiddins** 2015-10-27 05:38 UTC

**Comment by aleph7** [comment] 2015-10-27 05:52
Thanks. FYI fixed by removing the umbrella header `HDF5Kit.h` from the `public_headers` in the pod spec, seems to conflict with the CP-generated one.
