### ISSUE TITLE
Pod install fails with Xcode 7 beta 2 (7A121I)

### ISSUE THREAD

**Issue by jessesquires** [CocoaPods/CocoaPods#3748] opened 2015-06-27 19:15 UTC
:rainbow: 

#### Setup
````
Cocoapods 0.37.2
OS X 10.10.3
Xcode 7.0 (7A121I)
````

#### Xcode Project
Create a new Xcode project using the "Single View Application" template and Swift.

#### Podfile
````ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

# All Swift 2.0 Cocoa Touch frameworks
pod 'JSQDataSourcesKit', :git => 'https://github.com/jessesquires/JSQDataSourcesKit.git', :branch => 'release-2.0'
pod 'JSQNotificationObserverKit', :git=> 'https://github.com/jessesquires/JSQNotificationObserverKit.git', :branch => 'release-2.0'
pod 'JSQCoreDataKit', :git => 'https://github.com/jessesquires/JSQCoreDataKit.git', :branch => 'release-2.0'
````

#### Error
````bash
$ pod install --verbose
  Preparing

Analyzing dependencies

Updating spec repositories
Updating spec repo `master`
  $ /usr/local/bin/git pull --ff-only
  Already up-to-date.

CocoaPods 0.38.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.


Inspecting targets to integrate
  Using `ARCHS` setting to build architectures of target `Pods`: (``)

Fetching external sources
-> Pre-downloading: `JSQCoreDataKit` from `https://github.com/jessesquires/JSQCoreDataKit.git`, branch `release-2.0`
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/jessesquires/JSQCoreDataKit.git /var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/d20150627-64065-kabfyn --single-branch --depth 1
     --branch release-2.0
     Cloning into '/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/d20150627-64065-kabfyn'...
  > Copying JSQCoreDataKit from `/Users/jesse/Library/Caches/CocoaPods/Pods/External/JSQCoreDataKit/62c24114177a74e52937365da80bccb5` to `Pods/JSQCoreDataKit`
-> Pre-downloading: `JSQDataSourcesKit` from `https://github.com/jessesquires/JSQDataSourcesKit.git`, branch `release-2.0`
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/jessesquires/JSQDataSourcesKit.git /var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/d20150627-64065-1fsqlmf --single-branch
     --depth 1 --branch release-2.0
     Cloning into '/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/d20150627-64065-1fsqlmf'...
  > Copying JSQDataSourcesKit from `/Users/jesse/Library/Caches/CocoaPods/Pods/External/JSQDataSourcesKit/f717d9c39af3ae351a4f164e7178638f` to `Pods/JSQDataSourcesKit`
-> Pre-downloading: `JSQNotificationObserverKit` from `https://github.com/jessesquires/JSQNotificationObserverKit.git`, branch `release-2.0`
 > Git download
 > Git download
     $ /usr/local/bin/git clone https://github.com/jessesquires/JSQNotificationObserverKit.git /var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/d20150627-64065-cgocwq
     --single-branch --depth 1 --branch release-2.0
     Cloning into '/var/folders/tx/s__fjnns3yd_23813_gwk7sh0000gn/T/d20150627-64065-cgocwq'...
  > Copying JSQNotificationObserverKit from `/Users/jesse/Library/Caches/CocoaPods/Pods/External/JSQNotificationObserverKit/b39f6bb03bd90e4b655d7ff0fa6543ef` to
  `Pods/JSQNotificationObserverKit`

Resolving dependencies of `Podfile`
Starting resolution (2015-06-27 12:13:01 -0700)
Creating possibility state for JSQDataSourcesKit (from `https://github.com/jessesquires/JSQDataSourcesKit.git`, branch `release-2.0`) (1 remaining)
  Attempting to activate JSQDataSourcesKit (2.0.0)
  Activated JSQDataSourcesKit at JSQDataSourcesKit (2.0.0)
  Requiring nested dependencies ()
  Creating possibility state for JSQNotificationObserverKit (from `https://github.com/jessesquires/JSQNotificationObserverKit.git`, branch `release-2.0`) (1 remaining)
    Attempting to activate JSQNotificationObserverKit (2.0.0)
    Activated JSQNotificationObserverKit at JSQNotificationObserverKit (2.0.0)
    Requiring nested dependencies ()
    Creating possibility state for JSQCoreDataKit (from `https://github.com/jessesquires/JSQCoreDataKit.git`, branch `release-2.0`) (1 remaining)
      Attempting to activate JSQCoreDataKit (2.0.0)
      Activated JSQCoreDataKit at JSQCoreDataKit (2.0.0)
      Requiring nested dependencies ()
Finished resolution (3 steps) (Took 0.002493 seconds) (2015-06-27 12:13:01 -0700)
Unactivated: 
Activated: JSQDataSourcesKit, JSQNotificationObserverKit, JSQCoreDataKit

Comparing resolved specification to the sandbox manifest
  A JSQCoreDataKit
  A JSQDataSourcesKit
  A JSQNotificationObserverKit

Downloading dependencies

-> Installing JSQCoreDataKit (2.0.0)

-> Installing JSQDataSourcesKit (2.0.0)

-> Installing JSQNotificationObserverKit (2.0.0)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Pods-JSQCoreDataKit` iOS 9.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-JSQCoreDataKit/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-JSQCoreDataKit/Pods-JSQCoreDataKit.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-JSQCoreDataKit/Pods-JSQCoreDataKit-umbrella.h`
    - Installing target `Pods-JSQDataSourcesKit` iOS 9.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-JSQDataSourcesKit/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-JSQDataSourcesKit/Pods-JSQDataSourcesKit.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-JSQDataSourcesKit/Pods-JSQDataSourcesKit-umbrella.h`
    - Installing target `Pods-JSQNotificationObserverKit` iOS 9.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-JSQNotificationObserverKit/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-JSQNotificationObserverKit/Pods-JSQNotificationObserverKit.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-JSQNotificationObserverKit/Pods-JSQNotificationObserverKit-umbrella.h`
    - Installing target `Pods` iOS 9.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods/Pods.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods/Pods-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
2015-06-27 12:13:01.834 ruby[64065:2720860] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8123.33/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7f8985365840>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x0000000105fd8047 -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x0000000105fd77d4 _DVTAssertionHandler (in DVTFoundation)
  2  0x0000000105fd7a40 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x0000000105fd79a2 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x000000010733c1a9 IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000010b2aba5d +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x000000010b2ad5e2 +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff8b66df44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6
````

#### Related

The following issues might be related: #3720, #3745

**Comment by jessesquires** [comment] 2015-06-27 19:17
Switching to command line tools `Xcode 6.3.2 (6D2105)` succeeds.

**Comment by segiddins** [comment] 2015-06-27 19:39
Yup, this is a duplicate of https://github.com/CocoaPods/Xcodeproj/issues/278, which should be fixed by https://github.com/CocoaPods/Xcodeproj/pull/280!

**Closed by segiddins** 2015-06-27 19:39 UTC
