### ISSUE TITLE
Too many input, output paths cause a build failure

### ISSUE THREAD

**Issue by casatwy** [CocoaPods/CocoaPods#7362] opened 2018-01-24 08:03 UTC
> the error says:

```
BUILD FAILED
Verify final result code for completed build operation
Build operation failed without specifying any errors. Individual build tasks may have failed for unknown reasons.
One possible cause is if there are too many (possibly zombie) processes; in this case, rebooting may fix the problem.
Some individual build task failures (up to 12) may be listed below.
```

> how to make this happen:

We put about 1700 images into this pod (in our project we do need that much...) at the path of `BLiOSAppImages/Images/*.png`, then publish this pod using `pod repo push XXXRepoHouse BLiOSAppImages.podspec --verbose --allow-warnings --use-libraries`

I am sure that this pod have nothing but images, no source code, no libs, only images. But it just can not build success to publish...

> what I have tried

1. I tried to create a new empty project, using `:path => '/pod/path'` in the podfile point to the 1700-image-pod, and run `pod install` then build this empty project, it can not work either, the build error remains the same.

2. If I just put one image into it, it works fine. Or if using cocoapods 1.2.1 it works fine, too.

3. reboot not works

4. using `kill $(ps -A -ostat,ppid | awk '/[zZ]/{print $2}')` to kill zombie proccess, and then build, not works.

> you can use this script to generate 1700 images:

```
#!/bin/bash
mkdir -p Images
for i in {1..1700}
do
    echo "cp temp.png ./Images/$i.png"
    cp temp.png ./Images/$i.png
done
```

> the pod spec is:

```
Pod::Spec.new do |s|
  s.name         = "BLiOSAppImages"
  s.version      = "535"
  s.summary      = "BLiOSAppImages."
  s.description  = 
<<-DESC
                    this is BLiOSAppImages
                   DESC
  s.homepage     = "https://xxx.xxx.com/iOS/BLiOSAppImages"
  s.license      = { :type => "MIT", :file => "FILE_LICENSE" }
  s.author             = { "xxx" => "xxx@xxx.com" }
  s.platform     = :ios, "8.0"
  s.source       = { :git => "https://xxx.xxx.com/iOS/BLiOSAppImages.git", :tag => s.version.to_s }
  s.ios.resources = ["BLiOSAppImages/Images/*.png", "BLiOSAppImages/Fonts/*.ttf"]
  s.requires_arc = true

end
```

> other information you may need

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.13.2 (17C205)
       Xcode : 9.2 (9C40b)
         Git : git version 2.15.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : BLRepositories - https://xxx.xxx.com/iOS/BLRepositories.git @ f82d79a9e92f4c919d236b5fb0b15dfa1530aefd
               master - https://github.com/CocoaPods/Specs.git @ d8769f40e52f8faa0b47648a3f50ebcbc1733dbe
               TestRepoStory - https://xxx.xxx.com/tianweiyu/TestRepoStory.git @ 97d1766a639669ffc49af36cab27d7d136648770
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment] 2018-01-24 08:38
Do you mean to use `resources` or `resource_bundle`? Also can you build the same target in xcode without CocoaPods?

Can you please run `lint` using `--verbose` flag so we can get more context on the issue here?

**Comment by casatwy** [comment] 2018-01-24 08:50
1. I'm using `resources` not `resource_bundle`

2. I can build the 1700-image-pod project successfully, it do not need cocoapods because it has nothing but images. 

3. I'm using `pod repo lint /path/to/BLiOSAppImages --verbose` and it says:

```
Linting spec repo `BLiOSAppImages`

[!] An unexpected version directory `Assets.xcassets` was encountered for the `/Users/casa/Playground/BLiOSAppImages/BLiOSAppImages` Pod in the `BLiOSAppImages` repository.

/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source.rb:169:in `rescue in block in versions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source.rb:166:in `block in versions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source.rb:164:in `map'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source.rb:164:in `versions'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source/health_reporter.rb:50:in `block in analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source/health_reporter.rb:49:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-core-1.4.0/lib/cocoapods-core/source/health_reporter.rb:49:in `analyze'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/repo/lint.rb:55:in `block in run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/repo/lint.rb:47:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command/repo/lint.rb:47:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.4.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

```

**Comment by dnkoutso** [comment] 2018-01-24 09:00
can you please upload a sample project to demonstrate the issue?

**Comment by casatwy** [comment] 2018-01-24 09:12
here is the repo:

 `https://github.com/casatwy/TheDeadPodWithOnlyImages.git`

you create an empty project, and add `pod "TheDeadPodWithOnlyImages", :path => 'path/to/TheDeadPodWithOnlyImages' ` in the Podfile, `pod update` then build this project

you will see this issue.

**Comment by dnkoutso** [comment] 2018-01-24 17:59
@casatwy confirmed, the problem has to do with the large number of input/output paths added to the "Copy Pods Resources" script phase.

Seems like we might need to provide an option to disable those. I was able to successfully build with removing the input and output paths.

**Comment by casatwy** [comment] 2018-01-24 18:37
thank you！

**Comment by dnkoutso** [comment] 2018-01-24 18:45
@casatwy this is more or less an Xcode issue though not directly a CocoaPods issue, going to file a radar for this.

Workaround for you is to use a `resource_bundle` instead:

```ruby
  s.resource_bundle = { 'TheDeadPodWithOnlyImagesResources' => 'TheDeadPodWithOnlyImages/Images/*.png' }
```

This one worked for me and you will be able to publish.

**Comment by dnkoutso** [comment] 2018-01-24 19:15
Filed bug https://bugreport.apple.com/web/?problemID=36831832

**Comment by dnkoutso** [comment] 2018-01-24 19:17
@casatwy I do not think there is a lot for us to do here, we do not plan to provide an option to disable input/output paths. Your best bet is to use `resource_bundle` instead or you can split the podspec into multiple ones of 600 images each. Seems like somewhere near 800 is the limit input/output paths before this error starts happening.

Alternatively you can wait for Xcode and Apple to fix the issue above which might take a while :)

Going to close this since we will not be doing anything for CocoaPods here.

**Comment by casatwy** [comment] 2018-01-25 05:06
ok

**Comment by segiddins** [comment] 2018-01-25 17:15
I agree that the short-term fix is using resource bundles. 

But after thinking about it, we should probably split the build phases into chunks of a few hundred input/output paths, to ensure `env` is able to hold all of the entries.

**Comment by dnkoutso** [comment] 2018-01-31 16:11
Renamed the title to make it more generic, this issue remains.

**Closed** 2018-01-31 19:42 UTC
Labels: d2:moderate, s2:confirmed, t2:defect
