### ISSUE TITLE
Setting IPHONEOS_DEPLOYMENT_TARGET when using :generate_multiple_pod_projects

### ISSUE THREAD

**Issue by gereons** [CocoaPods/CocoaPods#10162] opened 2020-10-21 10:56 UTC
* [🌈] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod install` with this Podfile:

```
source 'https://cdn.cocoapods.org/'
use_frameworks! :linkage => :static
inhibit_all_warnings!

install! 'cocoapods', :generate_multiple_pod_projects => true

deployment_target = '13.0'
platform :ios, deployment_target

target 'DeploymentTargetTest' do
    pod 'SDCAlertView'
end

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
            end
        end
    end
end
```

As you can see, I'm using the post-install hook to set the deployment target, but this does not appear to set it everywhere it's needed:

```
$ grep -r IPHONEOS_DEPLOYMENT_TARGET Pods
Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
Pods/Pods.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
Pods/SDCAlertView.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Pods/SDCAlertView.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
Pods/SDCAlertView.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
Pods/SDCAlertView.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 9.0;
Pods/SDCAlertView.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
Pods/SDCAlertView.xcodeproj/project.pbxproj:				IPHONEOS_DEPLOYMENT_TARGET = 13.0;
```

Are there any other post-install actions that are required to update the remaining IPHONEOS_DEPLOYMENT_TARGET settings, which are apparently the ones Xcode is looking at?

## What did you expect to happen?

Compilation without warnings, all deployment target settings updated to 13.0

## What happened instead?

I'm seeing a warning to update the project settings for `SDCAlertView`: "Update the minimum deployment target of project 'SDCAlertView' to '12.0'"

## CocoaPods Environment

Cocoapods 1.10, Xcode 12.1, running on macOS 10.15.7

## Project that demonstrates the issue

https://github.com/gereons/DeploymentTargetTest

**Comment by dnkoutso** [comment] 2020-10-21 17:03
You are not changing the projects root object deployment target:

<img width="1792" alt="Screen_Shot_2020-10-21_at_9_58_00_AM" src="https://user-images.githubusercontent.com/310370/96753185-581f7700-1384-11eb-9247-4ae4a3b836b8.png">

This could be a tiny bug in cocoapods but workaround is 

```ruby
post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
            end
        end
        project.root_object.build_configuration_list.build_configurations.each do |bc|
            bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = deployment_target
        end
    end
end
```

**Comment by dnkoutso** [comment] 2020-10-21 17:08
Ah this may be working as intended actually. The platform of the root object is determined by the pods it includes. In this case SDCAlertView sets its deployment target to 9.0. 

So the workaround here is the correct way to fix this and I do not think we should change this logic into cocoapods.

Closing for now.

**Closed by dnkoutso** 2020-10-21 17:08 UTC
Labels: d1:easy, s2:confirmed, s7:workaround available, t2:defect

**Comment by gereons** [comment] 2020-10-22 11:13
Thanks! That workaround is just what I was looking for :)

**Comment by xyreryp** [comment] 2021-02-05 21:38
Thanks a lot! This works for our project!
