### ISSUE TITLE
Strange quotes in Podfile.lock?!

### ISSUE THREAD

**Issue by Bayonetta** [CocoaPods/CocoaPods#6255] opened 2016-11-30 08:05 UTC
The following contents is my footer content in Podfile.lock:

```
SPEC CHECKSUMS:

  RxSwift: af5680055c4ad04480189c52d28385b1029493a6
  SDWebImage: '098e97e6176540799c27e804c96653ee0833d13c'
  ...


PODFILE CHECKSUM: 1985f3107c446b3ecb03cb8e483a9dea9f528a77

COCOAPODS: 1.2.0.beta.1
```

Why is the SDWebImage's checksum within double quotations?

Maybe Some bugs for cocoapods-1.2.0.beta.1?

But my colleagues don't have this problem. And I'm sure we are using the same version for cocoapods. It will leading llvm reporting error when compiling.

![](https://i.stack.imgur.com/FwsNr.png)

I also edit the problem in stackoverflow. Could anyone explain it?

http://stackoverflow.com/questions/40861472/why-are-there-double-quotes-in-my-podfile-lock-file

**Comment by jklausa** [comment] 2016-12-01 14:17
Hey, we're also seeing this issue — one of our developers computer is generating those while all other machines choke up on the quotes. Anything we could do to help with debugging?

**Comment by orta** [comment] 2016-12-01 14:25
Hey there, this is a dupe of https://github.com/CocoaPods/CocoaPods/issues/5585 and https://github.com/CocoaPods/CocoaPods/issues/4740 - summary, you have developers with different versions of psyche https://github.com/CocoaPods/CocoaPods/issues/5585#issuecomment-263981765

**Closed by orta** 2016-12-01 14:25 UTC
