### ISSUE TITLE
Is there a way to make ObjC-Swift mix pod support custom module map?

### ISSUE THREAD

**Issue by qhhonx** [CocoaPods/CocoaPods#9138] opened 2019-09-02 06:15 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

![image](https://user-images.githubusercontent.com/2561942/64093355-96c22e80-cd8a-11e9-9aa6-11114fb4741e.png)

## CocoaPods Environment

`gem 'cocoapods', '1.6.1'`

The issued `IMRPartyModule` is our dedicated pod with `:modular_headers => true` in podfile and `s.module_map = /path/to/IMRPartyModule.modulemap` in podspec. Besides, `IMRPartyModule` is a mix pod that contains both ObjC and Swift codes. If using default modulemap with `:modular_headers => true` or just removing `:modular_headers => true`, there is no error occurred on `pod install` stage.

**Comment by dnkoutso** [comment] 2019-09-02 15:18
Not currently as the message suggests. Issue is duplicate of https://github.com/CocoaPods/CocoaPods/issues/9023 closing for now and we can continue discussion there.

**Closed by dnkoutso** 2019-09-02 15:18 UTC
