### ISSUE TITLE
library not found for -lPods-Kaboodle_iPhone-AFNetworking clang: error: linker command failed with exit code 1 (use -v to see invocation)

### ISSUE THREAD

**Issue by NewPersonal** [CocoaPods/CocoaPods#4171] opened 2015-09-13 07:26 UTC
Pod file looks like 
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

target 'Kaboodle_iPhone' do

pod 'CocoaLumberjack', '2.0.0'
pod 'RESideMenu', '~> 4.0.7'
pod 'SDWebImage', '~>3.6'
pod 'iCarousel','~>1.8.1'
pod 'VideoCore', '~> 0.2.0'
pod 'FLAnimatedImage', '~> 1.0'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'google-plus-ios-sdk'
pod 'GoogleMaps'
pod 'AFNetworking', '2.5.0'
end

target 'Kaboodle_iPhoneTests' do

end
***********************************************************************************************************************
Cocoapod version used :  0.38.2
Xcode Version: 7.0 (7A218)

***********************************************************************************************************************
Error Details
ld: library not found for -lPods-Kaboodle_iPhone-AFNetworking
Ld Build/Products/Debug-iphoneos/Kaboodle_iPhone.app/Kaboodle_iPhone normal armv7
    cd /Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone
    export IPHONEOS_DEPLOYMENT_TARGET=8.1
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch armv7 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneOS.platform/Developer/SDKs/iPhoneOS9.0.sdk -L/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Build/Products/Debug-iphoneos -L/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/XMPP_iPhone/Vendor/libidn -L/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/RTMP_iOSLib/CommLibiOS -L/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/RTMP_iOSLib/ffmpeg-2.2.1/lib -L/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/RTMP_iOSLib/libspeex-1.2rc1/lib -L/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/RTMP_iOSLib/libx264-r2409/lib -L/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/RTMP_iOSLib/MediaLibiOS -F/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Build/Products/Debug-iphoneos -F/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Pods/GoogleMaps/Frameworks -F/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Pods/google-plus-ios-sdk/google-plus-ios-sdk-1.7.1 -F/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/Replay -F/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/oovoo -F/Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty -filelist /Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Build/Intermediates/Kaboodle_iPhone.build/Debug-iphoneos/Kaboodle_iPhone.build/Objects-normal/armv7/Kaboodle_iPhone.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -miphoneos-version-min=8.1 -dead_strip -fembed-bitcode-marker -ObjC -lPods-Kaboodle_iPhone-AFNetworking -lPods-Kaboodle_iPhone-CocoaLumberjack -lPods-Kaboodle_iPhone-RESideMenu -lPods-Kaboodle_iPhone-SDWebImage -lPods-Kaboodle_iPhone-iCarousel -framework CoreGraphics -framework ImageIO -framework MobileCoreServices -framework QuartzCore -framework Security -framework SystemConfiguration -ObjC -lAFNetworking -lBolts -lCocoaLumberjack -lFBSDKCoreKit -lFBSDKLoginKit -lFBSDKShareKit -lFLAnimatedImage -lRESideMenu -lSDWebImage -lUriParser-cpp -lVideoCore -lc++ -liCarousel -licucore -lz -framework AVFoundation -framework Accelerate -framework AddressBook -framework AssetsLibrary -framework AudioToolbox -framework CFNetwork -framework CoreBluetooth -framework CoreData -framework CoreGraphics -framework CoreLocation -framework CoreMedia -framework CoreMotion -framework CoreText -framework CoreVideo -framework Foundation -framework GLKit -framework GoogleMaps -framework GoogleOpenSource -framework GooglePlus -framework ImageIO -framework MediaPlayer -framework MobileCoreServices -framework OpenGLES -framework QuartzCore -framework Security -framework SystemConfiguration -framework UIKit -framework VideoToolbox -weak_framework Accounts -weak_framework AudioToolbox -weak_framework CoreGraphics -weak_framework CoreLocation -weak_framework Foundation -weak_framework QuartzCore -weak_framework Security -weak_framework Social -weak_framework UIKit -lxml2 -fobjc-arc -fobjc-link-runtime -stdlib=libc++ -framework AssetsLibrary -framework MobileCoreServices -framework oovoo -framework AVFoundation -framework Accelerate -framework CoreGraphics -framework AudioToolbox -framework CoreMedia -framework CoreTelephony -framework CoreVideo -lc++ -lz -framework OpenGLES -framework QuartzCore -framework MapKit -framework Social -framework Twitter -lavfilter -lswresample -lspeexdsp -lx264 -lavdevice -liconv.2.4.0 -framework Security -lswscale -lavformat /Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/RTMP_iOSLib/CommLibiOS/CommLibiOS.a -lavutil -framework CoreLocation -framework CoreData -lresolv -framework CFNetwork -lxml2 -lspeex -lsqlite3 -framework SystemConfiguration -framework ReplayIO -lavcodec -framework MediaPlayer /Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Kaboodle_iPhone/ThirdParty/RTMP_iOSLib/MediaLibiOS/MediaLibiOS.a -lPods-Kaboodle_iPhone -Xlinker -dependency_info -Xlinker /Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Build/Intermediates/Kaboodle_iPhone.build/Debug-iphoneos/Kaboodle_iPhone.build/Objects-normal/armv7/Kaboodle_iPhone_dependency_info.dat -o /Users/shailee/Documents/Kaboodle_sept/Kaboodle_iPhone/Build/Products/Debug-iphoneos/Kaboodle_iPhone.app/Kaboodle_iPhone
**********************************************************************************************************************
Have tried all given solutions on web, including 
https://github.com/CocoaPods/CocoaPods/issues/2053

**Comment by segiddins** [comment] 2015-09-13 14:29
Can you try using CocoaPods-deintegrate and re-running pod install?

**Comment by NewPersonal** [comment] 2015-09-13 22:52
Tried that but still having the same issue.

**Comment by segiddins** [comment] 2015-09-14 00:32
In that case, we'd probably need an example project we can use to reproduce the issue in order to debug.

**Comment by NewPersonal** [comment] 2015-09-14 02:30
Can you suggest the preferred way to share the sample project?

**Comment by segiddins** [comment] 2015-09-14 02:47
Pushing a new repo to github that we could clone would probably be the easiest thing, thanks!

**Comment by segiddins** [comment] 2015-09-25 17:09
Closing due to lack of example project.

**Closed by segiddins** 2015-09-25 17:09 UTC
Labels: s1:awaiting input
