### ISSUE TITLE
Error: undefined method `end_with?' for nil:NilClass... Anyone?

### ISSUE THREAD

**Issue by murilonkz** [CocoaPods/CocoaPods#4093] opened 2015-08-27 21:35 UTC
### Command

```
/usr/local/rvm/rubies/ruby-2.2.3/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.38.2
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin14]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.10.1 (14B25)
       Xcode : 6.1.1 (6A2008a)
         Git : git version 1.9.3 (Apple Git-50)
Ruby lib dir : /usr/local/rvm/rubies/ruby-2.2.3/lib
Repositories : master -  @ fatal: Not a git repository (or any of the parent directories): .git
               master-1 - https://github.com/CocoaPods/Specs.git @ 41bf2da550f856b8710d3ce99b8abc8339b23420
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.5.3
cocoapods-trunk   : 0.6.2
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
platform :ios, '7.0'

inhibit_all_warnings!

source 'https://github.com/CocoaPods/Specs.git'

link_with 'ChatSecure', 'ChatSecureTests'
pod 'AFNetworking', '~> 2.4'
pod "Appirater", '~> 2.0'
pod 'OpenInChrome', '~> 0.0'
pod 'MWFeedParser', '~> 1.0'
pod "CocoaLumberjack", '~> 1.9'
pod "HockeySDK-Source", '~> 3.7'
pod 'MBProgressHUD', '~> 0.9'
pod "SSKeychain", '~> 1.2'
pod "UIAlertView-Blocks", '~> 1.0'
# pod 'gtm-oauth2', '~> 0.1.0' # Trunk is outdated, using local podspec
pod 'JTTargetActionBlock', '~> 1.0'
# pod 'YapDatabase/SQLCipher', '~> 2.5' # We need to use fork for sqlite3_rekey support
pod 'Mantle', '~> 2.0'
pod 'Navajo', '~> 0.0'
# wating on 8.0 https://github.com/jessesquires/JSQMessagesViewController/pull/840
# using for in meantime
# pod 'JSQMessagesViewController', '~> 8.0'
pod 'BBlock', '~> 1.2'
pod 'JVFloatLabeledTextField', '~> 1.0'
pod 'TTTAttributedLabel', '~> 1.10'
pod 'VTAcknowledgementsViewController', '~> 0.12'
pod 'PureLayout', '~> 2.0'
pod 'BButton', '~> 4.0'
pod 'uservoice-iphone-sdk', '~> 3.2'
pod 'TUSafariActivity', '~> 1.0'
pod 'ARChromeActivity', '~> 1.0'
pod 'CocoaAsyncSocket', '~> 7.4'
pod 'JTSImageViewController', '~> 1.4'
pod 'KVOController', '~> 1.0'

# Local Podspecs
pod 'gtm-http-fetcher', :podspec => 'Podspecs/gtm-http-fetcher.podspec.json'
pod 'gtm-oauth2', :podspec => 'Podspecs/gtm-oauth2.podspec.json'
pod 'SQLCipher/fts', :podspec => 'Podspecs/SQLCipher.podspec.json'

# Wating for update to pod needed for iPad bugs
pod 'CRToast', :git => 'https://github.com/cruffenach/CRToast', :commit => '78569d0e6e6704872af5db1bc37be0ff9d112ac0'

# Forks
pod 'SIAlertView', :git => 'https://github.com/ChatSecure/SIAlertView.git', :branch => 'attributedText'
pod 'JSQMessagesViewController', :git => 'https://github.com/ChatSecure/JSQMessagesViewController', :branch => '7.1.0-send_button'

# Submodules
pod 'ProxyKit/Client', :path => 'Submodules/ProxyKit/ProxyKit.podspec'
pod 'OTRKit', :path => 'Submodules/OTRKit/OTRKit.podspec'
pod 'CPAProxy', :path => 'Submodules/CPAProxy/CPAProxy.podspec'
pod 'YapDatabase/SQLCipher', :path => 'Submodules/YapDatabase/YapDatabase.podspec'
pod 'IOCipher/GCDWebServer', :path => 'Submodules/IOCipher/IOCipher.podspec'
```

### Error

```
NoMethodError - undefined method `end_with?' for nil:NilClass
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb:4:in `validates?'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb:25:in `block in <module:CocoaPodsStats>'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:115:in `call'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:115:in `block (3 levels) in run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:109:in `each'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/hooks_manager.rb:108:in `run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:453:in `run_plugins_post_install_hooks'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:444:in `perform_post_install_actions'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:112:in `install!'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/usr/local/rvm/gems/ruby-2.2.3@global/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/local/rvm/rubies/ruby-2.2.3/bin/pod:23:in `load'
/usr/local/rvm/rubies/ruby-2.2.3/bin/pod:23:in `<main>'
/usr/local/rvm/gems/ruby-2.2.3@global/bin/ruby_executable_hooks:15:in `eval'
/usr/local/rvm/gems/ruby-2.2.3@global/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment] 2015-08-28 06:40
Should be fixed by https://github.com/CocoaPods/cocoapods-stats/pull/24.

**Comment by segiddins** [comment] 2015-08-29 23:07
Closing as a duplicate of https://github.com/CocoaPods/CocoaPods/issues/3975

**Closed by segiddins** 2015-08-29 23:07 UTC
Labels: s4:awaiting validation
