### ISSUE TITLE
getting error when i update  pod in my project

### ISSUE THREAD

**Issue by rasmiranjan20** [CocoaPods/CocoaPods#3933] opened 2015-07-30 07:34 UTC
No such file or directory @ rb_file_s_stat

**Comment by neonichu** [comment] 2015-07-30 09:35
Please have a look at [our guidelines](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md#bug-reports) on how to write a good bug report and update this issue.

**Comment by alistra** [comment] 2015-07-30 10:25
I'll try to explain, because I'm getting the same error.

When I switch branches and my `Pods/` directory is in `.gitignore` and it leaves metadata about files from another branch that doesn't exist on the current branch yet, then `pod update` crashes. 

When I remove `Pods` directory and do a clean `pod update` it works.

Backtrace:

https://gist.github.com/anonymous/c278018f12cf0b8cc07f

**Comment by alistra** [comment] 2015-07-30 10:46
I guess I mean a duplicate of this #3914

**Comment by neonichu** [comment] 2015-07-30 11:18
I see, closing this as a dupe, thanks @alistra

**Closed by neonichu** 2015-07-30 11:18 UTC
Labels: s1:awaiting input
