### ISSUE TITLE
undefined method `version' for nil:NilClass

### ISSUE THREAD

**Issue by gabrielribeirro** [CocoaPods/CocoaPods#3650] opened 2015-06-04 17:58 UTC
### Command

```
/usr/bin/pod list
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.3.2 (6D2105)
         Git : git version 2.3.2 (Apple Git-55)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ e232decbc3583bde926d316b0889057fca19c5db
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.1'
pod 'GoogleMaps'
```

### Error

```
NoMethodError - undefined method `version' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:203:in `pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/list.rb:24:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/list.rb:24:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/list.rb:24:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by segiddins** [comment] 2015-06-04 18:02
Hm, that's interesting. I can't reproduce this at all.

**Comment by sigmundfridge** [comment] 2015-06-10 15:17
I am getting something similar using 0.32.1. First I am told that master repos needs 0.35.0, and then I get the same lines as above.
Upgrading to 0.35 (or 37) seems to fix this problem, although it then generates a whole host of errors with the Pods I have installed.

**Comment by segiddins** [comment] 2015-07-05 20:07
Closing due to lack of a reproduction case.

**Closed by segiddins** 2015-07-05 20:07 UTC

**Comment by Snwspeckle** [comment] 2015-12-15 18:06
I'm seeing this with CocoaPods version 39.0, anyone else?

**Comment by segiddins** [comment] 2015-12-15 19:42
@Snwspeckle please open a new issue with steps the team can follow to reproduce the issue. Thanks!

**Comment by wudijimao** [comment] 2015-12-31 16:31
The same error occurred on my workmate, I'll try to do some thing.
