### ISSUE TITLE
resource_bundles not working with assets catalog (cocoapods 1.0.1)

### ISSUE THREAD

**Issue by connectdotz** [CocoaPods/CocoaPods#5477] opened 2016-06-07 22:55 UTC
- [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).
# Report

After upgrade to 1.0.x the <code>UIImage(named:inBundle:compatibleWithTraitCollection)</code> no longer worked with images in assets catalog.
## What did you do?
- upgrade to cocoapod 1.0.1
- run test project
- failed to load the image file from assets catalog that used to work

Note, we have no problem loading a plain image file (outside of the .xcassets) from the bundle, just not able to access the same file when it's in .xcassets. And I do see the Assets.car file in the bundle directory, along with the plaint image file.
## What did you expected to happen?

the image should be able to load from assets catalog. 
## What happened instead?

<code>UIImage(named:inBundle:compatibleWithTraitCollection)</code> returns nil. The code should be correct as it can load plain image file from the same bundle.
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.2.2
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.1.1
Ruby lib dir : /usr/local/Cellar/ruby/2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4de31805e74f3ed92f1777b261fa474f1b18806b
```
### Installation Source

```
Executable Path: /usr/local/bin/pod
```
### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-playgrounds : 1.2.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```
### Podfile

``` ruby
use_frameworks!

target 'ResourceTest_Example' do
  pod 'ResourceTest', :path => '../'

  target 'ResourceTest_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 0.8'
  pod 'Nimble', '~> 3.0'
  pod 'FBSnapshotTestCase'
  pod 'Nimble-Snapshots'
  end
end
```
## Project that demonstrates the issue

[ResourceTest](https://github.com/connectdotz/ResourceTest):
the code that loads the image is in AFunc.swift

**Comment by connectdotz** [comment] 2016-06-08 11:11
Reading through lots of resource_bundles/assets-catalog related issues on the net, it wasn't very clearly to us what the official stand of assets catalog support in Cocoapod. Judging that it was working prior to 1.0, we assumed it should continue to work in 1.0.x. If this is not the right assumption, please advice...

**Comment by segiddins** [comment] 2016-06-08 17:22
@efirestone any interest in looking at this?

**Comment by efirestone** [comment] 2016-06-08 18:12
Would be happy to help, but I'm out on vacation without a laptop until June 17th. In the meantime, without being able to investigate:
- asset catalogs should be supported, in fact they should be better supported as of 1.0
- try using something like resources/**/* for your resource_bundles value, rather than something like resources/*/*.png

The biggest change with 1.0 is they CocoaPods should properly understand asset catalogs now, so you want to include the catalog, the JSON files, and everything else, rather than just be image files themselves.

The other issue is that I seem to remember imageNamed:inBundle:compatibleWithTraitCollections: being particular about looking up asset catalog images. You might try creating a catalog by hand and comparing the two (assuming that one works).

If it's still an issue when I get back, happy to help out.

**Comment by connectdotz** [comment] 2016-06-08 18:38
@efirestone, 

thanks for the suggestion, the resource_bundles is defined as:
`s.resource_bundles = {
     'ResourceTest' => ['ResourceTest/Assets/**/*']
   }
`
as I mentioned earlier, the Assets.car file is indeed in the bundle's directory, as far as we can tell. 

>... I seem to remember imageNamed:inBundle:compatibleWithTraitCollections: being particular about looking up asset catalog images.

Can you elaborate on this point... We didn't change the catalog between Cocoapods releases, so not sure by manually recreating the catalog would make any difference...

**Comment by efirestone** [comment] 2016-06-09 01:55
I don't remember the particulars unfortunately, and could be thinking of something else entirely. Your resource bundle definition looks right, so not sure what's up. You're definitely passing the correct bundle to imageNamed:?

**Comment by ANNotunzdY** [comment] 2016-06-09 07:51
I tried use of 'bundle_resources'.
However, the resource bundle was not copied to [APPNAME].app/Frameworks/[FRAMEWORK_NAME].frameworks.

ex)

https://github.com/ANNotunzdY/SVProgressHUD/blob/pod101/SVProgressHUD.podspec
```
 s.resource_bundles    = {
    'SVProgressHUD' => ['SVProgressHUD/SVProgressHUD.bundle/*']
  }
```

![screen shot 2016-06-09 at 16 48 57](https://cloud.githubusercontent.com/assets/525548/15922388/4ca78f2c-2e62-11e6-8cf2-798d5695d87d.png)

**Comment by efirestone** [comment] 2016-06-09 09:09
@ANNotunzdY your issue is likely different. You're specifying both a `resources` and `resource_bundles` attribute. You should only be specifying one (`resource_bundles`). Your file system layout is a bit odd too. It should work, but you don't need to call the folder `SVProgressHUD.bundle`, CocoaPods will do that for you. Usually you would name it something like `SVProgressHUD/Resources`, then use something like

```
 s.resource_bundles    = {
    'SVProgressHUD' => ['SVProgressHUD/Resources/**/*']
  }
```

**Comment by connectdotz** [comment] 2016-06-09 12:39
@efirestone, I think the bundle should be right, since I can use the same bundle to retrieve the image file from bundle as long as it is not in assets catalog:

`let bundle = NSBundle(URL: NSBundle(forClass: Dummy.self).URLForResource("ResourceTest", withExtension: "bundle")!)!`

this failed: image.png is in assets catalog:
` let image1 = UIImage(named:"image", inBundle: bundle, compatibleWithTraitCollection: nil)`
   
this succeeded: image2.png is outside of assets catalog (but still in the resource_bundles of course):
    `let image2 = UIImage(named:"image2", inBundle: bundle, compatibleWithTraitCollection: nil)`

I have posted the sample project, you can download and test with it: [https://github.com/connectdotz/ResourceTest](https://github.com/connectdotz/ResourceTest)

**Comment by efirestone** [comment] 2016-06-09 16:57
Aha! [Looks like this is a UIKit/asset catalog limitation](http://stackoverflow.com/questions/18900967/asset-catalogs-in-resource-bundles). There does seem to be a way to make it work though: use `-[NSBundle imageForResource:]`. See [this post](https://forums.developer.apple.com/message/98208#98208) for more.

If this works for you then we can close this issue as it's not a CocoaPods limitation.

**Comment by connectdotz** [comment] 2016-06-09 19:11
@efirestone, imageForResource: is not available on iOS, only on mac. I believe the `UIImage(named:inBundle:compatibleWithTraitCollection:)` is the iOS equivalent. 

This API used to work with cocoapods 0.39.x, there must be something introduced in 1.0.x that somehow broke it... did 0.39 actually copy the resources from assets catalog instead of deploying the compiled version?

**Comment by vavvolo** [comment] 2016-08-10 16:06
I ran in the same issue and I found that the product bundle identifier for the resource bundle target is not set if the spec (or subspec) that defines the resource_bundle doesn't have executable code. As a result of this the final binary Info.plist for the bundle doesn't have the CFBundleIdentifier key. This seems to affect ``UIImage(named:inBundle:compatibleWithTraitCollection:)`` but not ``UIViewController(nibName:bundle:)``.

This quick fix worked for me

```
post_install do |installer|
  installer.pods_project.targets.select { |target| target.name == 'MyResourceOnlyPod-BundleName' }.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['PRODUCT_BUNDLE_IDENTIFIER'] = 'org.cocoapods.BundleName'
    end
  end
end
```

**Comment by foscomputerservices** [comment] 2016-09-01 19:44
I can confirm that this is indeed an issue.  Yesterday I moved from 0.39 to 1.0.1 and immediately my app was crashing due to failing to load images from a dependent pod.  I restored to CocoaPods 0.39, regenerated everything (clean pod install) rebuilt and everything was again working as expected.

My pod contains code, so @vavvolo's solution didn't seem to help.  I looked at the generated plist in the install and it had the bundle identifier as expected without adding the code he suggested.

So back to 0.39 for me, I guess.

**Comment by Ruenzuo** [comment] 2016-09-16 15:05
Early this week we ran into this issue as well, so I can confirm it still happens with the latest version of CocoaPods. The funny thing is that a plugin we created for a completely different purpose "works-around" this issue as well, so you could try it out https://github.com/Ruenzuo/cocoapods-amimono if you're okay with what the plugin is doing.

**Comment by pavankataria** [comment] 2017-03-10 10:51
Any developments on this?

**Comment by benjamin-bader** [comment] 2017-06-23 01:12
This still seems to be an issue - I have a frame work with a `resource_bundles` entry that includes an `xcassets` file.  I can confirm that the assets are compiled into an `Assets.car` that is included in the named bundle, but `[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]` cannot load the image.

The issue seemed to be that the resources weren't included in the right target by default.  Manually assigning targets worked for my sample project, but that's not really a good story to tell our customers.

Replacing `resource_bundles` with `resources` in our podspec fixed our issue.

**Comment by sethsamuel** [comment] 2017-08-07 15:59
Running into a nasty variation on this, where using `resources` works on device but crashes simulator, but using `resource_bundles` works on simulator but fails to find image (without crashing) on device.

Podspec snippet:
```
   s.resources = ['OvertimeFlashbackCamera/Assets/**/*']
#s.resource_bundles = {
#     'Resources' => ['OvertimeFlashbackCamera/Assets/**/*']
#  }
```

Image loading:
```
let bundle = Bundle(for: type(of: self))
button.setImage(UIImage(named: "Close", in: bundle, compatibleWith: nil), for: .normal)
```

**Closed** 2017-11-12 17:52 UTC
Labels: s1:awaiting input

**Comment by MarloKessler** [comment] 2020-08-04 08:27
Has there been any updates on this, because i still face the same issue? 🤔😉
