### ISSUE TITLE
My Repository's URL Cannot Be Validated

### ISSUE THREAD

**Issue by verticon** [CocoaPods/CocoaPods#7455] opened 2018-02-24 16:27 UTC
* [* ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran 'pod lib lint --verbose'

## What did you expect to happen?

I expected my pod to validate

## What happened instead?

I got a failure message regarding my pod's repository URL

** BUILD SUCCEEDED **

   Testing with xcodebuild. 
 -> VerticonsToolbox (0.0.6)
    - WARN  | url: There was a problem validating the URL https://github.com/verticon/VerticonsToolbox.git.

[!] VerticonsToolbox did not pass validation, due to 1 warning (but you can use `--allow-warnings` to ignore it) and all results apply only to public specs, but you can use `--private` to ignore them if linting the specification for a private pod.
You can use the `--no-clean` option to inspect any issue.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G1212)
       Xcode : 9.2 (9C40b)
         Git : git version 2.6.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 22f6b6bc59a02c75877c4fd96025d9ceb0fe5e1f
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/verticon/VerticonsToolbox.git

## My Remarks

I am taking the failure message at face value: pod attempted to access my repository using the url provided by my pod spec and was unable to do so. I copied the URL from the terminal window, pasted it into a safari address bar, and successful brought up the GitHub page. I do not know how to further explore this so as to determine exactly what has gone wrong.

Issue [2795](https://github.com/CocoaPods/CocoaPods/issues/2795) did not help me.

FWIW: My pod is currently at version 0.0.6. In the past I have successfully validated and uploaded versions 0.0.1 -> 0.0.5. See [VerticonsToolbox](https://cocoapods.org/pods/VerticonsToolbox)

Please help. Thank you.

**Comment by dnkoutso** [comment] 2018-02-24 16:52
hm are you sure this issue is not masked as https://github.com/CocoaPods/CocoaPods/issues/7447?

**Comment by dnkoutso** [comment] 2018-02-24 16:53
To me this worked:
```
x** BUILD SUCCEEDED **

   Testing with `xcodebuild`. 
 -> VerticonsToolbox (0.0.6)

Pods workspace available at `/var/folders/0x/798grj997td8xhm6_jr85l680000gn/T/CocoaPods-Lint-20180224-66476-18nra2a-VerticonsToolbox/App.xcworkspace` for inspection.

VerticonsToolbox passed validation.
```

I honestly think you are getting #7447

**Comment by verticon** [comment] 2018-02-24 18:50
@dnkoutso Thank you. Yes, [#7447](https://github.com/CocoaPods/CocoaPods/issues/7447) does indeed seem to be my issue. And so, as was recommended, I decided to install the latest version of Ruby. However, after doing so I am not able to correctly execute the new version of ruby. Even though this is not a cocoa pods matter, would you please take a moment to see if you might be able to advise me? Below is the, to me, inexplicably inconsistent command line output. I added the # comments

$ /usr/bin/ruby --version # The old ruby
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
$ /usr/local/bin/ruby --version # The new ruby
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
$ which ruby
/usr/local/bin/ruby # The new ruby
$ ruby --version
ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16] # WTF?!
$ echo $PATH
/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin:/opt/X11/bin:/usr/local/gcc-arm-none-eabi-6_2-2016q4/bin
$ alias
$

**Comment by dnkoutso** [comment] 2018-02-24 18:52
I am unsure :| sorry best bet is to use https://github.com/postmodern/chruby or RVM? 

Going to close this as its now confirmed its not a CocoaPods issue.

**Comment by verticon** [comment] 2018-02-24 18:53
Okay. Happy coding!

**Closed by dnkoutso** 2018-02-24 18:52 UTC

**Comment by verticon** [comment] 2018-02-24 19:03
@dnkoutso 
I fixed my ruby issue by opening up a new terminal window
$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]
$ 

But, I still have the validation problem

**Comment by dnkoutso** [comment] 2018-02-24 19:19
I thought you said the issue was fixed? Seems like a configuration issue again?

**Comment by dnkoutso** [comment] 2018-02-24 19:19
The podspec still works for me in validation, I ran the same command as you and it works for me. Something is off with your configuration here triggered unfortunately by #7447

**Comment by dnkoutso** [comment] 2018-02-24 19:20
You have provided your project, I tried to reproduce and I couldn't. You also mentioned it worked on a comment above. I cannot see where is the CocoaPods library issue here.

**Comment by verticon** [comment] 2018-02-24 20:01
Sorry about opening the new issue. I didn't know whether or not a comment would suffice.

I did not say that it worked. I said that #7447 seemed like my issue and that I was taking the recommended steps. Once I got ruby 2.5 in place and gave it a try it did not work. However, it is encouraging that it works for you. What version of OS X are you on?

**Comment by dnkoutso** [comment] 2018-02-24 20:41
High Sierra 10.13.2
Xcode 9.2  9C40b
ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin16]

**Comment by verticon** [comment] 2018-02-24 22:02
Thanks for sticking with me, Dimitris. I upgraded from Sierra to High Sierra. Here is where I am at the moment:

~$ sw_vers -productVersion 
10.13.3

~$ xcodebuild -version
Xcode 9.2
Build version 9C40b

~$ ruby --version
ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin16]

~$ pod lib lint
-bash: /usr/local/bin/pod: /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/bin/ruby: bad interpreter: No such file or directory

$ ls /System/Library/Frameworks/Ruby.framework/Versions
2.3	Current

**Comment by verticon** [comment] 2018-02-24 22:13
Dimitris, Success at last! I reinstalled cocoa pods 1.4. Now I have:

$ pod lib lint

 -> VerticonsToolbox (0.0.6)

VerticonsToolbox passed validation.
$

**Comment by dnkoutso** [comment] 2018-02-24 22:14
whoohoo! I think it was just using CocoaPods under a different (the older one) ruby version!

Good stuff!

**Comment by verticon** [comment] 2018-02-24 22:16
My guess is that the cocoa pods install procedure generates script which capture the current version of ruby - the current **system** version of ruby. That is why my upgrade of ruby didn't work - it wasn't being used. Upgrading to High Sierra upgraded the system version from 2.0 to 2.3.
