### ISSUE TITLE
after install 1.5.0 version i am unable to archive .ipa file it is generating .xcarchive.

### ISSUE THREAD

**Issue by RamNalluri** [CocoaPods/CocoaPods#7632] opened 2018-04-13 09:11 UTC
after update pod version form 1.2.x to 1.5.0 we are  unable to archive .ipa file it is generating .xcarchive.

**Comment by numen31337** [comment] 2018-04-13 12:28
I guess this is the duplicate of https://github.com/CocoaPods/CocoaPods/issues/7590

**Closed** 2018-04-13 15:11 UTC

**Comment by RamNalluri** [comment] 2018-04-14 07:43
I am using only objective-c not swift or mixed. Every thing  working fine in 1.3.1 after I update pod version 1.5.0 we are unable to create IPA  file it's  directly generated .xcarchive file , without change any code .

I think both are different issues. Not for #7590

**Comment by nikhilchaurasia** [comment] 2018-05-09 11:42
@RamNalluri  I am also start getting similar issue after updating pod. I have objective-c project with no Swift dependency. If you have resolve the issue Pleas update the solution. It will be helpful. Thanks.
