### ISSUE TITLE
Cleaning (CMD+K) is required to see changes when developing library

### ISSUE THREAD

**Issue by richardtop** [CocoaPods/CocoaPods#8752] opened 2019-05-01 15:53 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Edited a file in the library I develop.
For example, I've changed  `view.backgroundColor = .white` to `view.backgroundColor = .red`.

Run the test app

## What did you expect to happen?
App's view to turn red

## What happened instead?
App's view is still white

**After cleaning (CMD+K), everything works as expected**

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.6.0p0 (2018-12-25 revision 66547) [x86_64-darwin18]
    RubyGems : 3.0.1
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /Users/richard/.rvm/rubies/ruby-2.6.0/lib
Repositories : gitlab-privatespecs - git@gitlab.local:mobile/privatespecs.git @ cd59b2559bd958318a40f04229d5018b2d78fa97
               master - https://github.com/CocoaPods/Specs.git @ 9c05a7a088cd2c001d4f2c23b7763fa9d6722d52
```

### Installation Source

```
Executable Path: /Users/richard/.rvm/gems/ruby-2.6.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.3
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue
[CalendarKitDemo](https://github.com/richardtop/CalendarKit/tree/master/CalendarKitDemo)

**Comment by dnkoutso** [comment] 2019-05-01 15:54
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/8073

**Closed by dnkoutso** 2019-05-01 15:54 UTC

**Comment by richardtop** [comment] 2019-05-01 16:02
@dnkoutso the solution in the issue doesn't work.

**Comment by dnkoutso** [comment] 2019-05-01 16:06
What solution did you try? Did you remove input/output paths or used legacy build system?

**Comment by dnkoutso** [comment] 2019-05-01 16:06
you should also clean the derived data.

**Comment by richardtop** [comment] 2019-05-01 16:06
@dnkoutso using the legacy build system helped after restarting Xcode
