### ISSUE TITLE
Caching codesigned frameworks during "Embed Pod Frameworks"

### ISSUE THREAD

**Issue by chrisballinger** [CocoaPods/CocoaPods#6433] opened 2017-01-25 21:44 UTC
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

The "Embed Pod Frameworks" step takes a very long time on my machine ever since Apple introduced the codesign regression in 10.12.1: https://twitter.com/conradev/status/791427116051013633

I haven't looked too closely yet, but would it be possible for me to modify the script template to cache the results of this step when the framework is unchanged between builds?

Thanks!

**Comment by benasher44** [comment] 2017-01-25 22:18
Hi @chrisballinger! Thanks for the report! I'm going to close this because it's a dup of #6118. In short, we're certainly open to ideas by means of a PR or other proposals on #6118, but so far no one has come up with an effecting means of caching. Furthermore, many people seem to have been able to resolve this by making adjustments to their keychains (see the thread).

**Closed by benasher44** 2017-01-25 22:18 UTC

**Comment by chrisballinger** [comment] 2017-01-25 23:29
@benasher44 Thanks for the response! Unfortunately #6118 is closed :(

My intention for this issue was to spur discussion and get feedback on whether or not it would be possible for me to add caching from people who are more familiar with the toolchain. I find the script to be somewhat slow even when building for the simulator, so perhaps there are other low hanging speed gains to be found.

I've already tried all of the fixes (that don't require disabling SIP and patching the codesign executable), and have cleaned out any duplicate or unnecessary keychain entries. There's nothing CocoaPods can do about this last part, but when I do archive build submissions it can often take up to an hour to build and codesign all of the frameworks, and slows my computer to a crawl because it appears the codesign process uses a very high priority. It's definitely Apple's problem... that I don't expect to ever be fixed.

**Comment by benasher44** [comment] 2017-01-26 00:12
These issues have been closed because we haven't been able to get any projects that reproduce the issue; them being closed doesn't mean you can't comment and discuss it with folks experiencing it as well.

To add some background: I was working on a project that required code signing 50+ frameworks during the build (at the time the issue was filed), and I didn't experience the long wait issues (along with a team of ~20 all working on the same project on updated macOS). Similarly, some folks in that thread have resolved their issues by making changes to their environment. Given all of that, the evidence points to this being an issue with people's environments. This doesn't mean it couldn't be some other real issue that's fixable within CocoaPods. We just don't have any reproducible cases for that yet.

That said, we're always open to PRs that reduce build times via caching or other mechanisms :)

**Comment by chrisballinger** [comment] 2017-01-26 00:51
@benasher44 Thanks! I'll poke around and see what I can find.
