### ISSUE TITLE
[1.6.0.beta.1] weak_frameworks lost

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7872] opened 2018-06-24 03:08 UTC
In CP v1.3.1, the `weak_frameworks` from podspec works, but in CP master branch, all `weak_frameworks` lost. I will check the code later.
The Podspec;
```
  s.frameworks = 'OpenAL','VideoToolbox','CoreMedia', 'AudioToolbox','MediaPlayer','CoreMotion','AVFoundation','SystemConfiguration'
  s.weak_frameworks = 'MetalKit'
```

**Comment by dnkoutso** [comment] 2018-06-24 04:14
very possible due to build_settings re-write.

**Comment by Whirlwind** [comment] 2018-06-24 06:27
the function `weak_frameworks_to_import` in class `PodTargetSettings` in the `build_settings.rb`:

```
        # @return [Array<String>]
        define_build_settings_method :weak_frameworks_to_import, :memoized => true, :sorted => true, :uniqued => true do
-          []
+          spec_consumers.flat_map(&:weak_frameworks)
        end
```

**Comment by Whirlwind** [comment] 2018-06-24 06:30
The code is very nice and I afraid that I do a error modify, so I could not make a PR.

**Comment by dnkoutso** [comment] 2018-06-24 06:52
we need to find out if there was a test in 1.5.3 that covers this case.

**Comment by Whirlwind** [comment] 2018-06-24 08:59
It seams that there is not any test for the `weak_frameworks` in the `AggregateTarget`, only for `PodTarget`. So the user target will not link weak framework.

**Comment by Whirlwind** [comment] 2018-06-25 02:28
Could somebody help me about this issue? I could not fix it by myself.

**Comment by dnkoutso** [comment] 2018-08-17 03:38
@Whirlwind  1.6.0.beta.1 is out is this still an issue? Can you upload a sample app?

**Comment by Whirlwind** [comment] 2018-08-17 04:06
I test my app, this still an issue.

**Comment by Whirlwind** [comment] 2018-08-17 04:07
```
-framework "ARKit" -framework "AVFoundation" -framework "Accelerate" -framework "AddressBook" -framework "AlibabaAuthSDK" -framework "AlipaySDK" -framework "AssetsLibrary" -framework "AudioToolbox" -framework "CFNetwork" -framework "CoreData" -framework "CoreFoundation" -framework "CoreGraphics" -framework "CoreLocation" -framework "CoreMedia" -framework "CoreMotion" -framework "CoreTelephony" -framework "CoreText" -framework "CrashReporter" -framework "Crashlytics" -framework "EAccountSDK" -framework "Fabric" -framework "Foundation" -framework "GLKit" -framework "ImageIO" -framework "JavaScriptCore" -framework "MapKit" -framework "MediaPlayer" -framework "MobileCoreServices" -framework "OpenAL" -framework "QuartzCore" -framework "SecGuard-Base" -framework "Security" -framework "StoreKit" -framework "SystemConfiguration" -framework "TBAppLinkSDK" -framework "TUnionSDKStatic" -framework "TUnionTradeSDK" -framework "TencentOpenAPI" -framework "UIKit" -framework "UMMobClick" -framework "UTDID" -framework "VideoToolbox" -framework "WebP" -framework "imageIO"
```
It lost the `-weak_framework MetalKit`.

**Comment by Whirlwind** [comment] 2018-08-17 04:11
I have a simple fork to fix this issue: https://github.com/Whirlwind/CocoaPods/commit/1880f14245ddf18d528b138b0fc01e7d27d4521a

I didn't make a PR for this issue.

**Comment by dnkoutso** [comment] 2018-08-17 05:18
Will check it for 1.6.0.beta.2

**Comment by dnkoutso** [comment] 2018-08-17 18:38
@Whirlwind weird there is a spec for this:
https://github.com/CocoaPods/CocoaPods/blob/master/spec/unit/target/build_settings/pod_target_settings_spec.rb#L89-L91

**Comment by dnkoutso** [comment] 2018-08-17 18:39
And also I see it in my sample app:
```
OTHER_LDFLAGS = $(inherited) -weak_framework "iAd"
```

**Comment by dnkoutso** [comment] 2018-08-17 19:48
So I guess you mean that aggregate target does not have these

**Comment by dnkoutso** [comment] 2018-08-17 19:54
I do not see an aggregate target receiving `weak_frameworks` in 1.3.1.

**Comment by dnkoutso** [comment] 2018-08-17 19:57
Without a sample app I cannot spend any more time on this.

**Comment by dnkoutso** [comment] 2018-08-17 21:03
Alright figured it out this has to do with static libraries only, @Whirlwind are you integrating with static libraries?

**Comment by Whirlwind** [comment] 2018-08-19 02:47
>  @Whirlwind are you integrating with static libraries?

No, my project is a app, not static library.

> So I guess you mean that aggregate target does not have these

Yes, the app's xcconfig lost the `-weak_framework`, not the pod target. By the way, the pod target should not link any system frameworks or other third part libraries, right?

**Comment by dnkoutso** [comment] 2018-08-19 03:41
I meant if you are using `use_frameworks!` or not.

Either way this is fixed in #8026

**Comment by Whirlwind** [comment] 2018-08-19 03:42
I do not use the `use_frameworks!`.

**Comment by dnkoutso** [comment] 2018-08-19 04:00
Good. Thats what i found out too

**Closed** 2018-08-19 18:44 UTC
Labels: s6:need sample

**Comment by leolobato** [comment] 2019-02-11 11:13
Not sure if I should open a separate issue, but `weak_framework` is not working when using `use_framework!` on 1.6.0. It does work on 1.5.3.

Attached is a simple sample project using `Flurry-iOS-SDK/FlurryAds` (which I use on a project and has a couple of frameworks weak linked).

It seems the issue is on `OTHER_LDFLAGS` on the generated `Flurry-iOS-SDK.xcconfig` file:

On 1.5.3 it looks like:

    OTHER_LDFLAGS = -l"FlurryAds_1.1.0" -l"FlurryMessaging_9.3.0" -l"Flurry_9.3.0" -l"z" -framework "AVFoundation" -framework "CoreGraphics" -framework "CoreMedia" -framework "CoreTelephony" -framework "Foundation" -framework "MediaPlayer" -framework "Security" -framework "SystemConfiguration" -framework "UIKit" -framework "WebKit" -weak_framework "AdSupport" -weak_framework "SafariServices" -weak_framework "StoreKit"

and on 1.6.0 it's missing all `-weak_framework`:

    OTHER_LDFLAGS = $(inherited) -l"FlurryAds_1.1.0" -l"FlurryMessaging_9.3.0" -l"Flurry_9.3.0" -l"z"

Let me know if I can help somehow.

[WeakTest-sample-project.zip](https://github.com/CocoaPods/CocoaPods/files/2850777/WeakTest-sample-project.zip)

**Comment by mathaeus** [comment] 2019-02-11 14:45
@leolobato we are having the very same issue, so I would appreciate if you would open a new issue with the information you provided and the sample project :)

**Comment by leolobato** [comment] 2019-02-11 15:06
Done. Opened here: [#8505](https://github.com/CocoaPods/CocoaPods/issues/8505).
