### ISSUE TITLE
Linting using frameworks doesn't catch incorrect import statements from public headers

### ISSUE THREAD

**Issue by Buju77** [CocoaPods/CocoaPods#3672] opened 2015-06-11 09:30 UTC
Setup: 2 projects
1. library pod: MyLibrary
2. app project:  MyApp

MyLibrary:
* static library target
* pod 'CocoaLumberjack'
* it has a public header `MyAwesomeClass.h` which incorrectly uses `#import <CocoaLumberjack.h>`
* building in xcode works fine
* `pod lib lint MyLibrary.podspec` (lints as dynamic framework) works fine

MyApp:
* Podfile:
  * use_frameworks!
  * pod 'MyLibrary'
* Now building just after pod install builds fine.
* But now in `TestViewController.m` it adds the following line: `#import <MyLibrary/MyAwesomeClass.h>`
--> Build Error: MyLibrary module couldn't be build. CocoaLumberjack.h not found.

*Solution:*
use the more correct way: `#import <CocoaLumberjack/CocoaLumberjack.h>`

*Question:*
So the build error only occurs when you explicitly import it, otherwise it builds fine. It would be nice if the linter will automatically detect these kind of incorrect import statements.

**Comment by neonichu** [comment] 2015-06-17 12:17
I'd say this is way outside of scope of the linter at this point in time, it does not look at your source files at all.

**Comment by Buju77** [comment] 2015-06-17 23:01
This is what we have done for "easily" finding out those incorrect import statements:

1. create a new single view app Xcode project
2. `pod install` with `use_frameworks!` (CP automatically creates the umbrella header with all public headers)
3. import all the `Pods-umbrella.h` in the default `ViewController.m` (I think putting it in `ViewController.h` would also work)
4. build the project
The compiler will then automatically fail if there are any incorrect imports. (Error: "header file not found")

So the main thing is that you just have to import the umbrella header somewhere once and build it.

As CP already knows of every public header of the pod and it has the ability to create an umbrella header of it, it should be pretty easy to create another `temp.m` which simply just imports this header and let the compiler run and see if it fails. Right?

**Comment by neonichu** [comment] 2015-06-18 05:42
OK, the way you outline the issue now, I have realised that this is actually a duplicate of #2134

**Closed by neonichu** 2015-06-18 05:42 UTC
Labels: t3:discussion
