### ISSUE TITLE
Pod Install and Update commands fail to inform the user when Podfile.lock is stale

### ISSUE THREAD

**Issue by deemadden** [CocoaPods/CocoaPods#5251] opened 2016-05-04 17:41 UTC
# Report
When running `pod install` or `pod update` in situations where the Podfile.lock has gotten stale and is looking for versions of pods or pod dependencies it should no longer be looking for, it will continually return some form of the message:

`[pod] ([pod version]) required by Podfile`
`[pod] ([pod another version of the pod above]) required by Podfile.lock`

When your pods get into this state, the one solution that seems to work is to delete the Podfile.lock file, resolve whatever Podfile, version conflict/dependencies that are going on and re-running

`pod install`

The messaging in the console doesn't provide the user with the information needed to resolve in this manner.  

It would be better to either change the message to let the user know that the problem may be resolved by performing the steps above explicitly, or having the pod command delete it and informing them what to do next, and prompting the user before doing so.

## What did you do?
1. Add two pods to a Podfile, one directly, one with a dependency on the older version of the other.
2. Run `pod install` or `pod update`

Deleting the Podfile.lock file, resolving the conflict, and rerunning `pod install` seems to fix the problem.

## What did you expected to happen?
Receive a message in the console indicating that the Podfile.lock file is stale, or prompt the user, informing them it will be removed and to resolve the conflict, then on y/n and to re-run `pod install`

## What happened instead?
Received a message that the older requirement was `required by Podfile.lock`

## Podfile

Unable to provide, as these are pods in a private repo.

**Comment by segiddins** [comment] 2016-05-04 18:42
Please provide a sample project we can sue to reproduce the issue, since I'm having trouble understanding exactly what's wrong. Thanks!

**Comment by neonichu** [comment] 2016-05-15 13:58
Closing, because we never got a reproducible project.

**Closed by neonichu** 2016-05-15 13:58 UTC
Labels: s1:awaiting input
