### ISSUE TITLE
Pod not showing up in search

### ISSUE THREAD

**Issue by Ahmadalsofi** [CocoaPods/CocoaPods#9462] opened 2020-01-07 10:30 UTC
I've created a two CocoaPods, but i can't find them while i'm searching on CocoaPods page. 

i find them here : https://cdn.cocoapods.org/all_pods.txt 

My pods: SOPullUpView and SOTabBar 

github link : https://github.com/Ahmadalsofi/SOTabBar
https://github.com/Ahmadalsofi/SOPullUpView

Thank you for helping.

**Comment by dnkoutso** [comment] 2020-01-07 17:41
This is a known issue with our search indexer for a while that is broken. New pods are not showing up in search.

Duplicate of #9366

**Closed by dnkoutso** 2020-01-07 17:41 UTC
