### ISSUE TITLE
Using `--no-integrate` causes CocoaPods to fail with "nil" error.

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#5033] opened 2016-03-15 14:43 UTC
When passing "--no-integrate" to CocoaPods 0.39 on OS X 10.11 it currently crashes with the following error:

```
Updating local specs repositories

CocoaPods 1.0.0.beta.6 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Downloading dependencies
Using ARAnalytics (3.9.1)
Using Appirater (2.0.5)
Using Appsee (2.2)
Using Bolts (1.6.0)
Using Branch (0.11.17)
Using Crashlytics (3.3.4)
Using DateTools (1.7.0)
Using Dwifft (0.3.1)
Using FBSDKCoreKit (4.10.0)
Using FBSDKLoginKit (4.10.0)
Using FBSDKShareKit (4.10.0)
Using Fabric (1.6.7)
Using Firebase (2.5.1)
Using GeoFire (1.1.2)
Using Google (1.0.7)
Using GoogleAnalytics (3.14.0)
Using GoogleNetworkingUtilities (1.0.0)
Using GoogleSymbolUtilities (1.0.3)
Using GoogleTagManager (3.15.0)
Using GoogleUtilities (1.1.0)
Using Heap (2.2.2)
Using Instabug (5.1.2)
Using JLRoutes (1.5.5)
Using JSQMessagesViewController (7.2.0)
Using JSQSystemSoundPlayer (2.0.1)
Using JTSImageViewController (1.5.1)
Using KVNProgress (2.2.4)
Using Mixpanel (2.9.4)
Using NSOperationStack (1.0.2)
Using Nimble (3.1.0)
Using ObjectMapper (1.1.5)
Using Parse (1.12.0)
Using Polly (0.4.3)
Using Quick (0.9.1)
Using RxBlocking (2.1.0)
Using RxCocoa (2.1.0)
Using RxOptional (1.0.0)
Using RxSwift (2.1.0)
Using SDWebImage (3.7.5)
Using SWTableViewCell (0.3.7)
Using StatefulViewController (1.0)
Using Swinject (1.1.0)
Using SwipeView (1.3.2)
Using TTTAttributedLabel (1.13.4)
Using Tweaks (2.0.0)
Using UICountingLabel (1.4.0)
Using UXCam (2.5.3)
Using le (1.1)
Generating Pods project

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/bin/pod build install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin15.0]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.6.3
Ruby lib dir : /Users/jamescampbell/.rvm/rubies/ruby-2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 77f8d822c3371a4beed149a9987a744c7ac8a7ef
```

### Plugins

```
cocoapods-build   : 0.0.1
cocoapods-deploy  : 0.0.4
cocoapods-plugins : 0.4.2
cocoapods-stats   : 0.6.2
```

### Podfile

```ruby
use_frameworks!

target 'SupTests' do
  platform :ios, '8.0'

  #Testing
  pod 'Quick'
  pod 'Nimble'

  #Analytics
  pod 'Google/Analytics', '~> 1.0.0'
  pod 'GoogleTagManager'

  #Functional
  pod 'RxBlocking', '~> 2.1.0'
  pod 'RxCocoa', '~> 2.1.0'
  pod 'RxSwift', '~> 2.1.0'
  pod 'RxOptional', '~> 1.0.0'
end

target 'Sup-Watch Extension' do
  platform :watchos, '2.0'

  #Mapping
  pod 'ObjectMapper'

  #Functional
  pod 'RxBlocking', '~> 2.1.0'
  pod 'RxCocoa', '~> 2.1.0'
  pod 'RxSwift', '~> 2.1.0'
  pod 'RxOptional', '~> 1.0.0'
end

target 'Sup' do
  platform :ios, '8.0'

  #UI
  pod 'KVNProgress'
  pod 'SWTableViewCell', '~> 0.3.7'
  pod 'TTTAttributedLabel'
  pod 'SwipeView'
  pod 'UICountingLabel'

  #DI
  pod 'Swinject'

  #Core
  pod 'Crashlytics', '3.3.4'
  pod 'Branch'
  pod 'Fabric'
  pod 'Firebase'
  pod 'FBSDKCoreKit'
  pod 'FBSDKLoginKit'
  pod 'FBSDKShareKit'
  pod 'GeoFire', :git => 'https://github.com/jcampbell05/geofire-objc.git', :branch => 'master'
  pod 'JLRoutes'
  pod 'JTSImageViewController'
  pod 'JSQMessagesViewController'
  pod 'SDWebImage', :git => 'https://github.com/roger-tan/SDWebImage.git', :branch => 'master'
  pod 'Appirater'
  pod 'StatefulViewController', '~> 1.0'
  pod 'Parse'
  pod 'DateTools'
  pod 'Dwifft'
  pod 'NSOperationStack', :git => 'https://github.com/jcampbell05/NSOperationStack.git', :branch => 'master'

  #Analytics
  pod 'UXCam'
  pod 'Instabug'
  pod 'le'
  pod 'Heap'
  pod "Appsee"
  pod 'ARAnalytics', :subspecs => ["Mixpanel"]
  pod 'Google/Analytics', '~> 1.0.0'
  pod 'GoogleTagManager'
  pod 'Tweaks'

  #Functional
  pod 'RxBlocking', '~> 2.1.0'
  pod 'RxCocoa', '~> 2.1.0'
  pod 'RxSwift', '~> 2.1.0'
  pod 'RxOptional', '~> 1.0.0'

  #Misc
  pod 'Polly', '~> 0.2'
end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:579:in `block (2 levels) in prepare_pods_project'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:579:in `select'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:579:in `block in prepare_pods_project'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:550:in `prepare_pods_project'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:154:in `block in generate_pods_project'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:153:in `generate_pods_project'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:111:in `install!'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/jamescampbell/Documents/Workspace/cocoapods-build/lib/cocoapods-build/command/build.rb:34:in `run'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/bin/pod:23:in `load'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/bin/pod:23:in `<main>'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/bin/ruby_executable_hooks:15:in `eval'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/bin/ruby_executable_hooks:15:in `<main>'
```

The expected behaviour is the CocoaPods is able to create it's project file correctly but not integrate it into the project.

**Comment by segiddins** [comment] 2016-03-15 14:52
Please try with 1.0.

**Comment by jcampbell05** [comment] 2016-03-15 16:43
@segiddins tried with 1.0.0 at first it failed because it couldn't load the deintergrate plugin. Bundle complained about being locked to 1.0.0.beta.1 if I tried using beta6 for that plugin and CocoaPods still didn't recognize it if I used beta1.

I found a workaround to stop CocoaPods trying to use this plugin and it triggered another crash. 

```
NoMethodError - undefined method `integrate_targets=' for #<Pod::Config:0x007fb758a68e40>
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-rome-0.4.2/lib/cocoapods-rome/pre_install.rb:3:in `block in <top (required)>'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:111:in `call'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:111:in `block (3 levels) in run'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:144:in `message'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:103:in `block (2 levels) in run'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:101:in `each'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:101:in `block in run'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:144:in `message'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/hooks_manager.rb:100:in `run'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:443:in `run_plugins_pre_install_hooks'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:136:in `block in prepare'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/user_interface.rb:144:in `message'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:131:in `prepare'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/installer.rb:113:in `install!'
/Users/jamescampbell/.rvm/gems/ruby-2.1.5@sup-front-end/gems/cocoapods-1.0.0.beta.6/lib/cocoapods/command/install.rb:37:in `run'
```

This is using https://github.com/neonichu/Rome/tree/master/lib/cocoapods-rome
Is there going to be a less brutal roadmap to 1.0 ? Some sort of legacy plugin.

**Comment by jcampbell05** [comment] 2016-03-15 17:30
After more research, it seems if the outer podfile doesn't have a platform set, that is what causes the issues when disabling intergration for 0.39

This can be reproduced like so:

```
use_frameworks!

target 'SupTests' do
  platform :ios, '8.0'
end

target 'Sup-Watch Extension' do
  platform :watchos, '2.0'
end

target 'Sup' do
  platform :ios, '8.0'
end
```

**Comment by segiddins** [comment] 2016-04-01 00:24
Yeah, I'm pretty sure this is a bug that's been fixed in the latest release, but I know Rome doesn't have 1.0 compatibility yet 😁 Could you try just adding `install! 'cocoapods', integrate_targets: false` to your Podfile and seeing if it still crashes with 1.0 (without using Rome)? Thanks!

**Comment by neonichu** [comment] 2016-05-01 17:02
This issue has been inactive for some time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Closed by neonichu** 2016-05-01 17:02 UTC
Labels: s1:awaiting input
