### ISSUE TITLE
Podspec dependency not working for existing framework linked to swift-code framework

### ISSUE THREAD

**Issue by igabrielsabiescu** [CocoaPods/CocoaPods#5554] opened 2016-06-22 17:30 UTC
# Report

## What did you do?

Using private pod, i'm trying to build framework A that links with a given framework B (Crashlytics). 
The framework i'm trying to build is written in swift.
Framework A and B are both refrenced inside a given Project via cocoapods ( Framework A is a local pod while Framework B - Crashlytics - is from the official repo )

## What did you expect to happen?

Link Framework B inside Framework A.
Link Framework A inside project and have a successful build

## What happened instead?

When pod update:

Framework B - Crashlytics - does not generate umbrella files for module integration with Framework A ( again, a swift code framework )

## CocoaPods Environment

Cannot add

## Project that demonstrates the issue

Cannot add

**Comment by segiddins** [comment] 2016-06-22 17:40
We can't really look into this issue without a sample project, sorry!

**Comment by neonichu** [comment] 2016-07-18 09:44
Closing, because we never received a reproducible project.

**Closed by neonichu** 2016-07-18 09:44 UTC
Labels: s1:awaiting input
