### ISSUE TITLE
Unable to convert Ruby value into a CFTypeRef.

### ISSUE THREAD

**Issue by jacobbullock** [CocoaPods/CocoaPods#6019] opened 2016-10-10 23:38 UTC
### Command

```
/Users/jacob/.rvm/gems/ruby-2.2.0/bin/pod install
```

### Report

* What did you do?
Tried to run `pod install`

* What did you expect to happen?
For pods to be installed

* What happened instead?
Got an error at the end of pod install.  

This is not happening on a different computer with the same version of cocoapods installed.  Difference is that one computer is running sierra + xcode 8, the other is el capitan + xcode 7.3

I also removed cocoapods and all past versions and reinstalled it fresh

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.0p0 (2014-12-25 revision 49005) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/jacob/.rvm/rubies/ruby-2.2.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ f5b7608622aef359db57b81475531aaad51c9e36
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
source 'https://github.com/CocoaPods/Specs.git'
 platform :ios, '8.1'

target 'PABLO' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for PABLO
pod 'DeviceKit', :git => 'https://github.com/dennisweissmann/DeviceKit', :tag => '0.3.5'
pod 'MBProgressHUD', '~> 0.9.2'
pod 'ALSystemUtilities'
pod 'DGActivityIndicatorView'
pod 'KILabel', '1.0.0'
pod 'GaugeKit'
pod 'Kingfisher', '~> 2.4.2'
pod 'ObjectMapper', '~> 1.2'
pod 'AlamofireObjectMapper', '~> 3.0'
pod 'HanekeSwift'
pod 'GradientCircularProgress', :git => 'https://github.com/keygx/GradientCircularProgress', :tag => '3.3.1'
pod 'NextGrowingTextView'
pod 'Gifu'
pod 'UIColor_Hex_Swift', '~> 2.1'
pod 'GoogleMaps', '~>1.13.2'
pod 'CMSwitchView'
pod 'JSQWebViewController','~>3.0.0'
pod 'GPUImage'
pod 'BWWalkthrough'
pod 'Firebase'
pod 'Firebase/Core'
pod 'Firebase/Messaging'
pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'
pod 'JWTDecode','~>1.0'
  target 'PABLO.temp_caseinsensitive_renameTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'PABLO.temp_caseinsensitive_renameUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

### Error

```
TypeError - Unable to convert Ruby value `"ALSystemUtilities"' into a CFTypeRef.
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:383:in `RubyValueToCFTypeRef'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:372:in `RubyValueToCFTypeRef'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:402:in `block in RubyHashToCFDictionary'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `each'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi/core_foundation.rb:400:in `RubyHashToCFDictionary'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi.rb:130:in `ruby_hash_write_devtoolscore'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi.rb:120:in `ruby_hash_write_xcode'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist/ffi.rb:43:in `write_to_path'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/plist.rb:46:in `write_to_path'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/xcodeproj-1.3.2/lib/xcodeproj/project.rb:333:in `save'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:696:in `block in write_pod_project'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:688:in `write_pod_project'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:173:in `block in generate_pods_project'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/jacob/.rvm/gems/ruby-2.2.0@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/jacob/.rvm/gems/ruby-2.2.0/bin/pod:23:in `load'
/Users/jacob/.rvm/gems/ruby-2.2.0/bin/pod:23:in `<main>'
/Users/jacob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `eval'
/Users/jacob/.rvm/gems/ruby-2.2.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by orta** [comment] 2016-10-11 06:26
Thanks for the issue, closing as dupe of https://github.com/CocoaPods/CocoaPods/issues/5955 https://github.com/CocoaPods/CocoaPods/issues/5943 and https://github.com/CocoaPods/CocoaPods/issues/5536

**Closed by orta** 2016-10-11 06:26 UTC
