### ISSUE TITLE
Archive fails on 0.39 with WatchOS 2 target

### ISSUE THREAD

**Issue by swissdev** [CocoaPods/CocoaPods#4369] opened 2015-10-12 16:41 UTC
Hi

We are trying to build an archive since hours without luck. The CocoaPods WatchOS Example doesn't work too.
If we create a podfile like this it builds correctly but it doesn't show in the Organizer.

***
use_frameworks!
target 'Sample' do
pod 'Alamofire', '~> 2.0'
end

target 'Sample-Watch Extension' do
platform :watchos, '2.0'
pod 'Alamofire', '~> 2.0'
end
***

If we remove the WatchOS 2 target in the podfile, everything works fine. What are we doing wrong? We need to upload the app as soon as possible..

deduplicate_targets are not set.
Bitcode is only enabled on the watch target
Parallelize build is off

**Comment by segiddins** [comment] 2015-10-12 16:43
What version of CocoaPods are you using?

**Comment by segiddins** [comment] 2015-10-12 16:43
I'm guessing that this is actually just a duplicate of https://github.com/CocoaPods/CocoaPods/issues/4178

**Comment by swissdev** [comment] 2015-10-12 16:45
We are using cocoapods-0.39.0

It worked on 0.38.2 beta 4 and on Yosemite. 
Since update to El Capitan it doesn't work anymore.

**Comment by swissdev** [comment] 2015-10-12 16:57
We used the WatchOS sample in the latest CocoaPods release. Nothing changed except the Provisioning Profiles and it doesn't work.

It shows one warning:
/Users/xx/Downloads/CocoaPods-master/examples/watchOS Example/Pods/<module-includes>:1:1: Umbrella header for module 'Alamofire' does not include header 'Pods-watchOSsample WatchKit Extension-Alamofire-umbrella.h'

And the "Can not make directory ... Alamofire.Dsym.. File exist" in the console

**Comment by neonichu** [comment] 2015-10-13 07:43
@swissdev Can you check if removing the "Copy Pods Resources" build script phase works, as discussed in #4178?

**Comment by swissdev** [comment] 2015-10-13 09:16
Yes, the "Copy Pods Ressources" are removed. I've spend the whole night in debugging. Meanwhile I was able to archive the project with this settings:
- Setting the Debug Information Format to DWARF for Watch and Today Extension Pods
- Setting the Embedded Content contains Swift to NO for Today and Watch Extension on Project

I was able to upload it now, but it's still processing.. Hopefully it works...

**Comment by segiddins** [comment] 2016-03-08 06:26
@neonichu can this be closed?

**Closed** 2016-03-13 17:30 UTC
Labels: s1:awaiting input
