### ISSUE TITLE
Abstract targets in cocoapods 1.0.0

### ISSUE THREAD

**Issue by codewhisperer** [CocoaPods/CocoaPods#4902] opened 2016-02-16 15:18 UTC
I'm working on a shared framework for an iOS and a tvOS app. The issue I'm having is a new functionality in cocoapods described in issue #840 isn't working for me.

This is my pod-file:

```
use_frameworks!
abstract_target!

pod 'AlamofireObjectMapper'
pod 'AlamofireImage'

target 'QC_iOS_SDK' do
    platform :ios, '9.0'
end

target 'QC_tvOS_SDK' do
    platform :tvos, '9.1'
end
```

The error message I got was "Invalid `Podfile` file: undefined method `abstract_target!`
When I left the abstract_target! line out I got this error: "The dependency `AlamofireObjectMapper` is not used in any concrete target."

Could you please explain how abstract targets are implemented in cocoapods 1.0.0, currently I'm using beta3.

**Comment by segiddins** [comment] 2016-02-16 15:36
The root target is always abstract. Additionally, I think those dependencies aren't being inherited because the targets are for different platforms -- in that case, you'll need to specify the dependency for each target manually.

**Comment by 8masterofpuppets8** [comment] 2016-02-16 15:56
We also tried linking the dependencies for each target separately but the problem then is that they don't link for the tvOS app at all and are missing on build time.

```
use_frameworks!

def common_pods
    pod 'AlamofireObjectMapper'
    pod 'AlamofireImage'
end

target 'QC_iOS_SDK' do
    platform :ios, '9.0'
    common_pods
end

target 'QC_tvOS_SDK' do
    platform :tvos, '9.1'
    common_pods
end
```

When I check the generated Pods_QC_tvOS_SDK.framework it doesn't include any of the dependencies, so when we build the tv target it fails, so we were hoping that the abstract_target would solve this issue. Any ideas?

**Comment by mrackwitz** [comment] 2016-02-16 16:41
@segiddins:
>Additionally, I think those dependencies aren't being inherited because the targets are for different platforms -- in that case, you'll need to specify the dependency for each target manually. 

But this isn't supposed to happen?

**Comment by mrackwitz** [comment] 2016-02-16 16:47
@8masterofpuppets8:
>When I check the generated Pods_QC_tvOS_SDK.framework it doesn't include any of the dependencies, so when we build the tv target it fails, so we were hoping that the abstract_target would solve this issue. Any ideas?

The aggregate target's build product doesn't really matter. The aggregate target is just used to hold the dependencies to the pod targets and link them as implicit dependencies with the user project due to limitations with Xcode. I think the problem is that you are linking the targets to a framework target, which itself is likely linked to the TV app, I guess? So what you would need to do is adding these app targets as well to the Podfile. You can use search path inheritance for the SDK targets, but once #4146 is merged, you would be able to define them all adjacent as well, because then the duplication is strong enough to recognize these cases.

**Comment by 8masterofpuppets8** [comment] 2016-02-16 17:20
@mrackwitz yeah so the idea is to share some code between iOS and tvOS which makes some network calls using Alamofire. We have a framework project which consists of two targets - one for iOS and one for tvOS and want to link Alamofire to both of them. We use a special archive process which builds the .framework files separately for iOS and tvOS and those get included in the actual apps.

> So what you would need to do is adding these app targets as well to the Podfile. You can use search path inheritance for the SDK targets

No quite sure what you mean. Maybe a small example? Thanks!

**Comment by mrackwitz** [comment] 2016-02-17 21:39
Here you go:

```ruby
target 'QC_iOS_App' do
    platform :ios, '9.0'
    common_pods
    target 'QC_iOS_SDK' do
        inherit! :search_paths
    end
end
```

**Comment by 8masterofpuppets8** [comment] 2016-02-18 09:17
Thanks! Does this mean that the app projects needs to include the SDK project as a subproject?

**Comment by mrackwitz** [comment] 2016-02-18 11:04
So they are not targets in the same project? I think then it would be necessary anyway to include the SDK project as subproject in the app project, so that you're able to set a target dependency from the app project to the subproject.

**Comment by segiddins** [comment] 2016-03-10 17:19
Closing due to lack of response.

**Closed by segiddins** 2016-03-10 17:19 UTC
Labels: s1:awaiting input
