### ISSUE TITLE
Unable to read the license file from Pods and remove all pods.

### ISSUE THREAD

**Issue by gzfrancisco** [CocoaPods/CocoaPods#3703] opened 2015-06-19 04:07 UTC
The problem:

The last week I update all my pods but they didn't update because there is this problem:

> [!] Unable to read the license file `/Dir/Project/Pods/JSONModel/LICENSE_jsonmodel.txt` for the spec `JSONModel (1.1.0)`

So, I just remove the Pod folder and run again. I had the same result but now all the pods are gone.
I deleted ~/.cocoapods and ~/Library/Caches/CocoaPods/ and run `pod install` and have the same problem.
After doing that again and again, I saw the pods are downloaded and installed in my project but when is copy the licence the command just remove all the installed pods.

Ok, then. I had also a Rails application to connect my iOS app to the server. And I just updated to Ruby 2.2.0 and my Rails app also didn't work. So I read and search over.

I discover this: http://stackoverflow.com/questions/27871726/strange-error-in-rails-missing-helper
And that sends me to this issue in Rails project on Github https://github.com/rails/rails/issues/18660

In concrete this message:

> pixeltrix commented on Apr 23
> The problem is that there doesn't seem to be a way to normalise the case of the path without doing something like this:
>> Dir['/users/andyw/code/testapp'].first
>> => "/Users/andyw/Code/testapp"
>
> nothing else seems to work because as @matthewd pointed out this change was a last minute fix to Ruby 2.2 so it's only a change in Dir.glob code. I think we need to not rely on the path passed to Rack::Builder as Dir.pwd seems to return the correctly-cased path.

So, **I just change the Ruby version to 2.1.6** in my Rails project and it works and thought: maybe is the same issue in cocoa pods.

I was correct. My project also had a path with uppercases and lowercases and I'm on Yosemite.
It happens in Ruby 2.2.0, 2.2.1 and 2.2.2 on a old project or a new one.

PD
Sorry for my english.
I just look up for an issue with something similar but didn't found.

**Comment by neonichu** [comment] 2015-06-22 12:28
This issue is a little bit convoluted, could you please outline some clear steps you took and where your expected behaviour wasn't matched?

**Comment by gzfrancisco** [comment] 2015-06-22 16:11
Sure.

Steps:

1. Set ruby version to 2.2.0 or later.
1. New project (with Xcode or Liftoff)
1. $ pod init
1. Add some pods
1. $ pod install (some times here also show the problem)
1. $ rm -rf Pods Podfile.lock
1. $ pod update

> [!] Unable to read the license file `/Dir/To/Project/CocoaIssue/Pods/JSONModel/LICENSE_jsonmodel.txt` for the spec `JSONModel (1.1.0)`

**Comment by segiddins** [comment] 2015-09-29 14:36
Closing because the steps provided don't reproduce the issue.

**Closed by segiddins** 2015-09-29 14:36 UTC
Labels: s1:awaiting input
