### ISSUE TITLE
Permanent development pods

### ISSUE THREAD

**Issue by aleph7** [CocoaPods/CocoaPods#5591] opened 2016-07-03 20:48 UTC
I have a project with a number of components split into separate repositories. I want to be able to work on the components at the same time as the main project. Currently this can be achieved with development pods (pointing to the local filesystem). But this erases the version information, which is important for the test server.

It would be great if I could mark a pod as a development pod, but at the same time provide a tag for the build server. If I do `pod install --development` it will checkout submodules or point to the local filesystem but otherwise it will use the tags and behave as it does right now.

I would be happy to contribute to this feature.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

**Comment by neonichu** [comment] 2016-07-04 08:30
One way to already achieve this would be to make your Podfile conditional on some environment variable. Depending on its value, you could use development or release Pods.

Could look roughly like this (untested):

```ruby
def pods
  if ENV['DEV']
    pod 'ReactiveCocoa', :path => '…'
  else
    pod 'ReactiveCocoa'
  end
end
```

**Comment by orta** [comment] 2016-07-04 11:41
This ^ would still give you a `Podfile.lock` with [relative paths](https://github.com/artsy/eigen/blob/master/Podfile.lock#L287).

In order to achieve this, you would also need to make changes to the lockfile, so that everyone had a consistent lockfile. 

A lot of discussion around this this in these issues https://github.com/CocoaPods/CocoaPods/issues/2672 and https://github.com/CocoaPods/CocoaPods/issues/1010

**Comment by segiddins** [comment] 2016-07-05 19:00
Yeah, I'm going to close this as a duplicate of those issues -- we've simply not seen a great way to handle this yet.

**Closed by segiddins** 2016-07-05 19:00 UTC
Labels: t3:discussion
