### ISSUE TITLE
Backwards compatibility

### ISSUE THREAD

**Issue by rob-nash** [CocoaPods/CocoaPods#8001] opened 2018-08-11 10:40 UTC
Hi,

Cocoapods is a great effort. Big thanks goes out to everyone that takes part.

Cocoapods has focused on a quick and simple experience for it's users.

```bash
pod install
```

And the code is ready to go.

But I've noticed older projects don't feel this way.

<img width="967" alt="screen shot 2018-08-11 at 10 50 54" src="https://user-images.githubusercontent.com/14126999/43990562-a9ca74ae-9d54-11e8-9878-6152d0f17e6a.png">

I spent about 20 to 30% of my sessions, last year, searching stackoverflow for solutions to podfile issues.

Just performed a search for the keyword `Cocoapods` on stackoverflow and got 500 results. Take a look at the first post.

<img width="870" alt="screen shot 2018-08-11 at 11 36 20" src="https://user-images.githubusercontent.com/14126999/43990958-e036c488-9d5a-11e8-983b-fe7288c2fb60.png">

I think results are capped to 500 so I wonder how busy stacks really is, regarding Cocoapods issues.

I believe a dependency manager should stay out of the way as much as possible.

[For most of this year](https://github.com/CocoaPods/CocoaPods/issues/7995), I have avoided contributing to open source projects that heavily depend on Cocoapods. 

I'm sorry to say that but it's true 😅

**Comment by orta** [comment] 2018-08-11 13:06
Hi - I'm afraid this isn't really a bug report or a feature request, so I'm going to close this. 

It's also not particularly nice message, people work on CocoaPods in their spare time to help the community. You're welcome to help out like us, or write blog posts like you're issue - you're very welcome to your opinions but please don't come into our repos and leave rude messages.

**Closed by orta** 2018-08-11 13:06 UTC

**Comment by rob-nash** [comment] 2018-08-11 15:25
@orta very bizarre response

i don't have the skill set to contribute to this repo

I'm highlighting an issue to you where cocoapods has started to hinder the community, which i should imagine is something you don't want to do. I suppose the next time cocoapods causes a problem that defeats the very objectives its sets out to achieve, **I will avoid bringing it to your  attention** because you apparently can't take **any criticism**.

have a nice day

**Comment by orta** [comment] 2018-08-11 17:44
I'm just trying to keep the issues civil and focused @rob-nash - a dependency manager is critical path for a lot of people's work, so as you can imagine, people can get heated. CocoaPods has hundreds of thousands of users, so we get some pretty unfocused feedback.

The culture of our issues for this repo is basically the baseline for how we would want to be treated ourselves. Asking you to provide actionable ideas or to help out, and not use our issues as a way to vent at the contributors helping isn't unreasonable I think.

That said, you definitely do have the skills to help out 👍 - nearly all the core devs here learned ruby in contributing to CocoaPods. You only need programming skills and time.

**Comment by paulb777** [comment] 2018-08-11 20:54
@rob-nash I don't think there is anyone who would argue that CocoaPods doesn't have issues. A quick browse though the github repos' Issues lists shows otherwise.  I'm not sure a survey would provide any substantial additional data. As @orta pointed out, CocoaPods is the result of volunteer contributions. If it's helpful to you, you're welcome to use it. If not, you're free to use something else or contribute to making CocoaPods do what you need.  CocoaPods direction is defined by its contributions.

For the SDK product I'm employed to develop, CocoaPods quality almost doesn't matter, since my company wants the product to reach as many iOS developers as possible and CocoaPods is by far the most popular iOS dependency manager.  And my contributing to CocoaPods helps both my product and the CocoaPods community in general.

While CocoaPods has many issues and it can be a challenge to continue to support Apple's ever-changing build systems, CocoaPods does a lot of things very well and there is a good reason for its popularity. That success is due to the contributions of many developers over the past several years who overcame a non-trivial learning curve to jump into the commons and contribute.  The subset of developers proficient in both Ruby and Xcode build file internals is not a very large one.

So pick a CocoaPods issue you're passionate about and dive in. Or contribute to Carthage or something else. We know there are deficiencies. Let's work together on addressing them.

**Comment by rob-nash** [comment] 2018-08-12 10:02
@paulb777 i've heard this argument already. I didn't ask for cocoapods, nor did I ask for you guys to get together and build it.

You guys have built something that has become so popular, it is on my doorstep and I can't avoid it.

So i have the right to start an issue and **have it filed in the issues list, along with all of the other issues there**. i don't appreciate having **my issue closed** because the issue offends you.

Yes, carthage is my 'go to' dependency manager of choice, but I still must use cocoapods when I discover projects that use it. it's unavoidable.

A lot of developers are using Cocoapods because they are unaware that it doesn't last. Over time, it breaks down. A lot of iOS developers have only 1 or 2 years experience and that number has been growing steadily for the last couple of years. There's a graph somewhere showing the number of new devs joining the platform. This one is close enough.

![what](http://static3.uk.businessinsider.com/image/5935da0cda6dde31f709e7e2-1200/cotd65.png)

So there has been a huge efflux of developers who are new to Cocoapods and are not aware of how well cocoapods stands the test of time. So in my opinion, backwards compatibility is a huge issue for you guys and you should **definitely not close it prematurely**!

I can't contribute to cocoapods because i don't have the skill set. I don't intend to acquire the skill to fix problems that you guys introduced into the community.

All I am arguing for is to have an issue filed here and not closed prematurely. That's it. Accept that this is a real problem because I see it everyday, literally every day and it directly effects the trade that I use to earn a living and feed my family.

So don't close my issue and accuse me of being 'difficult'. Yes, backward compatibility is a difficult issue. At least face up to it.

**Comment by amorde** [comment] 2018-08-12 19:08
When I first saw this issue I was quite confused as I didn't really know what you were saying the issue was. The title is "Backwards compatibility",  but you don't mention anything about that in body of the issue. You did include a screenshot of a Podfile error for a deprecated DSL attribute, but again it's not very clear what you are saying the issue is or what CocoaPods could do to improve.

If you feel that CocoaPods is not doing a good job of maintaining backwards compatibility, I would recommend describing why you feel that way. 

Did CocoaPods:

* Deprecate many DSL attributes that were heavily used?
* Change its syntax frequently?
* Fail to notify the community about the changes?
* Change DSL attributes that were not worth changing?

Key points that we can improve on or discuss such as these would be helpful.

> It's no good if in 6 months time, someone discovers your project and they can't compile it because the podfile has been deprecated. I understand that you are actively maintaining the project (and it's podfile) but I'm arguing the case that a podfile should manage the test of time better than it currently does.

I don't think it's fair to say a project that worked 6 months ago no longer compiles. The Podfile DSL has been pretty constant since 1.0 was released, which is when the Podfile DSL changed the most. There were very good reasons for the changes, and there's even a blog post discussing what changed and why that you can check out: [the 1.0 Migration Guide](http://blog.cocoapods.org/CocoaPods-1.0-Migration-Guide/). The version numbers of CocoaPods also imply this - CocoaPods was pre-1.0 for quite a while, and only hit 1.0 when the core team thought it was ready for 1.0.  There aren't any plans to rewrite the DSL any time soon, and the changes since then have all been additive as far as I know. 

I agree that we should keep backwards compatibility in mind going forward. A Podfile that was created with CocoaPods 1.0 should still work today, and that's great.

**Comment by rob-nash** [comment] 2018-08-13 11:26
Hi @amorde 

Negative. I have no data. Nothing specific. Just anecdotal observations over time. I didn't make any notes of what the individual issue were. I only have the screenshot of Stackoverflow (above). 

We could get some data from a poll that simply asks the public if this growing pain has become an issue for a sizeable percentage of your users (it has for me personally).

If I attempted to gather data over the next several weeks, it would be impossible to gather enough data to fairly represent the public at large. So I'm asking for a bit of faith in my previous anectodal observations, which I know might be a stretch.

I wasn't expecting a revolution from this thread. But I certainly wasn't expecting to be accused of being mean and having my ticket prematurely closed.
