### ISSUE TITLE
Platform not taken into consideration when resolving dependencies

### ISSUE THREAD

**Issue by tumatauenga** [CocoaPods/CocoaPods#4840] opened 2016-01-28 19:23 UTC
🌈

I am attempting to support both `tvos` and `ios` is a library I'm writing.  I have a dependency on `ios` that requires `'AFNetworking' ~> '2.0'`.

On `tvos` I have no such dependency, but I need a minimum of `'AFNetworking' ~> '3.0'`. My `podspec` file has the following info:

```
  s.ios.deployment_target = '8.0'
  s.tvos.deployment_target = '9.0'

  s.dependency 'AFNetworking'
  s.ios.dependency 'SignalR-ObjC', '2.0.0.beta3'
```

I thought that when running `pod install` against a `tvos` target, that the ios dependency that requires `'AFNetworking' ~> '2.0'` wouldn't be factored into the equation, and I would end up with the latest version of `AFNetworking` installed, however I get the error below:

```
Resolving dependencies of `Podfile`
[!] The platform of the target `Pods` (tvOS 9.0) is not compatible with `AFNetworking (2.6.3)`, which does not support `tvos`.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:355:in `validate_platform'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:445:in `valid_dependencies_for_target_from_node'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:450:in `block in valid_dependencies_for_target_from_node'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:450:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:450:in `flat_map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:450:in `valid_dependencies_for_target_from_node'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:82:in `block (3 levels) in specs_by_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:80:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:80:in `flat_map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:80:in `block (2 levels) in specs_by_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:79:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:79:in `block in specs_by_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:78:in `tap'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:78:in `specs_by_target'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```
If I explicitly state the `AFNetworking` requirements for `tvos` like this:

```
  s.tvos.dependency 'AFNetworking', '~>3.0'
  s.ios.dependency 'SignalR-ObjC', '2.0.0.beta3'
```

I get this error, despite the fact that the `SignalR-ObjC` library is not a dependency of the `tvos` platform:

```
Resolving dependencies of `Podfile`
[!] Unable to satisfy the following requirements:

- `AFNetworking (~> 2.0)` required by `SignalR-ObjC (2.0.0.beta3)`
- `AFNetworking (~> 3.0)` required by `MCCore-iOS-SDK (2.0.0-alpha)`

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:411:in `handle_resolver_error'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:69:in `rescue in resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:57:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

FYI this happens in both CocoaPods `0.39.0` and `1.0.0.beta.2`

**Comment by segiddins** [comment] 2016-01-28 22:06
That's because `MCCore-iOS-SDK` requires afnetworking ~> 3, versus ~> 2 for SignalR-ObjC

**Comment by tumatauenga** [comment] 2016-01-29 03:33
Thanks @segiddins. I'm actually the author of `MCCore-iOS-SDK`. It doesn't have an explicit requirement for `'AFNetworking', '~> 3.0'`, it's fine with `2.0`, that's how it can still work with `SignalR-ObjC`, which requires `'AFNetworking', '~>2.0'`

My issue is that the earliest version of `AFNetworking` that supports `tvos` is `3.0`. For `tvos` I have stated that I don't need `SignalR-ObjC` by stating the dependency as `ios` only: `s.ios.dependency 'SignalR-ObjC', '2.0.0.beta3'`, however when I run `pod install` against my `tvos` app, it seems that CocoaPods is still resolving dependencies against this `SignalR-ObjC` library (even though i've listed this as only a dependency for `ios`), so it installs `'AFNetworking', '~> 2.0'`, instead of `3.0`. Since `2.0` doesn't support `tvos` I get this error.

I hope that's clear...

**Comment by segiddins** [comment] 2016-02-03 17:42
I actually think this is the intended behavior, since adding a new platform in your Podfile shouldn't change the resolved versions of other pods you're already using.

**Comment by segiddins** [comment] 2016-02-24 17:40
Closing as 'behaves as intended'.

**Closed by segiddins** 2016-02-24 17:40 UTC

**Comment by maheshverma** [comment] 2016-05-13 12:54
I am facing the same scenario where I need AFNetworking 3.0 but due to signalR dependency on AFNetworking 2.0, I am stuck. So can we explicitly update a dependency (AFNetworking in my case)?

**Comment by orta** [comment] 2016-05-13 12:55
Yes - `pod update [pod_name`

**Comment by maheshverma** [comment] 2016-05-13 12:59
[!] The `[AFNetworking]` Pod is not installed and cannot be updated

and if I add this before installing pods, then 

[!] Unable to satisfy the following requirements:
- `AFNetworking (~> 3.0)` required by `Podfile`
- `AFNetworking (~> 2.0)` required by `SignalR-ObjC/Core (2.0.2)`

How should I resolve this?

**Comment by orta** [comment] 2016-05-13 13:00
This looks like a great example of a question that you should ask on [StackOverflow](http://stackoverflow.com) - there is an active tag [CocoaPods](http://stackoverflow.com/tags/cocoapods) where people can help out with questions like this. We try to keep the CocoaPods issues focused only on bug reports for the tool, and for upcoming feature requests. Which this isn't anymore.
