### ISSUE TITLE
CocoaPods Error

### ISSUE THREAD

**Issue by potap75** [CocoaPods/CocoaPods#5156] opened 2016-04-15 02:57 UTC
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

### Command

```
/Users/rpotapov/.rvm/rubies/ruby-2.3.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.0
Ruby lib dir : /Users/rpotapov/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ b23c4d45b02aa441752c52649fac10d91755dbc8
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project

platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Firebase', '>=2.5.0'

target 'FirebaseJokes' do

end

target 'FirebaseJokesTests' do

end

target 'FirebaseJokesUITests' do

end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="Firebase">
Did you mean?  to_query
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/rpotapov/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/rpotapov/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `eval'
/Users/rpotapov/.rvm/gems/ruby-2.3.0@global/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by segiddins** [comment] 2016-04-15 03:37
This is a duplicate of about 25 issues -- ruby 2.3.0 is not compatible with CocoaPods 0.39. Either use an older ruby or update to the CocoaPods 1.0 betas.

**Closed by segiddins** 2016-04-15 03:37 UTC
