### ISSUE TITLE
1.0 - @IBDesignables broken on dynamic frameworks

### ISSUE THREAD

**Issue by redent** [CocoaPods/CocoaPods#5588] opened 2016-07-01 09:41 UTC
# Report

## What did you do?

🌈 Steps to reproduce:

1. Create a new iOS Framework project.
2. Create and add any dependency to the `Podfile` file (sample below).
3. Execute `pod install` and open `.xcworkspace` file.
4. Create a custom `IBDesignable` `UIView` subclass (sample code below).
5. Create a new XIB or Storyboard and add the custom view.

<pre><code>import UIKit
@IBDesignable class CustomView: UIView {
    override init(frame: CGRect) {
        super.init(frame: frame)
        layer.cornerRadius = 10
    }
    required init?(coder aDecoder: NSCoder) {
        super.init(coder: aDecoder)
        layer.cornerRadius = 10
    }
}</code></pre>

## What did you expect to happen?

It should render the view correctly and show a rounded borders view.

## What happened instead?

Interface builder fails with the following error:
>    file:///Users/xxxxx/workspace/FooFramework/FooFramework/View.xib: error: IB Designables: Failed to update auto layout status: dlopen(FooFramework.framework, 1): Library not loaded: @rpath/Alamofire.framework/Alamofire
>      Referenced from: FooFramework.framework
>      Reason: image not found
>    
>    file:///Users/xxxxx/workspace/FooFramework/FooFramework/View.xib: error: IB Designables: Failed to render instance of CustomView: dlopen(FooFramework.framework, 1): Library not loaded: @rpath/Alamofire.framework/Alamofire
>      Referenced from: FooFramework.framework
>      Reason: image not found

And doesn't render the custom view.

Code compiles and runs correctly on simulator. This issue only affects Interface Builder not rendering custom `@IBDesignable` views.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ dea88a38a506172d75710d358d734070682a9041
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'
use_frameworks!

target 'FooFramework' do
pod 'Alamofire'
end
```

## Project that demonstrates the issue

Sample project can be downloaded here: [FooFramework.zip](https://www.dropbox.com/s/r4i8cgs4nkkvq4r/FooFramework.zip?dl=0)

**Workaround**

Current workaround is fall back to 0.39:

    pod _0.39.0_ install

**Comment by redent** [comment] 2016-07-01 09:51
Related to (duplicated by?) #5334.

**Comment by neonichu** [comment] 2016-07-01 11:35
Yep, this is a duplicate of #5334 — that issue also contains a workaround you can apply while using 1.x

**Closed by neonichu** 2016-07-01 11:35 UTC
