### ISSUE TITLE
[CDN] pod search failure

### ISSUE THREAD

**Issue by rakuyoMo** [CocoaPods/CocoaPods#9015] opened 2019-07-18 01:56 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run `pod search WechatOpenSDK`

## What did you expect to happen?

Get search results for WechatOpenSDK

## What happened instead?

Creating search index for spec repo 'cocoapods-'..[!] Can't retrieve all the pod sets for a CDN-backed source, it will take forever

### Stack

```
   CocoaPods : 1.7.4
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.18.0
Ruby lib dir : /Users/mbcore/.rvm/rubies/ruby-2.4.0/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ 53cc469815b2f25482f00681ed68b52f169b4a20
               MBCModuleSpecs - https://git.mbcore.com/iOSModuleSwift/MBCModuleSpecs.git @ 0f023dbe68f43ebdd03bfbb8c05ef7f8ddb8d52a
               mbcore-iosmodule-mbcspecs - https://git.mbcore.com/iOSModule/MBCSpecs.git @ d798117f5725bc1c9f6d1f7811857db209beb4eb
               MBCSpecs - git@git.mbcore.com:iOSModule/MBCSpecs.git @ d798117f5725bc1c9f6d1f7811857db209beb4eb
```

### Installation Source

```
Executable Path: /Users/mbcore/.rvm/rubies/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment] 2019-07-18 02:02
This is intentional as the error msg suggests. cc @igor-makarov for additional context. For now I am closing as "works as intended" and I will re-open if something else should happen.

**Comment by rakuyoMo** [comment] 2019-07-18 02:04
> This is intentional as the error msg suggests. cc @igor-makarov for additional context. For now I am closing as "works as intended" and I will re-open if something else should happen.

But how do I use the search feature now?

I can't use the search function. Is there any way I can use it?

**Comment by dnkoutso** [comment] 2019-07-18 02:07
Its not supported with CDN. Maybe we can be explicit about this.

**Comment by rakuyoMo** [comment] 2019-07-18 02:09
> Its not supported with CDN. Maybe we can be explicit about this.

When I use the CDN for `pod install`, does it mean I need to discard `pod search`?

Why not skip the CDN when not in `pod search`?

**Comment by dnkoutso** [comment] 2019-07-18 02:30
Hmmm yes @igor-makarov should we update search command to skip CDN sources?

**Comment by rakuyoMo** [comment] 2019-07-18 02:49
And as far as I know, some of my friends, repo contains CDN source, but `pod search` can be executed, and get the correct search results. His version of Cocoapods is **1.7.2**.

I don't know what caused this difference.

**Comment by igor-makarov** [comment] 2019-07-18 04:24
Do we have some API for web-based full text search? Could build that into the CDN somehow.

BTW if it's just name matching, CDN can do it. Perhaps it should just emit a warning and do that?

**Comment by dnkoutso** [comment] 2019-07-18 05:37
At the very least we should not crash so I am not sure how @rakuyoMo got into this mode where it crashes.

I think there is an API https://github.com/CocoaPods/cocoapods-search/blob/master/lib/cocoapods-search/command/search.rb

**Comment by dnkoutso** [comment] 2019-07-18 05:37
Marking for 1.8.0.

**Comment by rakuyoMo** [comment] 2019-07-18 05:39
> At the very least we should not crash so I am not sure how @rakuyoMo got into this mode where it crashes.
> 
> I think there is an API https://github.com/CocoaPods/cocoapods-search/blob/master/lib/cocoapods-search/command/search.rb

Reproducing this problem is very simple, just need to include `CDN Source` in your repo, then execute `pod search SomePod`, you will see this problem

**Comment by igor-makarov** [comment] 2019-07-18 05:54
OK so I looked into it and the full text search is confusing me. 

There's `Pod::Source::Manager#search_by_name` which ultimately tries to index each source and gets into each `Source` and tries to get a list of all pod sets. This is where it errors out.

There's also an implementation of full text search in `Pod::Source` but that isn't actually reached by the `pod search` command. In fact, I'm not sure it can be reached at all.

I could make `pod_sets` and `all_specs` do a warn instead of raise but it looks even more puzzling that way: 

```
$ bundle exec pod search baconkit
Creating search index for spec repo 'cocoapods-'.. Done!
Creating search index for spec repo 'netlify-'.. Done!
[!] Unable to find a pod with name, author, summary, or description matching `baconkit`

[!] Skipping retrieval of all the pod sets for a CDN-backed source as it will take forever

[!] Skipping retrieval of all the pod sets for a CDN-backed source as it will take forever
```

Granted, if one has the git specs repo then something will be found there, but it's out intention that people do not use the git specs.

**Comment by dnkoutso** [comment] 2019-07-18 06:05
I am OK to launch 1.8 without search being supported for CDN. We can just warn and say "[!] CDN Source `source_name` does not support search." or something like that.

**Comment by igor-makarov** [comment] 2019-07-18 06:16
Yeah, but where to put the warning? 😂  
(BTW only full text search is unsupported)

**Comment by manuyavuz** [comment] 2019-07-19 14:18
Hmm, I think then we can just direct user to use `--web` or `--simple` options if there is CDN repo?

The thing is, after I optimized full text search by multiple factors, there was no difference in response time, so we made full text search as default option, adding `--simple` as option. So directing user there should be enough.

**Comment by manuyavuz** [comment] 2019-07-19 14:31
Main story is here:

https://github.com/CocoaPods/Core/blob/1cdc4dafb0216db74f010ad077fd9ef034d343ae/lib/cocoapods-core/source/manager.rb#L183-L195
```ruby
      def updated_search_index
        index = stored_search_index || {}
        all.each do |source|
          source_name = source.name
          unless index[source_name]
            CoreUI.print "Creating search index for spec repo '#{source_name}'.."
            index[source_name] = aggregate.generate_search_index_for_source(source)
            CoreUI.puts ' Done!'
          end
        end
        save_search_index(index)
        index
      end
```

If we want pod search to just ignore cdn sources, best option to add a new method returning only non-cdn sources, and use that method instead of `all` when calling `all.each`.

If we want to warn user and redirect, we will need a check for source type in above method, and give appropriate warning.

I think it's better to warn because people might not have master repo anymore, which means pod search would only search for other repo based sources, and won't return anything from main specs repo.

**Comment by igor-makarov** [comment] 2019-07-19 16:23
This is the thing I worry about:
> I think it's better to warn because people might not have master repo anymore, which means pod search would only search for other repo based sources, and won't return anything from main specs repo.

**Comment by manuyavuz** [comment] 2019-07-19 16:34
Yes, then we can just fail and warn users to use either `--simple` or `--web` if they have a CDN source.

**Comment by dnkoutso** [comment] 2019-07-19 23:57
Sounds good to me.

**Comment by rakuyoMo** [comment] 2019-07-20 08:44
By the way, I hope that the `pod search` operation does not add the `master` repo.

I think this will affect the efficiency of `pod update`.

**Comment by igor-makarov** [comment] 2019-07-20 09:12
1.7.x still adds it in some cases. It will not be installed by default starting from 1.8.0.

**Comment by pointrlabs** [comment] 2019-07-20 11:35
`pod search` will always add master spec into index if you have that. This is the default way, and will stay that way. It’s effect on `pod update` is negligible because it performs it’s job asynchronously, and index update completes quickly.

If you don’t want to have full text search, you can always use `--simple` or `--web` options.

**Comment by manuyavuz** [comment] 2019-07-20 11:39
`pod search` will always add master spec into index if you have that. This is the default way, and will stay that way. It’s effect on `pod update` is negligible because it performs it’s job asynchronously, and index update completes quickly.

If you don’t want to have full text search, you can always use `--simple` or `--web` options.

**Comment by rakuyoMo** [comment] 2019-07-22 01:10
> `pod search` will always add master spec into index if you have that. This is the default way, and will stay that way. It’s effect on `pod update` is negligible because it performs it’s job asynchronously, and index update completes quickly.
> 
> If you don’t want to have full text search, you can always use `--simple` or `--web` options.

In my usual work, the most time-consuming part of the `pod update` operation is `Updating spec repo master`, so I want to switch to the CDN source. This may be caused by different network environments in different countries, but in any case, this is the fact that I want to avoid.

Therefore, I still hope that as of @igor-makarov , starting from 1.8.x, the master source will not be added by default.

**Comment by dnkoutso** [comment] 2019-07-22 15:18
To re-iterate `pod search` in 1.8.x *will not* add the master specs repo. It will add the _index_ to it _if_ it has been setup as @manuyavuz said.

That said this issue is more about how to handle `pod search` when a CDN source is present and I think we have a path forward.

**Comment by HnZhouZhong** [comment] 2019-07-22 16:04
> 顺便说一下，我希望`pod search`操作不添加`master`回购。
> 
> 我认为这会影响效率`pod update`。



> > 至少我们不应该崩溃，所以我不确定@rakuyoMo是如何进入这种模式崩溃的。
> > 我认为有一个API https://github.com/CocoaPods/cocoapods-search/blob/master/lib/cocoapods-search/command/search.rb
> 
> 重现这个问题非常简单，只需要`CDN Source`在你的repo中包含，然后执行`pod search SomePod`，你就会看到这个问题

Now I cannot use Pod search XX. The following is my error report:
[!] CDN: making - Relative path couldn 't be downloaded: CocoaPods - version. Yml, error: Failed to open a TCP connection to github.com CocoaPods - version. Yml: 443 (getaddrinfo: Nodename nor servname provided, or not known)。
Have you solved this problem？？

**Comment by dnkoutso** [comment] 2019-07-22 16:19
This is irrelevant GitHub is having issues.

**Comment by HnZhouZhong** [comment] 2019-07-22 16:26
But I can't use the pod search command anymore. I've reinstalled the pod and it still doesn't work. How can I fix this problem

**Comment by dnkoutso** [comment] 2019-07-22 16:26
You have to wait for Github to be fixed. https://developer.mozilla.org/en-US/docs/Web/HTTP/Status

**Comment by rakuyoMo** [comment] 2019-07-23 01:20
> But I can't use the pod search command anymore. I've reinstalled the pod and it still doesn't work. How can I fix this problem

Can I understand that you are in China? Maybe you need a VPN, or maybe you need to do this again when a network is better. Not connected to Github or Cocoapods is a common thing, sad

**Comment by HnZhouZhong** [comment] 2019-07-23 01:28
> > 但我不能再使用pod搜索命令了。我重新安装了pod，它仍然无法正常工作。我该如何解决这个问题
> 
> 我能理解你在中国吗？也许您需要VPN，或者当网络更好时您可能需要再次执行此操作。没有连接到Github或Cocoapods很常见，很难过

I can confirm that my network is ok. I reinstalled the pod and the corresponding environment, pod setup was successful, but pod search was not possible. I also tried different WiFi and tested it with 4G, which was also not possible.

**Comment by HnZhouZhong** [comment] 2019-07-23 01:29
Yesterday I upgraded swift5.0 and added the source address of the company to podfile, and then I can't use pod search

**Closed** 2019-07-29 13:40 UTC
Labels: s2:confirmed

**Comment by iOSCountry** [comment] 2019-08-28 11:57
Hello, I also encountered the same problem, but I read the chat history above you, I still don't understand how to solve it.

**Comment by rakuyoMo** [comment] 2019-08-29 01:38
> Hello, I also encountered the same problem, but I read the chat history above you, I still don't understand how to solve it.

You need to wait for the 1.8.x version update

**Comment by dnkoutso** [comment] 2019-08-29 01:44
This is shipped with 1.8.0.beta.2

**Comment by akzhang** [comment] 2019-09-18 03:43
It does't work yet, upgrade to 1.8.0.beta.2.

**Comment by yunjinghui123** [comment] 2019-11-25 10:05
I also encountered the same problem,  I still don't understand how to solve it.
CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [x86_64-darwin19]
    RubyGems : 3.0.6
        Host : Mac OS X 10.15.1 (19B88)
       Xcode :  ()
         Git : git version 2.21.0 (Apple Git-122.2)
### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0

pod search WechatOpenSDK
[!] Unable to find a pod with name, author, summary, or description matching `WechatOpenSDK`

**Comment by igor-makarov** [comment] 2019-11-25 10:17
This appears to be a different issue. 

`pod search` doesn't add the Trunk repo before searching.

**Comment by yunjinghui123** [comment] 2019-11-25 14:51
I upgraded cocoapods to 1.8.4 and removed the master according to the documentation. After that, pod search can no longer be used. Is the pod search command not available in versions 1.8.4 and later?

**Comment by igor-makarov** [comment] 2019-11-25 15:08
No, it's a bug, just not the one reported in the issue in which you're commenting in.

I suggest you open a separate issue for it.

**Comment by yunjinghui123** [comment] 2019-11-25 15:38
I have already proposed a new issue.
 https://github.com/CocoaPods/CocoaPods/issues/9366
