### ISSUE TITLE
Linting dynamics frameworks should fail if the module cannot be build.

### ISSUE THREAD

**Issue by b-ray** [CocoaPods/CocoaPods#3671] opened 2015-06-11 08:55 UTC
We are currently in the transition of moving our pods to dynamic frameworks.
Unfortunately we've found some issues with import statements to files from other pods not using the module-name after we've released the new versions.

So the problem was that linting and releasing the pods did not show the errors, they showed up later when trying to use files from the newly released dynamic framework pods.

Is there a way to make the linting fail for dynamic frameworks if there are problems with import statements (so that the module can actually not be imported)?

**Comment by neonichu** [comment] 2015-06-17 12:16
This is a duplicate of #2134

**Closed by neonichu** 2015-06-17 12:16 UTC
