### ISSUE TITLE
Private Cocoapods Repo

### ISSUE THREAD

**Issue by jeffreyjackson** [CocoaPods/CocoaPods#5484] opened 2016-06-08 12:11 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I tried to pod update on an repo which uses private cocoapods repo.  

## What did you expect to happen?
Cocoapods 1.0 would still see my repo source and pull as previously designed.

## What happened instead?
Cocoapods 1.0 couldn't find repo 

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : AutoLean-Cocoapods - https://github.com/AutoLean/Specs @ a16f55ba4231088562d0be777ef062e174072810
               forcedotcom - https://github.com/forcedotcom/SalesforceMobileSDK-iOS-Specs.git @ 62e9a9c8072bf4aaf834bd693c0bbcf9b92bb71d
               master - https://github.com/CocoaPods/Specs.git @ 49a2996d6d29d60fa0f39229fe3eac889e0590b2
               Norton-Specs - https://github.com/AutoLean/Norton-Specs.git @ 301f3e976a7d9c129ef2344741d81eabd339d526
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/AutoLean/Specs.git'

platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

target :Audit5S

pod 'iRate'
pod 'Parse'
pod 'ParseUI'
pod 'ParseCrashReporting'
pod 'uservoice-iphone-sdk'
pod 'iVersion'
pod 'ALFonts'
pod 'ALAppCatalog'
pod 'IGIdenticon'
pod 'SVProgressHUD'
pod 'Flurry-iOS-SDK'
pod 'JJTwitterAutofollow'
```

## Project that demonstrates the issue
I'll have to create one if necessary

**Comment by neonichu** [comment] 2016-06-08 16:58
Could you please share the concrete error you are receiving?

**Comment by jeffreyjackson** [comment] 2016-06-08 17:00
It's breaking on ALAppCatalog which is a repo that is housed under the private specs repo.  

```
[!] Unable to find a specification for `ALAppCatalog`
```

**Comment by jeffreyjackson** [comment] 2016-06-08 17:00
Thanks for following up @neonichu

**Comment by segiddins** [comment] 2016-06-08 17:24
what does `pod search ALAppCatalog` yield?

**Comment by jeffreyjackson** [comment] 2016-06-08 17:26
```
-> ALAppCatalog (4.1)
   UITableViewController for displaying available apps
   pod 'ALAppCatalog', '~> 4.1'
   - Homepage: http://www.autolean.com
   - Source:   https://github.com/AutoLean/ALAppCatalog-iOS.git
   - Versions: 4.1, 4.0, 3.9, 3.7, 3.6, 3.5, 3.4, 3.3, 3.2, 3.1, 3.0, 2.9, 2.8, 2.7,
   2.6, 2.5, 2.4, 2.3, 2.2, 2.1, 2.0, 1.1.1, 1.1, 1.0 [AutoLean-Cocoapods repo]
```

**Comment by segiddins** [comment] 2016-06-08 17:31
From that, it looks like its in the 'AutoLean-Cocoapods' repo -- are you sure that's included in your Podfile?

**Comment by jeffreyjackson** [comment] 2016-06-08 17:53
Yes, I've been using this method for over a year now - maybe 2?  It's only broken since 1.0.

**Comment by jeffreyjackson** [comment] 2016-06-09 12:47
If it helps, this is the [specs repo](https://github.com/autolean/specs)

**Comment by manuyavuz** [comment] 2016-06-13 08:25
Issue is caused by the change introduced in CocoaPods/Core@01ca6fad8.

Your pod's name in `.podspec` file is different from the pod name itself (which is implicitly inferred from the basename of `.podspec` file). I'm not sure what's the expected behavior here.

@segiddins thoughts on this?

**Comment by manuyavuz** [comment] 2016-06-13 09:10
Hi @jeffreyjackson,
Value of the `name` attribute inside your `.podspec` must match with the basename of the `.podspec` file.

Your pod's podspec file is named as `ALAppCatalog.podspec`, but the `name` attribute is `ALAppCatalog-iOS`. This is why CocoaPods couldn't find your pod.

Normally, `pod spec lint` fails with the following error in above case:

```
- ERROR | name: The name of the spec should match the name of the file.
```

So you will need to update your podspec accordingly.

Closing now, if your problem continues after that change, please inform us again.

**Closed by manuyavuz** 2016-06-13 09:10 UTC
