### ISSUE TITLE
Incorrect owner name (is EVCloudKitDao, should be evermeer)

### ISSUE THREAD

**Issue by evermeer** [CocoaPods/CocoaPods#6372] opened 2017-01-04 11:42 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

When I look for my 10 pods on cocoapods.org I see that they are: 'Maintained by EVCloudkitDao' which was the name of the first pod that I published. I would think it should say 'Maintained by evermeer'. If I look at the owner, then it's also called EVCloudKitDao. See https://cocoapods.org/owners/5259

## What did you expect to happen?

I would think it should say 'Maintained by evermeer'

## What happened instead?

 I see that they are: 'Maintained by EVCloudkitDao' which was the name of the first pod that I published.

### Stack

```
   CocoaPods : 1.2.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ab0398625eee91b8fe182776d77bd4337cceccf8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

All projects on https://cocoapods.org/owners/5259

**Comment by dnkoutso** [comment] 2017-02-18 19:43
@orta do you think this issue should be filed here instead of the cocoapods.org repo?

**Comment by orta** [comment] 2017-02-18 21:54
Looks like the end result of this conversation would be a dupe of https://github.com/CocoaPods/trunk.cocoapods.org/issues/155

So I'm closing it here

**Closed by orta** 2017-02-18 21:54 UTC
