### ISSUE TITLE
Unable to find a specification for a local (private) pod.

### ISSUE THREAD

**Issue by ocbnishi** [CocoaPods/CocoaPods#9803] opened 2020-05-20 19:28 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I created two local pods: `MainPods` & `ChildPod` like this:
1. Create Framework (in Xcode)
2. pod init & pod install
3. modify it

Then I inited pod in root folder of application:
 platform :ios, '13.0'

```
target 'PrivatePodBugDemo' do
  use_frameworks!
  # pod 'ChildPod', :path => 'DevPods/ChildPod'
  pod 'MainPod', :path => 'DevPods/MainPod'
end
```

## What did you expect to happen?

I expected to all run good when I include **only** `MainPod` which already includes `ChildPod`.

## What happened instead?

This error happened
```
[!] Unable to find a specification for `ChildPod` depended upon by `MainPod`
```
It's disappears when I uncomment `pod 'ChildPod', :path => 'DevPods/ChildPod'` in app's Podfile.
But I need to not include ChildPod in app's Podfile.

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.1.3
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.24.2 (Apple Git-127)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '13.0'

target 'PrivatePodBugDemo' do
  use_frameworks!

  # pod 'ChildPod', :path => 'DevPods/ChildPod'
  pod 'MainPod', :path => 'DevPods/MainPod'
end
```

## Project that demonstrates the issue
https://github.com/ocbnishi/PrivatePodBugDemo

**Comment by dnkoutso** [comment] 2020-05-20 19:33
`MainPod.podspec` has `s.dependency 'ChildPod'` so CocoaPods needs to know where to find this dependency. You have no `source` declaration in your `Podfile` and CocoaPods searchs for public pods named 'ChildPod' which do not exist.

Either remove the dependency or do what you have by uncommenting `# pod 'ChildPod', :path => 'DevPods/ChildPod'` so CocoaPods knows to find `ChildPod` from this path.

Closing as working as expected, please ask questions in StackOverflow under `cocoapods` tag.

**Closed by dnkoutso** 2020-05-20 19:33 UTC

**Comment by ocbnishi** [comment] 2020-05-20 19:44
> You have no `source` declaration in your `Podfile` and CocoaPods searches for public pods named `ChildPod` which does not exist anywhere.

@dnkoutso what do you mean?
How to define `source` on `Podfile` if they are placed local in app subfolder?

**Comment by dnkoutso** [comment] 2020-05-20 19:45
CocoaPods right now does not support discovering local pods automatically. You either have to publish them to a repo (public or your own internal one) or explicitly specify the `:path` directive for each pod. 

`Podfile` is a Ruby file so you can also fairly easily write code that discovers local pods and invokes `pod`.

**Comment by ocbnishi** [comment] 2020-05-20 19:48
So app `Podfile` should include every local pods and subpods like this, right?
```
App
├─ ChildPod
└─ MainPod
   └─ ChildPod
```

Or you are talking about `:path` in `.podspec`? I was trying it but it's deprecated now

**Comment by dnkoutso** [comment] 2020-05-20 19:50
you cant put `:path` in podspec as they are meant to be published...just add `:path` in your `Podfile` for all local podspecs.

**Comment by ocbnishi** [comment] 2020-05-20 19:53
I'm starting to feel stupid but 
`pod 'MainPod', :path => 'DevPods/MainPod/'` 
and 
`pod 'MainPod', :path => 'DevPods/MainPod/MainPod.podspec'` 
have the same behaviour and still invokes same error

**Comment by dnkoutso** [comment] 2020-05-20 19:57
The problem is can't find ChildPod. I apologize but I cannot continue explaining further here. The above answers should have what you need to understand how these things work.
