### ISSUE TITLE
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007f8d3a8fd6e8>

### ISSUE THREAD

**Issue by rmuhamedgaliev** [CocoaPods/CocoaPods#4742] opened 2016-01-08 05:58 UTC
### Command

```
/usr/local/opt/rbenv/versions/2.2.4/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/opt/rbenv/versions/2.2.4/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 39e1491ac3d416164a7687876dc56b36373d3292
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007f8d3a8fd6e8>
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/opt/rbenv/versions/2.2.4/lib/ruby/gems/2.2.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/opt/rbenv/versions/2.2.4/bin/pod:23:in `load'
/usr/local/opt/rbenv/versions/2.2.4/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment] 2016-01-09 17:17
This is a duplicate of #4741.

**Closed by segiddins** 2016-01-09 17:17 UTC
