### ISSUE TITLE
App dependent on PubNub 3.7.11 won't build in cocoapods 1.0.0beta6 but works fine in 1.0.0beta5

### ISSUE THREAD

**Issue by gregpassmore** [CocoaPods/CocoaPods#5051] opened 2016-03-17 21:51 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
We have a complex project that depends on PubNub 3.7.11. It works fine in old versions of cocoapods (0.38 etc). We upgraded to 1.0.0beta6 and pod install works, but the final build script fails to find the PubNub.bundle and tells us to run pod install to fix it. Downgrading to 1.0.0beta5 fixes the issue (luckily). 

## What did you do?

Ran pod install and then built workspace.

## What did you expected to happen?

 Install all pod dependencies correctly and build successfully .

**Comment by WinterKirk** [comment] 2016-03-22 19:41
I am also experiencing this issue in 1.0.0beta6 with OAStackView.

**Comment by segiddins** [comment] 2016-04-01 00:45
This is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/5034.

**Closed by segiddins** 2016-04-01 00:45 UTC
