### ISSUE TITLE
NoMethodError - undefined method `swift_version=' for

### ISSUE THREAD

**Issue by bolom** [CocoaPods/CocoaPods#5599] opened 2016-07-06 14:16 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

bundle exec pod install

## What did you expect to happen?

 Install all pod dependencies correctly.

### Error

```
NoMethodError - undefined method `swift_version=' for #<Pod::Podfile::TargetDefinition label=Pods-Goyava>
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/analyzer/target_inspector.rb:47:in `compute_results'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/analyzer.rb:763:in `block (3 levels) in inspect_targets_to_integrate'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/analyzer.rb:760:in `each'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/analyzer.rb:760:in `block (2 levels) in inspect_targets_to_integrate'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/analyzer.rb:758:in `each'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/analyzer.rb:758:in `block in inspect_targets_to_integrate'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/user_interface.rb:63:in `section'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/analyzer.rb:753:in `inspect_targets_to_integrate'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer.rb:234:in `analyze'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer.rb:148:in `block in resolve_dependencies'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/user_interface.rb:63:in `section'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer.rb:147:in `resolve_dependencies'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer.rb:111:in `install!'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/command/install.rb:37:in `run'
/Users/Michelin/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/command.rb:50:in `run'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/bin/pod:55:in `<top (required)>'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bin/pod:22:in `load'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bin/pod:22:in `<main>'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

## CocoaPods Environment

```
platform :ios, '9.0'
use_frameworks!

target 'Goyava' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'LookbackSafe', :configurations => ['Release']
    pod 'RealmSwift'
    pod 'Reachability'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end

```

**Comment by DanToml** [comment] 2016-07-06 14:35
@bolom It looks like you're using CocoaPods Master but not doing the same for Core?

**Comment by bolom** [comment] 2016-07-06 14:45
@DanToml yes i am using the master version bc with the code version i have got this error
![capture d ecran 30](https://cloud.githubusercontent.com/assets/72155/16622035/85fec9e8-4366-11e6-9f6f-037d89be3b9c.png)

**Comment by bolom** [comment] 2016-07-06 20:13
this Gemfile i have got the previous error

```

target 'Goyava' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'AWSMobileAnalytics'
    pod 'LookbackSafe', :configurations => ['Release']
    pod 'RealmSwift'
    pod 'Reachability'
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['SWIFT_VERSION'] = '3.0'
    end
  end
end
```

### Error

```
NoMethodError - undefined method `try' for <Pod::PodTarget name=RealmSwift >:Pod::PodTarget
Did you mean?  trap
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:287:in `add_language_specific_settings'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:228:in `add_target_specific_settings'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:65:in `generate'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/generator/xcconfig/pod_xcconfig.rb:35:in `save_as'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:211:in `create_xcconfig_file'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:24:in `block in install!'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/user_interface.rb:141:in `message'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/user_interface.rb:141:in `message'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer.rb:177:in `block in generate_pods_project'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/user_interface.rb:63:in `section'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer.rb:176:in `generate_pods_project'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/installer.rb:116:in `install!'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/command/install.rb:37:in `run'
/Users/Michelin/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/lib/cocoapods/command.rb:50:in `run'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-4fdb40b0b138/bin/pod:55:in `<top (required)>'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bin/pod:22:in `load'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bin/pod:22:in `<main>'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/Michelin/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by DanToml** [comment] 2016-07-06 21:57
huh. IIRC `try` is defined as part of `active_support`, so that could be `active_support/core_ext/object/try` not being required maybe? \c @segiddins

**Comment by DanToml** [comment] 2016-07-06 22:01
Yeah, I just managed to reproduce this locally (interestingly specs don't catch this one). Will push up a PR now.

**Comment by DanToml** [comment] 2016-07-06 22:06
this is fixed with https://github.com/CocoaPods/CocoaPods/pull/5600

**Comment by segiddins** [comment] 2016-07-07 00:31
You can also `gem install beta-pod && beta-pod master install` if you're into using wacky things created by segiddins

**Closed** 2016-07-07 10:52 UTC

**Comment by bolom** [comment] 2016-07-11 01:53
working for me guys tks!
