### ISSUE TITLE
Single quote in path, which CocoaPods can't handle.

### ISSUE THREAD

**Issue by Kartik-AI** [CocoaPods/CocoaPods#9163] opened 2019-09-18 08:07 UTC
@dnkoutso @segiddins @alloy 
# Report

## What did you do?
->  After adding shared_preferences: ^0.5.3+4 through flutter.  
-> than I am running my project and when pod install command is run it start but after some time it gives error.

Stripped /Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/Gonal_App/goanlapp/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework/Flutter of
    architectures: armv7 arm64
    Code Signing /Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/Gonal_App/goanlapp/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework with Identity -
    /usr/bin/codesign --force --sign -  --preserve-metadata=identifier,entitlements
    '/Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/Gonal_App/goanlapp/build/ios/Debug-iphonesimulator/Runner.app/Frameworks/Flutter.framework'
    /Users/ivorywebdesign/Documents/Kartik/VikramGandhi'sProject/Gonal_App/goanlapp/ios/Pods/Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh: eval: line 131: unexpected EOF
    while looking for matching `''
    Command PhaseScriptExecution failed with a nonzero exit code
    note: Using new build systemnote: Planning buildnote: Constructing build description

Could not build the application for the simulator.
Error launching application on iPhone 8 Plus.

## What did you expect to happen?

-> Means when Target Support Files/Pods-Runner/Pods-Runner-frameworks.sh file create there is a line having single Quote which is 
-> local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements '$1'"

so I think it should be like this 
local code_sign_cmd="/usr/bin/codesign --force --sign ${EXPANDED_CODE_SIGN_IDENTITY} ${OTHER_CODE_SIGN_FLAGS:-} --preserve-metadata=identifier,entitlements \"$1\""

## What happened instead?

-> if i do manually duble qoute of '$1' to  \"$1\" and run the code it always replace my code in default like previous

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G84)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8df8af6419407c98e2b3c224b9ea5c6e74230b9e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

Download the Demo Project from below link :- 
https://drive.google.com/open?id=1kU0I7tsB7EEA3RbBGThqPnQ89eYs6idc

**Comment by dnkoutso** [comment] 2019-09-18 15:51
Hey thanks for the issue. This is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/7546 I believe.

**Closed** 2019-09-20 14:47 UTC

**Comment by Kartik-AI** [comment] 2019-09-20 15:26
Hey Thanks @dnkoutso i have resolve the issue.
Actually in my folder path i am having folder name which has single quote(') so that's the reason behind this issue.
