### ISSUE TITLE
Consistency issue: build setting `SDKROOT` has multiple values

### ISSUE THREAD

**Issue by uranusjr** [CocoaPods/CocoaPods#2594] opened 2014-10-04 16:50 UTC
Not sure whether this is the same problem as #2305.

### Report

This fails when I set the Base SDK setting to different values for debug and release builds. I’m trying to have different values so that I can run my tests on Travis CI (which has dropped 10.8 support, so requires 10.9+ SDK) but ensure API availability when releasing (targeting 10.8+).

### Stack

```
   CocoaPods : 0.34.1
        Ruby : ruby 2.1.2p95 (2014-05-08 revision 45877) [x86_64-darwin13.0]
    RubyGems : 2.4.2
        Host : Mac OS X 10.9.5 (13F34)
       Xcode : 6.0.1 (6A317)
Ruby lib dir : /Users/uranusjr/.rbenv/versions/2.1.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0e15664c8f380d5738fab437fb2e9b296758a745
```

### Plugins

```
cocoapods-plugins : 0.3.1
cocoapods-trunk   : 0.2.0
cocoapods-try     : 0.4.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, "6.0"

source 'https://github.com/CocoaPods/Specs.git'

target "MacDown" do
  pod 'handlebars-objc', '~> 1.3'
  pod 'hoedown', '~> 2.0', :inhibit_warnings => true
  pod 'JJPluralForm', '~> 2.1'
  pod 'LibYAML', '~> 0.1.4', :inhibit_warnings => true
  pod 'M13OrderedDictionary', '1.0.3'
  pod 'MASPreferences', '~> 1.1'
  pod 'PAPreferences', '~> 0.2'
  pod 'Sparkle', '~> 1.7.1'
end

target "MacDownTests" do
  pod 'PAPreferences'
end
```

### Error

```
RuntimeError - [Xcodeproj] Consistency issue: build setting `SDKROOT` has multiple values: `{"Debug"=>"macosx", "Release"=>"macosx10.8"}`
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcodeproj-0.19.2/lib/xcodeproj/project/object/native_target.rb:79:in `common_resolved_build_setting'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcodeproj-0.19.2/lib/xcodeproj/project/object/native_target.rb:86:in `sdk'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/xcodeproj-0.19.2/lib/xcodeproj/project/object/native_target.rb:92:in `platform_name'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:492:in `block in compute_platform_for_target_definition'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:491:in `each'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:491:in `compute_platform_for_target_definition'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:540:in `block (2 levels) in compute_target_platforms'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:535:in `each'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:535:in `block in compute_target_platforms'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:534:in `compute_target_platforms'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer/analyzer.rb:50:in `analyze'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:184:in `analyze'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/user_interface.rb:49:in `section'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/installer.rb:90:in `install!'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/command/project.rb:101:in `run'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/lib/cocoapods/command.rb:48:in `run'
/Users/uranusjr/.rbenv/versions/2.1.2/lib/ruby/gems/2.1.0/gems/cocoapods-0.34.1/bin/pod:33:in `<top (required)>'
/Users/uranusjr/.rbenv/versions/2.1.2/bin/pod:23:in `load'
/Users/uranusjr/.rbenv/versions/2.1.2/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment] 2015-09-25 17:04
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/2305.

**Closed by segiddins** 2015-09-25 17:04 UTC
Labels: d1:easy
