### ISSUE TITLE
Multiple target install error with Cocoapods 1.0 on Target Support Files

### ISSUE THREAD

**Issue by jerometonnelier** [CocoaPods/CocoaPods#5522] opened 2016-06-15 15:31 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
I just migrated to Cocoapods 1.0 (this morning it worked fine with old version).
I have a project with multiple targets (we provide white label apps). I struggled a lot not to include all targets in the pod file since we will have a lot of them soon, but I ended with declaring a common include and adding the include within every target as follows :

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

def testing_pods
	pod 'AcknowledgementsBundle'
	pod 'Cosmos'
	pod 'PermissionScope'
	pod 'LECropPictureViewController'
	pod 'SwiftDate'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'KMPlaceholderTextView'
	pod 'GMStepper'
	pod 'JSQWebViewController'
	pod 'AFBlurSegue'
	pod 'XLPagerTabStrip'
	pod 'SimpleAnimation'
	pod 'KYDrawerController'
	pod 'DynamicButton'
	pod 'MGSwipeTableCell'
	pod 'PhoneNumberKit'
end
 
target 'Target1' do
    testing_pods
end

target 'Target2' do
    testing_pods
end
```

## What did you do?

ℹ Please replace this with what you did.  
Run `pod install` and/or `pod update`

## What did you expect to happen?

ℹ Please replace this with what you expected to happen.  
Install all pod dependencies correctly.

## What happened instead?
I keeping getting an error about the Target Support file missing : 

```
Errno::ENOENT - No such file or directory - /Users/jerometonnelier/Documents/Sources/Project/Pods/Target Support Files/Pods
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/project.rb:186:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/project.rb:186:in `realpath'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/project.rb:186:in `add_file_reference'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:185:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:183:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:183:in `block in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:178:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:178:in `add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:106:in `block in add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:104:in `add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/file_references_installer.rb:40:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:609:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:169:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

I tried to remove the pod folder (manually and with Terminal), completely remove and reinstall cocoa pods. Nothing works :-/

## CocoaPods Environment
`### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.8.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : cocoapods-specs - git@10.10.12.107:libraries/cocoapods-specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               master - https://github.com/CocoaPods/Specs.git @ fdeab0150c4f811dc33db08c74e66cb75b54697e
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!

def testing_pods
	pod 'AcknowledgementsBundle'
	pod 'Cosmos'
	pod 'PermissionScope'
	pod 'LECropPictureViewController'
	pod 'SwiftDate'
	pod 'Fabric'
	pod 'Crashlytics'
	pod 'KMPlaceholderTextView'
	pod 'GMStepper'
	pod 'JSQWebViewController'
	pod 'AFBlurSegue'
	pod 'XLPagerTabStrip'
	pod 'SimpleAnimation'
	pod 'KYDrawerController'
	pod 'DynamicButton'
	pod 'MGSwipeTableCell'
	pod 'PhoneNumberKit'
end
 
target 'Target1' do
    testing_pods
end

target 'Target2' do
    testing_pods
end
````

Thanks for your help :)

**Comment by jerometonnelier** [comment] 2016-06-22 09:56
Am I doing something wrong or is it a real bug? 
Thanks.

**Comment by segiddins** [comment] 2016-06-22 15:49
Could you please share a project that reproduces the bug?  Thanks!

**Comment by neonichu** [comment] 2016-07-18 09:44
Closing, because we never received a reproducible project.

**Closed by neonichu** 2016-07-18 09:44 UTC
Labels: s1:awaiting input
