### ISSUE TITLE
Error while deleting pod version from trunk

### ISSUE THREAD

**Issue by SanjoDeundiak** [CocoaPods/CocoaPods#7288] opened 2017-12-16 22:32 UTC
## What did you do?
pod trunk delete VirgilCryptoFork 0.0.1

## What did you expect to happen?
pod version is removed

## What happened instead?
https://pastebin.com/xmQyMmgH

### Stack
```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.1 (17B1003)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /usr/local/Cellar/ruby/2.4.1_2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a3896b491b263b2696a45eb67ad79bc0d3bced67
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment] 2017-12-16 22:42
What is the pod you are trying to remove?

**Comment by orta** [comment] 2017-12-16 23:08
This is a dupe of https://github.com/CocoaPods/trunk.cocoapods.org/issues/168 I think

**Comment by dnkoutso** [comment] 2017-12-16 23:14
ok I also think it does not belong here so @SanjoDeundiak please see if the issue above is the same or create a new one in the cocoapods trunk repo.

**Closed by dnkoutso** 2017-12-16 23:14 UTC
