### ISSUE TITLE
EMBEDDED_CONTENT_CONTAINS_SWIFT = YES causes app being rejected

### ISSUE THREAD

**Issue by marcvanolmen** [CocoaPods/CocoaPods#4515] opened 2015-11-07 17:40 UTC
I spend an hour trying to create an simple app to locate the bug but I failed, so sorry I have to do it with just a description:

We have project that contains 4 targets (1 iOS app, 1 iOS framework, 1 tvOS app, 1 tvOSframework).

• The tvOS app contains Swift code.
• The tvOSframework doesn't contain Swift code but one of the frameworks it uses contains Swift code.

When we run pod install the tvosframework gets the flag added

EMBEDDED_CONTENT_CONTAINS_SWIFT = YES

When Xcode builds this framework it creates inside the Framework another folder called Framework. (which is empty) When we submit the app, iTunes Connect refuses the app with the error that this Framework folder is not allowed.

When we manually override EMBEDDED_CONTENT_CONTAINS_SWIFT = NO, rebuild our app everything is ok.

```
EMBEDDED_CONTENT_CONTAINS_SWIFT = YES
FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_FRAMEWORK_BUILD_PATH"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
OTHER_CFLAGS = $(inherited) -iquote "$PODS_FRAMEWORK_BUILD_PATH/Aspects.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/FXKeychain.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/JLRoutes.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/MKTools.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/Mantle.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/Objection.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/RMStore.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/RNCryptor.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/RTVVideoEffects.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/SDWebImage.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/TRToolkit.framework/Headers" -iquote "$PODS_FRAMEWORK_BUILD_PATH/TRVideoKit.framework/Headers"
OTHER_LDFLAGS = $(inherited) -ObjC -all_load -framework "Aspects" -framework "FXKeychain" -framework "JLRoutes" -framework "MKTools" -framework "Mantle" -framework "Objection" -framework "RMStore" -framework "RNCryptor" -framework "RTVVideoEffects" -framework "SDWebImage" -framework "TRToolkit" -framework "TRVideoKit"
OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
PODS_FRAMEWORK_BUILD_PATH = $(BUILD_DIR)/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)/Pods-ReutersTVCore_tvOS
PODS_ROOT = ${SRCROOT}/Pods
```

**Comment by segiddins** [comment] 2015-11-07 17:51
Are you using cocoapods to integrate into a framework?

**Comment by marcvanolmen** [comment] 2015-11-07 18:06
No we use Xcode to add this framework. The framework itself uses several cocoapods so the above is the config of one of the cocoapods generated files for this frameowork.

**Comment by segiddins** [comment] 2015-11-13 04:49
Can you share a project that reproduces the issue? Since setting that build setting definitely should _not_ cause a rejection.

**Comment by marcvanolmen** [comment] 2015-11-17 16:37
I haven't been able to replicate it in non - private project I will try more over the next week.

**Comment by segiddins** [comment] 2015-11-17 16:51
Awesome, thanks for following up!

**Comment by andreyslyusar** [comment] 2015-11-18 11:22
Hi, I have a similar issue. Swift project 'A' with dynamic Swift framework 'B'. B has cocoapods dependencies:
```
target 'B', :exclusive => true do
  pod 'Typhoon', '~> 3.3'
  pod 'R.swift'
  pod 'SwiftColors'
  pod 'Alamofire', '~> 3.0'
end
```
Created workspace will have EMBEDDED_CONTENT_CONTAINS_SWIFT = YES both for A and B, but without changing EMBEDDED_CONTENT_CONTAINS_SWIFT to NO for B will lead to reject iTC, similar case https://github.com/CocoaPods/CocoaPods/issues/4419.

```
[!] The `Project [Debug]` target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in `Pods/Target Support Files/Pods-Project/Pods-Project.debug.xcconfig'. This can lead to problems with the CocoaPods installation
    - Use the `$(inherited)` flag, or
    - Remove the build settings from the target.
```

**Comment by segiddins** [comment] 2015-11-18 13:54
@andreyslyusar as requested above, please share a project we can use to reproduce the issue.

**Comment by jigneshsheth** [comment] 2015-11-20 21:20
I am having the same issue when start using the Alamofire by cocoapods.

**Comment by neonichu** [comment] 2015-11-26 13:56
Closing, since we never got a project to reproduce — we can reopen if someone can provide one.

**Comment by marcvanolmen** [comment] 2015-11-26 14:43
Because I'm in NY, I will bring our project on Dec 5th to the http://www.meetup.com/CocoaPods-NYC/ to see this helps.

**Comment by itsthejb** [comment] 2015-12-04 17:43
Hi all,

This sounds a bit like an issue we're having: we have a (non-Pod) internal Swift dynamic framework at the moment. If we have `EMBEDDED_CONTENT_CONTAINS_SWIFT = YES` then Xcode include the root dylibs inside that framework's `Frameworks` folder in the bundle:

![screen shot 2015-12-04 at 18 41 21](https://cloud.githubusercontent.com/assets/557391/11596644/a0d7b7c4-9ab6-11e5-8a91-18428ee6e255.png)

ie. you have `App.bundle/Frameworks/AwesomeInternalFramework.framework/Frameworks`. This appears to be incorrect and ITC will complain.

However, if we override `EMBEDDED_CONTENT_CONTAINS_SWIFT = NO` for the framework target, Cocoapods compains with:

`target overrides the `EMBEDDED_CONTENT_CONTAINS_SWIFT` build setting defined in...`

Therefore I think the Cocoapods warning is incorrect, and should not insist on this for framework targets (and possibly others).

Shouldn't be too hard to create a test project if necessary. Just let me know :+1:

**Comment by andreyslyusar** [comment] 2015-12-08 10:42
@neonichu do you still need an example project? Does @marcvanolmen managed to project example on NY meetup?

**Comment by marcvanolmen** [comment] 2015-12-08 12:56
I wasn't able to find the time to go to the meetup, so if you have a sample project please provide it.

**Comment by andreyslyusar** [comment] 2015-12-09 11:58
@neonichu here is an example of project: https://github.com/andreyslyusar/CocoaPods-Issue-4515

Example of error while upload iTC:
![screenshot 2015-12-09 12 45 16](https://cloud.githubusercontent.com/assets/1401690/11684756/1d0947f2-9e74-11e5-9e4a-56724ff1ab88.png)

```EMBEDDED_CONTENT_CONTAINS_SWIFT``` should be  ```EMBEDDED_CONTENT_CONTAINS_SWIFT = NO``` for EmbeddedFramework:
![screenshot 2015-12-09 12 54 09](https://cloud.githubusercontent.com/assets/1401690/11684799/6fd7aa00-9e74-11e5-809a-4016ff82702a.png)

**Comment by itsthejb** [comment] 2015-12-10 08:02
Can confirm that @andreyslyusar's demo project exactly recreates what we're seeing as well. Thanks for that!

**Comment by neonichu** [comment] 2015-12-10 08:36
Thanks for the example project!

**Comment by jegv91** [comment] 2016-01-18 18:34
Any updates on this issue?

**Comment by segiddins** [comment] 2016-01-18 19:52
@jegv91 not yet, but a PR with a fix would be much appreciated!

**Comment by Ben-G** [comment] 2016-01-19 22:55
@jegv91 I'm currently using a post install hook as a workaround:

	post_install do |installer|
		system "sed -i '' -E 's/EMBEDDED_CONTENT_CONTAINS_SWIFT[[:space:]]=[[:space:]]YES/EMBEDDED_CONTENT_CONTAINS_SWIFT = NO/g' Pods/Target\\ Support\\ Files/Pods-LibraryTargetName/*.xcconfig"
	end

Not elegant, but does the job for now.

**Comment by Kkhattab** [comment] 2016-01-20 06:44
@Ben-G where do u put this install hook ?

**Comment by ArtSabintsev** [comment] 2016-01-20 08:23
@Kkhattab you put it in the podfile (example: https://guides.cocoapods.org/syntax/podfile.html)

**Comment by Kkhattab** [comment] 2016-01-20 08:31
@ArtSabintsev I know you didn't suggest doing it but when i did it still didnt work, this is what I am experiencing. 

<img width="554" alt="screen shot 2016-01-20 at 12 29 06 am" src="https://cloud.githubusercontent.com/assets/6819847/12443500/04e3c756-bf0d-11e5-8249-ddd8c0d4da70.png">
![screen shot 2016-01-20 at 12 30 45 am](https://cloud.githubusercontent.com/assets/6819847/12443502/0ec61418-bf0d-11e5-9eb6-0852f4128732.png)

![screen shot 2016-01-20 at 12 28 50 am](https://cloud.githubusercontent.com/assets/6819847/12443469/dd9b56aa-bf0c-11e5-9f58-c059ed822a59.png)

**Comment by ArtSabintsev** [comment] 2016-01-20 15:10
Can you drop a copy of your podfile in here?

**Comment by Kkhattab** [comment] 2016-01-20 17:22
`platform :ios, ‘8.0’`
`use_frameworks!`

`target 'Rydite' do`
   `pod 'LayerKit'`
   `pod 'Atlas'`
   `pod 'NYTPhotoViewer'`
   `pod 'MBProgressHUD', '~> 0.9.1'`
   `pod 'SBPickerSelector'`
   `pod 'SWRevealViewController', :git => 'https://github.com/John-Lluch/SWRevealViewController.git'`
  `pod 'SwiftHEXColors'`
   `pod 'CWStatusBarNotification', '~> 2.3.3'`
   `pod 'Parse'`
   `pod 'IQKeyboardManagerSwift'`
   `pod 'PageMenu'`
  `pod 'GoogleMaps', '1.10.5'`
   `pod 'SPGooglePlacesAutocomplete', '~> 1.0'`
   `pod 'FPPopover', :git => 'https://github.com/alvises/FPPopover.git'`
`end`

**Comment by ArtSabintsev** [comment] 2016-01-20 18:20
can you add the post-install script in there as well?

**Comment by Kkhattab** [comment] 2016-01-20 18:33
`platform :ios, ‘8.0’`
`use_frameworks!`

`target 'Rydite' do`
   `pod 'LayerKit'`
   `pod 'Atlas'`
   `pod 'NYTPhotoViewer'`
   `pod 'MBProgressHUD', '~> 0.9.1'`
   `pod 'SBPickerSelector'`
   `pod 'SWRevealViewController', :git => 'https://github.com/John-Lluch/SWRevealViewController.git'`
  `pod 'SwiftHEXColors'`
   `pod 'CWStatusBarNotification', '~> 2.3.3'`
   `pod 'Parse'`
   `pod 'IQKeyboardManagerSwift'`
   `pod 'PageMenu'`
  `pod 'GoogleMaps', '1.10.5'`
   `pod 'SPGooglePlacesAutocomplete', '~> 1.0'`
   `pod 'FPPopover', :git => 'https://github.com/alvises/FPPopover.git'`
`end`

`post_install do |installer|`
    `system "sed -i '' -E 's/EMBEDDED_CONTENT_CONTAINS_SWIFT[[:space:]]=[[:space:]]YES/EMBEDDED_CONTENT_CONTAINS_SWIFT = NO/g' Pods/Target\\ Support\\` `Files/Pods-LibraryTargetName/*.xcconfig"`
`end`

It still get the same results as i posted above

**Comment by ArtSabintsev** [comment] 2016-01-20 18:36
ok, will take a look in a sample project later

```
platform :ios, ‘8.0’
use_frameworks!

target 'Rydite' do
pod 'LayerKit'
pod 'Atlas'
pod 'NYTPhotoViewer'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'SBPickerSelector'
pod 'SWRevealViewController', :git => 'https://github.com/John-Lluch/SWRevealViewController.git'
pod 'SwiftHEXColors'
pod 'CWStatusBarNotification', '~> 2.3.3'
pod 'Parse'
pod 'IQKeyboardManagerSwift'
pod 'PageMenu'
pod 'GoogleMaps', '1.10.5'
pod 'SPGooglePlacesAutocomplete', '~> 1.0'
pod 'FPPopover', :git => 'https://github.com/alvises/FPPopover.git'
end

post_install do |installer|
system "sed -i '' -E 's/EMBEDDED_CONTENT_CONTAINS_SWIFT[[:space:]]=[[:space:]]YES/EMBEDDED_CONTENT_CONTAINS_SWIFT = NO/g' Pods/Target\\ Support\\ Files/Pods-LibraryTargetName/*.xcconfig"
end
```

Thanks.

**Comment by Ben-G** [comment] 2016-01-20 18:40
Sorry if this was unclear, but you need to rename "Pods-LibraryTargetName"
in the script to the name of the Pods project specific to the target for
which you want to set the flag. E.g. "Pods-MyAwesomeFramework".

--
Benjamin Encz

Find me on twitter: @benjaminencz <https://twitter.com/benjaminencz>

**Comment by Kkhattab** [comment] 2016-01-20 19:04
@Ben-G ok i will try it would it essentially be `Pods-MyAppNameHere` ?

**Comment by Ben-G** [comment] 2016-01-20 19:19
@Kkhattab it would `Pods-MyFrameworkNameHere`. For the main app you should leave the `EMBEDDED_CONTENT_CONTAINS_SWIFT` setting untouched. You should only use this override for any frameworks that you are providing, in addition to the app. In our case we were importing an internal framework into our app. We needed to disable the flag for that internal framework.

**Comment by Kkhattab** [comment] 2016-01-20 20:25
@Ben-G yeah this doesn't seem to mitigate the issue for me. What's odd is I am not even adding a internal framework, I just wanted to add frameworks from cocoapods and then I started running into this issue.

**Comment by obitow** [comment] 2016-03-09 11:16
Hi, I have the same problem in my project. Setting this flag to No solves it, but the warning every time I run update or install annoys me a little. Can CocoaPods check if the target is a Framework, so the .xconfig file doesn't set EMBEDDED_CONTENT_CONTAINS_SWIFT to Yes?

**Comment by Kkhattab** [comment] 2016-03-09 11:23
@obitow  i believe the fix is to make sure you do not have any frameworks used in other frameworks in your cocoapods, so basically do not nest your frameworks.

**Comment by paulz** [comment] 2016-05-22 08:15
As a workaround, we simply ignore `EMBEDDED_CONTENT_CONTAINS_SWIFT` set by cocoapods:
https://gist.github.com/paulz/e1fb44c96fdfbcbbb29086adb7100d3f

```
post_install do |installer|
    ignore_overriding_contains_swift(installer, 'MyFramework')
end

def ignore_overriding_contains_swift(installer, framework_target)
    target = installer.aggregate_targets.find{|t| t.name == "Pods-#{framework_target}"}
    raise "failed to find #{framework_target} among: #{installer.aggregate_targets}" unless target
    target.xcconfigs.each_value do |config|
        config.attributes.delete('EMBEDDED_CONTENT_CONTAINS_SWIFT')
    end
end
```

**Comment by allenlinli** [comment] 2016-10-20 06:46
@paulz When I try to install podfile with this script. It shows error:
```[!] Invalid `Podfile` file: [!] Specifying multiple `post_install` hooks is unsupported.```

**Comment by benasher44** [comment] 2016-10-20 08:23
This is fixed in CocoaPods 1.1.0. It properly sets this setting based on the product type. Can people try testing with that version?

**Comment by hfossli** [comment] 2016-10-20 09:02
@benasher44 Maybe I'm missing something, but it isn't working as I would expect on my side

1) Create an xcode project for Swift only

2) Create Podfile.
```
hfossli in ~/Downloads/ASDASD(ruby-2.3.0) λ cat Podfile
platform :ios, '8.0'

use_frameworks!

target 'ASDASD' do
  pod 'KeychainSwift', '~> 6.0.2'
end
```

3) Verify pod version
```
hfossli in ~/Downloads/ASDASD(ruby-2.3.0) λ pod --version
1.1.0
```

4) Install 
```
hfossli in ~/Downloads/ASDASD(ruby-2.3.0) λ pod install
Analyzing dependencies
Downloading dependencies
Installing KeychainSwift (6.0.2)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `ASDASD.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.
```

5) Log to console the xcconfig
```
hfossli in ~/Downloads/ASDASD(ruby-2.3.0) λ cat Pods/Target\ Support\ Files/Pods-ASDASD/Pods-ASDASD.release.xcconfig 
ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES = YES
EMBEDDED_CONTENT_CONTAINS_SWIFT = YES
FRAMEWORK_SEARCH_PATHS = $(inherited) "$PODS_CONFIGURATION_BUILD_DIR/KeychainSwift"
GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
LD_RUNPATH_SEARCH_PATHS = $(inherited) '@executable_path/Frameworks' '@loader_path/Frameworks'
OTHER_CFLAGS = $(inherited) -iquote "$PODS_CONFIGURATION_BUILD_DIR/KeychainSwift/KeychainSwift.framework/Headers"
OTHER_LDFLAGS = $(inherited) -framework "KeychainSwift"
OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
PODS_BUILD_DIR = $BUILD_DIR
PODS_CONFIGURATION_BUILD_DIR = $PODS_BUILD_DIR/$(CONFIGURATION)$(EFFECTIVE_PLATFORM_NAME)
PODS_ROOT = ${SRCROOT}/Pods
```

Here's the result [Example project.zip](https://github.com/CocoaPods/CocoaPods/files/541241/Example.project.zip).

----- 
I would expect `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` to be omitted or be set to `NO`. My expectation may very well be wrong. 

Also when I export the app to archive using under Product > Archive in Xcode I get a pretty big archive with what I would say is a minimum amount of code for any viable app.

<img width="350" alt="skjermbilde 2016-10-20 kl 11 01 11" src="https://cloud.githubusercontent.com/assets/3652587/19553459/a5a38968-96b4-11e6-9eb3-aa4a12dd9662.png">

**Comment by benasher44** [comment] 2016-10-20 09:08
I'm assuming KeychainSwift uses Swift. In that case, it'll be set to yes for the target you're integrating that pod into. Since KeychainSwift is a Swift pod, your target requires Swift and its libraries by proxy.

**Comment by benasher44** [comment] 2016-10-20 09:12
One of the downsides of using Swift pods is that your target that uses them will then have to be distributed with the Swift libraries, which causes the bloat you're seeing.

**Comment by benasher44** [comment] 2016-10-24 14:23
Going to close this, since CocoaPods now properly sets `EMBEDDED_CONTENT_CONTAINS_SWIFT` to YES or leaves it untouched based on the target. It even handles it properly for extensions as well.

**Closed by benasher44** 2016-10-24 14:23 UTC

**Comment by chrisballinger** [comment] 2016-12-08 22:18
@benasher44 I still see this problem with CocoaPods 1.2.0.beta.1 for this project / Podfile: https://github.com/ChatSecure/ChatSecure-iOS/tree/omemo

We have an abstract target and three concrete sub targets. One is an app, one is a framework, and one is tests. We have to manually disable `ALWAYS_EMBED_SWIFT_STANDARD_LIBRARIES` or the App Store upload fails.

**Comment by benasher44** [comment] 2016-12-09 03:12
Hi @chrisballinger! Thanks for letting us know! Would you mind opening up a new ticket with the issue template filled out? It'd go a long way helping us help you. Thanks!
