### ISSUE TITLE
Hi, I am facing an issue when publishing my pod. Not sure exactly what it is.

### ISSUE THREAD

**Issue by danieldahan** [CocoaPods/CocoaPods#4290] opened 2015-09-29 19:02 UTC
-> Installing MK (1.14.0)
 > Git download
 > Git download
     $ /usr/bin/git clone https://github.com/GraphKit/MaterialKit.git
     /private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/MK
     --single-branch --depth 1 --branch 1.14.0
     Cloning into '/private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/MK'...
     Note: checking out '34c4fd851d73ff8bd7a75ff5092aaa6947a405ab'.

     You are in 'detached HEAD' state. You can look around, make experimental
     changes and commit them, and you can discard any commits you make in this
     state without impacting any branches by performing another checkout.

     If you want to create a new branch to retain commits you create, you may
     do so (now or later) by using -b with the checkout command again. Example:

       git checkout -b new_branch_name

  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Pods-MK` iOS 9.0
      - Generating Info.plist file at
      `../../../../../../../private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods-MK/Info.plist`
      - Generating module map file at
      `../../../../../../../private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods-MK/Pods-MK.modulemap`
      - Generating umbrella header at
      `../../../../../../../private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods-MK/Pods-MK-umbrella.h`
    - Installing target `Pods` iOS 9.0
      - Generating Info.plist file at
      `../../../../../../../private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods/Info.plist`
      - Generating module map file at
      `../../../../../../../private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods/Pods.modulemap`
      - Generating umbrella header at
      `../../../../../../../private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/Target
      Support Files/Pods/Pods-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to
  `../../../../../../../private/var/folders/gm/0tmgm2ds4kg2jtd806svl65c0000gn/T/CocoaPods/Lint/Pods/Pods.xcodeproj`
2015-09-29 14:55:54.641 ruby[12180:6094345] [MT] DVTAssertions: ASSERTION FAILURE in /Library/Caches/com.apple.xbs/Sources/IDEFrameworks/IDEFrameworks-8227/IDEFoundation/Initialization/IDEInitialization.m:590
Details:  Assertion failed: _initializationCompletedSuccessfully
Function: BOOL IDEIsInitializedForUserInteraction()
Thread:   <NSThread: 0x7f921b6de430>{number = 1, name = main}
Hints: None
Backtrace:
  0  0x0000000107ceea5c -[DVTAssertionHandler handleFailureInFunction:fileName:lineNumber:assertionSignature:messageFormat:arguments:] (in DVTFoundation)
  1  0x0000000107cee1e9 _DVTAssertionHandler (in DVTFoundation)
  2  0x0000000107cee455 _DVTAssertionFailureHandler (in DVTFoundation)
  3  0x0000000107cee3b7 _DVTAssertionFailureHandler (in DVTFoundation)
  4  0x00000001099cbf5c IDEIsInitializedForUserInteraction (in IDEFoundation)
  5  0x000000010c5cbeb9 +[PBXProject projectWithFile:errorHandler:readOnly:] (in DevToolsCore)
  6  0x000000010c5cda3e +[PBXProject projectWithFile:errorHandler:] (in DevToolsCore)
  7  0x00007fff8f31ff44 ffi_call_unix64 (in libffi.dylib)
Abort trap: 6

**Comment by neonichu** [comment] 2015-09-29 19:16
This is a dupe of #3829 — please make sure you have the right version of Xcodeproj which works with Xcode 7.

**Closed by neonichu** 2015-09-29 19:16 UTC
