### ISSUE TITLE
Pod Install Error: Many subspecs for multiple targets

### ISSUE THREAD

**Issue by uny** [CocoaPods/CocoaPods#5641] opened 2016-07-19 10:30 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
Cannot install.
```
Errno::ENAMETOOLONG - File name too long @ dir_s_mkdir - /Users/XXXXX/TooLongSubspecApp/Pods/Target Support Files/TooLongSubspec-AAAAAAAAAA-BBBBBBBBBB-CCCCCCCCCC-DDDDDDDDDD-EEEEEEEEEE-FFFFFFFFFF-GGGGGGGGGG-HHHHHHHHHH-IIIIIIIIII-JJJJJJJJJJ-KKKKKKKKKK-LLLLLLLLLL-MMMMMMMMMM-NNNNNNNNNN-OOOOOOOOOO-PPPPPPPPPP-QQQQQQQQQQ-RRRRRRRRRR-SSSSSSSSSS-TTTTTTTTTT-UUUUUUUUUU-VVVVVVVVVV-WWWWWWWWWW-XXXXXXXXXX
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer.rb:90:in `mkdir'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer.rb:90:in `mkdir'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer.rb:90:in `create_support_files_dir'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:19:in `block in install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer/target_installer/pod_target_installer.rb:17:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:621:in `block (2 levels) in install_libraries'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:619:in `each'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:619:in `block in install_libraries'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:618:in `install_libraries'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:170:in `block in generate_pods_project'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:167:in `generate_pods_project'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:119:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ d65423fbc8a769daeecb87ac0838f0675167158c
               toolongsubspecspecs - https://github.com/uny/toolongsubspecspecs.git @ 44b65eba8403aa1d0ff3d5abc93ba5b09d37eb5d
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/uny/toolongsubspecspecs.git'
# platform :ios, '9.0'

target 'TooLongSubspecApp' do
  # Comment this line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  pod 'TooLongSubspec/AAAAAAAAAA'
  pod 'TooLongSubspec/BBBBBBBBBB'
  pod 'TooLongSubspec/CCCCCCCCCC'
  pod 'TooLongSubspec/DDDDDDDDDD'
  pod 'TooLongSubspec/EEEEEEEEEE'
  pod 'TooLongSubspec/FFFFFFFFFF'
  pod 'TooLongSubspec/GGGGGGGGGG'
  pod 'TooLongSubspec/HHHHHHHHHH'
  pod 'TooLongSubspec/IIIIIIIIII'
  pod 'TooLongSubspec/JJJJJJJJJJ'
  pod 'TooLongSubspec/KKKKKKKKKK'
  pod 'TooLongSubspec/LLLLLLLLLL'
  pod 'TooLongSubspec/MMMMMMMMMM'
  pod 'TooLongSubspec/NNNNNNNNNN'
  pod 'TooLongSubspec/OOOOOOOOOO'
  pod 'TooLongSubspec/PPPPPPPPPP'
  pod 'TooLongSubspec/QQQQQQQQQQ'
  pod 'TooLongSubspec/RRRRRRRRRR'
  pod 'TooLongSubspec/SSSSSSSSSS'
  pod 'TooLongSubspec/TTTTTTTTTT'
  pod 'TooLongSubspec/UUUUUUUUUU'
  pod 'TooLongSubspec/VVVVVVVVVV'
  pod 'TooLongSubspec/WWWWWWWWWW'
  pod 'TooLongSubspec/XXXXXXXXXX'

  target 'TooLongSubspecAppTests' do
    inherit! :search_paths

    pod 'TooLongSubspec/YYYYYYYYYY'
    pod 'TooLongSubspec/ZZZZZZZZZZ'
  end
end
```

## Project that demonstrates the issue

https://github.com/uny/TooLongSubspecApp

**Comment by neonichu** [comment] 2016-07-19 11:00
This is a duplicate of #5491

**Closed by neonichu** 2016-07-19 11:00 UTC
