### ISSUE TITLE
Private spec does not allow push

### ISSUE THREAD

**Issue by muxi** [CocoaPods/CocoaPods#6449] opened 2017-01-30 19:18 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Create private repo directory: `mkdir ~/my_repo ; cd ~/my_repo`
Make it a git repo: `git init`
Add repo to repo list: `pod repo add myrepo ~/my_repo`
Push podspec into myrepo: `pod repo push myrepo /path/to/my_podspec.podspec`

## What did you expect to happen?
My podspec get pushed in this repo and can be accessed, as suggested by https://guides.cocoapods.org/making/private-cocoapods.html

## What happened instead?
```
Validating spec
Cloning spec repo `-1` from ``
[!] Unable to add a source with url `` named `-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
```

Using `--verbose` flag shows the problem:
```
Validating spec

Cloning spec repo `-1` from ``
  $ /usr/local/git/current/bin/git clone  -1
  error: unknown switch `1'
  usage: git clone [<options>] [--] <repo> [<dir>]
  ...
```
It seems that the url and name of `myrepo` is not getting derived when running the `git clone` command.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1108)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.11.0.390.gc69c2f50cf-goog
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : grpc -  @ fatal: Not a git repository (or any of the parent directories): .git
               grpc-repo - /Users/mxyan/grpc/grpc-repo @ 02e8492aa85157385805f53f3c767125b73b8465
               master - https://github.com/CocoaPods/Specs.git @ 955e4309eb149fbf73381c09c3aecd2786091d6b
               muxi - https://github.com/muxi/grpc.git @ 6ff14349ff1c7c16eff295aab21e9c370eb52af7
               myrepo - /Users/mxyan/my_repo @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

**Comment by muxi** [comment] 2017-02-23 19:23
Could anyone kindly confirm/disconfirm this problem?

**Comment by benasher44** [comment] 2017-02-24 14:51
Based on the commands you ran, it looks like your repo doesn't have a remote. This also lines up with the error message as well.

**Comment by benasher44** [comment] 2017-03-01 15:37
I think there's some clear improvement here. This error message is pretty crappy. We should just tell you that the source you're trying to push to doesn't have a remote setup. This would be a great starter task!

**Comment by robcontreras** [comment] 2017-03-16 04:35
wanted to tackle this, but i can't reproduce it, CocoaPods is explicitly saying the repo was not found

`
pod repo push my_repo my_pod.podspec

Validating spec
 -> my_pod (0.1.0)
    - ERROR | [iOS] unknown: Encountered an unknown error ([!] /usr/bin/git clone https://github.com/robcontreras/my_pod.git /var/folders/g4/khntl_mn6lxf1ztyvq8xd7640000gn/T/d20170315-20256-1b3rzti --template= --single-branch --depth 1 --branch 0.1.0

Cloning into '/var/folders/g4/khntl_mn6lxf1ztyvq8xd7640000gn/T/d20170315-20256-1b3rzti'...
remote: Repository not found.
fatal: repository 'https://github.com/robcontreras/my_pod.git/' not found
) during validation.
`

**Comment by benasher44** [comment] 2017-03-16 14:20
@robcontreras it looks like there is a remote setup there in your repro case. In the description, they're setting up a git repo locally (just `git init` somewhere, then running `pod repo add <local_path_to_place_where_git_init_happened>`), but then they're never setting up a remote for that repo (i.e. via `git remote add origin <url_to_remote>`). Does that make sense?

**Comment by dkhamsing** [comment] 2017-05-08 21:19
having issues trying to reproduce this

```bash
$ pod repo add myrepo my_repo/
Cloning spec repo `myrepo` from `my_repo/`
[!] /usr/bin/git clone my_repo/ myrepo

fatal: repository 'my_repo/' does not exist
```

@benasher44 is this still valid?

```
$ pod --version
1.2.1
```

**Comment by benasher44** [comment] 2017-05-17 16:01
@dkhamsing did you try setting up a folder with a git repo in it called `my_repo` first? I think that might be a prerequisite for reproducing this.

**Comment by dkhamsing** [comment] 2017-05-17 16:28
I tried to follow the instructions

```bash
dkhamsing@Daniels-MBP ~/Desktop (master)> mkdir my_repo
dkhamsing@Daniels-MBP ~/Desktop (master)> cd my_repo/
dkhamsing@Daniels-MBP ~/D/my_repo (master)> git init
Initialized empty Git repository in /Users/dkhamsing/Desktop/my_repo/.git/
dkhamsing@Daniels-MBP ~/D/my_repo (master)> cd ..
dkhamsing@Daniels-MBP ~/Desktop (master)> pod repo add myrepo my_repo/
Cloning spec repo `myrepo` from `my_repo/`
[!] /usr/bin/git clone my_repo/ myrepo

fatal: repository 'my_repo/' does not exist

dkhamsing@Daniels-MBP ~/Desktop (master) [1]> 
```

did I miss something?

**Comment by benasher44** [comment] 2017-05-17 16:35
Hm.  I guess not. It's possible one of the git-related changes in 1.2.1 changed how early this error crops up, which I think would have made the issue obvious early on. I'm going to close this one, and @muxi should reopen it if they can still repro the issue on 1.2.1. Thanks for looking into this @dkhamsing!

**Closed by benasher44** 2017-05-17 16:35 UTC
Labels: d1:easy, s3:detailed, t1:enhancement

**Comment by fanxiaocong** [comment] 2018-03-26 02:34
I have a similar problem. When I rely on other third party libraries in the podspec file and execute 'pod repo push MyPrivateRepo XXX.podspec'， The following error occurred: 
[!] Unable to add a source with url `` named `-1`.
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.

But if do not rely on other third party libraries, It works。What should I do? Thanks!

**Comment by ARIEnergy** [comment] 2022-04-01 01:39
@benasher44  The issue is still existing now

**Comment by Cydie** [comment] 2022-08-30 10:03
> I have a similar problem. When I rely on other third party libraries in the podspec file and execute 'pod repo push MyPrivateRepo XXX.podspec'， The following error occurred: [!] Unable to add a source with url `` named `-1`. You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
> 
> But if do not rely on other third party libraries, It works。What should I do? Thanks!

Exact same issue. If I add any dependency to the podspec, I end up with this
