### ISSUE TITLE
CocoaPods fails to install/update if one or more pods is shared between multiple targets

### ISSUE THREAD

**Issue by ArtSabintsev** [CocoaPods/CocoaPods#5942] opened 2016-09-23 16:24 UTC
Please refer to https://github.com/CocoaPods/CocoaPods/issues/3446 for the debug info.

@jtdavid and I have concluded that running `pod install` or `pod update` on a Podspec that has multiple targets sharing one or more pods throws the following issue:

`Errno::EEXIST - File exists @ dir_s_mkdir - /path/to/pod`

This happens using CocoaPods 1.1.0.rc.2 and the current commit on the master branch.

**Comment by orta** [comment] 2016-09-23 16:33
It looks like this is a dupe of https://github.com/CocoaPods/CocoaPods/issues/5864 which has a of discussion in it, so I'm going to close this in favour of that - thanks for the issue!

**Closed by orta** 2016-09-23 16:33 UTC

**Comment by ArtSabintsev** [comment] 2016-09-23 16:36
No problem - thank you!

**Comment by bendeming** [comment] 2016-10-12 06:49
This can occur if your targets do *not* include Swift.

In my case, I had something like this which had been working under 0.39:

```
def my_pods
  pod 'A' ...
  pod 'B' ...
end

# 'FooStaticLib' is a static library target 
target :FooStaticLib do
  my_pods
end

# 'FooStaticLibTests' is a test bundle that has no test host/host application
target :FooStaticLibTests do
   my_pods
   ...
end
```

which under 1.10.0.rc3 yields `Errno::EEXIST - File exists @ dir_s_mkdir` when doing a `pod install`

A workaround (or perhaps ultimate, correct solution?) is to nest the targets:

target :FooStaticLib do
  my_pods
  target :FooStaticLibTests do
    ...
  end
end
```

**Comment by benasher44** [comment] 2016-10-12 20:35
@bendeming can you file a new issue for 1.1.0.rc.3 so that we can have a closer look?
