### ISSUE TITLE
Cocoapods 1.9.3 brings breaking changes unexpectedly after updating xcodeproj

### ISSUE THREAD

**Issue by maxim-lobanov** [CocoaPods/CocoaPods#10153] opened 2020-10-16 07:28 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
## Context
Hello everyone!
Our team owns image-generation process for Azure DevOps and GitHub Actions Hosted images.
During image-generation of MacOS images, we install cocoapods via gem tool:

`gem install cocoapods` ([Related code](https://github.com/actions/virtual-environments/blob/main/images/macos/provision/core/rubygem.sh#L11))
This command install the latest version of cocoapods (1.9.3) and their dependencies.

## Problem

Recently, we have got a bunch of customers' reports where their builds (all versions of Xcode installed on image including 11.x, 12.0 and etc) started to fail with errors like below:
```
error: double-quoted include "PPRMOCMagnesResult.h" in framework header, expected angle-bracketed instead [-Werror,-Wquoted-include-in-framework-header]
```

Related issue: https://github.com/actions/virtual-environments/issues/1804

## Root cause
We have tried to investigate what can cause it because version of cocoapods was not changed between health and broken images. We have found that version of `xcodeproj` (dependency of cocoapods) was updated from `1.18` to `1.19` recently and `gem install cocoapods`  started to install xcodeproj 1.19 because [cocoapods requires](https://github.com/CocoaPods/CocoaPods/blob/master/cocoapods.gemspec#L40) `>= 1.17.0', '< 2.0` version.

`xcodeproj 1.19` contains breaking change related to `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` parameter that forces it to `YES` and causes issues like that https://github.com/CocoaPods/CocoaPods/issues/9902

## What does it mean for customers
It means that all customers, who install the latest version of cocoapods now, will face with this issue and will have to fix their builds.

I see that this issue has been already fixed in cocoapods 1.10.1-rc.1: https://github.com/CocoaPods/CocoaPods/pull/9905
But actually, all previous versions of cocoapods (including 1.9.3) are broken due to this breaking change.

## Possible workarounds
- Using Cocoapods 1.10.1-rc.1:
```
sudo gem uninstall cocoapods --all
sudo gem install cocoapods -v 1.10.0.rc.1
```
- Revert `xcodeproj` on machine
```
gem uninstall xcodeproj --force
gem install xcodeproj -v 1.18.0
gem install cocoapods
```
- Set `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` to `No` in project settings
- Set  `CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER` via podfile settings:
```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings['CLANG_WARN_QUOTED_INCLUDE_IN_FRAMEWORK_HEADER'] = 'NO'
  end
end
```

## Questions
Currently, we are deploying the new image with this change and we are trying to understand if we should stop deployment and freeze `xcodeproj 1.18.0` for a while on our build agents to avoid impact.
Was this change expected or unintentional?

Looks like this update can break a lot of customers and all of them will have to apply one of fixes above.

## What did you expect to happen?

I think all dependencies should be freezed to avoid such breaking changes

## Project that demonstrates the issue

https://github.com/braintree/braintree_ios

**Comment by maxim-lobanov** [comment] 2020-10-16 07:58
We have decided to freeze xcodeproj 1.18.0 for now until Cocoapods release stable version with fix: https://github.com/actions/virtual-environments/pull/1829

**Comment by igor-makarov** [comment] 2020-10-16 09:28
Hi @maxim-lobanov !

To summarize what you're saying, the latest release of Xcodeproj isn't compatible with the latest (non-beta) release of CocoaPods?

CocoaPods 1.10 final will ship very soon, so waiting might be the best solution.

Side note, why are gems installed as part of the image build? What's the design consideration? 

P.S. I've also edited your comment to correct the gem versions you have mentioned.

**Comment by maxim-lobanov** [comment] 2020-10-16 09:40
@igor-makarov , Yes, that is true.
In my understanding, the problem is that `xcodeproj` brings breaking change without bumping major version.
And all versions of cocoapods started to install it automatically due to condition `'xcodeproj',             '>= 1.17.0', '< 2.0'`. As a result, this breaking change is consumed by all cocoapods versions.
The breaking change is fixed in Cocoapods `1.10.0-rc.1` but previous versions are still affected.

Probably, it should be more strict condition in cocoapods like `>= 1.18.0', '< 1.19.0'`or `xcodeproj` should bump major version for such changes.

We are okay to wait for 1.10 release. In my understanding, after installing Cocoapods `1.10.0` to image, we will be able to remove freezing `xcodeproj 0.18.0` without any impact for customers.
We just would like to clarify whether it is was intentional or not and how we can avoid such issues in future.

P.S. We are pre-installing the latest versions of some popular tools like `cocopoads`, `xcode-install`, `xcpretty`, `fastlane` to save build minutes for customers so they don't need to install those tools in runtime.

**Comment by J5Dev** [comment] 2020-10-16 10:53
Just to add to here, we can confirm that rolling our apps back to use version 1.10.0.rc1 has indeed resolved our issue caused by this, which was that builds within App Centre were failing due to the above... for anyone else who lands here like us.

**Comment by dnkoutso** [comment] 2020-10-16 15:59
Yeap this is true. We are releasing 1.10 today to alleviate this but also concerning shipping 1.9.4 with the same fix.

**Comment by dnkoutso** [comment] 2020-10-16 16:04
The workaround here is to pin to Xcodeproj 1.18 but there are also ways with a `post_install` hook to overcome this.

**Comment by amorde** [comment] 2020-10-16 16:32
New Xcode build settings tend to only introduce warnings, not errors, so this one was a bit unusual. Should be fixed soon, thanks for the detailed report!

**Comment by maxim-lobanov** [comment] 2020-10-16 17:04
Thank you for acknowledging the issue.

@dnkoutso we have pinned `xcodeproj` for now just to unblock image-generation for next week: https://github.com/actions/virtual-environments/pull/1829. After 1.10.0 release, we will be able to remove it. Thanks!

@amorde , Unfortunately, I don't have much experience with Apple development to say why these warnings are treated as errors but I have public project with repro steps if it could help:
- https://github.com/maxim-lobanov/braintree_ios
- Failed build: https://github.com/maxim-lobanov/braintree_ios/runs/1265586307?check_suite_focus=true
- YAML file for this build: https://github.com/maxim-lobanov/braintree_ios/blob/master/.github/workflows/blank.yml

Does it make sense to pin version of `xcodeproj` in all next releases to avoid such breaking changes in future? This issue was pretty tricky to debug and find root cause because cocoapods started to work differently without changing cocoapods version. I guess something like `>= 1.18.0', '< 1.19.0'` would help to avoid it in future

**Comment by igor-makarov** [comment] 2020-10-16 20:02
@maxim-lobanov it looks like the podspec in question is set to treat warnings as errors, so that explains the build failure 😂

As for version pinning, I'm not sure this hard limitation won't introduce compatibility problems with other gems using Xcodeproj.

**Comment by dnkoutso** [comment] 2020-10-21 16:52
Due to my bulk move of issues this was accidentally marked for 1.11.0 release. 1.10.0 final release has shipped and we are still looking to see if if updating 1.9.x stable branch with a fix is worthwhile.

I am going to close for now.

**Closed by dnkoutso** 2020-10-21 16:52 UTC
Labels: s7:workaround available
