### ISSUE TITLE
Pod Spec Lint not finishing 

### ISSUE THREAD

**Issue by AfrozZaheer** [CocoaPods/CocoaPods#7118] opened 2017-10-10 04:57 UTC
# Report

## What did you do?

pod spec lint

## What did you expect to happen?

What I expect is to complete and give me some errors of success 

## What happened instead?

Pod spec lint is running from almost 24 hours and not finishing 

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : JetsRewards - https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git @ 0ec0d34e8ba7a7d69885c2b8e7a4f0cafc722be5
               jetsrewardspod - https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git @ 0ec0d34e8ba7a7d69885c2b8e7a4f0cafc722be5
               lightningkite - https://github.com/Lightningkite/LKPodspec.git @ ee2fee0fdf27732bfa2d4b105c449dfc3698d124
               master - https://github.com/CocoaPods/Specs.git @ 7dd014f4a3f385c9ecb351fb580b8f134dfb94bb
               PrivatePod - https://AfrozNXB@bitbucket.org/AfrozNXB/privatepodtest.git @ 74c9285203952bba4b9cf8304a5cc1f6012919aa
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment] 2017-10-10 04:58
Without a sample project we cannot reproduce. What pod? Paste the podspec? Run `pod spec lint --verbose` to see exactly where it hangs.  My gut tells me it hangs cloning the master repo.

This does not appear to be a CocoaPods library issue. Closing.

**Closed by dnkoutso** 2017-10-10 04:58 UTC

**Comment by AfrozZaheer** [comment] 2017-10-10 05:11
Pod::Spec.new do |s|


  s.name         = "JetsRewards"
  s.version      = "0.1.0"
  s.summary      = "JetsRewards POD to integrate in jets app"

  s.description  = <<-DESC
	POD to integrate jet reward to integrate to any jets app blah blah blah blah
    DESC

  s.homepage     = "https://bitbucket.org/AfrozMuhammad/jetsrewardspod/overview?init=true"


  s.license      = { :type => 'MIT', :file => 'LICENSE' }


  s.author       = { "AfrozZ" => "afrozezaheer@gmail.com" }

  s.source       = { :git => "https://AfrozMuhammad@bitbucket.org/AfrozMuhammad/jetsrewardspod.git" }

  s.platform     = :ios, "9.0"


 
  s.source_files = 'Pod/**/*.{swift,xcassets,h,m}'
  s.resource_bundles = {
     'JetsRewardsElements' => ['Pod/**/*.{storyboard,xib,xcassets,otf}']
  }

  s.dependency  "Alamofire"
  s.dependency  "FAParser"
  s.dependency  "Shimmer"
  s.dependency  "JTProgressHUD"
  s.dependency  "PagingView"
  s.dependency  "Hero"
  s.dependency  "SDWebImage"
  s.dependency  "IQKeyboardManagerSwift"
  s.dependency  "FormTextField"
  s.dependency  "CryptoSwift"


end

This is my pod spec

**Comment by AfrozZaheer** [comment] 2017-10-10 05:11
and it stuck at 

xcodebuild clean build -workspace /var/folders/gy/cbwttyb17f1gsbvkgl623k5m0000gp/T/CocoaPods-Lint-20171010-1614-x2n1xd-JetsRewards/App.xcworkspace -scheme App -configuration Release CODE_SIGN_IDENTITY=- -sdk iphonesimulator -destination id=B3531727-9C0B-40D3-87A1-1EA68962F99E

**Comment by dnkoutso** [comment] 2017-10-10 05:37
`pod spec lint --verbose --no-clean` open the generated .xcodeproj and inspect.
