### ISSUE TITLE
'Invalid Swift Support' email from iTunes when submitting with Xcode 7 GM & Cocoapods

### ISSUE THREAD

**Issue by earltedly** [CocoaPods/CocoaPods#4188] opened 2015-09-16 10:54 UTC
## Problem

Since building with Xcode 7 GM, I'm getting the following email back from Apple which fails submission:

> **Invalid Swift Support**
> 
> The files libswiftCoreLocation.dylib, libswiftCoreMedia.dylib, libswiftCoreData.dylib, > libswiftAVFoundation.dylib don’t match
> 
> /Payload/App.app/Frameworks/libswiftCoreLocation.dylib, /Payload/App.app/Frameworks/libswiftCoreMedia.dylib, /Payload/App.app/Frameworks/libswiftCoreData.dylib, /Payload/App.app/Frameworks/libswiftAVFoundation.dylib
> 
> Make sure the files are correct (?), rebuild your app, and resubmit it.
> 
> **Don’t apply post-processing to**
> 
> /Payload/App.app/Frameworks/libswiftCoreLocation.dylib, /Payload/App.app/Frameworks/libswiftCoreMedia.dylib, /Payload/App.app/Frameworks/libswiftCoreData.dylib, /Payload/App.app/Frameworks/libswiftAVFoundation.dylib.

## Workaround
There's a workaround on [Stackoverflow](http://stackoverflow.com/questions/32526526/invalid-swift-support-files-don-t-match) which seems to work:

1. Archive your app with new build number :(
2. Find the archive (.xcarchive file) in Finder from Organizer “Show in Finder”
3. Open the package and find directories like `Products/Applications/YourApp.ipa/Frameworks/` and `SwiftSupport/iphoneos/`
4. Copy all `libswiftXxx.dylib` files from `SwiftSupport/iphoneos/` into `Products/Applications/YourApp.ipa/Frameworks/` and overwrite
5. Now, Upload to App Store from Organiser

## Cocoapods relevance
I had a look around in `Pods-frameworks.sh` and found a section commented as:

> \# Embed linked Swift runtime libraries

Commenting the block of code which copies these libraries across (and code signs them) seems to have fixed my submission woes. I've not dived in deeper yet to see if it's just the copying of them which causes the issues or if it's the code-signing. I'm getting a bit out of my depth there.

**Comment by falsecz** [comment] 2015-09-16 12:24
Stackoverflow workaround works for me
Xcode 7 GM, CocoaPods 0.39.0.beta.4

**Comment by earltedly** [comment] 2015-09-16 14:14
Just edited my original issue to make it clear where I think Cocoapods might be aggravating things.

**Comment by itspradhan** [comment] 2015-09-18 05:34
Does CocoaPods 0.39.0.beta.4 fix this issue or we need to follow the workaround ?

**Comment by earltedly** [comment] 2015-09-18 06:02
It doesn't fix it that I'm aware of.

**Comment by itspradhan** [comment] 2015-09-18 07:07
I really hope cocoapods would fix this issue soon.

**Comment by orkenstein** [comment] 2015-09-18 09:06
Really annoying. Please fix!

**Comment by segiddins** [comment] 2015-09-18 11:57
Piling onto the issue won't get it fixed any faster. At the moment, most of the team is very busy dealing with different pieces of travel, so the fastest way to get a fix landed would be to submit a PR.

**Comment by djtarazona** [comment] 2015-09-18 21:29
> Commenting the block of code which copies these libraries across (and code signs them) seems to have fixed my submission woes. I've not dived in deeper yet to see if it's just the copying of them which causes the issues or if it's the code-signing. I'm getting a bit out of my depth there.

@earltedly Commenting out those lines solved the issue for you? How are you building your app? Just archiving via Xcode? Or using something like [`gym`](https://github.com/fastlane/gym)?  If these lines are commented out... wouldn't that mean necessary Swift files are left out?

**Comment by chrisballinger** [comment] 2015-09-18 21:56
I am also experiencing this problem and have only tried the StackOverflow workaround, but it's good to know there might be a root cause from the CocoaPods script.

**Comment by djtarazona** [comment] 2015-09-20 04:00
As @earltedly suggested, commenting out the following lines in `Pods-frameworks.sh` solved all issues for me!  Builds to the simulator from Xcode work, archiving from Xcode works, and builds with [`gym`](https://github.com/fastlane/gym) work.

```
  # Embed linked Swift runtime libraries
  local basename
  basename="$(basename "$1" | sed -E s/\\..+// && exit ${PIPESTATUS[0]})"
  local swift_runtime_libs
  swift_runtime_libs=$(xcrun otool -LX "${CONFIGURATION_BUILD_DIR}/${FRAMEWORKS_FOLDER_PATH}/${basename}.framework/${basename}" | grep --color=never @rpath/libswift | sed -E s/@rpath\\/\(.+dylib\).*/\\1/g | uniq -u  && exit ${PIPESTATUS[0]})
  for lib in $swift_runtime_libs; do
    echo "rsync -auv \"${SWIFT_STDLIB_PATH}/${lib}\" \"${destination}\""
    rsync -auv "${SWIFT_STDLIB_PATH}/${lib}" "${destination}"
    code_sign_if_enabled "${destination}/${lib}"
  done
```

I feel like the fix isn't this simple tho.  Is Xcode 7 taking care of copying the appropriate Swift runtime libraries now?

@segiddins I'll create a pull request with this solution then.

**Comment by earltedly** [comment] 2015-09-21 08:59
> I feel like the fix isn't this simple tho. Is Xcode 7 taking care of copying the appropriate Swift runtime libraries now?

@djtarazona I think a possible edge-case would be a scenario where you have a purely Objective-C project which makes use of cocoa pods containing Swift frameworks. I believe there's a build setting which tells Xcode about this `EMBEDDED_CONTENT_CONTAINS_SWIFT`.

**Comment by orkenstein** [comment] 2015-09-21 09:15
@earltedly, my project is 100% swift2 project.

**Comment by dmiotti** [comment] 2015-09-22 13:54
Same here :)

**Comment by orta** [comment] 2015-09-22 13:55
have you tried using this branch? https://github.com/CocoaPods/CocoaPods/pull/4221

**Comment by dmiotti** [comment] 2015-09-22 14:14
This branch did the trick thanks

**Comment by hatemalimam** [comment] 2015-09-22 14:33
The workaround works, but it's annoying to do each time :/

**Comment by ishortman** [comment] 2015-09-22 17:16
FYI...updated to 0.39.0.beta.4 and still the same issue invalid swift support when I try to submit to the app store.

**Comment by hatemalimam** [comment] 2015-09-22 19:58
When can we test this ? next release ?

**Comment by neonichu** [comment] 2015-09-22 20:04
I don't believe we need any more info on this for now — you can use the branch from #4221 as a workaround, see <https://guides.cocoapods.org/using/unreleased-features> on more info how to do it.

**Closed** 2015-09-27 15:42 UTC
Labels: ★
