### ISSUE TITLE
`pod spec lint` fails because it can't find a simulator.

### ISSUE THREAD

**Issue by atreat** [CocoaPods/CocoaPods#8163] opened 2018-10-05 16:03 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
git@github.com:Alamofire/Alamofire.git
cd Alamofire
pod spec lint
```

## What did you expect to happen?

I expect validation to succeed

## What happened instead?

```
 -> Alamofire (4.7.3)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

Analyzed 1 podspec.
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G2208)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : jute - git@github.com:modolabs/jute.git @ 6b6ff97fe21586098fb3bb59d107a710fd10d890
               master - https://github.com/CocoaPods/Specs.git @ 7cba4f2f2fdee44d5532c613b2e049609b3a010c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/Alamofire/Alamofire

I can't push my private repo because of this issue, realized I also couldn't lint Alamofire.
Read in some other issues that may be related to output the simctl
```
$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone 8 (com.apple.CoreSimulator.SimDeviceType.iPhone-8)
iPhone 8 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPhone X (com.apple.CoreSimulator.SimDeviceType.iPhone-X)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
iPad (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-)
Apple TV (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple TV 4K (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K)
Apple TV 4K (at 1080p) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
Apple Watch Series 3 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm)
Apple Watch Series 3 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm)
== Runtimes ==
iOS 11.4 (11.4 - 15F79) - com.apple.CoreSimulator.SimRuntime.iOS-11-4
tvOS 11.4 (11.4 - 15L576) - com.apple.CoreSimulator.SimRuntime.tvOS-11-4
watchOS 4.3 (4.3 - 15T212) - com.apple.CoreSimulator.SimRuntime.watchOS-4-3
== Devices ==
-- iOS 11.4 --
    iPhone X (8806A212-8BB5-4562-AF3F-B91E4BE8E97D) (Shutdown)
-- tvOS 11.4 --
-- watchOS 4.3 --
    Apple Watch - 38mm (585EEB1B-A2C0-4620-AE86-EABF9968FC3A) (Shutdown)
    Apple Watch - 42mm (3621379B-567F-4AF4-9E75-796AADBFD1C2) (Shutdown)
== Device Pairs ==
```

**Comment by dnkoutso** [comment] 2018-10-05 16:18
This seems a configuration issue on your end. I just tried the same on the same repo and it successfully built.

It also appears you are on Xcode 9.4.1 from the report. If you are on Xcode 10.1 then this fix was merged yesterday https://github.com/CocoaPods/fourflusher/pull/11.

I am going to preemptively close this one and I *will* re-open it if we find out its a CocoaPods library issue instead.

```
Analyzed 1 podspec.

Alamofire.podspec passed validation.
```

**Closed by dnkoutso** 2018-10-05 16:18 UTC

**Comment by atreat** [comment] 2018-10-05 16:53
When I switch to the Xcode Beta I get similar results...

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin17]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.13.6 (17G2208)
       Xcode : 10.1 (10O35n)
         Git : git version 2.18.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : jute - git@github.com:modolabs/jute.git @ 6b6ff97fe21586098fb3bb59d107a710fd10d890
               master - https://github.com/CocoaPods/Specs.git @ 7cba4f2f2fdee44d5532c613b2e049609b3a010c
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```


```
$ xcrun simctl list
== Device Types ==
iPhone 4s (com.apple.CoreSimulator.SimDeviceType.iPhone-4s)
iPhone 5 (com.apple.CoreSimulator.SimDeviceType.iPhone-5)
iPhone 5s (com.apple.CoreSimulator.SimDeviceType.iPhone-5s)
iPhone 6 (com.apple.CoreSimulator.SimDeviceType.iPhone-6)
iPhone 6 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6-Plus)
iPhone 6s (com.apple.CoreSimulator.SimDeviceType.iPhone-6s)
iPhone 6s Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-6s-Plus)
iPhone 7 (com.apple.CoreSimulator.SimDeviceType.iPhone-7)
iPhone 7 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-7-Plus)
iPhone 8 (com.apple.CoreSimulator.SimDeviceType.iPhone-8)
iPhone 8 Plus (com.apple.CoreSimulator.SimDeviceType.iPhone-8-Plus)
iPhone SE (com.apple.CoreSimulator.SimDeviceType.iPhone-SE)
iPhone X (com.apple.CoreSimulator.SimDeviceType.iPhone-X)
iPhone XR (com.apple.CoreSimulator.SimDeviceType.iPhone-XR)
iPhone XS (com.apple.CoreSimulator.SimDeviceType.iPhone-XS)
iPhone XS Max (com.apple.CoreSimulator.SimDeviceType.iPhone-XS-Max)
iPad 2 (com.apple.CoreSimulator.SimDeviceType.iPad-2)
iPad Retina (com.apple.CoreSimulator.SimDeviceType.iPad-Retina)
iPad Air (com.apple.CoreSimulator.SimDeviceType.iPad-Air)
iPad Air 2 (com.apple.CoreSimulator.SimDeviceType.iPad-Air-2)
iPad (5th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--5th-generation-)
iPad Pro (9.7-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--9-7-inch-)
iPad Pro (12.9-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro)
iPad Pro (12.9-inch) (2nd generation) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--12-9-inch---2nd-generation-)
iPad Pro (10.5-inch) (com.apple.CoreSimulator.SimDeviceType.iPad-Pro--10-5-inch-)
iPad (6th generation) (com.apple.CoreSimulator.SimDeviceType.iPad--6th-generation-)
Apple TV (com.apple.CoreSimulator.SimDeviceType.Apple-TV-1080p)
Apple TV 4K (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-4K)
Apple TV 4K (at 1080p) (com.apple.CoreSimulator.SimDeviceType.Apple-TV-4K-1080p)
Apple Watch - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-38mm)
Apple Watch - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-42mm)
Apple Watch Series 2 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-38mm)
Apple Watch Series 2 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-2-42mm)
Apple Watch Series 3 - 38mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-38mm)
Apple Watch Series 3 - 42mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-3-42mm)
Apple Watch Series 4 - 40mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-40mm)
Apple Watch Series 4 - 44mm (com.apple.CoreSimulator.SimDeviceType.Apple-Watch-Series-4-44mm)
== Runtimes ==
iOS 12.1 (12.1 - 16B5068g) - com.apple.CoreSimulator.SimRuntime.iOS-12-1
tvOS 12.1 (12.1 - 16J5584c) - com.apple.CoreSimulator.SimRuntime.tvOS-12-1
watchOS 5.1 (5.1 - 16R5568d) - com.apple.CoreSimulator.SimRuntime.watchOS-5-1
== Devices ==
-- iOS 12.1 --
    iPhone 8 (62D67846-2DB6-4530-9A27-C7CFDA87D6FD) (Shutdown)
    iPhone X (C9C4C06E-D0BA-424F-838E-F0FF5C7E249C) (Shutdown)
-- tvOS 12.1 --
-- watchOS 5.1 --
== Device Pairs ==
```

```
$ pod spec lint

 -> Alamofire (4.7.3)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
```

**Comment by dnkoutso** [comment] 2018-10-05 16:55
Sorry again, this continues to appear a configuration issue with Xcode, and iOS simulator on your machine.

The CocoaPods build is green that builds a bunch of projects and I was also able to lint the exact repo you mentioned successfully.

It is best to ask StackOverflow under `cocoapods` tag.

**Comment by SlaunchaMan** [comment] 2018-10-05 19:52
That looks like what I was experiencing that led to the aforementioned `fourflusher` PR. @atreat, if you’re using Bundler, try adding this line to get that version:

```Ruby
gem "fourflusher", :git => 'https://github.com/CocoaPods/fourflusher', :branch => 'master'
```

That fixed it for me.

**Comment by dnkoutso** [comment] 2018-10-05 20:01
@SlaunchaMan the initial report though was using Xcode 9 not Xcode 10.1 beta

**Comment by dnkoutso** [comment] 2018-10-05 20:10
maybe I am wrong though and its not tied to that?

**Comment by atreat** [comment] 2018-10-05 21:12
@SlaunchaMan thanks for the tip, thats exactly what I ended up doing.

@dnkoutso I didn't see any difference between Xcode versions, looks like it was just the fourflusher issue.

**Comment by dnkoutso** [comment] 2018-10-05 21:57
Thanks for confirming. Apologies for just saying it was your wrong configuration. Seems like the issue is fixed and others can apply the same workaround.

**Comment by SlaunchaMan** [comment] 2018-10-06 20:03
@dnkoutso The confusing thing is that even if you’re using a different Xcode version, if you have 10.1 _installed_, it’ll use the new format.

**Comment by crsantos** [comment] 2018-10-09 14:27
Can we assume that `fourflusher` will be bumped on cocoapods `1.6.0`?

**Comment by dnkoutso** [comment] 2018-10-09 15:22
Yes but you can also point to `fourflusher` latest as described above :)

**Comment by seanrucker** [comment] 2018-10-15 22:16
I'm having the same issue and don't understand the workaround. Anyone able to provide guidance?

**Comment by dnkoutso** [comment] 2018-10-15 22:17
```
gem "fourflusher", :git => 'https://github.com/CocoaPods/fourflusher', :branch => 'master'
```

Using https://bundler.io/v1.12/git.html

**Comment by Coeur** [comment] 2018-10-19 08:52
Another workaround is available at https://stackoverflow.com/questions/52742003/cocoapods-cant-find-simulators-pod-repo-push-fails for those not using blunder.

**Comment by Coeur** [comment] 2018-10-19 10:15
@crsantos well, you gave me a -1, but at least I made a pull request for that: #8203

**Comment by atreat** [comment] 2018-10-19 16:40
I now get this when trying the Gemfile workaround...
```
Fetching https://github.com/CocoaPods/fourflusher
Fetching gem metadata from https://rubygems.org/...........
Resolving dependencies...
Bundler could not find compatible versions for gem "fourflusher":
  In Gemfile:
    fourflusher

    cocoapods (~> 1.5.0) was resolved to 1.5.3, which depends on
      fourflusher (~> 2.0.1)

Could not find gem 'fourflusher (~> 2.0.1)', which is required by gem 'cocoapods (~> 1.5.0)', in any of the relevant sources:
  https://github.com/CocoaPods/fourflusher (at master@bf4c2ff)
```

Gemfile:
```ruby
source 'https://rubygems.org'

gem 'cocoapods', '~> 1.5.0'
gem "fourflusher", git: 'https://github.com/CocoaPods/fourflusher', branch: 'master'
```

**Comment by atreat** [comment] 2018-10-19 17:13
Following suit with cocoapods results in a similar output:
```
Fetching https://github.com/CocoaPods/cocoapods
Fetching https://github.com/CocoaPods/fourflusher
Fetching gem metadata from https://rubygems.org/.........
Resolving dependencies...
Bundler could not find compatible versions for gem "fourflusher":
  In Gemfile:
    fourflusher

    cocoapods was resolved to 1.6.0.beta.2, which depends on
      fourflusher (~> 2.0.1)

Could not find gem 'fourflusher (~> 2.0.1)', which is required by gem 'cocoapods', in any of the relevant sources:
  https://github.com/CocoaPods/fourflusher (at master@bf4c2ff)
```

Gemfile:
```ruby
source 'https://rubygems.org'

gem 'cocoapods',  git: 'https://github.com/CocoaPods/cocoapods', branch: 'master'
gem "fourflusher", git: 'https://github.com/CocoaPods/fourflusher', branch: 'master'
```

**Comment by atreat** [comment] 2018-10-19 18:15
In order to get a release out I had to forego the spec linting and manually add the spec file to my private spec repo. Then also push the spec repo manually.

I don't recommend doing this at all. Just leaving a note as to what I had to do.

**Comment by ralfebert** [comment] 2018-10-20 20:05
Until the dependency issue is fixed, using the old fourflusher commit before the 2.1 release does the trick as workaround:

```
source 'http://rubygems.org'

gem "cocoapods", '1.6.0.beta.2'
gem "fourflusher", :git => 'https://github.com/CocoaPods/fourflusher', :ref => '5639cc4'
```

**Comment by Coeur** [comment] 2018-10-20 20:49
@ralfebert I bet the fix will be merged for 1.6.0.beta.3.

**Comment by cerezo074** [comment] 2018-10-23 15:22
@ralfebert I've tried your gemfile and it doesn't worked I still get the same error, could you explain me with more details what you did it?

**Comment by ElektrojungeMS** [comment] 2018-11-01 21:10
We were bitten by this when our CI added Xcode 10 as an option. We solved it by manually updating `fourflusher` to version 2.1.0 and uninstalling version 2.0.1 before running `pod spec lib`:
`gem uninstall fourflusher --force && gem install fourflusher`

What's really interesting is that the error didn't even mention fourflusher:
```2018-10-31T20:55:31.0794960Z  -> AppCenter (1.10.1) - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation. [!] The `AppCenter.podspec` specification does not validate.```

What's curious is that I could not reproduce this locally. Maybe because I have "old" simulators that were created with Xcode 9? 🤔

**Comment by jdrukman** [comment] 2018-11-06 22:42
Can someone explain in really basic terms what I have to do to work around this issue? I have had no luck with uninstalling/reinstalling different versions of fourflusher.

**Comment by hitendradeveloper** [comment] 2019-03-20 10:33
**do below steps it solved my issue For XCode 10.2 beta 4**

> 1. sudo gem uninstall fourflusher
> 2. sudo gem install fourflusher
> 3. sudo gem update cocoapods

**Comment by Coeur** [comment] 2019-03-20 12:50
@hitendradeveloper simply updating cocoapods to 1.6.0 or newer should be enough for Xcode 10.2 compatibility.

**Comment by mmdock** [comment] 2019-04-26 19:26
@Coeur trying to understand something that should be basic: 

```
$ sudo gem uninstall cocoapods
Password:
Successfully uninstalled cocoapods-1.5.3
Remove executables:
	pod, sandbox-pod

in addition to the gem? [Yn]  y
Removing pod
Removing sandbox-pod
Successfully uninstalled cocoapods-1.5.3
$ sudo gem install cocoapods -v 1.6.1
Fetching cocoapods-1.6.1.gem
Successfully installed cocoapods-1.6.1
Parsing documentation for cocoapods-1.6.1
Installing ri documentation for cocoapods-1.6.1
Done installing documentation for cocoapods after 1 seconds
1 gem installed
$ pod --version
1.5.3
$ sudo gem list cocoapods

*** LOCAL GEMS ***

cocoapods (1.6.1)
cocoapods-core (1.6.1, 1.5.3)
cocoapods-deintegrate (1.0.4, 1.0.2)
cocoapods-downloader (1.2.2)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.3.1)
cocoapods-try (1.1.0)
$ gem uninstall cocoapods-core -v 1.5.3
Successfully uninstalled cocoapods-core-1.5.3
$ pod spec lint LocalizedCountryList.podspec
 -> LocalizedCountryList (2.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: com.apple.coresimulator.simruntime.ios-10-3, com.apple.coresimulator.simruntime.ios-11-0, com.apple.coresimulator.simruntime.ios-11-4, com.apple.coresimulator.simruntime.ios-12-2, com.apple.coresimulator.simruntime.ios-9-3, com.apple.coresimulator.simruntime.tvos-12-2, com.apple.coresimulator.simruntime.watchos-5-2). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error.
$ pod --version
1.5.3
```

I have uninstalled and reinstalled cocoapods multiple times and it just stays claiming it is 1.5.3.   I am just trying to update to 1.6.1 so I could pass this simulator spec lint error.  What on earth could i possibly have configured here for it to do this and never update / use correct version?

**Comment by Coeur** [comment] 2019-04-27 00:59
@mmdock that's really off-topic for this issue. You should have opened an issue at https://github.com/rubygems/rubygems/issues instead.

**Comment by mmdock** [comment] 2019-04-27 04:00
@Coeur sorta off topic yeah.  However, it was what i needed to do to get my `spec lint` working so might be relevant to someone.   if one person could encounter this issue, so could others.  Considering that this looks to be a relatively silent issue related to rubygems updating cocoapods correctly....

**Comment by MaximBazarov** [comment] 2019-06-05 05:30
Same error, Xcode 10.1, Xcode 11 beta are installed.
```
$ pod lib lint

 -> Unicore (2.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.) during validation.

[!] Unicore did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.
```

Simulators window contains all iOS simulators needed

**Comment by Adrift001** [comment] 2019-06-05 06:49
[iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.

**Comment by Adrift001** [comment] 2019-06-05 06:50
[iOS] unknown: Encountered an unknown error (Could not find a `ios` simulator (valid values: ). Ensure that Xcode -> Window -> Devices has at least one `ios` simulator listed or otherwise add one.

**Comment by Coeur** [comment] 2019-06-05 08:00
@MaximBazarov @Adrift001 please open a separate issue for Xcode 11 beta.
Here it was for Xcode 10.1 and it got fixed long ago by https://github.com/CocoaPods/fourflusher/pull/11.

**Comment by dimsky** [comment] 2019-06-05 08:51
@Coeur 

Edit fourflusher  find.rb

`if device['availability'] == '(available)' || device['isAvailable'] == true || device['isAvailable'] == 'YES' || device['isAvailable'] == 'true'
            Simulator.new(device, os_name, os_version)
          end`

**Comment by Coeur** [comment] 2019-06-05 09:32
@dimsky there is already a Pull Request for that. Let's continue in the other thread, #8875.

**Comment by RicardoKoch** [comment] 2019-06-05 16:02
Confirming @dimsky code fixed the issue introduced in Xcode 11 Beta.

**Comment by jogendra** [comment] 2019-06-13 05:00
For my **Xcode 11 Beta** `sudo gem update` solved the issue!

**Comment by karosLi** [comment] 2019-07-02 12:40
On Xcode 10.2,  `oses.include?(os)` will  fail.

```
unless oses.include?(os)
        fail "Could not find a `#{os}` simulator (valid values: #{oses.join(', ')}). Ensure that "\
          "Xcode -> Window -> Devices has at least one `#{os}` simulator listed or otherwise add one."
      end
```

 And oses will print as below.
```
com.apple.coresimulator.simruntime.ios-10-3
com.apple.coresimulator.simruntime.ios-11-4
com.apple.coresimulator.simruntime.ios-8-4
```

Should replace `oses.include?(os)` to `oses.to_s.include?(os.to_s)`. It works for me.

**Comment by Coeur** [comment] 2019-07-02 14:43
@karosLi it was already mentioned above, where we linked 27 days ago to #8875, itself linking to #8878, itself released with CocoaPods 1.7.2, 19 days ago. So a simple pod update will solve it.

**Comment by dnkoutso** [comment] 2019-07-02 14:45
`gem update fourflusher` also separate should do it.

**Comment by karosLi** [comment] 2019-07-03 05:00
> @karosLi it was already mentioned above, where we linked 27 days ago to #8875, itself linking to #8878, itself released with CocoaPods 1.7.2, 19 days ago. So a simple `gem update` will solve it. The character L from Death Note would have find this out already. ;)
> 
> And note that it's spelled `Xcode`, not `XCode`.

hahahaha, you are a very humorous and careful man. I like you. 

Currently as some reason, we have to keep using CocoaPods 1.5.3. So based on this background, we can not upgrade to 1.7.2. For us to resolve this issue on CocoaPods 1.5.3, the best way is to use latest find.rb file.

**Comment by karosLi** [comment] 2019-07-03 05:02
> `gem update fourflusher` also separate should do it.

Yes, i think so.

**Comment by achirkof** [comment] 2019-12-06 16:30
For those who have to use old version of Cocoapods and new version of Xcode, just change your local file `~/.gem/ruby/2.6.0/gems/fourflusher-2.0.1/lib/fourflusher/find.rb` with `find.rb` from latest version of `fourflusher` https://github.com/CocoaPods/fourflusher.

We have to use `Xcode 11.3`, `Cocoapods 1.5.3` and `fourflusher-2.0.1` and `pod spec lint` works correctly after this manipulation.
