### ISSUE TITLE
pods are always installed for iOS 8 deployment target instead of iOS 9

### ISSUE THREAD

**Issue by Coeur** [CocoaPods/CocoaPods#7314] opened 2018-01-08 08:06 UTC
* [🌈] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Create a new Xcode 9.2 project "example" for iOS Swift
2. Change deployment target to iOS 9.0
3. Use a Podfile with:

```
platform :ios, '9.0'
use_frameworks!

abstract_target 'default_pods' do
    pod 'AFNetworking', '~> 3'
    target 'example'
end
```

4. Run `pod install` or `pod update`

## What did you expect to happen?

AFNetworking is installed with a Deployment Target of iOS 9.0.

## What happened instead?

AFNetworking is installed with a Deployment Target of iOS 8.0, which causes noticeable warnings like _/Users/coeur/example/Pods/AFNetworking/AFNetworking/AFURLSessionManager.m:163:30: 'setResumingHandler:' is only available on iOS 9.0 or newer_

Even if I manually change the Pods project Deployment Target to iOS 9.0, a simple `pod update` will reset it to iOS 8.0.

## CocoaPods Environment

* CocoaPods 1.4.0.rc.1 (also reproduced with CocoaPods 1.3.1)
* Xcode 9.2 & High Sierra

## Project that demonstrates the issue

https://github.com/Coeur/CocoaPods7314

**Comment by Coeur** [comment] 2018-01-08 08:21
I found the following workaround, adding a post_install hook:

```
platform :ios, '9.0'
use_frameworks!

abstract_target 'default_pods' do
    pod 'AFNetworking', '~> 3'
    target 'example'
end

post_install do |pi|
    pi.pods_project.targets.each do |t|
        t.build_configurations.each do |config|
            config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
        end
    end
end
```

**Comment by dnkoutso** [comment] 2018-01-08 16:12
Can you please provide a sample project and use the template given to you when you file a new issue?

**Comment by Coeur** [comment] 2018-01-09 02:55
@dnkoutso Done, with a screenshot.

**Comment by dnkoutso** [comment] 2018-01-09 06:25
@Coeur still dont think its a CocoaPods bug. The podspec of AFNetworking says deployment target to 7.0 but I think because you are using Xcode 9.2 which does not contain iOS 7.0 it defaults to the next available version. 

https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/a/7/5/AFNetworking/3.1.0/AFNetworking.podspec.json#L21

Podspecs can define their own deployment target which gets set by the CocoaPods library.

I do not see any particular issue with CocoaPods library here. Will close this one but please reply here if you feel strongly there is an issue here...

**Comment by dnkoutso** [comment] 2018-01-09 06:26
Yes, Xcode 9 drops iOS 7.0 support so that's why you get iOS 8.0 instead.

**Comment by Coeur** [comment] 2018-01-09 07:30
@dnkoutso , you mean that in a Podspec, I can only forcibly define a Deployment Target, I can't simply define the minimal supported Deployment Target?

When I write a Podspec, I use **platforms.ios** to define what is _at least_ required to build, not to define what _must_ be built.

In all case, no matter the Podspec, it is an integration bug from CocoaPods to build for iOS 8+ when we want an iOS 9+ project.

**Comment by Jinxiansen** [comment] 2018-01-11 10:18
@dnkoutso @Coeur 
How to specify two different platforms in a pod,
I have two target, respectively, support for iOS 8 and iOS 9, how to distinguish?

**Comment by dnkoutso** [comment] 2018-01-11 16:21
I do not think this is supported currently.

**Comment by Coeur** [comment] 2018-01-12 04:17
@Jinxiansen , it doesn't even work for one single platform. But if one day there is support for multi platforms, then the documentation will tell you. One suggestion could be:

```
abstract_target 'default_pods' do
    target 'One' do
        platform :ios, '8.0'
    end
    target 'Two' do
        platform :ios, '9.0'
    end
end

```

**Comment by Coeur** [comment] 2018-01-12 04:25
@dnkoutso, I still wish to re-open the issue.

**Comment by Jinxiansen** [comment] 2018-01-12 06:04
@Coeur  I tried the above two methods, but failed to solve my problem .😰

**Comment by Coeur** [comment] 2018-04-11 11:19
@Jinxiansen don't forget you have to do `pod install` (or `pod deintegrate && pod install`) to get the post_install to execute at least once. It will not work with only `pod update`.

**Comment by Whirlwind** [comment] 2018-05-30 06:14
I think the deployment target version should be equal to the user target version.

If the pod target's deployment version is equal to iOS 9 which define by user target, the dependency will use their new api if they check the deploy version:

```
#if (defined(__IPHONE_OS_VERSION_MIN_REQUIRED) && __IPHONE_OS_VERSION_MIN_REQUIRED >= 80000) || (defined(__MAC_OS_X_VERSION_MIN_REQUIRED) && __MAC_OS_X_VERSION_MIN_REQUIRED >= 1100)
            configuration = [NSURLSessionConfiguration backgroundSessionConfigurationWithIdentifier:configurationIdentifier];
#else
            configuration = [NSURLSessionConfiguration backgroundSessionConfiguration:configurationIdentifier];
#endif
```
The code from the `AFNetworking`. In the podspec, there is a `platforms":{"ios":"7.0","osx":"10.9","tvos":"9.0"}`. So the pod target is deploy to iOS 7.0, and the macro will always  be false! `AFNetworking` will always use the old api.

**Comment by Coeur** [comment] 2018-05-30 06:42
@Whirlwind as I wrote on Jan 12, I wanted to keep the issue opened, but @dnkoutso doesn't seem to want it.

**Comment by lolgear** [comment] 2018-05-31 09:53
@dnkoutso 

So, I have UICKeychainStore in Pods.xcodeproj.

Pods.xcodeproj has deployments targets:

Pods (Project) -> 9.0
UICKeychainStore -> 8.0

My App deployment target -> 9.3

I would like to keep them in sync in case of aesthetics.

@Coeur 
If you can't reopen issue and it have not solved yet, it is time to make open-radar for CocoaPods.

**Comment by ayushgoel** [comment] 2018-06-21 05:28
+1

I was hoping the deployment target would be defined according to the [platform](https://guides.cocoapods.org/syntax/podfile.html#platform) specified.

`platform :ios, '9.0'`

**Comment by Coeur** [comment] 2018-09-18 09:09
@BB9z not the same finality: my example workaround was to accomplish iOS 8.0 for target 'One' and iOS 9.0 for target 'Two'. Your script isn't conditional to the target and isn't mixing iOS versions as intended.

**Comment by Coeur** [comment] 2018-09-18 09:13
@BB9z, I'm unsure what you mean by "seems wrong", as I'm successfully using the workaround from my January 8th post.

**Comment by BB9z** [comment] 2018-09-18 09:43
@Coeur assume we had a podfile:

```ruby
target 'One' do
    platform :ios, '8.0'
    pod 'A'    # A has a deployment target 6.0, we want it build with 8.0
    pod 'B'   # B has a deployment target 7.0, we want it build with 8.0
end

target 'Two' do
    platform :ios, '9.0'
    pod 'A'    # A has a deployment target 6.0, we want it build with 9.0
    pod 'B'    # B has a deployment target 7.0, we want it build with 9.0
end
```

In my options, your script will define the deployment targets for "One" and "Two" respectively. But actually, you change nothing. `t.name` is the name of the pod target, not our application.

```
pi.pods_project.targets.each do |t|
  # t is pod target, not our app target
  p t.name # will log A and B
end
```

**Comment by Coeur** [comment] 2018-09-18 12:14
@BB9z The workaround from my January 8th post (second post of this thread) is certainly not for mixing deployment targets: it's for the issue reported in the preceeding post (first post of this thread), with a single desired deployment target (iOS 9 for instance).

I don't understand why people are diverging the discussion on supporting multiple deployment target when it doesn't even work correctly for one single unique deployment target: **if the target is built for 9.0, then the Pods should build for 9.0, not for 8.0. That's all there is in this issue report.**

**Comment by amorde** [comment] 2018-09-28 04:15
I seems that it would make sense to bump the deployment target to the user project's value if it is higher than the podspec's deployment target. @dnkoutso can you think of any issues that may arise from doing that?

**Comment by lolgear** [comment] 2018-09-28 06:39
@amorde If person has one project/workspace for several targets ( for example, several "typical" targets ), these targets could be out of sync in "deployment target dimension", but Pods are shared between these "typical" targets.

Typical targets are either app extensions or cloned apps ( some teams have clones of their main app for rebranding reasons before "big daddy money income").

**Comment by amorde** [comment] 2018-09-28 06:57
ah, I forgot that a target can specify a deployment target _lower_ than the project one. bummer.

**Comment by Speakus** [comment] 2018-12-27 19:50
I believe the issue is duplicated with this one: https://github.com/CocoaPods/CocoaPods/issues/8069 but for my opinion current issue is better described

**Comment by Coeur** [comment] 2019-03-28 01:43
@stale please keep it open.

**Comment by Whirlwind** [comment] 2019-03-28 02:00
Could somebody tell me why the CP use the min deployment version which be defined in the podspec. I could not find the reason.

**Comment by lolgear** [comment] 2019-03-28 09:58
@Whirlwind 

Well, I can try... the truth is in [License](https://github.com/CocoaPods/CocoaPods/blob/master/LICENSE)...

Read [carefully](https://github.com/CocoaPods/CocoaPods/blob/8c5549330970731b73f98f2b7b2b26331b990718/LICENSE#L22)...

> THE SOFTWARE IS PROVIDED "AS IS", WITHOUT WARRANTY OF ANY KIND, EXPRESS OR...

**Comment by GiantBlue76** [comment] 2019-04-08 00:40
Any ETA on a fix for this?  It's extremely annoying.

**Comment by Coeur** [comment] 2019-04-08 04:21
@GiantBlue76 with a `post_install` hook, [as shown in the second post of the thread](https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-355905199), the configuration is kept even after `pod install` or `pod update`.

**Comment by GiantBlue76** [comment] 2019-04-08 14:09
> @GiantBlue76 with a `post_install` hook, [as shown in the second post of the thread](https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-355905199), the configuration is kept even after `pod install` or `pod update`.
> 
> And no, there won't be any ETA until someone gets their hands at a pull request. Could be you, could be anyone.

Thank you!  This is a sufficient workaround.  Much appreciated!

**Comment by amorde** [comment] 2019-04-26 16:49
We should be treating this as a _minimum_, but there are certain situations this isn't handled properly.

I'll have a PR up for this relatively soon - targeting 1.8.0 release for this

**Comment by stanmots** [comment] 2019-05-05 18:57
I updated the script mentioned in [this comment](https://github.com/CocoaPods/CocoaPods/issues/7314#issuecomment-355905199) for those who:

- Use the new `generate_multiple_pod_projects` feature
- Want to prevent warnings for pods which have too low deployment target versions

To use this script run

```bash
pod deintegrate
pod install
```

```ruby
source 'https://cdn.jsdelivr.net/cocoa/'

# This is your app's deployment target version
DEPLOYMENT_VERSION = '12.0'.freeze
DEPLOYMENT_TARGET_KEY = 'IPHONEOS_DEPLOYMENT_TARGET'.freeze
# All pods will have at least this version to prevent Xcode warnings
PODS_MIN_DEPLOYMENT_VERSION = '8.0'.freeze

platform :ios, DEPLOYMENT_VERSION
use_modular_headers!

install! 'cocoapods',
         generate_multiple_pod_projects: true,
         incremental_installation: true

target 'YourTarget' do
 # Insert your pods

  target 'YourTargetTests' do
    inherit! :complete
    # Insert your test pods

  end
end

def fix_deployment_targets(installer)
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configuration_list.build_configurations.each do |config|
        if config.build_settings[DEPLOYMENT_TARGET_KEY].to_f < PODS_MIN_DEPLOYMENT_VERSION.to_f
          config.build_settings[DEPLOYMENT_TARGET_KEY] = PODS_MIN_DEPLOYMENT_VERSION
          puts "Successfully set #{DEPLOYMENT_TARGET_KEY} of target #{target.name} for config #{config.display_name} to #{PODS_MIN_DEPLOYMENT_VERSION}"
        end
      end
    end
  end
end

post_install do |installer|
  fix_deployment_targets installer
end
```

**Comment by icecrystal23** [comment] 2019-05-20 23:46
My 2 cents: CocoaPods should *not* change a defined minimum deployment target.  There is no bug here other than user error: trying to use a library with an unsupported minimum deployment target.  The correct answer to this problem is for AFNetworking to drop support for iOS 7.  FWIW it looks like they did do this recently: https://github.com/AFNetworking/AFNetworking/commit/b3c4a78aca208f4dae596968b3dffb39bb44efa6

**Comment by amorde** [comment] 2019-05-21 17:59
After thinking about this some more I agree with the above. CocoaPods is doing the right thing by following what the podspec claims to support, and if pod consumers want to change that they can do so using a post_install hook. At this point I don't consider this a bug.

**Comment by Coeur** [comment] 2019-05-22 03:17
@amorde The first line of the Podfile being `platform :ios, '9.0'`, setting the xcconfig for an older version of iOS is the issue.

**Comment by icecrystal23** [comment] 2019-05-22 04:22
@Coeur that is the target platform for your project, not for each Pod that you want to include.  It informs CocoaPods which compatible versions of dependencies to pull in.

**Comment by icecrystal23** [comment] 2019-05-22 04:34
There seems to be a misconception among folks in this thread about what a minimum deployment target means and the effects of setting one. 

There are runtime API availability checks that can be used to properly support multiple versions of iOS in a single executable. The minimum deployment target lets a library or application run correctly on that version or higher. Furthermore updating the minimum deployment target can cause complication to fail (for deprecated methods that are removed), therefore it is not a good idea for a tool like this to change it.

**Comment by Coeur** [comment] 2019-05-22 04:37
@icecrystal23 please give us an example of such compilation failure when raising the minimum deployment target up.

**Comment by Coeur** [comment] 2019-05-22 05:41
If we (@amorde, @icecrystal23) consider it's not a bug, then we should change [the documentation of `platform` in the Podfile](https://github.com/CocoaPods/Core/blob/61d22428211654717845806b701806fa1764f05f/lib/cocoapods-core/podfile/dsl.rb#L533) to be clear that `platform :ios, '9.0'` isn't going to do what many people want.

We could write something like:
>### platform
>Specifies the platform for which a static library should be built, but NOT the deployment target for which it should be built (the number in `platform :ios, '9.0'` is only to find a compatible version of the pod). The actual deployment target will be lower than specified, will have unused symbols and will cause you a lot of headache. To properly set the minimum deployment target, please always manually add a workaround like:
>```ruby
>post_install do |pi|
>    pi.pods_project.targets.each do |t|
>        t.build_configurations.each do |bc|
>            bc.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
>        end
>    end
>end
>```
>where '9.0' is your actual minimum deployment target.

**Comment by icecrystal23** [comment] 2019-05-22 15:29
Looks like the most common error I see is actually a warning, but we tend to have "Treat warnings as errors" enabled so it causes failures in our libraries.  Example, when moving the deployment target from 10 to 11:
`'bottomLayoutGuide' was deprecated in iOS 11.0: Use view.safeAreaLayoutGuide.bottomAnchor instead of bottomLayoutGuide.topAnchor`

Note that this will cause the behavior to be wrong even if it doesn't actually cause compilation to fail (ie, if you treat it as a warning instead of an error).

+1 to updating the documentation, however I still disagree with the assumption that the behavior *you* want is the behavior *most* people want.  Either way, the documentation should be correct and clear about what the setting actually does.

**Comment by Whirlwind** [comment] 2019-05-22 15:47
+1 to this is a bug.

I write a SDK, and it supports iOS 6 and later. But I don't hope that user compile it with iOS 6, and I hope the user compile it with the latest iOS version ( or they support deploy version, eg: iOS 10). 

I did many things to support new api to get better development way. But now, the CocoaPods will never compile the Pods target to use new api. As a SDK owner, I could not let my user use new api, it is too bad.

And, I am a developer for a app, too. I still hope use new api, but the CocoaPods could not support it. It is too bad.

Of cause, I could write a `post_install` to fix it. But It is not a good way. I have 3 app targets with different deploy target version, it is too hard to write a hook.

Maybe, we could have a dsl to choice the way to user.

**Comment by lolgear** [comment] 2019-05-22 15:55
@icecrystal23 

Am I right that you are talking about these two sets:

|Pod Deployment target|SDK Version|App Deployment Target|
|---|---|---|
|10.0|12.3|11.0|
|11.0|12.3|11.0|

Next, you are talking that behavior will be different if you switch these settings from set 1 to set 2 ( by updating dependency deployment target version to your app deployment target. ).

Is it correct now?

Next, in these assumptions, your app will be installed on devices with OS version _greater than or equal_ to **App Deployment Target**.

1. So, if an old framework has small deployment target and uses old symbols that _are_ removed or _obsoleted_ or _deprecated_ in newer OS versions, it _will compile_ and perfectly linked to your project?

2. But if you increase deployment target of this framework, it will cause errors and warnings and will block further development in case of deprecated/removed/obsoleted old stuff?

**Comment by icecrystal23** [comment] 2019-05-22 16:32
@lolgear mostly yeah. The point is that the library was developed using a specific minimum deployment target in mind.  It will compile and link and work fine in an app with a higher minimum deployment target.  

I did a little testing with a sample app and changing the minimum deployment target around.  It appears that `bottomLayoutGuide` seems to function correctly no matter which target is chosen.  Changing the minimum deployment target to something higher seems to have no effect other than causing compilation warnings.

I don't understand what benefit would be gained from updating the minimum deployment target to something higher than what the library was written for.  New APIs can still be accessed using availability APIs, like this: 
```
if #available(iOS 11.0, *) { /* do new stuff */ } else { /* do old stuff */ }
```

**Comment by LinusU** [comment] 2019-07-29 21:21
@icecrystal23 

> I don't understand what benefit would be gained from updating the minimum deployment target to something higher than what the library was written for. [...]

I've posted this in #4859, but it seems very relevant here:

Since I have a deployment target of iOS 12 in my main app, my app doesn't build arm 32-bit code, but since some of the pods have a much lower deployment target they do. This leaves me with linking errors when I'm trying to archive the app, and the only fix I've found is to bump the deployment target to 12 on all my pods as well.

I think it would be very neat if CocoaPods could always propagate my platform :ios, '12.0' down to the individual pods deployment target. That way all pods would be optimized to run for the appropriate platform!

https://github.com/CocoaPods/CocoaPods/issues/4859#issuecomment-500838635

**Comment by icecrystal23** [comment] 2019-07-29 21:26
@LinusU you are then consuming the Pods in a way not intended by the authors.  You can choose to apply that workaround, but it is not a good general policy that should be blindly applied to all pods.

**Comment by Coeur** [comment] 2019-07-30 03:27
@icecrystal23 you're probably wrong about that: pod authors may support MULTIPLE versions of iOS, while the podspec only let us define the minimum one.

**Comment by LinusU** [comment] 2019-07-30 10:03
> [...] but it is not a good general policy that should be blindly applied to all pods.

I don't really see how that is sustainable, should I _only_ use pods that specifically targets iOS 12? That seems quite strange. Surely there should be no ill effects by compiling with a newer deployment target? 🤔

**Comment by icecrystal23** [comment] 2019-07-30 16:54
You guys are still acting like you can't run a library built for iOS 8 on iOS 12.  You can.  It is a *minimum* deployment target.  Meaning the library supports iOS 8 and newer.

I don't know what linker errors you are getting, but in general you can compile and link with older minimum targets just fine.

**Comment by Westacular** [comment] 2019-08-02 16:53
@LinusU A workaround for the specific issue of dropping 32-bit code when targeting iOS 11+ is to set `ARCHS = "$(ARCHS_STANDARD_64_BIT)"` in your app target. CocoaPods _does_ automatically copy this setting to all Pods targets. (Xcode will give an "update to recommended settings" warning about this, but that seems like a lesser evil.)

**Comment by LinusU** [comment] 2019-08-02 17:00
@Westacular that's amazing, thanks!!

**Closed** 2019-12-29 20:25 UTC
Labels: s1:awaiting input

**Comment by SohaibSiddique** [comment] 2021-04-29 08:33
> I found the following workaround, adding a post_install hook:
> 
> ```
> platform :ios, '9.0'
> use_frameworks!
> 
> abstract_target 'default_pods' do
>     pod 'AFNetworking', '~> 3'
>     target 'example'
> end
> 
> post_install do |pi|
>     pi.pods_project.targets.each do |t|
>         t.build_configurations.each do |config|
>             config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '9.0'
>         end
>     end
> end
> ```

its working for me in 2021

**Comment by MLukman** [comment] 2021-09-03 08:42
Still happening today

**Comment by Coeur** [comment] 2021-09-04 12:23
Well, the topic was closed by a bot, not because it was resolved.
