### ISSUE TITLE
Target has frameworks with conflicting names: googletoolboxformac.

### ISSUE THREAD

**Issue by tapz** [CocoaPods/CocoaPods#6083] opened 2016-10-25 18:09 UTC
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod update

## What did you expect to happen?
 
Install all pod dependencies correctly and the project compiles without errors.

## What happened instead?

If I include FireBase/Core to MyAppExtension target I get this error in pod update:
[!] The 'Pods-MyApp' target has frameworks with conflicting names: googletoolboxformac.

If I do NOT include FireBase/Core to MyAppExtension target I get a compiler error "Missing required Module ''Firebase". 

Really don't understand why a framework is needed from a framework I have imported. What other frameworks the framework is using should be its internal matter. My projects are all Swift. Firebase is some binary only objective-c crap.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8T61a)
         Git : git version 2.9.3 (Apple Git-75)
Ruby lib dir : /Users/tapani/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5427dc44a5df9aa13c530cb9f30f28bee0b1feb3
```

### Installation Source

```
Executable Path: /Users/tapani/.rvm/gems/ruby-2.2.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

install! 'cocoapods',
    :integrate_targets => true,
    :deduplicate_targets => true

target 'MyApp' do
    project '../MyApp.xcodeproj'

    target 'MyAppCore' do
        pod 'Firebase/Core'
        pod 'Firebase/Messaging'
        pod 'Firebase/RemoteConfig'
        pod 'GoogleSignIn'
    end

    target 'MyAppTests' do
      inherit! :search_paths
    end

    target 'MyAppExtension' do
        inherit! :search_paths
        pod 'Firebase/Core'
    end
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['APPLICATION_EXTENSION_API_ONLY'] = 'NO'
    end
  end
end
```

**Comment by benasher44** [comment] 2016-10-25 23:58
This looks like a dup of #5643. Going to close this one. Thanks for filing!

**Closed by benasher44** 2016-10-25 23:58 UTC

**Comment by tapz** [comment] 2016-11-16 11:08
When will there be a fix for this? Unable to use CocoaPods at all with my framework + share extension project! The RC did not give this error and everything worked just fine. Just change this to warning.

**Comment by zierka** [comment] 2016-12-08 12:39
This is a fairly common use case when having extensions, so it would be good to have some feedback from the team about this.

Maybe this [comment](https://github.com/CocoaPods/CocoaPods/issues/5708#issuecomment-246935216) could be a possible solution?

**Comment by lexin** [comment] 2017-03-28 11:02
Yes. with 1.2.0 Have this error. How to link pod to the extension target?

**Comment by ControlAdad** [comment] 2017-03-28 19:18
Me too have same problem :|

**Comment by lexin** [comment] 2017-03-29 07:28
Installed cocoapods 1.1.1 vers 
Everything is ok. But it's strange, why the last version cause an error.

**Comment by serges147** [comment] 2017-04-15 07:02
Same problem with 1.2.1

**Comment by benasher44** [comment] 2017-04-26 17:02
If you could provide a Podfile that reproduces the issue, that'd be helpful!

**Comment by mxcl** [comment] 2017-05-22 22:49
I have run into this issue with almost 7 projects now. I still have no idea why it happens, or how exactly it should be fixed. The linked threads in this thread have all been closed and so cannot be commented on. This is the only result for this issue that comes up in Google. I am a little frustrated here.

**Comment by shkron** [comment] 2017-05-24 17:17
The issue is with the extension. Somehow Google's frameworks (Firebase and regular Google) are conflicting when not added to both targets together (main and the extension).

The quick fix that worked for me is to either add GoogleSignIn or whatever Google module you are trying to add to the extension target as well as the main target, or remove any google module from extension target in Podfile and update if applicable.

**Comment by sbrighiu** [comment] 2017-05-31 22:12
Guys, i've been developing keyboards for a while. Just use "pod _1.0.1_ update" to update your pods and all will be ok. This coupled with removing the Frameworks folder after the arhive has been made (only do if you have issues with submitting to App Store), will save you a lot of time
