### ISSUE TITLE
pod can't specify version well

### ISSUE THREAD

**Issue by L-Jovi** [CocoaPods/CocoaPods#5581] opened 2016-06-29 03:52 UTC
I follow smart [react-native-ios-charts](https://github.com/Jpadilla1/react-native-ios-charts) and update to new version by `pod install`

and I specify version below

    use_frameworks!
    
    target 'MyApp' do
      pod 'SwiftyJSON', '2.3.1'
      pod 'Charts', '2.2.3'
    end

but the version always incorrect like below output

    Analyzing dependencies
    Downloading dependencies
    Installing Charts (2.2.4)
    Installing SwiftyJSON (2.3.2)
    Generating Pods project
    Integrating client project
    
    [!] Please close any current Xcode sessions and use `MyApp.xcworkspace` for this project from now on.
    
    Sending stats
    
    Pod installation complete! There are 2 dependencies from the Podfile and 2 total pods installed.

how could I fix it?

thanks for your time.

**Comment by neonichu** [comment] 2016-06-29 08:43
How does your `Podfile.lock` look like?

**Comment by L-Jovi** [comment] 2016-06-29 10:15
@neonichu  thanks for your reply, provide my `Podfile.lock` below.

```
PODS:
  - Charts (2.2.4):
    - Charts/Core (= 2.2.4)
  - Charts/Core (2.2.4)
  - SwiftyJSON (2.3.2)

DEPENDENCIES:
  - Charts (~> 2.2.3)
  - SwiftyJSON (~> 2.3.1)

SPEC CHECKSUMS:
  Charts: a9e735c83c6d376ade20f6612dcf0ba217394a49
  SwiftyJSON: 04ccea08915aa0109039157c7974cf0298da292a

PODFILE CHECKSUM: 626f6c08d9ba950017bb5af58c8a27a9c0af03ab

COCOAPODS: 1.0.0
```

I'm not familiar with `Podfile.lock`, how could I fix it?

thanks for your patience.

**Comment by neonichu** [comment] 2016-06-29 11:00
`pod update` should do the trick

But I'm wondering what the behaviour should actually be like when the versions from the lockfile violate the Podfile — maybe this should actually fail to install? cc @segiddins

**Comment by L-Jovi** [comment] 2016-06-29 11:44
I try `pod update` but also fetch wrong version :(

**Comment by neonichu** [comment] 2016-06-29 11:55
Which version of CocoaPods are you using? `pod update` works for me using the given `Podfile` and lockfile.

**Comment by L-Jovi** [comment] 2016-06-29 12:49
pod version `1.0.0`

**Comment by L-Jovi** [comment] 2016-07-04 04:24
@neonichu  any idea now?

thanks for your patience :)

**Comment by segiddins** [comment] 2016-07-05 18:45
I have zero clue, I also cannot reproduce it with the given Podfile & Lockfile

**Comment by neonichu** [comment] 2016-08-22 20:47
Closing this, because I don't think there unfortunately isn't anything actionable we can do here.

**Closed by neonichu** 2016-08-22 20:47 UTC
Labels: s1:awaiting input

**Comment by L-Jovi** [comment] 2016-08-23 02:16
╮(╯_╰)╭
