### ISSUE TITLE
Failed to import bridging header when executing UI test target

### ISSUE THREAD

**Issue by RuslanPatyk** [CocoaPods/CocoaPods#5440] opened 2016-06-01 14:31 UTC
# Report

Failed to import bridging header when executing UI test target

## What did you do?

Before, I was having a trouble with using of @testable import in unit test target, but @jessecurry 's answer (https://github.com/CocoaPods/CocoaPods/issues/2695) did help me. Now, unit tests are OK, but approach descried in the issue above doesn't work with UI tests target. I am getting the following error: 

"2016-06-01 17:25:28.603 XCTRunner[50109:4048860] Running tests...
2016-06-01 17:25:28.624 XCTRunner[50109:4048860] The bundle “ProjectsUITests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-06-01 17:25:28.624 XCTRunner [50109:4048860(dlopen_preflight(/Users/ruslanpatyk/Library/Developer/Xcode/DerivedData/Projects-atquhxnomxlwelhgfuqaeifnnhto/Build/Products/Debug-iphonesimulator/ProjectsUITests-Runner.app/PlugIns/ProjectsUITests.xctest/ProjectsUITests): Library not loaded: @rpath/Alamofire.framework/Alamofire
  Referenced from: /Users/ruslanpatyk/Library/Developer/Xcode/DerivedData/Projects-atquhxnomxlwelhgfuqaeifnnhto/Build/Products/Debug-iphonesimulator/ProjectsUITests-Runner.app/PlugIns/ProjectsUITests.xctest/ProjectsUITests
  Reason: image not found)"

## What did you expected to happen?

1. It would be great to get a step by step tutorial from cocoa-pods team about setting up cocoa pods with projects that use both unit tests and ui tests. 
2. It would be nice to get info about using @testable import in unit test target and ui test target.

**Comment by segiddins** [comment] 2016-06-01 14:35
This is a duplicate of #5250

**Closed by segiddins** 2016-06-01 14:35 UTC
