### ISSUE TITLE
undefined method `to_ary' for #<Pod::Specification name="iVersion">Did you mean?  to_query

### ISSUE THREAD

**Issue by swordray** [CocoaPods/CocoaPods#4748] opened 2016-01-11 04:16 UTC
### Command

```
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/swordray/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 0fdaddc77d9f60958bd0dbe1753b3bfb5449d71d
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '8.0'

use_frameworks!

pod 'iVersion'
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="iVersion">
Did you mean?  to_query
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/swordray/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/swordray/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by orta** [comment] 2016-01-11 08:09
Dupe of #4689  - please use the 1.0.0 beta for 2.3.0 support

**Closed by orta** 2016-01-11 08:09 UTC
