### ISSUE TITLE
Error while 'pod install' in ChatSecure-iOS

### ISSUE THREAD

**Issue by JayrajGohil** [CocoaPods/CocoaPods#4191] opened 2015-09-16 19:54 UTC
While I am doing 'pod install' step it is throwing error every time. 
Error is like below and I also attached the screenshots of same.
 **RuntimeError - [Xcodeproj] Consistency issue: no parent for object `XMPPRoom.xcdatamodel`: `VersionGroup`, `BuildFile`**
..
...
...
...

**[!] Oh no, an error occurred.**

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=%5BXcodeproj%5D+Consistency+issue%3A+no+parent+for+object+%60XMPPRoom.xcdatamodel%60%3A+%60VersionGroup%60%2C+%60BuildFile%60&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

![1](https://cloud.githubusercontent.com/assets/7090220/9916511/62e07074-5cda-11e5-9ee8-689035e0b71b.png)
![2](https://cloud.githubusercontent.com/assets/7090220/9916513/63357222-5cda-11e5-87e2-35ba6b302ea9.png)
![3](https://cloud.githubusercontent.com/assets/7090220/9916514/6339e9b0-5cda-11e5-8c60-abfe362b4744.png)
![4](https://cloud.githubusercontent.com/assets/7090220/9916515/63410664-5cda-11e5-83e7-42f69ad7e506.png)
![5](https://cloud.githubusercontent.com/assets/7090220/9916512/63341f76-5cda-11e5-82ad-d68cb2b867de.png)

**Comment by neonichu** [comment] 2015-09-18 00:00
This is a duplicate of #4187

**Closed by neonichu** 2015-09-18 00:00 UTC
