### ISSUE TITLE
Cannot include a pod in multiple targets with different platform settings

### ISSUE THREAD

**Issue by senseful** [CocoaPods/CocoaPods#4703] opened 2015-12-30 22:12 UTC
I would like to include a pod in both my iOS target, and my watchOS 2 target, however, when I attempt to do so, I get various errors.

### 🌈 Details:

  - CocoaPods 0.39.0
  - Xcode 7.2
  - Language: Swift

### Attempt 1: Include pod in both targets

In order for the watch kit extension to use the proper version of the framework, it looks like we must [specifically mention the platform](https://github.com/neonichu/native-watchOS-example). This seems to be recommended on [this post also](https://medium.com/@JTEhlert/using-cocoapods-with-watchos-2-723b92eae04f#.j8qxp9ed7).

Podfile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CocoaPodsWithWatchTarget' do
    platform :ios, '9.0'
    pod 'Parse', '~> 1.11'
end

target 'CocoaPodsWithWatchTarget WatchKit App' do

end

target 'CocoaPodsWithWatchTarget WatchKit Extension' do
    platform :watchos, '2.0'
    pod 'Parse', '~> 1.11'
end
```

Error:

  - Generated duplicate UUIDs

Full Output:

> $ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.1)
Installing Parse (1.11.0)
Generating Pods project
2015-12-30 13:41:30.297 ruby[72433:22160294] warning:  The file reference for "Bolts.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
2015-12-30 13:41:30.297 ruby[72433:22160294] warning:  The file reference for "Parse.framework" is a member of multiple groups ("Products" and "Products"); this indicates a malformed project.  Only the membership in one of the groups will be preserved (but membership in targets will be unaffected).  If you want a reference to the same file in more than one group, please add another reference to the same path.
Integrating client project
>
[!] Please close any current Xcode sessions and use `CocoaPodsWithWatchTarget.xcworkspace` for this project from now on.
Sending stats
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total
pods installed.
>
[!] [Xcodeproj] Generated duplicate UUIDs:
>
PBXFileReference -- /mainGroup/children/children:displayName:Bolts.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Bolts.framework,path:Bolts.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Bolts.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Bolts.framework,path:Bolts.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Parse.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Parse.framework,path:Parse.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Parse.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Parse.framework,path:Parse.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_CocoaPodsWithWatchTarget.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_CocoaPodsWithWatchTarget.framework,path:Pods_CocoaPodsWithWatchTarget.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_CocoaPodsWithWatchTarget_WatchKit_Extension.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_CocoaPodsWithWatchTarget_WatchKit_Extension.framework,path:Pods_CocoaPodsWithWatchTarget_WatchKit_Extension.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Products,isa:PBXGroup,name:Products,sourceTree:<group>,/Products/children/displayName:Bolts.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Bolts.framework,path:Bolts.framework,sourceTree:BUILT_PRODUCTS_DIR,/Products/Bolts.framework
PBXFileReference -- /mainGroup/children/children:displayName:Bolts.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Bolts.framework,path:Bolts.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Bolts.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Bolts.framework,path:Bolts.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Parse.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Parse.framework,path:Parse.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Parse.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Parse.framework,path:Parse.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_CocoaPodsWithWatchTarget.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_CocoaPodsWithWatchTarget.framework,path:Pods_CocoaPodsWithWatchTarget.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Pods_CocoaPodsWithWatchTarget_WatchKit_Extension.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Pods_CocoaPodsWithWatchTarget_WatchKit_Extension.framework,path:Pods_CocoaPodsWithWatchTarget_WatchKit_Extension.framework,sourceTree:BUILT_PRODUCTS_DIR,,displayName:Products,isa:PBXGroup,name:Products,sourceTree:<group>,/Products/children/displayName:Parse.framework,explicitFileType:wrapper.framework,includeInIndex:0,isa:PBXFileReference,name:Parse.framework,path:Parse.framework,sourceTree:BUILT_PRODUCTS_DIR,/Products/Parse.framework

### Attempt 2: Perhaps the targets are being linked to twice?

It looks like a similar issue could be resolved [by ensuring that each target is only linked to once](https://github.com/CocoaPods/CocoaPods/issues/2633#issuecomment-58731403).

Podfile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

link_with ['CocoaPodsWithWatchTarget']

def import_pods
    pod 'Parse', '~> 1.11'
end

target 'CocoaPodsWithWatchTarget' do
    platform :ios, '9.0'
    import_pods
end

target 'CocoaPodsWithWatchTarget WatchKit App' do

end

target 'CocoaPodsWithWatchTarget WatchKit Extension' do
    platform :watchos, '2.0'
    import_pods
end
```

Error:

  - Generated duplicate UUIDs

Full Output:

> (same as above)

### Attempt 3: Use link_with with multiple targets

Looks like the documentation for [link_with](http://guides.cocoapods.org/syntax/podfile.html#link_with) says that it determines which pods to link with if they are defined at the root level (if I understood correctly). So let's try linking with both targets.

Podfile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

link_with 'CocoaPodsWithWatchTarget', 'CocoaPodsWithWatchTarget WatchKit Extension'

pod 'Parse', '~> 1.11'

target 'CocoaPodsWithWatchTarget' do
    platform :ios, '9.0'
end

target 'CocoaPodsWithWatchTarget WatchKit App' do

end

target 'CocoaPodsWithWatchTarget WatchKit Extension' do
    platform :watchos, '2.0'
end
```

Error:

  - "Targets with different platforms"

Full Output:

>$ pod install
Updating local specs repositories
>
CocoaPods 1.0.0.beta.1 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.
>
For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.
>
Analyzing dependencies
[!] Targets with different platforms

### Attempt 4: Include the pod once at the root, and define platforms for each target

Podfile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'Parse', '~> 1.11'

target 'CocoaPodsWithWatchTarget' do
    platform :ios, '9.0'
end

target 'CocoaPodsWithWatchTarget WatchKit App' do

end

target 'CocoaPodsWithWatchTarget WatchKit Extension' do
    platform :watchos, '2.0'
end
```

Error:

  - When attempting to use `import Parse` in the WatchKit Extension, I get the build error "No such module 'Parse'". (It works just fine in the iOS target.)

Full Output:

> $ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.1)
Installing Parse (1.11.0)
Generating Pods project
Integrating client project
Sending stats
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

### Attempt 5: See if I can even get it working with just watchOS 2

Podfile:
```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

target 'CocoaPodsWithWatchTarget' do

end

target 'CocoaPodsWithWatchTarget WatchKit App' do

end

target 'CocoaPodsWithWatchTarget WatchKit Extension' do
    platform :watchos, '2.0'
    pod 'Parse', '~> 1.11'
end
```

Error:

  - When attempting to use `import Parse` in the iOS target, I get the build error "No such module 'Parse'" (obviously, since it was removed from the podfile for that target). (It works just fine in the WatchKit Extension target.)

Full Output:
> $ pod install
Updating local specs repositories
Analyzing dependencies
Downloading dependencies
Installing Bolts (1.5.1)
Installing Parse (1.11.0)
Generating Pods project
Integrating client project
Sending stats
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

### Other Notes

In this particular example, I was staring with a brand new project each time by first creating the project, committing changes to git, then reseting the changes after each attempt. 

When I tried it with another project, I would sometimes get an error about needing to [update the base configuration](https://github.com/CocoaPods/CocoaPods/issues/2633). When that did happen, [webdevotion's fix](https://github.com/CocoaPods/CocoaPods/issues/2633#issuecomment-97872445) worked; however, there was still some form of the errors listed above.

How can I get this to work? I.e. so I can build my project with the pod being accessible from both targets.

Any links to relevant documentation would also be appreciated!

**Comment by senseful** [comment] 2015-12-31 10:13
It seems like I should be using the first version of the podfile above, and that the duplicate UUIDs problem is related to [this issue](https://github.com/CocoaPods/CocoaPods/issues/4326). Looks like we should be using [the temporary fix outlined here](https://medium.com/@mosn/watchos-2-0-pod-install-5236a40ca4bc#.2z0muqhcn) for now. Please correct me if I'm wrong! Thanks

**Comment by neonichu** [comment] 2015-12-31 18:04
Sounds right, closing this as a duplicate of #4326

**Closed by neonichu** 2015-12-31 18:04 UTC
