### ISSUE TITLE
UITests can import framework but can't run any methods from it

### ISSUE THREAD

**Issue by NicosKaralis** [CocoaPods/CocoaPods#5433] opened 2016-05-31 13:36 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 🌈

# Report

## What did you do?

I've updated my project to use the latest version of cocoapods, from `0.39` to `1.0`. After this change my UITest no longer can import a framework that I previously had imported.

This is my UITest class that is no longer working:
```
import XCTest
import SimulatorStatusMagic
class IranCabralUITests: XCTestCase {
  override func setUp() {
    super.setUp()
    XCUIApplication()
    SDStatusBarManager.sharedInstance().enableOverrides()
  }
  
  override func tearDown() {
    super.tearDown()
    SDStatusBarManager.sharedInstance().disableOverrides()
  }
  // Tests go here
}
```

## What did you expected to happen?

The library should be loaded and executed as it happened before I updated cocoapods

## What happened instead?

The UITest is able to import the framework but crashes if I call any method from it and I get this error:
```
2016-05-31 10:17:48.159 XCTRunner[22997:5393699] Running tests...
2016-05-31 10:17:48.181 XCTRunner[22997:5393699] The bundle “AppUITests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2016-05-31 10:17:48.181 XCTRunner[22997:5393699] (dlopen_preflight(/Users/user/Project/App/DerivedData/App/Build/Products/Debug-iphonesimulator/AppUITests-Runner.app/PlugIns/AppUITests.xctest/AppUITests): Library not loaded: @rpath/SimulatorStatusMagic.framework/SimulatorStatusMagic
  Referenced from: /Users/user/Projects/App/DerivedData/App/Build/Products/Debug-iphonesimulator/AppUITests-Runner.app/PlugIns/AppUITests.xctest/AppUITests
  Reason: image not found)
```

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin14]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/nicoskaralis/.rvm/rubies/ruby-2.2.4/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ 645efcc8ecbd3fcfc44770e265b8436a7664f1bf
               master - https://github.com/CocoaPods/Specs.git @ 900a5276e58e3d16337f4aff4ab64eda9bed7d3e
```

### Installation Source

```
Executable Path: /Users/nicoskaralis/.rvm/gems/ruby-2.2.4@km005-ios/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

target 'App' do
  # Pods for App
  pod 'Fabric'
  # ...

  target 'AppUITests' do
    inherit! :search_paths
    # Pods for testing
    pod 'SimulatorStatusMagic', configuration: 'Debug'
  end
end
```

## Project that demonstrates the issue

https://github.com/NicosKaralis/pods-error

**Comment by NicosKaralis** [comment] 2016-05-31 15:35
After some research I found what is happening.

Looking at #4752 I began look if could be similar to this problem. Since I don't know all config vars set by XCode I started checking the run scripts that cocoapods did set.

And I found that my target application has a "📦 Embed Pods Frameworks" that calls ``"${SRCROOT}/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh"`` and when I look at the UITest target I didn't see this script. So I added it and it works now.

Isn't this supposed to be set by cocoapods?

After I set this it works:
![image](https://cloud.githubusercontent.com/assets/627404/15680414/09997e30-272c-11e6-8a15-168b32521464.png)

**Comment by segiddins** [comment] 2016-05-31 15:49
Duplicate of #5250

**Closed by segiddins** 2016-05-31 15:49 UTC

**Comment by hadanischal** [comment] 2019-08-11 10:35
> After some research I found what is happening.
> 
> Looking at #4752 I began look if could be similar to this problem. Since I don't know all config vars set by XCode I started checking the run scripts that cocoapods did set.
> 
> And I found that my target application has a "📦 Embed Pods Frameworks" that calls `"${SRCROOT}/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh"` and when I look at the UITest target I didn't see this script. So I added it and it works now.
> 
> Isn't this supposed to be set by cocoapods?
> 
> After I set this it works:
> ![image](https://cloud.githubusercontent.com/assets/627404/15680414/09997e30-272c-11e6-8a15-168b32521464.png)

It really save my day

**Comment by dnkoutso** [comment] 2019-08-11 11:05
Need to remove `inherit!, :search_paths` from UI test target as it requires linking and embedding in order for it to function.

**Comment by DracoRubi** [comment] 2019-10-14 13:14
> After some research I found what is happening.
> 
> Looking at #4752 I began look if could be similar to this problem. Since I don't know all config vars set by XCode I started checking the run scripts that cocoapods did set.
> 
> And I found that my target application has a "📦 Embed Pods Frameworks" that calls `"${SRCROOT}/Pods/Target Support Files/Pods-App/Pods-App-frameworks.sh"` and when I look at the UITest target I didn't see this script. So I added it and it works now.
> 
> Isn't this supposed to be set by cocoapods?
> 
> After I set this it works:
> ![image](https://cloud.githubusercontent.com/assets/627404/15680414/09997e30-272c-11e6-8a15-168b32521464.png)

This solved the issue! Thanks a lot.
