### ISSUE TITLE
Website Search is down

### ISSUE THREAD

**Issue by dburc01** [CocoaPods/CocoaPods#7571] opened 2018-04-01 00:31 UTC
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Navigated to cocoapods.org and searched for various pods.

## What did you expect to happen?

Expected search results based on inquiry

## What happened instead?

One line shows up says
results.  Show only: 

No results show up

## CocoaPods Environment

N/A

## Project that demonstrates the issue

Website status indicates that all features are up and running including search. I tried multiple searches with multiple devices and operating systems. Same result.

**Comment by DanToml** [comment] 2018-04-01 00:32
duplicate of https://github.com/CocoaPods/CocoaPods/issues/7545

**Closed by DanToml** 2018-04-01 00:32 UTC
