### ISSUE TITLE
dyld warning on El Capitan 

### ISSUE THREAD

**Issue by mark-anders** [CocoaPods/CocoaPods#4121] opened 2015-09-03 15:25 UTC
I ran into the issue where early 0.39 beta would not run on El Capitan and in the process I discovered I had TONS of old versions of CocoaPods on my machine.  After cleaning up, and moving to a GEMHOME config, I'm getting the following errors when doing a `pod install` or `pod update`, but not when doing a `pod --version` or `pod list` or possibly other commands.  

This is happening with both 0.39 and 0.38.  Everything seems to work, but obviously something is wrong.  Any ideas?

    Updating local specs repositories
    Analyzing dependencies
    dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode-beta.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
    dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
    dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
    dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode-beta.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
    Pre-downloading: `CocoaLumberjack` from `https://github.com/CocoaLumberjack/CocoaLumberjack.git`, branch `swift_2.0`

**Comment by segiddins** [comment] 2015-09-03 15:29
My guess is that this is happening while verifying you have the Xcode command line tools installed?

**Comment by mark-anders** [comment] 2015-09-03 15:34
I'm not sure.  I have the tools installed. If I do: `xcode-select --install` it says they're installed and to use software update.  Should I try uninstall and re-installing XCode?

**Comment by neonichu** [comment] 2015-09-07 13:45
Can't hurt, definitely looks like an Xcode installation and not a CP issue.

**Comment by PSchu** [comment] 2015-09-11 14:01
Hi, did a reinstall help?
I just updated to El Capitan GM and get the same warnings.

**Comment by mark-anders** [comment] 2015-09-11 18:03
A reinstall did not help.  What I did was: 

1. install via App Store the latest Command Line tools.
2. Deleted the XCode 7 Beta 
3. Installed XCode 7 GM.  I had not had a non-Beta on my machine since I'm running El Capitan.
4. Installed XCode 7.1 Beta

After running pod update on a project I got the same warnings as before.

**Comment by kallipigous** [comment] 2015-09-11 23:15
same problem here. Any thoughts?

**Comment by obitow** [comment] 2015-09-12 02:06
I made a clean install of El Capitan GM and Xcode 7 GM with command line tools and I'm getting this error too.

**Comment by avitus** [comment] 2015-09-14 03:12
I have the exact same problem and have tried reinstalling everything. Am now on Xcode 7 and El Cap final releases and still have the problem.

**Comment by desduvauchelle** [comment] 2015-09-14 08:29
Same issue here.

**Comment by sasikiran** [comment] 2015-09-14 08:59
I also clean installed El Cap GM and Xcode 7 GM and see this warning printed in the console.

**Comment by michaelochs** [comment] 2015-09-14 09:22
Same here.

**Comment by neonichu** [comment] 2015-09-14 09:40
could one of you do a `pod install —verbose` so that we can see which command is printing the warnings?

**Comment by desduvauchelle** [comment] 2015-09-14 09:44
hope this helps 
```
$ pod install --verbose
Preparing

Updating local specs repositories

Updating spec repo `master`
  $ /usr/bin/git pull --ff-only
  From https://github.com/CocoaPods/Specs
     fde9d78..99760e3  master     -> origin/master
  Updating fde9d78..99760e3
  Fast-forward
   Specs/APLRUCache/1.0.0/APLRUCache.podspec.json     | 25 +++++++
   Specs/CHXBannerView/0.8/CHXBannerView.podspec.json | 24 ++++++
   Specs/GBDeviceInfo/3.3.0/GBDeviceInfo.podspec.json | 63 ++++++++++++++++
   Specs/KMSClient/1.0/KMSClient.podspec.json         | 72 ++++++++++++++++++
   Specs/LHJTestes/0.0.1/LHJTestes.podspec.json       | 24 ++++++
   .../0.0.7/LeanCloudFeedback.podspec.json           | 38 ++++++++++
   Specs/MatrixSDK/0.5.3/MatrixSDK.podspec.json       | 35 +++++++++
   Specs/Pegas/0.1.1/Pegas.podspec.json               | 85 ++++++++++++++++++++++
   .../0.6.2/RSPagedItemsController.podspec.json      | 26 +++++++
   .../1.0/WATokenFieldView.podspec.json              | 28 +++++++
   Specs/eeGeo/1.0.92/eeGeo.podspec.json              | 53 ++++++++++++++
   11 files changed, 473 insertions(+)
   create mode 100644 Specs/APLRUCache/1.0.0/APLRUCache.podspec.json
   create mode 100644 Specs/CHXBannerView/0.8/CHXBannerView.podspec.json
   create mode 100644 Specs/GBDeviceInfo/3.3.0/GBDeviceInfo.podspec.json
   create mode 100644 Specs/KMSClient/1.0/KMSClient.podspec.json
   create mode 100644 Specs/LHJTestes/0.0.1/LHJTestes.podspec.json
   create mode 100644 Specs/LeanCloudFeedback/0.0.7/LeanCloudFeedback.podspec.json
   create mode 100644 Specs/MatrixSDK/0.5.3/MatrixSDK.podspec.json
   create mode 100644 Specs/Pegas/0.1.1/Pegas.podspec.json
   create mode 100644 Specs/RSPagedItemsController/0.6.2/RSPagedItemsController.podspec.json
   create mode 100644 Specs/WATokenFieldView/1.0/WATokenFieldView.podspec.json
   create mode 100644 Specs/eeGeo/1.0.92/eeGeo.podspec.json

CocoaPods 0.39.0.beta.4 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.


Analyzing dependencies

Inspecting targets to integrate
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode-beta.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode-beta.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
  Using `ARCHS` setting to build architectures of target `Pods`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-myApp`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-myAppTest`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MyCustomView`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-MyCustomViewTests`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-myApp WatchKit Extension`: (``)
  Using `ARCHS` setting to build architectures of target `Pods-myApp WatchKit App`: (``)

Finding Podfile changes
  - RealmSwift

Resolving dependencies of `Podfile`

Comparing resolved specification to the sandbox manifest
  - Realm
  - RealmSwift

Downloading dependencies

-> Using Realm (0.95.0)

-> Using RealmSwift (0.95.0)
  - Running pre install hooks

Generating Pods project
  - Creating Pods project
  - Adding source files to Pods project
  - Adding frameworks to Pods project
  - Adding libraries to Pods project
  - Adding resources to Pods project
  - Linking headers
  - Installing targets
    - Installing target `Realm` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/Realm/Info.plist`
      - Copying module map file to `Pods/Target Support Files/Realm/Realm.modulemap`
    - Installing target `RealmSwift` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/RealmSwift/Info.plist`
      - Generating module map file at `Pods/Target Support Files/RealmSwift/RealmSwift.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/RealmSwift/RealmSwift-umbrella.h`
    - Installing target `Pods-myApp` iOS 8.0
      - Generating Info.plist file at `Pods/Target Support Files/Pods-myApp/Info.plist`
      - Generating module map file at `Pods/Target Support Files/Pods-myApp/Pods-myApp.modulemap`
      - Generating umbrella header at `Pods/Target Support Files/Pods-myApp/Pods-myApp-umbrella.h`
  - Running post install hooks
  - Writing Xcode project file to `Pods/Pods.xcodeproj`
  - Writing Lockfile in `Podfile.lock`
  - Writing Manifest in `Pods/Manifest.lock`

Integrating client project

Integrating target `Pods-myApp` (`myApp.xcodeproj` project)
  - Running post install hooks
    - cocoapods-stats from `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.5.3/lib/cocoapods_plugin.rb`

Sending stats
      - Realm, 0.95.0
      - RealmSwift, 0.95.0```

**Comment by neonichu** [comment] 2015-09-14 09:50
hm, looks like this is happening when opening the Xcode project. Could you try running this ruby script in your project directory to see if this is actually the cause:

```ruby
#!/usr/bin/env ruby

require 'xcodeproj'

project_path = 'Pods/Pods.xcodeproj'
Xcodeproj::Project.open(project_path)
```

**Comment by Brett-Best** [comment] 2015-09-14 14:00
@neonichu I ran that ruby script see output below from terminal:
```
brettbest$ ruby test.rb
dyld: warning, LC_RPATH @executable_path/../../../../../../../SharedFrameworks in /Applications/Xcode 7.app/Contents/SharedFrameworks/DVTFoundation.framework/Versions/A/../../..//DVTInstrumentsFoundation.framework/Versions/A/DVTInstrumentsFoundation being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode 7.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libclang.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../lib in /Applications/Xcode 7.app/Contents/Frameworks/IDEFoundation.framework/Versions/A/../../../../Developer/Toolchains/XcodeDefault.xctoolchain/usr/lib/libLTO.dylib being ignored in restricted program because of @executable_path
dyld: warning, LC_RPATH @executable_path/../Frameworks in /Applications/Xcode 7.app/Contents/PlugIns/Xcode3Core.ideplugin/Contents/MacOS/Xcode3Core being ignored in restricted program because of @executable_path
```

**Comment by neonichu** [comment] 2015-09-14 14:27
Thanks, now we know when it happens — I'm just confused by why it isn't happening for me.

**Comment by segiddins** [comment] 2015-09-14 14:44
@neonichu system ruby and `dlopen` might not play nicely any more?

**Comment by neonichu** [comment] 2015-09-14 14:46
@segiddins good point, this is exactly what happens (I wasn't using system ruby)

**Comment by segiddins** [comment] 2015-09-14 14:55
Let's radar this and make Xcodeproj more robust? It looks like it can still open CF just fine.

**Comment by neonichu** [comment] 2015-09-14 15:00
FWIW, it doesn't have any impact on Xcodeproj's functionality — we can probably just silence it.

**Comment by Brett-Best** [comment] 2015-09-16 12:00
@neonichu so that wouldn't cause frameworks not getting found?
Podfile used below... The error I am getting is: ld: framework not found Alamofire

Can give more information if needed but if this isn't related to the above warnings I don't want to post it here but rather in the place that you recommend. 
Using Xcode 7 GM on OS X 10.11.
```
use_frameworks!

target 'Pazzle iOS' do
  platform :ios, '9.0'
  pod 'Alamofire'
end

target 'Pazzle iOS Tests' do
  platform :ios, '9.0'
  pod 'Alamofire'
end

target 'Pazzle iOS UITests' do
  platform :ios, '9.0'
  pod 'Alamofire'
end

target 'Pazzle OS X' do
  platform :osx, '10.11'
  pod 'Alamofire'
end

target 'Pazzle OS X Tests' do
  platform :osx, '10.11'
  pod 'Alamofire'
end

target 'Pazzle OS X UITests' do
  platform :osx, '10.11'
  pod 'Alamofire'
end

```
Thanks!

**Comment by neonichu** [comment] 2015-09-16 12:56
@Brett-Best I think this would be rather related to #4034 than to this issue — could you try disabling deduplication to see if that changes anything?

**Comment by Raesu** [comment] 2015-09-18 17:25
I have this issue as well, discovered with a new project. Using `pod install` won't integrate any files into my .xcodeproj nor create a workspace. So it seems totally unusable for creating new projects.

**Comment by willlarche** [comment] 2015-09-18 18:33
I'm having this issue as well.

**Comment by Raesu** [comment] 2015-09-18 19:02
I installed/updated ruby 2.2.3 with Homebrew (https://gorails.com/setup/osx/10.11-el-capitan), but the problem persists.

**Comment by pesception** [comment] 2015-09-18 20:59
Same problem here. None of the things suggested seem to work for me. Desperately looking for a solution !

**Comment by cdstamper** [comment] 2015-09-20 17:39
Looks like I'm having the same issue as of today (it was building fine yesterday and I didn't update my OS, Xcode, or Pods itself).

**Comment by Benjamindodgson** [comment] 2015-09-21 18:33
You can add me to the list of people having this problem. God this sucks.

**Comment by mark-anders** [comment] 2015-09-21 18:46
@Benjamindodgson  - I'm having the problem too, but the pod command is still working for me.  Is it not for you?

**Comment by cdstamper** [comment] 2015-09-21 18:49
@mark-anders I had to install 'pod' in the ~/Software/ruby directory because of El Capitan's Rootless feature, so it's kinda working for me.

**Comment by mark-anders** [comment] 2015-09-21 18:51
@cdstamper - I had to do that too.  This particular bug is about the dyld warning, not about "not being able to install cocoapods on El Cap.

**Comment by ijameslive** [comment] 2015-09-22 02:00
Same boat.... has anyone found a solution yet?

**Comment by willlarche** [comment] 2015-09-22 02:12
I’ve actually found this doesn’t seem to affect my ability to use pods.

**Comment by neonichu** [comment] 2015-09-22 07:33
The warning doesn't affect the usage of CP. I'm locking this to not further clobber the discussion.

If you have other problems, please open other issues for them, with the [required information](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md) we need to reproduce them.

**Comment by neonichu** [comment] 2016-04-30 14:19
Those warnings have been silenced inside Xcodeproj a while ago and didn't have any non-aesthetic impact anyway, so let's close this.

**Closed by neonichu** 2016-04-30 14:19 UTC
