### ISSUE TITLE
'pod try GooglePlacePicker' generate an error

### ISSUE THREAD

**Issue by nicolettinzia** [CocoaPods/CocoaPods#9468] opened 2020-01-08 16:34 UTC
ℹI'm using:
Cocoapods 1.8.4
Xcode 11.2

ℹ The error occurs when I exec this command:
pod try GooglePlacePicker

ℹ This is the error returned:
### Error
```
NoMethodError - undefined method `root' for false:FalseClass
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/user_interface.rb:118:in `title'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.8.4/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

ℹ This is what I expected to happen.  
Install all pod dependencies correctly.

## CocoaPods Environment

ℹ This the output of `pod env`:
### Stack
```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.2 (11B52)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ d6bced7d21e94b8547fbd5dbf0d9131d363976f4
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '9.0'
source 'https://github.com/CocoaPods/Specs.git'

target 'project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  rn_path = '../node_modules/react-native'
  rn_maps_path = '../node_modules/react-native-maps'

  #pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  #pod 'React-RCTGeolocation', :path => '../node_modules/@react-native-community/geolocation'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-ART', :path => '../node_modules/react-native/Libraries/ART'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'

  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga', :modular_headers => true  
  #pod 'React', path: rn_path, subspecs: [
    #'CxxBridge'
  #]
  
  pod 'DoubleConversion', :podspec => "#{rn_path}/third-party-podspecs/DoubleConversion.podspec"
  pod 'glog', :podspec => "#{rn_path}/third-party-podspecs/glog.podspec"
  pod 'Folly', :podspec => "#{rn_path}/third-party-podspecs/Folly.podspec"
   
  pod 'GooglePlaces'
  pod 'GoogleMaps'
  pod 'Google-Maps-iOS-Utils'
  
  pod 'react-native-maps', path: rn_maps_path
  pod 'react-native-google-maps', path: rn_maps_path
  
  pod 'RNImageCropPicker', :path =>  '../node_modules/react-native-image-crop-picker'

  pod 'RNVectorIcons', :path => '../node_modules/react-native-vector-icons'

  pod 'react-native-fetch-blob', :path => '../node_modules/react-native-fetch-blob'

  pod 'RNShare', :path => '../node_modules/react-native-share'

  target 'project' do
    inherit! :search_paths
    # Pods for testing
  end

end

post_install do |installer|
  installer.pods_project.targets.each do |target|
      if target.name == 'react-native-google-maps'
          target.build_configurations.each do |config|
              config.build_settings['CLANG_ENABLE_MODULES'] = 'No'
          end
      end
    if target.name == "React"
      target.remove_from_project
    end
    if target.name == "yoga"
        target.remove_from_project
    end
  end
end

target 'project' do
  # Uncomment the next line if you're using Swift or would like to use dynamic frameworks
  # use_frameworks!

  # Pods for project

  target 'project' do
    inherit! :search_paths
    # Pods for testing
  end

end
```

**Comment by dnkoutso** [comment] 2020-01-08 19:48
Duplicate of https://github.com/CocoaPods/cocoapods-try/issues/63

**Closed by dnkoutso** 2020-01-08 19:48 UTC

**Comment by nicolettinzia** [comment] 2020-01-08 19:56
Then what is the solution?

**Comment by dnkoutso** [comment] 2020-01-08 21:19
No solution yet. Issue is open and needs someone to contribute a fix!

**Comment by arriolac** [comment] 2020-01-27 22:22
@nicolettinzia this error aside, please note that the `GooglePlacePicker` sample is officially deprecated. See: https://cocoapods.org/pods/GooglePlacePicker
