### ISSUE TITLE
Xcode 7 dyld:Library not loaded image not found

### ISSUE THREAD

**Issue by Onetaway** [CocoaPods/CocoaPods#3661] opened 2015-06-09 09:58 UTC
I use Xcode 7 open my xcworkspace.When build ,the console reports as below:

dyld: Library not loaded: @rpath/Pods.framework/Pods
  Referenced from: /var/mobile/Containers/Bundle/Application/0D07038E-BCE0-48B2-AFB4-222DACED9C0B/BaoZouCamera.app/BaoZouCamera
  Reason: image not found

**Comment by formbound** [comment] 2015-06-09 17:48
This is an issue (at least for me) on device only.

**Comment by larsschwegmann** [comment] 2015-06-09 20:41
+1 I have this issue as well. Only on the device though, simulator is fine.

**Comment by segiddins** [comment] 2015-06-09 20:48
Sounds like we're not properly weak-linking the pods framework, @neonichu ?

**Comment by neonichu** [comment] 2015-06-09 21:25
Yep, can you folks check if the framework is set to weak linking in your target?

**Comment by benhanzl** [comment] 2015-06-09 21:43
I am seeing this warning, which might be related:

ld: warning: -weak_framework is treated as -framework when used with -bitcode_bundle (Xcode setting ENABLE_BITCODE=YES). Weak linking may still happen based on availability mark-up in headers

If I turn off Bitcode in my build settings, everything works as expected.

**Comment by larsschwegmann** [comment] 2015-06-09 21:45
Same goes for me. Turning off Bitcode resolved the issue for me.

**Comment by neonichu** [comment] 2015-06-09 21:46
Cool, thanks for the info!

**Comment by jshier** [comment] 2015-06-11 02:26
@neonichu Bitcode support is required for the new app slicing to work. Was this closed as won't fix or will it be fixed in the future? This seems like something CocoaPods should support.

**Comment by cezheng** [comment] 2015-06-16 02:30
As as temporary workaround, I'm disabling bitcode for my project's debug configuration, but received a whole lot of warnings. How will this be fixed in the future?

**Comment by neonichu** [comment] 2015-06-16 08:36
@cezheng It will be fixed by not requiring weak linking for the CP integration, so that bitcode can be enabled without any issues.

**Comment by RLovelett** [comment] 2015-06-24 13:53
I'm using Xcode 7 beta 2 (7A121l) and am experiencing this issue. I've tried, what I think are, both of the work-arounds provided in this issue report.

That is I have tried to not weak link the CP integration Framework. See the diff of the change I made to my Xcode project.

```
diff --git a/Sample.xcodeproj/project.pbxproj b/Sample.xcodeproj/project.pbxproj
index c98d3ee..52cf570 100644
--- a/Sample.xcodeproj/project.pbxproj
+++ b/Sample.xcodeproj/project.pbxproj
@@ -7,7 +7,7 @@
        objects = {

 /* Begin PBXBuildFile section */
-               267658CD88D8FDA2B615ABA8 /* Pods_Sample.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = C01832E6EA74AD6BC1555456 /* Pods_Sample.framework */; settings = {ATTRIBUTES = (Weak, ); }; };
+               267658CD88D8FDA2B615ABA8 /* Pods_Sample.framework in Frameworks */ = {isa = PBXBuildFile; fileRef = C01832E6EA74AD6BC1555456 /* Pods_Sample.framework */; settings = {ATTRIBUTES = (Required, ); }; };
                4C42FB541B30A1AA00CF9ABD /* BooksTableViewCell.swift in Sources */ = {isa = PBXBuildFile; fileRef = 4C42FB521B30A1AA00CF9ABD /* BooksTableViewCell.swift */; };
                4C42FB551B30A1AA00CF9ABD /* BooksTableViewController.swift in Sources */ = {isa = PBXBuildFile; fileRef = 4C42FB531B30A1AA00CF9ABD /* BooksTableViewController.swift */; };
                4C7D649C1B31F18C00F0AC3A /* SampleBooks.swift in Sources */ = {isa = PBXBuildFile; fileRef = 4C7D649B1B31F18C00F0AC3A /* SampleBooks.swift */; };
```

After doing the above patch it runs just fine in the simulator. However, running on the device fails with:

```
Incident Identifier: 48307A54-0E0A-469F-9D0B-6023AA8FCD5A
CrashReporter Key:   da830e78afb6efd9414121b515e213ca5f5a8475
Hardware Model:      iPad5,3
Process:             Sample [607]
Path:                /private/var/mobile/Containers/Bundle/Application/1A0EE652-C1C4-45DE-968C-C8BEB5623B58/Sample.app/Sample
Identifier:          com.sample
Version:             1 (1.0)
Code Type:           ARM-64 (Native)
Parent Process:      launchd [1]

Date/Time:           2015-06-24 09:34:46.046 -0400
Launch Time:         2015-06-24 09:34:45.790 -0400
OS Version:          iOS 8.3 (12F69)
Report Version:      105

Exception Type:  EXC_BREAKPOINT (SIGTRAP)
Exception Codes: 0x0000000000000001, 0x0000000120059088
Triggered by Thread:  0

Dyld Error Message:
  Library not loaded: @rpath/Pods_Sample.framework/Pods_Sample
  Referenced from: /private/var/mobile/Containers/Bundle/Application/1A0EE652-C1C4-45DE-968C-C8BEB5623B58/Sample.app/Sample
  Reason: image not found
  Dyld Version: 353.12

Binary Images:
0x120058000 - 0x12007ffff dyld arm64  <75c62bbe28b13fcd91014f15139742dc> /usr/lib/dyld
```

Then I tried disabling Bitcode by applying this patch:

```
diff --git a/Sample.xcodeproj/project.pbxproj b/Sample.xcodeproj/project.pbxproj
index 52cf570..fb9b5f6 100644
--- a/Sample.xcodeproj/project.pbxproj
+++ b/Sample.xcodeproj/project.pbxproj
@@ -643,6 +643,7 @@
                                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
                                CLANG_ENABLE_MODULES = YES;
                                CODE_SIGN_IDENTITY = "iPhone Distribution: Science Applications International Corporation (ENT)";
+                               ENABLE_BITCODE = NO;
                                INFOPLIST_FILE = Sample/Info.plist;
                                IPHONEOS_DEPLOYMENT_TARGET = 8.3;
                                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
@@ -661,6 +662,7 @@
                                ASSETCATALOG_COMPILER_APPICON_NAME = AppIcon;
                                CLANG_ENABLE_MODULES = YES;
                                CODE_SIGN_IDENTITY = "iPhone Distribution: Science Applications International Corporation (ENT)";
+                               ENABLE_BITCODE = NO;
                                INFOPLIST_FILE = Sample/Info.plist;
                                IPHONEOS_DEPLOYMENT_TARGET = 8.3;
                                LD_RUNPATH_SEARCH_PATHS = "$(inherited) @executable_path/Frameworks";
```

Same crash log. Is there something else that I missing?

**Comment by neonichu** [comment] 2015-06-24 14:01
@RLovelett you should try to keep the framework weak linked and disable bitcode.

**Comment by RLovelett** [comment] 2015-06-24 15:14
@neonichu that seems to have done the trick. Thanks.

**Comment by segiddins** [comment] 2015-06-24 16:47
@RLovelett that beta 2 crash is caused by https://github.com/CocoaPods/CocoaPods/issues/3723

**Comment by mikewalkerjr** [comment] 2015-07-10 14:57
I disabled bitcode and now I'm getting:

dyld: Symbol not found: __TMdVSS5Index
  Referenced from: /private/var/mobile/Containers/Bundle/Application/6D846190-6DF6-447E-9B1C-BBDB4C7A0D2E/BiggerCity.app/Frameworks/Alamofire.framework/Alamofire
  Expected in: /private/var/mobile/Containers/Bundle/Application/6D846190-6DF6-447E-9B1C-BBDB4C7A0D2E/BiggerCity.app/Frameworks/libswiftCore.dylib
 in /private/var/mobile/Containers/Bundle/Application/6D846190-6DF6-447E-9B1C-BBDB4C7A0D2E/BiggerCity.app/Frameworks/Alamofire.framework/Alamofire

**Comment by deemadden** [comment] 2015-07-23 16:30
Still seeing the same problem in beta 4, with SnapKit installed in a project as a pod.

**Comment by edwardvalentini** [comment] 2015-07-26 23:42
+1

**Comment by iltercengiz** [comment] 2015-08-02 20:45
+1 @deemadden.
Same here with Alamofire.
I also have a setup that includes a framework target. App target uses that framework and Alamofire is linked to that framework. Unless I disable bitcode in all of the targets (in this case, Alamofire, Pods, Custom Framework, App), I can't run it on device.
P.S. both the framework and the app is Swift projects.

**Comment by aaronhuisinga** [comment] 2015-08-03 01:56
@iltercengiz How did you go about disabling bitcode for the frameworks like Alamofire? I got it disabled for my app and Pods, but still get the error from iTunes Connect.

**Comment by neonichu** [comment] 2015-08-03 06:43
See #3744 for development on this. I'm going to lock this issue, since we don't need more info on it.

**Comment by neonichu** [comment] 2015-09-22 19:56
Since Xcode 7 beta 5, weak linking and bitcode are compatible, so this issue can be closed.

**Closed by neonichu** 2015-09-22 19:56 UTC
