### ISSUE TITLE
Unable to generate Archive which will show in Organizer (archive is corrupted) after using Swift Pods

### ISSUE THREAD

**Issue by TosinAF** [CocoaPods/CocoaPods#3240] opened 2015-03-09 05:32 UTC
I have tried everything. 

Once, I add a swift pod to my app, It will Build & Archive but will generate a corrupt archive.
I am using 0.36 RC with Xcode 6.1.1 & Deployment target of 8.0

I downloaded arsty eiolodn which archived successfully in my environment. 
I compared build settings, but could not find any major difference

Other Solutions Tried: -
Checking for skip install

EDIT: - Added a dynamic Framework manually & that worked. So it's deffs an issue with cocoapods. I understand its in beta but Im trying to figure whats different between my project & the Arsty Eiolodn

If you want the sample project to try, I can email it if needed. Would appreciate any help. I have a spent a week on this.

**Comment by segiddins** [comment] 2015-03-10 16:48
Sharing a sample project would definitely be a huge help.

**Comment by mono0926** [comment] 2015-04-13 01:36
Me, too.

**Comment by bonokite** [comment] 2015-04-16 15:36
+1

I can't generate any valid archive on my project. Archiving works correctly but the file never appears on the organizer, I must go to the Finder and find it by myself. If I try to open it by a double-click, Xcode complains and prompts me with an 'archive is corrupted or unreadable' message.

This issue is quite easy to be reproduced. Just create a new project and then add a watch app target. Include one single framework on your podfile for both iphone and watch app targets. Now if you try to archive you'll see that the file never appears on the organizer when the process finishes.

**Comment by mono0926** [comment] 2015-04-23 08:10
In my case, #3361 doesn't resolve the problem...

**Comment by marcpalmer** [comment] 2015-05-03 11:43
I also have this problem. Currently the build is also duplicating my pods frameworks e.g. in my today and watchkit extensions, as well as my own dynamic frameworks. Interestingly they are not in the main app.

Also... there are two copies of the swift dylibs, one in the app and one in one of my extensions.

**Comment by andreamazz** [comment] 2015-05-07 13:27
FWIW the problem has to do with extensions, as mentioned in #3200

**Comment by marcpalmer** [comment] 2015-05-07 16:00
Yes. Removing all cocoa dependencies from my extensions/frameworks, the app Archives and appears in Organizer. I had to remove all pods from extensions sadly.

**Comment by mrackwitz** [comment] 2015-05-11 10:10
There's work going on to fix this in #3550 - but it's not quite ready, yet.

**Comment by andreamazz** [comment] 2015-05-11 10:15
Great! I'll be happy to test it.

**Comment by neonichu** [comment] 2015-07-01 13:17
We can close this, since #3550 has been merged to master.

**Closed by neonichu** 2015-07-01 13:17 UTC
Labels: s1:awaiting input
