### ISSUE TITLE
Pods copy resource script overrides default xcasset bahaviour

### ISSUE THREAD

**Issue by barksten** [CocoaPods/CocoaPods#1546] opened 2013-11-05 06:50 UTC
I have a project with different "themes" that are used for different xcode targets. For the themes I have two xcasset catalogs, one with red graphics and one with green graphics. Inside the bundles the files are named the same (so that I can simply use background.png as image name and get the correct color). Which xcasset that get copied is determined by the target membership (and ultimately by the build step "copy bundle resources").
Since cocoa pods version 0.27 I've noticed that there is a new entry in the copy pods resource script. That will cause my red graphics copied by the standard xcode build step to be replaced with the green graphics copied by the cocoa pods copy resources build step.

**Comment by anivaros** [comment] 2015-02-03 12:55
Same issue on version 0.36.0.beta.2 :(
![screen shot 2015-02-03 at 15 55 05](https://cloud.githubusercontent.com/assets/873387/6020450/17f4c2c8-abbd-11e4-8413-1c705af06cfc.png)

**Comment by Tibbs** [comment] 2015-02-18 10:53
I have the same issue. Moving the Copy Bundle Resources to the end of the list works only if the project is cleaned first. I noticed it is only an issue with assets which are referenced but not copied to the project. I added the problematic asset again, this time I copied it and it works fine.
I just started using pods. To be honest, I don't know why it is not a major issue for most people

**Comment by T-Pham** [comment] 2015-02-24 05:23
I had the same issue and found a workaround as follow.
Since the Pods' copy resource script copies incorrect image files, we should move the `Copy Bundle Resources` build phrase after the `Copy Pods Resources` build phrase so that any incorrect image file copied by Pods will be replaced with the correct ones. Unfortunately (or not), Xcode checks if the files are modified before copying them, so the trick only works if we clean the project before each build. Thus, we have to make Xcode think that the image files have been modified to force it to copy them. We can do that by adding a `New Run Script Phrase` and `touch` all the files we want Xcode to copy with the script `find SomeDirectory -name "*.xcassets" -exec touch {} \+;`. Remember to replace SomeDirectory with the directory that contains your xcassets files.

![screen shot 2015-02-24 at 12 11 11 pm](https://cloud.githubusercontent.com/assets/1930855/6343688/bc4a2008-bc1f-11e4-8884-04db05b8a1a8.png)

**Comment by marcocattai** [comment] 2015-02-24 18:03
Any news on this issue?

**Comment by Tibbs** [comment] 2015-02-25 13:56
@T-Pham nice touch! It works like a charm.
I hope it will be officially fixed soon

**Comment by nevstad** [comment] 2015-03-04 10:47
Any updates?

**Comment by AliSoftware** [comment] 2015-03-12 01:53
I'll try to work on a proper solution soon.

**Comment by sashagood** [comment] 2015-03-12 12:30
Hi! Any news?

**Comment by AliSoftware** [comment] 2015-03-12 14:35
When I said "soon" yesterday, I only meant "next week or so" :smile: 

The idea we want to implement is to stop managing assets with the `pod-resources.sh` script. Instead we will:
* add a reference to each pod's `xcassets` to the user's project (inside that `Pods/` group we already add for `xcconfig` files) at integration time (when you run `pod install`)
* add those `xcassets` to the appropriate app's targets (according to what is configured in your `Podfile`)
* then let Xcode do the job of selecting the proper `xcasset` catalogs for us according to the target being built


It would be greatly appreciated if you guys could at least provide sample projects (ideally ones suited for unit tests / integration specs) for the various configurations you encountered, so we can directly use them as non-regression specs to test this future new way to integrate assets.

**Comment by taberrr** [comment] 2015-03-19 21:00
Re-ordering the Copy Pods Resources phase didn't work here (I suspect because one of our pods contains .xcassets) so I ended up using @zygoat's solution, which seems to work!

@AliSoftware that sounds fancy! In case it helps any w/ testing, the pod we're installing that contains .xcassets is: https://github.com/AgileBits/onepassword-app-extension

**Comment by AliSoftware** [comment] 2015-03-19 23:02
@taberrr Thx! That's actually the one I'm using for testing that too.

Feel free to test out the `ali-xcassets-1546` branch of CocoaPods to test it out with your project. That's still WIP because I still need to add specs/unit tests and cleanup some code when one removes a pod, but this branch should be pretty close to working now.

**Comment by taberrr** [comment] 2015-03-20 00:54
@AliSoftware awesome man! Love me some 1Password. Looking good over here, just installed it to a quick test project:

    [!] Please close any current Xcode sessions and use `Skap.xcworkspace` for this project from now on.
    - User targets being integrated: ["Skap"]
    - Pod Targets = ["Pods-Skap-1PasswordExtension", "Pods-Skap-AFNetworking"]
        - Adding /Volumes/taberdrive/docs/iphone/Skap/Pods/1PasswordExtension/1Password.xcassets to user project
        - Adding 1Password.xcassets to targets ["Skap"]
    ==> User project dirty? true```

No need for any additional fancy shell scripts! 👍

**Comment by TokyoBirdy** [comment] 2015-03-20 10:43
I wrote a script to fix this

**Comment by problame** [comment] 2015-03-26 16:52
As a temporary fix, you can easily fix the `Pods-resources.sh` script generated by CocoaPods. I don't have the time to dig into the CocoaPods source but I guess this could be an approach to fixing the underlying problem.

```
# Pods/Target\ Support\ Files/Pods/Pods-resources.sh
  ...
  install_resource()
  {
    case $1 in
    ...
    *.xcassets)
-   	XCASSET_FILES="${PODS_ROOT}/$XCASSET_FILES '$1'"
+   	XCASSET_FILES="$XCASSET_FILES '$1'"
        ;;
		...
```

**Comment by kishinmanglani** [comment] 2015-04-06 13:49
Does 0.36.1 or 0.36.2 change any of this? Is the above still the best solution?

**Comment by irace** [comment] 2015-04-07 14:55
Still seeing this problem with 0.36.3.

**Comment by irace** [comment] 2015-04-07 15:33
@AliSoftware Your branch seemed to fix our issues. Do you expect it to go into, say, a 0.36.4 release?

**Comment by irace** [comment] 2015-04-07 16:30
@AliSoftware I may have spoke too soon, actually. It looks like running `pod install` using your branch results in a new duplicate reference to my `.xcdatamodeld` file being added to the Xcode project each time.

**Comment by AliSoftware** [comment] 2015-04-07 16:38
@irace You mean that the first time you run `pod install` you got your pod's `.xcdatamodel` file added and present only once, but if you re-run `pod install` you got it added again?

**Comment by irace** [comment] 2015-04-07 16:41
@AliSoftware That seems to be the case, yes.

**Comment by frandelarosa** [comment] 2015-04-10 07:27
Any news on this? Can't run the project properly without to do clean before. I tried to use the fix proposed by @T-Pham but I'm not sure if I set it correctly. Maybe something is wrong with my project path.

**Comment by lukemelia** [comment] 2015-04-15 23:52
Considering the commit message that closed this, should this issue be reopened until a fix is confirmed?

**Comment by slhodson969** [comment] 2015-04-16 12:00
None of the scripts seem to be working for me. I am meant to be uploading an app to Apple today but the iPad target ignores its assets folder so has no app icon.

Is there an updated Cocoapods version that has this fix in?

**Comment by sashagood** [comment] 2015-04-16 12:24
Is someone have any news? Can't use pods because of this bug.

**Comment by wiistriker** [comment] 2015-04-16 14:14
Same error for me

**Comment by orta** [comment] 2015-04-16 14:38
You're welcome to test and see if master fixes your problem, https://github.com/CocoaPods/guides.cocoapods.org/blob/gemfile/source/using/a-gemfile.html.md

**Comment by AliSoftware** [comment] 2015-04-16 15:13
A bit of update: We will provide a fix in an upcoming release, that won't properly fix this #1546 (white-label apps, a.k.a multiple xcassets in various targets in the user's project), but that will fix cases for pods with xcassets.

The matter at hand with the current 1546 issue is way more complex that we first imagined, and will require a more complex approach. I already tried a bunch of ideas in the past month, sadly those refactoring and trials failed to cover every use case, so we still need to decide which way we'll be going from there to fix 1546 with a better, proper solution.

**Comment by kishinmanglani** [comment] 2015-04-16 20:30
Is swapping the build phase order still a reliable fix?

**Comment by kylef** [comment] 2015-04-16 20:37
This wasn't meant to be closed.

**Comment by x2on** [comment] 2015-04-17 08:18
So it looks like 0.36.4 fixed the issue for me for using Watch Extension and CocoaPods.

**Comment by niveus** [comment] 2015-05-21 23:11
Still having this issue in 0.37.1. Fixed it reordering the build phases and adding @T-Pham 's script phase: `find ${PROJECT_DIR} -name "*.xcassets" -exec touch {} \+;` before the Copy Bundle Resources phase

**Comment by AlbertTong** [comment] 2015-06-09 04:08
Used to be an issue previously but hasn't been an issue since upgrading to 0.37.1 (was on 0.34 previously with a manual workaround to the Pods-resources.sh file)

**Comment by onmyway133** [comment] 2015-06-30 04:35
Move `Copy Pods Resources` before `Copy Bundle Resources` fixes for me

**Comment by nobre84** [comment] 2015-09-09 20:40
@AliSoftware any news on this? Your approach looked fine as actool should only try to compile user assets with the right target ownership. I have a white-label project idea stalled because of this one, I may contribute a sample project of my use case if you need it.

**Comment by AliSoftware** [comment] 2015-09-09 20:43
My work was abandoned because it couldn't work at all with
configuration-dependent pods so didn't fit all the cases
Le mer. 9 sept. 2015 à 22:40, Rafael Nobre <notifications@github.com> a
écrit :

**Comment by nobre84** [comment] 2015-09-09 21:11
I see. I realized that your efforts tried to fix assets coming from Pods, while the issue with multiple assets in user targets being broken is just a side effect of the current pods-resources script, am I right on these conclusions? What would be the simplest work-around to allow this white label use case to work?

**Comment by a13xb** [comment] 2016-01-11 12:30
I have ran into the same problem. In our project we need to support all of these:

1. shared user asset catalogs
2. per-target user asset catalos
3. pods with asset catalogs

I ended up fudging the resource script from [Podfile post-install hook](https://gist.github.com/a13xb/cf07c19c75ec5b4709a9).

The downside is that you have to re-run `pod install` if application's asset catalogs are added or removed. But it almost never happens in our case (YMMV). Pods asset catalogs  change more often, so I've put it in the post-install hook, as opposed to a standalone script. It's dirty but it works.

**Comment by neonichu** [comment] 2016-05-02 08:34
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Closed by neonichu** 2016-05-02 08:34 UTC
Labels: d2:moderate, s2:confirmed, t2:defect

**Comment by scinfu** [comment] 2019-09-27 08:51
Same error in pod 1.7.5.
I tested and found is cocoapods.
