### ISSUE TITLE
Git download (cloning) takes ages

### ISSUE THREAD

**Issue by zxcq99** [CocoaPods/CocoaPods#4540] opened 2015-11-13 10:54 UTC
Hey,

My git repository with pods is quite heavy and it takes forever to do a `pod update`. It used to work fine (0.36.4 I believe was the last that worked fast). Is there any way to clone repository only once if few pods are cloned from same repository/commit ? It would speed it up this process a lot.

Thanks :)

**Comment by segiddins** [comment] 2015-11-13 13:26
Can you share a podfile we can use to reproduce? Otherwise, there's not really much we can go on with "it's slow". Thanks!

**Comment by zxcq99** [comment] 2015-11-13 15:30
Can't really share an exact Podfile since it's private and I am not allowed to share VPN so you could connect to it anyway. Here is an example how it looks like:

`source 'https://github.com/CocoaPods/Specs.git'`
`platform :ios, '7.0'`
`workspace 'MyProjectName.xcworkspace'`
`xcodeproj 'MyProjectName/MyProjectName.xcodeproj'`
`pod 'Pod1', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/rep-common.git'`
`pod 'Pod2', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/rep-common.git'`
`pod 'Pod3', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/rep-common.git'`
`pod 'Pod4', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/framework.git', :branch => 'develop'`
`pod 'Pod5', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/framework.git', :branch => 'develop'`
`pod 'Pod6', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/framework.git', :branch => 'develop'`
`pod 'Pod7', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/framework.git', :branch => 'develop'`
`pod 'Pod8', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/framework.git', :branch => 'develop'`
`pod 'Pod9', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/rep-common.git'`
`pod 'Pod10', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/rep-common.git'`
`pod 'Pod11', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/rep-common.git'`
`pod 'Pod12', :git => 'git@gitlab.dev.exyz.biz:xyz-ios/rep-common.git'`

**Comment by segiddins** [comment] 2015-11-13 16:18
Ah so it's just that the repo is being downloaded multiple times? Fixing that would require a significant refactor to the download cache which isn't likely to happen soon, but I'd be happy to review a PR that attempts to do it!

**Comment by zxcq99** [comment] 2015-11-13 16:33
Yes, that's my issue ^^ It's quite annoying when your repo is so big. I hope there is someone willing to do it :)

**Comment by segiddins** [comment] 2015-11-13 17:26
Actually thinking this over, the cache should already be caching every pod the first time it downloads it, it's just a matter of then having something recognize that the sha just cached is going to be the same one that's downloaded next.

**Comment by zxcq99** [comment] 2015-11-13 17:39
What has changed since 0.36.0 though that made this process so much slower? It takes about 10 mins to `pod update` with 0.36.0 and like an hour with 0.39.0.

**Comment by segiddins** [comment] 2015-11-13 17:43
No clue, and I'd need a podfile I can install to really be able to debug.

**Comment by zxcq99** [comment] 2015-11-18 14:49
Is it possible that SSH is slowing it down so much? I heard that Gitlab + ssh causes such issues sometimes but I am not sure if I should believe that.

**Comment by timbodeit** [comment] 2015-11-23 01:09
@zxcq99 Why would you want to collect multiple pods Pods in a single 500MB repository?
Why not give every Pod its own repo?

**Comment by zxcq99** [comment] 2015-11-25 07:48
@timbodeit It's not in my decision, that's how my company does that.

**Comment by zxcq99** [comment] 2015-12-07 10:41
@segiddins Did some tests and seems like it's downloading the repositories reall fast (takes 3 sec to download (clone) each pod but then it's stuck like that: 
![zrzut ekranu 2015-12-07 o 11 39 36](https://cloud.githubusercontent.com/assets/3925166/11624922/66805ee6-9cd7-11e5-8da9-d454346d28db.png)
for like a 3 minutes. Any way I could debug it myself? Since I can't share the podspec with you :(

**Comment by orta** [comment] 2015-12-07 11:46
If you run the command with `--verbose` at the end, you should get some more information about what's going on under the hood.

**Comment by segiddins** [comment] 2016-01-24 20:23
Closing due to lack of posted verbose output.

**Closed by segiddins** 2016-01-24 20:23 UTC
Labels: d2:moderate, t1:enhancement

**Comment by braysonjohn148** [comment] 2020-01-21 16:24
[cocoapods] anybody with this ziped folder https://github.com/CocoaPods/Specs to provide us the link, taking long to clone from git. Please help, trying to download for month now.

**Comment by timbodeit** [comment] 2020-05-22 13:46
@braysonjohn148 I don't think your question relates to this issue. Are you looking for a zip archive of the current master of the Specs repo? Does the "Download Zip" button not do what you need? <img width="495" alt="Screenshot 2020-05-22 at 15 44 44" src="https://user-images.githubusercontent.com/4222754/82674145-2b372e80-9c43-11ea-854d-33bb35017e38.png">

Have you tried doing a shallow clone to speed up the download while preserving git functionality?

**Comment by amorde** [comment] 2020-05-23 02:10
Hey folks, we recommend using the CDN repo instead of cloning the master repo. This removes the requirement of downloading everything.

See https://blog.cocoapods.org/CocoaPods-1.7.2/ for details. To use it in your project, add this to your Podfile:

```ruby
source 'https://cdn.cocoapods.org'`
```
