### ISSUE TITLE
Podfile.lock SPEC CHECKSUMS sometimes contains quotes

### ISSUE THREAD

**Issue by k06a** [CocoaPods/CocoaPods#5585] opened 2016-06-29 18:33 UTC
Having opposite diffs with some colleagues after `pod install`:
```
-  PINCache: '078426d356ab95ef875e9e62e5c35a2ea3333c28'
+  PINCache: 078426d356ab95ef875e9e62e5c35a2ea3333c28
```
and:
```
-  PINCache: 078426d356ab95ef875e9e62e5c35a2ea3333c28
+  PINCache: '078426d356ab95ef875e9e62e5c35a2ea3333c28'
```

We are all using CocoaPods 1.0.1. What does this quotes means?

**Comment by orta** [comment] 2016-06-29 21:07
I think this is a dupe of https://github.com/CocoaPods/CocoaPods/issues/3452 - you have different versions of Ruby ( and psyche ) between colleagues.

**Closed by orta** 2016-06-29 21:07 UTC

**Comment by tomassliz** [comment] 2016-11-28 15:24
@orta I have the same problem here and we all have the same version of Ruby. So It's not the source of the problem. We're using version 1.1.1

**Comment by stefan-sedlak** [comment] 2016-11-30 13:29
We synced psych gem version. We produce the same result now. Strange is that old pods are without quotes new pods are quoted:
  KIF: '082eb65279e51c3092923802849eb796a04982ab'
  libextobjc: a650fc1bf489a3d3a9bc2e621efa3e1006fc5471

**Comment by k06a** [comment] 2016-11-30 20:00
@stefan-sedlak thats because of first zero oh hash :)

**Comment by k06a** [comment] 2016-11-30 20:01
@stefan-sedlak read this thread for answer why this will not be fixed: https://github.com/ruby/psych/issues/232

**Comment by stefan-sedlak** [comment] 2016-11-30 20:12
@k06a thanks, first zero made my day. I hope that psych will improve to quote hashes starting with 1 exclusively on 1st April.

**Comment by keith** [comment] 2017-01-18 22:04
We've fixed this by including the newest version of psych in our Gemfile. This way at least all team members have the version that quotes and we don't conflict with each other.

**Comment by ajwhite** [comment] 2017-02-24 20:18
@keith mind sharing a sample of what this looks like in a project using cocoapods?

**Comment by orta** [comment] 2017-02-25 14:30
Psyche is a ruby gem, you would need to learn how [to use a Gemfile](https://duckduckgo.com/?q=how+do+I+use+a+gemfile&t=osx&ia=web#) to make it work with CocoaPods.

**Comment by keith** [comment] 2017-02-25 19:47
In our case we have a `Gemfile` like this:

```ruby
source 'https://rubygems.org'

gem 'cocoapods', '1.2.0'
gem 'psych'
```

And then when you `bundle install` you will check in your `Gemfile` and `Gemfile.lock`. Then instead of `pod install` you need to run `bundle exec pod install`. The version of psych will be locked in the `Gemfile.lock` and will be the same for all users.

See the link from @orta for more details.

**Comment by anwright52** [comment] 2017-12-05 02:22
Is it possible for Cocoapods to specify the version of psych that it uses?
