### ISSUE TITLE
Upgrading to 0.36.0.rc.1 from 0.35 with use_frameworks! breaks while compiling a non-arc compatible Pod

### ISSUE THREAD

**Issue by bejar37** [CocoaPods/CocoaPods#3246] opened 2015-03-10 18:16 UTC
I'm specifically referring to [chrisdevereux/Slash](https://github.com/chrisdevereux/Slash). That pod defines a struct which includes an Obj-C pointer, which is non-ARC compatible. The Pod used to compile fine in the previous version. I've tried adding `-fno-objc-arc` to the framework build settings, as well as setting the `Objective-C Automatic Reference Counting` flag to `NO` in the same place.

**Comment by segiddins** [comment] 2015-03-10 19:43
The problem with Slash may be that its header files are included twice, in both the arc and no-arc subspecs?

**Comment by bejar37** [comment] 2015-03-10 19:55
Yeah, even removing the doubled header files I'm still getting the compilation error. I'm pretty sure the subspecs defined there are broken, since at least one of the headers included in the arc version includes things that are non-arc compatible.

My issue though is that this built and worked fine under CocoaPods 0.35 / without frameworks, but now no longer works. How can I specify to build this framework without ARC?

**Comment by samdmarshall** [comment] 2015-03-10 21:29
Can you upload a sample of this, I couldn't reproduce this as described on 0.36.0.rc.1

**Comment by bejar37** [comment] 2015-03-11 15:02
OK, I'll try to get a minimal example and post links to them here. Thanks!

**Comment by segiddins** [comment] 2015-10-05 22:14
Closing due to lack of example project.

**Closed by segiddins** 2015-10-05 22:14 UTC
