### ISSUE TITLE
Not able to get my pod in cocoapods.org search list

### ISSUE THREAD

**Issue by devanshvyas** [CocoaPods/CocoaPods#9448] opened 2020-01-01 05:37 UTC
# Report
Not able to get my pod in cocoapods.org search list

## What did you do?
Run `pod trunk push`

## What did you expect to happen?
After a day of publishing pod it should be displayed in search list on cocoapods website.

## What happened instead?
Not getting my pod in search list

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.2 (19C57)
       Xcode : 11.3 (11C29)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ 935921ccce2f8a0f688157a04776f40fee37fa69
               TimelineView - git - https://github.com/devanshvyas/TimelineView @ 6491f632fc024decf018666bbc0a240ed71ac1f8
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/Cellar/cocoapods/1.8.4/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'TimelineView' do
  # Comment the next line if you don't want to use dynamic frameworks
  use_frameworks!

  # Pods for TimelineView

end
```
## Project that demonstrates the issue
Git: https://github.com/devanshvyas/TimelineView

**Comment by dnkoutso** [comment] 2020-01-01 06:30
This is a known issue with our search indexer for a while that is broken. New pods are not showing up in search.

Duplicate of #9366

**Closed by dnkoutso** 2020-01-01 06:30 UTC
