### ISSUE TITLE
Fatal error: Extra content at the end of the document at :15917.

### ISSUE THREAD

**Issue by virendramobisoft** [CocoaPods/CocoaPods#6510] opened 2017-02-23 08:39 UTC
### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.8
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.9.2
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 216ce53d952b3ab24beefd6b7718fbaec9f4e9e1
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, ‘9.0’

target 'abcdefg' do
    
    pod 'AFNetworking', '~> 3.1.0'
    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'FBSDKShareKit'
    pod 'FBSDKMessengerShareKit'
    pod 'PureLayout', '~> 2.0.5'
    pod 'FMDB', '~> 2.5'
#    pod 'FMDB/FTS'   # FMDB with FTS
#    pod 'FMDB/standalone'   # FMDB with latest SQLite amalgamation source
#    pod 'FMDB/standalone/FTS'   # FMDB with latest SQLite amalgamation source and FTS
#    pod 'FMDB/SQLCipher'   # FMDB with SQLCipher
    pod 'Flurry-iOS-SDK', '~> 7.3.0'
    pod 'Parse', '~> 1.13.0'
#    pod 'IQKeyboardManager'
    pod 'Branch'
    pod 'Google/SignIn’
    pod 'libPhoneNumber-iOS', '~> 0.8'
    pod 'KeenClient', '~>3.5.2'
    pod 'Braintree', '~>4.3.0'
    pod 'Braintree/DataCollector'
    pod 'Braintree/PayPalDataCollector'
    pod 'IQDropDownTextField', '~> 1.0'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'SAMKeychain'
    pod 'SDWebImage', '~>4.0.0-beta2'
end

target 'abcdefgTests' do
    
end
```

### Error

```
CFFormatError - invalid XML: Fatal error: Extra content at the end of the document at :15917.
/Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.5/lib/cfpropertylist/rbLibXMLParser.rb:26:in `rescue in load'
/Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.5/lib/cfpropertylist/rbLibXMLParser.rb:13:in `load'
/Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.5/lib/cfpropertylist/rbCFPropertyList.rb:337:in `load_str'
/Library/Ruby/Gems/2.0.0/gems/CFPropertyList-2.3.5/lib/cfpropertylist/rbCFPropertyList.rb:255:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/plist.rb:25:in `new'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/plist.rb:25:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:851:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:850:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:850:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:845:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer/analyzer.rb:66:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:236:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command/update.rb:81:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.2.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by orta** [comment] 2017-02-23 09:04
It looks like CocoaPods can't read your Xcodeproject's xml file, does it open in Xcode?

**Comment by virendramobisoft** [comment] 2017-02-23 09:05
Yes

**Comment by virendramobisoft** [comment] 2017-02-23 09:08
Now I am trying the fresh install of gem and cocoapods as given on https://bhaveshdhaduk.wordpress.com/2014/05/07/cocoapods-uninstall-and-install/ .

**Comment by virendramobisoft** [comment] 2017-02-23 09:31
Still not resolved..

**Comment by benasher44** [comment] 2017-03-01 15:00
Could you post a sample project? That'd go a long way to helping us debug this. Thanks!

**Comment by benasher44** [comment] 2017-03-11 17:21
@virendramobisoft could you maybe post the end of your project file, given the error output seems to indicate that's where the issue is?

**Comment by virendramobisoft** [comment] 2017-03-13 05:46
@benasher44 Sorry but I am not able to reproduce this issue now. What I did to get rid of this is, I deleted the entire local project repository and did a complete new checkout from the git repository.

**Comment by benasher44** [comment] 2017-03-13 12:40
Huh okay. Well I'm glad you got it resolved! I'm going to close this then, since there's nothing else to do here. Please reopen if you find it happens again. Have a great day!

**Closed by benasher44** 2017-03-13 12:40 UTC
Labels: s1:awaiting input
