### ISSUE TITLE
Pod not showing in search

### ISSUE THREAD

**Issue by admin-graycompany** [CocoaPods/CocoaPods#9201] opened 2019-09-27 21:26 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk push GrayCore.podspec`

## What did you expect to happen?

Update Pod and show it in search

## What happened instead?

Pod was updated but it is not showing in search

### Stack

```
   CocoaPods : 1.8.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 10.3 (10G8)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : graycore-ios-specs - git - https://github.com/admin-graycompany/graycore-ios-specs.git @ 134b2d1dae80d4bc7aee464ad20f7f2e2970b96c
               master - git - https://github.com/CocoaPods/Specs.git @ 06160247b7ec78415f93a2abbbd59e80dad70992
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-keys        : 2.1.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment] 2019-09-27 22:20
Duplicate of https://github.com/CocoaPods/cocoapods.org/issues/424. It is a known issue that new pods are not being indexed.

**Closed by dnkoutso** 2019-09-27 22:20 UTC
