### ISSUE TITLE
Pod update single pod not working properly 

### ISSUE THREAD

**Issue by teressaeid** [CocoaPods/CocoaPods#8070] opened 2018-09-01 20:10 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
e.g. Run `pod update EPSignature`

## What did you expect to happen?

Update the EPSignature branch and leave other dependencies as is.

## What happened instead?

It looks like it updated all the dependencies instead of one. 

## CocoaPods Environment

1.5.3 

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.6 (17G65)
       Xcode : 9.4.1 (9F2000)
         Git : git version 2.14.1
Ruby lib dir : /usr/local/Cellar/ruby/2.4.2/lib
Repositories : bitbucket-halogenmobile-kclib-swift-kcpnetworkmanager - https://bitbucket.org/halogenmobile/kclib-swift-kcpnetworkmanager.git @ 917b3c31cf287eab2151beaddc2753363d4afbf7
               bitbucket-halogenmobile-sof-pod_spec_osx-ios - https://bitbucket.org/halogenmobile/sof-pod_spec_osx-ios.git @ e0ff91f1ed17525570d35cefc44634e416856614
               master - https://github.com/CocoaPods/Specs.git @ 1106685af233a5ff84fb425bd56f7e4915cf43c9
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
slather               : 2.4.5
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
# source 'git@github.com:RobotsAndPencils/RNPPrivateSpecs.git'
# uncomment if you want to use any RNP private specs ex RPNX, MightyAtom, RoboKit - https://github.com/RobotsAndPencils/RNPPrivateSpecs/tree/master/Specs

platform :ios, '11.0'
install! 'cocoapods', :deterministic_uuids => false
use_frameworks!
inhibit_all_warnings!

# TODO: After setting up your project run the `pod outdated` command to see if any newer versions have been released since this template was created. If they are out of date then update here.

# Its best to specify at the major-minor versions so the project can pick up minor changes as they get released. Note that if you don't specify any version information then you could pick up a major version upgrade and woe be to you... or if you lock it down to a point release then you'll never get updates.

target :Humanity do
  pod 'Astro', '~> 5.0'
  pod 'KeychainAccess', '~> 3.1'
  pod 'SVProgressHUD', '~> 2.2'
  pod 'TPKeyboardAvoiding', '~> 1.3'
  
  # CrashReporting
  pod 'HockeySDK', '~> 5.0'
  
  # Networking
  pod 'Alamofire', '~> 4.7'
  pod 'AlamofireImage', '~> 3.3'
  pod 'PromiseKit', '~> 6.2'
  pod 'AWSCore', '~> 2.6'
  pod 'AWSCognitoIdentityProvider', '~> 2.6'

  # Testing / CodeGen
  pod 'Fakery', '~> 3.0'
  pod 'Sourcery', '~> 0.9'

  # Debugging / Analysis
  pod 'SwiftLint', '~> 0.22'

  pod 'APNGKit', :git => 'https://github.com/MattKiazyk/APNGKit' #Changes in https://github.com/onevcat/APNGKit/pull/76
  pod 'GSKStretchyHeaderView'
  pod 'lottie-ios'
  pod 'XCDYouTubeKit'
  pod 'Hero'
  pod 'Branch'
  pod 'UICircularProgressRing', :git => 'git@github.com:MattKiazyk/UICircularProgressRing.git' #adds shadow
  pod 'MediaWatermark', :git => 'https://github.com/teressaeid/media-watermark' #videooverlay
  pod 'EPSignature', :git => 'https://github.com/teressaeid/EPSignature' #signature
  pod 'CTKFlagPhoneNumber'
  pod 'Mixpanel-swift'
  
  target :HumanityTests do
    pod 'Quick', '~> 1.2'
    pod 'Nimble', '~> 7.0'
    pod 'OHHTTPStubs', '~> 6.0'
    pod 'OHHTTPStubs/Swift', '~> 6.0'
  end
end

# Until these pods upgrade to current version of Swift we force them into the previous version
post_install do |installer|
  previous_swift_version = '3.2'
  current_swift_version = '4.0'
  pods_written_with_previous_swift = []

  if pods_written_with_previous_swift != []
    installer.pods_project.targets.each do |target|
        if pods_written_with_previous_swift.include? target.name
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = previous_swift_version
          end
        else
          target.build_configurations.each do |config|
            config.build_settings['SWIFT_VERSION'] = current_swift_version
          end
        end
    end
  end

  # workaround to fix runtime warnings when running tests:
  #   "Class BITHockeyManager is implemented in both... One of the two will be used. Which one is undefined."
  # See: https://github.com/CocoaPods/CocoaPods/issues/7126#issuecomment-336160205
  sharedLibrary = installer.aggregate_targets.find { |aggregate_target| aggregate_target.name == 'Pods-Humanity' }
  installer.aggregate_targets.each do |aggregate_target|
    if aggregate_target.name == 'Pods-Humanity-HumanityTests'
      aggregate_target.xcconfigs.each do |config_name, config_file|
        sharedLibraryPodTargets = sharedLibrary.pod_targets
        aggregate_target.pod_targets.select { |pod_target| sharedLibraryPodTargets.include?(pod_target) }.each do |pod_target|
          pod_target.specs.each do |spec|
            frameworkPaths = unless spec.attributes_hash['ios'].nil? then spec.attributes_hash['ios']['vendored_frameworks'] else spec.attributes_hash['vendored_frameworks'] end || Set.new
            frameworkNames = Array(frameworkPaths).map(&:to_s).map do |filename|
              extension = File.extname filename
              File.basename filename, extension
            end
            frameworkNames.each do |name|
              config_file.frameworks.delete(name)
            end
          end
        end
        xcconfig_path = aggregate_target.xcconfig_path(config_name)
        config_file.save_as(xcconfig_path)
      end
    end
  end
end
```

## Project that demonstrates the issue

<img width="1188" alt="screenshot 2018-08-31 11 45 39" src="https://user-images.githubusercontent.com/3945814/44949516-5475b280-ae01-11e8-81c4-cb2b5fdbfadd.png">
<img width="1188" alt="screenshot 2018-08-31 11 45 50" src="https://user-images.githubusercontent.com/3945814/44949517-5475b280-ae01-11e8-9c9a-4e1cb11b5b13.png">

My teammates have the correct behavior, I did a fresh install of cocoapods on a new computer, same behavior.

I also tried a `cache clean`, and updated to the latest ruby.

Please help, I do not understand why this is happening.

Thank you!

**Comment by amorde** [comment] 2018-09-01 23:45
Hi @teressaeid,

I _think_ it wasn't actually updating all of the pods, it was just notifying that the source the pod came from changed. This was a bug that was fixed in #7883 

Can you try updating to `1.6.0.beta.1` and see if that fixes the issue? You can install it with `[sudo] gem install cocoapods --pre`

**Comment by amorde** [comment] 2018-09-02 01:40
Ah okay, thanks for trying the beta. Will need to look into it

**Comment by amorde** [comment] 2018-09-02 01:41
Could you upload a sample project? Since this relies on the current state of your project, I can't try to reproduce this myself unless I have something to test against

**Comment by amorde** [comment] 2018-09-02 01:48
I can confirm that it works as expected on a test project

**Comment by teressaeid** [comment] 2018-09-02 01:50
I don't have a test project handy, trying to find something on git? what are you testing against? I would want to test on it

**Comment by teressaeid** [comment] 2018-09-02 02:01
Okay I am using this https://github.com/spinfo/HistoriaApp_iOS 

I only wanted to update Yams but it installed the other instead of using

<img width="795" alt="screenshot 2018-09-01 22 00 18" src="https://user-images.githubusercontent.com/3945814/44951454-881d0080-ae32-11e8-9387-eaa31897ba0f.png">

**Comment by amorde** [comment] 2018-09-02 02:59
That project has the `Pods/` directory ignored, so when I clone it CocoaPods has to install every pod. Is it possible you're running into something similar? If your `Pods/` directory is not up to date, CocoaPods will re-install the version that's compatible with the `Podfile.lock`

**Comment by amorde** [comment] 2018-09-12 20:36
Received a project privately but am unable to repro - I'm going to close this but feel free to open another issue if you narrow down a reproducible example.

**Comment by allenhumphreys** [comment] 2018-09-13 16:05
@amorde This is happening to me too. I don't know if I'll have time to narrow it down, I will if I can. Just wanted to say it's not a unique case.

**Comment by teressaeid** [comment] 2018-09-13 16:17
@allenhumphreys Wondering if you run that same command on a zipped archive if it behaves properly, in my case it does (on a zipped archive). I think the root of the issue is with some GitHub config, but haven't been able to narrow it down =(

**Comment by amorde** [comment] 2018-09-13 17:01
Okay, I will re-open for now. If anyone can create an example that reproduces the issue that would be super helpful 🙏

**Comment by amorde** [comment] 2018-09-13 17:14
how are you including the private pod? ex. are you using a private spec repo or are you using something like `pod 'MyPod', :git => 'url_to_git_repo'`?

**Comment by allenhumphreys** [comment] 2018-09-13 17:15
Private spec repo

**Comment by genericwoods** [comment] 2018-09-13 18:17
Also private spec repo here

**Closed** 2019-02-07 07:01 UTC
Labels: s1:awaiting input
