### ISSUE TITLE
xcconfig LIBRARY_SEARCH_PATHS edited to remove "$(inherited)" when adding Google Analytics

### ISSUE THREAD

**Issue by zammbi** [CocoaPods/CocoaPods#3908] opened 2015-07-27 05:35 UTC
I was having build troubles and created this, but I believe it is a bug. 
http://stackoverflow.com/questions/31465465/adding-google-analytics-to-my-podfile-breaks-the-build-library-not-found

In my pod xcconfig file, the var "LIBRARY_SEARCH_PATHS" gets edited when I include Google Analytics and it removes "$(inherited)":

Example:
```LIBRARY_SEARCH_PATHS = 
"$(PODS_ROOT)/Google/Libraries" 
"$(PODS_ROOT)/Google/Libraries" 
"$(PODS_ROOT)/GoogleAnalytics/Libraries" 
"$(PODS_ROOT)/GoogleNetworkingUtilities/Libraries" 
"$(PODS_ROOT)/GoogleNetworkingUtilities/Libraries" 
"$(PODS_ROOT)/GoogleSymbolUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries" 
"$(PODS_ROOT)/GoogleUtilities/Libraries"```

**Comment by segiddins** [comment] 2015-07-27 05:36
Can guess that this happens because this is the only setting where we never explicitly prepend an `inherited` when generating the XCConfig

**Comment by neonichu** [comment] 2015-07-27 06:20
In any case, this should also be fixed in the upstream podspec, since there is no need to modify the library search path.

**Comment by segiddins** [comment] 2015-07-27 06:24
@neonichu no, this is a bug in the xcconfig we generate -- has nothing to do with the podspec being used

**Comment by neonichu** [comment] 2015-07-27 06:30
It's a bug, the given podspec is still wrong, though. It uses `library` for a vendor library, that's why it even has to set the library search path: https://github.com/CocoaPods/Specs/blob/master/Specs/GoogleAnalytics-iOS-SDK/3.12/GoogleAnalytics-iOS-SDK.podspec.json#L38

**Comment by zammbi** [comment] 2015-07-28 02:29
Sounds like I'll just not add Google Analytics into the podfile until this is fixed :)

**Comment by smileyborg** [comment] 2015-08-04 18:55
I just ran into basically this same issue as well, using the pod `Kahuna` (v2.0.3): https://github.com/CocoaPods/Specs/blob/master/Specs/Kahuna/2.0.3/Kahuna.podspec.json

Installing this pod triggers the CocoaPods-generated xcconfig file for my app target to have the following `HEADER_SEARCH_PATHS` value (without this pod, the xcconfig file does not have anything for this key):

   HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Kahuna" "${PODS_ROOT}/Headers/Public/Kahuna/Kahuna"

Because my Xcode project defines some header search paths, and this xcconfig file does not include `$(inherited)`, then my application target does not end up having the header search paths from the project. This breaks the build of course.

It seems to me that @segiddins is right here, in other words that `$(inherited)` should be added regardless of the pod. Do you see a problem with the Kahuna podspec?

**Comment by smileyborg** [comment] 2015-08-21 14:53
So is this a confirmed bug to fix in a future CocoaPods release? I've been having to manually add `$(inherited)` to the generated `.xcconfig` files and this is a pain.

**Comment by segiddins** [comment] 2015-08-21 16:05
@smileyborg yeah, agree it's a bug, no one has contributed a fix yet though, apparently.

**Comment by smileyborg** [comment] 2015-08-21 16:10
I'd be happy to try and take a stab, can you point me in the right direction to where I should look to fix this? (And any tests that should be modified as a result?)

**Comment by segiddins** [comment] 2015-08-21 17:30
Probably just adding `'LIBRARY_SEARCH_PATHS' => '$(inherited)'` and `'HEADER_SEARCH_PATHS` => '$(inherited)'` in the xcconfig generator, and seeing what tests fail when that change is made?

**Closed** 2015-08-24 11:23 UTC
Labels: s2:confirmed

**Comment by zammbi** [comment] 2015-08-24 20:58
Thanks for the fix! I'll test it once it has been released.

**Comment by Gerst20051** [comment] 2015-08-25 16:50
:+1:

**Comment by Belarmino** [comment] 2016-04-01 12:52
in my a i use pod 0.39.0, i install Google/singin i get this error
`ld: library not found for -lPods-Pagali
clang: error: linker command failed with exit code 1 (use -v to see invocation)`
my .xcconfig has "$(inherited)" in HEADER_SEARCH_PATHS
`HEADER_SEARCH_PATHS = $(inherited) ${PODS_ROOT}/Google/Headers $(inherited) "${PODS_ROOT}/Headers/Public" "${PODS_ROOT}/Headers/Public/Google" "${PODS_ROOT}/Headers/Public/GoogleAppUtilities" "${PODS_ROOT}/Headers/Public/GoogleAuthUtilities" "${PODS_ROOT}/Headers/Public/GoogleInterchangeUtilities" "${PODS_ROOT}/Headers/Public/GoogleNetworkingUtilities" "${PODS_ROOT}/Headers/Public/GoogleSignIn" "${PODS_ROOT}/Headers/Public/GoogleSymbolUtilities" "${PODS_ROOT}/Headers/Public/GoogleUtilities"`
Help me please.
