### ISSUE TITLE
执行pod lib lint  指令后的错误

### ISSUE THREAD

**Issue by DAIBIDAIBI** [CocoaPods/CocoaPods#4645] opened 2015-12-10 08:12 UTC
Encoding::CompatibilityError - incompatible character encodings: ASCII-8BIT and UTF-8
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/standard_error.rb:88:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/linter.rb:36:in `rescue in initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-0.39.0/lib/cocoapods-core/specification/linter.rb:32:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/validator.rb:32:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/validator.rb:32:in `initialize'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/spec/lint.rb:51:in `new'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/spec/lint.rb:51:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/spec/lint.rb:50:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/spec/lint.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'

**Comment by neonichu** [comment] 2015-12-10 15:26
This seems like a duplicate of #2642, please check out the solution and see if it works for you.

**Closed by neonichu** 2015-12-10 15:26 UTC

**Comment by songhongkang** [comment] 2020-01-07 11:34
解决了吗，我也遇到了
