### ISSUE TITLE
My own public Pod is not appearing in the CocoaPods search

### ISSUE THREAD

**Issue by rcasanovan** [CocoaPods/CocoaPods#9116] opened 2019-08-20 13:35 UTC
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod trunk push`

## What did you expect to happen?
The pod should appears in the CocoaPods search (web search)

## What happened instead?
I'm able to check the pod web page (https://cocoapods.org/pods/RCNPopupController). The pod is public and in fact I'm able to add my pod to any pod file and run `pod install` without any problem but if I try to search the pod using the CocoaPods web page 0 results appears.

## CocoaPods Environment

`CocoaPods : 1.7.4`
`Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]`
`RubyGems : 2.6.4`
`Host : Mac OS X 10.14.5 (18F132)`
`Xcode : 10.2.1 (10E1001)`
`Git : git version 2.20.1 (Apple Git-117)`
`Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib`
`Repositories : master - https://github.com/CocoaPods/Specs.git @ 933b9126a1480ff5a6b2dbf4ef9765157b2a146f`

## Project that demonstrates the issue
-Check the pod url (https://cocoapods.org/pods/RCNPopupController). It's available.
-Try to install the pod using `pod install` on any pod file. It's working.
-Try to search "RCNPopupViewController" in the web page search. 0 results appears.

**Comment by dnkoutso** [comment] 2019-08-20 15:25
This is a known issue. The search indexer has been broken for a while. Duplicate of https://github.com/CocoaPods/cocoapods.org/issues/424.

Closing. Will try to see if we can get the indexer back online.

**Closed by dnkoutso** 2019-08-20 15:25 UTC

**Comment by rcasanovan** [comment] 2019-08-20 17:39
Thanks @dnkoutso!.

**Comment by djfitz** [comment] 2019-08-20 23:51
Yes, a big thanks to you as well @dnkoutso.
