### ISSUE TITLE
[iOS] unknown: Encountered an unknown error (no implicit conversion of nil into String

### ISSUE THREAD

**Issue by vince4** [CocoaPods/CocoaPods#6326] opened 2016-12-19 14:20 UTC
# Report

## What did you do?

Run `pod repo push Y******* Y*****Reader.podspec --use-libraries --allow-warnings --verbose`

## What did you expect to happen?

Push last tag (0.1.37) of my iOS project to my private repo. 

## What happened instead?

My github spec repo has no version 0.1.37 and the command failed with error : 

	Validating spec
		Y*****Reader (0.1.37) - Analyzing on iOS 8.0 platform.
    	Preparing
    	
	Analyzing dependencies
	Inspecting targets to integrate
  	Using `ARCHS` setting to build architectures of target `Pods-App`: ()

	Fetching external sources
	-> Fetching podspec for `Y******Reader` from `/Users/vincent/Documents/App/y******-reader-ios/Y******Reader/Y******Reader.podspec`

	Resolving dependencies of 
	 -> Y******Reader (0.1.37)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR | [iOS] unknown: Encountered an unknown error (no implicit conversion of nil into String
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/specification.rb:523:in `initialize'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/specification.rb:523:in `new'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/specification.rb:523:in `from_file'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/specification/set.rb:45:in `specification'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source.rb:265:in `search'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-core-1.1.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:347:in `create_set_from_sources'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:317:in `find_cached_set'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:290:in `specifications_for_dependency'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:108:in `search_for'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:206:in `block in sort_dependencies'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:200:in `each'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:200:in `sort_by'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:200:in `sort_dependencies'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/delegates/specification_provider.rb:52:in `block in sort_dependencies'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/delegates/specification_provider.rb:69:in `with_no_such_dependency_error_handling'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/delegates/specification_provider.rb:51:in `sort_dependencies'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/resolution.rb:445:in `push_state_for_requirements'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/resolution.rb:437:in `require_nested_dependencies_for'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/resolution.rb:421:in `activate_spec'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/resolution.rb:387:in `attempt_to_activate_new_spec'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/resolution.rb:317:in `attempt_to_activate'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/resolution.rb:137:in `process_topmost_state'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/resolution.rb:78:in `resolve'
	/Library/Ruby/Gems/2.0.0/gems/molinillo-0.5.2/lib/molinillo/resolver.rb:42:in `resolve'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/resolver.rb:62:in `resolve'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:723:in `block in resolve_dependencies'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:721:in `resolve_dependencies'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:236:in `analyze'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:150:in `block in resolve_dependencies'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/user_interface.rb:64:in `section'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/installer.rb:149:in `resolve_dependencies'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:403:in `block in download_pod'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:403:in `each'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:403:in `download_pod'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:299:in `block in perform_extensive_analysis'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:293:in `each'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:293:in `perform_extensive_analysis'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/validator.rb:79:in `validate'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/push.rb:127:in `block in validate_podspec_files'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/push.rb:121:in `each'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/push.rb:121:in `validate_podspec_files'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/push.rb:66:in `run'
	/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
	/usr/local/bin/pod:23:in `load'
	/usr/local/bin/pod:23:in `<main>'
	) during validation.
	
	[!] The `Y*****Reader.podspec` specification does not validate.
	
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/push.rb:132:in `block in validate_podspec_files'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/push.rb:121:in `each'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/push.rb:121:in `validate_podspec_files'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/repo/push.rb:66:in `run'
	/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:334:in `run'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
	/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
	/usr/local/bin/pod:23:in `load'
	/usr/local/bin/pod:23:in `<main>'

However, my specifications passed validation with command : `pod spec lint YBXiOSReader.podspec --use-libraries --allow-warnings`

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.1 (16B2555)
       Xcode : 8.1 (8B62)
         Git : git version 2.10.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : 
               master - https://github.com/CocoaPods/Specs.git @ e351d5bef66084a8d71397e689664f6f9d532be5
               pixelglow - https://github.com/pixelglow/ZipZap.git @ bd1ce609e711365d139a5a6fb455b39c82f7dd6a
               Y****** - git@github.com:y*****/y********-ios-specs.git @ ad56135cd325db2a9b4c7d000be4c1fddac31f62
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, "8.0"

target "Y******Reader" do

pod 'zipzap',                	'~> 8.1.1'
pod 'RNCryptor',                '2.2' #  book crypt with OpenSLL

end

target "Y******ReaderTests" do

pod 'Kiwi'
pod 'OHHTTPStubs'
end
```

### Podspec

```
Pod::Spec.new do |s|
  s.name         = "Y*****Reader"
  s.version      = "0.1.37"
  s.summary      = "The ******* iOS Reader"
  s.homepage     = "https://www.*"
  s.license = { :type => 'Private', :text => <<-LICENSE
                   Copyright 2014
                   For internal usage ***** only
                 LICENSE
               }
  s.author             = { "Vincent *****" => "*" }
  s.platform     = :ios, "8.0"
  s.source       = { :git => "git@github.com:******/y******-reader-ios.git", :tag => s.version.to_s }
  s.source_files  = "Y*****Reader/Y*****Reader/Reader/**/*.{h,m}"
  s.resources = "Y*****Reader/Y*****Reader/Reader/Ressources/*"
  s.requires_arc = true
  s.dependency "zipzap", "8.1.1"
  
  s.subspec "Security" do |sp|
    sp.source_files = "Y******Reader/Y******Reader/Security/*"
    sp.dependency "RNCryptor", "2.2"
  end
  
  s.subspec "API" do |sp|
    sp.source_files = "Y*****Reader/Y*****Reader/API/*"
  end

end
```

**Comment by benasher44** [comment] 2016-12-21 15:15
Hi @vince4! Were you running this with your podspec in your current working directory?

**Comment by vince4** [comment] 2016-12-21 15:26
Hi @benasher44, 
Yes, i'm running this with my Y*****Reader.podspec in my current working directory.

**Comment by benasher44** [comment] 2016-12-21 15:36
@vince4 could you give me the full path to your spec by chance? Based on the trace, it seems something is wrong with the path.

**Comment by vince4** [comment] 2016-12-22 13:48
Here is my spec full path : 
`/Users/vincent/Documents/App/y******-reader-ios/Y*****Reader/Y******Reader.podspec`

**Comment by benasher44** [comment] 2016-12-22 14:42
@vince4 okay now I think it might be one of your dependencies. Can you first try removing the `zipzap` dependency and run the command again? I expect it to not validate/build, since that dependency will be missing, but I think it'll make it farther along to building. If you still have the same error, can you try removing the `RNCryptor` dependency? Hopefully, we can isolate it to one of those. Thanks!

**Comment by vince4** [comment] 2016-12-22 16:38
@benasher44 I removed zipzap dependency and now it's much better, the build success. 
But now the specification does not validate. I presume because zipzap is missing : 

```
pod repo push Y****** Y*****Reader.podspec --use-libraries --allow-warnings

Validating spec
 -> Y******Reader (0.1.37)
    - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  Y*****Reader/Y*****Reader/Y*****Reader/Reader/Y**ReaderDataSourceProtocol.h:11:9: fatal error: 'ZZArchive.h' file not found

[!] The `Y*****Reader.podspec` specification does not validate.
```

How can I add zipzap as dependency again ?

**Comment by benasher44** [comment] 2017-01-11 14:53
@vince4 sorry for the delay. This might be a duplicate of #5184. Can you try running `rm -rf ~/.cocoapods` and then running `pod setup`? After that, you can add zipzap back as a dependency and try again.

**Comment by benasher44** [comment] 2017-03-19 22:40
I'm going to close this since there hasn't been any activity on it in months. If you're still experiencing this, please open a new issue and fill out the issue template from information using the latest version of CocoaPods. Have a great day!

**Closed by benasher44** 2017-03-19 22:40 UTC
Labels: s1:awaiting input

**Comment by vince4** [comment] 2017-04-04 08:53
Sorry for the delay. 
I ran your commands `rm -rf ~/.cocoapods`, `pod setup` and I setup my custom repo `pod repo add y******* https://github.com/y****`. Now it's working great again !
Before my repo name was in capitals. Passing the repo name in lower case may have help.
