### ISSUE TITLE
IBDesignable not works with the frameworks which links with CocoaPods' framework.

### ISSUE THREAD

**Issue by sinoru** [CocoaPods/CocoaPods#7606] opened 2018-04-09 01:40 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Use my custom framework which linked with CocoaPods' Framework

## What did you expect to happen?

Just works.

## What happened instead?

Failed:
```
[MT] IBSceneUpdate: [scene update, delegate=<IBStoryboardDocument: 0x7feec9364800>] Error Domain=com.apple.InterfaceBuilder Code=-1 "Failed to load designables from path /Users/sinoru/Library/Developer/Xcode/DerivedData/Ovey-fmwxmwpxyfgdluaoblaljoqussjk/Build/Intermediates.noindex/IBDesignables/Products/Debug-iphonesimulator/OveyUIKit.framework" UserInfo={NSLocalizedFailureReason=dlopen(OveyUIKit.framework, 1): Library not loaded: @rpath/JGProgressHUD.framework/JGProgressHUD
  Referenced from: OveyUIKit.framework
  Reason: no suitable image found.  Did find:
	/Users/sinoru/Library/Developer/Xcode/DerivedData/Ovey-fmwxmwpxyfgdluaoblaljoqussjk/Build/Intermediates.noindex/IBDesignables/Products/Debug-iphonesimulator/JGProgressHUD.framework/JGProgressHUD: required code signature missing for '/Users/sinoru/Library/Developer/Xcode/DerivedData/Ovey-fmwxmwpxyfgdluaoblaljoqussjk/Build/Intermediates.noindex/IBDesignables/Products/Debug-iphonesimulator/JGProgressHUD.framework/JGProgressHUD'
, <…>
```

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.5.0p0 (2017-12-25 revision 61468) [x86_64-darwin17]
    RubyGems : 2.7.3
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.17.0
Ruby lib dir : /Users/sinoru/.rbenv/versions/2.5.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 18020377917e622f64b4b73808de98b6cf39e5be
```

### Installation Source

```
Executable Path: /Users/sinoru/.rbenv/versions/2.5.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# -*- mode: ruby -*-
# vi: set ft=ruby :

workspace 'Ovey.xcworkspace'

# Comment the next line if you're not using Swift and don't want to use dynamic frameworks
use_frameworks!

target 'OveyUIKit' do
  project 'OveyUIKit/OveyUIKit'
  platform :ios, '9.0'

  # Pods for OveyKit
  pod 'JGProgressHUD', '~> 2.0'

  target 'OveyUIKitTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'Ovey' do
    project 'Ovey/Ovey'
    platform :ios, '9.0'

    # Pods for Ovey
    pod 'Firebase', '~> 4.10'
    pod 'Firebase/RemoteConfig'
    pod 'GoogleSignIn', '~> 4.1'
    pod 'FBSDKLoginKit', '~> 4.31', :inhibit_warnings => true
    pod 'Bolts', :inhibit_warnings => true
    pod 'FBSDKCoreKit', :inhibit_warnings => true
    pod 'naveridlogin-sdk-ios', '~> 4.0'
    pod 'Kakao', :podspec => 'PodsSpecs/Kakao.podspec'

    pod 'PhoneNumberKit', '~> 2.1'

    target 'OveyTests' do
      inherit! :search_paths
      # Pods for testing
    end

    target 'OveyUITests' do
      inherit! :search_paths
      # Pods for testing
    end
  end
end

# Workaround for @IBDesignable (https://github.com/CocoaPods/CocoaPods/issues/5334)
post_install do |installer|
  installer.pods_project.targets.each do |target|
    next if target.product_type == "com.apple.product-type.bundle"
    target.build_configurations.each do |config|
      config.build_settings['CONFIGURATION_BUILD_DIR'] = '$PODS_CONFIGURATION_BUILD_DIR'
    end
  end
end
```

## Project that demonstrates the issue

It works just before as is. But it happens after Xcode updates.
I think it is related to macOS changes which is (from Xcode 9.3 Release Notes):
```
The debugger on macOS now requires the entitlement com.apple.security.get-task-allow to attach to apps built for macOS or for iOS, tvOS or watchOS apps built for Simulator. Xcode automatically injects this entitlement to your builds. The entitlement is stripped from apps distributed using the Organizer window. (34638816)
To disable Xcode injecting the entitlement, set CODE_SIGN_INJECT_BASE_ENTITLEMENTS to NO in the build settings for the target or app. (34638816)
```

So, default CocoaPods behavior is when to create Pods Project, It disables whole codesign. But now, at least, iOS Simulator requires codesign. So maybe default behavior should be changed?

I know that is frameworks referred from application it self, it will be works because of `Embed Pods Frameworks` phases(which do codesign if codesign not exist). But If `IBDesignable`-like thing used, may be frameworks can be referred from `BUILT_PRODUCTS_DIR` which is not signed, So IBSceneUpdate can be failed.

**Comment by dnkoutso** [comment] 2018-04-09 15:18
I do not think there is support for `IBDesignable` in CocoaPods. are you suggesting this was working in 1.4.0?

**Comment by sinoru** [comment] 2018-04-10 00:31
@dnkoutso Yes. It was working previsouly, until macOS policy changed (With Xcode 9.3).

**Comment by winddpan** [comment] 2018-04-10 13:56
Same problem on version 1.5.0, I slove the issue by demotion version to 1.4.0.

**Comment by luispadron** [comment] 2018-04-10 14:49
Can confirm, receiving issues with an IBDesignable framework in 1.5.0 but fine in 1.4.0

**Comment by dnkoutso** [comment] 2018-04-10 14:53
would love a sample app here and also someone to investigate.

**Comment by sinoru** [comment] 2018-04-10 15:02
I check that removing `CODE_SIGNING_ALLOWED`, `CODE_SIGNING_REQUIRED` settings on the project which is created by CocoaPods solves this problem.

This is caused by now macOS requires codesigns (even dummy codesigning) when debugger attach to it. But, frameworks are not codesigned, so..
IBDesignables requires Interface Builder's process(debugger attached) to load frameworks, but it can't.

**Comment by luispadron** [comment] 2018-04-10 15:04
Here is a sample app: https://github.com/luispadron/PodDesignableTest

It uses one of my pods, if you `pod update` with cocoapods 1.5.0, the designable view will not show and sometimes an error (code signing) will show up. If you run `pod update` with 1.4.0 the designable works as intended and shows up on IB as expected.

**Comment by Serproger** [comment] 2018-04-11 12:15
> If you run pod update with 1.4.0 the designable works as intended and shows up on IB as expected

Thank you very much! I've spent around five hours  fixing the problem.

I can't understand how can such shit be released. Has somebody tested it with XCode 9.3?

**Comment by orta** [comment] 2018-04-11 13:44
@Serproger please don't use language like you did in our CocoaPods issues, that's not cool.

**Comment by nickdnk** [comment] 2018-04-11 15:44
Can confirm downgrading to 1.4 fixed the issue.

**Comment by dnkoutso** [comment] 2018-04-11 15:49
Reading the issue, I am uncertain if this is an Xcode 9.3 issue and most likely a CocoaPods library issue, it seems that it works for everyone in Xcode 9.3 and CocoaPods 1.4 so this leads me to believe that its a CocoaPods issue and not an Xcode issue.

**Comment by luispadron** [comment] 2018-04-11 16:03
@dnkoutso, agreed seeing as how it works on both of my machines on Xcode 9.3 and pods 1.4 but breaks with 1.5.

**Comment by sinoru** [comment] 2018-04-12 00:36
Remove`CODE_SIGNING_ALLOWED`, `CODE_SINING_REQUIRED` should make it works.
May I create pull request of this?

**Comment by h36ahmedUW** [comment] 2018-04-12 16:43
Yes please :)

**Comment by soleares** [comment] 2018-04-13 22:53
@sinoru Yes, that fixes it. 

Here's a post install hook that can be used until this is fixed and merged. Add it to the bottom of your Podfile and run `pod install`

```
# Fix for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
```

**Comment by nebiros** [comment] 2018-04-15 03:58
Same happened to me with TTTAttributedLabel: https://github.com/TTTAttributedLabel/TTTAttributedLabel/issues/783

**Comment by Anobisoft** [comment] 2018-04-19 11:27
can i fix that in podspec?

**Comment by nebiros** [comment] 2018-04-19 20:26
@Anobisoft no idea, but I add @soleares workaround, https://github.com/CocoaPods/CocoaPods/issues/7606#issuecomment-381279098, it worked, :)

**Comment by IbrahimDesouky72** [comment] 2018-04-28 19:56
after building the stars did not appear in the view

**Comment by Jon889** [comment] 2018-05-03 04:52
Is it so hard just to support IBDesignables in CocoaPods and make sure they don't break again in subsequent versions?

**Comment by amorde** [comment] 2018-05-03 17:16
@Jon889 I believe it's just a matter of someone taking the time to implement it and add tests to make sure we don't break it down the road. The most active CocoaPods contributors have been working on other features such as Swift static library support, static frameworks, Podspec-based unit tests, performance improvements, etc.

PRs are welcome!

**Comment by smilesworld116** [comment] 2018-05-10 01:32
Any updates here?

**Comment by sinoru** [comment] 2018-05-10 01:38
I create pull request #7640, and waiting for comment.

**Comment by Cyanide7523** [comment] 2018-05-10 04:03
I tried [soleares' workaround](#issuecomment-381279098) and I'm getting error message in `pod lib lint` : undefined method `post_install` for Pod:Module.

**Comment by stevenp** [comment] 2018-05-14 20:49
It's also worth nothing that IBDesignables, at least for now, will not work with static libraries (see https://stackoverflow.com/a/44733038/1001911) though there are some suggestions for ways to update your build configuration to use dynamic frameworks for designable targets at development time. Maybe there's a way to allow for a pod developer to specify this in the podspec in the future?

**Comment by mohsinka** [comment] 2018-05-28 09:30
@soleares Thanks a lot man! Wasted an entire day on this.

**Comment by ryanbooker** [comment] 2018-05-31 06:04
FYI, the posted work around doesn't seem to work any more.

**Comment by lbencs** [comment] 2018-06-13 08:45
The issue still has.
And this does not work for me.

Xcode: 9.3.1
CocoaPods: 1.5.3

# Workaround for Cocoapods issue #7606
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings.delete('CODE_SIGNING_ALLOWED')
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end

**Comment by AtomicCactus** [comment] 2018-06-19 02:19
Confirmed issue still persists

Xcode 9.4
CocoaPods 1.5.3

The workaround doesn't seem to work..

**Comment by sheinix** [comment] 2018-06-20 17:05
I can "clean" the error with the above solution, but the issue still persist for me too after a while working with some views.

XCode 9.4.1
Cocoapods 1.5.3

Does downgrading to 1.4.0 works?

Thanks

**Comment by sheinix** [comment] 2018-06-20 18:40
I don't see the error anymore downgrading to 1.4.0
```
sudo gem uninstall cocoapods
sudo gem install cocoapods -v 1.4.0
pod update
```

**Comment by anilabsinc-ajay** [comment] 2018-06-21 06:14
When this issue going to fixed, should we move to the Carthage or SPM

**Comment by luispadron** [comment] 2018-06-26 15:45
There is a PR in review, be patient

**Comment by soleares** [comment] 2018-07-17 19:46
@miraz029 The post-install hook above works for me with 1.5.0. Did you add the hook to your Podfile?

**Comment by rigaldamez** [comment] 2018-07-18 04:18
I did a `pod update` this morning and broke a lot of things which I have not fixed, apart from this issue discussed on this thread.

I have added the hook suggested as above to my pod file and running Cocoapods v1.5.3 and Xcode v9.4.1 and still no luck!

any other suggestions that may have fixed this issue for others?

This is my error:

```
Main.storyboard: error: IB Designables: Failed to render and update auto layout status for ConversationsListVC (ZGv-vB-cXa): dlopen(MapboxNavigation.framework, 1): Library not loaded: @rpath/Mapbox.framework/Mapbox
  Referenced from: MapboxNavigation.framework
  Reason: image not found
```

**Comment by soleares** [comment] 2018-07-18 04:46
@rigaldamez Please try 1.5.0 with the post install hook. It’s been working for me for a while.

**Comment by rigaldamez** [comment] 2018-07-18 05:32
@soleares  Yes, that worked! - Cocoapods v1.5.0 and Xcode v9.4.1 with the post install hook got rid of the error.

**Comment by frederickjjoubert** [comment] 2018-07-20 13:48
I've also been trying to figure out this error for a week or two now and just stumbled across this post. @soleares I downgraded to Cocoapods v1.5.0 and I'm using Xcode v9.4.1, tried the post install hook and pod updated, no luck. Still having the same error:
`IB Designables
Failed to render and update auto layout status for MasterVC (...): The agent threw an exception.`

**Comment by litmanenPL** [comment] 2018-08-26 00:40
For the latest COCOAPODS (1.5.3) please view this [comment](https://github.com/CocoaPods/CocoaPods/issues/7689#issuecomment-416005556) and try this `post_install` hook as the workaround:

```
# Workaround for Cocoapods issue #7689 (and #7606? - to be confirmed)
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
        config.build_settings.delete('CODE_SIGNING_REQUIRED')
    end
end
```

**Closed** 2018-09-18 01:53 UTC
Labels: d1:easy, help wanted

**Comment by NinoScript** [comment] 2018-12-19 15:00
> For the latest COCOAPODS (1.5.3) please view this [comment](https://github.com/CocoaPods/CocoaPods/issues/7689#issuecomment-416005556) and try this `post_install` hook as the workaround:
> 
> ```
> # Workaround for Cocoapods issue #7689 (and #7606? - to be confirmed)
> post_install do |installer|
>     installer.pods_project.build_configurations.each do |config|
>         config.build_settings['CODE_SIGNING_ALLOWED'] = 'YES'
>         config.build_settings.delete('CODE_SIGNING_REQUIRED')
>     end
> end
> ```

This also works for CocoaPods 1.6.0.beta.2

**Comment by amorde** [comment] 2018-12-19 18:31
The fix is included in `1.6.0.beta.2` - the workaround shouldn't be necessary on that version

**Comment by afshin-hoseini** [comment] 2019-04-07 06:35
@amorde Same issue still persists in `1.6.0.beta.2`

**Comment by Tyler-Keith-Thompson** [comment] 2019-04-17 23:09
For us this issue was all about run paths. There's another thread somewhere that has part of this solution posted but given the recent comments and the trouble we had on our team we thought we'd share our fix:

```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    next unless config.name == 'Debug'
    config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
      '$(FRAMEWORK_SEARCH_PATHS)'
    ]
  end
end
```

**Comment by ShanghaiTimes** [comment] 2019-05-08 09:24
> For us this issue was all about run paths. There's another thread somewhere that has part of this solution posted but given the recent comments and the trouble we had on our team we thought we'd share our fix:
> 
> ```
> post_install do |installer|
>   installer.pods_project.build_configurations.each do |config|
>     next unless config.name == 'Debug'
>     config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
>       '$(FRAMEWORK_SEARCH_PATHS)'
>     ]
>   end
> end
> ```


This seemed to work, however it now throws a warning:
Main.storyboard: warning: IB Designables: Using class UIView for object with custom class because the class _TtC14MapBoxTutorial10MGLMapView does not exist

**Comment by piotrros** [comment] 2019-05-31 11:51
Everything was working and today out of nowhere I started to have this issue. I've updated cocoa pods itself and all the pods, but took a lot of time to fix.

But, I still have this issue with 1.7.1. 

I've tried all post_install fixes. 
I've tried cleaning build folder & derived data.
I've tried re-running pod update.
I've tried restarting XCode and Mac OS multiple times.

I've tried downgrading to 1.4.0, but I can't do it, because one of pods I use requires 1.5.0.

Using Xcode 10.2.1 by the way.

I'm completely stuck. Project runs, but I cannot edit Storyboard (well, technically, I can edit stuff, but I don't see the changes unless I restart Xcode or run the app on the device).

Here's how it looks like:
<img width="789" alt="Screenshot 2019-05-31 at 13 46 53" src="https://user-images.githubusercontent.com/8133606/58704051-ffc09180-83aa-11e9-997d-00b6a3b0c189.png">

One error for each instance of GoogleMaps view.

**Comment by piotrros** [comment] 2019-06-03 11:45
Funny thing: it also yields this issue on view controllers, which don't contain GoogleMap view at all. 

Some time ago the error disappeared, but reappeared after several minutes. And nothing helps..

I even tried doing this:

```
import GoogleMaps

class GoogleMapView: GMSMapView {
    
}
```

What's more funny, even after changing GMSMapView to UIView I'm still getting the same errors. 

I've tried deleting Derived Data, cleaning, restarting Xcode, restarting Mac, reinstalling Pods.

**Comment by dachev** [comment] 2019-08-13 21:52
None of the suggested workarounds worked for me. However, I was able to make the error go away by using `use_frameworks!`

**Comment by w-i-n-s** [comment] 2019-08-28 22:16
Issue still present on 1.7.4. Develop private pod with class
```import UIKit

@IBDesignable public class BorderedView: UIView {
    @IBInspectable var borderColor: UIColor? = UIColor.white {
        didSet {
            if let actualColor = borderColor {
                layer.borderColor = actualColor.cgColor
            } else {
                layer.borderColor = UIColor.white.cgColor
            }
            
            setNeedsDisplay()
        }
    }
    @IBInspectable var borderWidth: CGFloat = 1 {
        didSet {
            layer.borderWidth = borderWidth
            setNeedsDisplay()
        }
    }
}
```

**Comment by pableiros** [comment] 2020-01-07 18:49
The issue is gone using `Xcode 11`, `cocoapods 1.9.0.beta.2` and implementing the following in the `Podfile`:

```
post_install do |installer|
    installer.pods_project.build_configurations.each do |config|
        next unless config.name == 'Debug'
        config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
          '$(FRAMEWORK_SEARCH_PATHS)'
        ]
    end
end

```

**Comment by alperkayabasi** [comment] 2020-02-11 08:03
> For us this issue was all about run paths. There's another thread somewhere that has part of this solution posted but given the recent comments and the trouble we had on our team we thought we'd share our fix:
> 
> ```
> post_install do |installer|
>   installer.pods_project.build_configurations.each do |config|
>     next unless config.name == 'Debug'
>     config.build_settings['LD_RUNPATH_SEARCH_PATHS'] = [
>       '$(FRAMEWORK_SEARCH_PATHS)'
>     ]
>   end
> end
> ```

After hours of headache, that worked. I love you guys.
Version: Xcode 11.3.1 / Cocoapods 1.8.4

**Comment by nickdnk** [comment] 2020-10-12 15:10
I get random errors that point in different directions and the IBs will build and display sometimes, sometimes not, just by restarting XCode. Working with this is impossible. Right now I'm struggling with IBDesignables saying (in the new info that's finally available in XCode 12): 

`The agent raised a "NSUnknownKeyException" exception: [<MyFramework.MyClass 0x00...> setValue:forUndefinedKey:]: this class is not key value coding compliant for the key adjustsImageSizeForAccessibilityContentSizeCategory.`

I never even heard of or touched `adjustsImageSizeForAccessibilityContentSizeCategory`, and it's not present in my class (a UIControl subclass) at all. Everything works fine when I run the app though.

Storyboards are a joke. I haven't had a problem-free session with XCode since I started using IBDesignables.

XCode 12.0.1, CocoaPods 1.9.3. My Podfile contains the code alperkayabasi posted as well as `use_modular_headers!`. No errors when running `pod install`.

I don't know where to go with this problem as I have no clue what the underlying cause is, but the thread here seems at least related, so perhaps this will help someone with debugging.

**Comment by talron10** [comment] 2021-01-24 19:09
Any workaround for this?
xCode 12.3 with cocoapods 1.10 isn't working

**Comment by ABashkirova** [comment] 2021-01-25 11:01
> Any workaround for this?
> xCode 12.3 with cocoapods 1.10 isn't working with all of solutions mentioned above

+1

**Comment by piotrros** [comment] 2021-01-25 11:08
Try adding this line inside your target:

  inherit! :search_paths

**Comment by talron10** [comment] 2021-01-25 19:18
I can use_frameworks! unfortunately as not all of the pods I use support that.
Is there another way? or some way to debug this error to figure our the cause? (`Failed to reload designables from path (null)`)

**Comment by linxz-coder** [comment] 2021-07-04 06:55
> > Any workaround for this?
> > xCode 12.3 with cocoapods 1.10 isn't working with all of solutions mentioned above
> 
> +1

+2

**Comment by serafimapp** [comment] 2021-11-18 08:56
> > > Any workaround for this?
> > > xCode 12.3 with cocoapods 1.10 isn't working with all of solutions mentioned above
> > 
> > 
> > +1
> 
> +2

+3

**Comment by talron10** [comment] 2021-11-18 13:10
Actually - we worked this out by not including external frameworks in the storyboards and just wrapped them up in some connecting class. (which checks with #canImport if the framework is available)
