### ISSUE TITLE
pod repo push failure after xcodeproj / fourflusher updates 

### ISSUE THREAD

**Issue by pkordal** [CocoaPods/CocoaPods#5445] opened 2016-06-02 07:47 UTC
### Command

```
/usr/local/bin/pod repo push private_specs_repo PROJECT.podspec --allow-warnings
```

### Report

There is an issue when we want pushing pod spec to our private pod spec repo.

Our Gemfile has traditionally only one gem - 

gem 'cocoapods', '1.0.0'

Before each work with cocoa pods we do gem update. 

Few days ago problem mentioned in this report started occurring after versions of 2 gems were bumped
xcodeproj 1.0.0 -> 1.1.0
fourflusher 0.3.0 -> 0.3.1

As far as I checked there is some issue with Ruby's autoload in cocoapods/validator.rb.

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories :
               source - ssh://git@ourRepo @ 5b52ad5422ee5a76b16bf14a5e9bb58f2c0a7429
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
LoadError - cannot load such file -- fourflusher
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/validator.rb:717:in `xcodebuild'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/validator.rb:478:in `block in build_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/user_interface.rb:144:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/validator.rb:477:in `build_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/validator.rb:274:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/validator.rb:263:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/validator.rb:81:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command/repo/push.rb:126:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command/repo/push.rb:120:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command/repo/push.rb:120:in `validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command/repo/push.rb:65:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

I saw @neonichu released fourflusher 0.3.1 few days ago. Maybe there is some issue with it? 
I am not Ruby specialist yet so it is hard to me giving more support.

Update:
Lowering fourflusher in version 0.3 does the job until next gem update.

Best,
Paweł

**Comment by kordziu** [comment] 2016-06-02 08:10
Ok, found out calling pod repo push with bundle exec does the work. It was issue with fastlane's pod_push action not doing it. We can close it. Sorry for false alarm.

**Comment by EliaCereda** [comment] 2016-06-02 16:11
I'm experiencing the same problem while calling CocoaPods directly from the Terminal.

Downgrading `fourflusher` to 0.3.0 fixed the problem for me too:
```
$ sudo gem install fourflusher --version 0.3.0
$ sudo gem uninstall fourflusher --version 0.3.1
```

**Comment by mrackwitz** [comment] 2016-06-02 17:23
I can confirm that this is a problem. /c @neonichu @icanzilb

**Comment by icanzilb** [comment] 2016-06-02 17:32
Here's the output when I try to push my pod up:

```
### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.6.3
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/marin/.rvm/rubies/ruby-2.2.1/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ c03632020b0a429fbab35bf0f1c047a68ca05ea2
               master - https://github.com/CocoaPods/Specs.git @ adc0518990c7abacc2ff782cebab62c56b378914
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-playgrounds : 1.2.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
LoadError - cannot load such file -- fourflusher
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:717:in `xcodebuild'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:478:in `block in build_pod'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:477:in `build_pod'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:274:in `block in perform_extensive_analysis'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `each'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:81:in `validate'
/Users/marin/.rvm/gems/ruby-2.2.1/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:109:in `validate_podspec'
/Users/marin/.rvm/gems/ruby-2.2.1/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:61:in `run'
/Users/marin/.rvm/gems/ruby-2.2.1/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/marin/.rvm/gems/ruby-2.2.1@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/marin/.rvm/gems/ruby-2.2.1/bin/pod:22:in `load'
/Users/marin/.rvm/gems/ruby-2.2.1/bin/pod:22:in `<main>'
/Users/marin/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `eval'
/Users/marin/.rvm/gems/ruby-2.2.1/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by icanzilb** [comment] 2016-06-02 17:43
the suggested change from @mrackwitz works for me 👍

**Comment by neonichu** [comment] 2016-06-02 22:12
Having a hard time reproducing this. Anyone got any ideas on what circumstances might be causing it? cc @segiddins

**Comment by neonichu** [comment] 2016-06-02 22:16
OK, got it now — this happens when multiple versions of `fourflusher` are installed at the same time.

**Comment by neonichu** [comment] 2016-06-02 22:26
Just for reference, this is how I am reproducing it:

```bash
mkdir -p yolo
export GEM_HOME=$PWD/yolo
export GEM_PATH=$PWD/yolo

gem install fourflusher --version 0.3.0
gem install fourflusher --version 0.3.1
gem install cocoapods
```

then run `pod lib lint`

**Comment by neonichu** [comment] 2016-06-11 00:17
@segiddins/@mrackwitz does one of you have any opinions on if we want to change the `autoload` to `require` for fourflusher?

**Comment by segiddins** [comment] 2016-06-11 00:29
Let's change it to a require if it fixes the issue, though ideally Wed do it inside a method instead of at the top level

**Comment by neonichu** [comment] 2016-06-11 00:47
:+1: will make a PR

**Closed** 2016-06-11 20:14 UTC
Labels: s2:confirmed

**Comment by Architect001** [comment] 2016-06-13 05:56
following command:   

> pod lib lint

output the following:




### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin15.0.0]
    RubyGems : 2.6.3
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.6.4 (Apple Git-63)
Ruby lib dir : /Users/WLY/.rvm/rubies/ruby-2.0.0-p643/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5d7afffb00ca12e9279c10de2970e05ef0ae656c
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Error

```
LoadError - cannot load such file -- fourflusher
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:717:in `xcodebuild'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:478:in `block in build_pod'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:477:in `build_pod'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:274:in `block in perform_extensive_analysis'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `each'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:81:in `validate'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command/spec/lint.rb:60:in `block in run'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command/spec/lint.rb:50:in `each'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command/spec/lint.rb:50:in `run'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/bin/pod:22:in `load'
/Users/WLY/.rvm/gems/ruby-2.0.0-p643/bin/pod:22:in `<main>'
```

I try the above method, but Useless. 

seek help...

**Comment by dlbuckley** [comment] 2016-06-23 21:30
@Architect001 I was having the same issue. All I did was uninstall all my four-flusher gem versions and then install the latest one.

```
sudo gem uninstall four-flusher
// Select to uninstall all versions and then run:
sudo gem install four-flusher
```

**Comment by andresbrun** [comment] 2016-07-08 07:59
I have faced the same issue and I managed to solved it by uninstalling all gems as @dlackty explains but installing only the version 0.3.2 instead of the last one (1.0.1).
```
sudo gem uninstall fourflusher
// Select to uninstall all versions and then run:
sudo gem install fourflusher --version 0.3.2
```
Working with cocoapods version 1.0.1

**Comment by borisyurkevich** [comment] 2016-07-26 10:16
@andresbrun your solution worked, you just need to edit the last line of your comment. it is:
`sudo gem install fourflusher --version 0.3.0`
Not:
`sudo gem install fourflusher --version 0.3.2`

**Comment by lemonkey** [comment] 2016-07-29 19:33
Still happens for me on my Jenkins server, even if there is only one version of fourflusher installed (0.3.1 was initially installed, but I then remove it and replace it with 0.3.2 before trying 0.3.0, none of which worked).

What's strange is that the podspec passes pod lib lint if I do it from the command line on said server.

**Comment by Jvaeyhcd** [comment] 2016-08-10 01:18
@icanzilb i have the same problem,can you tell me how to solve it.

**Comment by icanzilb** [comment] 2016-08-10 01:26
updating everything to the latest version right now should fix it

**Comment by Jvaeyhcd** [comment] 2016-08-10 01:43
i have updated everything to the latest version.

but when i wrote the following commod:
```
pod trunk push HcdPopMenu.podspec
```
output the following:

### Command

```
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/bin/pod trunk push HcdPopMenu.podspec
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.0.0p643 (2015-02-25 revision 49749) [x86_64-darwin14.1.0]
    RubyGems : 2.4.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/funmi/.rvm/rubies/ruby-2.0.0-p643/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ fed2eed57fd0b3278479483841d37d541da77676
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'HcdPopMenuDemo' do
pod 'pop'
pod 'SDWebImage'
end
```

### Error

```
LoadError - cannot load such file -- fourflusher
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:717:in `xcodebuild'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:478:in `block in build_pod'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:141:in `message'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:477:in `build_pod'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:274:in `block in perform_extensive_analysis'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `each'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:263:in `perform_extensive_analysis'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/validator.rb:81:in `validate'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643@global/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:109:in `validate_podspec'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643@global/gems/cocoapods-trunk-1.0.0/lib/pod/command/trunk/push.rb:61:in `run'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/bin/pod:23:in `load'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/bin/pod:23:in `<main>'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `eval'
/Users/funmi/.rvm/gems/ruby-2.0.0-p643/bin/ruby_executable_hooks:15:in `<main>'
```

Here is my code:[https://github.com/Jvaeyhcd/HcdPopMenu](https://github.com/Jvaeyhcd/HcdPopMenu)

**Comment by Architect001** [comment] 2016-08-11 10:00
update  all about😂

发自我的 iPhone

**Comment by Coeur** [comment] 2016-09-02 01:41
I got the same issue with CocoaPods 1.0.1:

    $ gem list fourflusher
    
    *** LOCAL GEMS ***
    
    fourflusher (1.0.1, 0.3.2, 0.3.0)

I had to manually uninstall some versions.

**Comment by nicklockwood** [comment] 2016-09-09 19:40
I'm getting the same issue, and I only have fourflusher 0.3.0
