### ISSUE TITLE
Specs satisfying the `PubNub (= 4.12.0)` dependency were found, but they required a higher minimum deployment target.

### ISSUE THREAD

**Issue by SharmaVinay** [CocoaPods/CocoaPods#9529] opened 2020-02-10 17:41 UTC
pod update PubNub

Analyzing dependencies
[!] CocoaPods could not find compatible versions for pod "PubNub":
  In Podfile:
    PubNub (= 4.12.0)

Specs satisfying the `PubNub (= 4.12.0)` dependency were found, but they required a higher minimum deployment target.

**Comment by dnkoutso** [comment] 2020-02-10 18:19
This isn't a sufficient bug report. Please re-open a new issue filling in issue template and attaching a sample app. The error message also clearly says what the issue is.

Closing preemptively.

**Closed by dnkoutso** 2020-02-10 18:19 UTC
