### ISSUE TITLE
Frameworks Aren’t Always Found

### ISSUE THREAD

**Issue by SlaunchaMan** [CocoaPods/CocoaPods#4181] opened 2015-09-14 20:26 UTC
We have an iOS app with an embedded framework, a WatchKit Extension (watchOS 2) with its own embedded watchOS framework, and some test targets. We’ve had issues with Alamofire.framework not being found. This has two issues: first, we can't compile because our frameworks aren't found. Second, the `Pods-APPNAME-frameworks.sh` script seems to copy the entire source folder into the app’s frameworks!

I was able to fix it by modifying the script as such:

```Shell
  if [ -r "${BUILT_PRODUCTS_DIR}/$1" ]; then
    local source="${BUILT_PRODUCTS_DIR}/$1"
  elif [ -r "${BUILT_PRODUCTS_DIR}/$(basename "$1")" ]; then
    local source="${BUILT_PRODUCTS_DIR}/$(basename "$1")"
  elif [ -r "$1" ]; then
    local source="$1"
  elif [ -r "${BUILT_PRODUCTS_DIR}/Pods/$(basename "$1")" ]; then
    local source="${BUILT_PRODUCTS_DIR}/Pods/$(basename "$1")"
  fi
```

The final branch of that conditional looks in the `Pods/` directory if it can’t find the pod elsewhere. It looks like `embed_frameworks_script.rb` would be the right place to add this change, but I want to build up a test case before actually sending a PR.

I would appreciate any pointers to make a failing test out of my Podfile!

This is all Xcode 7 GM and CocoaPods 0.39.0 beta 4.

**Comment by segiddins** [comment] 2015-09-14 23:49
Can you share a Podfile we can use to reproduce the issue? My guess is that the last two branches need to be switched, but I'm not sure.

**Comment by SlaunchaMan** [comment] 2015-09-15 14:51
Will definitely get a `Podifle` together for an example, but in the meantime, here’s my post-install workaround in the `Podfile` (excuse my Ruby noobishness):
```Ruby
post_install do |installer|
    installer.aggregate_targets.each do |target|
        path = target.embed_frameworks_script_path
        newpath = path.to_s + ".new"

        if path.exist? then
            newfile = File.open(newpath, 'w')

            File.open(path, 'r').each do |line|
                newfile.puts(line)

                if line.include? 'local source="${BUILT_PRODUCTS_DIR}/$(basename "$1")"' then
                    newfile.puts('  elif [ -r "${BUILT_PRODUCTS_DIR}/Pods/$(basename "$1")" ]; then')
                    newfile.puts('    local source="${BUILT_PRODUCTS_DIR}/Pods/$(basename "$1")"')
                end
            end

            File.rename(newfile, path)
        end
    end
end
```

**Comment by segiddins** [comment] 2015-09-25 17:08
Closing due to lack of reproduction case.

**Closed by segiddins** 2015-09-25 17:08 UTC
Labels: s1:awaiting input
