### ISSUE TITLE
`pod spec lint` pulling the wrong dependency pod version

### ISSUE THREAD

**Issue by eneko** [CocoaPods/CocoaPods#4797] opened 2016-01-21 17:14 UTC
Here is my `podspec` file:

```
Pod::Spec.new do |s|
   [...]
    s.dependency "SwiftyJSON", "~>2.3.2"
end
```

And here is my Podfile:
```
use_frameworks!

def pods()
    pod 'JSONRequest'
    pod 'SwiftyJSON', '~>2.3.2'
end

target 'XXXSDK' do
    pods()
end

target 'XXXSDKTests' do
    pods()
end
```

When I run `pod install`, SwiftyJSON 2.3.2 is installed properly. However, when I run `pod spec lint`, it it pulls SwiftyJSON 2.2.1:
```
$ pod spec lint
 -> SwiftyJSON (2.2.1)
```

Any ideas? Using CocoaPods 0.39.

**Comment by eneko** [comment] 2016-01-21 17:17
PS: The same issue happens if I remove the version number from the `podspec` file.  I've tried clearing the following directories with no luck:
```
./Pods/Local Podspecs/
/Users/enekoalonso/Library/Caches/CocoaPods/Pods/External/SwiftyJSON
```

**Comment by eneko** [comment] 2016-01-22 22:36
Thanks, that seems to work, thank you. The repo, however, was up to date. It is the pod dependencies that are the problem, for whatever reason is not downloading the latest or indicated version, but it is stuck on an old version (`SwiftyJSON` 2.2.1 in this case)

**Comment by segiddins** [comment] 2016-01-22 22:42
what source do you specify in your podspec?

**Comment by eneko** [comment] 2016-01-22 22:58
The source pulls from a private GitHub repo, see here:
```
Pod::Spec.new do |s|
    s.name         = "XXXSDK"
    s.version      = "0.3.0"
    s.summary      = "The XXXSDK provides access to the XXX JSON API."
    s.homepage     = "https://github.com/hathway/HWAY_XXX_iOS_SDK"
    s.license      = "Copyright (c) 2015 Hathway, Inc."
    s.authors      = { "cshireman" => "chris@wearehathway.com", "eneko" => "eneko@wearehathway.com" }
    s.platform     = :ios, "8.0"
    s.source       = { :git => "https://github.com/hathway/HWAY_XXX_iOS_SDK.git", :tag => s.version }
    s.source_files = "XXXSDK/**/*.swift"
    s.dependency "SwiftyJSON", "~>2.3.2"
    s.dependency "JSONRequest"
end
```

I've done that before with other frameworks and never had this issue, that I recall.

Here is the error output:
```
$ pod spec lint --verbose

    SwiftyJSON (2.2.1) - Analyzing on OS X 10.9 platform.
  Preparing

Analyzing dependencies

Fetching external sources
-> Fetching podspec for `SwiftyJSON` from `/Users/enekoalonso/dev/projects/HWAY_XXX_iOS_SDK/Pods/Local Podspecs/SwiftyJSON.podspec.json`

Resolving dependencies of 

Comparing resolved specification to the sandbox manifest
  A SwiftyJSON

Downloading dependencies

-> Installing SwiftyJSON (2.2.1)
  > Copying SwiftyJSON from
  `/Users/enekoalonso/Library/Caches/CocoaPods/Pods/External/SwiftyJSON/aa7e8eb43d066fc5b426f5218a6a41a3-ae2d0` to
  `../../../../../private/var/folders/3r/0xg3y55n6tv0czmltsk_39s00000gn/T/CocoaPods/Lint/Pods/SwiftyJSON`
  - Running pre install hooks

[....]
```

I've completely removed my local pod specs folder (`/Users/enekoalonso/dev/projects/HWAY_XXX_iOS_SDK/Pods/Local Podspecs/`) but that didn't change anything.

**Comment by eneko** [comment] 2016-01-22 23:00
Ok, I've found the problem. My setup is an iOS Framework that uses CocoaPods (hence, there is a Podfile, a Podfile.lock and a Pods folder).  We distribute this framework via CocoaPods internally, so there is a .podspec file.

**Comment by segiddins** [comment] 2016-01-22 23:03
Interesting, that shouldn't cause an issue. If you can boil it down to a reproduction case we can run, that would be much appreciated!

**Comment by mgrebenets** [comment] 2016-02-19 04:41
I think I had similar issue and in my case `pod spec lint` would pull Expecta `0.3.1` and OCMock `3.1.1` even though both have long moved to `1.0.5` and `3.2` correspondingly. What puzzled me even more is why would it even pull those, because these pods are used for unit test target only, the main framework target has no pod dependencies whatsoever.

Turns out, in my `Pods/Local Podspecs` there was a couple of `JSON` files for `Expecta` and `OCMock`. I think those were created when I was using `path:` option in `Podfile` for development purposes. Since we commit `Pods` directory along with main code, I got those local podspecs committed too and then those were causing trouble for `pod spec lint`. So I removed `Pods` directory and re-ran `pod install` and got successful validation after that.

Probably we need to ignore `Pods/Local Podspecs` in `.gitignore` to avoid this type of problems in the future.

**Comment by neonichu** [comment] 2016-05-01 17:12
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Closed by neonichu** 2016-05-01 17:12 UTC
