### ISSUE TITLE
Framework dependency image not found when running app built on framework

### ISSUE THREAD

**Issue by ksoftllc** [CocoaPods/CocoaPods#8720] opened 2019-04-17 23:22 UTC
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod install

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

Runtime crash because image is missing:

```
    dyld: Library not loaded: @rpath/NonEmpty.framework/NonEmpty
      Referenced from: /private/var/containers/Bundle/Application/ECBB8FFF-7B1C-4070-9405-7BDDB845AE1F/Avjobs.app/Frameworks/CMUtilities.framework/CMUtilities
      Reason: image not found
```

Avjobs target incorporates CMUtilties framework in the workspace. The CMUtilties framework depends on PointFree-Validated pod.  The PointFree-Validated pod depends on NonEmpty pod. Apparently the workspace does not configure to include the image for NonEmpty in the Avjobs target build.

I was able to work around this by adding a dependency on PointFree-Validated pod to the Avjobs target, even though Avjobs does not directly call PointFree-Validated.

### Stack

```
   CocoaPods : 1.6.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2 (10E125)
         Git : git version 2.17.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 6dd6ab05f30a14e11270de300a561b7cec3513c8
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
workspace 'Avjobs'


target 'Avjobs' do
project 'Avjobs'

  platform :ios, '11.0'
  use_frameworks!

  pod 'RxSwift', '~> 4.5.0'
  pod 'RxCocoa', '~> 4.5.0'
  pod 'ReSwift', '~> 4.1.1'
  pod 'XMLCoder', '~> 0.3.1'

  target 'AvjobsTests' do
    inherit! :search_paths
    # Pods for testing
    pod 'RxTest', '~> 4.5.0'
    pod 'RxBlocking', '~> 4.5.0'
    pod 'XMLCoder', '~> 0.3.1'
  end
end


project 'CMUtilities/CMUtilities.xcodeproj'

target 'CMUtilities' do
  platform :ios, '11.0'
  use_frameworks!
  
  pod 'RxSwift', '~> 4.5.0'
  pod 'RxCocoa', '~> 4.5.0'
  pod 'ReSwift', '~> 4.1.1'
  pod 'PointFree-Validated', '~> 0.2.0'

  target 'CMUtilitiesTests' do
      inherit! :search_paths
  end   
end
```

## Project that demonstrates the issue

https://github.com/ksoftllc/Cocoapods-Issue-Example
see readme.md for steps to reproduce.

**Comment by markltownsend** [comment] 2019-04-19 21:47
Duplicate of #8664

**Comment by dnkoutso** [comment] 2019-04-21 14:39
Closing as dup but thank you for the detailed report and sample app.

**Closed by dnkoutso** 2019-04-21 14:39 UTC

**Comment by NagendraMNK** [comment] 2020-02-12 07:23
if you get this kind issues, please check those plugin dependencies from client packages JSON and those into .xml file also so that you pod files get the auto-generates configs to your project
