### ISSUE TITLE
Installing NativeOData got  error

### ISSUE THREAD

**Issue by atulgawali** [CocoaPods/CocoaPods#4064] opened 2015-08-24 09:20 UTC
i am trying to  fetch  data using sap  sdk, i am  using SMP3SDKInstaller_3_8_4_mac sdk and  cocoapod process steps
in cocoa pod file i write this

pod 'NativeMAF', :path => "/Users/esensemac7/Desktop/Sap/SMP3SDKInstaller_3_8_4_mac/modules/NativeSDK/NativeSDK/MAFReuse/iOS/NativeMAF.podspec"
pod 'NativeOData', :path => "/Users/esensemac7/Desktop/Sap/SMP3SDKInstaller_3_8_4_mac/modules/NativeSDK/NativeSDK/ODataFramework/iOS/NativeOData.podspec"

using  this i have successfully install NativeMAF framework..
but for "NativeOData" i got error

### Error

```
NoMethodError - undefined method `[]' for #<Xcodeproj::Project::Object::PBXFileReference:0x007ff2ba188850>
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/project.rb:191:in `block in add_file_reference'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `block in each_filename'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `each'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/pathname.rb:263:in `each_filename'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/project.rb:189:in `add_file_reference'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:184:in `block (2 levels) in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:182:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:182:in `block in add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:178:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:178:in `add_file_accessors_paths_to_pods_group'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:105:in `block in add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:140:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:104:in `add_resources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer/file_references_installer.rb:40:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:562:in `install_file_references'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:152:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:150:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/installer.rb:110:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60%5B%5D%27+for+%23%3CXcodeproj%3A%3AProject%3A%3AObject%3A%3APBXFileReference%3A0x007ff2ba188850%3E&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Esenses-iMac-6:SapUsingCocoaPod esensemac7$

**Comment by neonichu** [comment] 2015-08-24 13:26
This appears to be a duplicate of #3590

**Closed by neonichu** 2015-08-24 13:26 UTC
