### ISSUE TITLE
Failed to Code Sign

### ISSUE THREAD

**Issue by lukef** [CocoaPods/CocoaPods#4011] opened 2015-08-11 21:53 UTC
Configuring a project with the `use_frameworks!` option causes the following compilation/code sign issue when trying to build for a device or archive the application

`No valid signing identities (i.e. certificate and private key pair) matching the team ID “(null)” were found.`

This error will be repeated for each Pod Framework. The resulting Pod targets all have 'Don't Code Sign' set automatically.

If I *manually* set the code signing identity and profile for each configuration the error goes away.

The correct signing identity and profile have been set before installing the pods.

Podfile is below:

```
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '8.1'
inhibit_all_warnings!
use_frameworks!

pod 'Cartography'
pod 'FXKeychain'

# third-party support services
pod 'Bugsnag', :git => "https://github.com/bugsnag/bugsnag-cocoa.git"

# debug only
pod 'Reveal-iOS-SDK', :configurations => ['Staging']
```

**Comment by segiddins** [comment] 2015-08-11 22:39
What version of CocoaPods are you using? Where in the build process is the error occurring?

**Comment by lukef** [comment] 2015-08-11 22:53
Sorry. 

CocoaPods version = **0.38.2**. 

The error occurs almost immediately. It is during the '**Check dependencies**' phase.

<img width="762" alt="screen shot 2015-08-11 at 3 52 09 pm" src="https://cloud.githubusercontent.com/assets/37941/9212794/ff0e18c2-4040-11e5-9686-929dd17cbce9.png">

**Comment by neonichu** [comment] 2015-08-12 06:42
Might be a dupe of #3063 — it's definitely more related to how your code-signing stuff is set up locally than to CP, so will be hard to reproduce.

**Comment by lukef** [comment] 2015-08-12 17:40
It may be a dupe, but to be honest I don't see how my code signing is incorrectly or weirdly configured. Since posting, I went back and tried the EXACT setup without the `use_frameworks!` flag (and obviously any pod needing it) and the setup works. I had **Automatic** set on the Debug configuration and a *specific* Provisioning Profile on Release. I *do* have a third Project Configuration set up. Not sure if that is the issue.

re: #3063 - It does suggest that cocoapods is resorting to Automatic when something bombs. Is there a way to confirm this?

Currently I can set all the profiles manually for all Pods, but I feel like this, somewhat, defeats the purpose here.

**Comment by segiddins** [comment] 2015-08-12 17:42
@lukef not surprising that things work fine as static libs, since they don't ever require code signing separately from the app that they're linked into

**Comment by lukef** [comment] 2015-08-12 17:45
@segiddins - Sure, but if the tool is creating Frameworks now, is the recommended approach to manually set all the profiles? If so, should I document that some place? If not, the tool is broken.

**Comment by segiddins** [comment] 2015-08-12 17:52
I don't know what the underlying issue is either, having never experienced it myself

**Comment by orta** [comment] 2015-08-12 18:20
@lukef we're not seeing these problems on [artsy/eigen](https://github.com/artsy/eigen) - perhaps you could compare the code signing between that app and your own?

**Comment by lukef** [comment] 2015-08-12 18:38
@orta thanks. FWIW I get the same issue trying to build/archive for Device with your project too.
<img width="437" alt="screen shot 2015-08-12 at 11 36 41 am" src="https://cloud.githubusercontent.com/assets/37941/9233186/98cbb0b4-40e6-11e5-845c-c9d398a262e3.png">

**Comment by neonichu** [comment] 2015-08-12 20:53
hm, building eigen works fine for me, too — you will have to tell us more about your local code signing setup and provisioning profiles to even determine if that is something related to CP.

**Comment by lukef** [comment] 2015-08-12 21:02
Ok, i'm going to apologize and say that this is an Xcode/Mac issue somewhere.

I'm not totally sure what the issue was here but the solution, it seems, was to do the following. It's nasty, 
- Delete Xcode and re-install
- Delete **ALL** my certificates and private keys that are related to Xcode in any way (after backing them up)
- Delete all Provisioning Profiles: `rm -rf ~/Library/MobileDevice`
- Delete all the Xcode settings (**if doing this double check all this before doing it!**) via:
```
defaults delete com.apple.dt.Xcode
rm -rf ~/Library/Application\ Support/Developer
rm -rf ~/Library/Saved\ Application\ State/com.apple.dt.Xcode.savedState
rm -rf ~/Library/Preferences/com.apple.dt.Xcode.*
```

After doing so, I re-connected/re-downloaded my primary developer account (I do client work so have a bunch) and hit refresh on the profile screen.

So far things seem back to normal.

**Comment by lukef** [comment] 2015-08-12 21:07
fwiw - in case it is helpful, the primary issue manifests itself in this way:

<img width="514" alt="issue" src="https://cloud.githubusercontent.com/assets/37941/9236719/4edc6e02-40fb-11e5-8dbd-c760bf727456.png">

After "cleaning", it the warning is gone.

**Closed** 2015-08-12 21:08 UTC

**Comment by neonichu** [comment] 2015-08-13 05:34
@lukef thanks for the detailed steps to fix this

**Comment by carrchr** [comment] 2015-10-31 02:51
FYI- I got the same build error on all CocoaPods targets when we added `use_frameworks!`  
The build only failed when running on our CI server (Atlasssian Bamboo) which is just a wrapper for some shell scripts. The exact same code and `xcodebuild` command would work on a local Mac.  
I found this [website](http://devcenter.bitrise.io/docs/cocoapods-frameworks-signing-issue) detailing a "Post script" to add to the end of my `Podfile` that fixed the issue:  

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['EXPANDED_CODE_SIGN_IDENTITY'] = ""
      config.build_settings['CODE_SIGNING_REQUIRED'] = "NO"
      config.build_settings['CODE_SIGNING_ALLOWED'] = "NO"
    end
  end
end
```

**Comment by NitWitStudios** [comment] 2015-11-17 16:14
@carrchr :+1:  Your script did the trick. I was having the same issues when using 'use_frameworks!' in my pod file that when building an AdHoc build of my app, the code signing always failed on the pods (both on local xcode and Travis CI builds). Your script fixed my problems and all runs well now. Thanks!

**Comment by hiltonc** [comment] 2015-11-27 17:21
I'm using @carrchr's workaround with great success. Shouldn't this get rolled into Cocoapods itself?

**Comment by fatuhoku** [comment] 2016-03-05 15:39
Bump. Surely this work around is necessary for all Cocoapods users. Definitely should be rolled into Cocoapods.

**Comment by Mridul56** [comment] 2016-11-01 20:31
is your application accepted by apple? using this trick ?

**Comment by carrchr** [comment] 2016-11-01 20:35
Yes. No App Store submissions issues. And we are using same `post_install` step with CocoaPods 1.x

**Comment by Mridul56** [comment] 2016-11-01 20:42
@carrchr Thanks for your answer. i have tried the above solution but after doing using the 'post_install' in pod file and installing pod again using 'pod install' one of my pod giving me this error "could not build objective c module Atlas".

To verify this i build my app again after reverting the above changes and using the same app's bundle identifier and codesiging for the pod, then this error didn't come "could not build objective c module Atlas".

please help
