### ISSUE TITLE
Pod static framework dependency can't mix Swift and Objective-C (SomeFile.h not found)

### ISSUE THREAD

**Issue by bryanboyko** [CocoaPods/CocoaPods#7435] opened 2018-02-14 00:36 UTC
# Report

## What did you do?

Our repo, project **A**, has Swift files and FBAudienceNetwork as a dependency. FBAudienceNetwork in turn has a dependency that is a static library. To prevent transitive dependency issue on pod install - https://github.com/CocoaPods/CocoaPods/issues/3289, we upgraded to CocoaPods version 1.4.0.rc.1 to gain ability to build our repo with Swift as a static lib from this change -
 https://github.com/CocoaPods/Core/pull/386.

Adding the below code to project **A** podspec
```
s.static_framework = true
```

We created a project **B** and attempted to incorporate project **A** as a static lib via Cocoapods.

## What did you expect to happen?

**B** builds and runs successfully

## What happened instead? 

When we pod install project **A** as a static lib into another project, **B**, project **B** fails to build because **Swift files inside the project A static lib can no longer recognize ObjC files in the same static lib**. See error below:
(There are a bunch of these reported for the static lib target when building project **B**)
```
Use of undeclared type 'File'
```

**Several things to note:**

**1.**The error looks the same as what happens when building a static lib without a bridging header added to build settings and/or when ObjC files are not declared public in target build phases section 'Link with Binary Libraries' (As detailed here https://guides.cocoapods.org/making/using-pod-lib-create.html - "It's worth mentioning here, as this catches people quite often, a Swift library needs to have its classes declared as public for you to see them in your example library.")

**2.** When we directly open **A**.xcworspace and build it as either a static lib or a dynamic framework (Using two different targets), both **build successfully**.

**3.** Project **A** also has a Tests target. The tests, which are all written in Swift and incorporate both Swift and ObjC files, **build and run successfully** when the dynamic framework target is added to the Tests target Build Phases section 'Link With Binary Libraries.' When the dynamic framework in the Tests target Link With Binary Libraries section is replaced with the static library, the Tests target **did not build**.

Here is the error when building the Tests target with the static lib:
```
<unknown>:0: error: merge-module command failed with exit code 1 (use -v to see invocation)
Command /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/swiftc failed with exit code 1
```

**4.** After static lib **A** is pod installed into **B** as a Development Pod, we added the static lib target to project **B** schemes via manage schemes. We then built the static lib target only. It failed with error
```
Use of undeclared type 'File'
```
We then specifically added the bridging header development pod path to the Pods project static lib target, which is project **A**, in it's Build Settings -> Swift Compiler -> Objective-C Bridging Header section. The target then **built**. Project **B** however, still **did not build**.

**5.** We added bridging-header development pod path to project **B** Build Settings -> Swift Compiler -> Objective-C Bridging Header section. **B** still **did not build**.

**6.** We're also getting the below error when pod installing in project **A** repo
```
[!] The Podfile contains framework or static library targets, for which the Podfile does not contain host targets (targets which embed the framework).
If this project is for doing framework development, you can ignore this message. Otherwise, add a target to the Podfile that embeds these frameworks to make this message go away (e.g. a test target).
```

### Stack

```
   CocoaPods : 1.4.0.rc.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.3 (Apple Git-98)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a1ec0d9ceb6eb13b6ad34ffeeaf5d9ab2f5e3186
               maxads - https://github.com/MAXAds/Specs.git @ b69cc151dafcfb28d6e2648b9de84e6231ef472b
               Specs - git@github.com:MAXAds/Specs.git @ b69cc151dafcfb28d6e2648b9de84e6231ef472b
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

source 'https://github.com/CocoaPods/Specs.git'
source 'https://github.com/MAXAds/Specs.git'

def common_deps

  pod 'SwiftLint'
  pod 'mopub-ios-sdk', '>= 4.18.0'
  pod 'EVReflection/MoyaRxSwiftXML', '5.5'
  pod 'FBAudienceNetwork', '= 4.27.2'

end


#NOTE - Keep MAX framework target in addition to MAXLib because MAXTests needs to be linked to a framework and CocoaPods throws an error if there is no framework target

target 'MAX' do

  common_deps

  target 'MAXTests' do
     inherit! :search_paths

     pod 'Quick'
     pod 'Nimble'
  end

end

target 'MAXLib' do

  common_deps

end
```

## Project that demonstrates the issue

Both repos are private. Ideally I can avoid sharing them. If need be we have public equivalents and I can push my branches to them and then include the projects.

**Comment by paulb777** [comment] 2018-02-14 00:48
It's not clear to me if you're trying to do static frameworks or static libraries.  Support for Swift static libraries, including mixed language support, is currently in progress at #6966. Static Frameworks do not yet support mixed languages. More details and a workaround at #7213.

If your issue is not covered by either of those, we'll likely need a reproducible test case to address.

**Comment by bryanboyko** [comment] 2018-02-14 00:52
@paulb777 ah my bad. I'm confusing static libraries and static frameworks. Based on our podspec addition 's.static_framework = true' it looks as though I mean static frameworks.

Thanks for the heads up on #7213. I'll take a look.

**Comment by dnkoutso** [comment] 2018-02-14 04:00
@bryanboyko please close if #7213 work around is good for you.

**Comment by bryanboyko** [comment] 2018-02-20 22:08
@dnkoutso Thanks! #7213 fixed my initial issue - Swift files inside my pod not being able to recognize ObjC files in the same pod after the pod was integrated into another project via Cocoapods.

Unfortunately I'm now running into a couple more issues with 'static_framework = true'.

1. ObjC files in a project integrating a mixed Swift and ObjC static framework pod can't access Swift files from the pod.

2. Swift files in a project integrating a mixed Swift and ObjC static framework pod can't access ObjC files from the pod. 

These problems sound the same as the bottom two unchecked boxes in this Cocoapods issue, which was recently reopened #7307 

ObjC into Swift support would be much appreciated! Is there a workaround for this yet? Possibly in this PR https://github.com/CocoaPods/CocoaPods/pull/6966?

**Comment by dnkoutso** [comment] 2018-02-20 22:09
Uncertain from a quick view, but I am starting to lean on closing this as a dup of #7307.

@paulb777 any thoughts here?

**Comment by bryanboyko** [comment] 2018-02-20 22:30
Seems dupey to me - happy to close :)

**Comment by paulb777** [comment] 2018-02-20 22:31
Yes, agreed that it looks like a dup of #7307

**Closed by paulb777** 2018-02-20 22:31 UTC

**Comment by bryanboyko** [comment] 2018-04-02 22:54
Working in release 1.5.0.beta.1

@paulb777 Thanks!

**Comment by dnkoutso** [comment] 2018-04-02 22:58
very nice to hear!
