### ISSUE TITLE
Project with static transitive dependency, undefined symbols as of '0.39.0.rc.1'

### ISSUE THREAD

**Issue by mhuusko5** [CocoaPods/CocoaPods#4336] opened 2015-10-07 13:55 UTC
I have a project that is an internal framework with a bunch of dependencies, some of which are static libraries. I have stripped out everything sensitive or unnecessary leaving a skeleton project of SDK with Firebase dependency, and SDKExample project that consumes it as a development pod. 

This was working (compiling, and running) fine as of '0.39.0.beta.4'. 

As of '0.39.0.beta.5' is compiled but broke at runtime for a separate reason (something about Alamofire and swiftlibcore not being loaded). 

As of '0.39.0.rc.1' it doesn't compile, with a tonne of undefined symbols originating from the transitive Firebase lib.

Project: http://s000.tinyupload.com/index.php?file_id=01814995073571208264 (can't attach .zip's to github issues.. really??)

**Comment by segiddins** [comment] 2015-10-07 14:01
@kcoleman731 is it possible your changes could've caused this regression?

**Comment by neonichu** [comment] 2015-10-07 18:55
Yep, I have verified that this is caused by @kcoleman731's changes. 

The issue is that only Firebase itself is added, but not its required frameworks and libraries:

```diff
diff --git a/Pods/Target Support Files/SDK/SDK.xcconfig b/Pods/Target Support Files/SDK/SDK.xcconfig
index a46a2f4..d5701ac 100644
--- a/Pods/Target Support Files/SDK/SDK.xcconfig	
+++ b/Pods/Target Support Files/SDK/SDK.xcconfig	
@@ -1,6 +1,7 @@
 GCC_PREPROCESSOR_DEFINITIONS = $(inherited) COCOAPODS=1
 HEADER_SEARCH_PATHS = "${PODS_ROOT}/Headers/Private" "${PODS_ROOT}/Headers/Private/SDK" "${PODS_ROOT}/Headers/Public"
-OTHER_LDFLAGS = -framework "Foundation" -framework "UIKit"
+LIBRARY_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Firebase"
+OTHER_LDFLAGS = -l"FirebaseStatic" -framework "Foundation" -framework "UIKit"
 OTHER_SWIFT_FLAGS = $(inherited) "-D" "COCOAPODS"
 PODS_ROOT = ${SRCROOT}
 SKIP_INSTALL = YES
\ No newline at end of file
```

From the Firebase.xcconfig:

```
OTHER_LDFLAGS = -ObjC -l"FirebaseStatic" -l"c++" -l"icucore" -framework "CFNetwork" -framework "Security" -framework "SystemConfiguration"
```

**Comment by kcoleman731** [comment] 2015-10-07 19:12
@mhuusko5 @segiddins @neonichu looking in to a fix for this now.

**Comment by kcoleman731** [comment] 2015-10-07 20:12
@mhuusko5 @segiddins @neonich I just pulled down the SDK project (thanks @mhuusko5 for pulling together). It looks like the issue is actually with `-l"FirebaseStatic" being added to the `SDK` target in the Pods project. If I remove that linker flag, the project builds just fine. 

With my earlier PR [4278](https://github.com/CocoaPods/CocoaPods/pull/4278), cocoapods is now adding linker flags for vendored frameworks and libraries for dependency pods. In this case, `Firebase` is a dependency of `SDK` and the `Firebase` podspec has [`libFirebaseStatic.a` as a vendored library](`https://github.com/CocoaPods/Specs/blob/master/Specs/Firebase/2.4.1.1/Firebase.podspec.json#L26). Thus the linker flag is getting added to the SDK project. 

The impetus for PR  [4278](https://github.com/CocoaPods/CocoaPods/pull/4278) was support dynamic `vendored frameworks` for dependency pods.  Perhaps this functionality need not extend to `vendored libraries`?

Working on a patch and tests.

**Comment by neonichu** [comment] 2015-10-07 20:19
@kcoleman731 maybe — could also be that we shouldn't do it for static binaries, only for dynamic ones?

**Comment by kcoleman731** [comment] 2015-10-07 20:29
@neonichu understood...given that only we have access to a `Pathname` for vendored libs and frameworks in `xcconfig_helper.rb`, is there a simple way for us to discern the type of binary?

**Comment by kcoleman731** [comment] 2015-10-07 20:31
Ah...nm found it.

**Comment by kcoleman731** [comment] 2015-10-08 00:42
@mhuusko5 Just opened a PR with a fix. Would you mind pointing your `Gemfile` at this branch a testing? https://github.com/CocoaPods/CocoaPods/pull/4341

I am able to build your sample project without issue.

**Comment by segiddins** [comment] 2015-10-08 23:07
Fixed via https://github.com/CocoaPods/CocoaPods/pull/4341.

**Closed by segiddins** 2015-10-08 23:07 UTC
Labels: s4:awaiting validation, t2:defect
