### ISSUE TITLE
install cocoapods on latest macOS

### ISSUE THREAD

**Issue by kaimacuser** [CocoaPods/CocoaPods#12145] opened 2023-11-11 09:29 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I tried to install cocoapods on macOS Sonoma 14.1.1 (on MacbookAir and MacMini)
`sudo gem install cocoapods`

## What did you expect to happen?

I expected that pod is installed width all dependencies correctly.

## What happened instead?

I received an error message:
`ERROR:  Error installing cocoapods: There are no versions of cocoapods-downloader (>= 2.0) compatible with your Ruby & RubyGems. Maybe try installing an older version of the gem you're looking for? cocoapods-downloader requires Ruby version >= 2.7.4. The current ruby version is 2.6.10.210.`

## Temporary Solution
It trys to install cocoapods but runs into an error because the version of ruby, that is delivered with macOS, seems to be too old for installing the latest version of cocoapods.

The solution for me was to install an older version of cocoapods which seems to be based on Ruby 2.6.* (the version macOS ist delivered with). While executing the command I was asked to install a few other things, so the final order was:

1. `sudo gem install drb -v 2.0.5`
2. `sudo gem install activesupport -v 6.1.7.6`
3. `sudo gem install cocoapods -v 1.13.0`

**Comment by saldous** [comment] 2023-11-13 21:10
Duplicate of: https://github.com/CocoaPods/CocoaPods/issues/12122

**Closed** 2023-11-14 19:14 UTC

**Comment by MaxHsu911** [comment] 2023-11-18 04:55
It works!! Thanks for sharing!!

**Comment by AbdulAmmic** [comment] 2024-02-05 18:57
It works

**Comment by ociclica** [comment] 2024-03-18 16:03
Worked perfectly, thanks!

**Comment by elvsp1n** [comment] 2024-04-13 17:14
Try upgrading ruby before installing cocoapods with:
```
brew install ruby
echo 'export PATH="/usr/local/opt/ruby/bin:$PATH"' >> ~/.zshrc
echo 'export LDFLAGS="-L/usr/local/opt/ruby/lib"' >> ~/.zshrc 
echo 'export CPPFLAGS="-I/usr/local/opt/ruby/include"' >> ~/.zshrc
. ~/.zshrc
ruby -v
sudo gem install cocoapods
# Optional
# At the moment of writing, there seems to be an update for the gems, apply it with the following
sudo gem update --system 3.5.9
```
Cheers,
EE

**Comment by dixon1e** [comment] 2024-06-08 12:11
@elvsp1n when trying this on MacOS Sonoma (M3) the path was not the same as you've described. This is very new to me so I'm not sure what I did differently. Ruby installed in directory:
`/opt/homebrew/Cellar/ruby/3.3.2/bin/ruby`

And when doing the command `sudo gem install cocoapods` it completes the install but is not found in the path.

Where is cocoapods installed? This is quite confusing.

**Comment by monfresh** [comment] 2024-06-08 13:31
@dixon1e Yes, this is indeed one of the most confusing parts about working with Ruby on macOS. The problem is made worse by people giving bad advice to use `sudo`. Over the past 12 years I've helped thousands of people set up a proper Ruby dev environment on their Mac, and I personally recommend installing Ruby with a version manager, and not with Homebrew. You'll then be able to install cocoapods with `gem install cocoapods`. 

I recommend starting with my [step-by-step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/), which many Cocoapods users have thanked me for.

Here are more articles that might help you understand the differences between version managers and Homebrew, and why you shouldn't use sudo or the system Ruby:

[Why You Should Never Use sudo to Install Ruby Gems](https://www.moncefbelyamani.com/why-you-should-never-use-sudo-to-install-ruby-gems/)

[Comparison of the different ways to install Ruby on a Mac](https://www.moncefbelyamani.com/the-definitive-guide-to-installing-ruby-gems-on-a-mac/)

[Why You Shouldn't Use the System Ruby to Install Gems on a Mac](https://www.moncefbelyamani.com/why-you-shouldn-t-use-the-system-ruby-to-install-gems-on-a-mac/)

**Comment by ankits1626** [comment] 2024-06-14 09:50
so here is the solution:
device: Apple M3 Pro

1. Install rbenv : `brew install rbenv`
2. Install ruby 3.1.6: `rbenv install ruby 3.1.6` or `rbenv install 3.1.6`
3. Set ruby version globally: `rbenv global 3.1.6`
4. Verify if expected ruby version is set globally : `ruby -v` , If it display **_ruby 3.1.6p260 (2024-05-29 revision a777087be6) [arm64-darwin23]_** its ok install cocoapods If not move to step 5
5. Open your shell initialization file : `nano ~/.zshrc`
6. Ensure that you have the following line at the end of the file (for zsh): `if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi `
7. Save the file and then reload your shell configuration: `source ~/.zshrc`
8. Perform step 4 and see if ruby version is updated
9. sudo gem install cocoapods

**Comment by monfresh** [comment] 2024-06-14 13:06
Please, [never use sudo to install gems](https://www.moncefbelyamani.com/why-you-should-never-use-sudo-to-install-ruby-gems/)! That is bad advice that I hope one day will disappear from the internet.

If you use a Ruby version manager like `rbenv`, there is absolutely never a need to use `sudo`. I've been working with Ruby for almost 15 years and not a single time have I ever had to use `sudo` to install a Ruby gem.

Step 9 above should be `gem install cocoapods`

**Comment by Tufan1121** [comment] 2024-06-21 18:14
I install cocoapods but when i try to use i got this error:

Warning: CocoaPods not installed. Skipping pod install.
  CocoaPods is used to retrieve the iOS and macOS platform side's plugin code that responds to your plugin usage on the Dart side.
  Without CocoaPods, plugins will not work on iOS or macOS.
  For more info, see https://flutter.dev/platform-plugins
To install see https://guides.cocoapods.org/using/getting-started.html#installation for instructions.



CocoaPods not installed or not in valid state.

**Comment by monfresh** [comment] 2024-07-31 19:46
@Tufan1121 If you're still having this issue, it depends on how you installed Cocoapods. If you used `gem install`, this error means that the Ruby version where you installed Cocoapods is not the current active version when you're using Flutter. Before working with Ruby, you always need to make sure you're using the correct version, which you can check by running `ruby -v` and `which ruby`.

To understand how this works, how to switch between Ruby versions, and how to set up your project to automatically switch to the correct version, read my [step by step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/).

**Comment by tanmoy-cloudly** [comment] 2024-09-05 06:47
> so here is the solution: device: Apple M3 Pro
> 
> 1. Install rbenv : `brew install rbenv`
> 2. Install ruby 3.1.6: `rbenv install ruby 3.1.6` or `rbenv install 3.1.6`
> 3. Set ruby version globally: `rbenv global 3.1.6`
> 4. Verify if expected ruby version is set globally : `ruby -v` , If it display **_ruby 3.1.6p260 (2024-05-29 revision a777087be6) [arm64-darwin23]_** its ok install cocoapods If not move to step 5
> 5. Open your shell initialization file : `nano ~/.zshrc`
> 6. Ensure that you have the following line at the end of the file (for zsh): `if which rbenv > /dev/null; then eval "$(rbenv init -)"; fi `
> 7. Save the file and then reload your shell configuration: `source ~/.zshrc`
> 8. Perform step 4 and see if ruby version is updated
> 9. sudo gem install cocoapods

I wonder why macOS doesn't include the ruby 3.x.x out of the box. This fix worked like a charm.

**Comment by monfresh** [comment] 2024-09-05 13:39
> I wonder why macOS doesn't include the ruby 3.x.x out of the box. This fix worked like a charm.

As explained in the article I linked to in one of my earlier comments above ([Why You Shouldn't Use the System Ruby to Install Gems on a Mac](https://www.moncefbelyamani.com/why-you-shouldn-t-use-the-system-ruby-to-install-gems-on-a-mac/)), the version of Ruby that Apple preinstalls on macOS is meant for Apple's use only. It's not meant to be used for development. So, even if macOS came with Ruby 3.x.x out of the box, you shouldn't be using that version either!

The way to think about it is to assume that macOS does not come with any Ruby version out of the box, which Apple said might happen in the future. The proper way to use Ruby on macOS is to install a separate version of Ruby using a version manager such as chruby, rbenv, asdf, rvm, etc.

The one I recommend is chruby, because it's the simplest, fastest, and least likely to cause issues. Here's my [step by step guide for installing Ruby on a Mac](https://www.moncefbelyamani.com/how-to-install-xcode-homebrew-git-rvm-ruby-on-mac/) with ruby-install and chruby.

**Comment by stonehappi** [comment] 2025-01-24 13:55
Thank you.it is work well
