### ISSUE TITLE
Build objective-c project produces warnings when altogether: use_frameworks!, inhibit_all_warnings! and -Weverything

### ISSUE THREAD

**Issue by Antondomashnev** [CocoaPods/CocoaPods#5791] opened 2016-08-25 20:45 UTC
* [✔️] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Hi there, the following issue I first had in my project and then was able to reproduce in the test project. But I'm not sure if it's related to CocoaPods or not.

## What did you do?

I set up the `objective-c` project, added `podfile` with the following content:
```ruby
source 'git@github.com:CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'CocoaPodsTest' do
  pod 'pop', '~> 1.0'
end
``` 
In the project I added to the `other warnings flags` the flag `-Weverything`, it's an overkill a bit, but it's the simplest way to reproduce the issue.

## What did you expect to happen?

No warnings in the empty project.

## What happened instead?

Build log outputs some warnings from the `CocoaPods` dependency.

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.3p173 (2015-08-18 revision 51636) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/antondomashnev/.rvm/rubies/ruby-2.2.3/lib
Repositories : artsy - https://github.com/artsy/Specs @ 40004aaa5870afdc655bfbbdc84a2718ec8c1805
               conichigmbh - git@github.com:conichiGMBH/ios-specs.git @ d3eb88070b306f6bc434619b7a4820e7e1acf31a
               conichigmbh-1 - https://github.com/conichiGMBH/ios-specs @ d3eb88070b306f6bc434619b7a4820e7e1acf31a
               czechboy0 - https://github.com/czechboy0/Podspecs.git @ faebf3543d12ab21efdac4a7af094f05c4a31805
               master - https://github.com/CocoaPods/Specs.git @ 66955bd657b4852b2f420671446c7a9f34266e0d
               master-1 - https://github.com/CocoaPods/Specs.git @ 2a8af5dfb13ef718f900693e65d2f21f3951cb42
               master-2 - git@github.com:CocoaPods/Specs.git @ 2a8af5dfb13ef718f900693e65d2f21f3951cb42
```

### Installation Source

```
Executable Path: /Users/antondomashnev/.rvm/gems/ruby-2.2.3/bin/pod
```

### Plugins

```
claide-plugins             : 0.9.1
cocoapods-check            : 1.0.0
cocoapods-deintegrate      : 1.0.0
cocoapods-keys             : 1.6.1
cocoapods-packager         : 1.4.0
cocoapods-plugins          : 1.0.0
cocoapods-search           : 1.0.0
cocoapods-stats            : 1.0.0
cocoapods-superdeintegrate : 0.0.1
cocoapods-trunk            : 1.0.0
cocoapods-try              : 1.1.0
```

### Podfile

```ruby
source 'git@github.com:conichiGMBH/ios-specs.git'
source 'git@github.com:CocoaPods/Specs.git'

platform :ios, '8.0'
use_frameworks!
inhibit_all_warnings!

target 'CocoaPodsTest' do
  pod 'pop', '~> 1.0'
end
```

## Project that demonstrates the issue

https://github.com/Antondomashnev/CocoaPodsIssueProject

**Comment by neonichu** [comment] 2016-08-26 09:00
This is a duplicate of #5589

**Closed by neonichu** 2016-08-26 09:00 UTC
