### ISSUE TITLE
`abstract_target` and `inherit` lost framework search path

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7828] opened 2018-06-13 10:48 UTC
I write a Podfile:
```
    target 'IM' do
        platform :ios, '8.0'
        project 'IM/IM.xcodeproj'
        inherit! :search_paths
        foundationPods
    end
```
the xcconfig:
```
FRAMEWORK_SEARCH_PATHS = $(inherited) "${PODS_ROOT}/Crashlytics/iOS" "${PODS_ROOT}/Fabric/iOS" "${PODS_ROOT}/HTSSDKManager/HTSSDKManager/QQPlatform" "${PODS_ROOT}/PLCrashReporter/iOS Framework" "${PODS_ROOT}/SecGuard/Binary" "${PODS_ROOT}/TOCropViewController/ios" "${PODS_ROOT}/UMengAnalytics/umsdk_IOS_analyics_idfa_v4.1.10" "${PODS_ROOT}/YYImage/Vendor"
```
But, I think that It is wrong way, so I change to : 
```
abstract_target 'Library' do
    foundationPods

    target 'IM' do
        platform :ios, '8.0'
        project 'IM/IM.xcodeproj'
        inherit! :search_paths
    end
end
```

But I could not find the framework from the dependencies, the xcconfig:
```
FRAMEWORK_SEARCH_PATHS = $(inherited)
```

Is it a bug?

**Comment by segiddins** [comment] 2018-06-13 14:28
It’s because you’re trying to inherit from an abstract target, so you actually need to link the inherited pods since they’re not getting linked into any parent target

**Comment by dnkoutso** [comment] 2018-06-13 15:03
I do not think this is a bug. It could have been a potential incorrect configuration < 1.6.0 (master for now) but it has been fixed with the build settings re-write.

**Comment by Whirlwind** [comment] 2018-06-13 15:09
@segiddins if my project has not any app target and only one Library target, what should I do?

**Comment by Whirlwind** [comment] 2018-06-13 15:11
@dnkoutso I could not understand what you said.

**Comment by segiddins** [comment] 2018-06-13 15:41
You’ll need to not use inherit search paths

**Comment by Whirlwind** [comment] 2018-06-14 03:33
The `IM` target is just a static library.

I think that it should not link any dependencies and copy the resources from the dependencies, and just a HEADER_SEARCH_PATHS and FRAMEWORK_SEARCH_PATHS to make the `import` to work. Is it right?

**Comment by Whirlwind** [comment] 2018-06-14 04:47
I am not sure....

**Comment by dnkoutso** [comment] 2018-06-14 05:05
Is it easy to try? I can try myself in a few days perhaps.

**Comment by Whirlwind** [comment] 2018-06-14 05:28
I check a project with CocoaPods v1.3.1, the `FRAMEWORK_SEARCH_PATHS` lost when use `inherit! :search_paths`, too.

Have I some misunderstandings about `inherit! :search_path` ?

**Comment by Whirlwind** [comment] 2018-06-14 05:34
> :search_paths The target inherits the search paths of the parent only.

It seems that it inherits the `HEADER_SEARCH_PATHS` only. The `copy resource shell` will be integrated into the user target, too.

**Comment by dnkoutso** [comment] 2018-06-14 14:45
It *might* be an issue but that does not appear to be a regression.

**Comment by Whirlwind** [comment] 2018-10-28 09:48
Are there some idea for this issue?

**Closed** 2019-02-14 07:35 UTC
Labels: s1:awaiting input
