### ISSUE TITLE
diff with pods.xcproject file

### ISSUE THREAD

**Issue by Tlz-1994** [CocoaPods/CocoaPods#10017] opened 2020-08-31 07:56 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

When `pod install` finished, there have different diff from a different device.

## What did you expect to happen?

because of our `podfile.lock` and`CocoaPods` version is the same, so I think we need to get the same `pods.xcproject ` diff.

## What happened instead?

`pods.xcproject ` is not the same.

## CocoaPods Environment

CocoaPods version 1.9.3
ruby version 2.6.3

**Comment by dnkoutso** [comment] 2020-08-31 17:15
I do not quite understand the issue report. I think you are saying running `pod install` changes your xcodeproj which is by design?

Can you please upload a sample app and clearly add steps to reproduce?

**Comment by Tlz-1994** [comment] 2020-09-01 08:23
![image](https://user-images.githubusercontent.com/14328694/91825247-95159a00-ec6e-11ea-9cb5-84d020daebe6.png)
When we run `pod install`，different devices will get different diffs like the uploaded image. But our `podfile.lock` and ruby version and everything is same. So it makes us wonder.
And we don't add `Pods/` in `.gitignore` file, so it's a disaster.

**Comment by Tlz-1994** [comment] 2020-09-08 08:19
[issue.zip](https://github.com/CocoaPods/CocoaPods/files/5186994/issue.zip)
This is our sample project, just like you see, we don't add `Pod/` in `.gitignore`, anyone can build the project without having to rely on cocoapods. But when someone runs `pod install`, will create some diff(Please look at the previous reply).
@dnkoutso

**Comment by dnkoutso** [comment] 2020-09-26 17:32
I was unable to reproduce with the current sample provided.

I committed an initial commit of the extracted project, used cocoapods 1.9.3 and run `pod install` and I saw 0 diff.

**Closed** 2020-10-04 04:58 UTC
Labels: s1:awaiting input, s6:need sample
