### ISSUE TITLE
I am currently getting "Updating local specs repositories" each time I run "pod install"

### ISSUE THREAD

**Issue by jcampbell05** [CocoaPods/CocoaPods#4999] opened 2016-03-08 10:16 UTC
Currently when I run `pod install` with 0.39 on OS X 10.11 I keep getting "Updating local specs repositories" and it takes a very very very long time. 

The expected behaviour is that it should only do this once or at the very least not take this long. I'm not sure if this is related to the on-going Github issues.

**Comment by runeb** [comment] 2016-03-08 10:22
Same here. Just spent 90 minutes waiting for master repo setup, now with `pod install` it hangs on "Updating local specs repositories", which as far as I know does the exact same thing I just waited 90 minutes to complete.

**Comment by manuyavuz** [comment] 2016-03-08 10:32
It seems like currently Specs repo is very slow, I tried `git pull` on local repo located in `~/.cocoapods/repos/master/Specs`, and pull completed after a long 5 minutes.

Therefore, I'm pretty sure the hanging on is caused by the slowness in the GitHub.

in the meantime, you could just use `pod install --no-repo-update`, or wait until `git pull` to be completed if you really need a pod version which is not currently exist in the specs repo on your machine.

**Comment by jcampbell05** [comment] 2016-03-08 10:33
In light of this I am considering working on some techniques to using the HTTP APIs Github allows you to use for Repos. Not sure what you think @segiddins.

**Comment by art-divin** [comment] 2016-03-08 10:47
This is an ongoing problem since yesterday: https://github.com/CocoaPods/CocoaPods/issues/4989

**Comment by orta** [comment] 2016-03-08 11:57
This is a dupe of #4989

**Closed by orta** 2016-03-08 11:57 UTC
