### ISSUE TITLE
LoadError - cannot load such file -- cfpropertylist

### ISSUE THREAD

**Issue by kaushikdas0** [CocoaPods/CocoaPods#6382] opened 2017-01-07 02:12 UTC
Fresh install of cocoapod on Sierra 

╰─$ pod init

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod init
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin16]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.12.2 (16C67)
       Xcode : 8.2.1 (8C1002)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ c6f5b08e610b173c47d79fc2726757a313b0c511
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Error

```
LoadError - cannot load such file -- cfpropertylist
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/plist.rb:25:in `read_from_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:200:in `initialize_from_file'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-1.4.2/lib/xcodeproj/project.rb:102:in `open'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command/init.rb:41:in `validate!'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.1/lib/claide/command.rb:333:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

**Comment by benasher44** [comment] 2017-01-07 03:04
Hi @kaushikdas0! That's strange that this gem is missing on your system after an install. Can you try `gem install CFPropertyList`, and then try running your command again? Thanks!

**Comment by kaushikdas0** [comment] 2017-01-07 03:10
@benasher44 Hi, thanks for replying. Have tried that but with no luck

**Comment by benasher44** [comment] 2017-01-07 03:19
Okay. Can you try uninstalling cocoapods, and then installing it again?

**Comment by benasher44** [comment] 2017-01-07 03:20
Can you also try running your command in a fresh terminal once you've reinstalled? I had an issue like this earlier today, and a fresh terminal window fixed things.

**Comment by DanToml** [comment] 2017-01-07 07:40
This is a duplicate of #6214, please remove all versions of cfpropertylist `gem uninstall CFPropertyList`, and then `gem install CFPropertyList`

**Closed by DanToml** 2017-01-07 07:40 UTC
Labels: s4:awaiting validation

**Comment by virendramobisoft** [comment] 2017-02-23 10:08
@DanToml Above solution created [#6510](https://github.com/CocoaPods/CocoaPods/issues/6510)  issue in my case.

**Comment by akjesto** [comment] 2017-07-07 11:04
@DanToml  Thank you.Working fine.You are great

**Comment by rimiti** [comment] 2020-01-28 13:22
@endocrimes you saved my day, thx!
