### ISSUE TITLE
NameError - uninitialized constant Concurrent::Promises

### ISSUE THREAD

**Issue by tapz** [CocoaPods/CocoaPods#9188] opened 2019-09-25 21:17 UTC
### Command

```
/Users/tapani/.gem/bin/pod update
```

### Report

* What did you do?

pod update

* What did you expect to happen?

pods to be updated

* What happened instead?

CocoaPods crashed.

Searching for inspections failed: #<Pod::UserInterface::InspectorReporter:0x007fac2a1ab7a0> does not handle inspector_successfully_recieved_report

### Stack

```
   CocoaPods : 1.8.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.6
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0
Ruby lib dir : /Users/tapani/.rvm/rubies/ruby-2.2.1/lib
Repositories : master - git - https://github.com/CocoaPods/Specs.git @ d1d57f6995a8f879c3b5d40cdfe95f03dcb1fdc1
               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '10.2'
require_relative '../node_modules/@react-native-community/cli-platform-ios/native_modules'
project 'MyApp.xcodeproj'

def pods
  # Uncomment this line if you're using Swift or would like to use dynamic frameworks
  use_modular_headers!

  pod 'FBLazyVector', :path => "../node_modules/react-native/Libraries/FBLazyVector"
  pod 'FBReactNativeSpec', :path => "../node_modules/react-native/Libraries/FBReactNativeSpec"
  pod 'RCTRequired', :path => "../node_modules/react-native/Libraries/RCTRequired"
  pod 'RCTTypeSafety', :path => "../node_modules/react-native/Libraries/TypeSafety"

  pod 'React', :path => '../node_modules/react-native/'
  pod 'React-Core', :path => '../node_modules/react-native/'
  pod 'React-CoreModules', :path => '../node_modules/react-native/React/CoreModules'
  pod 'React-Core/DevSupport', :path => '../node_modules/react-native/'
  pod 'React-RCTActionSheet', :path => '../node_modules/react-native/Libraries/ActionSheetIOS'
  pod 'React-RCTAnimation', :path => '../node_modules/react-native/Libraries/NativeAnimation'
  pod 'React-RCTBlob', :path => '../node_modules/react-native/Libraries/Blob'
  pod 'React-RCTImage', :path => '../node_modules/react-native/Libraries/Image'
  pod 'React-RCTLinking', :path => '../node_modules/react-native/Libraries/LinkingIOS'
  pod 'React-RCTNetwork', :path => '../node_modules/react-native/Libraries/Network'
  pod 'React-RCTSettings', :path => '../node_modules/react-native/Libraries/Settings'
  pod 'React-RCTText', :path => '../node_modules/react-native/Libraries/Text'
  pod 'React-RCTVibration', :path => '../node_modules/react-native/Libraries/Vibration'
  pod 'React-Core/RCTWebSocket', :path => '../node_modules/react-native/'
  pod 'React-cxxreact', :path => '../node_modules/react-native/ReactCommon/cxxreact'
  pod 'React-jsi', :path => '../node_modules/react-native/ReactCommon/jsi'
  pod 'React-jsiexecutor', :path => '../node_modules/react-native/ReactCommon/jsiexecutor'
  pod 'React-jsinspector', :path => '../node_modules/react-native/ReactCommon/jsinspector'
  pod 'ReactCommon/jscallinvoker', :path => "../node_modules/react-native/ReactCommon"
  pod 'ReactCommon/turbomodule/core', :path => "../node_modules/react-native/ReactCommon"
  pod 'Yoga', :path => '../node_modules/react-native/ReactCommon/yoga'
  pod 'DoubleConversion', :podspec => '../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec'
  pod 'glog', :podspec => '../node_modules/react-native/third-party-podspecs/glog.podspec'
  pod 'Folly', :podspec => '../node_modules/react-native/third-party-podspecs/Folly.podspec'
end

target 'MyApp' do
    pods
end

```

### Error

```
NameError - uninitialized constant Concurrent::Promises
/Users/tapani/.gem/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:62:in `block in preheat_existing_files'
/Users/tapani/.gem/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:61:in `map'
/Users/tapani/.gem/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:61:in `preheat_existing_files'
/Users/tapani/.gem/gems/cocoapods-core-1.8.0/lib/cocoapods-core/cdn_source.rb:253:in `update'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:122:in `block (3 levels) in update'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:121:in `block (2 levels) in update'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:120:in `each'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:120:in `block in update'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:118:in `open'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/sources_manager.rb:118:in `update'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:145:in `block in update_repositories'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:143:in `each'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/installer/analyzer.rb:143:in `update_repositories'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:230:in `block in resolve_dependencies'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:229:in `resolve_dependencies'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/installer.rb:156:in `install!'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/command/update.rb:63:in `run'
/Users/tapani/.rvm/gems/ruby-2.2.1@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/tapani/.gem/gems/cocoapods-1.8.0/lib/cocoapods/command.rb:52:in `run'
/Users/tapani/.gem/gems/cocoapods-1.8.0/bin/pod:55:in `<top (required)>'
/Users/tapani/.gem/bin/pod:23:in `load'
/Users/tapani/.gem/bin/pod:23:in `<main>'
/Users/tapani/.gem/bin/ruby_executable_hooks:15:in `eval'
/Users/tapani/.gem/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dnkoutso** [comment] 2019-09-25 21:24
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9177 and fixed already to be shipped with 1.8.1.

Solution is to `gem update concurrent-ruby` to update its version to at least 1.1.x...

**Closed by dnkoutso** 2019-09-25 21:24 UTC
