### ISSUE TITLE
Newly created swift framework pod fails to be found when installed in a clean project

### ISSUE THREAD

**Issue by dglancy** [CocoaPods/CocoaPods#3277] opened 2015-03-17 07:32 UTC
This is my first swift-based dynamic framework pod I've created, so perhaps I've done something wrong.

Podfile:

```
platform :ios, '8.0'
use_frameworks!

pod 'ClinchKit' 
```

When I run the project, (in simulator or device, its a universal framework), I get:

```
dyld: Library not loaded: @rpath/ClinchKit.framework/ClinchKit
  Referenced from: /Users/dglancy/Library/Developer/CoreSimulator/Devices/62EE8B10-0D32-41DB-A910-D6FB6159E1FC/data/Containers/Bundle/Application/DEC1E760-9641-410B-8EC1-BB451B4B7C79/CoffeDock-Swift.app/CoffeDock-Swift
  Reason: image not found
```

If I add the framework manually to the project as a `Embedded Binary` (which Xcode adds as a copy step in the build phase), then everything works great. But if I add it as a Pod then I get this runtime issue.

Any ideas?

**Comment by neonichu** [comment] 2015-03-17 08:05
Could you also share the podspec with us?

**Comment by dglancy** [comment] 2015-03-17 08:14
```
Pod::Spec.new do |s|
  s.name = "ClinchKit"
  s.version = "1.0"
  s.summary = "The Clinch iOS SDK, for integrating Clinch into your iOS application"
  s.description = 'The Clinch iOS SDK, for integrating Clinch into your iOS application. The SDK supports iOS 8.'
  s.homepage = "https://github.com/ClinchIO/ClinchKit"
  s.license = { :type => "MIT", :file => "LICENSE" }
  s.authors = { "Damien Glancy" => "damien@clinch.io", "Steve Quinlan" => "steve@clinch.io" }
  s.social_media_url = "http://twitter.com/clinch"
  s.source = { :git => 'https://github.com/ClinchIO/ClinchKit.git', :tag => s.version.to_s }
  s.requires_arc = true
   
  s.platform = :ios, '8.0'
  s.ios.platform = :ios, '8.0'
  s.ios.preserve_paths = 'ClinchKit.framework'
  s.ios.public_header_files = 'ClinchKit.framework/Headers/*.h'
  s.ios.vendored_frameworks = 'ClinchKit.framework'
end
```

**Comment by neonichu** [comment] 2015-03-17 08:26
Ah, it's a `vendored_framework` - you didn't do anything wrong then, unfortunately vendored dynamic frameworks aren't embedded by CocoaPods, yet. Closing as a duplicate of #1993

**Closed by neonichu** 2015-03-17 08:26 UTC

**Comment by neonichu** [comment] 2015-03-17 08:28
BTW, in case you're not aware,  warns against binary frameworks written in Swift: <https://developer.apple.com/swift/blog/?id=2>

**Comment by dglancy** [comment] 2015-03-18 13:04
Thanks @neonichu for the info.

**Comment by yuvirajsinh** [comment] 2021-01-05 05:52
> BTW, in case you're not aware,  warns against binary frameworks written in Swift: https://developer.apple.com/swift/blog/?id=2

Is it still valid with ABI stability?
