### ISSUE TITLE
Cocoapods does not create framework target for Google analytics

### ISSUE THREAD

**Issue by vminc** [CocoaPods/CocoaPods#6615] opened 2017-04-03 04:29 UTC
My cocoapods file specifies Google Analytics framework target for my project

```
use_frameworks!
pod "Google/Analytics"
```

However after the pod is installed, I cannot see the GoogleAnalytics framework target generated, and I still need to import the Google Analytics header in my bridging header file. What did I miss here?

The full pod file is
```
use_frameworks!

target 'AnalyticsKit' do
  use_frameworks!
  workspace 'MY'
  project 'AnalyticsKit/AnalyticsKit.xcodeproj'
  platform :ios, '8.0'
  pod "Google/Analytics"
end
```

**Comment by dnkoutso** [comment] 2017-04-03 04:34
@vminc This is expected behavior. The pods being installed (with the exception of `GoogleToolboxForMac`) are pre-built pods. There is no need to create a target if there are no sources to build.

Closing as this is working as intended.

**Comment by dnkoutso** [comment] 2017-04-03 04:34
Also see the generated `xcconfig` flags:

```
OTHER_LDFLAGS = $(inherited) -ObjC -l"GoogleAnalytics" -l"c++" -l"sqlite3" -l"stdc++" -l"z" -framework "AddressBook" -framework "AssetsLibrary" -framework "CoreData" -framework "CoreFoundation" -framework "CoreLocation" -framework "CoreMotion" -framework "FirebaseAnalytics" -framework "FirebaseCore" -framework "FirebaseInstanceID" -framework "GGLAnalytics" -framework "GGLCore" -framework "GoogleToolboxForMac" -framework "MessageUI" -framework "StoreKit" -framework "SystemConfiguration"
```

**Closed by dnkoutso** 2017-04-03 04:34 UTC

**Comment by vminc** [comment] 2017-04-03 04:42
Thanks, how do I import "GAI.h" from this framework without using a bridging header? I import GGLAnalytics but "GAI.h" is not there. The problem is I want to use this module in a framework in which a bridging header is not supported...

**Comment by vminc** [comment] 2017-04-03 04:53
I run into the same problem with the "GoogleAnalytics" pod as well (it's a different pod from "Google/Analytics")

```
use_frameworks!
pod "GoogleAnalytics"
```

**Comment by dnkoutso** [comment] 2017-04-03 04:53
Is this in Swift or ObjC? In ObjC I did `#import <GoogleAnalytics/GAI.h>` and worked.

For Swift this worked for me:

```swift
import Google.Analytics

func hello() -> String {
    GAI();
    return "";
}
```

**Comment by vminc** [comment] 2017-04-03 05:03
This is swift code. I can "import Google.Analytics"  without errors, however I still got "Unresolved identifier" when referencing GAI.

**Comment by freegor** [comment] 2017-06-21 15:23
@vminc  Are you have it resolved?
