### ISSUE TITLE
setting EXCLUDED_ARCHS not working for main app project using pods 1.10 RC1 and Xcode 12

### ISSUE THREAD

**Issue by BalkiX** [CocoaPods/CocoaPods#10086] opened 2020-09-23 13:05 UTC
# Report

## What did you do?

Have a podspec with next two lines:
s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }

Run `pod install`

## What did you expect to happen?

expected is no error

## What happened instead?

you will see next error on app build:
Pods-XXX.debug.xcconfig Ignoring build settings configuration file Pods-XXX.debug.xcconfig due to an error: String 'EXCLUDED_ARCHS[sdk = iphonesimulator*] = arm64' could not be parsed: macro string representation 'EXCLUDED_ARCHS[sdk = iphonesimulator*]' isn't well formed: couldn't resolve the parameter name. 

NOTE: just updating EXCLUDED_ARCHS in xcconfig to have no spaces between sdk and = and iphonesimulator solves the problem.
Like this: 'EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64'

### Stack

```
   CocoaPods : 1.10.0.rc.1
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin20]
    RubyGems : 3.1.2
        Host : macOS 11.0 (20A5374i)
       Xcode : 12.0 (12A7209)
         Git : git version 2.28.0
Ruby lib dir : /Users/peternusios/.rvm/rubies/ruby-2.7.0/lib
Repositories : infor-scm-xos-cocoapodsspecs - git - http://git.infor.com/scm/xos/cocoapodsspecs.git @ 97a963c77cc984f29a798f7d976d2824900174a0

               localPodspecRepo - git - /Users/peternusios/Developer/cocoapodsspecs @ e8b0427595271c2763d0ee48e468909c9441a8cf

               master - git - https://github.com/CocoaPods/Specs.git @ 14358c7be6b03c9d0f55fd1933a5dadd7b089ac4

               staysortedhq - git - https://github.com/StaySortedHQ/Specs.git @ bf9944c82620408a824b70c25164fc2e430f2567

               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /Users/peternusios/.rvm/rubies/ruby-2.7.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-trunk       : 1.5.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '13.0'

source 'http://git.infor.com/scm/xos/cocoapodsspecs.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
use_modular_headers!

#AppCoreVersion = '~> 1.1.0'
CUIVersion = '~> 2.5.0'
InforAuthenticationVersion = '~> 5.0.0'

workspace 'Infor.AppSkeleton'

def sharedCoreFrameworks
  # Common UI
  pod 'XiColors'
  pod 'InforCommonUICore', CUIVersion
  pod 'InforCommonUIAnalytics', CUIVersion
  pod 'InforCommonUIGetStarted', CUIVersion
  pod 'InforCommonUIPasscode', CUIVersion
  pod 'InforCommonUIQRCode', CUIVersion
  pod 'InforCommonUIServerSettings', CUIVersion
  pod 'InforCommonUISplashScreen', CUIVersion
  pod 'InforCommonUIUserDetails', CUIVersion
  
  # Logging framework
  pod 'SwiftyBeaver', :configurations => ['Debug']
  # Network
  pod 'ReachabilitySwift', '~> 5.0.0'
  pod 'InforAuthentication', InforAuthenticationVersion
end

target 'InforAppCoreLogging' do
  project 'AppCoreFrameworks/InforAppCoreLogging'
  pod 'SwiftyBeaver', :configurations => ['Debug']
end

target 'InforAppCoreCommunicator' do
  project 'AppCoreFrameworks/InforAppCoreCommunicator'
  pod 'InforCommonUICore', CUIVersion
end

target 'InforAppCoreObjectModel' do
  project 'AppCoreFrameworks/InforAppCoreObjectModel'
  pod 'InforCommonUICore', CUIVersion
end

target 'InforAppCoreSettings' do
  project 'AppCoreFrameworks/InforAppCoreSettings'
  pod 'InforCommonUICore', CUIVersion
  pod 'InforCommonUIServerSettings', CUIVersion
end

target 'InforAppCore' do
  project 'AppCoreFrameworks/InforAppCore'
  sharedCoreFrameworks
end

target 'Infor.AppSkeleton' do
    project 'Infor.AppSkeleton.xcodeproj'
    sharedCoreFrameworks
    
    # Crashlytics
    pod 'Firebase/Crashlytics'
    # Analytics
    pod 'Firebase/Analytics'
    
    # Common UI
    pod 'InforCommonUIColors', CUIVersion
    pod 'InforCommonUISideMenu', CUIVersion
    pod 'InforCommonUISidePanel', CUIVersion
    pod 'InforCommonUIUserDetails', CUIVersion

    # Other
    pod 'SVGKit', :git => 'https://github.com/SVGKit/SVGKit.git', :branch => '3.x'
end
```

**Comment by dnkoutso** [comment] 2020-09-23 15:22
I wonder if this actually an Xcode bug...CocoaPods doesn't do a lot of magic there just adds the key/value in the xcconfig.

Can you try to check if using an xcconfig file in Xcode 12 without CocoaPods has the same issue? If so we can close this and a Feedback ticket should be filed.

**Comment by BalkiX** [comment] 2020-09-23 17:28
> I wonder if this actually an Xcode bug...CocoaPods doesn't do a lot of magic there just adds the key/value in the xcconfig.
> 
> Can you try to check if using an xcconfig file in Xcode 12 without CocoaPods has the same issue? If so we can close this and a Feedback ticket should be filed.

You wrote that Cocoapods writes it to xconfig and in xconfig it is wrong with the spaces, while in podspec there are no spaces.

**Comment by dnkoutso** [comment] 2020-09-25 15:53
i still havent quite understood the issue here.

Your report starts with:
```
s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
```

No spaces and looks like a correct Ruby hash.

Then you say:
```
NOTE: just updating EXCLUDED_ARCHS in xcconfig to have no spaces between sdk and = and iphonesimulator solves the problem.
```

But above you do not show any spaces?

And then you say:
```
Like this: 'EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64'
```

Which is _not_ a Ruby hash and and its a string.

**Comment by BalkiX** [comment] 2020-09-25 18:13
> i still havent quite understood the issue here.
> 
> Your report starts with:
> 
> ```
> s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
> ```
> 
> No spaces and looks like a correct Ruby hash.
> 
> Then you say:
> 
> ```
> NOTE: just updating EXCLUDED_ARCHS in xcconfig to have no spaces between sdk and = and iphonesimulator solves the problem.
> ```
> 
> But above you never showed you have any spaces?
> 
> And then you say:
> 
> ```
> Like this: 'EXCLUDED_ARCHS[sdk=iphonesimulator*] = arm64'
> ```
> 
> Which is _not_ a Ruby hash and and its a string.

Hi,
below two lines is what is written in my podspec:
s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }
s.user_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'arm64' }

and this line is what I see in xconfig created by cocoaPods:
EXCLUDED_ARCHS[sdk = iphonesimulator*] = arm64

manually updating xconfig by removing spaces fixes the build, therefore I mentioned it to be clear what exactly is the issue.
HTH

**Comment by dnkoutso** [comment] 2020-09-26 17:09
You are right this is what happens but this appears to be no issue for me on Xcode 12. And no warning either.

![Uploading Screen_Shot_2020-09-26_at_10_08_26_AM.png…]()

**Comment by dnkoutso** [comment] 2020-09-26 17:12
I tried both `s.pod_target_xcconfig` _and_ `s.user_target_xcconfig` as you said.

I cannot reproduce at this time.

**Comment by dnkoutso** [comment] 2020-09-26 17:14
please upload a sample app demonstrating the issue. I cant get the spaces to show up in any kind of configuration.

**Comment by BalkiX** [comment] 2020-09-30 14:25
Sorry, the issue was directly in my post install script:
`# write build_settings dictionary to xcconfig
  new_build_settings.each do |key,value|
      File.open(xcconfig_path, "a") {|file| file.puts "#{key} = #{value}"}
  end`

**Closed** 2020-09-30 14:31 UTC
Labels: s6:need sample

**Comment by deepesh-vasthimal-cko** [comment] 2021-02-16 11:04
@dnkoutso, Is there a way to add below inside my pod file ? instead of podspec. Reason being i need to exclude i386 and I dont own the 3rd party pod, So i want to force it to exclude the arch i386 myself. Please help. 

`s.pod_target_xcconfig = { 'EXCLUDED_ARCHS[sdk=iphonesimulator*]' => 'i386' }`

**Comment by deepesh-vasthimal-cko** [comment] 2021-02-16 11:05
I think i got it from here : https://github.com/CocoaPods/CocoaPods/issues/10104. let me try this. 

```
post_install do |installer|
  installer.pods_project.build_configurations.each do |config|
    config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386"
  end
end
```

**Comment by deepesh-vasthimal-cko** [comment] 2021-02-16 11:17
> @dnkoutso I think i got it from here : #10104. let me try this.
> 
> ```
> post_install do |installer|
>   installer.pods_project.build_configurations.each do |config|
>     config.build_settings["EXCLUDED_ARCHS[sdk=iphonesimulator*]"] = "i386"
>   end
> end
> ```

This worked.
