### ISSUE TITLE
Umbrella header with MyProject-umbrella.h name instead of MyProject.h not working for me

### ISSUE THREAD

**Issue by Gargam** [CocoaPods/CocoaPods#5351] opened 2016-05-17 19:29 UTC
[*] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Try to create a swift/objc framework based on .a static library

## What did you expected to happen?

I expect it to work :)

## What happened instead?

The generated umbrella header and its reference in the modulemap is "ProjectName-umbrella.h".
On some rare occasion, the generated objective-c header file (MyProject-Swift.h) try to import ```<ProjectName/ProjectName.h>```, this will not work because the umbrella header is named ProjectName-umbrella.h instead of ProjectName.h

### Stack

```
   CocoaPods : 1.0.0
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/gargam/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a879778f04ab428f8416583435b0d14b07b4b9a1
```

### Installation Source

```
Executable Path: /Users/gargam/.rbenv/versions/2.3.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
use_frameworks!

target 'MyProject_Example' do
  pod 'MyProject', :path => '../'
  pod 'MyProject/Dep1', :path => '../'
  pod 'MyProject/StaticLibraryDep2', :path => '../'
end
```

Maybe I misunderstood something, but right now I don't know how to proceed, I've spent the day trying to read all about module map etc.

**Comment by neonichu** [comment] 2016-05-17 19:45
I believe this is a duplicate of #3767

**Closed by neonichu** 2016-05-17 19:45 UTC
