### ISSUE TITLE
Configuration based resources no longer work in 1.0.0.beta.5

### ISSUE THREAD

**Issue by twoboxen** [CocoaPods/CocoaPods#5010] opened 2016-03-09 16:41 UTC
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

The podfile has
    pod 'HockeySDK', '3.8.5', :configurations => ['Debug', 'QA', 'Alpha']

ran "pod install"

tried to build the ios app

## What did you expected to happen?

All my hockey resources are found and copied into the app

## What happened instead?

Resource "/Users/me/Library/Developer/Xcode/DerivedData/TestApp-cnufknpuwsvwpccgsbdbndfrctzv/Build/Intermediates/ArchiveIntermediates/TestApp (QA)/BuildProductsPath/QA-iphoneos/HockeySDK/HockeySDKResources.bundle" not found. Run 'pod install' to update the copy resources script.

## Podfile

```ruby
platform :ios, '8.0'

workspace 'TestApp'

source 'https://github.com/CocoaPods/Specs.git'

# ignore all warnings from all pods
inhibit_all_warnings!

target 'TestApp' do
    pod 'HockeySDK', '3.8.5', :configurations => ['Debug', 'QA', 'Alpha']
end
```

**Comment by segiddins** [comment] 2016-03-09 16:53
This is likely a duplicate of https://github.com/CocoaPods/CocoaPods/issues/4963.

**Closed by segiddins** 2016-03-09 16:53 UTC
