### ISSUE TITLE
Can't push pod to my spec but passes local validation

### ISSUE THREAD

**Issue by m-sugawara** [CocoaPods/CocoaPods#3154] opened 2015-02-17 07:07 UTC
Hello, I'm trying to push a pod to the my spec.
My CocoaPods version is 0.35.0. latest.

It does pass local validation:

```
pod spec lint --allow-warnings mypods.podspec

 -> mypods (1.0.4)
    - WARN  | [source] Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.

Analyzed 1 podspec.

mypods.podspec passed validation.
```

```
pod lib lint --allow-warnings mypods.podspec

 -> mypods (1.0.4)
    - WARN  | [source] Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.

mypods passed validation.
```

However when trying to push to my spec I get:

```
pod repo push --allow-warnings myspecs mypods.podspec

Validating spec
[!] The `mypods.podspec` specification does not validate.
```

--verbose option

```
pod repo push --verbose myspecs mypods.podspec

Validating spec
    mypods (1.0.4) - Analyzing on iOS platform.
  Preparing

Analyzing dependencies

Inspecting targets to integrate

Fetching external sources
-> Fetching podspec for `mypods` from `/Users/[****my_user****]/github/mypods/mypods/mypods.podspec`

Resolving dependencies of 
[!] The `mypods.podspec` specification does not validate.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:90:in `rescue in block in validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:87:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:84:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:84:in `validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:42:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

This is mypods.podspec file

```
Pod::Spec.new do |s|
  s.name         = "mypods"
  s.version      = "1.0.4"
  s.summary      = "A long description of mypods."
  s.homepage     = "https://github.com/m-sugawara/mypods"
  s.license      = { :type => "MIT", :file => "LICENSE.txt" }
  s.author             = { "m-sugawara" => "https://github.com/m-sugawara" }
  s.platform     = :ios
  s.source       = { :git => "git@github.com:m-sugawara/mypods.git", :tag => "1.0.4", :commit => "b33e0358e2ce80540fbd927b02ab99147fa644b3" }
  s.source_files  = "Classes", "Classes/**/*.{h,m}", "mypods/Classes/**/*.{h,m}"
  s.requires_arc = true
end
```

**Comment by segiddins** [comment] 2015-02-17 16:11
Had you pushed that tag to github yet?

**Comment by m-sugawara** [comment] 2015-02-17 20:49
Yes, I already had pushed that tag to github.

This is my command
```
git tag -a "1.0.4" -m "version1.0.4"
git push origin --tags
```

**Comment by kylef** [comment] 2015-02-18 23:40
Strange how `pod spec lint` passes but repo push didn't and doesn't really show a reason.

I spotted this in your podspec: `:tag => "1.0.4", :commit => "b33e0358e2ce80540fbd927b02ab99147fa644b3"`, you've specified both a tag and a commit. You should only have one or the other (and preferably a tag).

**Comment by m-sugawara** [comment] 2015-02-19 01:54
@kylef 
Thank you for your response.
I deleted `:commit => "b33e0358e2ce80540fbd927b02ab99147fa644b3"` from my podspec, and try `pod repo push --allow-warnings myspecs mypods.podspec` command. but it does not passed validation.
I also deleted `:tag => "1.0.4"` from my podspec. but it does not passed validation too.

This is my latest mypods.podspec file
```
Pod::Spec.new do |s|
  s.name         = 'mypods'
  s.version      = '1.0.4'
  s.summary      = 'hello my pods!!'
  s.homepage     = 'https://github.com/m-sugawara/mypods'
  s.license      = { :type => 'MIT', :file => 'LICENSE.txt' }
  s.platform     = 'ios'
  s.author             = { 'm-sugawara' => 'm_sugawara@mydomain.com' }
  s.source       = { :git => 'https://github.com/m-sugawara/mypods.git', :tag => '1.0.4' }
  s.source_files  = 'mypods/Classes/**/*.{h,m}'
  s.requires_arc = true
end
```

**Comment by m-sugawara** [comment] 2015-02-19 02:13
This is my pods repo list, and I try `push` all repo except master. but it does not passed validation.

```
pod repo list

master
- Type: git (origin)
- URL:  https://github.com/CocoaPods/Specs.git
- Path: /Users/[****my_user****]/.cocoapods/repos/master

myspecs
- Type: git (origin)
- URL:  https://github.com/m-sugawara/myspecs.git
- Path: /Users/[****my_user****]/.cocoapods/repos/myspecs

privatespecs
Could not get sha1 for HEAD. Skipping.
- Type: git ()
- URL:  
- Path: /Users/[****my_user****]/.cocoapods/repos/privatespecs

testPods
- Type: local copy
- Path: /Users/[****my_user****]/.cocoapods/repos/testPods

4 repos
```

```
pod repo push myspecs --allow-warnings mypods.podspec 

Validating spec
[!] The `mypods.podspec` specification does not validate.

pod repo push privatespecs --allow-warnings mypods.podspec 

Validating spec
[!] The `mypods.podspec` specification does not validate.

pod repo push testPods --allow-warnings mypods.podspec 

Validating spec
[!] The `mypods.podspec` specification does not validate.
```

**Comment by segiddins** [comment] 2015-02-19 06:08
As of https://github.com/CocoaPods/CocoaPods/commit/367c539ac1910f298ee2641db458dd896e9e4fc8, the underlying error message will be shown.

**Comment by m-sugawara** [comment] 2015-02-19 06:51
@segiddins 
Thank you for your prompt response.
I changed `push.rb` file as of 367c539, and try to `push`.
This message showed.

```
$ pod repo push myspecs mypods.podspec 

Validating spec
[!] The `mypods.podspec` specification does not validate.

undefined method `downcase' for nil:NilClass

/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:395:in `source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/sources_manager.rb:37:in `find_or_create_source_with_url'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:435:in `block in sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:434:in `map'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:434:in `sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:376:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:375:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer/analyzer.rb:58:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:184:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:106:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:105:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/installer.rb:90:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:304:in `install_pod'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:210:in `block in perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:206:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:206:in `perform_extensive_analysis'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/validator.rb:73:in `validate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:88:in `block in validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:84:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:84:in `validate_podspec_files'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command/repo/push.rb:42:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.7.0/lib/claide/command.rb:271:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/lib/cocoapods/command.rb:45:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.35.0/bin/pod:43:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by nickdep7** [comment] 2015-03-06 00:50
@m-sugawara just had the same issue, kinda new to cocoapods but what I had found was: 

That somehow I had pushed my pod spec to the repos folder under ~/.cocoapods/repos instead of under my REPO folder. Then when I corrected the terminal command for the repo push... I could not get the "pod repo push" to work but I could get the "pod spec lint" working 

So I was able to resolve this by removing my locally pushed pod spec folder from the ~/.cocoapods/repos/<REPO>/<POC SPEC FOLDER NAME>

http://guides.cocoapods.org/terminal/commands.html#pod_repo_push

Hope this helps others...

**Comment by m-sugawara** [comment] 2015-03-07 04:29
@nickdep7
Thank you for your response.
I tried to remove this.

‛‛‛
testPods
- Type: local copy
- Path: /Users/[****my_user****]/.cocoapods/repos/testPods
‛‛‛

And try ‛pod repo push‛ , it passed validation!
Thank you so much.

**Comment by brianpartridge** [comment] 2015-03-24 19:21
I was running into this same issue pushing to my private spec repo.  As a workaround, I moved `~/.cocoapods/repos/master` and made a symlink from `~/.cocoapods/repos/myspecrepo` to `~/.cocoapods/repos/master`. Then validation passed and the push succeeded.

I think this is related to sources and push wasn't using myspecrepo as a source. Perhaps `pod repo push` needs the same `--sources=` option as `pod spec lint`?

**Comment by segiddins** [comment] 2015-03-24 19:29
@brianpartridge `pod repo push` uses all available sources on the machine.

**Comment by brianpartridge** [comment] 2015-03-24 19:33
@segiddins well there's definitely a issue then because removing the master repo made the push validation work.  This is on 0.36. (sorry to hijack the thread)

**Comment by kylef** [comment] 2015-03-31 04:14
I'm going to close this issue since the OP's original issue has been resolved.

@brianpartridge Please file a new issue for your problem, and please include full steps to reproduce.

**Closed by kylef** 2015-03-31 04:14 UTC
Labels: s1:awaiting input

**Comment by brianpartridge** [comment] 2015-03-31 15:12
I can't repro. Maybe my local copy of the spec repo got out of date. Will open a new issue if it happens again. Thanks.

**Comment by zhipcui** [comment] 2015-10-21 08:20
pod repo push --verbose --allow-warnings

**Comment by sheetal-hemrom** [comment] 2016-09-29 02:22
@zhipcui OMG that thing just made it work.. I was stuck for hours

**Comment by zhonglaoban** [comment] 2017-02-24 09:56
i found that was  some changed file do not commit , so i tag another tag and it Pushing the  repo success

**Comment by zhangwei5436** [comment] 2018-02-13 08:56
Can you tell me  how  resolve the problem？？ @m-sugawara

**Comment by zhangwei5436** [comment] 2018-02-13 08:57
I have the same issue ,but i can't resolve it?

**Comment by zhangwei5436** [comment] 2018-02-13 09:30
thanks i resolved

**Comment by WadeZhao23** [comment] 2018-12-12 06:41
> thanks i resolved

How do u resolved this issue

**Comment by mfaani** [comment] 2022-04-06 21:42
Just ran into this. The problem was that the url of the `PodSpec` was incorrect.
The `pod lib lint` was succeeding on the mac, but given the incorrect URL in the `PodSpec` it was failing.

**Comment by paulb777** [comment] 2022-04-06 22:47
Try `pod spec lint`
