### ISSUE TITLE
Pod validation requires beta xcode when pod doesn't support watchOS

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#4129] opened 2015-09-05 22:41 UTC
```shell
$ pod --version
0.38.2

$ pod trunk push

[!] Found podspec `CGFloatType.podspec`
Updating spec repo `master`

Validating podspec
 -> CGFloatType (1.3.1)
    - ERROR | [watchOS] Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  |  [BEROR]error: There is no SDK with the name or path 'watchos'
    - NOTE  | [watchOS]  error: There is no SDK with the name or path 'watchos'

[!] The podspec does not validate.
```

```ruby
Pod::Spec.new do |spec|
  spec.name = 'CGFloatType'
  spec.version = '1.3.1'
  spec.summary = 'Provides various methods and functions to deal with CGFloat on 64-bit systems (CGFLOAT_IS_DOUBLE).'

  spec.description  = <<-DESC
    It's easy to forget that `CGFloat` may actually be a `double` despite it's
    name. On 64-bit systems, where `CGFLOAT_IS_DOUBLE` is set to 1 it will actually
    be a double.

    This may become cumbersome when you are developing an application where you
    want a single code base which builds for both 32-bit and 64-bit such as when
    developing against the 32-bit simulator and deploying arm64.

    CGFloatType is a simple pod which provides helper methods on `NSNumber` to help
    deal with this. Along with providing various rounding, and various other math
    functions which accept a `CGFloat`.
  DESC

  spec.homepage = 'https://github.com/kylef/CGFloatType'
  spec.license = { :type => 'BSD', :file => 'LICENSE' }
  spec.author = { 'Kyle Fuller' => 'kyle@fuller.li' }
  spec.social_media_url = 'http://twitter.com/kylefuller'
  spec.source = { :git => 'https://github.com/kylef/CGFloatType.git', :tag => "#{spec.version}" }
  spec.frameworks = ['CoreGraphics']
  spec.source_files = 'CGFloatType/CGFloatType.{h,m}'
  spec.requires_arc = true
end
```

**Comment by segiddins** [comment] 2015-09-05 22:46
This is a duplicate of a closed issue, I believe.

**Comment by kylef** [comment] 2015-09-05 23:06
@segiddins This is reproducible with CocoaPods 0.39.0.beta4 and there are no related commits since the tag which would fix this.

```
[I] $ pod --version
0.39.0.beta.4
[I] $ pod trunk push

[!] Found podspec `CGFloatType.podspec`
Updating spec repo `master`
Validating podspec
 -> CGFloatType (1.3.1)
    - ERROR | [watchOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | xcodebuild:  [BEROR]error: There is no SDK with the name or path 'watchos'
    - NOTE  | [watchOS] xcodebuild:  error: There is no SDK with the name or path 'watchos'

[!] The podspec does not validate.
```

**Comment by segiddins** [comment] 2015-09-06 01:18
I know. We decided not to fix it.

**Comment by kylef** [comment] 2015-09-06 01:23
@segiddins Can you link to the issue, I can't find it?

**Comment by segiddins** [comment] 2015-09-06 01:30
I'm away for the weekend, but I know we discussed this.

**Comment by kylef** [comment] 2015-09-06 01:31
"I'm away" yet you've commented three times on this issue  ¯\_(ツ)_/¯.

**Comment by neonichu** [comment] 2015-09-07 13:29
I believe @segiddins was talking about #3925

**Comment by segiddins** [comment] 2015-09-25 04:44
Closing as a duplicate. I'm in favor of people explicitly specifying supported platforms anyways.

**Closed by segiddins** 2015-09-25 04:44 UTC
Labels: d1:easy, t2:defect
