### ISSUE TITLE
Cannot run unit tests in new Swift pod

### ISSUE THREAD

**Issue by JimRoepcke** [CocoaPods/CocoaPods#7894] opened 2018-06-29 00:06 UTC
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- `pod lib create Rules`
- Answered all the questions with the default answers except say No to view based testing.
- Added my Swift files to the project's Classes folder.
- `pod install`
- Open the workspace.
- Cmd-U (Test).

## What did you expect to happen?

I expected tests to run.

## What happened instead?

Build succeeds, but with this warning:

```
ld: warning: directory not found for option '-F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.4.sdk/Developer/Library/Frameworks'
```

And this console output:

```
2018-06-28 16:55:48.943967-0700 xctest[39973:4152757] The bundle “Rules_Tests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-06-28 16:55:48.944105-0700 xctest[39973:4152757] (dlopen_preflight(/Users/jim/Library/Developer/Xcode/DerivedData/Rules-cymfcyukficsvsghhxyuhzarvneb/Build/Products/Debug-iphonesimulator/Rules_Tests.xctest/Rules_Tests): Library not loaded: @rpath/Rules.framework/Rules
  Referenced from: /Users/jim/Library/Developer/Xcode/DerivedData/Rules-cymfcyukficsvsghhxyuhzarvneb/Build/Products/Debug-iphonesimulator/Rules_Tests.xctest/Rules_Tests
  Reason: image not found)
Program ended with exit code: 82
```

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.4 (9F1027a)
         Git : git version 2.10.1
Ruby lib dir : /Users/jim/.rbenv/versions/2.3.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 8c2aa947e5c36c90ca3bb7fa510fc9b0474a9b9d
```

### Installation Source

```
Executable Path: /Users/jim/.gem/bin/pod
```

### Plugins

```
claide-plugins               : 0.9.2
cocoapods-deintegrate        : 1.0.2
cocoapods-keys               : 1.7.0
cocoapods-plugins            : 1.0.0
cocoapods-search             : 1.0.0
cocoapods-stats              : 1.0.0
cocoapods-trunk              : 1.3.0
cocoapods-try                : 1.1.0
cocoapods-update-if-you-dare : 0.1.1
slather                      : 2.3.0
```

### Podfile

```ruby
use_frameworks!

target 'Rules_Example' do
  pod 'Rules', :path => '../'

  target 'Rules_Tests' do
    inherit! :search_paths

    pod 'Quick', '~> 1.2.0'
    pod 'Nimble', '~> 7.0.2'
  end
end
```

**Comment by JimRoepcke** [comment] 2018-06-29 03:35
[sample.zip](https://github.com/CocoaPods/CocoaPods/files/2147671/sample.zip)

`pod lib create Sample`

Default answers except no view based testing.

Made these changes:

```patch
diff --git a/Example/Tests/Tests.swift b/Example/Tests/Tests.swift
index d9490f3..68b6fd8 100644
--- a/Example/Tests/Tests.swift
+++ b/Example/Tests/Tests.swift
@@ -8,6 +8,11 @@ class TableOfContentsSpec: QuickSpec {
     override func spec() {
         describe("these will fail") {
 
+            it("can instantiate Something") {
+                let it = Something()
+                expect(1) == 1
+            }
+            
             it("can do maths") {
                 expect(1) == 2
             }
diff --git a/Sample/Classes/ReplaceMe.swift b/Sample/Classes/ReplaceMe.swift
index e69de29..8887427 100644
--- a/Sample/Classes/ReplaceMe.swift
+++ b/Sample/Classes/ReplaceMe.swift
@@ -0,0 +1,6 @@
+
+public class Something {
+    public init() {
+
+    }
+}
```

Cmd-U.

Here's the build navigator output:

![image](https://user-images.githubusercontent.com/39997/42071889-acdb841c-7b12-11e8-884f-292b70b2efaa.png)

Here's the console output:

```
2018-06-28 20:34:03.866844-0700 xctest[42483:4284363] The bundle “Sample_Tests” couldn’t be loaded because it is damaged or missing necessary resources. Try reinstalling the bundle.
2018-06-28 20:34:03.867006-0700 xctest[42483:4284363] (dlopen_preflight(/Users/jim/Library/Developer/Xcode/DerivedData/Sample-ayndkytxavqevufkuuvxjnobntcr/Build/Products/Debug-iphonesimulator/Sample_Tests.xctest/Sample_Tests): Library not loaded: @rpath/Sample.framework/Sample
  Referenced from: /Users/jim/Library/Developer/Xcode/DerivedData/Sample-ayndkytxavqevufkuuvxjnobntcr/Build/Products/Debug-iphonesimulator/Sample_Tests.xctest/Sample_Tests
  Reason: image not found)
Program ended with exit code: 82
```

**Comment by dnkoutso** [comment] 2018-06-29 03:41
nice thanks!

**Comment by dnkoutso** [comment] 2018-06-29 04:44
<img width="1140" alt="screen_shot_2018-06-28_at_9_05_05_pm" src="https://user-images.githubusercontent.com/310370/42073566-554bb348-7b1c-11e8-9d1b-e2cc4a8394d8.png">

@JimRoepcke the problem is that your app host entry is not correct. Is this sample app created by pods or by you? I forget if pods automatically creates this workspace and therefore its a cocoapods bug. Set the app host and the tests ran for me.

**Comment by JimRoepcke** [comment] 2018-06-29 06:47
@dnkoutso yes, the sample app was created by CocoaPods. Thanks for your help!

**Comment by JimRoepcke** [comment] 2018-06-29 07:04
That fixed the problem for me.

And this change removed the build warning. Is this change correct?

```diff
diff --git a/Example/Rules.xcodeproj/project.pbxproj b/Example/Rules.xcodeproj/project.pbxproj
index 79ef828..ada7274 100644
--- a/Example/Rules.xcodeproj/project.pbxproj
+++ b/Example/Rules.xcodeproj/project.pbxproj
@@ -552,7 +552,7 @@
 			baseConfigurationReference = BC2669B97E4BE6ACA8D43DA8 /* Pods-Rules_Tests.debug.xcconfig */;
 			buildSettings = {
 				FRAMEWORK_SEARCH_PATHS = (
-					"$(SDKROOT)/Developer/Library/Frameworks",
+					"$(PLATFORM_DIR)/Developer/Library/Frameworks",
 					"$(inherited)",
 				);
 				GCC_PREPROCESSOR_DEFINITIONS = (
@@ -573,7 +573,7 @@
 			baseConfigurationReference = DEC1318F5438E8FEEC3ED424 /* Pods-Rules_Tests.release.xcconfig */;
 			buildSettings = {
 				FRAMEWORK_SEARCH_PATHS = (
-					"$(SDKROOT)/Developer/Library/Frameworks",
+					"$(PLATFORM_DIR)/Developer/Library/Frameworks",
 					"$(inherited)",
 				);
 				INFOPLIST_FILE = Tests/Info.plist;
```

**Comment by dnkoutso** [comment] 2018-06-29 07:05
probably yes. I am not familiar with `pod lib create` to be honest so I can't tell where the bug exactly is.

**Comment by dnkoutso** [comment] 2018-06-29 07:19
@JimRoepcke opened up a PR.

**Comment by amorde** [comment] 2018-07-13 17:33
Fixed in https://github.com/CocoaPods/pod-template/pull/229

**Closed by amorde** 2018-07-13 17:33 UTC
Labels: help wanted, s7:workaround available, t2:defect
