### ISSUE TITLE
Error on pod spec lint.

### ISSUE THREAD

**Issue by euroboy** [CocoaPods/CocoaPods#9198] opened 2019-09-27 13:40 UTC
When running `pod spec lint` I get the following error: _ERROR | [iOS] unknown: Encountered an unknown error (uninitialized constant Concurrent::Promises
Did you mean?  Concurrent::Promise_ . Cannot figure out how to solve this.

Cocoapods version: 1.8.0 (on 1.7.5 everything works).

**Comment by dnkoutso** [comment] 2019-09-27 14:23
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9188

Use `gem update concurrent-ruby`.

Also fixed with 1.8.1 release.

**Closed by dnkoutso** 2019-09-27 14:23 UTC
