### ISSUE TITLE
vendored_frameworks in static library pods

### ISSUE THREAD

**Issue by dcow** [CocoaPods/CocoaPods#3828] opened 2015-07-16 10:41 UTC
Our workspace has a few main app projects, a shared modules project, and the pods project. However, instead of direct dependencies on the targets in the modules project, we give each target a podspec and then have cocoapods handle taping it into the big libPods.a archive (which our app projects link against).

We have a pod that acts as a facade for a `vendored_framework` distribution. The spec for the framework from the vendor does not list the headers as public headers. However, it's a library and the only way to use it is with the headers. In other words, the fact that the headers are not visible is a mistake.

    app -> local development pod -> framework library pod

`Dev pod` can't see headers from `framework pod` at the time the `app` is built.

Is this an issue with the way CocoaPods handles packaging vendored_frameworks that are dependencies of static pod libraries, or is this working as expected and the vendor simply needs to update the spec to include the public headers explicitly? I ask because I kinda thought the point of a framework was that you didn't have to explicitly list all its components, and rather, that the details of such were conveyed conventionally via the structure of the framework.

**Comment by segiddins** [comment] 2015-07-16 14:13
This sounds like a bug, a PR with a fix would be very welcome!

**Comment by neonichu** [comment] 2015-07-17 07:02
Which version of CocoaPods are we talking about? AFAIK, 0.37 should symlink framework headers automatically, but I have seen some reports of issues with that for 0.38 beta.

**Comment by neonichu** [comment] 2015-07-17 07:04
See #3822 for the header issue in 0.38

**Comment by dcow** [comment] 2015-07-17 18:57
@neonichu I used 0.36 but have updated to 0.37.2 but neither worked for me.

**Comment by dcow** [comment] 2015-07-17 19:30
app -> local development pod -> framework library pod

App can't see headers from framework pod.
Local development pod *can* see framework headers.

**Comment by segiddins** [comment] 2015-07-17 20:16
Does the app actually declare a dependency on the framework pod?

**Comment by dcow** [comment] 2015-07-20 16:41
app -> dev pod-> framework

It's the `dev-pod -> framework` part that doesn't work when in the context above. App declares dependency on dev pod. Dev pod is the only code that uses framework and it declares the dependency in its pod spec. In other words, the goal is not for framework to be transitively available to app, but rather, simply for app to be able to build when depending on dev-pod. For that to happen dev-pod must see headers from framework.

**Comment by segiddins** [comment] 2015-08-01 20:36
@dcow a project that demonstrates the issue would be awesome!

**Comment by segiddins** [comment] 2015-08-25 07:30
This might be fixed by https://github.com/CocoaPods/CocoaPods/pull/3832, which sets `FRAMEWORK_SEARCH_PATHS`?

**Comment by segiddins** [comment] 2015-08-29 23:06
This should now be fixed in the betas, but I'm closing since we never got a project to reproduce.

**Closed by segiddins** 2015-08-29 23:06 UTC
Labels: s4:awaiting validation
