### ISSUE TITLE
"pod lib create" fails in CocoaPods 1.0.0.beta.3

### ISSUE THREAD

**Issue by juanjonol** [CocoaPods/CocoaPods#4877] opened 2016-02-08 19:10 UTC
`pod lib create` uses a Podfile with the `:exclusive => true` option, so when it run `pod install`, the installation fails.

**Comment by segiddins** [comment] 2016-02-08 21:14
This is a duplicate of several issues on the CocoaPods/pod-template repo -- the pod template will be updated once 1.0 final is released.

**Closed by segiddins** 2016-02-08 21:14 UTC
