### ISSUE TITLE
pod try BoringSSL. Fail 

### ISSUE THREAD

**Issue by QOFOL** [CocoaPods/CocoaPods#9597] opened 2020-03-07 09:29 UTC
Trying BoringSSL
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:138: warning: Passing the keyword argument as the last hash parameter is deprecated
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/pod_source_installer.rb:39: warning: The called method `initialize' is defined here

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod try BoringSSL
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.9.0
        Ruby : ruby 2.7.0p0 (2019-12-25 revision 647ee6f091) [x86_64-darwin18]
    RubyGems : 3.1.2
        Host : Mac OS X 10.14.6 (18G103)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /usr/local/Cellar/ruby/2.7.0/lib
Repositories : trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface.rb:118:in `title'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/command.rb:52:in `run'
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60root%27+for+false%3AFalseClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Looking for related issues on cocoapods/cocoapods...
/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface/inspector_reporter.rb:80: warning: URI.escape is obsolete
 - Error while installing SDWebImage  on my mac. 
   https://github.com/CocoaPods/CocoaPods/issues/9544 [closed] [2 comments]
   2 weeks ago

/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface/inspector_reporter.rb:80: warning: URI.escape is obsolete
 - error pod try MaterialComponents
   https://github.com/CocoaPods/CocoaPods/issues/9452 [closed] [1 comment]
   03 Jan 2020

/usr/local/lib/ruby/gems/2.7.0/gems/cocoapods-1.9.0/lib/cocoapods/user_interface/inspector_reporter.rb:80: warning: URI.escape is obsolete
 - pod try BEMCheckBox stacktrace
   https://github.com/CocoaPods/CocoaPods/issues/9415 [closed] [1 comment]
   17 Dec 2019

and 3 more at:
https://github.com/cocoapods/cocoapods/search?q=undefined%20method%20%60root%27%20for%20false%3AFalseClass&type=Issues&utf8=✓

**Comment by dnkoutso** [comment] 2020-03-09 16:42
Duplicate of https://github.com/CocoaPods/cocoapods-try/issues/63

**Closed by dnkoutso** 2020-03-09 16:42 UTC
