### ISSUE TITLE
.pch wont recognise included files

### ISSUE THREAD

**Issue by mikeRozen** [CocoaPods/CocoaPods#3318] opened 2015-03-26 15:40 UTC
Header import wont be recognised in .pch in the subsec
```
Pod::Spec.new do |s|
  s.name         = "YooshUiIos"
  s.version      = "0.0.2"
  s.summary      = "A short description of YooshUiIos."


s.frameworks   = ['Foundation', 'UIKit', 'CoreGraphics', 'QuartzCore']
#s.xcconfig = { 'OTHER_LDFLAGS' => '-force_load' }
s.prefix_header_file = 'YooshUiIos-Prefix.pch'
s.requires_arc = true
  s.description  = <<-DESC
                   A longer description of YooshUiIos in Markdown format.

                   * Think: Why did you write this? What is the focus? What does it do?
                   * CocoaPods will be using this to generate tags, and improve search results.
                   * Try to keep it short, snappy and to the point.
                   * Finally, don't worry about the indent, CocoaPods strips it!
                   DESC

  s.homepage     = "http://EXAMPLE/YooshUiIos"
  s.author       = { "Mike" => "blabla@gmail.com" }
  s.platform     = :ios, "7.0"
  s.source       = { :git => "git@bitbucket.org:bla/bla.git" }

s.public_header_files = 'UIHelpers/ARNStyles.h','UIHelpers/ARNCGAdditions.h'
s.source_files = 'UIHelpers/MGConferenceDatePicker/*.{h,m}','UIHelpers/ARNCGAdditions.{h,m}','UIHelpers/ARNStyles.{h,m}'


#ForkmatterKit - WorkAround Start------------------------------------------------------------
s.subspec 'AddressFormatter' do |ss|
   ss.requires_arc = true
#ss.public_header_files = "UIHelpers/ARNStyles.h","UIHelpers/ARNCGAdditions.h"
   ss.ios.source_files  = "Pods/FormatterKit/FormatterKit/TTTAddressFormatter.{h,m}"
 end

end
```

The validation with ```spec ``` will fail. Validation with ```lib ``` will pass. 
```
Pods-YooshUiIos-prefix.pch:24:9: fatal error: 'ARNStyles.h' file not found
```
When I use it as pod in my library everything  get downloaded and compiled.

Another strange issue that I notice is even when it pass validation and in case I have more then one supspec ONLY last subspec will be generated.... And I actually can see it in the logs that he rebuild every subspec from  beginning.
Can you please suggest what can be done?

**Comment by kylef** [comment] 2015-03-30 20:22
@mikeRozen Can you please add an example project or full steps to reproduce this issue? This pod spec won't work since the source is redacted.

**Comment by mikeRozen** [comment] 2015-03-31 06:08
**Kylef** Can you just include some ```.h``` file in the ```.pch```  and use it in   ```podsec``` and try to run a validation with ```spec``` and ```lib```(just make sure that you call ```.h``` in your original library).[http://stackoverflow.com/questions/28831636/podspec-prefix-import-not-found/29276039#29276039]


About the strange issue:when I create more than one ```subsec``` only the last one get created (in the validation project) when I read the logs I can see that for each ```subsec``` he make a build but only last directory get created in the *validation project*. 
Thanks.

**Comment by segiddins** [comment] 2015-07-05 19:51
Closing since we never got a runnable example project.

**Closed by segiddins** 2015-07-05 19:51 UTC
Labels: s1:awaiting input
