### ISSUE TITLE
macOS 10.15.4 + Cocoapods 1.9.1 [an error occurred while pod try]

### ISSUE THREAD

**Issue by beatman423** [CocoaPods/CocoaPods#9732] opened 2020-04-20 05:23 UTC
Before you start, are you using the latest CocoaPods release?
Yes I'm using CocoaPods 1.9.1. 

Xcode Version: 11.4.1 (11E503a).  

# Report

## What did you do?

Run `pod try Alamofire`

## What did you expect to happen?

To try if my CocoaPods is functioning.

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin19]
    RubyGems : 2.7.7
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.13.1
Ruby lib dir : /Users/biran/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - file system
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Error

```
NoMethodError - undefined method `root' for false:FalseClass
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.9.1/lib/cocoapods/installer/pod_source_installer.rb:179:in `root_spec'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.9.1/lib/cocoapods/installer/pod_source_installer.rb:192:in `predownloaded?'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.9.1/lib/cocoapods/installer/pod_source_installer.rb:69:in `install!'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:139:in `install_pod'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:50:in `block in run'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.9.1/lib/cocoapods/user_interface.rb:118:in `title'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-try-1.1.0/lib/pod/command/try.rb:49:in `run'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.9.1/lib/cocoapods/command.rb:52:in `run'
/Users/biran/.rvm/gems/ruby-2.4.1/gems/cocoapods-1.9.1/bin/pod:55:in `<top (required)>'
/Users/biran/.rvm/gems/ruby-2.4.1/bin/pod:23:in `load'
/Users/biran/.rvm/gems/ruby-2.4.1/bin/pod:23:in `<main>'
/Users/biran/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `eval'
/Users/biran/.rvm/gems/ruby-2.4.1/bin/ruby_executable_hooks:24:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60root%27+for+false%3AFalseClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Searching for inspections failed: #<Pod::UserInterface::InspectorReporter:0x007fb6e5d97da0> does not handle inspector_successfully_recieved_report

### Stack

```
   CocoaPods : 1.9.1
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin19]
    RubyGems : 2.7.7
        Host : Mac OS X 10.15.4 (19E287)
       Xcode : 11.4.1 (11E503a)
         Git : git version 2.13.1
Ruby lib dir : /Users/biran/.rvm/rubies/ruby-2.4.1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD

               master - file system
```

### Installation Source

```
Executable Path: /Users/biran/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

**Comment by dnkoutso** [comment] 2020-04-20 05:34
Duplicate of https://github.com/CocoaPods/cocoapods-try/issues/63 and fixed but haven't shipped yet.

**Closed by dnkoutso** 2020-04-20 05:34 UTC

**Comment by zhangwei5436** [comment] 2020-05-14 08:24
怎么解决
