### ISSUE TITLE
pod update error with specified git repo for  developing pod

### ISSUE THREAD

**Issue by aelam** [CocoaPods/CocoaPods#3545] opened 2015-05-09 16:33 UTC
In my Podfile , I specified a pod with a custom git repo which is a dependency of my developing pod.
See below 
In my Podfile
````
pod 'Nimbus/Models', :git=> 'https://github.com/aelam/nimbus.git'  # nimbus with custom repo 
pod 'Nimbus/Collections', :git=> 'https://github.com/aelam/nimbus.git' # nimbus with custom repo 
pod 'Seed', :path => '../SeedIOS/'   # developing pod
````
In my development pod `SeedIOS `
```
  s.dependency "Nimbus/Models"   , "~> 1.2.0"
  s.dependency "Nimbus/Collections"  , "~> 1.2.0"
  
```

Here is the log
### Command

```
/usr/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.1
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.4 (14E11f)
       Xcode : 6.3.1 (6D1002)
         Git : git version 2.4.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1fc14d637fd7ac9b21c415afa6e8da9acccc1a2d
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.0
cocoapods-try     : 0.4.4
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
 platform :ios, '7.0'
inhibit_all_warnings!

target 'TRAVEL' do

pod 'AFNetworking', '~> 2.5.1'
pod 'SDWebImage'
pod 'Masonry', '~> 0.6.1'
pod 'JLRoutes'
pod 'UIColor-HexString', '~> 1.0.1'
pod 'CocoaLumberjack',  '~> 1.8.1'
pod 'SFHFKeychainUtils', '~> 0.0.1'
pod 'NSString-UrlEncode', '~> 1.1.0'
pod 'NSDate+TimeAgo', '~> 1.0.3'
pod 'TOWebViewController'
pod 'Harpy'
#pod 'INTULocationManager'
pod 'FLEX', '~> 2.0.2'


#custom
 ##:podspec => 'podspecs/Nimbus.podspec'
 #, :git=> 'https://github.com/aelam/nimbus.git' ##, :tag => '1.2.1g'
pod 'Nimbus/Models', :git=> 'https://github.com/aelam/nimbus.git'
pod 'Nimbus/Collections', :git=> 'https://github.com/aelam/nimbus.git'
pod 'Seed', :path => '../SeedIOS/'

end

target 'TRAVELTests' do

end
```

### Error

```
Errno::ENOENT - No such file or directory - /tmp/d20150510-25770-16s2i7p
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `stat'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1552:in `block in fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1568:in `fu_each_src_dest0'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:1550:in `fu_each_src_dest'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/fileutils.rb:434:in `cp_r'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/downloader.rb:42:in `block in download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:110:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/downloader.rb:40:in `download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/abstract_external_source.rb:101:in `block in pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:70:in `titled_section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/abstract_external_source.rb:99:in `pre_download'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/external_sources/downloader_source.rb:13:in `fetch'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:347:in `fetch_external_source'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:324:in `block (2 levels) in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:323:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:323:in `block in fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:322:in `fetch_external_sources'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer/analyzer.rb:57:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:190:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:112:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/user_interface.rb:49:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:111:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/installer.rb:91:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.1/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by oferRounds** [comment] 2015-05-22 08:51
@aelam, were you mange to solve this one? Dealing with the same issue.

**Comment by aelam** [comment] 2015-05-22 10:24
@oferRounds  
I've moved the custom git repo out from Podfile, and use a specified podspec instead. 
It works

Replace
```` 
pod 'Nimbus/Models', :git=> 'https://github.com/aelam/nimbus.git'
pod 'Nimbus/Collections', :git=> 'https://github.com/aelam/nimbus.git'
````
with 
````
pod 'Nimbus', :subspecs => ['Models', 'Collections'], :podspec => 'podspecs/Nimbus.podspec'

````
Have a try

**Comment by oferRounds** [comment] 2015-05-22 10:29
Not sure how to apply the same logic in my case. This is my issue:
https://github.com/CocoaPods/CocoaPods/issues/3596

**Comment by oferRounds** [comment] 2015-05-22 10:38
Ok, thanks to a Friend I found it. This is a duplicate of this issue:
https://github.com/CocoaPods/CocoaPods/pull/3260

I had duplicated by mistake the lines:

target 'DatingApp' do

end

**Comment by gavrix** [comment] 2015-06-06 04:21
@aelam I believe that's because root directory in your custom pod's repos do not contain podspec file. See, when you specify 
```
pod 'Nimbus/Models', :git=> 'https://github.com/aelam/nimbus.git'
```
it will first checkout given repo, and then try to locate `Nimbus.podspec` (as in given pod name) in root directory of that repo to actually do pod resolution and setup it in the project. Your repos do not contain podspec files. 

I suggest this issue is invalid and should be closed.

**Comment by aelam** [comment] 2015-06-06 04:55
I think if I use a custom repo, it will  use origin podfile (in Specs.git) with my custom git repo code. 
For example, if I use nimbus with my custom repo, it will pull the podfile from specs.git and replaces the repo to my custom one 

Am I right ?


发自我的 iPhone

**Comment by gavrix** [comment] 2015-06-06 13:17
Of course not. Each version’s podspec is unique. It may or may not contain some sepcific features, different version may contain different set of source files to include and so on.
If you specify pod’s repo instead of pointing to a version of the pod in Specs.git, how could `cocoapods`  even know which version of your pod to pickup from Specs.git? 

Instead, you always specify podspec in your Podfile. When you set version, it’ll be looked up for in Specs.git, if set git repo - it’ll be looked up for in that repo’s root directory, or you may set podspec file path directly (how you solve your problem).

Don’t believe me — just add podspec to your custom Nimbuz repo and see what happens.

**Closed** 2015-06-06 15:53 UTC
