### ISSUE TITLE
Deterministic generation of project.pbxproj

### ISSUE THREAD

**Issue by apascual** [CocoaPods/CocoaPods#9359] opened 2019-11-21 08:07 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

1. Generate the project.pbxproj file using xcodegen (https://github.com/yonaskolb/XcodeGen)
2. Run pod install

## What did you expect to happen?

I would expect project.pbxproj to be the same after running the steps multiple times.

## What happened instead?

Xcodegen is deterministic and the generated project file is always the same for the same configurations and folders content.

On the other hand, CocoaPods is generating a different version of the project file every time, the UUIDs seem to be different and also the order of the build scripts.

### Stack

```
   CocoaPods : 1.8.4
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15.1 (19B88)
       Xcode : 11.2.1 (11B500)
         Git : git version 2.21.0 (Apple Git-122.2)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : axis-mobile-apps-ios-axis-specs - git - ssh://gittools.se.axis.com:29418/mobile-apps/ios-axis-specs @ b79f2d71e46ca32917be52679131738a95202179
               axispods - git - ssh://abelp@gittools.se.axis.com:29418/mobile-apps/ios-axis-specs @ d7c91a7601330090f61ee0dd5c4b1a5c9c85757d
               master - git - https://github.com/CocoaPods/Specs.git @ 263113829416c719e73c99bba6d99e9ec3b25e2e
               popcorntimetv - git - https://github.com/PopcornTimeTV/Specs @ d8e0d01c6912e797e9561f58f3534cec82db8b20
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '11.4'

def common_pods

  pod 'AnyCodable-FlightSchool', '0.2.3', :inhibit_warnings => true
  pod 'Bolts', '1.7.0', :inhibit_warnings => true
  pod 'CocoaLumberjack', '3.5.3', :inhibit_warnings => true
  pod 'KeychainAccess', '4.1.0', :inhibit_warnings => true
  pod 'KissXML', '5.3.1', :inhibit_warnings => true
  pod 'KVOController', '1.2.0', :inhibit_warnings => true
  pod 'Moya', '13.0.1', :inhibit_warnings => true
  pod 'MONActivityIndicator', '2.0.0', :inhibit_warnings => true
  pod 'ReachabilitySwift', '5.0.0', :inhibit_warnings => true
  pod 'SwiftLint', '0.37.0', :inhibit_warnings => true

end

target 'test' do

  common_pods

  target 'guardian-tests' do

    inherit! :search_paths
    pod 'Cuckoo', '1.3.0', :inhibit_warnings => true
    pod 'OCMock', '3.4.3', :inhibit_warnings => true
    pod 'SwiftHamcrest', '2.2.1', :inhibit_warnings => true

  end

end

target 'default' do
  common_pods
end

# Change deployment target for all pods.
# https://github.com/CocoaPods/CocoaPods/issues/7314

post_install do |pi|
  pi.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '11.4'
    end
  end
end
```

## Project that demonstrates the issue

https://github.com/apascual/DeterministicExample

**Comment by dnkoutso** [comment] 2019-12-03 16:25
I need a project that demonstrates the issue. On a sample app of mine with a git repo if I continuously run `pod install` I do not see any diff generated.

The project will always be re-written once with CocoaPods using its own UUID generator so I am not sure how this interacts with XcodeGen at all.

**Comment by apascual** [comment] 2019-12-03 21:29
> I need a project that demonstrates the issue. On a sample app of mine with a git repo if I continuously run `pod install` I do not see any diff generated.
> 
> The project will always be re-written once with CocoaPods using its own UUID generator so I am not sure how this interacts with XcodeGen at all.

Hi @dnkoutso, thank you for your reply, here is a project with steps to reproduce the issue: https://github.com/apascual/DeterministicExample

The non deterministic issue does not happen when you run multiple times pod install on the same project, but rather when you do the installation for first time multiple times using the same original project file. :)

**Comment by apascual** [comment] 2020-02-03 23:36
@dnkoutso Hi, could you remove the "need sample" tag, an example was provided some weeks ago. Thank you.

**Comment by amorde** [comment] 2020-02-06 23:10
Was able to confirm using your project, though this can be confirmed without `xcodegen`.

To reproduce:
1. Run `pod install`
2. Commit the modifications to the user project (not `Pods.xcodeproj`)
3. Run `pod deintegrate`
4. Run `pod install`

The user project will be different than the one that was committed. Currently CocoaPods only promises that the same UUIDs will be used when creating `Pods.xcodeproj`, not for the UUIDs integrated into your existing project.

This could be made 100% deterministic by either using a fixed random seed, or by manually patching the UUIDs that CocoaPods adds to your project. Xcodeproj currently uses a secure random number generator so the file references added to your project do not use deterministic UUIDs.

**Comment by apascual** [comment] 2020-02-07 08:09
Hi @amorde,

Thank you for the clarification. It feels like setting a fixed random seed is the way to go then, is it possible to configure that seed in CocoaPods or the functionality is currently missing?

Best regards.

**Comment by amorde** [comment] 2020-02-08 02:19
The functionality is currently missing - this would require changes to https://github.com/CocoaPods/Xcodeproj as well as CocoaPods

**Comment by apascual** [comment] 2020-02-10 08:59
> The functionality is currently missing - this would require changes to https://github.com/CocoaPods/Xcodeproj as well as CocoaPods

There is something that I don't understand, why would xcodegen require changes if it is already generating exact copies of the project file every time (including UUIDs)?

Thanks.

**Comment by amorde** [comment] 2020-02-11 04:59
Because the way CocoaPods does this for `Pods.xcodeproj` affects _all_ UUIDs. For this to work with the user project, we would want to only change the UUIDs of what CocoaPods adds to the project and nothing else. This isn't possible with how it's done currently

**Comment by grigorye** [comment] 2020-03-06 17:50
@amorde I'm not sure about this part:

> For this to work with the user project, we would want to only change the UUIDs of what CocoaPods adds to the project and nothing else.

I believe that for XcodeGen generated project there's no such a restriction, given that the project itself is regenerated before the integration of CocoaPods. The only desirable property here is that the UUIDs would be deterministic, whether they're completely changed by running `pod install` looks irrelevant.

@apascual You can try the following script as part of `postGenCommand`, after invocation of `pod install`, feed it with the path to .xcodeproj. I've just made it as a workaround (it's actually based on what I was able to grasp in CocoaPods sources and, as far as I understand, it should do the very thing in terms of UUIDs to the client project as CocoaPods doe to Pods.xcodeproj). At quick glance it works as expected - at least it generates stable .xcodeproj and I am able to build the project without a problem.

```
#! /usr/bin/ruby

# Based on
# https://github.com/CocoaPods/CocoaPods/blob/a1c94aaaa21b3da318208c7426433753c0332716/lib/cocoapods/installer.rb#L340

require 'xcodeproj'

project_path = ARGV[0]
project = Xcodeproj::Project.open(project_path)
Xcodeproj::Project::UUIDGenerator.new([project]).generate!
project.save()
```

**Comment by grigorye** [comment] 2020-03-09 02:33
@amorde I'm not sure about this part:

> For this to work with the user project, we would want to only change the UUIDs of what CocoaPods adds to the project and nothing else.

I believe that for XcodeGen generated project there's no such a restriction, given that the project itself is regenerated before the integration of CocoaPods. The only desirable property here is that the UUIDs would be deterministic, whether they're completely changed by running `pod install` or not, looks irrelevant.

@apascual You can try the following script as part of `postGenCommand`, after invocation of `pod install`, feed it with the path to .xcodeproj. I've just made it as a workaround (it's actually based on what I was able to grasp in CocoaPods sources and, as far as I understand, it should do the very thing in terms of UUIDs to the client project as CocoaPods doe to Pods.xcodeproj). At quick glance it works as expected - at least it generates stable .xcodeproj and I am able to build the project without a problem.

```
#! /usr/bin/ruby

# Based on
# https://github.com/CocoaPods/CocoaPods/blob/a1c94aaaa21b3da318208c7426433753c0332716/lib/cocoapods/installer.rb#L340

require 'xcodeproj'

project_path = ARGV[0]
project = Xcodeproj::Project.open(project_path)
Xcodeproj::Project::UUIDGenerator.new([project]).generate!
project.save()
```

Update: while the above script results in deterministic uuids, changing the project, e.g. removal of a source file, results in the changes in uuids of non-related objects (e.g. other sources files). This problem does not exist in pure XcodeGen generated pbxproj. I tried to find the difference between XcodeGen and CocoaPods generation of uuids, and at quick glance it's in tuist version of XcodeProj (https://github.com/tuist/XcodeProj) vs CocoaPods version of Xcoderoj (https://github.com/CocoaPods/Xcodeproj). So I gave it a try and was able to "implement" the tuist XcodeProj based variant of the script above. And, you know, it actually works, producing the changes only in the relevant uuids.

Feel free to give it a try. You'll need `brew install swift-sh` to use it (this is solely based on [XcodeProj's scripting sample](https://github.com/tuist/XcodeProj#scripting) with added call to [`xcodeproj.pbxproj.invalidateUUIDs`](https://github.com/tuist/XcodeProj/blob/f87362ca763c0b66687d6737517b55ad648d33ed/Sources/XcodeProj/Objects/Project/PBXProj.swift#L168-L172) that is documented to generate deterministic UUIDs on save).

```
#!/usr/bin/swift sh

import Foundation
import XcodeProj  // @tuist ~> 7.8.0
import PathKit

guard CommandLine.arguments.count == 2 else {
    let arg0 = Path(CommandLine.arguments[0]).lastComponent
    fputs("usage: \(arg0) <project>\n", stderr)
    exit(1)
}

let projectPath = Path(CommandLine.arguments[1])
let xcodeproj = try XcodeProj(path: projectPath)
xcodeproj.pbxproj.invalidateUUIDs()
try xcodeproj.write(path: projectPath)
```

**Comment by grigorye** [comment] 2020-03-09 14:03
I made a [Swift package](https://github.com/grigorye/xcodeprojFixUUIDs) for the above script, so one can use [Mint](https://github.com/yonaskolb/Mint) to build once and run it like this: `mint run grigorye/xcodeprojFixUUIDs@0.1 <your-xcodeproj-after-pod-install>`.

**Comment by amorde** [comment] 2020-03-10 17:39
Yes there isn't the same restriction because `XcodeGen` _generates_ the entire project. Remember that CocoaPods integrates into projects that users create and maintain, so we don't want to wipe out all the UUIDs in the user's project and replace them with ones CocoaPods created.

The API you mentioned above:
```ruby
Xcodeproj::Project::UUIDGenerator.new([project]).generate!
```

Replaces _all_ UUIDs in the passed in project - what we would need to do is only replace the UUIDs for the references that CocoaPods _added_ to the project.

**Closed** 2020-06-17 04:22 UTC
Labels: s1:awaiting input
