### ISSUE TITLE
pod install command fails

### ISSUE THREAD

**Issue by MuhammadRafeh** [CocoaPods/CocoaPods#12251] opened 2024-02-04 17:42 UTC
(node:10929) [DEP0040] DeprecationWarning: The `punycode` module is deprecated. Please use a userland alternative instead.
(Use `node --trace-deprecation ...` to show where the warning was created)
Using firebase.json from '/Users/rafeh.atique/Documents/Personal/react-native/WhatsWeb/firebase.json'
Adding a custom script phase for Pod RNFBApp: [RNFB] Core Configuration
Auto-linking React Native modules for target `WhatsWeb`: RNCAsyncStorage, RNCClipboard, RNDeviceInfo, RNExitApp, RNFBApp, RNFS, RNFileViewer, RNRate, RNSVG, RNShare, RNZipArchive, ReactNativeLocalization, react-native-safe-area-context, and react-native-webview
Framework build type is static library
[Codegen] Generating ./build/generated/ios/React-Codegen.podspec.json
[Codegen] generating an empty RCTThirdPartyFabricComponentsProvider
Analyzing dependencies
Fetching podspec for `DoubleConversion` from `../node_modules/react-native/third-party-podspecs/DoubleConversion.podspec`
[Codegen] Found FBReactNativeSpec
Fetching podspec for `RCT-Folly` from `../node_modules/react-native/third-party-podspecs/RCT-Folly.podspec`
[Codegen] Found rncore
Fetching podspec for `boost` from `../node_modules/react-native/third-party-podspecs/boost.podspec`
Fetching podspec for `glog` from `../node_modules/react-native/third-party-podspecs/glog.podspec`
Fetching podspec for `hermes-engine` from `../node_modules/react-native/sdks/hermes-engine/hermes-engine.podspec`
[Hermes] Using release tarball from URL: https://repo1.maven.org/maven2/com/facebook/react/react-native-artifacts/0.73.2/react-native-artifacts-0.73.2-hermes-ios-debug.tar.gz
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 16.2M  100 16.2M    0     0   911k      0  0:00:18  0:00:18 --:--:--  904k
  % Total    % Received % Xferd  Average Speed   Time    Time     Time  Current
                                 Dload  Upload   Total   Spent    Left  Speed
100 12.3M  100 12.3M    0     0   739k      0  0:00:17  0:00:17 --:--:--  705k
Downloading dependencies
Installing DoubleConversion (1.1.6)
Installing FBLazyVector (0.73.2)
Installing FBReactNativeSpec (0.73.2)
Installing Firebase (10.20.0)
Installing FirebaseCore (10.20.0)
Installing FirebaseCoreInternal (10.20.0)
Installing GoogleUtilities (7.12.0)
Installing PromisesObjC (2.3.1)
Installing RCT-Folly (2022.05.16.00)
Installing RCTRequired (0.73.2)
Installing RCTTypeSafety (0.73.2)
Installing RNCAsyncStorage (1.21.0)
Installing RNCClipboard (1.13.2)
Installing RNDeviceInfo (10.12.0)
Installing RNExitApp (2.0.0)
Installing RNFBApp (18.8.0)
Installing RNFS (2.20.0)
Installing RNFileViewer (2.1.5)
Installing RNRate (1.2.12)
Installing RNSVG (14.1.0)
Installing RNShare (10.0.2)
Installing RNZipArchive (6.1.0)
Installing React (0.73.2)
Installing React-Codegen (0.73.2)
Installing React-Core (0.73.2)
Installing React-CoreModules (0.73.2)
Installing React-Fabric (0.73.2)
Installing React-FabricImage (0.73.2)
Installing React-ImageManager (0.73.2)
Installing React-Mapbuffer (0.73.2)
Installing React-NativeModulesApple (0.73.2)
Installing React-RCTActionSheet (0.73.2)
Installing React-RCTAnimation (0.73.2)
Installing React-RCTAppDelegate (0.73.2)
Installing React-RCTBlob (0.73.2)
Installing React-RCTFabric (0.73.2)
Installing React-RCTImage (0.73.2)
Installing React-RCTLinking (0.73.2)
Installing React-RCTNetwork (0.73.2)
Installing React-RCTSettings (0.73.2)
Installing React-RCTText (0.73.2)
Installing React-RCTVibration (0.73.2)
Installing React-callinvoker (0.73.2)
Installing React-cxxreact (0.73.2)
Installing React-debug (0.73.2)
Installing React-graphics (0.73.2)
Installing React-hermes (0.73.2)
Installing React-jserrorhandler (0.73.2)
Installing React-jsi (0.73.2)
Installing React-jsiexecutor (0.73.2)
Installing React-jsinspector (0.73.2)
Installing React-logger (0.73.2)
Installing React-nativeconfig (0.73.2)
Installing React-perflogger (0.73.2)
Installing React-rendererdebug (0.73.2)
Installing React-rncore (0.73.2)
Installing React-runtimeexecutor (0.73.2)
Installing React-runtimescheduler (0.73.2)
Installing React-utils (0.73.2)
Installing ReactCommon (0.73.2)
Installing ReactNativeLocalization (2.3.2)
Installing SSZipArchive (2.4.3)
Installing SocketRocket (0.6.1)
Installing Yoga (1.14.0)
Installing boost (1.83.0)
Installing fmt (6.2.1)
Installing glog (0.3.5)
Installing hermes-engine (0.73.2)

[!] Error installing hermes-engine

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/Users/rafeh.atique/.rbenv/versions/2.7.6/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.15.0
        Ruby : ruby 2.7.6p219 (2022-04-12 revision c9c2245c0a) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 14.0 (23A344)
       Xcode : 15.0 (15A240d)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /Users/rafeh.atique/.rbenv/versions/2.7.6/lib
Repositories : foodeveloper-foopods - git - https://github.com/foodeveloper/foopods.git @ 7141c1fb3c64dce338f6389bc49a6a20801b3df3

               trunk - CDN - https://cdn.cocoapods.org/
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-pod-linkage : 0.0.1
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
# Resolve react_native_pods.rb with node to allow for hoisting
require Pod::Executable.execute_command('node', ['-p',
  'require.resolve(
    "react-native/scripts/react_native_pods.rb",
    {paths: [process.argv[1]]},
  )', __dir__]).strip

platform :ios, min_ios_version_supported
prepare_react_native_project!

# If you are using a `react-native-flipper` your iOS build will fail when `NO_FLIPPER=1` is set.
# because `react-native-flipper` depends on (FlipperKit,...) that will be excluded
#
# To fix this you can also exclude `react-native-flipper` using a `react-native.config.js`
# ```js
# module.exports = {
#   dependencies: {
#     ...(process.env.NO_FLIPPER ? { 'react-native-flipper': { platforms: { ios: null } } } : {}),
# ```
flipper_config = ENV['NO_FLIPPER'] == "1" ? FlipperConfiguration.disabled : FlipperConfiguration.enabled

linkage = ENV['USE_FRAMEWORKS']
if linkage != nil
  Pod::UI.puts "Configuring Pod with #{linkage}ally linked Frameworks".green
  use_frameworks! :linkage => linkage.to_sym
end

target 'WhatsWeb' do
  config = use_native_modules!

  use_react_native!(
    :path => config[:reactNativePath],
    # Enables Flipper.
    #
    # Note that if you have use_frameworks! enabled, Flipper will not work and
    # you should disable the next line.
    # :flipper_configuration => flipper_config,
    # An absolute path to your application root.
    :app_path => "#{Pod::Config.instance.installation_root}/.."
  )
  use_frameworks! :linkage => :static # Firebase Config
  
  target 'WhatsWebTests' do
    inherit! :complete
    # Pods for testing
  end

  post_install do |installer|
    # https://github.com/facebook/react-native/blob/main/packages/react-native/scripts/react_native_pods.rb#L197-L202
    react_native_post_install(
      installer,
      config[:reactNativePath],
      :mac_catalyst_enabled => false
    )
  end
end
```

### Error

```
Errno::EEXIST - File exists @ syserr_fail2_in - /Users/rafeh.atique/Library/Caches/CocoaPods/Pods/External/hermes-engine/6ef44e4a609ea85b35328bf8b605bebb-b361c/destroot/Library/Frameworks/universal/hermes.xcframework/ios-arm64_x86_64-maccatalyst/hermes.framework/Resources
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1390:in `symlink'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1390:in `copy'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:497:in `block in copy_entry'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1513:in `wrap_traverse'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1516:in `block in wrap_traverse'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1515:in `each'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1515:in `wrap_traverse'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:494:in `copy_entry'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:468:in `block in cp_r'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1589:in `block in fu_each_src_dest'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1598:in `block in fu_each_src_dest0'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1596:in `each'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1596:in `fu_each_src_dest0'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:1587:in `fu_each_src_dest'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/2.7.0/fileutils.rb:467:in `cp_r'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:343:in `block (2 levels) in copy_files'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in `each'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in `block in copy_files'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:128:in `lock'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:99:in `write_lock'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:332:in `copy_files'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:269:in `block (2 levels) in uncached_pod'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in `each'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in `block in uncached_pod'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:291:in `in_tmpdir'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:238:in `uncached_pod'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:33:in `download_pod'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader.rb:42:in `download'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_downloader.rb:69:in `download!'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:117:in `download_source'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:67:in `install!'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:621:in `install_source_of_pod'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:539:in `block (2 levels) in install_pod_sources'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:86:in `titled_section'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:538:in `block in install_pod_sources'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `each'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in `install_pod_sources'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:258:in `block in download_dependencies'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:64:in `section'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:257:in `download_dependencies'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:163:in `install!'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/command/install.rb:52:in `run'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/claide-1.1.0/lib/claide/command.rb:334:in `run'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/lib/cocoapods/command.rb:52:in `run'
/Users/rafeh.atique/.rbenv/versions/2.7.6/lib/ruby/gems/2.7.0/gems/cocoapods-1.15.0/bin/pod:55:in `<top (required)>'
/Users/rafeh.atique/.rbenv/versions/2.7.6/bin/pod:25:in `load'
/Users/rafeh.atique/.rbenv/versions/2.7.6/bin/pod:25:in `<main>'

**Comment by paulb777** [comment] 2024-02-04 18:20
Dupe of #12226

**Closed by paulb777** 2024-02-04 18:20 UTC
