### ISSUE TITLE
pods issue

### ISSUE THREAD

**Issue by Mahmoud-Nasser01** [CocoaPods/CocoaPods#9461] opened 2020-01-07 09:26 UTC
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
 Run `pod install`

## What did you expect to happen?
 Install all pod dependencies correctly.

## What happened instead?
after installing all pods to project in terminal this error happened and no podlock file created

> ### Error
> 
> ```
> NoMethodError - undefined method `merged_pod_target_xcconfigs' for nil:NilClass
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:166:in `block in remove_pod_target_xcconfig_overrides_from_target'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:164:in `each'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:164:in `remove_pod_target_xcconfig_overrides_from_target'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:147:in `block in add_target'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:146:in `tap'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:146:in `add_target'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:49:in `block in install!'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:145:in `message'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:34:in `install!'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:114:in `block in install_pod_targets'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `map'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:111:in `install_pod_targets'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:32:in `block in install_all_pod_targets'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:145:in `message'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:31:in `install_all_pod_targets'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer/xcode/single_pods_project_generator.rb:19:in `generate!'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:308:in `block in create_and_save_projects'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/user_interface.rb:64:in `section'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:303:in `create_and_save_projects'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:295:in `generate_pods_project'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:174:in `integrate'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/installer.rb:162:in `install!'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command/install.rb:52:in `run'
> /Library/Ruby/Gems/2.6.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/lib/cocoapods/command.rb:52:in `run'
> /Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.0.beta.2/bin/pod:55:in `<top (required)>'
> /usr/local/bin/pod:23:in `load'
> /usr/local/bin/pod:23:in `<main>'
> ```
> 
> ――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――
> 
> [!] Oh no, an error occurred.
> 
> Search for existing GitHub issues similar to yours:
> https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60merged_pod_target_xcconfigs%27+for+nil%3ANilClass&type=Issues
> 
> If none exists, create a ticket, with the template displayed above, on:
> https://github.com/CocoaPods/CocoaPods/issues/new
> 
> Be sure to first read the contributing guide for details on how to properly submit a ticket:
> https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md
> 
> Don't forget to anonymize any private data!
<img width="384" alt="Screen Shot 2020-01-07 at 11 21 00 AM" src="https://user-images.githubusercontent.com/50577573/71883837-e7ce9e80-313f-11ea-8c4b-d3ff0fc9a02e.png">
<img width="382" alt="Screen Shot 2020-01-07 at 11 21 23 AM" src="https://user-images.githubusercontent.com/50577573/71883863-f1580680-313f-11ea-88fc-c90f667e4cb0.png">
<img width="384" alt="Screen Shot 2020-01-07 at 11 21 00 AM" src="https://user-images.githubusercontent.com/50577573/71883890-fd43c880-313f-11ea-827d-89136fe1b116.png">
<img width="382" alt="Screen Shot 2020-01-07 at 11 21 23 AM" src="https://user-images.githubusercontent.com/50577573/71883893-fddc5f00-313f-11ea-9a88-5e55d1261d9f.png">

## CocoaPods Environment
I don't know how to define this

## Project that demonstrates the issue
https://github.com/muhammadelkady25/Fulltact-iOS-App

**Comment by omkarg** [comment] 2020-01-07 13:07
Even i am facing the same issue. Were you able to fix it?

**Comment by dnkoutso** [comment] 2020-01-07 13:29
the sample app link provided does not exist. Please upload sample app so we can diagnose.

**Comment by chrisballinger** [comment] 2020-01-09 03:40
I am also facing this issue after updating to 1.9beta2, try this branch to repro: https://github.com/ChatSecure/ChatSecure-iOS/tree/xcode-11

**Comment by chrisballinger** [comment] 2020-01-09 03:42
This is probably resolved by this PR: https://github.com/CocoaPods/CocoaPods/pull/9470

**Comment by paulb777** [comment] 2020-01-09 03:45
Yep, this issue looks like a duplicate of #9465

**Comment by dnkoutso** [comment] 2020-01-09 05:48
closing as dup of https://github.com/CocoaPods/CocoaPods/issues/9465

**Closed by dnkoutso** 2020-01-09 05:48 UTC
Labels: s6:need sample
