### ISSUE TITLE
Can't find my project on cocoapods.org

### ISSUE THREAD

**Issue by michaeleisel** [CocoaPods/CocoaPods#9127] opened 2019-08-26 01:39 UTC
I can't find my project, ZippyJSON, on cocoapods.org, even though I can use it with `pod ZippyJSON` in other projects just fine.

# Report

## What did you do?

Run `pod trunk push ZippyJSON.podspec --allow-warnings --verbose`

### Stack

```
   CocoaPods : 1.7.5
        Ruby : ruby 2.6.3p62 (2019-04-16 revision 67580) [universal.x86_64-darwin19]
    RubyGems : 3.0.3
        Host : Mac OS X 10.15 (19A536g)
       Xcode : 10.3 (10G8)
         Git : git version 2.21.0
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.6/usr/lib
Repositories : artsy - https://github.com/artsy/Specs.git @ ef1735b844309562ba59a1ef257a3148958fe4e9
               master - https://github.com/CocoaPods/Specs.git @ e32f4aaa8f6ad641a62cf88b3b54b521055331d0
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate                 : 1.0.4
cocoapods-disable-podfile-validations : 0.1.1
cocoapods-generate                    : 1.5.0
cocoapods-plugins                     : 1.0.0
cocoapods-search                      : 1.0.0
cocoapods-stats                       : 1.1.0
cocoapods-trunk                       : 1.3.1
cocoapods-try                         : 1.1.0
```

**Comment by dnkoutso** [comment] 2019-08-26 01:41
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9116 and ultimately duplicate of https://github.com/CocoaPods/cocoapods.org/issues/424.

Closing. We have yet to fix the search indexer.

**Closed by dnkoutso** 2019-08-26 01:41 UTC
