### ISSUE TITLE
Pod setup no resopnd

### ISSUE THREAD

**Issue by RichardDuan** [CocoaPods/CocoaPods#9261] opened 2019-10-15 16:26 UTC
After reinstalling the 10.15 system, the terminal input pod setup did not respond.
![image](https://user-images.githubusercontent.com/15153355/66850549-a351bd80-efab-11e9-80d5-8d6ba311f508.png)

**Comment by dnkoutso** [comment] 2019-10-15 16:31
This works as expected. `pod setup` doesnt do anything in 1.8.x but we kept it for backwards compatibility. In 1.9.x we added a message but the command still does nothing.

Closing as works as intended.

**Closed by dnkoutso** 2019-10-15 16:31 UTC
