### ISSUE TITLE
“pod install” creates a “SWIFT_VERSION = 5.0” attribute inside Pods.project (and no XCode 10.2.x was ever installed on that machine) Bug?

### ISSUE THREAD

**Issue by friguron** [CocoaPods/CocoaPods#8876] opened 2019-06-05 16:44 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

"pod install" (after removing Pods folder and Podfile.lock file)

## What did you expect to happen?

Pods.project file should not contain any metion to SWIFT_VERSION = 5.0 (specially when no Xcode 10.2.X is installed on that machine)

## What happened instead?

Pods.project file contains a "SWIFT_VERSION = 5.0 (unsupported)" entry and our team doesn't know why, it's somewhat unwanted.

### Stack

```
   CocoaPods : 1.4.0
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin16]
    RubyGems : 2.6.14
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.2 (Apple Git-113)
Ruby lib dir : /Users/my_user_name/.rvm/rubies/ruby-2.4.1/lib
Repositories : private_repo_1_specs - https://private_URL_repository/Specs.git @ f159e77c8516f654555176c98cdcf86a553de921
               master - https://github.com/CocoaPods/Specs.git @ ac38c4011d80e0b1a552e0d9cabb89893101aa4f
               Specs - https://private_repo_2/arq_ios/Specs.git @ 41bbb74f56d21a813cc82e45c83c5ec4dd20dbb0
```

### Installation Source

```
Executable Path: /Users/my_user_name/.rvm/gems/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

__________________________________

Hi,

I’m part of a team developing some architectural iOS solution involving integrating private iOS frameworks.

Part of the core of this solution needs CocoaPods and right now we’re very happy about all the complex module definition we’ve created so far.

But we have isolated an issue we don’t know if it’s a feature, a bug, a known fact… We’ll describe it here with as much detail as we can, to see if someone can shed some light on it

(It will be a crossposting doubt in stackoverflow/CocoaPods github).

Context:

Our architectural solution has to cover a range of versions of iOS/Swift/Xcode for it to be deployed. The last certified versions we’re dealing with are: Swift 4.0 + Xcode 10.1 + CocoaPods 1.4.0 (yes, we know CocoaPods 1.7.1 is out, but our validation process forces us to still work with 1.4.0).

Anyway, what does it all mean? It means when we’re developing our code, we need to update our internal libraries dependencies, situation which typically is resolved with a good old “pod install”.

This pod install checks all our “brother projects” repositories and it downloads whatever new internal pods it needs, and (here comes the important part), it recreates the “Pods” project (that means it recreates the Pods.project file).

This Pods.project is the big “umbrella” where all the imported frameworks will live in our big solution. If we browse this Pods.project from within Xcode we can look for the “SWIFT_VERSION” keyword. When we do this, the expected (and wanted) result for our project is “undefined”.

So far, we’ve described the expected situation we would like to be dealing with, but some weeks ago we started to notice strange things when we needed to check our solution against different (newer) versions of “Cocoapods” (and its “satellite” associated gems).

Cocoapods is a piece of our toolkit that needs to be periodically checked, so in some machines we also started to install additional cocoapods versions (1.6.0, 1.6.1, 1.7.0 and 1.7.1) apart from our certified 1.4.0

What does it mean? Installing different CocoaPods versions also leads to additional gem installations in the background, mainly “fourflusher”, “xcodeproj”, etc...

Typically, once you have cocoapods 1.4.0 (and 1.6.0, 1.6.1, 1.7.0 and 1.7.1) you end up with things like, more than one fourflusher version installed (2.0.1, 2.2.0), more than one cocoapods version installed (logically), and more than one xcodeproj version installed (typically 1.5.6, 1.8.X and 1.9.0).

What does it all mean in the end?

Having the latest versions of all these additional cocoapods related gems installed leads to the following (undesired for us) situation:

The “pod install” action (having deleted “Pods” folder and “Podfile.lock” file beforehand) recreates a Pods.project file, but with SWIFT_VERSION attribute set to “5.0 (unsupported)”. Why?

Particularly when we had never installed Xcode 10.2.X in these machines we’re running “pod install”

Why xcodeproj decides to add this attribute (with a value of 5.0) inside Pods.project, when in the past (Xcodeproj version 1.5.6 for example), it left this as “undefined”?

NOTE: If instead of cocoapods 1.7.X we upgrade to just cocoapods 1.6.x, then xcodeproj gem will raise to version 1.8.X

The behaviour of this other xcodeproj version (1.8.X) is apparently similar to 1.9.X, but instead of adding a (we think unneeded) SWIFT_VERSION attribute with a value of 5.0, it also creates it but with a value of 4.2.

This is not a problem if you just have Xcode 10.1 installed, as this version of Xcode DOES understand how to deal with Swift 4.2, or at least, it offers you to upgrade your project settings.

Our actual question is: is all this a known situation? why does cocoapods/Xcodeproj 1.8.X /1.9.0 decide to raise the SWIFT_VERSION to 4.2/5.0

(especially in the 5.0 case, where Xcode 10.2.(x) had never been installed on those machines)

Just in case someone might think some sibling-project might have an internal SWIFT_VERSION setting of 5.0 already set, (and this might be the reason for this value to get propagated to the Pods.project file), we have to say that no subproject/framework has SWIFT_VERSION set to 5.0

Why we know this? Because we run this command in the root of our big solution folder

grep “SWIFT_VERSION = 5\.0” * -r 

and it never finds any 5.0 instance.

Besides, inside of each private framework pod, we've manually set to 4.0 the s.swift_version attribute.

Any hints about why "pod install" seems to trigger an (unwanted) SWIFT_VERSION 5.0 inside the Pods.project file, even though we never had any Xcode 10.2.x installed on it? Is it a bug? feature? known situation? expectable situation?

It's a really long question and description, so if something is unclear we'll happy clarify any doubt.

Greetings

**Comment by dnkoutso** [comment] 2019-06-05 18:31
Really need a sample app here. A pod probably requires Swift 5.0 or you need to use 1.7.x and use `supports_swift_version` DSL to limit the version of Swift to install.

**Comment by friguron** [comment] 2019-06-05 18:39
The project is completely confidential. No way to provide any sample of it, I'm sorry :(

We've double checked all frameworks/pods being imported into the big one. 90% of them are ours (private also), and as I said before, all defined with s.swift_version = 4.0 in their podspecs.

Tomorrow we will triple check some standard 3rd party typical pods, but as far as I can remember none of them seemed to be asking for swift 5.0
We'll also check "supports_swift_version" option to see if it changes something.

Thanks.

**Comment by dnkoutso** [comment] 2019-06-06 01:24
Sorry this is too difficult to diagnose without a sample app.

I am going to keep it open but the issue will be closed if it remains inactive.

**Comment by friguron** [comment] 2019-06-06 07:12
Fair enough, but first I'd like to reach my workplace to give this additional feedback and discussing it with my team.

We'll also try to have a simplified case behaving the same way so we can get more insight.

Thanks

**Comment by dnkoutso** [comment] 2019-06-06 14:39
Sounds good will wait for you response!

**Comment by Pashcal** [comment] 2019-06-10 16:08
Hi. We have the same issue with installed xcode 10.1 and cocoapods 1.6.1 (the same result with 1.7.1).
In addition, we also have `s.swift_version = '4.2'` settings and when running `pod spec lint`, we are got result `- NOTE  | [iOS] xcodebuild:  error: SWIFT_VERSION '5.0' is unsupported, supported versions are: 3.0, 4.0, 4.2. (in target 'ObjectMapper')`

Also, in our project was no changes in Podfile and podspec, the same as we are using xcode 10.1 and cocoapods 1.6.1 last couple of months and `pod install` and `pod spec lint` worked fine before. So, it's strange, but seems like something was changed remotely in cocoapods or in xcode 10.1 🤔

`source 'https://github.com/CocoaPods/Specs.git'
# + private source

platform :ios, '9.0'
use_frameworks!
inhibit_all_warnings!

def mobilesdk_pods
  pod 'AlamofireObjectMapper', '~> 5.0'
  pod 'SwiftLint', '~> 0.27.0'
  # + some private pods
end

target 'mobilesdk' do
  mobilesdk_pods
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ENABLE_CODE_COVERAGE'] = 'NO'
    end
  end
end
`
Later I will try to prepare test project with such issue for full investigation 👌

**Comment by dnkoutso** [comment] 2019-06-10 18:20
The default settings from Xcodeproj gem have been updated to use SWIFT_VERSION to 5.0 as the default and last known Swift version.

https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb#L389

`pod spec lint` will use the Xcode version you have installed. You have to add a `swift_version` in the podspec you are linting for it to use that value or pass `--swift-version` parameter.

**Comment by dnkoutso** [comment] 2019-06-10 18:22
@Pashcal please paste the podspec you are trying to lint or a repo with it.

I am fairly certain there is no bug here and its a configuration issue.

**Comment by Pashcal** [comment] 2019-06-10 18:49
@dnkoutso 

```
Pod::Spec.new do |s|
  s.name = 'SomeNameOfSDK'
  s.platform = :ios
  s.version = '0.0.1'
  s.author = 'CompanyName'
  s.license = 'Proprietary'
  s.homepage = 'https://somepage.com'
  s.summary = 'Bla-Bla'

  s.source = { :git => "ssh://git@bitbucket.companyname/some-sdk-ios.git" }
  s.source_files = "mobilesdk", "mobilesdk/**/*.{swift,h,m}"
  s.resource_bundles =  {
    "mobilesdkres" => [
        "mobilesdk/**/*.{json,xml,der}"
    ]
  }
  s.swift_version = '4.2'
  s.pod_target_xcconfig = {
    "ENABLE_BITCODE" => "NO",
    "VALID_ARCHS" => "armv7 armv7s x86_64 arm64 arm64e"
  }

  s.requires_arc = true
  s.ios.deployment_target = '9.0'
  s.module_name  = 'mobilesdk'

  s.dependency "SomePrivateFrameworks", "~> 0.1"
  s.dependency "AlamofireObjectMapper", "~> 5.0"
  s.dependency "SomeOtherPublicFrameworks"
end
```

Interesting that with `pod install` all pods targets are setting SWIFT_VERSION to 4.2, but `Pods` project build setting has SWIFT_VERSION = 5.0
<img width="760" alt="image" src="https://user-images.githubusercontent.com/1590811/59218018-ef3cc200-8bc7-11e9-8a3c-eca8af66b473.png">

And when using `pod spec lint`, then `Pods` project build setting has SWIFT_VERSION = 5.0 and `ObjectMapper` target also. All other targets have swift version 4.2.
<img width="760" alt="image" src="https://user-images.githubusercontent.com/1590811/59218671-7474a680-8bc9-11e9-94a5-5d77f7464755.png">

**Comment by Pashcal** [comment] 2019-06-10 18:57
> The default settings from Xcodeproj gem have been updated to use SWIFT_VERSION to 5.0 as the default and last known Swift version.
> 
> https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb#L389

Seems like this update not related, because current issue was appeared in last few days. Month ago everything worked fine.
Maybe some changes inside xcode 10.1 which we missed, but I really can't find it.

**Comment by friguron** [comment] 2019-06-11 09:37
> The default settings from Xcodeproj gem have been updated to use SWIFT_VERSION to 5.0 as the default and last known Swift version.
> 
> https://github.com/CocoaPods/Xcodeproj/blob/master/lib/xcodeproj/constants.rb#L389
> 
> `pod spec lint` will use the Xcode version you have installed. You have to add a `swift_version` in the podspec you are linting for it to use that value or pass `--swift-version` parameter.

Fair enough altogether, we'll try setting the "swift_version" in a explicit way.

But anyway, in the machine making the tests we never installed Xcode 10.2.X, (the only one understanding SWIFT_VERSION = 5.0), so it doesn't really make sense... Why not detecting the installed Xcode 10.1 on this machine and pushing SWIFT_VERSION only to 4.2 ?

**Comment by Pashcal** [comment] 2019-06-11 14:20
Update:

During investigation we figured out, that is really related to used `AlamofireObjectMapper` version `~> 5.0` which is related to `ObjectMapper` version `~> 3.4`. And `ObjectMapper` was updated to 3.5.0 with using Swift 5 in their podspec, which was reason of different result of `pod install` and `pod spec lint` on our side → Podfile.lock uses ObjectMapper (3.4.2)

Here is versions from Podfile.lock
```
PODS:
  - Alamofire (4.8.2)
  - AlamofireObjectMapper (5.2.0):
    - Alamofire (~> 4.7)
    - ObjectMapper (~> 3.4)
  - ObjectMapper (3.4.2)

DEPENDENCIES:
  - AlamofireObjectMapper (~> 5.2.0)

COCOAPODS: 1.6.1

```

So `ObjectMapper` issue was solved, but `pod install` continue changing Pods.xcodeproj to `SWIFT_VERSION  = 5.0;`

**Comment by friguron** [comment] 2019-06-11 15:00
BTW, we've created some simple project with just Realm as a dependency. It has 2 branches, one for cocoapods 1.4.0 and another for 1.7.0. It’s very similar to Pashcal one. Feel free to browse either of them:

1.4.0
https://github.com/jordimele/Test_1.7.0/tree/develop

cocoapods 1.4.0 (so xcodeproj 1.5.6) has created the following setup for Xcode:
![imagen](https://user-images.githubusercontent.com/3338420/59282348-0da6ca00-8c69-11e9-9f93-0f9c39a76466.png)

![imagen](https://user-images.githubusercontent.com/3338420/59282436-3c24a500-8c69-11e9-8212-b5db2e82fb6a.png)

![imagen](https://user-images.githubusercontent.com/3338420/59282476-49da2a80-8c69-11e9-89db-7e62f13b165b.png)

____________________________________________________________________________
1.7.0
https://github.com/jordimele/Test_1.7.0/tree/feature/Cocoapods_1.7.0

Cocoapods 1.7.0 (so xcodeproj 1.9.0) has created the following setup for Xcode:

![imagen](https://user-images.githubusercontent.com/3338420/59282678-97569780-8c69-11e9-9751-6949277e25e2.png)

![imagen](https://user-images.githubusercontent.com/3338420/59283025-2bc0fa00-8c6a-11e9-91ea-3bb7ddeeef59.png)

![imagen](https://user-images.githubusercontent.com/3338420/59282821-cff67100-8c69-11e9-864b-961181ce0349.png)


OTOH, as we can see on the the code snippet you sent us before, SWIFT_VERSION is effectively set to 5.0 (hardcoded). We just find it might be potentially inconvenient for our building purposes.

So our questions are (in case they’re achievable):

-Where should we specify a particular SWIFT_VERSION **_for the Pods.project file_** ?

-Where should we specify a particular SWIFT_VERSION **_for the Pods-Test_1.7.0.project file_** ?

Specifying s.swift_version 4.0 inside the .podspec files makes this value appear in the dependencies SWIFT_VERSION (that's ok, we can see it on the screenshots), but Pods.project file SWIFT_VERSION is raised to 5.0 no matter what.

How can we specify (if ever) a SWIFT_VERSION value of 4.2, 4.0 or, much better, "unspecified"  **_for the Pods.project file_** when using cocoapods 1.7.0 (XCodeproj 1.9.0) ?

Greetings

**Comment by dnkoutso** [comment] 2019-06-11 19:18
The `pod spec lint` issue is probably the same as this https://github.com/CocoaPods/CocoaPods/issues/8764.

Basically CocoaPods (via Xcodeproj) prints out `SWIFT_VERSION` to 5.0 and because the project is generated during lint there is no way to specify which Swift version to use for the dependencies.

I will be making a PR to fix this.

For:

> -Where should we specify a particular SWIFT_VERSION for the Pods.project file ?
> -Where should we specify a particular SWIFT_VERSION for the Pods-Test_1.7.0.project file ?

You do not because `Pods.xcodeproj` is always generated by CocoaPods. Hm it might be an issue that the generated `Pods-<name>` targets inherit their `SWIFT_VERSION` from `Pods.xcodeproj`. We should probably delete those since those targets do not use any Swift.

@friguron if you delete the build setting from the `Pods-<name>` targets does it compile?

**Comment by KeimyPlaza** [comment] 2019-06-18 16:24
@friguron I’ve the same issue.

@dnkiutso I try with 1.7.2 about #8764 solved but It’s the same issue exactly.

Are the any idea to resolve?

Thks

**Comment by dnkoutso** [comment] 2019-06-23 22:56
Whats left to do here? #8764 was merged and shipped.

**Comment by friguron** [comment] 2019-06-25 08:54
> The `pod spec lint` issue is probably the same as this #8764.
> 
> Basically CocoaPods (via Xcodeproj) prints out `SWIFT_VERSION` to 5.0 and because the project is generated during lint there is no way to specify which Swift version to use for the dependencies of the pod you are linting.
> 
> I will be making a PR to fix this #8764.
> 
> For:
> 
> > -Where should we specify a particular SWIFT_VERSION for the Pods.project file ?
> > -Where should we specify a particular SWIFT_VERSION for the Pods-Test_1.7.0.project file ?
> 
> You do not. That is because `Pods.xcodeproj` is always generated by CocoaPods. Hm it might be an issue that the generated `Pods-<name>` targets inherit their `SWIFT_VERSION` from `Pods.xcodeproj`. We should probably delete those since those targets do not use any Swift.
> 
> @friguron if you delete the build setting from the `Pods-<name>` targets does it compile?

Hi, we've made the test you suggested: removing the SWIFT_VERSION setting from the Pods project (using both 1.7.0 and 1.7.2 versions of Cocoapods) and it compiles in both cases. 
But the thing is it already compiled even leaving the 5.0 setting there. 

Right now we don't have any compilation problem. Our concern was more we might potentially have future problems when integrating all the pieces our big solution needs.

In our testing/building environment (our local machines) we can remove this setting from the .project file by hand (no problem), but there are some parts of the whole building pipeline where Continuous Integration is involved and we're not sure we're in control of these automatized environments that easily, and/or if these SWIFT_VERSION = 5.0 setting might interfere in the future.

Greetings.

**Comment by dnkoutso** [comment] 2019-06-25 10:46
There should be no problem at all. CocoaPods sets this at the project level due to Xcodeproj but _each_ generated target calculates and sets the Swift version to use. 

This now sounds like a non-issue to me so I am going to close it. We can re-open if we find a clear concise and reproducible project or if `SWIFT_VERSION = 5.0` interferes in the future. It shouldn't and it doesn't as it seems now.

**Closed by dnkoutso** 2019-06-25 10:46 UTC

**Comment by friguron** [comment] 2019-06-25 11:20
Fair enough. 
In case some issue arises, there won't be any problem re-reporting it here. As you say, let's hope not.

Thanks for the support anyway.

**Comment by dnkoutso** [comment] 2019-06-25 11:23
yes! no problem.
