### ISSUE TITLE
Error CDN "Relative path couldn't be downloaded" in all commands

### ISSUE THREAD

**Issue by AgDP** [CocoaPods/CocoaPods#9169] opened 2019-09-19 14:37 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
pod install
pod repo push 

## What did you expect to happen?

ℹ Please replace these two lines with what you expected to happen.  
Install all pod dependencies correctly.

## What happened instead?

[!] CDN: visualstudio-defaultcollection-mobiledrivesmart-_git-ds-ios-framework Relative path couldn't be downloaded: CocoaPods-version.yml Response: 302

## CocoaPods Environment

"pod env" get the same error:
[!] CDN: visualstudio-defaultcollection-mobiledrivesmart-_git-ds-ios-framework Relative path couldn't be downloaded: CocoaPods-version.yml Response: 302

With "gem list --local | grep cocoapods"
cocoapods (1.7.5)
cocoapods-core (1.7.5)
cocoapods-deintegrate (1.0.4)
cocoapods-downloader (1.2.2)
cocoapods-plugins (1.0.0)
cocoapods-search (1.0.0)
cocoapods-stats (1.1.0)
cocoapods-trunk (1.4.0)
cocoapods-try (1.1.0)

## Project that demonstrates the issue

it's only an issue with CocoaPods the tool.

**Comment by igor-makarov** [comment] 2019-09-19 16:15
This is a duplicate of #9098, please update to 1.8.0 and delete the VS repo as explained in #9098.

**Comment by dnkoutso** [comment] 2019-09-19 16:25
Thanks!

**Closed by dnkoutso** 2019-09-19 16:24 UTC

**Comment by AgDP** [comment] 2019-09-20 06:33
thanks!!

**Comment by prohoney** [comment] 2019-11-12 15:56
I wasn't able to run the most basic (`pod lib lint`, `pob lib list`, etc) commands I was on `1.7.5` things were working. Then I upgraded to Catalina and I don't know from which point it stopped working. It was working for my colleagues... and we couldn't upgrade to `1.8.0`

The solution that did work for me was, I went into my `~/.cocoapods/repos` directory. And deleted the repo that was giving me this problem and then just added it again. 

I believe the root cause was: I had 3 different directories of the **same**  _private_ repo. I've downloaded it multiple times —while we may have changed its URL and things have got messed up there.

I'm not sure but I believe you could also do

```
pod repo remove bad-repo
```

and that would also make things work again, but I haven't tried it.

**Comment by ZaidSA** [comment] 2020-01-16 07:00
This helped me:

```ruby
rm -rf ~/.cocoapods
pod install
```
