### ISSUE TITLE
NoMethodError - undefined method `source_tree' for <PBXBuildFile UUID=``>:Xcodeproj::Project::Object::PBXBuildFile

### ISSUE THREAD

**Issue by xxd** [CocoaPods/CocoaPods#3755] opened 2015-07-01 03:32 UTC
After running pod install we got error below:

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/bin/pod install --verbose
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.37.2
        Ruby : ruby 2.0.0p481 (2014-05-08 revision 45883) [universal.x86_64-darwin14]
    RubyGems : 2.0.14
        Host : Mac OS X 10.10.3 (14D136)
       Xcode : 6.2 (6C131e)
         Git : git version 1.9.5 (Apple Git-50.3)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 3f759ac10346d72085664700a10bf19dfe235689
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-trunk   : 0.6.1
cocoapods-try     : 0.4.5
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '8.0'
use_frameworks!

target 'xiudouiOS' do
pod 'Alamofire','1.2.2'
pod 'SwiftyJSON','2.2.0'
pod 'SnapKit', '~> 0.11.0'
pod 'Refresher'
end
```

### Error

```
NoMethodError - undefined method `source_tree' for <PBXBuildFile UUID=``>:Xcodeproj::Project::Object::PBXBuildFile
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.3/lib/xcodeproj/project/object/helpers/groupable_helper.rb:114:in `source_tree_real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.3/lib/xcodeproj/project/object/helpers/groupable_helper.rb:98:in `real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.3/lib/xcodeproj/project/object/helpers/groupable_helper.rb:119:in `source_tree_real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.3/lib/xcodeproj/project/object/helpers/groupable_helper.rb:98:in `real_path'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.24.3/lib/xcodeproj/project/object/file_reference.rb:163:in `real_path'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:56:in `block (2 levels) in update_to_cocoapods_0_34'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:53:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:53:in `block in update_to_cocoapods_0_34'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:52:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:52:in `update_to_cocoapods_0_34'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:24:in `block (2 levels) in integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:23:in `block in integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb:22:in `integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:39:in `block in integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator/target_integrator.rb:36:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator.rb:116:in `block in integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator.rb:115:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator.rb:115:in `integrate_user_targets'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer/user_project_integrator.rb:63:in `integrate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:660:in `block in integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:657:in `integrate_user_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/installer.rb:100:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command/project.rb:101:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.8.2/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/lib/cocoapods/command.rb:46:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.37.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60source_tree%27+for+%3CPBXBuildFile+UUID%3D%60F965E06C1B3AC59E0063E2DB%60%3E%3AXcodeproj%3A%3AProject%3A%3AObject%3A%3APBXBuildFile&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

Please help for this issue, thanks a lot!

**Comment by neonichu** [comment] 2015-07-01 12:52
Looks like a duplicate of #3720

**Closed by neonichu** 2015-07-01 12:52 UTC
