### ISSUE TITLE
Compiler error "Property has a previous declaration" with 0.39.0, but not with 0.38.2

### ISSUE THREAD

**Issue by natanrolnik** [CocoaPods/CocoaPods#4518] opened 2015-11-08 08:31 UTC
Hello! I've been spending a few hours in the recent days trying to figure out why my app is not compiling anymore when i run `pod install` with 0.39.0. This may be more a "help"/"give me some direction" issue than a real problem from CocoaPods.

My Podfile has the following structure: my main target has `Realm` as one of the pods; and amongst other pods, I have 3 private pods (all mine) that declare `Realm` as a dependency. When building the app, I get errors related to re-declaration of `RLMObject`, `RLMArray` and `RLMResults` (all are the base class or properties in my pods' files), where properties and interface are (possibly more than) duplicate. I already tried deleting the DerivedData folder, investigating header search paths, and spent hours on this, without any hint on how to solve it correctly, or where is my fault.

I already checked that all the private pods pass `pod lib lint` without errors.

The curious thing is that, using CocoaPods 0.38.2, it doesn't happen.

Any idea on how I can tackle this? 

(Samuel, thanks for contributing so much to the OSS community and to CocoaPods!)

**Comment by natanrolnik** [comment] 2015-11-08 10:37
Strangest thing:

I removed each private pod, copied the files manually to my project, and still the errors are appearing.

For example, when I subclass `RLMObject`, and right above I do `#import <Realm/Realm.h>`, I have the "duplicate interface..." error.
When I do the same but declare the import like `#import "Realm.h"`, I get file not found.

This problem is driving me crazy :sweat:

**Comment by neonichu** [comment] 2015-11-08 18:46
It's hard to say what could be happening from your description, could you please share an example that exhibits the problem?

**Comment by natanrolnik** [comment] 2015-11-08 19:49
Hey Boris! If I would setup a project that reproduces the same issue - would that help?

**Comment by neonichu** [comment] 2015-11-08 19:50
@natanrolnik definitely!

**Comment by jeffscaturro-wf** [comment] 2015-11-12 19:58
We are also encountering this issue when upgrading from CocoaPods `0.38.2` to `0.39.0`. For us, we are  getting these errors in AFNetworking with the only change being that upgrade.

**Comment by kashzonal** [comment] 2015-11-13 16:28
I have also updated from 0.38.2 to 0.39.0 and I am getting the many errors to do with duplication of imports and redefinition of enums, here are a couple of examples:

(24)   ~/workspace/iOS/PRODUCT/MyApp/MyApp-Prefix.pch
(10)   ~/DerivedData/MyApp-38656102/Build/Products/Debug-iphoneos/DDTTYLogger.h
Error:(294, 1) duplicate interface definition for class 'DDLog'

(24)  ~/workspace/iOS/PRODUCT/MyApp/MyApp-Prefix.pch
(10)  ~/DerivedData/MyApp-38656102/Build/Products/Debug-iphoneos/DDTTYLogger.h
Error:(573, 5) redefinition of enumerator 'DDLogMessageCopyFunction'

I have tried everything that Nathan has tried without any luck.

**Comment by neonichu** [comment] 2015-11-13 21:21
hm, having issues with duplications of imports and enums sounds more like #4420, are you sure you haven't also upgraded Xcode to 7.1 or newer while changing CP versions?

**Comment by kashzonal** [comment] 2015-11-16 09:32
I have upgraded to 7.1 but I have made sure to use 7.0 SDK and #4420 does mention mixing Swift and ObjC. I am not doing that. I have updated three pods for our Unit and Automation testing as the automation framework stopped working with iOS9. The weird thing is that the pods start failing if I update any pod. If there isn't an update, the project compiles without any problems.

**Comment by neonichu** [comment] 2015-11-19 09:19
Closing, because we never got a project to reproduce this.

**Closed by neonichu** 2015-11-19 09:19 UTC
Labels: s1:awaiting input

**Comment by natanrolnik** [comment] 2015-11-19 10:27
Sorry @neonichu - crazy days here recently. I'll try to submit a project trying to reproduce as soon as I can.

**Comment by neonichu** [comment] 2015-11-19 11:02
@natanrolnik no problem, we'll reopen once you do :)

**Comment by natanrolnik** [comment] 2015-11-22 10:35
I tried to solve the problem - and doing something (that I think I've done before) solved.
Instead of importing `RLMObject` and other Realm files as:

```
#import "RLMResults.h"
#import "RLMObject.h"
```

Importing like this solved my issue:

```
#import <Realm/Realm.h"
```

When I was trying to setup the example project, I changed the imports and it worked - so I reproduced the changes in my project and it started working on `0.39.0`. 

I'm sorry @neonichu ¯\_(ツ)_/¯
