### ISSUE TITLE
How to parse podfile to json

### ISSUE THREAD

**Issue by MahantPatil** [CocoaPods/CocoaPods#9860] opened 2020-06-12 12:02 UTC
I am trying to parse the podfile using `pod ipc podfile-json podfile_path`. If i run through irb, i am able to parse and the `pod ipc` lists the podfile-json command.
` "Usage:\n\n    $ pod ipc COMMAND\n\n      Inter-process communication\n\nCommands:\n\n    + list                  Lists the specifications known to CocoaPods\n    + podfile               Converts a Podfile to YAML\n    + podfile-json          Converts a Podfile to JSON\n    + repl                  The repl listens to commands on standard input\n    + spec                  Converts a podspec to JSON\n    + update-search-index   Updates the search index\n\nOptions:\n\n    --silent                Show nothing\n    --verbose               Show more debugging information\n    --no-ansi               Show output without ANSI codes\n    --help`

If i run through code, i am getting Unknown command: `podfile-json`. If i lists the `pod ipc` commands podfile-json is not listed 
` "Usage:\n\n    $ pod ipc COMMAND\n\n      Inter-process communication\n\nCommands:\n\n    + list                  Lists the specifications known to CocoaPods\n    + podfile               Converts a Podfile to YAML\n    + repl                  The repl listens to commands on standard input\n    + spec                  Converts a podspec to JSON\n    + update-search-index   Updates the search index\n\nOptions:\n\n    --silent                Show nothing\n    --verbose               Show more debugging information\n    --no-ansi               Show output without ANSI codes\n    --help                  Show help banner of specified command\n"`

**Comment by Thuhtet23** [comment] 2020-06-14 10:58
[https://github.com/CocoaPods/CocoaPods/issues/9860#issue-637701345]() 

- [ ] 
Duplicate of #

**Comment by MahantPatil** [comment] 2020-06-16 03:50
Duplicate of which issue? Can you please send me that issue url.?

**Comment by dnkoutso** [comment] 2020-06-19 19:35
`pod ipc podfile-json Podfile` worked for me in a sample project. Please provide clear instructions on how to reproduce and perhaps a sample app if this is failing for you still.

Used 1.9.3 cocoapods version.

**Closed** 2020-06-26 20:12 UTC
Labels: s1:awaiting input
