### ISSUE TITLE
resources of pod in debug configuration

### ISSUE THREAD

**Issue by Igor-Palaguta** [CocoaPods/CocoaPods#3031] opened 2015-01-12 07:38 UTC
Hello,

I have pod that is used just in debug configuration
    pod 'XXX', :configurations => ['Debug']

This pod uses some resources
  spec.resources = "Responses/*.json"

These resources are useless in another configurations. But they are copied even in release.
As I see in resources script, there is no condition for configuration. I think resources script should be different for every configuration

I checked this in 0.35 and 0.36

Is it known issue? Is there any workaround for this?

**Comment by kylef** [comment] 2015-01-12 08:39
This is a known issue, this is a duplicate of #2391. There is an open pull request fixing this at #3030.

**Closed by kylef** 2015-01-12 08:39 UTC
