### ISSUE TITLE
Pod [V1.5.0] lib lint fail with error "AppIcon" in case of its dependency or subspec contains a xcassets type resources

### ISSUE THREAD

**Issue by seuzxh** [CocoaPods/CocoaPods#7617] opened 2018-04-11 02:09 UTC
* [√] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

- I create a test Pod with command "pod lib create"
- I add a subspec named "TestSub1" in the podspec file
- Add resources of "TestSub1" with the xcassets file
- run "pod lib lint  --allow-warnings --verbose --fail-fast --no-clean"

## What did you expect to happen?

- lint success

## What happened instead?

- lint fail with message 

```
/* com.apple.actool.errors */
/Users/zhaoxianghui/Documents/XCProject/TestPod1.5.0/TestSub1/Assets/testpodAset.xcassets: error: None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".
/* com.apple.actool.compilation-results */
/Users/zhaoxianghui/Library/Developer/Xcode/DerivedData/App-ephhbjaiwsmhsbexfmoptnatintl/Build/Products/Release-iphonesimulator/App.app/Assets.car
/Users/zhaoxianghui/Library/Developer/Xcode/DerivedData/App-ephhbjaiwsmhsbexfmoptnatintl/Build/Products/Release-iphonesimulator/assetcatalog_generated_info.plist
Command /bin/sh failed with exit code 1
** BUILD FAILED **
The following build commands failed:
PhaseScriptExecution [CP]\ Copy\ Pods\ Resources /Users/zhaoxianghui/Library/Developer/Xcode/DerivedData/App-ephhbjaiwsmhsbexfmoptnatintl/Build/Intermediates.noindex/App.build/Release-iphonesimulator/App.build/Script-2991DDF45C0A25EC16418712.sh
```

### Stack

```
   CocoaPods : 1.5.0
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [x86_64-darwin16]
    RubyGems : 2.6.8
        Host : Mac OS X 10.13.4 (17E199)
       Xcode : 9.3 (9E145)
         Git : git version 2.9.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.3/lib
Repositories : coding-hging-specs - https://git.coding.net/hging/Specs.git @ 69c5cf4775bd6fde8b04782d6a3725d8d738f31a
               master - https://github.com/CocoaPods/Specs.git @ 18020377917e622f64b4b73808de98b6cf39e5be
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

you can get the demo project from here: 

[Demo Project](https://github.com/seuzxh/TestPod1.5.0.git)

**Comment by dnkoutso** [comment] 2018-04-11 03:54
Also appears to be in subspecs only as you correctly stated in the beginning.

**Comment by dnkoutso** [comment] 2018-04-11 04:09
@seuzxh figured it out. It's because your subspec has no sources it gets integrated differently. Definitely a bug but if you add a source file to your subspec it should work.

**Comment by dnkoutso** [comment] 2018-04-11 04:13
This will most likely get fixed for 1.6.0 depending on progress on revamped pods project generation and target installation.

**Comment by seuzxh** [comment] 2018-04-11 04:31
@dnkoutso As you replied "It's because your subspec has no sources it gets integrated differently. "
Do you mean I should add some source_files for my subspec like this ?

```ruby
  s.subspec 'TestSub1' do |sub1|
    sub1.source_files = 'TestSub1/*.h'

    sub1.resources = 'TestSub1/Assets/testpodAset.xcassets' #'TestSub1/Assets/**/*.png'

  end
```

I've tried but also failed

**Comment by dnkoutso** [comment] 2018-04-11 04:32
Yeap

**Comment by seuzxh** [comment] 2018-04-11 04:35
Oh ~ I tried again, it pass validation.

**Comment by seuzxh** [comment] 2018-04-11 05:47
@dnkoutso  It pass validation after I add the `source_files ` 。
But I found if I add the `--use-libraries` option, it failed again with the same error message as I said before.  

pod lib lint --allow-warnings  --use-libraries --verbose --fail-fast --no-clean  **--use-libraries**

**Comment by dnkoutso** [comment] 2018-04-17 05:02
@seuzxh will need to investigate. sorry havent had time.

**Comment by passol1988** [comment] 2018-05-18 02:34
@seuzxh Did u have any solution?
I met same issue when I  ` --use-libraries` and it prompt `None of the input catalogs contained a matching stickers icon set or app icon set named  "AppIcon".`

**Comment by passol1988** [comment] 2018-05-18 03:35
I use cocoapods (version 1.4.0) is Ok.while 1.5.0 and 1.5.2 it reproduces error.

**Comment by seuzxh** [comment] 2018-05-18 05:08
@passol1988 I've no solution now, but @dnkoutso said this issue will be fixed in 1.6.0 version....
But I think this is a big issue for my team.....

**Comment by bazik123** [comment] 2018-09-04 08:58
is this fixed in 1.6.0-alfa?

have you found any workarounds?

**Comment by tomasgreen** [comment] 2018-10-17 14:01
For anyone still stuck on this, try adding an empty AppIcon to the assets, it's not graceful but it worked.

**Comment by JimmyYezeguelian** [comment] 2018-10-17 14:48
> For anyone still stuck on this, try adding an empty AppIcon to the assets, it's not graceful but it worked.

Yes of course but after that you'll find that you can't have multiple xcasset (https://github.com/CocoaPods/CocoaPods/pull/8136)

**Comment by tomasgreen** [comment] 2018-10-17 17:45
> > For anyone still stuck on this, try adding an empty AppIcon to the assets, it's not graceful but it worked.
> 
> Yes of course but after that you'll find that you can't have multiple xcasset (#8136)

Yeah, that was bad advice, turns out it way more effective to exclude it from the resources and add them as a resource bundle instead.

**Comment by zhgw01** [comment] 2018-11-05 06:52
Is there any plan to fix this issue?

**Comment by xdkhan** [comment] 2018-11-14 07:48
This bug still exists in the new version(1.6.0 beta2)

**Comment by amorde** [comment] 2018-11-15 00:06
PRs are welcome :)

**Comment by lucasanovaes** [comment] 2018-11-21 19:47
Still happening using `Xcode 10.0` and `cocoapods: 1.6.0.beta.2`

The only workaround is to add an empty "AppIcon" inside `.xcassets` 😅

**Closed** 2019-04-09 17:06 UTC
Labels: d2:moderate, help wanted, s2:confirmed, s7:workaround available, t2:defect
