### ISSUE TITLE
After installing pods, the result of Podfile.lock (checksum) is different among team members.

### ISSUE THREAD

**Issue by choiapril6** [CocoaPods/CocoaPods#8931] opened 2019-06-24 07:08 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
Run `pod install`

## What did you expect to happen?
Install all pod dependencies correctly, and no changes in Podfile.lock

## What happened instead?

Podfile.lock file has changed. A single line of some framework checksum has changed.
Among my teammates working on a same project, some face this issue, some don't. We guessed the reason is the version of Mac OS. Those who are using Mac OS 10.14.5 only faces this issue. 10.14.4 doesn't change Podfile.lock.

### Stack

```
   CocoaPods : 1.7.1
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.6
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 7d3114ff972ba97b39ffe4745121c15fa66a2e8b
               navercorp-specs - https://oss.navercorp.com/CocoaPods/Specs.git @ b37e1560239642f0e8b11ad337eb98bab8daa654
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-clean       : 0.0.1
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# -*- coding: utf-8 -*-
platform :ios, "10.0"
inhibit_all_warnings!
use_frameworks!

(and information about pods that we are using)

**Comment by dnkoutso** [comment] 2019-06-25 14:22
Are you certain you are running the same CocoaPods version? I cant see the reason why macOS would produce a different checksum. Also check the Ruby version you are using which might be related.

**Comment by choiapril6** [comment] 2019-06-27 05:29
The version of CocoaPods has no clue because we all have the same version. Also, I doubt if Ruby's version is the reason. All the information I have grasped is listed below. 

Now I want to note that why the checksum of that particular framework changes. 

Person | CocoaPods | Ruby | RubyGems | Host | The Checksum of Framework 'P'
-- | -- | -- | -- | -- | --
A | 1.7.1 | ruby 2.3.7p456 (2018-03-28 revision 63024) | 2.7.6 | Mac OS X 10.14.5 | X (Let's say X for short.)
B | 1.7.1 | ruby 2.3.7p456 (2018-03-28 revision 63024) | 2.6.14 | Mac OS X 10.14.4 | X
C | 1.7.1 | ruby 2.6.2p47 (2019-03-13 revision 67232) | 3.0.4 | Mac OS X 10.14.5 | X
D | 1.7.1 | ruby 2.3.7p456 (2018-03-28 revision 63024) | 3.0.3 | Mac OS X 10.14.4 | X
E | 1.7.1 | ruby 2.3.7p456 (2018-03-28 revision 63024) | 2.7.3 | Mac OS X 10.14.4 | Y (same as upstream)
F | 1.7.1 | ruby 2.5.1p57 (2018-03-29 revision 63029) | 3.0.4 | Mac OS X 10.14.5 | Y

**Comment by dnkoutso** [comment] 2019-06-27 11:35
Whats the framework? Is it published publicly or internal?

**Comment by choiapril6** [comment] 2019-06-28 02:35
It's a framework published only in-house.

**Comment by dnkoutso** [comment] 2019-06-28 03:21
> By the way, I've found that people with checksum X and people with checksum Y have different 'ThatInHouseFramework.podspec.json' file. The json file which produces checksum X has one more key-value pair, "swift_versions": "4.2", and the other doesn't. (Both have "swift_version": "4.2". "swift_versions" pair doesn't seem necessary though.) Which program produces json file? Maybe that would be the reason?

You see both `swift_versions` and `swift_version` due to backwards compatibility reasons. 

This seems to me you are using different version of CocoaPods for different people.

**Comment by cosmer-work** [comment] 2019-06-28 19:19
I can reproduce this on a single machine.

1. `pod install` no changes to Podfile.lock
2. Delete Pods directory
3. `pod install` several spec checksums are changed in Podfile.lock

Another member of my team, using the same version of CocoaPods, ends up with completely different checksums after running `pod install`.

The checksums are stable for some short period of time (a day?) but eventually end up changing again.

The problematic pods are all private frameworks that use `:git` in the app's Podfile to refer to a specific repository.

I think this started happening after updating from 1.6.1 to 1.7.2.

**Comment by dnkoutso** [comment] 2019-06-28 19:43
do you have a quick sample app/repo for me to test?

**Comment by dnkoutso** [comment] 2019-06-28 19:43
This might be the same as https://github.com/CocoaPods/CocoaPods/issues/8021

**Comment by cosmer-work** [comment] 2019-06-28 19:49
I don't have anything I can share at the moment.

**Comment by dnkoutso** [comment] 2019-06-28 19:51
This will be more difficult to repro without one. I'll try myself but no guarantees, otherwise the issue will be auto-closed due to inactivity.

**Comment by cosmer-work** [comment] 2019-06-28 20:31
My coworker and I currently getting different checksums for the same project. I had him send me the contents of 'Pods/Local Podspecs'. Our Foo.podspec.json files for the affected project are slightly different.

The last two items are in a different order. The contents is the same otherwise.

```
...
  "testspecs": [
    {
      "name": "Tests",
      "test_type": "unit",
      "source_files": "FooTests/*.swift",
      "resources": "FooTests/Examples/*"
    }
  ],
  "swift_version": "5.0"
}
```
```
... 
  "swift_version": "5.0",
  "testspecs": [
    {
      "name": "Tests",
      "test_type": "unit",
      "source_files": "FooTests/*.swift",
      "resources": "FooTests/Examples/*"
    }
  ]
}
```
I think that explains the different checksums.

**Comment by dnkoutso** [comment] 2019-06-28 20:35
weird indeed. The code is here for adding this value https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification/json.rb#L41

Again you had mentioned its the same version of Ruby correct?

**Comment by cosmer-work** [comment] 2019-06-28 20:39
Same version of CocoaPods. Not sure about Ruby and he just left for the day.

**Comment by cosmer-work** [comment] 2019-06-28 20:45
The swift version is specified in the library's podspec like this `s.swift_version = '5.0'`

**Comment by dnkoutso** [comment] 2019-06-29 01:17
Should be fine. Ruby since 1.9+ appears to be having ordered hashes. I cant figure out why in the world this would be out of place. I highly doubt cocoapods works on Ruby < 2.x so unless it does and your co-worker uses that then that might explain it.

Other than that, I am out of ideas and I would imagine plenty of others would be having this issue as `swift_version` is a very common DSL now.

I am sorry we will need a sample app or some very clear steps to reproduce.

**Comment by cltnschlosser** [comment] 2019-07-01 19:49
We had the same issue today after moving from Cocoapods 1.5.3 to 1.7.3 (Yeah big jump I know).

Issue was specifically with `pod 'CocoaLumberjack/Swift', git: 'https://github.com/CocoaLumberjack/CocoaLumberjack.git', commit: '9107ddcbd19acba752e6fa7bb85acb0ea63ca6bd'`

Had 3 different checksums appear, I only managed to get the actually podspec.jsons for 2 of them:

Interesting bit is:
```
  "swift_version": "5.0",
  "default_subspecs": "Core",
```
vs
```
  "swift_versions": "5.0",
  "default_subspecs": "Core",
  "swift_version": "5.0",
```

Deleting ~/.cocoapods and Pods/ resulted in everyone getting the latter, so that seems to be an effective workaround for now.

I also find it interesting that the podspec.json has:
```
  "source": {
    "git": "https://github.com/CocoaLumberjack/CocoaLumberjack.git",
    "tag": "3.5.2"
  },
```
When the source isn't locked to that tag it was locked to a specific commit.

We are also moving to `pod 'CocoaLumberjack/Swift', '~> 3.5.3'` now that the release is out, which I think should sidestep the issue.

**Comment by dnkoutso** [comment] 2019-07-01 19:58
For the bottom half the podspec does not matter since the source will be checked out at the commit you mentioned.

@cosmer-work @cltnschlosser you may have uncovered the issue. I think if you do `pod cache clean CocoaLumberjack` (or whatever Pod) you do then the checksums would be the same. The problem probably probably lies with the cache keeping the same podspec but a 1.7.x version is serializing it differently.

Try `pod cache clean --all` as well.

**Comment by cltnschlosser** [comment] 2019-07-02 17:26
Got a hold of the third a copy of the json with the third checksum. Looks like there is more at play here than just caching.
```
{
  "name": "CocoaLumberjack",
  "version": "3.5.2",
  "license": "BSD",
  "summary": "A fast & simple, yet powerful & flexible logging framework for Mac and iOS.",
  "homepage": "https://github.com/CocoaLumberjack/CocoaLumberjack",
  "authors": {
    "Robbie Hanson": "robbiehanson@deusty.com"
  },
  "source": {
    "git": "https://github.com/CocoaLumberjack/CocoaLumberjack.git",
    "tag": "3.5.2"
  },
  "description": "It is similar in concept to other popular logging frameworks such as log4j, yet is designed specifically for objective-c, and takes advantage of features such as multi-threading, grand central dispatch (if available), lockless atomic operations, and the dynamic nature of the objective-c runtime.",
  "requires_arc": true,
  "preserve_paths": "README.md",
  "platforms": {
    "ios": "8.0",
    "osx": "10.10",
    "watchos": "3.0",
    "tvos": "9.0"
  },
  "swift_versions": "5.0",
  "default_subspecs": "Core",
  "subspecs": [
    {
      "name": "Core",
      "source_files": [
        "Classes/CocoaLumberjack.h",
        "Classes/DD*.{h,m}",
        "Classes/Extensions/*.{h,m}",
        "Classes/CLI/*.{h,m}"
      ],
      "private_header_files": "Classes/DD*Internal.{h}"
    },
    {
      "name": "Swift",
      "dependencies": {
        "CocoaLumberjack/Core": [

        ]
      },
      "source_files": [
        "Classes/CocoaLumberjack.swift",
        "Classes/DDAssert.swift",
        "Classes/SwiftLogLevel.h"
      ]
    }
  ],
  "swift_version": "5.0"
}
```
vs
```
{
  "name": "CocoaLumberjack",
  "version": "3.5.2",
  "license": "BSD",
  "summary": "A fast & simple, yet powerful & flexible logging framework for Mac and iOS.",
  "homepage": "https://github.com/CocoaLumberjack/CocoaLumberjack",
  "authors": {
    "Robbie Hanson": "robbiehanson@deusty.com"
  },
  "source": {
    "git": "https://github.com/CocoaLumberjack/CocoaLumberjack.git",
    "tag": "3.5.2"
  },
  "description": "It is similar in concept to other popular logging frameworks such as log4j, yet is designed specifically for objective-c, and takes advantage of features such as multi-threading, grand central dispatch (if available), lockless atomic operations, and the dynamic nature of the objective-c runtime.",
  "requires_arc": true,
  "preserve_paths": "README.md",
  "platforms": {
    "ios": "8.0",
    "osx": "10.10",
    "watchos": "3.0",
    "tvos": "9.0"
  },
  "swift_versions": "5.0",
  "default_subspecs": "Core",
  "swift_version": "5.0",
  "subspecs": [
    {
      "name": "Core",
      "source_files": [
        "Classes/CocoaLumberjack.h",
        "Classes/DD*.{h,m}",
        "Classes/Extensions/*.{h,m}",
        "Classes/CLI/*.{h,m}"
      ],
      "private_header_files": "Classes/DD*Internal.{h}"
    },
    {
      "name": "Swift",
      "dependencies": {
        "CocoaLumberjack/Core": [

        ]
      },
      "source_files": [
        "Classes/CocoaLumberjack.swift",
        "Classes/DDAssert.swift",
        "Classes/SwiftLogLevel.h"
      ]
    }
  ]
}
```

The only difference is the ordering.

Running `cat Pods/Local\ Podspecs/CocoaLumberjack.podspec.json | openssl sha1` matches the checksums that we are seeing:
`3ef0f6416179d266edb7f7d23bd6aa239ff6fcec` vs `70fd1db68ba3dd53f58acce1f6e1bfaee3c2b137`

**Comment by dnkoutso** [comment] 2019-07-02 17:28
This again appears the ordering from each version being serialized. `swift_version` used to be part of the attributes but then was moved for backwards compatible change as a separate entry.

Did you ask and run `pod cache clean --all`?

**Comment by cltnschlosser** [comment] 2019-07-02 17:32
Oh getting `3ef0f6416179d266edb7f7d23bd6aa239ff6fcec` after `pod cache clean --all` didn't realize that the order changed across different versions.

**Comment by dnkoutso** [comment] 2019-07-02 17:36
You have a workaround for now which is to run `pod cache clean --all`

**Comment by dnkoutso** [comment] 2019-07-08 20:18
@choiapril6 @cosmer-work @cltnschlosser 

We discussed a bit internally on how to tackle this. It appears this was a bad miss in 1.7.x to handle backwards compatibility with 1.6.x.

I do not think we will make any changes currently to put `swift_version` (singular form) _back_ to its correct order as people who have upgraded will face the same issue that you filed here in the first place.

We will push forward with what we have for now and ensure in the future the ordering of JSON entries does not change.

The workaround for all teams is to use `pod cache clean <podname>` or `pod cache clean --all` to ensure a consistent podspec is used during installation.

I am going to close this for now but feel free to pushback as why we should tackle it or not.

Apologies again for the inconvenience this has caused and thank you for persisting in identifying its root cause.

**Closed by dnkoutso** 2019-07-08 20:18 UTC
Labels: s2:confirmed, s7:workaround available, t2:defect

**Comment by choiapril6** [comment] 2019-07-15 08:43
@dnkoutso 
One of my team can not solve the problem with `pod cache clean <podname> or pod cache clean --all`. Which version do you think this issue will be improved?

**Comment by KorolZhu** [comment] 2019-09-29 02:52
the swift_version order issue also happened two me, in my single computer,  single Project, but two directory in two branch. i found a workaround for just delete the Pods/Local Podspecs/xxx.podspec.json and then pod install.

**Comment by dnkoutso** [comment] 2019-09-29 03:03
this was fixed in 1.8.1 with https://github.com/CocoaPods/Core/pull/592. 

We expect some folks to get this issue as things stabilize with a deterministic JSON serialization.

run `rm -rf Pods/` then  `pod cache clean --all` and then `pod install`.

**Comment by KorolZhu** [comment] 2019-09-29 03:11
Fantastic， thanks ！

**Comment by asikora-sf** [comment] 2019-10-22 19:48
@dnkoutso Related, we're seeing an issue where the swift_versions array is containing duplicate values sometimes in the Local Podspecs projectname.podspec.json like so:
```
"swift_versions": [
    "5.0",
    "5.1",
    "5.1"
  ],
```

This occurs randomly with cocoapods 1.7.5

Does the fix for this issue resolve that? It seems like you stopped 'modifying the original' so it seems likely?

**Comment by dnkoutso** [comment] 2019-10-22 19:53
Yes it is fixed in 1.8.4 IIRC or 1.8.3 Please upgrade to that and publish a new version. CocoaPods should be able to handle this erroneous serialized JSON file correctly either way despite the duplicate.

You might get some changes with spec checksums which is unfortunate but it should continue to work from now on.

**Comment by asikora-sf** [comment] 2019-10-22 19:53
@dnkoutso thank you very much!

**Comment by asikora-sf** [comment] 2019-10-22 19:54
Yeah our issue is the checksum being different, it still all 'worked' but was a struggle as we wanted to verify the correct dependency.

**Comment by dnkoutso** [comment] 2019-10-22 19:55
Its a shitty issue but it will get fixed by moving forward.

**Comment by wustzhy** [comment] 2020-10-22 04:42
This issue happened on my team, too.
Finally, I found that  my xx.podspec.json was different from other males'. Although there is only one line break difference.
<img width="1111" alt="图片" src="https://user-images.githubusercontent.com/20319474/96825264-4b258500-1463-11eb-8118-11432a8e0885.png">

so, I replace mine with other workmate's xx.podspec file. Then the checksum value of xx is same with other's, after pod install.

I suspect that I accidentally operated this file by hand, which led to the difference between this file and that of others.

**Comment by SudoPlz** [comment] 2021-05-11 13:55
I'm facing this issue with cocoapods 1.10.1 with react-native pod dependencies that look like:

`pod 'RNCAsyncStorage', :path => '../node_modules/@react-native-community/async-storage'`

between my local environment and our CI/CD.
Before pushing to our CI/CD (github actions) we always `pod update` to make sure the lockfile is updated to the latest dependencies, but still different checksums are produced.

Any idea what's going on?
Any idea what the problem is?

**Comment by TomSwift** [comment] 2021-06-02 21:45
> Any idea what's going on?

@SudoPlz I had a very similar issue to yours which turned out to be https://github.com/facebook/react-native/issues/31121.  The patch in that issue resolved it for me.

**Comment by SudoPlz** [comment] 2022-03-17 15:36
@TomSwift unfortunately it's not FBReactNativeSpec that's changing, it's many of my dependencies:

```
diff --git a/ios/Podfile.lock b/ios/Podfile.lock
index 7564fbe..b3ceebf 100644
--- a/ios/Podfile.lock
+++ b/ios/Podfile.lock
@@ -601,7 +601,7 @@ SPEC CHECKSUMS:
   Amplitude-iOS: df355e2be58972041acde9576a2ae97c217bf941
   Base64: cecfb41a004124895a7bcee567a89bae5a89d49b
   boost: a7c83b31436843459a1961bfd74b96033dc77234
-  CodePush: 35a0d8be82686010ee70b510c3549ba8df5ca737
+  CodePush: b51b7ac64c07d4eacfc8cc5750a1dd28adbf2528
   DoubleConversion: 831926d9b8bf8166fd87886c4abab286c2422662
   FBLazyVector: 808f741ddb0896a20e5b98cc665f5b3413b072e2
   FBReactNativeSpec: 94473205b8741b61402e8c51716dea34aa3f5b2f
@@ -618,7 +618,7 @@ SPEC CHECKSUMS:
   JWT: ef71dfb03e1f842081e64dc42eef0e164f35d251
   libevent: 4049cae6c81cdb3654a443be001fb9bdceff7913
   nanopb: a0ba3315591a9ae0a16a309ee504766e90db0c96
-  Permission-Camera: 273b78e214eae8d734d1c497b67aa0030838c006
+  Permission-Camera: bae27a8503530770c35aadfecbb97ec71823382a
   PromisesObjC: 68159ce6952d93e17b2dfe273b8c40907db5ba58
   RCT-Folly: 803a9cfd78114b2ec0f140cfa6fa2a6bafb2d685
   RCTRequired: 3c77b683474faf23920fbefc71c4e13af21470c0
@@ -633,13 +633,13 @@ SPEC CHECKSUMS:
   React-jsiexecutor: 15ea57ead631a11fad57634ff69f78e797113a39
   React-jsinspector: 1e1e03345cf6d47779e2061d679d0a87d9ae73d8
   React-logger: 1e10789cb84f99288479ba5f20822ce43ced6ffe
-  react-native-add-calendar-event: e501cea7d393396ff1e798c462983c9e6d8dfc02
+  react-native-add-calendar-event: d7744f983d6770cc9e4f004db22bc4d4b4575f17
   react-native-amplitude-analytics: a6513b42f3e84ef46a487aa4ebaa28e60ba36c3f
-  react-native-camera: 6e6d25f6318980dd2837747760628b4442aac01a
-  react-native-gleapsdk: fcb88d1286718b68f439f14574760ad17cbe82aa
-  react-native-netinfo: 29d4129ffb7fd4722984f96bfd5100e5e6e2344e
-  react-native-safe-area-context: 6dc26ec4f287a718145984fc47701b8531311ac2
-  react-native-webview: 77ee909f73e1fcab76380f7dcc3344771fe61bd8
+  react-native-camera: 7bf59f2728ffb019fa25e60a225d2c57e1a8f0f6
+  react-native-gleapsdk: b29a7cbd6019e687bea4314a06f2828b57f0ac38
+  react-native-netinfo: 379ba2af7d2abcec0c062267abe1c9a977c72bf9
+  react-native-safe-area-context: 4a34aba6110f050b5eacf14d23525b1d95158898
+  react-native-webview: 380c1a03ec94b7ed764dac8db1e7c9952d08c93a
   React-perflogger: 93d3f142d6d9a46e635f09ba0518027215a41098
   React-RCTActionSheet: 87327c3722203cc79cf79d02fb83e7332aeedd18
   React-RCTAnimation: 009c87c018d50e0b38692699405ebe631ff4872d
@@ -652,14 +652,14 @@ SPEC CHECKSUMS:
   React-RCTVibration: d0361f15ea978958fab7ffb6960f475b5063d83f
   React-runtimeexecutor: af1946623656f9c5fd64ca6f36f3863516193446
   ReactCommon: 650e33cde4fb7d36781cd3143f5276da0abb2f96
-  RNCAsyncStorage: c0754b486fec6e532d358bfd7337cb45c8d2c897
-  RNCMaskedView: f127cd9652acfa31b91dcff613e07ba18b774db6
-  RNDeviceInfo: 240b4cc18b24ac8ba1bffeae7e72a289b93dcfd9
+  RNCAsyncStorage: b49b4e38a1548d03b74b30e558a1d18465b94be7
+  RNCMaskedView: 0e1bc4bfa8365eba5fbbb71e07fbdc0555249489
+  RNDeviceInfo: a674f06c5a5bd496aebb809cbc3be61cfd612a65
   RNFBApp: 5bae3002117e55f3c9aa0fb38175dd16c8046c90
   RNFBDynamicLinks: af1099d827079101afece32aba470ae50d519217
   RNGestureHandler: a479ebd5ed4221a810967000735517df0d2db211
   RNKeychain: 4f63aada75ebafd26f4bc2c670199461eab85d94
-  RNPermissions: 7ad8d93b004e6bc85c89e27a102afcde90e07efa
+  RNPermissions: 34d678157c800b25b22a488e4d8babb57456e796
   RNReactNativeHapticFeedback: 4085973f5a38b40d3c6793a3ee5724773eae045e
   RNReanimated: c1b56d030d1616239861534d9adb531f8cffab68
   RNScreens: 40a2cb40a02a609938137a1e0acfbf8fc9eebf19
(END)
```

and I'm using "react-native": "0.67.3" so the previous issue (absolute to relative paths) should be fixed.
:/

**Comment by choiapril6** [comment] 2025-03-26 08:45
I ran into this issue again while looking for a solution.  

Following @wustzhy’s suggestion, I fixed it by replacing `Texture.podspec.json` and `TextureSwiftSupport.podspec.json` in `Pods/Local Podspecs/` with the upstream versions, then running `pod install`. Now, `Podfile.lock` matches the upstream version.  

I never modified `Texture.podspec.json` or `TextureSwiftSupport.podspec.json` myself, so I’m not sure how the discrepancy happened.

**Comment by vietstone-ng** [comment] 2025-07-25 07:47
oh, I face this problem today, me and my teammate.

**The cause is one use `pod by gem`, another use `pod by brew`.** It results in different dependency versions (ruby and json).

Just get all using the same installation, then problem is fixed.

**Comment by harryzjm** [comment] 2025-09-02 05:50
In our case, you need to update cocoapds to keep the minor version consistent
```shell
brew list cocoapods
/opt/homebrew/Cellar/cocoapods/1.16.2_1
```
Because 1.16.2 and 1.16.2_1, --version will all print `1.16.2`
```shell
~$ > pod --version
1.16.2
```
