### ISSUE TITLE
`pod spec lint` rewrote my repo's remote url to point at CocoaPods/Specs

### ISSUE THREAD

**Issue by kballard** [CocoaPods/CocoaPods#5828] opened 2016-09-08 19:04 UTC
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I installed CocoaPods version 1.1.0.beta.2, then ran `pod spec lint` in my local repo.

## What did you expect to happen?

It should have linted.

## What happened instead?

It rewrote my local git repo's remote to point at https://github.com/CocoaPods/Specs.git, checked out the master branch of my repo (I was on another branch), and then threw an error about being in the wrong directory:

>     - ERROR | [iOS] unknown: Encountered an unknown error (Must be in the root of the repo (/Users/kevinballard/.cocoapods/repos/master), instead in /Users/kevinballard/Dev/Postmates/PMJSON.) during validation.

### Stack

```
   CocoaPods : 1.1.0.beta.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 77052f80878c01c85457152e6c180d4037279f14
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

I reproduced this problem with https://github.com/postmates/PMJSON. After running it once, running it a second time doesn't reproduce the issue, but if I rewrite the remote URL to point it back to the correct URL, `pod spec lint` breaks again.

**Comment by orta** [comment] 2016-09-08 19:05
Thanks for the issue, this is a dupe of https://github.com/CocoaPods/CocoaPods/issues/5823 fixed by https://github.com/CocoaPods/Core/pull/352 - we'll be releasing an RC to fix it soon

**Closed by orta** 2016-09-08 19:05 UTC

**Comment by robertofrontado** [comment] 2016-09-22 00:27
Having the same issue here, don't know what to do,

Error:
```
[!] Found podspec `OkDataSources.podspec`
Updating spec repo `master`

CocoaPods 1.1.0.rc.2 is available.
To update use: `sudo gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information, see https://blog.cocoapods.org and the CHANGELOG for this version at https://github.com/CocoaPods/CocoaPods/releases/tag/1.1.0.rc.2

Validating podspec
 -> OkDataSources (1.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Must be in the root of the repo (/Users/robertofrontado/.cocoapods/repos/master), instead in /Users/robertofrontado/Documents/Proyectos iOS/OkDataSources-iOS.) during validation.

[!] The spec did not pass validation, due to 1 error.
```

And my podspec:
```
Pod::Spec.new do |s|
  s.name         = "OkDataSources"
  s.version      = "1.0.0"
  s.summary      = "Wrappers for iOS TableView and CollectionView DataSources to simplify its api at a minimum. Also it has a cool PagerView and SlidingTabs!."

  s.homepage     = "https://github.com/FuckBoilerplate/OkDataSources"
  s.license = { :type => "MIT", :file => "LICENSE" }

  s.author             = { "Roberto Frontado" => "robertofrontado@gmail.com" }
  s.source           = { :git => "https://github.com/FuckBoilerplate/OkDataSources.git", :tag => "v#{s.version}" }
  s.social_media_url   = "https://github.com/FuckBoilerplate"

  s.ios.deployment_target = '8.0'
  s.requires_arc = true

  s.default_subspec = "Core"

  s.subspec "Core" do |ss|
    ss.source_files = 'Library/*.swift'
  end

  s.subspec "RxSwift" do |ss|
    ss.source_files = "Library/RxSwift/*.swift"
    ss.dependency "OkDataSources/Core"
    ss.dependency "RxSwift", ">= 3.0.0-beta.1"
  end
  
end
```

**Comment by perfectpapa** [comment] 2016-09-28 03:24
Having the same issue here,and my pod version is 1.1.0.beta.2

```
-> NTTDataBankBaseFramework (0.1.2)
    - WARN  | url: There was a problem validating the URL https://twitter.com/Melo_Wang.
    - WARN  | [iOS] license: Unable to find a license file
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 1 error and 2 warnings.

```
pod version
```
pod --version
1.1.0.beta.2
```
my private repo remote changed
```
~/.cocoapods/repos/private$ git remote -v
origin	https://github.com/CocoaPods/Specs.git (fetch)
origin	https://github.com/CocoaPods/Specs.git (push)

```
help me plz

**Comment by iDevelopper** [comment] 2016-10-02 10:49
Re-installing Xcode 7.3.1, setting the path for the active developer directory of Xcode 7. This fixes the issue. Pod lint passe validation!

Also:


```
[patrickbodet : ~/Documents/PBRevealViewController] > sudo gem install cocoapods --pre
Password:
Successfully installed cocoapods-1.1.0.rc.2
Parsing documentation for cocoapods-1.1.0.rc.2
Done installing documentation for cocoapods after 2 seconds
1 gem installed
[patrickbodet : ~/Documents/PBRevealViewController] > pod --version
1.0.1
```

**Comment by robertofrontado** [comment] 2016-10-02 16:57
Solved issue for me, I wasn't using the right version of cocoapods (Using `1.0.1` instead of `1.1.0.rc.2`) 😅  So I uninstalled all of them and installed the newer one and it worked 👍

**Comment by iDevelopper** [comment] 2016-10-02 17:07
Yes, you can see also #5987

**Comment by iDevelopper** [comment] 2016-10-02 17:09
Ouf !!

**Comment by cbernardone** [comment] 2016-10-03 19:42
I'm having the same issue and am not clear on what you're saying to solve it. Are you saying to downgrade Xcode to 7? I tried updating cocoa pods to 1.1.0.rc.2, but its not taking.

**Comment by cbernardone** [comment] 2016-10-03 20:05
It's okay, I figured it out. No need to downgrade Xcode. Just need to get to cocoapods-1.1.0.rc.2 with Xcode 8. Although cocoapods-1.1.0.rc.2 installs properly, you must also delete the prior version in order for it to get used. So first do "sudo gem install cocoapods --pre" and then do "sudo gem uninstall cocoa pods". It will prompt you which version to remove. Remove the older version and it will use the newer version. This will make the pod lib lint error go away.

**Comment by robertofrontado** [comment] 2016-10-03 20:08
@cbernardone That's right, you just have to use Xcode 8 with the right version of cocoapods 👍

**Comment by cbernardone** [comment] 2016-10-03 20:16
Thanks @robertofrontado.

**Comment by iDevelopper** [comment] 2016-10-03 20:21
@cbernardone , Yes, we have to delete the old version of cocoapods, which was not very clear to me.
