### ISSUE TITLE
Bug in 1.6.0.rc.2 breaks build

### ISSUE THREAD

**Issue by wolfmcnally** [CocoaPods/CocoaPods#8488] opened 2019-02-06 00:20 UTC
* 🌈 I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Attempted to build an existing project that builds successfully under CocoaPods 1.6.0.beta.2 with 1.6.0.rc.2.

## What did you expect to happen?

A successful build.

## What happened instead?

The build fails at compile-time because one of the top-level dependencies cannot find its lower dependencies.

### Stack

```
   CocoaPods : 1.6.0.rc.2
        Ruby : ruby 2.4.1p111 (2017-03-22 revision 58053) [x86_64-darwin17]
    RubyGems : 2.6.14
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.20.1
Ruby lib dir : /Users/ironwolf/.rvm/rubies/ruby-2.4.1/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 167f9e3661aa91569aaf4ed4d8d918a93cf6593d
```

### Installation Source

```
Executable Path: /Users/ironwolf/.rvm/rubies/ruby-2.4.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!
platform :ios, '12.0'

workspace 'CryptoWallet.xcworkspace'

project 'CryptoWallet.xcodeproj'

target 'CryptoWallet' do
   pod 'LifeHash'
end
```

## Project that demonstrates the issue

✅ Detailed README included.

https://github.com/wolfmcnally/LifeHashBuildTest

**Comment by dnkoutso** [comment] 2019-02-06 00:31
I get a build error on 1.6.0.beta.2 and 1.6.0.rc2. So i dont think its a regression.

```
Showing All Errors Only
/Users/dnkoutso/Development/ios/LifeHashBuildTest/Pods/LifeHash/LifeHash/Classes/FracGrid.swift:36:9: Use of unresolved identifier 'forAll'
```

Is this what you are getting too (and a bunch of other similar errors?)

**Comment by dnkoutso** [comment] 2019-02-06 00:32
Apologies, going over readme now.

**Comment by dnkoutso** [comment] 2019-02-06 00:35
@amorde I can confirm `$(ARCHS_STANDARD_64_BIT)` causes this as in the README. Is this similar to the other issue with workaround?

**Comment by wolfmcnally** [comment] 2019-02-06 00:49
@dnkoutso Below is a random sampling of errors. I get 84 errors when building and they appear to be behaving as if the declarations in the dependencies don't exist, although the `import` directives don't cause errors.

As to what versions it's happening on, I've switch back and forth between 1.6.0.beta.2 and 1.6.0.rc.2 many times. For me it *never* happens on beta.2 and *always* happens on rc.2.

```
/Users/ironwolf/Dropbox/LifeHashBuildTest/Pods/LifeHash/LifeHash/Classes/BitEnumerator.swift:95:24: Use of undeclared type 'Frac'
/Users/ironwolf/Dropbox/LifeHashBuildTest/Pods/LifeHash/LifeHash/Classes/ColorGrid.swift:38:40: Use of undeclared type 'ColorFunc'
/Users/ironwolf/Dropbox/LifeHashBuildTest/Pods/LifeHash/LifeHash/Classes/FracGrid.swift:31:16: Use of undeclared type 'IntSize'
/Users/ironwolf/Dropbox/LifeHashBuildTest/Pods/LifeHash/LifeHash/Classes/Gradients.swift:131:5: Use of unresolved identifier 'Color'
/Users/ironwolf/Dropbox/LifeHashBuildTest/Pods/LifeHash/LifeHash/Classes/Grid.swift:63:18: Use of unresolved identifier 'makeCircularIndex'
```

**Comment by dnkoutso** [comment] 2019-02-06 01:20
@wolfmcnally the problem is `$(ARCHS_STANDARD_64_BIT)` once I set that it actually worked.

**Comment by dnkoutso** [comment] 2019-02-06 01:20
It is weird because I get it on 1.6.0.beta.2...

**Comment by amorde** [comment] 2019-02-06 01:46
I added logic to remove `$(ARCHS_STANDARD_64_BIT)` on Xcode 10 because Xcode 10.1 would produce a warning if the deployment target was iOS 11+ and specified the `ARCHS` setting (see #8242 for details). The way CocoaPods detects whether it is Xcode 10 or not is via the `Project Format` of the user project (_not_ `Pods.xcodeproj` but your actual project). Changing the version to a lower one such as `Xcode 8.0 Compatible` should revert to the behavior of `1.6.0.beta.2`

Will try to look into your sample project tonight to see if I notice anything but hope that provides some context

**Comment by amorde** [comment] 2019-02-06 02:34
Ok, dug into it some more, its looks like these lines in the podspec may be affecting this https://github.com/CocoaPods/Specs/blob/697e4d4590c1286948a38fc891843754107b3a85/Specs/1/2/4/LifeHash/0.2.1/LifeHash.podspec.json#L21-L22

If you select the `LifeHash` target in the Pods project and change `Build Active Architecture Only` to `YES` then the build succeeds.

**Comment by amorde** [comment] 2019-02-06 02:36
Since the dependencies will only be built for the active architecture, it makes sense the target will fail to build when building non-active architectures. It seems that this only worked before because CocoaPods was forcing 64-bit architectures in certain scenarios

**Comment by dnkoutso** [comment] 2019-02-06 02:52
@amorde is this a non-issue and it should be fixed by podspec then?

**Comment by wolfmcnally** [comment] 2019-02-06 04:35
@amorde @dnkoutso Success! Looking at your findings I made the following change to LifeHash.podspec:

```ruby
    s.pod_target_xcconfig = {
        'SWIFT_OPTIMIZATION_LEVEL' => '-O',
        'SWIFT_COMPILATION_MODE' => 'wholemodule'
#        ,
#        'ARCHS' => '$(ARCHS_STANDARD)',
#        'ONLY_ACTIVE_ARCH' => 'NO'
    }
```

I  believe I added these lines after analyzing the release build settings, so the debug build would still be optimized for speed even during the default build. But the second two lines really aren't necessary for this— I think they were part of what changed for the release build. Removing them lets the build succeed, even when the Project Format setting is set to `Xcode 10.0-compatible`.

**Comment by amorde** [comment] 2019-02-06 06:44
👍 thanks for the very detailed report! Going to close as this seems to not be a bug in CocoaPods

**Closed by amorde** 2019-02-06 06:44 UTC
