### ISSUE TITLE
Error on pod install 

### ISSUE THREAD

**Issue by ivan-mercaux** [CocoaPods/CocoaPods#4816] opened 2016-01-25 13:13 UTC
### Command

```
/Users/administrator/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/administrator/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 14277b13b3f5ac8c54e73ff2849beaa420fadb4c
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
platform :ios, '7.0'

pod 'AFNetworking', '~> 3.0'
pod 'ZBarSDK', '~> 1.3'
pod 'SQLClient', '~> 0.1'

target 'Mercaux' do
  pod 'ReactiveCocoa', '~> 2.4'
end

target 'MercauxTests' do

end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworking">
Did you mean?  to_query
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/administrator/.rvm/gems/ruby-2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/administrator/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/administrator/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/administrator/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/administrator/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by orta** [comment] 2016-01-25 13:15
Thanks @ivan-mercaux  - Closing as a dupe of https://github.com/CocoaPods/CocoaPods/issues/4391

**Closed by orta** 2016-01-25 13:15 UTC
