### ISSUE TITLE
Integrating Client Project Speed Issue

### ISSUE THREAD

**Issue by brianmichel** [CocoaPods/CocoaPods#4043] opened 2015-08-19 21:07 UTC
I've noticed that the integration time of running `pod install` seems to has gone up significantly in the recently releases. I re-read the 0.38 blog post and found that there was an feature I could opt out of for the deterministic UUID generation (Thanks @neonichu!), but it doesn't seem to have improved performance. Here are the results...

**With** _COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true_
`pod install  63.12s user 6.26s system 61% cpu 1:52.20 total`

**Without** _COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true_
`pod install  64.98s user 7.50s system 65% cpu 1:51.01 total`

Are there more places for me to inspect what is going on with CocoaPods, I'd like to gather more performance info on my own before bugging everyone, but I ran out of options without pointers into the source.

**Comment by segiddins** [comment] 2015-08-19 21:45
could you try running with `--verbose` and eyeballing which section of the install process is taking the longest? Outside of the, ruby-prof or sharing a pod file with us is probably your best bet :/

**Comment by brianmichel** [comment] 2015-08-20 01:42
I can share the file, but I'd prefer to do so in private if we get to that point. Let me check out the verbose output first and see what I can find!

**Comment by brianmichel** [comment] 2015-08-21 18:26
So I checked the verbose output and this step seemed to take a long time specifically. 

`  - Writing Xcode project file to 'Pods/Pods.xcodeproj'`

Any idea where I should look into the source for where this part of the gem is executing?

**Comment by segiddins** [comment] 2015-08-21 18:32
That sounds exactly like deterministic UUID generation... are you sure you're running 0.38.2, and using `COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true`?

**Comment by brianmichel** [comment] 2015-08-21 18:35
@segiddins I will double check, and rerun my tests, but I am fairly certain.

**Comment by MP0w** [comment] 2015-08-24 11:58
I can confirm that Deterministic UUIDS have a big impact on projects that are using many pods. Generating the project takes multiple minutes (>5) unless I use `COCOAPODS_DISABLE_DETERMINISTIC_UUIDS=true` (~40 seconds to generate the project).
Unfortunately I can't share the project but should be the same for every projects with many pods

**Comment by segiddins** [comment] 2015-08-29 18:44
To anyone else reading this -- I will need a reproduction example I can run in order to debug why UUID generation is so slow, otherwise you'll have to try and optimize that code in Xcodeproj yourself.

**Comment by segiddins** [comment] 2015-08-29 19:38
It's possible that https://github.com/CocoaPods/Xcodeproj/pull/300 might help

**Comment by segiddins** [comment] 2015-10-06 00:40
Closing, presuming the linked-to PR improves things since I never got any feedback on it.

**Closed by segiddins** 2015-10-06 00:40 UTC
Labels: s1:awaiting input, s4:awaiting validation
