### ISSUE TITLE
Deleted Workspace and can't get it back.

### ISSUE THREAD

**Issue by mommyme** [CocoaPods/CocoaPods#4534] opened 2015-11-12 19:38 UTC
I deleted Cocoapods from my project, and now I am trying to add it back in. When I run pod install, the workspace is not created. It had previously been created but was deleted. I have tried all of these solutions:

pod setup
pod install 
If that doesn't work, try removing the cocoapods directory ~/.cocoapods and running pod setup and install again.

rm -rf ~/.cocoapods 
pod setup
pod install
If that doesn't work either, remove the cocoapods directory again and manually clone the specs repo into ~/.cocoapods/repos/master and run pod install

rm -rf ~/.cocoapods 
git clone https://github.com/CocoaPods/Specs.git ~/.cocoapods/repos/master
pod install
and none have resulted in recreating the workspace. I could really use some help.

**Comment by segiddins** [comment] 2015-11-12 21:31
Please share a project that has this problem so we can debug?

**Comment by neonichu** [comment] 2015-11-19 09:20
Closing, because we never got a project to reproduce this.

**Closed by neonichu** 2015-11-19 09:20 UTC
Labels: s1:awaiting input
