### ISSUE TITLE
Xibs in named resource bundles that use size classes compile as iphone-only xibs

### ISSUE THREAD

**Issue by klundberg** [CocoaPods/CocoaPods#3536] opened 2015-05-07 17:52 UTC
I have an internal library at my company that has 4 xibs in it, three of which had size classes turned on. The ones that did have size classes on ended up with ~iPhone suffixes in the named resource bundle our internal pod uses, which causes the app to crash when it tries to load that xib on iPads. I can disable size classes since they aren't necessary strictly for those xibs, but that's not a great solution if we do want to include varying content per size class in a single xib in the future. CocoaPods should be smart enough to make xcode build the xib properly when put inside a named resource bundle. I assume this is a problem in the copy pods resources script.

My app currently has an iOS 7 deployment target which is probably why the ~iPhone prefix was added in the first place, I presume an iOS 8 target would not add the prefix at all.

**Comment by klundberg** [comment] 2015-05-07 18:11
Another workaround is to change my podspec from using the resource_bundles key to the resources key. This causes the ibtool commands in the copy pods resources script to work properly on each item in the pod individually instead of the entire bundle file at once which doesn't recurse into the bundle's contents it seems.

**Comment by neonichu** [comment] 2015-05-07 20:02
Can you check out #3463 and see if this is a duplicate of that? It seems to me that it is.

**Comment by neonichu** [comment] 2015-06-17 12:31
Let's consider this resolved, as no more information was given.

**Closed by neonichu** 2015-06-17 12:31 UTC
Labels: s1:awaiting input
