### ISSUE TITLE
Init methods must return a type related to the receiver type

### ISSUE THREAD

**Issue by igabrielsabiescu** [CocoaPods/CocoaPods#5614] opened 2016-07-11 12:29 UTC
# Report

## What did you do?

I'm using a swift development pod.
I ran pod update on my project

## What did you expect to happen?

A compiled framework and a running project that incldues the compiled framework

## What happened instead?

The process fails to compile:

../PoqPlatform.framework/Headers/PoqPlatform-Swift.h:5592:1: Init methods must return a type related to the receiver type

From what i observed is that the swift environment seems to have an issue with the generated swift files

Bellow the block of code that generates this issue.
Is there a way a used class can be ommited from generating the swift header file ?

```swift
- SWIFT_CLASS("_TtC11PoqPlatform20TabBarViewController")
@interface TabBarViewController : UITabBarController <UINavigationControllerDelegate, UITabBarControllerDelegate>
@property (nonatomic, strong) UIView * _Nullable middleTabBarItem;
@property (nonatomic, strong) UIButton * _Nullable middleBtn;
@property (nonatomic, strong) UIImageView * _Nullable middleImage;
@property (nonatomic, strong) UILabel * _Nonnull middleTextLabel;
@property (nonatomic, copy) NSArray<TabBarBadgeView *> * _Nonnull badges;
@property (nonatomic) BOOL tabBarVisible;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull tabTitles;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull tabs;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull tabIcons;
@property (nonatomic, copy) NSArray<NSString *> * _Nonnull selectedTabIcons;
- (void)viewDidLoad;
- (void)viewDidLayoutSubviews;
- (void)viewDidAppear:(BOOL)animated;
- (void)setUpTabs;
- (PoqNavigationViewController * _Nonnull)getHomeController:(NSInteger)index;
- (PoqNavigationViewController * _Nonnull)getStoresController:(NSInteger)index;
- (PoqNavigationViewController * _Nonnull)getShopController:(NSInteger)index;
- (PoqNavigationViewController * _Nonnull)getBagController:(NSInteger)index;
- (PoqNavigationViewController * _Nonnull)getWishlistController:(NSInteger)index;
- (PoqNavigationViewController * _Nonnull)getMyProfileController:(NSInteger)index;
- (PoqNavigationViewController * _Nonnull)getMoreController:(NSInteger)index;
- (PoqNavigationViewController * _Nonnull)getTinderController:(NSInteger)index;
- (void)setCustomMiddleBtn;
- (void)middleButtonTapped;
- (void)tapTwice;
- (void)showMiddleButton;
- (void)setMiddleButtonSelected;
- (void)setMiddleButtonUnselected;
- (void)tabBar:(UITabBar * _Nonnull)tabBar didSelectItem:(UITabBarItem * _Nonnull)item;
- (BOOL)tabBarController:(UITabBarController * _Nonnull)tabBarController shouldSelectViewController:(UIViewController * _Nonnull)viewController;
- (void)setBadge:(NSInteger)index badgeValue:(NSString * _Nullable)badgeValue;
- (void)removeBadge:(NSInteger)index badgeValue:(NSString * _Nullable)badgeValue;
- (NSString * _Nullable)getBadge:(NSInteger)index;
- (UIView * _Nullable)viewForTabBarItemAtIndex:(NSInteger)index;
- (UITabBarItem * _Nonnull)initTabBarItem:(NSInteger)index;
- (nonnull instancetype)initWithNibName:(NSString * _Nullable)nibNameOrNil bundle:(NSBundle * _Nullable)nibBundleOrNil OBJC_DESIGNATED_INITIALIZER;
- (nullable instancetype)initWithCoder:(NSCoder * _Nonnull)aDecoder OBJC_DESIGNATED_INITIALIZER;
@end
```

**Comment by neonichu** [comment] 2016-07-11 14:03
The issue is that your `initTabBarItem` method breaks Cocoa conventions which isn't such a good idea. You can control the generation of the ObjC compatibility header with the `SWIFT_INSTALL_OBJC_HEADER` build setting.

In any case, the generation of that header has nothing to do with CocoaPods, so I'm going to close this issue.

**Closed by neonichu** 2016-07-11 14:03 UTC
