### ISSUE TITLE
CocoaPods changed the origin of my repo to CocoaPods/Specs

### ISSUE THREAD

**Issue by DaveWoodCom** [CocoaPods/CocoaPods#5771] opened 2016-08-21 10:31 UTC
🌈
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Was updating my `.podspec` file (`pod trunk push XCGLogger.podspec`), for some reason the linting failed (have only changed the version/tag info). So I figured I'd try the beta version:

```
sudo gem install cocoapods --pre
Fetching: cocoapods-core-1.1.0.beta.1.gem (100%)
Successfully installed cocoapods-core-1.1.0.beta.1
Fetching: molinillo-0.5.0.gem (100%)
Successfully installed molinillo-0.5.0
Fetching: fourflusher-1.0.1.gem (100%)
Successfully installed fourflusher-1.0.1
Fetching: gh_inspector-1.0.2.gem (100%)
Successfully installed gh_inspector-1.0.2
Fetching: cocoapods-1.1.0.beta.1.gem (100%)
Successfully installed cocoapods-1.1.0.beta.1
Parsing documentation for cocoapods-core-1.1.0.beta.1
Installing ri documentation for cocoapods-core-1.1.0.beta.1
Parsing documentation for molinillo-0.5.0
Installing ri documentation for molinillo-0.5.0
Parsing documentation for fourflusher-1.0.1
Installing ri documentation for fourflusher-1.0.1
Parsing documentation for gh_inspector-1.0.2
Installing ri documentation for gh_inspector-1.0.2
Parsing documentation for cocoapods-1.1.0.beta.1
Installing ri documentation for cocoapods-1.1.0.beta.1
5 gems installed
```

After updating to the 1.1.0.beta.1 version of CocoaPods, I ran these commands (a few times):

`pod lib lint`
`pod spec lint`

Now, the origin of my repo has been changed from my real origin, to the `CocoaPods/Specs` repo: `https://github.com/CocoaPods/Specs.git`

How is it possible that CocoaPods altered the configuration of my repo? Seems to be a major bug.

My `.git/config` file now has this in it:

```
[remote "origin"]
	url = https://github.com/CocoaPods/Specs.git
	fetch = +refs/heads/*:refs/remotes/origin/*
	gtPushAllTags = true
	gtPrivateKeyPath = <My Private Key!>
	sslVerify = true
```

## What did you expect to happen?

I expected it to update the CocoaPods system with my updated `.podspec`, definitely didn't expect it to change the origin of my git repo.

## What happened instead?

CocoaPods changed the origin of my repo to the CocoaPods/Specs repo. My git GUI (Tower) is now telling me I'm 123586 commits behind. It's merged what it has as my repo, with yours.

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a70f33f178ca993cef643062d51ee8f67bf56d02
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Additional Info
If needed, I can send you the full output of the `--verbose` run above, or other info as needed.

**Comment by neonichu** [comment] 2016-08-21 14:53
This sounds very much like #5661 — is it possible that you did have Xcode 8 selected as active Xcode when this happened?

**Comment by DaveWoodCom** [comment] 2016-08-21 16:35
Yes I did. Xcode 8, Beta 6.

**Comment by neonichu** [comment] 2016-08-21 17:22
Thanks, closing this as a duplicate of #5661

**Closed by neonichu** 2016-08-21 17:22 UTC
Labels: s1:awaiting input

**Comment by charliecliff** [comment] 2016-10-05 15:50
I'm also still seeing this error on:

`1.1.0.rc.2`

Although, this was said to duplicate [#5661](https://github.com/CocoaPods/CocoaPods/issues/5661), which was closed and marked as addressed in `1.1.0.rc.1` ?

**Comment by dulgan** [comment] 2016-12-13 15:49
Same problem here, using 1.1.1 and Xcode 8.1, I made a pod install and my project origin repo is now pointing as follow :

* remote origin
  Fetch URL: https://github.com/CocoaPods/Specs.git
  Push  URL: https://github.com/CocoaPods/Specs.git
  HEAD branch: master
  Remote branches:
    master                      new (next fetch will store in remotes/origin)
    predates_sharding_branch    new (next fetch will store in remotes/origin)
    refs/remotes/origin/Android stale (use 'git remote prune' to remove)
    refs/remotes/origin/iOS     stale (use 'git remote prune' to remove)

Where iOS is my current branch and Android is another one, my own server just totally disapeared.

**Comment by benasher44** [comment] 2016-12-13 18:19
Hi @dulgan! Would you mind filing a new issue and filling out the issue template? Thanks!
