### ISSUE TITLE
pod spec lint gives error of validation relates to AFNetworking

### ISSUE THREAD

**Issue by jagdish24** [CocoaPods/CocoaPods#6567] opened 2017-03-17 06:30 UTC
I have create one xcode project and used AFNetworking in pod.

`pod 'AFNetworking', '~> 2.0'`

Now i wants to use this code in another xcode project as a cocoapod. So i created its pod spec with source of http (not git). 
Here is the syntax how i have used in Podspec file.

`s.dependency 'AFNetworking'`

Now i m going to lint code and push on source which is http with below command and got errors.

Command

`pod spec lint`

Errors in terminal

 ```
-> XXXXPodNameXXX
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - WARN  | xcodebuild:  libsodium/src/libsodium/sodium/core.c:31:3: warning: *** The library is being compiled using an undocumented method. [-W#warnings]
    - WARN  | xcodebuild:  libsodium/src/libsodium/sodium/core.c:32:3: warning: This is not supported. It has not been tested, it might not [-W#warnings]
    - WARN  | xcodebuild:  libsodium/src/libsodium/sodium/core.c:33:3: warning: work as expected, and performance is likely to be suboptimal. [-W#warnings]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/pbkdf2-sha256.c:56:15: warning: comparison of constant 137438953440 with expression of type 'size_t' (aka 'unsigned long') is always false [-Wtautological-constant-out-of-range-compare]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_pwhash/scryptsalsa208sha256/nosse/pwhash_scryptsalsa208sha256_nosse.c:305:30: warning: implicit conversion loses integer precision: 'unsigned long long' to 'size_t' (aka 'unsigned long') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/randombytes/salsa20/randombytes_salsa20_random.c:441:17: warning: comparison of constant 18446744073709551615 with expression of type 'const size_t' (aka 'const unsigned long') is always true [-Wtautological-constant-out-of-range-compare]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/randombytes/sysrandom/randombytes_sysrandom.c:310:17: warning: comparison of constant 18446744073709551615 with expression of type 'const size_t' (aka 'const unsigned long') is always true [-Wtautological-constant-out-of-range-compare]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:142:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:143:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:144:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:145:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:146:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:147:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:148:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:149:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:150:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | xcodebuild:  libsodium/src/libsodium/crypto_scalarmult/curve25519/ref10/x25519_ref10.c:151:10: warning: implicit conversion loses integer precision: 'int64_t' (aka 'long long') to 'int32_t' (aka 'int') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_pwhash/argon2/argon2-encoding.c:313:5: warning: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_pwhash/argon2/argon2-encoding.c:315:5: warning: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_pwhash/argon2/argon2-encoding.c:317:5: warning: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h:181:30: warning: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h:182:30: warning: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h:183:30: warning: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    - WARN  | [iOS] xcodebuild:  libsodium/src/libsodium/crypto_onetimeauth/poly1305/donna/poly1305_donna32.h:184:30: warning: implicit conversion loses integer precision: 'unsigned long' to 'uint32_t' (aka 'unsigned int') [-Wshorten-64-to-32]
    - ERROR | [iOS] xcodebuild:  XXXX/XXXX/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:48:12: error: definition of 'AFNetworkActivityIndicatorManager' must be imported from module 'AFNetworking.AFNetworkActivityIndicatorManager' before it is required
    - NOTE  | [iOS] xcodebuild:  AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.h:45:12: note: previous definition is here
    - ERROR | [iOS] xcodebuild:  XXXX/XXXX/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:51:1: error: illegal redeclaration of property in class extension 'AFNetworkActivityIndicatorManager' (attribute must be 'readwrite', while its primary must be 'readonly')
    - NOTE  | [iOS] xcodebuild:  AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.h:57:88: note: property declared here
    - WARN  | [iOS] xcodebuild:  XXXX/XXXX/Pods/AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.m:57:17: warning: method definition for 'setNetworkingActivityActionWithBlock:' not found [-Wincomplete-implementation]
    - NOTE  | [iOS] xcodebuild:  AFNetworking/UIKit+AFNetworking/AFNetworkActivityIndicatorManager.h:97:1: note: method 'setNetworkingActivityActionWithBlock:' declared here

Analyzed 1 podspec.

[!] The spec did not pass validation, due to 3 errors and 25 warnings.
[!] The validator for Swift projects uses Swift 3.0 by default, if you are using a different version of swift you can use a `.swift-version` file to set the version for your Pod. For example to use Swift 2.3, run: 
    `echo "2.3" > .swift-version`.

```

How to solve above ?

**Comment by benasher44** [comment] 2017-03-17 15:50
Hi there! Thanks for the report! Can you please provide the full podspec or a sample project so that we can try to reproduce this? Thanks!

**Comment by jagdish24** [comment] 2017-03-20 10:08
Here is podsepc file.

```
Pod::Spec.new do |s|

  s.name         = "XXXXX"
  s.version      = "X.X"
  s.summary      = "An iOS library to interact with the XXXX."
  s.homepage     = "http://XXXX.com/"


  s.license     = { :type => 'MIT', :text => <<-LICENSE
                   Copyright 2012
                   Permission is granted to...
                 LICENSE
               }


  s.author             = { "ABC" => "abc@abc.com" }


  s.platform     = :ios, '7.0'



  s.source       = { :http => 'http://XXXX.com/samplesource/XXXX.zip' }

  s.source_files  = '*.h', 'XXXX', 'XXXX/**/*.{h,m}'
  s.frameworks = 'Foundation', 'CoreBluetooth' 


  s.requires_arc = true

  s.xcconfig = { 'GCC_PREPROCESSOR_DEFINITIONS' => 'XXXXLIB_VERSION="\"' + s.version.to_s + '\""'}
  s.dependency 'UICKeyChainStore'
  s.dependency 'AFNetworking'
  s.dependency 'Tweaks'
  s.dependency 'libsodium'
  s.dependency 'CocoaLumberjack'
  s.dependency 'MTDates'
  s.dependency 'INTULocationManager'
end
```

**Comment by benasher44** [comment] 2017-03-26 00:34
Hm I'm not totally sure just by looking at this sorry. You might try removing your `s.xcconfig` line in favor of something like this:

```
s.prefix_header_contents = "#define XXXXLIB_VERSION #{s.version.to_s}"
```

That said, this seems like more of a build issue related to your project rather than a CocoaPods issue. For that reason, I'm going to close this, since we try to keep issues here scoped to things we could fix by patching CocoaPods, and that doesn't seem to be the case here. Best of luck, and have a great day!

**Comment by benasher44** [comment] 2017-03-26 00:35
I'd definitely recommend posting on stackoverflow.com though, since that seems like a better forum for this kind of question.

**Closed by benasher44** 2017-03-26 00:34 UTC
Labels: s1:awaiting input
