### ISSUE TITLE
Per-configuration pods don't work with __has_include()

### ISSUE THREAD

**Issue by lysannschlegel** [CocoaPods/CocoaPods#2774] opened 2014-11-03 12:27 UTC
:rainbow: I've added a 'configurations' requirement to one of my pods that I want for Debug builds only.
The issue is that this will only prevent linking the pod with other configurations, it will not hide the header files. Thus the recommended way of detecting if a pod is available, __has_include(), cannot work. It results in a linker error for all configurations without the pod.

### Example

```ruby
pod 'DCIntrospect-ARC', :configurations => ['Debug']
```

```objc
#if __has_include(<DCIntrospect-ARC/DCIntrospect.h>)
#import <DCIntrospect-ARC/DCIntrospect.h>
#endif

@implementation AppDelegate
- (BOOL)application:(UIApplication *)application didFinishLaunchingWithOptions:(NSDictionary *)launchOptions
{
    #if __has_include(<DCIntrospect-ARC/DCIntrospect.h>)
        [[DCIntrospect sharedIntrospector] start];
        NSLog(@"DCIntrospect enabled");
    #endif    
    return YES;
}
@end
```

This builds fine with the Debug configuration, and prints the string to the console, but it reports a linker error for all other configurations (such as Release):
```
Undefined symbols for architecture x86_64:
  "_OBJC_CLASS_$_DCIntrospect", referenced from:
      objc-class-ref in AppDelegate.o
```

I expect both configurations to work, and I expect the Release configuration to not make the DCIntrospect headers available.

**Comment by kylef** [comment] 2015-03-30 19:15
Closing this issue as a duplicate of #1249.

**Closed by kylef** 2015-03-30 19:15 UTC
Labels: t3:discussion
