### ISSUE TITLE
[Xcode 8 beta 3][Swift 3]pod spec lint fails - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code

### ISSUE THREAD

**Issue by bay2** [CocoaPods/CocoaPods#5663] opened 2016-07-23 15:29 UTC
# Report
Validation fails for pod spec.

# What did you do?
`pod lib lint --no-clean --verbose`

# What happened instead?

```
    - WARN  | description: The description is shorter than the summary.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | [iOS] xcodebuild:  xcodebuild: error: 'App.xcworkspace' does not exist.

Pods workspace available at `/var/folders/cw/88q2vyf967xfpjjrscjp_91m0000gn/T/CocoaPods/Lint/App.xcworkspace` for inspection.

[!] DZNEmptyDataSwift did not pass validation, due to 1 error and 1 warning.

/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command/lib/lint.rb:75:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command/lib/lint.rb:47:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command/lib/lint.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.beta.1/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'

```
# CocoaPods Environment

### Stack

```
   CocoaPods : 1.1.0.beta.1
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 8.0 (8S174q)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 1728d9a2c9f789b57d1a54832923232ba07f3cc7
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
slather               : 2.3.0
```

# Project that demonstrates the issue
[https://github.com/bay2/DZNEmptyDataSwift](https://github.com/bay2/DZNEmptyDataSwift)

# Podspec

```
Pod::Spec.new do |s|

 s.name         = "DZNEmptyDataSwift"
 s.version      = "0.0.1"
 s.summary      = "这是一个用于UITableView&UICollectionView空数据时，设置显示空数据提示。swift版本的DZNEmptyDataSet。"
  s.description  = "这个库只需要简单的配置，就能自动的在空数据时加载加配置的视图显示。"
  s.homepage     = "https://github.com/bay2/DZNEmptyDataSwift"
  s.license      = { :type => "MIT", :file => "LICENSE" }
  s.author             = { "sim" => "sim_cai@icloud.com" }
  s.platform     = :ios, "8.0"
  s.source       = { :git => "https://github.com/bay2/DZNEmptyDataSwift.git", :tag => "#{s.version}" }
  s.source_files  = "DZNEmptyDataSwift/*.swift"
  s.framework  = "UIKit"
  s.requires_arc = true

  end
```

**Comment by neonichu** [comment] 2016-07-26 17:54
Closing as dupe of #5661

**Closed by neonichu** 2016-07-26 17:54 UTC
