### ISSUE TITLE
ArgumentError - Malformed version number string >= 1.2.2

### ISSUE THREAD

**Issue by kevb10** [CocoaPods/CocoaPods#5231] opened 2016-05-01 19:53 UTC
* [X ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report
Error when installing or updating dependencies

## What did you do?
Run 'pod update'

## What did you expected to happen?
Update all dependencies correctly

## What happened instead?
Shows errors
ArgumentError - Malformed version number string >= 1.2.2
https://gist.github.com/kevb10/8f218b325117b1a2e6bf45da290d3edb

## Podfile

> ℹ Please paste the contents of your Podfile below.    
# Uncomment this line to define a global platform for your project
#platform :ios, '8.0'
#use_frameworks!

target 'Vice Versa' do
pod 'Parse', '~> 1.8.5'
pod 'MBProgressHUD', '~> 0.9.1'
pod 'QBImagePickerController'
pod 'ParseFacebookUtilsV4'
pod 'QMCVDevelopment', '~> 0.3.7' 
pod 'QMServicesDevelopment', '~> 0.4'
pod 'QuickBlox', '~> 2.7.2'
pod 'TWMessageBarManager', '~> 1.7.2'
pod 'SVProgressHUD'
pod 'MMPopupView'
end

target 'Vice VersaTests' do

end

```ruby
# Paste your Podfile contents HERE.
```

**Comment by orta** [comment] 2016-05-01 20:12
Looks like one of your pods has a bad version number, specifically `>= 1.2.2` which isn't a version number - you haven't put enough information into this issue to figure it out, can you please make a sample project?

**Comment by kevb10** [comment] 2016-05-01 20:19
Deleted my Podfile.lock and Pods directory. Ran pod install and is working fine but I'm sure you're correct

**Comment by segiddins** [comment] 2016-05-02 00:50
Actually, can you share your `Podfile.lock` from when the error was occurring? That seems to be where the invalid string is coming from. Thanks!

**Comment by kevb10** [comment] 2016-05-02 12:28
https://gist.github.com/kevb10/be55c76603428179b6b4ab9da919887c

**Comment by segiddins** [comment] 2016-05-03 17:38
I don't see how that lockfile is causing this issue :(
I think to investigate further we'd need a project we can run `pod install` on that reproduces the issue

**Comment by neonichu** [comment] 2016-05-15 13:57
Closing, because we never got a reproducible project.

**Closed by neonichu** 2016-05-15 13:57 UTC
Labels: s1:awaiting input
