### ISSUE TITLE
Cannot generate iOS App archive in xcode after I use cocoapods in my project

### ISSUE THREAD

**Issue by BruceConner** [CocoaPods/CocoaPods#4216] opened 2015-09-19 07:12 UTC
Today, I got mission to submit a ipa file for testing, I tried lots of times, it failed again and again. It could archive, but not export ,  finally I try to use the previous version of cocopods(0.37.2), it worked! I didn't know if it was a bug?

**Comment by neonichu** [comment] 2015-09-19 10:47
This seems like a dupe of #4119 — please add more information if it is not.

**Closed by neonichu** 2015-09-19 10:47 UTC

**Comment by BruceConner** [comment] 2015-09-21 01:16
My xcode version is 6.3.1, I remembered that I installed a cocoapods before, which version was like 0.39.., perhaps It happened because of this. Just like the pictures below:
![image](https://cloud.githubusercontent.com/assets/3842680/9983930/b6f24792-603f-11e5-8f74-d6ad34c68dc6.png)

![2](https://cloud.githubusercontent.com/assets/3842680/9983950/0cf897ea-6040-11e5-8574-0daca9463306.jpeg)

I tried to use some new projects to test if it was cased by cocoapods. It proved this. And then I back to version 0.37.2, it worked.

==================
And, I upgraded to 0.38.2 and tried to export the ipa file just now, it worked! anyway , thanks for your response.

**Comment by BruceConner** [comment] 2015-09-21 01:30
By the way, I just wanna say I like using it.^&^. You're great!
