### ISSUE TITLE
pod install and update error, after install Xcode11 and new MacOS 10.14.6

### ISSUE THREAD

**Issue by WLChopSticks** [CocoaPods/CocoaPods#9223] opened 2019-10-06 08:16 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
Run pod update to update my pods.
Create a new project, and then run pod init, pod install.

## What did you expect to happen?
Install all pod dependencies correctly.

## What happened instead?
wangleideMacBook-Pro:init wanglei$ pod install
Analyzing dependencies
Downloading dependencies
Installing AFNetworking (3.2.1)

[!] Error installing AFNetworking
[!] /usr/bin/git clone https://github.com/AFNetworking/AFNetworking.git /var/folders/sb/f51kjyz95fg1ymgf26n_b6wc0000gn/T/d20191006-699-p2rrzh --template= --single-branch --depth 1 --branch 3.2.1

Cloning into '/var/folders/sb/f51kjyz95fg1ymgf26n_b6wc0000gn/T/d20191006-699-p2rrzh'...
dyld: lazy symbol binding failed: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib

dyld: Symbol not found: _curl_global_sslset
  Referenced from: /Applications/Xcode.app/Contents/Developer/usr/libexec/git-core/git-remote-https
  Expected in: /usr/lib/libcurl.4.dylib

## CocoaPods Environment
wangleideMacBook-Pro:init wanglei$ pod env

### Stack

```
   CocoaPods : 1.8.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.6 (18G95)
       Xcode : 11.0 (11A420a)
         Git : git version 2.21.0 (Apple Git-122)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : ConfigPrivatePod - git - https://github.com/WLChopSticks/ConfigPrivatePod @ af082216efb32bbfc4f612835427f3ceb3dfd865
               moduleTest - git - https://github.com/WLChopSticks/moduleTest.git @ 5e027c4ceb9fc5a6f213ebe1d1ca2c1046239853
               PrivatePods - git - https://github.com/ModulizationDemo/PrivatePods.git @ 727fb3add4fd6d34275a185841a1607f5b74bfd7
               test - git - https://github.com/WLChopSticks/test.git @ bf04725ae3d9588daad8f937f48417926bc75304
               trunk - CDN - https://cdn.cocoapods.org/
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.4.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'init' do
  # Comment the next line if you don't want to use dynamic frameworks
  #use_frameworks!
  pod 'AFNetworking'
  # Pods for init

end
```

**Comment by dnkoutso** [comment] 2019-10-07 02:17
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9202

**Comment by dnkoutso** [comment] 2019-10-07 02:17
Seems unrelated to cocoapods as its failing to run `git`. Closing for now and I can re-open.

**Closed by dnkoutso** 2019-10-07 02:17 UTC

**Comment by WLChopSticks** [comment] 2019-10-07 02:30
Thank you for checking the issue so quickly. But there is still the same error after I tried issue 9202 you refered to. I also tried to replace my current curl with the latest version, but nothing changed...

**Comment by dnkoutso** [comment] 2019-10-07 02:38
Can you run 
```
git clone https://github.com/AFNetworking/AFNetworking.git /var/folders/sb/f51kjyz95fg1ymgf26n_b6wc0000gn/T/d20191006-699-p2rrzh --template= --single-branch --depth 1 --branch 3.2.1
```

Manually?

This is a problem with configuration of the current machine and `git` not CocoaPods. CocoaPods just invokes `git`.

**Comment by WLChopSticks** [comment] 2019-10-07 03:08
> Can you run
> 
> ```
> git clone https://github.com/AFNetworking/AFNetworking.git /var/folders/sb/f51kjyz95fg1ymgf26n_b6wc0000gn/T/d20191006-699-p2rrzh --template= --single-branch --depth 1 --branch 3.2.1
> ```
> 
> Manually?
> 
> This is a problem with configuration of the current machine and `git` not CocoaPods. CocoaPods just invokes `git`.

Running git clone will raise same error, I will check why git command breaks. Thank you.
