### ISSUE TITLE
Pod Install fails if the folder has brackets in its name

### ISSUE THREAD

**Issue by jleandroperez** [CocoaPods/CocoaPods#2940] opened 2014-12-12 21:04 UTC
#### Steps:

1. Open a Terminal, create a folder that has brackets in its name: `/Users/xxx/Documents/[Test]/`
2. Make sure to access the `[Test]` folder
3. Run `git clone https://github.com/wordpress-mobile/WordPress-iOS-Editor`
4. Run `cd /Users/xxx/Documents/[Test]/WordPress-iOS-Editor/Example`
5. Run `pod install`

#### Results:

The following error will be printed out:

```
[!] Could not automatically select an Xcode project. Specify one in your Podfile like so:

    xcodeproj 'path/to/Project.xcodeproj'
```

#### Notes:

If the folder doesn't have brackets, it works perfectly. We've discovered that Cocoapod's cache doesn't work when the code is stored in a folder that has brackets (because it doesn't pick up the *Podfile.lock*).

Thanks!

**Comment by kylef** [comment] 2015-02-21 17:09
This issue is a duplicate of #2852 and it was already fixed in 0.36.0.beta.1.

**Closed by kylef** 2015-02-21 17:09 UTC
