### ISSUE TITLE
The spec did not pass validation, due to 1 error.

### ISSUE THREAD

**Issue by texyz** [CocoaPods/CocoaPods#10121] opened 2020-10-05 13:10 UTC
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ pod spec lint --verbose

## What did you expect to happen?
I expected my pod to be published
ℹ Publish pod and pass validation

## What happened instead?

ℹ Please replace these two lines with of what happened instead.  
e.g. Pod A is missing the subspec B for target C.

## CocoaPods Environment

ℹ [!] The spec did not pass validation, due to 1 error.

/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command/spec/lint.rb:95:in `run'
/Library/Ruby/Gems/2.6.0/gems/claide-1.0.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.9.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

## Project that demonstrates the issue

ℹ
<img width="554" alt="Screenshot 2020-10-05 at 02 12 53" src="https://user-images.githubusercontent.com/34765619/95083361-531bc000-0714-11eb-804b-2c7575a1f816.png">

**Comment by dnkoutso** [comment] 2020-10-05 15:39
This report is not sufficient for us to diagnose. Usually `lint` errors mean something went wrong with `xcodebuild`.

Please provide a sample app and clear instructions and logs on how to reproduce.

**Comment by texyz** [comment] 2020-10-05 15:50
So sorry about that
https://drive.google.com/file/d/1uCs1_Xm5kp9x0GdHSpogZRoLzBIZlxk0/view?usp=sharing

**Comment by texyz** [comment] 2020-10-05 19:20
- ERROR | [iOS] unknown: Encountered an unknown error (416: unexpected token at '{
      "name": "CollectionCells",
      "platforms": {
        "ios": "9.0"
      },
      "public_header_files": "components/CollectionCells/src/*.h",
      "source_files": [
        "components/CollectionCells/src/*.{h,m}",
        "components/CollectionCells/src/private/*.{h,m}"
      ],
      "resources": [
        "components/CollectionCells/src/MaterialCollectionCells.bundle"
      ],
      "frameworks": [
        "CoreGraphics",
        "QuartzCore"
      ],
      "dependencies": {
        "MDFInternationalization": [

        ],
        "MaterialComponents/CollectionLayoutAttributes": [

        ],
        "MaterialComponents/Ink": [

        ],
        "MaterialComponents/Typography": [

        ],
        "MaterialComponents/Palettes": [

        ],
        "MaterialComponents/private/Icons/ic_check": [

        ],
        "MaterialComponents/private/Icons/ic_check_circle": [

        ],
        "MaterialComponents/private/Icons/ic_chevron_right": [

        ],
        "MaterialComponents/') during validation.

[!] FlutterwaveSDK did not pass validation, due to 1 error.
You can use the `--no-clean` option to inspect any issue.

**Comment by dnkoutso** [comment] 2020-10-05 19:22
duplicate of #9672

try

rm -rf ~/.cocoapods/repos
pod cache clean --all

and then pod install.

Closing as duplicate.

**Closed by dnkoutso** 2020-10-05 19:22 UTC

**Comment by texyz** [comment] 2020-10-05 19:23
I am creating a pod library, please help out on what maybe the issue

**Comment by dnkoutso** [comment] 2020-10-05 19:24
seems same issue #9672.
