### ISSUE TITLE
Pods update binds to commit

### ISSUE THREAD

**Issue by sciutand** [CocoaPods/CocoaPods#4821] opened 2016-01-26 20:40 UTC
Since migrating to version 1.0.0.beta2 I've experiencing this behaviour where `pod update` doesn't track the branch but instead binds itself to a commit

Podfile extract:

```
...
  pod 'OneTapKit/Application',:git => 'git@github.com:receipt-bank/onetap-ios-kit.git', :branch => 'feature/schedule-tasks'
...
```

output of `pod update`
```
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OneTapKit` from `git@github.com:receipt-bank/onetap-ios-kit.git`, commit `667468e504fe1a6a0516552d15ec082d5d5aee69`
```

expected output would be:
```
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `OneTapKit` from `git@github.com:receipt-bank/onetap-ios-kit.git`, branch `feature/schedule-tasks`
```

resulting Podfile.lock (extract)
```
PODS:
 ...
  - OneTapKit/Application (0.1.4.dev):
    - OneTapKit/Core
  - OneTapKit/Core (0.1.4.dev):
    - Alamofire (~> 3.1.0)
    - Bolts/Tasks (~> 1.5)
    - RBCamera/Storage (~> 0.2.0)
    - XCGLogger (~> 3.2)
 ...

DEPENDENCIES:
 ...
  - OneTapKit/Application (from `git@github.com:receipt-bank/onetap-ios-kit.git`, branch `feature/schedule-tasks`)
  - RBCamera (from `git@github.com:receipt-bank/RBCamera.git`, branch `master`)
  ...

EXTERNAL SOURCES:
  OneTapKit:
    :branch: feature/schedule-tasks
    :git: git@github.com:receipt-bank/onetap-ios-kit.git
 ...

CHECKOUT OPTIONS:
  OneTapKit:
    :commit: 667468e504fe1a6a0516552d15ec082d5d5aee69
    :git: git@github.com:receipt-bank/onetap-ios-kit.git
 ...

SPEC CHECKSUMS:
  ...
  OneTapKit: 86eb5285e5f2852d311abaff90e430fe2157dc16
  ...

PODFILE CHECKSUM: 19995f659101d08bf1051a1e30d95133e439fef6

COCOAPODS: 1.0.0.beta.2
```

I've tried changing the podspec version but it still won't cause pod update the fetch the head of the branch. Only way to make pod update work as expected after the initial install/update (short of wiping Podifle.lock and Manifest.lock) is to remove the pod entries from `CHECKOUT OPTIONS`.

**Comment by segiddins** [comment] 2016-01-26 21:24
I cannot reproduce this. Can you share a project where running `pod update` reliably reproduces the issue? Thanks!

**Comment by sciutand** [comment] 2016-01-26 22:40
I will should have done that in the first place..sorry

**Comment by sciutand** [comment] 2016-01-26 23:25
Here something similiar to my set up:

Pod repository
```
https://github.com/sciutand/cp4821-sample-pod.git
```

Project repository with dependency to above pod (master => branch)

```
https://github.com/sciutand/cp4821-sample-project.git
```

Below output of pod install followed by two pod updates interleaved by new commits to the master branch of https://github.com/sciutand/cp4821-sample-pod.git

The cp4821 pod is binding to commit `86c02492ab3dc26faf9d02dac80db242f0d327a9` instead of tracking the master branch

```

// RUN FIRST INSTALL
Andreas-MacBook-Air:cp4821-sample-project andrea$ pod install
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `cp4821` from `git@github.com:sciutand/cp4821-sample-pod.git`, branch `master`
Downloading dependencies
Installing XCGLogger (3.2)
Installing cp4821 (0.1.dev)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `cp4821-application.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.
Andreas-MacBook-Air:cp4821-sample-project andrea$ open cp4821-application.xcworkspace

//AFTER CHANGES TO THE POD REPOSITORY TRY TO UPDATE POD
Andreas-MacBook-Air:cp4821-sample-project andrea$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `cp4821` from `git@github.com:sciutand/cp4821-sample-pod.git`, commit `86c02492ab3dc26faf9d02dac80db242f0d327a9`
Downloading dependencies
Using XCGLogger (3.2)
Installing cp4821 0.1.dev (was 0.1.dev)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.

//SOME MORE CHANGES TRY TO UPDATE POD
Andreas-MacBook-Air:cp4821-sample-project andrea$ pod update
Update all pods
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `cp4821` from `git@github.com:sciutand/cp4821-sample-pod.git`, commit `86c02492ab3dc26faf9d02dac80db242f0d327a9`
Downloading dependencies
Using XCGLogger (3.2)
Installing cp4821 0.1.dev (was 0.1.dev)
Generating Pods project
Integrating client project
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 2 total pods installed.


//CHECK STAUS OF POD REPOSITORY
cd ../cp4821-sample-pod
Andreas-MacBook-Air:cp4821-sample-pod andrea$ git reflog
54f2a1e HEAD@{0}: commit: Change pod spec to see if it makes any difference
807a0da HEAD@{1}: commit: Change version to test pod update
86c0249 HEAD@{2}: commit (initial): Add sample pod
```

**Comment by segiddins** [comment] 2016-01-26 23:41
Thanks! I have a fix for this in the works

**Closed** 2016-01-29 02:53 UTC
Labels: s4:awaiting validation, t2:defect
