### ISSUE TITLE
cannot load such file -- cocoapods/command/repo/add (LoadError)

### ISSUE THREAD

**Issue by siuying** [CocoaPods/CocoaPods#4090] opened 2015-08-27 04:10 UTC
Using rvm with 2.2.2p95, after upgrade to 0.39.0.beta.2 pod install will fail:

```
$ bundle
Fetching gem metadata from https://rubygems.org/...........
Fetching version metadata from https://rubygems.org/...
Fetching dependency metadata from https://rubygems.org/..
Resolving dependencies...
...
Installing cocoapods-core 0.39.0.beta.2 (was 0.39.0.beta.1)
Using cocoapods-downloader 0.9.2
Using cocoapods-plugins 0.4.2
Using cocoapods-stats 0.6.0
Using netrc 0.7.8
Using cocoapods-trunk 0.6.2
Using cocoapods-try 0.5.0
Using colored 1.2
Using escape 0.0.4
Using molinillo 0.3.1
Using xcodeproj 0.27.0
Installing cocoapods 0.39.0.beta.2 (was 0.39.0.beta.1)
Using bundler 1.10.3
Bundle complete! 1 Gemfile dependency, 22 gems now installed.
Use `bundle show [gemname]` to see where a bundled gem is installed.
$ pod install
/Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command/repo.rb:2:in `require': cannot load such file -- cocoapods/command/repo/add (LoadError)
	from /Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command/repo.rb:2:in `<top (required)>'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:22:in `require'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:22:in `<class:Command>'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:16:in `<module:Pod>'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:11:in `<top (required)>'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/bin/pod:44:in `<top (required)>'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/bin/pod:23:in `load'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/bin/pod:23:in `<main>'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `eval'
	from /Users/siuying/.rvm/gems/ruby-2.2.2/bin/ruby_executable_hooks:15:in `<main>'
```

**Comment by segiddins** [comment] 2015-08-27 04:21
:(

In the meantime, try `chmod -R ugo+r /Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/`

**Comment by siuying** [comment] 2015-08-27 04:27
Nope, it try to include "cocoapods/command/repo/add" but there are none:

```
ls -1 /Users/siuying/.rvm/gems/ruby-2.2.2/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command/
cache.rb
init.rb
inter_process_communication.rb
lib.rb
list.rb
outdated.rb
project.rb
repo.rb
search.rb
setup.rb
spec.rb
```

**Comment by mobiletoly** [comment] 2015-08-27 05:09
Same here.
Uninstalled 0.39.0.beta.2 and installed 0.39.0.beta.1, it works:

$ gem install cocoapods -v 0.39.0.beta.1

**Comment by flufff42** [comment] 2015-08-27 05:49
I presume you've already identified the root cause, but a quick glance at the [rubygems page](https://rubygems.org/gems/cocoapods/) shows the gem seems to have shrunk since `0.39.0.beta.1`

```
gem compare cocoapods 0.39.0.beta.1 0.39.0.beta.2
Fetching: cocoapods-0.39.0.beta.1.gem (100%)
Fetching: cocoapods-0.39.0.beta.2.gem (100%)
Compared versions: ["0.39.0.beta.1", "0.39.0.beta.2"]
  DIFFERENT version:
    0.39.0.beta.1: 0.39.0.beta.1
    0.39.0.beta.2: 0.39.0.beta.2
  DIFFERENT files:
    0.39.0.beta.1->0.39.0.beta.2:
      * Deleted:
            lib/cocoapods/command/cache/clean.rb
            lib/cocoapods/command/cache/list.rb
            lib/cocoapods/command/repo/add.rb
            lib/cocoapods/command/repo/lint.rb
            lib/cocoapods/command/repo/list.rb
            lib/cocoapods/command/repo/push.rb
            lib/cocoapods/command/repo/remove.rb
            lib/cocoapods/command/repo/update.rb
            lib/cocoapods/command/spec/cat.rb
            lib/cocoapods/command/spec/create.rb
            lib/cocoapods/command/spec/edit.rb
            lib/cocoapods/command/spec/lint.rb
            lib/cocoapods/command/spec/which.rb
            lib/cocoapods/generator/acknowledgements/markdown.rb
            lib/cocoapods/generator/acknowledgements/plist.rb
            lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb
            lib/cocoapods/generator/xcconfig/pod_xcconfig.rb
            lib/cocoapods/generator/xcconfig/xcconfig_helper.rb
            lib/cocoapods/installer/analyzer/analysis_result.rb
            lib/cocoapods/installer/analyzer/locking_dependency_analyzer.rb
            lib/cocoapods/installer/analyzer/sandbox_analyzer.rb
            lib/cocoapods/installer/analyzer/specs_state.rb
            lib/cocoapods/installer/analyzer/target_inspection_result.rb
            lib/cocoapods/installer/analyzer/target_inspector.rb
            lib/cocoapods/installer/target_installer/aggregate_target_installer.rb
            lib/cocoapods/installer/target_installer/pod_target_installer.rb
            lib/cocoapods/installer/user_project_integrator/target_integrator.rb
            lib/cocoapods/installer/user_project_integrator/target_integrator/xcconfig_integrator.rb
      * Changed:
            CHANGELOG.md +9/-0
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/command.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/command/lib.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/command/spec.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/downloader.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/downloader/request.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/executable.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/gem_version.rb +1/-1
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/generator/acknowledgements.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/generator/embed_frameworks_script.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/hooks_manager.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/installer.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/installer/analyzer.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/installer/file_references_installer.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/installer/pod_source_installer.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/resolver.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/sandbox/file_accessor.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/sandbox/headers_store.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/sandbox/path_list.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/sources_manager.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/target/pod_target.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/user_interface.rb 
              (!) New permissions: 100600 -> 100644
            lib/cocoapods/validator.rb 
              (!) New permissions: 100600 -> 100644
  DIFFERENT runtime dependencies:
    0.39.0.beta.1->0.39.0.beta.2:
      * Updated:
            cocoapods-core from: ["= 0.39.0.beta.1"] to: ["= 0.39.0.beta.2"]
```

**Comment by segiddins** [comment] 2015-08-27 06:01
I honestly have no idea how/why this is happening :sob:

**Comment by siuying** [comment] 2015-08-27 06:06
Those files exists on your machine when you release the gem?

**Comment by segiddins** [comment] 2015-08-27 06:08
Yes! They're all here, and I swear I updated all the permissions before I released beta 2

**Comment by siuying** [comment] 2015-08-27 06:12
I tried and the repo look perfectly fine. Maybe you can release again?

![](http://media.giphy.com/media/F7yLXA5fJ5sLC/giphy.gif)

**Comment by segiddins** [comment] 2015-08-27 06:14
The team will talk things over tomorrow, in the meantime I recommend either running 0.38.2 or via a clone of the repo

**Comment by siuying** [comment] 2015-08-27 06:34
:+1:

**Comment by flippinjoe21** [comment] 2015-08-27 15:10
@segiddins Note that cloning the repo has it's own issues. 

```
LoadError - cannot load such file -- xcodeproj/project/object
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/Library/Ruby/Gems/2.0.0/gems/xcodeproj-0.27.0/lib/xcodeproj/project.rb:4:in `<top (required)>'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer/analyzer/target_inspector.rb:32:in `compute_results'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer/analyzer.rb:657:in `block (2 levels) in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer/analyzer.rb:655:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer/analyzer.rb:655:in `block in inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer/analyzer.rb:654:in `inspect_targets_to_integrate'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer/analyzer.rb:61:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer.rb:213:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/user_interface.rb:59:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/installer.rb:105:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
```

**Comment by segiddins** [comment] 2015-08-27 15:14
Looks like Xcodeproj was affected as well :sob:

**Comment by j796160836** [comment] 2015-08-27 15:51
I got this error message when do the `pod install`  
```
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- cocoapods/command/repo/add (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command/repo.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:22:in `<class:Command>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:16:in `<module:Pod>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:11:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/bin/pod:44:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
```

**Comment by j796160836** [comment] 2015-08-27 15:54
Oh no...I rollback to cocoapods-0.38.2 via `sudo gem install cocoapods` command
and no works. :(

```
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require': cannot load such file -- cocoapods/command/repo/add (LoadError)
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command/repo.rb:2:in `<top (required)>'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:73:in `require'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:22:in `<class:Command>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:16:in `<module:Pod>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/lib/cocoapods/command.rb:11:in `<top (required)>'
	from /Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0.beta.2/bin/pod:44:in `<top (required)>'
	from /usr/bin/pod:23:in `load'
	from /usr/bin/pod:23:in `<main>'
```

**Comment by flippinjoe21** [comment] 2015-08-27 15:57
@j796160836 you have to 
`sudo gem uninstall cocoapods-core -v 0.39.0.beta.2`
`sudo gem uninstall cocoapods -v 0.39.0.beta.2`

**Comment by j796160836** [comment] 2015-08-27 16:22
Thanks @flippinjoe21, but I have another problem. When I use `pod install`
It show me these message.
```
---------------------------------------------
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.0/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- /Library/Ruby/Gems/2.0.0/gems/cocoapods-stats-0.6.0/lib/cocoapods_plugin.rb
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Library/Ruby/Site/2.0.0/rubygems/core_ext/kernel_require.rb:126:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.38.2/bin/pod:44:in `<top (required)>'
/usr/bin/pod:23:in `load'
/usr/bin/pod:23:in `<main>'
---------------------------------------------

[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-try-release-fix-0.1.2`
```

It looks like a warning.

----

I open my `.xcworkspace` file, it show me these this message
```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
I searched the internet and found these answers  
http://stackoverflow.com/questions/17072396/cocoapods-errors-on-project-build

I had try  
1. Clean the build folder
2. Check the PODS_ROOT variable in build settings.


please help

**Comment by segiddins** [comment] 2015-08-27 16:23
looks like stats also needs a release, @kylef

**Comment by j796160836** [comment] 2015-08-27 16:24
Finally, I change the delete the build script at Build Phases it goes fine.

**Comment by flippinjoe21** [comment] 2015-08-27 16:27
@j796160836 I don't think that's exactly what you want to do.   The *real* fix here would be to 
`sudo gem uninstall cocoapods xcodeproj && sudo gem install cocoapods`

Correct me if I'm wrong @segiddins but the xcodeproj issue is strictly permissions?  Which should be fixed by a uninstall reinstall?

**Comment by j796160836** [comment] 2015-08-27 16:33
OK, I tell you the very first question that I met.  
When I build the iOS code (All of Obj-C, WatchKit and dynamic library included) in xcode, 
I saw these error.
```
diff: /../Podfile.lock: No such file or directory
diff: /Manifest.lock: No such file or directory
error: The sandbox is not in sync with the Podfile.lock. Run 'pod install' or update your CocoaPods installation.
```
So I try upgrade to beta version and try to solve the very question that I met.

**Comment by j796160836** [comment] 2015-08-27 16:40
I had tried `sudo gem uninstall cocoapods xcodeproj && sudo gem install cocoapods`  
I had removed all the version and install again
```
 1. xcodeproj-0.14.1
 2. xcodeproj-0.16.1
 3. xcodeproj-0.17.0
 4. xcodeproj-0.18.0
 5. xcodeproj-0.19.2
 6. xcodeproj-0.26.3
 7. xcodeproj-0.27.0
```

```
 1. cocoapods-0.29.0
 2. cocoapods-0.32.1
 3. cocoapods-0.33.1
 4. cocoapods-0.34.1
 5. cocoapods-0.38.2
```
I got the same result (lots of warning but it's works)

**Comment by segiddins** [comment] 2015-08-27 16:46
It's an issue with the released gem, @kylef said he'd release fixed versions

**Comment by segiddins** [comment] 2015-08-28 06:02
Please try again with Beta 3. We've taken steps to ensure this won't happen again.

**Comment by siuying** [comment] 2015-08-28 07:15
Work as expected, thanks!

**Comment by segiddins** [comment] 2015-08-28 07:16
Thanks for bearing with us!

**Closed** 2015-08-28 07:16 UTC
Labels: s4:awaiting validation

**Comment by coolnameismy** [comment] 2016-03-31 02:21
i get into same trouble , and i delete folder cocoapods-stats-x.x.x form library/Ruby/Gems/2.0.0/gems
then this trouble gone ~
