### ISSUE TITLE
Cocoapods 1.5.0 not able to Generate Active Archive 

### ISSUE THREAD

**Issue by KiranMantana** [CocoaPods/CocoaPods#7648] opened 2018-04-17 06:57 UTC
Yesterday Updated to Cocoapods 1.5.0, 

Using Objective C , Xcode Version 9.2 (9C40b). 

Trying to Archive the Build, But in the Organiser, the App Comes under "Other Items" and "Validate", "Download Dysms" are disabled, Only having "Export Option". Attaching the screenshot from Apple website and i am getting the Archive Screen in the same way, In lower versions, it is working fine. 

Below apple Link 

https://developer.apple.com/library/content/technotes/tn2215/_index.html#//apple_ref/doc/uid/DTS40011221-CH1-PROJ

![appledoc](https://user-images.githubusercontent.com/7392665/38853344-95dca36a-423a-11e8-9349-f68ef8ece4ea.png)

Please let me know if any info needed.

**Comment by MaximeLM** [comment] 2018-04-17 12:56
Duplicate of #7590

**Comment by artrmz** [comment] 2018-04-17 13:28
@MaximeLM Tried master version and still the same, although I am trying to export archive via command line and getting this error:

```
error: exportArchive: exportOptionsPlist error for key 'method': expected one of {}, but found development

Error Domain=IDEFoundationErrorDomain Code=1 "exportOptionsPlist error for key 'method': expected one of {}, but found development" UserInfo={NSLocalizedDescription=exportOptionsPlist error for key 'method': expected one of {}, but found development}
```

I know it's caused by one of pods (Which sadly I can not share. Also this one pod has it's own xcassets. It also depends on frameworks, vendored_frameworks and some other pods). It might be an pod's issue though... did not have time to debug it yet.

**Comment by dnkoutso** [comment] 2018-04-17 14:46
@artrmz can you upload a sample app?

**Comment by artrmz** [comment] 2018-04-17 15:18
@dnkoutso Cannot share the pod but will try to create sample app/pod that recreates the issue tomorrow.

**Comment by dnkoutso** [comment] 2018-04-18 07:36
@artrmz you have uncovered a bug in 1.6.0 (master) I will need to fix. thanks! I know its irrelevant to this PR.

**Comment by artrmz** [comment] 2018-04-18 09:01
@dnkoutso I think I managed to find out what is causing the issue (at least in my environment). Uploading example project:

[VccExample.zip](https://github.com/CocoaPods/CocoaPods/files/1923169/VccExample.zip)

Will have to set signing/provisionnings for development first then:
```
bundle install
bundle exec pod install
bundle exec fastlane EXAMPLE_TEST
```

From what I managed to debug seems like archive export fail when Pod contains `xcassets` file but has no `.m` source files. This example is quite "stupid" but in a real project such Pod has no .m files because it only contains its own assets, static libraries, vendored frameworks and some other pod dependencies.

**Comment by artrmz** [comment] 2018-04-19 05:03
@dnkoutso Just tried the newest master and both my issues are gone, thanks!

**Comment by dnkoutso** [comment] 2018-04-19 06:08
awesome!

**Closed by dnkoutso** 2018-04-19 06:08 UTC

**Comment by KiranMantana** [comment] 2018-05-16 07:47
When can we expect the 1.6.0 release?
