### ISSUE TITLE
Cannot push two spec with the same minimum iOS version

### ISSUE THREAD

**Issue by serejahh** [CocoaPods/CocoaPods#5978] opened 2016-09-30 09:42 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I'm trying to update a podspec for a [lib](https://github.com/Yalantis/PullToMakeFlight/blob/swift3/PullToMakeFlight.podspec) which is based on [another one](https://github.com/Yalantis/PullToRefresh/blob/develop/PullToRefresher.podspec).

## What did you expect to happen?

`PullToMakeFlight.podspec passed validation.`

## What happened instead?

I got an error during linting the spec: 

```
 -> PullToMakeFlight (2.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Unable to satisfy the following requirements:

- `PullToRefresher (~> 2.0)` required by `PullToMakeFlight (2.0)`

Specs satisfying the `PullToRefresher (~> 2.0)` dependency were found, but they required a higher minimum deployment target.) during validation.

Analyzed 1 podspec.
```

Base pull to refresh has minimum iOS 8 and custom pull to refresh also has iOS 8. 

⚠️  When I set iOS 9 for `PullToMakeFlight` everything works fine

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.10.0
Ruby lib dir : /Users/serhii/.rvm/rubies/ruby-2.3.0/lib
Repositories : anodamobi - https://github.com/anodamobi/ANODA-CocoaPods.git @ efe834d1d1d590a6978919b86d6242b9e6922651
               artsy - https://github.com/artsy/Specs.git @ 9c305e16a057d3062373aaaa1d8584bbd764fa55
               master - https://github.com/CocoaPods/Specs.git @ 81c504da50ecf52872c19c964e93b04b6bed407c
```

### Installation Source

```
Executable Path: /Users/serhii/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
claide-plugins         : 0.9.0
cocoapods-deintegrate  : 1.0.1
cocoapods-dependencies : 1.0.0.beta.1
cocoapods-plugins      : 1.0.0
cocoapods-search       : 1.0.0
cocoapods-stats        : 1.0.0
cocoapods-trunk        : 1.0.0
cocoapods-try          : 1.1.0
cocoapods_debug        : 0.1.0
```

### Podfile

```ruby
platform :ios, '9.0'
use_frameworks!

target 'PullToMakeFlightDemo' do

	pod "PullToMakeFlight", :path => "./"

end
```

## Project that demonstrates the issue

You can check [this repo](https://github.com/Yalantis/PullToMakeFlight/tree/swift3) (`swift` branch) out and run `pod spec lint`

**Comment by b-ray** [comment] 2016-10-01 15:28
Although the minimum deployment target of `PullToRefresher` seems to be `8.0` in the respective GitHub repo [here](https://github.com/Yalantis/PullToRefresh/blob/develop/PullToRefresher.podspec), the deployment target in the [version that got released to the CocoaPods Specs repo](https://github.com/CocoaPods/Specs/blob/master/Specs/PullToRefresher/2.0/PullToRefresher.podspec.json) appears to be `9.0`.
I suspect this is what causes you troubles?

**Comment by serejahh** [comment] 2016-10-01 18:39
@b-ray Thanks for the hint. Could it be related to swift 3?

**Comment by benasher44** [comment] 2016-10-02 22:55
@serejahh the issue is as @b-ray mentioned: The [podspec for `PullToRefresher`](https://github.com/CocoaPods/Specs/blob/master/Specs/PullToRefresher/2.0/PullToRefresher.podspec.json) states that the deployment target is iOS 9, so a podspec that depends on `PullToRefresher` won't validate for iOS 8.

One other thing I noticed about your podspec is that you shouldn't use both `s.platform` and `s.ios.deployment_target`. One will just override the other, since `s.ios.deployment_target` implies `s.platform` with iOS as the platform.

I'm going to close this, since it's not an issue with CocoaPods. Thanks!

**Closed by benasher44** 2016-10-02 22:55 UTC

**Comment by serejahh** [comment] 2016-10-03 12:56
@b-ray That was the problem. Now everything works. Thanks!
