### ISSUE TITLE
Help! ActiveSupport 7.1.1 doesn’t work

### ISSUE THREAD

**Issue by konguele** [CocoaPods/CocoaPods#12098] opened 2023-10-17 02:57 UTC
Good Morning,

 I found an Issue when I tried to build my game with Cordova and Cocoapods. Ruby was on version 2.6.0 and Cocoapods was installed on version 1.8.4, I installed cocoapods version 1.13.0 via homebrew, but it didn’t work properly.

I uninstalled everything. I upgraded Ruby to 3.2.2, I was able to install cocoapods normal, without using homebrew on version 1.13.0 and now I get this error:

Failed to install 'admob-plus-cordova': Error: Command failed with exit code 1: pod --version
/usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:108:in <class:Array>': undefined method deprecator' for ActiveSupport:Module (NoMethodError)

deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator
^^^^^^^^^^^
Did you mean? deprecate_constant
from /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:8:in <top (required)>' from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in require'
from internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb:86:in require' from /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.13.0/lib/cocoapods.rb:9:in <top (required)>'
from internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb:86:in require' from <internal:/usr/local/lib/ruby/site_ruby/3.2.0/rubygems/core_ext/kernel_require.rb>:86:in require'
from /usr/local/lib/ruby/gems/3.2.0/gems/cocoapods-1.13.0/bin/pod:36:in <top (required)>' from /usr/local/bin/pod:25:in load'
from /usr/local/bin/pod:25:in <main>' at makeError (/Users/juanjosegarciamanzano/Downloads/Jabali/node_modules/execa/lib/error.js:60:11) at handlePromise (/Users/juanjosegarciamanzano/Downloads/Jabali/node_modules/execa/index.js:118:26) at process.processTicksAndRejections (node:internal/process/task_queues:95:5) Failed to restore plugin "admob-plus-cordova". You might need to try adding it again. Error: Error: Command failed with exit code 1: pod --version /usr/local/lib/ruby/gems/3.2.0/gems/activesupport-7.1.1/lib/active_support/core_ext/array/conversions.rb:108:in class:Array': undefined method `deprecator' for ActiveSupport:Module (NoMethodError)

deprecate to_default_s: :to_s, deprecator: ActiveSupport.deprecator

**Comment by zdpdsy** [comment] 2023-10-17 10:27
@konguele

**Comment by zdpdsy** [comment] 2023-10-17 10:28
you can see this issues

https://github.com/CocoaPods/CocoaPods/issues/12081 @konguele

**Comment by paulb777** [comment] 2023-11-14 18:44
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/12081 and fixed in CocoaPods 1.14.x

**Closed by paulb777** 2023-11-14 18:44 UTC
