### ISSUE TITLE
Repo push to a private spec failed..  Xcode 8?

### ISSUE THREAD

**Issue by lianweiqin** [CocoaPods/CocoaPods#5914] opened 2016-09-20 09:17 UTC
* [ ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

run 'pod repo push privateSpec xxx.podspec --allow-warnings --use-libraries --verbose'

## What did you expect to happen?

push to spec successful

### command line tools 
Setting up CocoaPods master repo
  $ /Applications/Xcode.app/Contents/Developer/usr/bin/git remote set-url origin
  https://github.com/CocoaPods/Specs.git
  fatal: No such remote 'origin'
  [!] Failed: /Applications/Xcode.app/Contents/Developer/usr/bin/git remote
  set-url origin https://github.com/CocoaPods/Specs.git
  $ /Applications/Xcode.app/Contents/Developer/usr/bin/git checkout master
  Already on 'master'

## CocoaPods Environment

1.1.0.beta.2

**Comment by neonichu** [comment] 2016-09-20 09:35
Probably a dupe of #5915 — please use the latest release candidate instead of the betas.

**Closed by neonichu** 2016-09-20 09:35 UTC
