### ISSUE TITLE
[Master] There are many quotes in Podfile.lock

### ISSUE THREAD

**Issue by Whirlwind** [CocoaPods/CocoaPods#7834] opened 2018-06-14 09:26 UTC
I have not any idea about it. Could somebody help me?

My project uses CocoaPods v1.3.1, and I upgrade the version to the master branch. The Podfile.lock have many changes:

![image](https://user-images.githubusercontent.com/1251192/41403574-ca1f8a9e-6ff7-11e8-9485-acd72e162bec.png)

![image](https://user-images.githubusercontent.com/1251192/41403601-d871230a-6ff7-11e8-8b26-7e47e6e0dd22.png)

I check the many issues and I know the psych maybe cause it. But I use `psych` v2.2.2 in my Gemfile and never update it, and `bundle exec pod install` not works.

**Comment by Whirlwind** [comment] 2018-06-14 10:41
I found the commit on CocoaPods-Core https://github.com/CocoaPods/Core/commit/0839199c6d9f901af7eefd0be9c86a9e595c1452

Should the `+` be quoted?

**Comment by dnkoutso** [comment] 2018-06-15 05:42
I think this is fine, what problem is it causing to you?

**Comment by Whirlwind** [comment] 2018-06-15 05:57
I use the CocoaPods v1.5/1.6 in my project, and others in my team use the CocoaPods v1.3.1. In some reasons, I could not upgrade the version of CocoaPods now. I just upload some changes in my Lockfile. But I found that there are too many changes about the quotes, I must check every line to commit. The diff is too much.

**Comment by dnkoutso** [comment] 2018-06-15 05:58
Sorry I do not think there is an issue here besides inconvenience. The quotes were necessary to escape a few characters present in the podfile and fix other issues.

I do not think there is a bug here so I am inclined to close this issue.

**Comment by dnkoutso** [comment] 2018-06-15 05:59
See this https://github.com/CocoaPods/CocoaPods/issues/7302

**Comment by Whirlwind** [comment] 2018-06-15 06:00
I check some documents, and I known the quote is necessary. But I could not find the `+` is necessary for quote.

**Comment by dnkoutso** [comment] 2018-06-15 06:01
You can see more here https://github.com/CocoaPods/Core/pull/438

Perhaps it is true but overall I do not see this an issue or a bug in how CocoaPods works.

**Comment by Whirlwind** [comment] 2018-06-15 06:09
Some chars must be quoted: 

> :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, `

I could not found the `+`.

**Comment by segiddins** [comment] 2018-06-15 06:19
It can probably be added to the list of characters that's valid after the first character in a scalar string, but you'd need to check the YAML spec

**Comment by Whirlwind** [comment] 2018-06-15 06:39
https://stackoverflow.com/questions/19109912/do-i-need-quotes-for-strings-in-yaml

> 
- In general, you don't need quotes.
- Use quotes to force a string, e.g. if your key or value is 10 but you want it to return a String and not a Fixnum, write '10' or "10".
- Use quotes if your value includes special characters, (e.g. :, {, }, [, ], ,, &, *, #, ?, |, -, <, >, =, !, %, @, \).
- Single quotes let you put almost any character in your string, and won't try to parse escape codes. '\n' would be returned as the string \n.
- Double quotes parse escape codes.  "\n" would be returned as a line feed character.
- The exclamation mark introduces a method, e.g. !ruby/sym to return a Ruby symbol.

First, the `+` is safe and it is unnecessary to be quoted.
Then, the single-quotes is safier then double-quotes.

> @ and ` can be used anywhere in a plain string except at the beginning, because they are reserved indicators.

It is safe if the reserved indicators are not at the begin of string. And I found the `Podfile.lock` have quote the git url.

**Comment by dnkoutso** [comment] 2018-06-16 02:54
@Whirlwind feel free to open PR to fix this in CocoaPods/Core project.

**Comment by Whirlwind** [comment] 2018-06-16 03:05
I could open a PR after you agree With me .

1. Use single quote instead of double quote
2. Only quote the string that begins with the reserved indicators

**Comment by dnkoutso** [comment] 2018-06-16 03:20
I would make a change for `+` first.

**Comment by Whirlwind** [comment] 2018-06-16 03:21
The git URL have same problem, too.

**Comment by dnkoutso** [comment] 2018-06-16 03:35
Git url is a different issue and its for circle ci we are not changing that currently

**Comment by Whirlwind** [comment] 2018-06-16 03:38
What is the `circle ci`?

**Comment by dnkoutso** [comment] 2018-06-20 07:01
@Whirlwind  https://circleci.com/

**Comment by dnkoutso** [comment] 2018-06-20 07:02
Here's why we added quotes https://github.com/CocoaPods/CocoaPods/issues/7586

**Comment by Whirlwind** [comment] 2018-06-20 07:08
It seems that Git URL which I said is not spec repo url.

I meant that the `pod 'xxx', :git=>'git@github.com/xx/xx.git'`. the url `git@github.com/xx/xx.git` will be quoted.

**Comment by Whirlwind** [comment] 2018-06-20 12:04
@dnkoutso I still don't understand the relationship between the issue #7586 and the quotes.....

**Comment by Whirlwind** [comment] 2018-10-23 15:00
@dnkoutso Hi, I want to remove the quotes in this issue. I try to modify the `yaml_helper.rb` in the Cocoapods/Core project.

```
       VALID_PLAIN_SCALAR_STRING = %r{\A
-        [\w&&[^#{INDICATOR_START_CHARS}]] # valid first character
-        [\w/\ \(\)~<>=\.:`,-]* # all characters allowed after the first one
+        [\w/ \(\)~<>=\.:`,-@\+]* # all characters allowed after the first one
       \z}ox
```

It will effect these cases:

1.   allow the `@`:
`- "ShareService/Band (from `git@myprivate.com/ShareService.git`, branch `1.1.0`)"` -> `- ShareService/Band (from `git@myprivate.com/ShareService.git`, branch `1.1.0`)`
`"git@myprivate:iOS_Library/source_repo.git":` -> `git@myprivate:iOS_Library/source_repo.git:`

2. allow the `+`:
`"UIColor+Hex": 90e101521d717e84f8e29d068fdf1ca8be6c0649` -> `UIColor+Hex: 90e101521d717e84f8e29d068fdf1ca8be6c0649`

3. allow the `.`:
```
  Search:
    :path: "../Local Pods/Search/"
```
->
```
  Search:
    :path: ../Local Pods/Search/
```

Is it right?

**Comment by segiddins** [comment] 2018-10-23 16:30
I want to keep the quotes — I’d rather the lockfile be slightly uglier than risk being invalid YAML or, even worse, YAML that means something different than what was intended

**Comment by Whirlwind** [comment] 2018-10-23 16:52
I google some documents and make a validate in some tools, these quotes should be unused . I don't think cocoapods should add these quotes to keep valid for other tools.

**Comment by amorde** [comment] 2018-10-23 17:40
@Whirlwind do the quotes cause any issues? `Podfile.lock` isn't something that is supposed to be frequently read or consumed by other tools, so I don't think CocoaPods should be adjusting its implementation to cater to that. If the quoting makes the YAML parsing more reliable, I would opt for keeping the quotes.

**Closed** 2018-10-24 08:15 UTC
Labels: d1:easy, help wanted, t1:enhancement
