### ISSUE TITLE
pod install fails with "There may only be up to 1 unique SWIFT_VERSION per target. Found target(s) with multiple Swift versions:"

### ISSUE THREAD

**Issue by dlo** [CocoaPods/CocoaPods#7267] opened 2017-12-06 19:05 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run "pod install"

## What did you expect to happen?

I expect CocoaPods to install.

## What happened instead?

Pods fail to install:

```
 $ pod install
Analyzing dependencies
[!] There may only be up to 1 unique SWIFT_VERSION per target. Found target(s) with multiple Swift versions:
My App: Swift
My App: Swift 4.0
```

### Stack

```
   CocoaPods : 1.4.0.beta.2
        Ruby : ruby 2.4.2p198 (2017-09-14 revision 59899) [x86_64-darwin17]
    RubyGems : 2.6.13
        Host : Mac OS X 10.13.1 (17B1003)
       Xcode : 9.2 (9C40b)
         Git : git version 2.14.1
Ruby lib dir : /Users/dan/.rbenv/versions/2.4.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 79ac7bd97bcfed87b5612527d2834556c399b97f
               wepay - git@github.com:wepay/mobile-podspecs.git @ dc0adce02cba98e28dee2312c03bf507235d7a00
```

### Installation Source

```
Executable Path: /Users/dan/.rbenv/versions/2.4.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# vim: ft=ruby
#
platform :ios, '10.3'

source 'https://github.com/CocoaPods/Specs.git'
project 'My App.xcodeproj'

inhibit_all_warnings!
use_frameworks!

pod 'Alamofire', '~> 4.0'
pod 'AlamofireImage', '~> 3.0'
pod 'AlamofireNetworkActivityIndicator', '~> 2.0'

pod 'LionheartExtensions', '~> 3.8'
pod 'SuperLayout', '~> 0.2'
pod 'LionheartAlamofireClient', '~> 2.2'
pod 'QuickTableView', '~> 2.3'

pod 'TableViewPopoverPresenting', '~> 3'
pod 'FMDB/standalone/FTS', '~> 2.6'
pod 'KeyboardAdjuster'
pod 'ReachabilitySwift', '~> 3.0'
pod 'SwiftyUserDefaults', '~> 3.0'

pod 'Siren', '~> 1.1'

# Analytics
pod 'Mixpanel-swift', '~> 2.1'

pod 'Firebase/Core'
pod 'Firebase/Crash'
pod 'Firebase/Messaging'

pod 'FBSDKCoreKit'
pod 'FBSDKLoginKit'
pod 'FBSDKShareKit'

pod 'ZendeskSDK'

pod 'Sentry', :git => 'https://github.com/getsentry/sentry-cocoa.git', :subspecs => ['Core', 'KSCrash'], :tag => '3.2.1'

target 'My App' do
end

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['CLANG_ALLOW_NON_MODULAR_INCLUDES_IN_FRAMEWORK_MODULES'] = "YES"
    end
  end
end
```

**Comment by dlo** [comment] 2017-12-06 19:06
FWIW, I've gone through the entire project file, and SWIFT_VERSION is set to "4.0" for all targets.

**Comment by dnkoutso** [comment] 2017-12-06 20:10
Uh, I am uncertain what is going on here. I still believe your `.xcodeproj` for some reason includes `SWIFT_VERSION` for `My App`. 

My advice is to open `MyApp.xcodeproj/project.pbxproj` and search for `SWIFT_VERSION` and delete the one with an empty value.

Going to close this and re-open if you can confirm there is no such entry in your project and upload a sample app demonstrating this issue.

**Closed by dnkoutso** 2017-12-06 20:10 UTC

**Comment by dlo** [comment] 2017-12-06 20:16
@dnkoutso See my [previous comment](https://github.com/CocoaPods/CocoaPods/issues/7267#issuecomment-349741834), it addresses your suggestion. Every target is set to "4.0"—there are no blanks.

Let me see if I can set up a sample project.

**Comment by dnkoutso** [comment] 2017-12-06 20:19
Thank you! Interesting to see you are also on Xcode 9.2 so that might always have to do something with it.

**Comment by SkipCat** [comment] 2020-08-03 16:03
I had this error too, using XCode 11.3.1. What was causing the issue is that SWIFT_VERSION was only defined for the Debug mode. In Xcode, check that in **Build settings** > **User-defined** > **SWIFT_VERSION** both Debug and Release modes have a value, like this:

<img width="424" alt="Capture d’écran 2020-08-03 à 17 59 20" src="https://user-images.githubusercontent.com/17815245/89202600-7e1e5200-d5b3-11ea-99c0-7bd366a00a05.png">

**Comment by tanmoy27112000** [comment] 2022-06-03 07:30
If you have added a firebase messaging target check the build setting and search for SWIFT_VERSION. you will see that there will be some flavor without any swift version just get the global version to 5.
<img width="1637" alt="Screenshot 2022-06-03 at 1 00 18 PM" src="https://user-images.githubusercontent.com/22212661/171808518-36337d35-44ac-4d18-a720-2e27ad6d0a1d.png">
0

**Comment by akbar607** [comment] 2024-03-11 06:19
Thank lot you saved my day
