### ISSUE TITLE
Import conflict issue

### ISSUE THREAD

**Issue by smolskyaleksey** [CocoaPods/CocoaPods#6130] opened 2016-11-04 07:54 UTC
Hello, I have conflict issue when I try to add 2 pods to my project. Issue is "Expected function body after function declarator". http://prntscr.com/d2ksx7 . I attached demo project to show issue. Could you help me to find right way to resolve it?  Need to make pod install before run project.
Environment: Xcode 8.1, Cocoapods 1.1.1
[PJTEST.zip](https://github.com/CocoaPods/CocoaPods/files/570856/PJTEST.zip)

**Comment by b-ray** [comment] 2016-11-04 19:36
Try removing the `ALWAYS_SEARCH_USER_PATHS` xcconfig setting from the three local podspecs to fix the `"Expected function body after function declarator"` error.
However, I experienced a second error when building the project, which is caused by having two c++ header files in the project with the same name.
To fix this, I'd suggest disabling the `headermap` for the `Realm` pod for now. To do that, update your post_install hook to the following:

```
post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        target.build_configurations.each do |config|
            if target.name == 'Realm'
                config.build_settings['USE_HEADERMAP'] = 'NO'
            end
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
            config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'PJ_AUTOCONF=1'
        end
    end
end
```

**Comment by smolskyaleksey** [comment] 2016-11-08 16:35
Thank you very much. You are very helpful, the problem was solved.

**Comment by orta** [comment] 2016-11-28 12:11
Closing due to no actionable things to do here

**Closed by orta** 2016-11-28 12:11 UTC
Labels: s4:awaiting validation
