### ISSUE TITLE
Can't do `pod trunk push` for a Swift 3.0 library

### ISSUE THREAD

**Issue by evgenyneu** [CocoaPods/CocoaPods#5515] opened 2016-06-14 10:32 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run `pod trunk push` for the library written in Swift 3.0 using Xcode 8.0 (8S128d).

## What did you expect to happen?

Pushed the library to cocoapods.

## What happened instead?

Shows the following error:

```
Validating podspec
 -> SigmaSwiftStatistics (2.0.0)
    - ERROR | [iOS] unknown: Encountered an unknown error (Simulator iPhone 4s is not available.) during validation.
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.2p95 (2015-04-13 revision 50295) [x86_64-darwin14]
    RubyGems : 2.4.5
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 8.0 (8S128d)
         Git : git version 2.8.1 (Apple Git-69)
Ruby lib dir : /Users/evgenii/.rbenv/versions/2.2.2/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 488f8b4ae512b216b2ded446b3f3e58e9eba6fba
```

### Installation Source

```
Executable Path: /Users/evgenii/.rbenv/versions/2.2.2/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

## Project that demonstrates the issue

https://github.com/evgenyneu/SigmaSwiftStatistics

iPhone 4S is no longer supported in iOS 10. If I try to add this simulator in Xcode it shown the following error:

> Incompatible device.

**Comment by Brett-Best** [comment] 2016-06-14 14:14
@evgenyneu I think the problem is in https://github.com/CocoaPods/CocoaPods/blob/048955d3f1b285c4fae5c70186e87f1aa7467f5e/lib/cocoapods/validator.rb#L725 and https://github.com/CocoaPods/CocoaPods/blob/048955d3f1b285c4fae5c70186e87f1aa7467f5e/spec/unit/validator_spec.rb#L430.

**Comment by segiddins** [comment] 2016-06-14 15:29
Your podspec says you support back to iOS 8, so try creating an iOS 8 4S simulator?

**Comment by evgenyneu** [comment] 2016-06-14 22:14
@Brett-Best, good thinking. I changed 'iPhone 4s' to 'iPhone 5' in the [validator.rb](https://github.com/CocoaPods/CocoaPods/blob/048955d3f1b285c4fae5c70186e87f1aa7467f5e/lib/cocoapods/validator.rb#L725) but `pod spec lint` complained that it could not find iPhone 5. It looked like it could not find any of my iOS 10 simulators.

However, the problem was fixed after I downloaded iOS 9.3 simulator. I was able to `pod trunk push` and my issue is fixed. Thanks, @segiddins.

**Comment by DanToml** [comment] 2016-07-04 20:30
I think this should also be fixed by https://github.com/CocoaPods/CocoaPods/pull/5529
\c @neonichu

**Comment by neonichu** [comment] 2016-07-04 20:46
@DanToml good catch, I think you're right :+1:

**Closed by neonichu** 2016-07-04 20:46 UTC

**Comment by evolFe** [comment] 2016-07-15 02:24
I have the same problem, but my Xcode have the iOS 9.3 simulator. My Xcode version is 7.3.1
