### ISSUE TITLE
FB iOS SDK  Include of non-modular header inside framework module

### ISSUE THREAD

**Issue by UtkuDalmaz** [CocoaPods/CocoaPods#5310] opened 2016-05-13 11:09 UTC
Hello,

I am trying to import FB ios SDK to my project.

First of all, i cannot use use_frameworks! because one of the library that i use is not built as dynamic framework. However, Bolts library is also installed automatically with that library in pods. 

When i want to import FBSDKCore and FBSDKLogin to my project, i get  "Include of non-modular header inside framework module" at "# import <Bolts/BFAppLinkResolving.h>" that line.

I suspect that is caused by Bolts framework installed via cocoapod. 

When i try to install FB SDK via cocoapods i have the same issue.

Anyone knows a proper fix for this issue ?

xCode : 7.3.1
CocoaPods: 1.0
FB SDK: 4.11

**Comment by neonichu** [comment] 2016-05-13 12:01
Could you please take a look at <https://github.com/CocoaPods/CocoaPods/blob/master/.github/ISSUE_TEMPLATE.md> and share required information like your `Podfile`? It would also be helpful to share a project which reproduces the issue.

**Comment by UtkuDalmaz** [comment] 2016-05-13 13:04
Oh sorry

Here is my podfile

platform :ios, “8.0”

target “Jemiyet” do
pod 'SVProgressHUD'
pod 'TWMessageBarManager'
pod 'QMServices'
pod 'Fabric'
pod 'Crashlytics'
end

**Comment by neonichu** [comment] 2016-05-13 14:20
So essentially you have two copies of the Bolts framework in your project, one coming in as a transitive dependency via CP and one because you're integrating the FB SDK? That's probably the cause of the error you're getting, because you'll end up with a modular and a non-modular copy of the headers (also most likely linker issues later on because of duplicated symbols).

**Comment by UtkuDalmaz** [comment] 2016-05-13 14:57
I only imported FBSDKCore and FBSDKLogin frameworks, not Bolts but you are
right i have non-modular Bolts.

How can i fix this issue?
Any idea?
On Fri, 13 May 2016 at 5:20 PM Boris Bügling <notifications@github.com>
wrote:

> So essentially you have two copies of the Bolts framework in your project,
> one coming in as a transitive dependency via CP and one because you're
> integrating the FB SDK? That's probably the cause of the error you're
> getting, because you'll end up with a modular and a non-modular copy of the
> headers (also most likely linker issues later on because of duplicated
> symbols).
>
> —
> You are receiving this because you authored the thread.
> Reply to this email directly or view it on GitHub
> <https://github.com/CocoaPods/CocoaPods/issues/5310#issuecomment-219056761>
>
-- 
*Utku Dalmaz*
Tel: +905334373245
http://utkudalmaz.com

LinkedIn: http://tr.linkedin.com/pub/utku-dalmaz/34/773/811
Youtube: http://youtube.com/utkudalmaz
Facebook: http://facebook.com/utkudalmazmusic
Twitter: http://twitter.com/utkudalmaz
Soundcloud: http://soundcloud.com/utkudalmaz
Google+: https://plus.google.com/100460446190264550069
Skype: utkudalmaz

**Comment by Coeur** [comment] 2016-05-13 15:37
If you are using CocoaPods, why not using:

    pod 'FBSDKCoreKit'
    pod 'FBSDKLoginKit'
    pod 'Bolts'

**Comment by UtkuDalmaz** [comment] 2016-05-13 21:24
@Coeur 

When i try this i get

No such module 'FBSDKCoreKit'

**Comment by UtkuDalmaz** [comment] 2016-05-14 03:07
And also how can i prevent cocoapods to install a library this is required by an installed library?

in my case, it installs Bolts because it is needed by QMServices, is there a way to prevent this and install Bolts manually ?

**Comment by Coeur** [comment] 2016-05-14 08:12
@UtkuDalmaz oh, I got an answer for your last question:
1) duplicate the [podspec of QMServices](https://github.com/CocoaPods/Specs/blob/master/Specs/QMServices/0.4/QMServices.podspec.json) locally, and edit the dependency on Bolts from it
2) change your Podfile to:

    pod 'QMServices', podspec: 'QMServices.podspec.json'

3) add your 'manual' dependency on Bolts in the Podfile, otherwise the pod lib won't build.

**Comment by UtkuDalmaz** [comment] 2016-05-14 12:53
@Coeur 
1-) where should i copy it?
2-) thats ok
3-) can you give me more detail on this?

**Comment by Coeur** [comment] 2016-05-14 14:39
Copy it anywhere in your repo. For an example, I put my custom podspecs in the `Specs/` folder, and [my Podfile looks like this](https://github.com/tomaz/appledoc/blob/master/Podfile).

**Comment by UtkuDalmaz** [comment] 2016-05-14 15:16
@Coeur 

One more question

If i skip Bolts installation via cocoapods, then will that library needs it be able to build with manually added Bolts framework ?

**Comment by neonichu** [comment] 2016-05-15 19:53
I feel like we have ventured out of the scope of an issue with CP here, so I'm going to close this.

**Closed by neonichu** 2016-05-15 19:53 UTC
Labels: s1:awaiting input

**Comment by Coeur** [comment] 2016-05-16 01:38
@UtkuDalmaz, I don't know.
