### ISSUE TITLE
anyone can help me

### ISSUE THREAD

**Issue by codesourse** [CocoaPods/CocoaPods#4013] opened 2015-08-12 08:19 UTC
[!] Can't merge user_target_xcconfig for pod targets: ["Bugly", "Realm", "Headers"]. Singular build setting CLANG_CXX_LANGUAGE_STANDARD has different values.

**Comment by neonichu** [comment] 2015-08-12 08:51
This is a duplicate of #3813

**Closed by neonichu** 2015-08-12 08:51 UTC
