### ISSUE TITLE
resources are not copied when source_files are specified

### ISSUE THREAD

**Issue by brightredchilli** [CocoaPods/CocoaPods#5105] opened 2016-03-30 15:54 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

:rainbow: :heart:
# Report
Cocoapods 0.39.0
I have a project that includes another project, and uses the 'resources' podspec to specify an image to be copied over. What I'm seeing is that when I specify an .m file in my project, the image fails to copy. I have some lines in the AppDelegate that simply print the path of the image, if found.
```
#s.source_files = "SomeLibrary/SomeViewController.h" #Uncomment this line and comment the one below, it works!
s.source_files = "SomeLibrary/SomeViewController.h", "SomeLibrary/SomeViewController.m" #Comment this line and uncomment the line above, it works!
```
## What did you do?

Sample project: https://github.com/brightredchilli/test-pod-resources

This sample project has a project called Testpod, and library called SomeLibrary, which is very sparse. SomeLibrary has a podspec.

## What did you expected to happen?
I expected to see an image copied over to my target project from the library, SomeLibrary.

Including an .m file would causes resources not to be copied over. I maybe suspect that maybe this has something to do with frameworks, but, it seems against the contract of 'resources' - (A list of resources that should be copied into the target bundle.)

## What happened instead?

When m files are includes, resources are not copied. When they are ommitted, resources are copied fine.

## Podfile

```ruby
platform :ios, '8.0'

inhibit_all_warnings!
use_frameworks!

link_with 'PodTest'

target 'PodTest' do
  pod 'SomeLibrary', :path => 'SomeLibrary'
end
```

## Podspec(of the offending library)

```ruby
Pod::Spec.new do |s|
  s.name          = "SomeLibrary"
  s.version       = "0.0.1"
  s.summary       = "A library to test the resources functionality of podspec"
  s.description   = <<-DESC
                    test test test
                    DESC
  s.license       = "MIT"
  s.authors       = { "Me" => "ying@intrepid.io" }
  s.resources = "SomeResources/**/*"
  #s.source_files = "SomeLibrary/SomeViewController.h" #Uncomment this line and comment the one below, it works!
  s.source_files = "SomeLibrary/SomeViewController.h", "SomeLibrary/SomeViewController.m" #Comment this line and uncomment the line above, it works!
  s.platform      = :ios
  s.ios.deployment_target = "8.0"
end
```

**Comment by segiddins** [comment] 2016-04-01 01:17
@efirestone any interest in looking into this one?

**Comment by segiddins** [comment] 2016-04-01 01:18
(The distinction with the source files is that it determines whether or not we actually build a target for the Pod)

**Comment by efirestone** [comment] 2016-04-01 02:54
Looking…

**Comment by efirestone** [comment] 2016-04-01 04:28
As you mention @segiddins , here's what's happening using 1.0.0.beta.6:

*With Sources (.m's)*
A `SomeLibrary.framework` target is created and the `.m`s are compiled to become the executable in the framework. Because there's a `.framework` bundle, the resources get copied into that bundle.

*Without Sources (.m's)*
There's nothing to compile, so there's nothing to turn into the executable part of a `.framework`, so there's no way to create a valid framework bundle. Since there's no bundle, the resources get copied into the main app bundle.

The short version is that resources that are provided by a framework need to be looked up using [`+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/occ/clm/UIImage/imageNamed:inBundle:compatibleWithTraitCollection:), where you explicitly specify the framework bundle as the place to find the resource.

A few options:
- (Recommended) Use `.resource_bundles` and look the image up from there using [`+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/occ/clm/UIImage/imageNamed:inBundle:compatibleWithTraitCollection:)
- (Alternative Recommendation) Include the `.m` and use [`+[UIImage imageNamed:inBundle:compatibleWithTraitCollection:]`](https://developer.apple.com/library/ios/documentation/UIKit/Reference/UIImage_Class/#//apple_ref/occ/clm/UIImage/imageNamed:inBundle:compatibleWithTraitCollection:) to look the image up from the framework bundle.
- Use static libraries, which will force the images to go into the app bundle (like they are in your example when no `.m`s are present)


If CocoaPods wanted to make things consistent for your two example cases, it could *always* generate the framework bundle by creating a dummy Objective-C class and compiling that to make the framework. This wouldn't necessarily help you, as it would mean that neither of your example cases would work (without switching to the `UIImage` method I mentioned). It also isn't necessarily any more correct than the behavior today.

@brightredchilli, add back your `.m` file and give the `UIImage` method I mentioned a shot. If that works for you then I suggest we close this as "behaves correctly".

**Comment by brightredchilli** [comment] 2016-04-02 19:59
The scenario I have is that I am integrating an old library that did not use cocoapods, and did not consider the need to namespace resources. It would be really nice for me to use coocapods to integrate this library, explicitly capturing it's resources.

I have experimented now with resource bundles and yes, resource bundles do work. I can say that although there is a workaround to this issue, it really isn't clear why `resources` should work in one scenario and not the other. It seems that `resources` doesn't have any practical use. Sure I can copy images, but if I just had a bunch of images, it's unlikely ill use cocoapods to integrate them. I would wager that almost always there is accompanying code that uses the resources. I'm curious to know what you guys think is the right way to handle this, regardless of whether cocoapods intends to change the way it works currently.

If this is not a path cocoapods wants to go down, it might be helpful to just update the documentation to say so.

**Comment by efirestone** [comment] 2016-04-03 06:52
Glad resource bundles work. They're the recommended approach for handling resources these days. A couple points:

- `resources` is not a recommended mechanism anymore for reasons similar to what you're hitting (the documentation mentions as much). There's no namespacing which can lead to libraries squashing each others' resources.
- When looking for resources, or for resource bundles for that matter, it's a good practice to use `bundleForClass` to find the resource with a class that's part of `SomeLibrary`. This works consistently whether the class is part of the main bundle (when using static libraries), or part of a separate executable bundle (when using dynamic frameworks). This can be turned into a handy category method along the lines of `+[NSBundle someLibraryResourcesBundle]`. See [this comment](https://github.com/CocoaPods/CocoaPods/issues/4851#issuecomment-184323213) for some code. This doesn't directly help your case since you don't have any classes in your library.
- Taking the previous point even farther, I tend to use explicit API to expose resources and keep the `someLibraryResourcesBundle` method private. Your framework would provide methods along the lines of `+[SomeLibraryResources myProvidedImage]` which internally is implemented using `someLibraryResourcesBundle`. This means that (a) you get compile-time checking, and (b) if you move or rename the on-disk resource your external contract doesn't change.

To try to further clarify what's happening with `resources`, it always copies the resources into the same bundle where the code for the same podspec is compiled/linked. This has two normal use cases:
**Static Libraries**
MyApp.app
 -- MyApp // The app executable. Includes both the app code and the SomeLibrary code.
 -- SomeLibraryImage.png

**Dynamic Frameworks**
MyApp.app
 -- MyApp // The app executable. Includes the app code.
 -- SomeLibrary.framework
    -- SomeLibrary // The compiled SomeLibrary code
    -- SomeLibraryImage.png

Finally, there's your use case, which should look like the latter, but instead looks like the former. There's nothing to compile to make `SomeLibrary`, which means the `.framework` bundle would be invalid, so instead the assets are getting copied into the main app bundle.

CocoaPods isn't currently designed for your exact use case. You'd want a new method that consistently copies resources into the main app bundle, regardless of whether you're using static libraries or dynamic frameworks. The `resources` property has this behavior with static libraries or with dynamic frameworks that have no `.m` files, but as mentioned previously if you have a proper dynamic framework with classes then the resources will get copied into that framework bundle. Adding such a method is a bad idea as it has the same lack of namespacing issue that `resources` has (worse in fact), and therefore seems fine until you run into weird conflicts that manifest as incorrect assets at runtime and you have to switch to `resource_bundles` anyway.

As for the right way to handle this, the answer is to use resource bundles. Lookups work consistently and they don't have any namespacing issues. I'd suggest adding convenience methods as I mention above too to make accessing the resources less cumbersome. If there are details of your scenario that make this complicated, add some details and we can iterate.

If any of this wasn't clear from the documentation, documentation PRs are definitely welcome. Given that there aren't any required changes to the CocoaPods code, I'd suggest we close this issue.

**Closed** 2016-04-03 14:54 UTC
Labels: t3:discussion

**Comment by Coder-256** [comment] 2016-04-08 21:07
@brightredchilli This isn't the right place to post this, but I think what you're looking for is [Carthage](https://github.com/carthage/carthage).

**Comment by doubov** [comment] 2016-06-22 20:29
How about this issue: https://github.com/CocoaPods/CocoaPods/issues/5105
I have a problem where I cannot load the XIBs from my Cocoapod. The problem is resolved if I manually edit the Pods-defaults-MyApp-resources.sh and add the necessary .xib files under the install_resource directive. 
Is there a way we can have a functionality of copying our resources, despite providing source files? 
Specifying resource_bundles with the same name as the Pod seems to create another target in the Pods project:
![screen shot 2016-06-22 at 16 28 44](https://cloud.githubusercontent.com/assets/1895992/16282359/7113886e-3896-11e6-968e-451c4b57aa0e.png)
and doesn't work for the purpose. Please advise.

**Comment by efirestone** [comment] 2016-06-22 22:19
@doubov can you open a new issue? I'm not sure I fully understand your scenario, but it does sound different from what was originally described here. A basic sample project is also always helpful. Thanks!

**Comment by doubov** [comment] 2016-06-23 13:17
I will create a sample project now and create a new issue.

**Comment by doubov** [comment] 2016-06-23 13:46
@efirestone Created https://github.com/CocoaPods/CocoaPods/issues/5560

**Comment by w-i-n-s** [comment] 2019-05-28 17:09
Hi there. Next is worked for me. 
1. move all images from .xcassets 
2. `s.resources = 'PretyDevPod/Assets/**/*'`
3. extension for `UIImageView`
```swift
//  UIImageView+Additions.swift

import UIKit

public extension UIImageView {
    func setBundleImageNamed(_ name: String) {
        let bundle = Bundle(for: WizardController.self)
        let bundledImage = UIImage(named: name, in: bundle, compatibleWith: nil)
        image = bundledImage
    }
}
```
