### ISSUE TITLE
Headers in vendored framework not found

### ISSUE THREAD

**Issue by softwind0214** [CocoaPods/CocoaPods#3287] opened 2015-03-18 11:23 UTC
Hi, has anybody met this problem?

I have a pod A with a vendored framework B, and a pod C.
There is a header file in B named 'd.h', and it's referenced by 'e.h' in A.
And 'e.h' is referenced by some files in C.

When I build C as a individual project, it works well.
When I build a project with both A and C, it says 'd.h file not found'.

How can I fix this issue?

**Comment by neonichu** [comment] 2015-03-18 12:25
This sounds like a duplicate of #3161

If you control A, you can use the `public_headers` as a workaround for now, like this <https://github.com/layerhq/releases-ios/blob/master/LayerKit.podspec#L16>

**Comment by kylef** [comment] 2015-03-31 02:18
Closing as a duplicate of #3287, feel free to re-open if that isn't in fact a duplicate.

**Closed by kylef** 2015-03-31 02:18 UTC
