### ISSUE TITLE
Linker issue with HockeySDK update

### ISSUE THREAD

**Issue by jsetting32** [CocoaPods/CocoaPods#3875] opened 2015-07-23 21:38 UTC
I am currently having an issue with my project when I ran pod update. 

```
Ld /Users/jsetting32/Library/Developer/Xcode/DerivedData/iMobileRep-fkbibgkprypkmpgvfnzgodvshqzn/Build/Products/Debug-iphonesimulator/iMobileRepTests.xctest/iMobileRepTests normal i386
    cd /Users/jsetting32/Documents/Projects/iMobileRep
    export IPHONEOS_DEPLOYMENT_TARGET=8.3
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang++ -arch i386 -bundle -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk -L/Users/jsetting32/Library/Developer/Xcode/DerivedData/iMobileRep-fkbibgkprypkmpgvfnzgodvshqzn/Build/Products/Debug-iphonesimulator -L/Users/jsetting32/Documents/Projects/iMobileRep/iMobileRep -F/Users/jsetting32/Library/Developer/Xcode/DerivedData/iMobileRep-fkbibgkprypkmpgvfnzgodvshqzn/Build/Products/Debug-iphonesimulator -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/Developer/Library/Frameworks -F/Users/jsetting32/Documents/Projects/iMobileRep/Pods/HockeySDK/HockeySDK-iOS/HockeySDK.embeddedframework -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/Library/Frameworks -F/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator8.4.sdk/Developer/Library/Frameworks -filelist /Users/jsetting32/Library/Developer/Xcode/DerivedData/iMobileRep-fkbibgkprypkmpgvfnzgodvshqzn/Build/Intermediates/iMobileRep.build/Debug-iphonesimulator/iMobileRepTests.build/Objects-normal/i386/iMobileRepTests.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -Xlinker -rpath -Xlinker @loader_path/Frameworks -bundle_loader /Users/jsetting32/Library/Developer/Xcode/DerivedData/iMobileRep-fkbibgkprypkmpgvfnzgodvshqzn/Build/Products/Debug-iphonesimulator/iMobileRep.app/iMobileRep -Xlinker -objc_abi_version -Xlinker 2 -framework XCTest -ObjC -lAFNetworking -lCocoaAsyncSocket -lGDataXML-HTML -lM13ProgressSuite -lMBProgressHUD -lQR-Code-Encoder-for-Objective-C -lSMXMLDocument -lSVStatusHUD -lTBXML -lZipArchive -lc++ -liCarousel -lobjective-zip -lvfrReader -lxml2 -lz -framework Accelerate -framework AssetsLibrary -framework CFNetwork -framework CoreGraphics -framework CoreImage -framework CoreText -framework Foundation -framework HockeySDK -framework ImageIO -framework MessageUI -framework MobileCoreServices -framework QuartzCore -framework QuickLook -framework Security -framework SystemConfiguration -framework UIKit -ObjC -lxml2 -lz -lPods-iMobileRep-HockeySDK -lPods-iMobileRep-MBProgressHUD -lPods-iMobileRep-QR-Code-Encoder-for-Objective-C -lPods-iMobileRep-SMXMLDocument -framework AssetsLibrary -framework CoreGraphics -framework CoreText -framework CrashReporter -framework MobileCoreServices -framework QuartzCore -framework QuickLook -framework Security -framework SystemConfiguration -framework UIKit -fobjc-arc -fobjc-link-runtime -Xlinker -no_implicit_dylibs -stdlib=libc++ -mios-simulator-version-min=8.3 -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/jsetting32/Library/Developer/Xcode/DerivedData/iMobileRep-fkbibgkprypkmpgvfnzgodvshqzn/Build/Intermediates/iMobileRep.build/Debug-iphonesimulator/iMobileRepTests.build/iMobileRepTests.xctest.xcent -lScanApi -lPods-iMobileRepTests -Xlinker -dependency_info -Xlinker /Users/jsetting32/Library/Developer/Xcode/DerivedData/iMobileRep-fkbibgkprypkmpgvfnzgodvshqzn/Build/Intermediates/iMobileRep.build/Debug-iphonesimulator/iMobileRepTests.build/Objects-normal/i386/iMobileRepTests_dependency_info.dat -o /Users/jsetting32/Library/Developer/Xcode/DerivedData/iMobileRep-fkbibgkprypkmpgvfnzgodvshqzn/Build/Products/Debug-iphonesimulator/iMobileRepTests.xctest/iMobileRepTests

ld: framework not found CrashReporter
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

This only occurs in the test target. 

Both configuration files in the main project target are set to the Pod Config files. I have been at this for hours but basically once I ran 'pod update', it updated HockeySDK to a later version (of course). It was working before the update. I then reverted back to the old HockeySDK version I was using and the same issue appeared. Then I checked the HockeySDK pod directory and CrashReporter.framework is there. So I was thinking there may be an issue with linkers but I am at a loss. I am using cocoapods version 0.38.0. Any ideas why this occurred?

PS. When it was working, I had cocoapods version 0.37.2 and HockeySDK 3.6.4. I ran a cocoapods install and then ran pod update and I'm where I am now

**Comment by segiddins** [comment] 2015-07-23 22:14
Can you please share your pod file?

**Comment by jsetting32** [comment] 2015-07-23 22:31
target 'iMobileRep' do
pod 'AFNetworking'
pod 'QR-Code-Encoder-for-Objective-C'
pod 'HockeySDK', '~> 3.6.4'
pod 'MBProgressHUD'
pod 'SMXMLDocument'
pod 'iCarousel'
pod 'CocoaAsyncSocket'
pod 'TBXML'
pod 'SVStatusHUD'
pod 'M13ProgressSuite'
pod 'vfrReader'
pod 'objective-zip'
pod 'GDataXML-HTML'
pod 'ZipArchive'
end

target 'iMobileRepTests' do
end

**Comment by flufff42** [comment] 2015-07-27 08:16
After migrating to 0.38.x I encountered a similar issue.

In this particular case the Podfile was set up roughly as follows:

```ruby
pod AFNetworking
pod 'LibraryWithAFNetworkingDependency'

target :TestTarget, :exclusive => true do
    pod 'OCMock'
    pod 'LibraryWithAFNetworkingDependency'
end
```

yielding linker errors for the test target's `LibraryWithAFNetworkingDependency` where `AFNetworking` could not be found.

This was fixed with 

```diff
- target :TestTarget, :exclusive => true do
+ target :TestTarget do
```

In your case @jsetting32 I believe moving `HockeySDK` outside of your application target should make it available for the test target also.

@segiddins This looks to me like a rather subtle interaction between target deduplication and the behaviour of `exclusive => true` as I don't recall seeing any changes documented there.

**Comment by neonichu** [comment] 2015-07-27 08:29
Hm, this seems more like a bug in the deduplication to me, since the explicit AFNetworking dependency should still be honoured, regardless of the `exclusive => true`. cc @mrackwitz

**Comment by neonichu** [comment] 2016-05-01 17:17
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Closed by neonichu** 2016-05-01 17:17 UTC
