### ISSUE TITLE
ERROR ITMS-90502: in tvOS and iOS targets in one project

### ISSUE THREAD

**Issue by 3lvis** [CocoaPods/CocoaPods#4526] opened 2015-11-10 14:02 UTC
When sending my tvOS app to the App Store for TestFlight purposes I get

>ERROR ITMS-90502: "Invalid Bundle. Apps that only contain the arm64 slice must also have 'arm64' in the list of UIRequiredDeviceCapabilities in Info.plist."

Even when my Info.plist contains this.
![c6z1i](https://cloud.githubusercontent.com/assets/1088217/11064185/d50f0ab4-87bb-11e5-8fcd-7404c4f1a3ac.png)

After some research I found that this gets solved by adding the mentioned `UIRequiredDeviceCapabilities` to each pod :

<img width="901" alt="screen shot 2015-11-10 at 15 02 00" src="https://cloud.githubusercontent.com/assets/1088217/11064206/09c113ce-87bc-11e5-895b-09bbbe4742fb.png">

Sadly I have two Info.plist per Pod so I had to add a lot of this for this issue to be fixed.

**Comment by 3lvis** [comment] 2015-11-10 14:04
Similar question in StackOverflow http://stackoverflow.com/questions/33575798/error-itms-90502-on-tvos-target

**Comment by orta** [comment] 2015-11-10 14:13
this is a duplicate of #4514 - which also contains a fix, might make a SO comment pointing people there if they need it, thanks @3lvis

**Closed by orta** 2015-11-10 14:13 UTC

**Comment by 3lvis** [comment] 2015-11-10 14:58
@orta thanks!
