### ISSUE TITLE
Missing Required Modules

### ISSUE THREAD

**Issue by bassrock** [CocoaPods/CocoaPods#3095] opened 2015-02-02 00:51 UTC
I amusing the 0.36.0 beta 2 version of the plugin and working to create an app using an Extension. I want my app framework to be the only part that uses certain cocoa pods. However when I try to import my AppKit into my main project (using swift) the complier complains that it is missing the required modules, which happen to be the cocoapods that I am not including in my main app.

![screen shot 2015-02-01 at 4 48 32 pm](https://cloud.githubusercontent.com/assets/1010384/5994697/57765326-aa32-11e4-9b69-e8e50f1d84a3.png)

![screen shot 2015-02-01 at 4 50 00 pm](https://cloud.githubusercontent.com/assets/1010384/5994700/9af657ae-aa32-11e4-8aa5-9e71d2969ad8.png)

**Comment by orta** [comment] 2015-02-11 11:42
Sorry to be that guy, but can you by chance make a tiny demo project with this behaviour? It's hard to get a sense of where the problem lies with just this discussion.

**Comment by bassrock** [comment] 2015-02-18 01:10
@orta sorry for the delay a project is here and I am on the Xcode Beta 6.2: 
https://github.com/bassrock/CocoaPodsIssueDemo.git

**Comment by neonichu** [comment] 2015-02-18 09:42
@bassrock thx for the sample

The issue is that the dependencies of TestKit end up in their own directory "Pods-TestKit", so they will not be found when linking the "Demo" target. cc @mrackwitz

**Comment by bassrock** [comment] 2015-02-19 01:10
So how should the frameworks actually go about this?

**Comment by neonichu** [comment] 2015-02-19 02:11
@bassrock It is an issue in how CocoaPods builds the dependencies, not in how you set up your framework.

**Comment by mrackwitz** [comment] 2015-02-20 19:24
CocoaPods with frameworks extends the scoping of build products by a further level. It appends the name of the target to integrate to the default `CONFIGURATION_BUILD_DIR` to make sure, that you always integrate the right build of the framework as you could have different selections of subspecs per target definition (which is a `target '…' do … end` block in the Podfile).
So they are scoped effectively by: `Project > Configuration > Platform > Target`.
Xcode has very limited handling for paths of build artificats and doesn't support this scoping. To work around this limitations, we embed the frameworks by a shell script build phase instead of a copy files build phase.

In your case, you would need to follow these steps, at least for the current beta release:
1. Configure `FRAMEWORK_SEARCH_PATHS` of your app `Test` to include an entry `$(CONFIGURATION_BUILD_DIR)/TestKit`.
2. Add a script shell build phase `Embed Pods Frameworks` with the following line: `"${SRCROOT}/Pods/Target Support Files/Pods-TestKit/Pods-TestKit-frameworks.sh"`

Another idea would be to provide a podspec for your AppKit and integrate it over CocoaPods in your application.

**Comment by bassrock** [comment] 2015-02-20 20:16
Ok I will try the first option there as it seems less cumbersome than creating a new pod spec. Is this a limitation that will probably be changed in the future somehow with cocoa pods?

**Comment by bassrock** [comment] 2015-02-21 01:20
@mrackwitz tried your solution on this branch. https://github.com/bassrock/CocoaPodsIssueDemo/tree/solution-1Test

It seemed to work for the app but not for the Today Extension. Is that one doing something different?

**Comment by neonichu** [comment] 2015-02-24 10:10
As a solution for CP itself, we have to think about deduplicating framework targets and only scope those which really need, so instances of the same Pod being used with different sets of subspecs. This would also solve CocoaPods/swift#3 (usage of Pods in Playgrounds) and the linked issue #3063.

**Comment by cmds4410** [comment] 2015-03-25 23:09
@mrackwitz Am I correct that there's no way to effectively "shield" these pods from external targets? I'm running into the same issue as @bassrock where my Extension doesn't need to use any of the cocoa pods directly, but Xcode is complaining that they are missing. I tried your solution above to no avail. I would greatly appreciate any additional thoughts you have :) cc @neonichu

**Comment by cmds4410** [comment] 2015-03-30 21:28
@bassrock Have you had any luck?

**Comment by bassrock** [comment] 2015-03-30 21:29
@cmds4410 nope. I switched to a static library for all the ui pods, and then used carthage for my iOS 8 frameworks i needed to share.

**Comment by cmds4410** [comment] 2015-03-30 21:32
@bassrock Bummer. How are you getting around the warnings for linking against unsafe dylibs?

**Comment by bassrock** [comment] 2015-03-30 21:33
@cmds4410 what warnings? I am only using frameworks that support the API Enabled

**Comment by cmds4410** [comment] 2015-03-30 21:46
@bassrock Whoops I wasn't sure if you were still using the pods you referenced here: https://github.com/CocoaPods/CocoaPods/issues/2980

**Comment by bassrock** [comment] 2015-03-30 21:47
@cmds4410 nope. I can't due to these issues. So I have had to create a lot of mine own stuff to handle it. And switched to AlamoFire

**Comment by stamhankar999** [comment] 2015-04-09 21:54
Is there an ETA for the fix? Several of our customers are hitting this in our CI service (ship.io).

**Comment by RedPlumber** [comment] 2015-04-27 08:40
Hi all,
I think I have similar problem and I created a sample project.
As I explain in the readme file, everything is fine on the master branch but I have a problem in develop branch adding a different kind of pod.. can you please help me with https://github.com/RedPlumber/SwiftProject ? Thanks

**Comment by kordziu** [comment] 2015-05-08 09:55
Just kindly asking if there are any news on it? It is making our Jenkins configuration does not work with Swift&CocoaPods now what makes using pods in project very painful.

**Comment by olala7846** [comment] 2015-05-11 09:38
We have the same issue as @kordziu , this breaks our Jenkins configurations ... Is there any workaround for Jenkins?

**Comment by neonichu** [comment] 2015-05-11 09:57
There's work going on to fix this in #3550 - but it's not quite ready, yet.

**Comment by cdwind** [comment] 2015-05-12 20:42
I'm using 0.37.1 get this error

rsync error: some files could not be transferred (code 23) at /SourceCache/rsync/rsync-45/rsync/main.c(992) [sender=2.6.9]
Command /bin/sh failed with exit code 23

**Comment by codecaffeine** [comment] 2015-05-13 18:45
@cdwind I saw the same issue (#3541) and they said it’s because of this issue.

**Comment by levous** [comment] 2015-06-17 05:53
Hopefully this will be resolved soon but I managed to fix it in a reliable if not kludgy way.

In xcode project > target > build phases
add a run script build phase before "Copy Pod Resources".  
Paste this script: 
`sed -i -- 's/Pods-TheBadPathAppTests\///g' "${SRCROOT}/Pods/Target Support Files/Pods-TheBadPathAppTests/Pods-TheBadPathAppTests-frameworks.sh"`
replace all occurrences of "TheBadPathAppTests" with your app target name
There.  Now you can build in Xcode AND xctool

**Comment by RedPlumber** [comment] 2015-07-05 21:32
All issues have been fixed on my sample project with latest cocoa pods beta version 0.38.0.beta.2
check out https://github.com/RedPlumber/SwiftProject

**Comment by neonichu** [comment] 2015-08-19 17:45
This has been fixed by target deduplication.

**Closed by neonichu** 2015-08-19 17:45 UTC
Labels: s2:confirmed, t2:defect
