### ISSUE TITLE
Unable to archive watchOS example

### ISSUE THREAD

**Issue by mrezk** [CocoaPods/CocoaPods#4023] opened 2015-08-13 19:57 UTC
:rainbow: I am getting the following error when trying to archive watchOS example: 
```
ld: building for watchOS, but linking in object file built for iOS, file '/Users/mrezk/Library/Developer/Xcode/DerivedData/watchOSsample-fleuimghmfxceqgyqzusbgvktttd/Build/Intermediates/ArchiveIntermediates/watchOSsample/BuildProductsPath/Release-watchos/Pods-watchOSsample WatchKit Extension/Alamofire.framework/Alamofire' for architecture armv7k
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

I am using the watchOS example project modified by https://github.com/CocoaPods/CocoaPods/pull/4022.

**Comment by segiddins** [comment] 2015-08-13 23:34
Is there any chance this is fixed by https://github.com/CocoaPods/CocoaPods/pull/4004 ?

**Comment by mrezk** [comment] 2015-08-14 03:58
Nope, I just tested that and got the exact same result :disappointed:.

**Comment by neonichu** [comment] 2016-05-01 16:47
I believe this is a dupe of #4178.

**Closed by neonichu** 2016-05-01 16:47 UTC
