### ISSUE TITLE
CocoaPods 0.38.1: Ambiguous expansion of macro errors

### ISSUE THREAD

**Issue by x2on** [CocoaPods/CocoaPods#3881] opened 2015-07-24 07:59 UTC
With CocoaPods 0.38.1 and the usage of `CocoaLumberJack` in a project i get the following error:

`Ambiguous expansion of macro 'LOG_LEVEL_DEF'`

Using CocoaPods 0.38.0 it works fine.

Any ideas what could be the cause for that?

**Comment by okuramasafumi** [comment] 2015-07-24 09:25
I encountered the same problem. Downgrading to `0.38.0` works.

**Comment by neonichu** [comment] 2015-07-24 12:29
Just to clarify, is that an error `pod install` shows or an error when building with Xcode?

**Comment by x2on** [comment] 2015-07-24 12:30
@neonichu a error in Xcode after upgrading to CocoaPods 0.38.1 and run `pod install` with the new version. Switching back to 0.38.0 works.

**Comment by neonichu** [comment] 2015-07-24 16:50
Unfortunately, I cannot reproduce this in a simple project. Can one of you share a code snippet that is causing that or even better an example project?

**Comment by segiddins** [comment] 2015-07-26 05:13
This ought to be fixed in 0.38.2.

**Closed by segiddins** 2015-07-26 05:13 UTC
Labels: s1:awaiting input
