### ISSUE TITLE
MARKDOWN TEMPLATE

### ISSUE THREAD

**Issue by OlehKulykov** [CocoaPods/CocoaPods#4749] opened 2016-01-11 08:08 UTC
### Command

```
/Users/<USER_NAME>/.gem/ruby/2.0.0/bin/pod update
```

### Report

* What did you do?
  - pod update.

* What did you expect to happen?
  - generate workspace from clean xcode project with single pod.

* What happened instead?
  - workspace generated and buildable, but with errors bellow.

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
               master - https://github.com/CocoaPods/Specs.git @ 7975739a9d3ffe1d6e71882e3d0a0296da481b8b
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
use_frameworks!
platform :ios, '8.0'

pod 'LzmaSDK-ObjC', :inhibit_warnings => true
```

### Error

```
NoMethodError - undefined method `user_targets' for #<Pod::Installer::PostInstallHooksContext::UmbrellaTargetDescription:0x007f9d94ec6cb8>
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:20:in `block in pods_from_project'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `each'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `flat_map'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-stats-1.0.0.beta.2/lib/cocoapods_stats/target_mapper.rb:9:in `pods_from_project'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:31:in `block (2 levels) in <module:CocoaPodsStats>'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:80:in `titled_section'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-stats-0.6.2/lib/cocoapods_plugin.rb:27:in `block in <module:CocoaPodsStats>'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `call'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:117:in `block (3 levels) in run'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:111:in `block (2 levels) in run'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `each'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:109:in `block in run'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:140:in `message'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/hooks_manager.rb:108:in `run'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:481:in `run_plugins_post_install_hooks'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:462:in `perform_post_install_actions'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:113:in `install!'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:156:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/<USER_NAME>/.gem/ruby/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/<USER_NAME>/.gem/ruby/2.0.0/bin/pod:23:in `load'
/Users/<USER_NAME>/.gem/ruby/2.0.0/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60user_targets%27+for+%23%3CPod%3A%3AInstaller%3A%3APostInstallHooksContext%3A%3AUmbrellaTargetDescription%3A0x007f9d94ec6cb8%3E&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by neonichu** [comment] 2016-01-11 12:50
This is a duplicate of #4741

**Closed by neonichu** 2016-01-11 12:50 UTC
