### ISSUE TITLE
Podfile.lock always difference in two mac when execute pod update (The same version 1.2.0) 

### ISSUE THREAD

**Issue by weiminghuaa** [CocoaPods/CocoaPods#6514] opened 2017-02-24 09:20 UTC
git diff
```
diff --git i/Podfile.lock w/Podfile.lock
index e12c98b..2282a00 100644
--- i/Podfile.lock
+++ w/Podfile.lock
@@ -134,7 +134,7 @@ DEPENDENCIES:

 EXTERNAL SOURCES:
   React:
-    :path: ./node_modules/react-native
+    :path: "./node_modules/react-native"

 SPEC CHECKSUMS:
   AFNetworking: 5e0e199f73d8626b11e79750991f5d173d1f8b67
@@ -149,7 +149,7 @@ SPEC CHECKSUMS:
   Masonry: 9f515466afe48632562342a40a1c224071a1a022
   MDMCoreData: 28b334173177effeb1dd135da677062096e3cb68
   MGSwipeTableCell: 616700eb0ffd1c611ba909066cb7fd739790a0a7
-  MLeaksFinder: 0850e2f2abc7227adc4d4e2d1992b431264eb4d5
+  MLeaksFinder: '0850e2f2abc7227adc4d4e2d1992b431264eb4d5'
   MLLabel: 71315bd11dc45bebba159e07427496ea8bfc2b0a
   Qiniu: 77a3dba411556a383d72d17e842345a9d4c83252
   QQ_XGPush: 8c3637d61e1b3fe6e7f60bb1c8aac34184c8bf40
```

**Comment by orta** [comment] 2017-02-24 12:27
You have different versions of Ruby, and so psyche produces different YAML lock files - dupe of https://github.com/CocoaPods/CocoaPods/issues/6255

**Closed by orta** 2017-02-24 12:27 UTC
