### ISSUE TITLE
ld: library not found for -lPods-[appName]

### ISSUE THREAD

**Issue by ButuzGOL** [CocoaPods/CocoaPods#8296] opened 2018-11-19 14:35 UTC
Have issue only when do Archive (opening xcode with AppName.xcworkspace)
ld: library not found for -lPods-[appName]

This solution helps
https://stackoverflow.com/questions/24078597/cocoapods-ld-library-not-found-for-lpods-projectname/24100063#24100063

But is it normal that i always need to clean 
```grep -n 'libPods-[appName].a in Frameworks' './ios/AppName.xcodeproj/project.pbxproj'```
after pod install ?
and also have issues with this in CI

**Comment by shaharmor** [comment] 2018-11-19 15:46
I have this issue too.

Running `Pod install` generates a `liPods-[appName].a` in `Frameworks` that is not needed and have to be manually removed.

**Comment by segiddins** [comment] 2018-11-21 12:15
Please add a sample project that reproduces the issue

**Comment by sercanov** [comment] 2018-11-27 11:21
I also having this issue with custom build configuration ( not Debug or Release ) on React Native. It happens only on Archive action. It also may be related to how React Native handling schemes and build configurations.

**Comment by dnkoutso** [comment] 2019-02-21 00:12
PR out.

**Comment by msand** [comment] 2019-02-21 00:33
@dnkoutso Excellent! How can I test this?

**Comment by dnkoutso** [comment] 2019-02-21 00:34
It hasnt been merged yet and it will only perform a clean up for old integrated references. Hoping its the same thing/fix as you want.

Once it gets merged (or even now) you can use https://bundler.io/v1.12/git.html to point to a specific branch for a gem.

**Comment by dnkoutso** [comment] 2019-02-21 00:35
To me this issue occurs when someone switches from frameworks<=>static libraries or decides to switch a target from `inherit! :search_paths` to not use this. I am hoping its the same issue here.

**Comment by msand** [comment] 2019-02-21 00:37
Alright, I haven't been poking with cocoapods much, can bundler be used to override the globally installed version? Btw, I guess you're not using this in any codebase involving ReactNative?

**Comment by dnkoutso** [comment] 2019-02-21 00:38
> Btw, I guess you're not using this in any codebase involving ReactNative?

No but from the StackOverflow link this has been a long standing bug in CocoaPods and I was able to reproduce and add a test for it. Hoping this is the same issue with RN.

Yes bundler should just override the global one...you will need to use `bundle exec pod install` etc for the bundle to be used.

**Comment by msand** [comment] 2019-02-21 01:16
I tried using this:
```ruby
gem 'cocoapods', :git => 'https://github.com/dnkoutso/CocoaPods.git', :ref => '77be91d3d9b451bb438f5c1935d9e3814e630ab7'
```

But got:
```
NoMethodError - undefined method `swift_versions' for #<Pod::Specification name="DoubleConversion">
Did you mean?  swift_version
               swift_version=
```

So, I tried using the latest cocopods core dependencies from their master branches as well:
```ruby
def cp_gem(name)
  url = "https://github.com/CocoaPods/#{name}.git"
  opts = { :git => url, :branch => 'master' }
  gem name, opts
end

cp_gem 'cocoapods-deintegrate'
cp_gem 'cocoapods-downloader'
cp_gem 'cocoapods-plugins'
cp_gem 'cocoapods-search'
cp_gem 'cocoapods-stats'
cp_gem 'cocoapods-trunk'
cp_gem 'cocoapods-try'

```
But still the same: https://github.com/msand/RN059/commit/82fa7e885996553d522b4d4f44b1ee886e16abc7

@dnkoutso Any suggestions?

**Comment by msand** [comment] 2019-02-21 01:25
A few more core dependencies from the master branch seems to resolve that error:

```ruby
def cp_gem(name, repo_name)
  url = "https://github.com/CocoaPods/#{repo_name}.git"
  opts = { :git => url, :branch => 'master' }
  gem name, opts
end

cp_gem 'claide',                'CLAide'
cp_gem 'cocoapods-core',        'Core'
cp_gem 'cocoapods-deintegrate', 'cocoapods-deintegrate'
cp_gem 'cocoapods-downloader',  'cocoapods-downloader'
cp_gem 'cocoapods-plugins',     'cocoapods-plugins'
cp_gem 'cocoapods-search',      'cocoapods-search'
cp_gem 'cocoapods-stats',       'cocoapods-stats'
cp_gem 'cocoapods-trunk',       'cocoapods-trunk'
cp_gem 'cocoapods-try',         'cocoapods-try'
cp_gem 'molinillo',             'Molinillo'
cp_gem 'nanaimo',               'Nanaimo'
cp_gem 'xcodeproj',             'Xcodeproj'
```

**Comment by msand** [comment] 2019-02-21 01:31
Now pod install and adding rnsvg worked fine. Building to see that it all works out.

**Comment by msand** [comment] 2019-02-21 02:19
All kinds of issues with react-native still but probably because of bad integration from their side. Will look at it more when I have more time available.

**Closed** 2019-02-21 04:26 UTC
Labels: d1:easy, s2:confirmed, t2:defect
