### ISSUE TITLE
make warning for new build system

### ISSUE THREAD

**Issue by Speakus** [CocoaPods/CocoaPods#9056] opened 2019-07-30 13:22 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ Please replace these two lines with what you did.  
use Xcode 10+ (Xcode 10.3 for example)
pod install

## What did you expect to happen?

get warning if I use new build system and do not use solution from here:
https://github.com/CocoaPods/CocoaPods/issues/8073#issuecomment-493330597
So your script could check
variable `COMMAND_MODE=legacy` should be set or Podfile should contains:
`install! 'cocoapods', :disable_input_output_paths => true`
At least until Xcode 11 will be released

## What happened instead?

No warning - And I get surprises runtime.

## CocoaPods Environment

v.1.7.5 (latest now)

## Project that demonstrates the issue

not required cause we have confirmed and unfixed issue: https://github.com/CocoaPods/CocoaPods/issues/8073 which currently have only workaround

**Comment by dnkoutso** [comment] 2019-08-24 00:41
@Speakus see https://github.com/CocoaPods/CocoaPods/pull/9125

**Comment by Speakus** [comment] 2019-08-27 20:14
@dnkoutso 

> Updating this ticket to reflect current status since CocoaPods 1.8.0.beta.2 is released.

I'm sorry but changing title does not reflect what initially requested.

My title was "make warning for new build system".
The title about "USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES" is not the same cause the flag "USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES" affect only Xcode 11 builds while my project was used Xcode 10.3

Also I tried to change:
-			compatibilityVersion = "Xcode 10.0";
+			compatibilityVersion = "Xcode 8.0";

and run pod install but this changed nothing - the two folders are completely the same including Pods.xcodeproj also reset compatibility to `Xcode 10`... weird.

**Comment by Speakus** [comment] 2019-08-27 21:08
> The workaround in the other issue around disabling input output paths is currently the correct work around _or_ at the time of this comment use Xcode 11 Beta 6 with CocoaPods 1.8.0.beta.2 and _no_ xcfilelists.

Unfortunately I did not understand. You told Xcode version does not matter for cocoapod system...

> Workaround: Switch your .xcodeproj format to go < 9.3 Compatible and CocoaPods will not use xcfilelist and incremental compilation should work.

I tried this for both. For cocoapod 1.7.5 and 1.8.0.beta.2 also. So switching my `.xcodeproj` to 8.0 or even 3.2 compatibility does not change anything in project - cocoapods still uses xcfilelists. Also actually I do not understand what is the workaround expected to do. Allow to work properly with new build system?

**Comment by Speakus** [comment] 2019-09-03 20:02
1. There is way to detect which xcode supposed to use to build current project: https://github.com/fastlane/ci/blob/master/docs/xcode-version.md

2. I made new issue which you requested: https://github.com/CocoaPods/CocoaPods/issues/9140

**Comment by dnkoutso** [comment] 2019-09-03 20:11
`.xcode-version` is not supported by CocoaPods. It has been proposed but no RFC has been written.

**Comment by dnkoutso** [comment] 2019-09-03 20:11
Thanks for #9140. I continue to believe for this issue (#9056) we cannot do much.

**Comment by Speakus** [comment] 2019-09-03 21:06
imho it's not so big deal to support `.xcode-version` but even if not then cocoapod always could check `compatibilityVersion` is less than Xcode 11

**Comment by dnkoutso** [comment] 2019-09-03 21:19
This is more about the new build system though not so much about the Xcode version. The new build system was supported in Xcode 9 as optional and was made the default in Xcode 10. Users may still choose to use the legacy one even in Xcode 11.

We could parse a workspace settings file to see but I think its unnecessary to add this logic.

**Comment by Speakus** [comment] 2019-09-03 21:44
The main issue described here we could get runtime issues with new build system without any warnings.
the issue: https://github.com/CocoaPods/CocoaPods/issues/8073 was not really fixed but suggested workaroud is not applied by default. So the #9056 is about to allow anyone (who uses cocoapod) to know about some issue is here - at least by seeing the warning.
So it allow developer to select one possible solution:
1. switching to Xcode 11 and cocoapod 1.8.0.beta.2 (Inapplicable for Appstore builds at the moment) 
2. have workaround from #8073 `install! 'cocoapods', :disable_input_output_paths => true`
3. switch to legacy build system.

It's ok to select solution but hard to know the issue is there cause:
it's not reproduced for every build.
So warning from cocoapod could helps to many cocoapods clients.

**Comment by Speakus** [comment] 2019-12-25 20:23
this one was not resolved

**Comment by Speakus** [comment] 2020-05-26 01:02
this one was not resolved yet

**Comment by dnkoutso** [comment] 2020-06-22 19:41
Xcode 12 Beta 1 seems to be fixing the issue permenantly.

> When using USE_RECURSIVE_SCRIPT_INPUTS_IN_SCRIPT_PHASES with XCFileLists, the items within are now properly treated as recursive inputs. (54635196) (FB7109342)

We have not yet verified it but I will and if so I will close this issue.

**Comment by dnkoutso** [comment] 2020-06-22 21:23
Confirmed with project in https://github.com/CocoaPods/CocoaPods/issues/8073#issuecomment-418197075 that this is fixed in Xcode 12 Beta 1.

This is no longer needed.

**Closed by dnkoutso** 2020-06-22 21:23 UTC
Labels: help wanted, s7:workaround available
