### ISSUE TITLE
`user_target_xcconfig` doesn't merge build settings which accept multiple values with `inherit! :none` in share extension target

### ISSUE THREAD

**Issue by RishatShamsutdinov** [CocoaPods/CocoaPods#6569] opened 2017-03-18 06:37 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

`pod install`

## What did you expect to happen?

Share extension target has properly merged xconfig.

## What happened instead?

Share extension target xconfig missed `GCC_PREPROCESSOR_DEFINITIONS` from pods.

### Stack

```
   CocoaPods : 1.2.0
        Ruby : ruby 2.2.1p85 (2015-02-26 revision 49769) [x86_64-darwin14]
    RubyGems : 2.4.8
        Host : Mac OS X 10.12.3 (16D32)
       Xcode : 8.2 (8C38)
         Git : git version 2.10.1 (Apple Git-78)
Ruby lib dir : /Users/rishat/.rvm/rubies/ruby-2.2.1/lib
Repositories : brion - https://github.com/brion/OGVKit-Specs.git @ 374f4f37e1a4645b1513186bcd53ef016b599a9a
               master - https://github.com/CocoaPods/Specs.git @ 2d076ebccf59883d4fcf74d2f787062665507374
               tyrone-sudeium - https://github.com/tyrone-sudeium/xiph-ios-podspecs.git @ bf1a2e8070d9a5537b6bbe7ccdb1cfe269b0b438
```

### Installation Source

```
Executable Path: /Users/rishat/.rvm/gems/ruby-2.2.1/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.2
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
# platform :ios, '9.0'

target 'App' do
    pod 'PodA', :subspecs => ['Core'], :path => '../PodA'
    pod 'PodB', :subspecs => ['Core'], :path => '../PodB'
end

target 'Share' do
    inherit! :none

    pod 'PodA', :subspecs => ['Extra'], :path => '../PodA'
    pod 'PodB', :subspecs => ['Extra'], :path => '../PodB'
end
```

## Project that demonstrates the issue

https://github.com/RishatShamsutdinov/PodsXconfigMergeDemo

**Comment by dnkoutso** [comment] 2017-03-18 15:21
@RishatShamsutdinov does this work in 1.1.1 for example? We made a few changes in 1.2.0 (and even more fixes in 1.2.1.beta.1).

But I can take a look.

**Comment by dnkoutso** [comment] 2017-03-18 15:28
@RishatShamsutdinov nevermind most of the changes raound inherit search paths are done for pre-built static libraries or frameworks. This might be different, investigating.

**Comment by dnkoutso** [comment] 2017-03-18 15:55
@benasher44 do we expect to merge xcconfig pre_processor definitions and/or other stuff when the inheritance is set to `:none`?

**Comment by dnkoutso** [comment] 2017-03-18 16:03
Yeah definitely confirmed:

In `aggregate_xcconfig.rb`

```ruby
        def user_target_xcconfig_values_by_consumer_by_key
          pod_targets.each_with_object({}) do |target, hash|
            target.spec_consumers.each do |spec_consumer|
              spec_consumer.user_target_xcconfig.each do |k, v|
                (hash[k] ||= {})[spec_consumer] = v
              end
            end
          end
        end
```

The `pod_targets` method will ignore all pods with `inheritance` set to `:none`.

**Comment by dnkoutso** [comment] 2017-03-18 18:52
@RishatShamsutdinov, @segiddins @benasher44 depends on what the definition of `:none` is here this might be or might not be an issue.

If we expect that inheriting nothing also includes `user_target_xcconfig` then this is working as intended, otherwise if we believe the `user_target_xcconfig` *should* be merged regardless of what inherit mode we have then this is a bug. Fairly easy to fix too, I think.

**Comment by RishatShamsutdinov** [comment] 2017-03-18 18:55
```+ :none The target inherits none of the behaviour from the parent. ```

Pods are not parent, so I don't understand why it take effect for dependencies.

**Comment by dnkoutso** [comment] 2017-03-18 19:17
@RishatShamsutdinov yeah I am also leaning that this is a bug...

**Comment by benasher44** [comment] 2017-03-19 19:04
@dnkoutso this seems like a bug. `inherit` should only refer to inheriting pods/settings from parent targets. Targets that use this should still get settings from the pods declared specifically for their target.

**Closed** 2017-07-13 09:13 UTC
Labels: s1:awaiting input, s2:confirmed, t2:defect
