### ISSUE TITLE
Copy Pod resource error

### ISSUE THREAD

**Issue by FreudGit** [CocoaPods/CocoaPods#5082] opened 2016-03-24 19:56 UTC
Hi

I get error when compiling.

error: Resource "/Users/Francois/Library/Developer/Xcode/DerivedData/aaa-anttjkksjengtgfoimmmmimiwoxu/Build/Products/Debug-iphonesimulator/CZPhotoPickerController/CZPhotoPickerController.bundle" not found. Run 'pod install' to update the copy resources script.

As the issue was closed, i'm not sure if you will see that they are some user experiment a bug again in the 1.0.0 - pre 6 version

Here's the link
https://github.com/CocoaPods/CocoaPods/issues/3082

Sorry if this was not necessary.
 Have a great day!

**Comment by getaaron** [comment] 2016-03-28 23:03
Possibly related to https://github.com/CocoaPods/CocoaPods/commit/757c2bfd908d50126169af6592367cbf8409e4b1 or https://github.com/CocoaPods/CocoaPods/commit/56f8b22912dbe3182f3e08c28f8a81c7983b6a6e.

Is there a more reliable way to build these commands than long string interpolation, and trying to remember to escape everything properly?

**Comment by Iyuna** [comment] 2016-03-29 11:23
Have the same issue with all private pods as well as with HockeySDK.

**Comment by clintron** [comment] 2016-03-29 18:45
Ditto, beta 6.  People have suggested using HockeySDK-Source, but that hasn't solved the problem.

**Comment by pronebird** [comment] 2016-03-29 19:15
Same here, any workaround for that?

**Comment by vstepanyuk** [comment] 2016-03-29 22:07
error: /Users/vitaliy/Library/Developer/Xcode/DerivedData/DiabCalc-fhiolaegwdjdpifbjiexrejrjacz/Build/Products/Debug-iphonesimulator/SOTProgressHUD/SOTProgressHUDAssets.bundle: No such file or directory

**Comment by dral3x** [comment] 2016-03-30 08:16
I fixed the problem by removing the override on the "Per-configuration Build Product Path" setting in the Pods project resource bundle.

**Comment by ngutman** [comment] 2016-03-30 14:31
Might be related to #4954

**Comment by segiddins** [comment] 2016-04-01 01:09
Duplicate of https://github.com/CocoaPods/CocoaPods/issues/5034.

**Closed by segiddins** 2016-04-01 01:09 UTC
