### ISSUE TITLE
TypeError - no implicit conversion of nil into String ( CocoaPods : 1.0.1)

### ISSUE THREAD

**Issue by leeaken** [CocoaPods/CocoaPods#6103] opened 2016-10-29 04:18 UTC
I want to make a private cocopods library,here is my private library:

https://git.coding.net/leeaken/MXNetworkSpec.git
https://git.coding.net/leeaken/MXNetwork.git

```
/Users/aken/.rvm/rubies/ruby-2.2.4/bin/pod install --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.2.4p230 (2015-12-16 revision 53155) [x86_64-darwin15]
    RubyGems : 2.4.8
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.7.4 (Apple Git-66)
Ruby lib dir : /Users/aken/.rvm/rubies/ruby-2.2.4/lib
Repositories : agdsdl - https://github.com/agdsdl/Specs.git @ 8f487be6bb89793e17f0b8e1f286e5e709d1c050
               coding-leeaken-mxnetwork - https://git.coding.net/leeaken/MXNetwork.git @ d9b48fbd28cbffd94958246347828a9e5e721e24
               eyeem - https://github.com/eyeem/CocoaPods-Specs.git @ 4bd304d1eb6db2e12faf085700e40ff07f12e676
               master - https://github.com/CocoaPods/Specs.git @ 3473dd24772ee0c403b38ca8b875379dfbd37ae2
               MXNet - https://git.coding.net/leeaken/MXNetworkSpec.git @ 0ad08de5601440c59de41d32a172b43228f973b5
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
```

### Podfile

```ruby
platform :ios, '8.0'

project 'Test.xcodeproj'

source 'https://git.coding.net/leeaken/MXNetwork.git'
source 'https://github.com/CocoaPods/Specs.git'

use_frameworks!
inhibit_all_warnings!





target 'Test' do
  pod 'MXNetwork', '0.1.0'
end
```

### Error

```
TypeError - no implicit conversion of nil into String
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification.rb:523:in `initialize'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification.rb:523:in `new'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification.rb:523:in `from_file'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/specification/set.rb:45:in `specification'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source.rb:268:in `search'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `block in search'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `select'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-core-1.0.1/lib/cocoapods-core/source/aggregate.rb:83:in `search'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:346:in `create_set_from_sources'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:316:in `find_cached_set'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:289:in `specifications_for_dependency'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:107:in `search_for'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:205:in `block in sort_dependencies'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `each'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `sort_by'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:199:in `sort_dependencies'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:131:in `block (2 levels) in <class:Resolution>'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:174:in `initial_state'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:100:in `start_resolution'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.4.5/lib/molinillo/resolution.rb:63:in `resolve'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/molinillo-0.4.5/lib/molinillo/resolver.rb:42:in `resolve'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/resolver.rb:62:in `resolve'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:563:in `block in resolve_dependencies'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:561:in `resolve_dependencies'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/installer/analyzer.rb:76:in `analyze'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:227:in `analyze'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:151:in `block in resolve_dependencies'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/user_interface.rb:63:in `section'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:150:in `resolve_dependencies'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/installer.rb:114:in `install!'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/command/install.rb:37:in `run'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/lib/cocoapods/command.rb:50:in `run'
/Users/aken/.rvm/gems/ruby-2.2.4@global/gems/cocoapods-1.0.1/bin/pod:55:in `<top (required)>'
/Users/aken/.rvm/rubies/ruby-2.2.4/bin/pod:23:in `load'
/Users/aken/.rvm/rubies/ruby-2.2.4/bin/pod:23:in `<main>'
/Users/aken/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `eval'
/Users/aken/.rvm/gems/ruby-2.2.4@global/bin/ruby_executable_hooks:15:in `<main>'

**Comment by dnkoutso** [comment] 2016-10-29 05:56
probably something wrong with the podspec you've published. Can you paste its contents?

**Comment by leeaken** [comment] 2016-10-29 08:19
@dnkoutso  hi,do you mean the  MXNetworkSpec.git is wrong ?

Here is my  podspec

Pod::Spec.new do |s|
  s.name         = "MXNetwork"
  s.version      = "0.1.0"
  s.summary      = "MXNetwork 是一个网络组件库"
  s.homepage     = "https://git.coding.net/leeaken/MXNetwork.git"
  #s.license      = "MIT"
  s.license       = { :type => "MIT", :file => "LICENSE" }
  s.author             = { "li.tiankun" => "li.tiankun@163.com" }
  s.ios.deployment_target = "7.0"
  s.requires_arc = true
  s.source       = { :git => "https://git.coding.net/leeaken/MXNetwork.git", :tag => s.version.to_s }
  
  s.source_files  = "MXNetwork/*.{h,m}"
  #s.exclude_files = 'MXNetwork/Vender'
  s.framework = "CFNetwork"
  s.dependency "AFNetworking", "~> 3.0"
end

**Comment by leeaken** [comment] 2016-10-29 11:03
I also push private spec to github,here it is
https://github.com/leeaken/MXNetworkSpec

**Comment by dnkoutso** [comment] 2016-10-29 15:45
@leeaken I cannot reproduce. I tried Ruby 2.2.4 but i was successfully able to consume your pod in a sample app...this is the line it fails at https://github.com/CocoaPods/Core/blob/master/lib/cocoapods-core/specification.rb#L523

**Comment by DanToml** [comment] 2016-10-29 17:05
@leeaken this looks like a duplicate of https://github.com/CocoaPods/CocoaPods/issues/5184. Could you try running `rm -rf ~/.cocoapods/repos/master` and `pod setup`?

**Comment by leeaken** [comment] 2016-10-30 06:43
Hi,@dnkoutso @DanToml  thanks very much!
I fix my Podfile config, and rm -rf ~/.cocoapods/repos/master, and pod setup,then i solve my issue. my  Podfile looks like this:

platform :ios, '8.0'

project 'Test.xcodeproj'

source 'https://git.coding.net/leeaken/MXNetworkSpec.git'
source 'https://github.com/CocoaPods/Specs.git'  
   
platform :ios, "7.0"  
   
target "Test" do    
 pod 'MXNetwork', '~> 0.1.0'
end

I will close the issue! Thanks.

**Closed** 2016-10-30 06:44 UTC
