### ISSUE TITLE
Error (Xcode): DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead

### ISSUE THREAD

**Issue by joselcv** [CocoaPods/CocoaPods#12061] opened 2023-09-19 16:01 UTC
After updating to the latest versions of ios and xcode, it started showing this error: 

Firebase-IOS14.0
DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead

Firebase-IOS16.4
DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead

**Comment by BC-M** [comment] 2023-09-19 16:31
Is fixed by the next release. Look at [this comment](https://github.com/CocoaPods/CocoaPods/issues/12048#issuecomment-1722501282) for a workaround. Also please close this issue, because it’s a duplicate and the issue is already known.

**Closed as completed** 2023-09-19 17:01 UTC

**Comment by joselcv** [comment] 2023-09-19 17:03
I already tried that solution and in the final part this appears:

RubyGem built successfully
  Name: cocoapods
  Version: 1.12.1
  File: cocoapods-1.12.1.gem

Then I try to run my app and the previous error still appears

**Comment by laTruffe79** [comment] 2023-09-19 17:10
Hello, same error...
