### ISSUE TITLE
Xcode 15 and iOS 17 - Error: DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead

### ISSUE THREAD

**Issue by paulocoutinhox** [CocoaPods/CocoaPods#12065] opened 2023-09-20 20:55 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Run my application on Version 15.0 (15A240d) and iOS 17:

<img width="996" alt="image" src="https://github.com/CocoaPods/CocoaPods/assets/395096/28626f85-6fed-46b3-b127-3a63bc1eb6cb">

## What did you expect to happen?

Compile

## What happened instead?

Error:

```
error: DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead (in target 'Firebase' from project 'Pods')
```

### Stack

```
   CocoaPods : 1.12.1
        Ruby : ruby 3.2.2 (2023-03-30 revision e51014f9c0) [arm64-darwin22]
    RubyGems : 3.4.10
        Host : macOS 13.5.2 (22G91)
       Xcode : 15.0 (15A240d)
         Git : git version 2.39.3 (Apple Git-145)
Ruby lib dir : /opt/homebrew/Cellar/ruby/3.2.2_1/lib
Repositories : cocoapods - git - https://github.com/CocoaPods/Specs.git @ 61b4abee484d2d3a805bef132548edfdba90de1d
```

### Installation Source

```
Executable Path: /opt/homebrew/Cellar/cocoapods/1.12.1/libexec/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.5
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.1
cocoapods-trunk       : 1.6.0
cocoapods-try         : 1.2.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'

# variables
IOS_PLATFORM = '13.0'

# settings
platform :ios, IOS_PLATFORM
inhibit_all_warnings!
use_frameworks!

# dependencies
def shared_pods
  pod 'Firebase/Crashlytics', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '10.5.0'
  pod 'Firebase/Messaging', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '10.5.0'
  pod 'Firebase/InAppMessaging', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '10.5.0'
  pod 'Firebase/RemoteConfig', :git => 'https://github.com/firebase/firebase-ios-sdk.git', :tag => '10.5.0'
end

# targets
target 'ubook' do
  shared_pods
end

# post install
post_install do |installer|
  # ios deployment version
  installer.pods_project.targets.each do |t|
    t.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = IOS_PLATFORM
    end
  end

  # fix for xcode14 codesign for dependencies - remove after fix oficially
  installer.pods_project.targets.each do |target|
    if target.respond_to?(:product_type) and target.product_type == "com.apple.product-type.bundle"
      target.build_configurations.each do |config|
          config.build_settings['CODE_SIGNING_ALLOWED'] = 'NO'
      end
    end
  end
end
```

**Comment by orta** [comment] 2023-09-20 21:26
Effectively a dupe of https://github.com/CocoaPods/CocoaPods/issues/12048 - I'd watch that one

**Comment by skywalkerlw** [comment] 2023-09-20 21:50
can we release a new version of cocoapod since Xcode 15 is officially released

**Comment by ccomsi** [comment] 2023-09-21 01:20
Xcode 15 has been officially released, and I think it's time to release CocoaPods 13.0

**Comment by patrickjquinn** [comment] 2023-09-21 17:58
Yeah I need to support iOS 17 with my app and this issue is effectively blocking me from building against Xcode 15, any changes we can get CP 13 out the door sometime soon?

**Comment by paulocoutinhox** [comment] 2023-09-21 18:00
This help me for now and it it building until new release:

```
# post install
post_install do |installer|
  # fix xcode 15 DT_TOOLCHAIN_DIR - remove after fix oficially - https://github.com/CocoaPods/CocoaPods/issues/12065
  installer.aggregate_targets.each do |target|
      target.xcconfigs.each do |variant, xcconfig|
      xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
      IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
  end

  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
          xcconfig_path = config.base_configuration_reference.real_path
          IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
      end
    end
  end
end
```

**Comment by ninhgeocomply** [comment] 2023-09-22 03:48
Same for me, I remember this bug that has been raised for a long time. I tried to find a new build. Unfortunately, we don't have any new builds when the Xcode 15 has an automatic update on my Mac.

**Comment by rashadatjou** [comment] 2023-09-22 07:35
@paulocoutinhox is there maybe a fix for `.podspec` files as well? I am trying to release 2 CocoaPods but I am not able to do it because of this error... 😭

**Comment by rashadatjou** [comment] 2023-09-22 07:40
I am unfortunately tied to release these dependencies using _Xcode_ `15.0` due to personal constraints on my machine for anyone else you should use _Xcode_ `14.3.1` to release your CocoaPods and wait until this fix gets patched.

**Comment by anushshenoy** [comment] 2023-09-22 19:52
https://github.com/CocoaPods/CocoaPods/issues/12048#issuecomment-1731950712

**Comment by dnkoutso** [comment] 2023-09-23 02:14
1.13.0 shipped with the fix.

**Closed by dnkoutso** 2023-09-23 02:14 UTC

**Comment by fangyuxi** [comment] 2023-09-23 02:20
But, can't install 1.13.0 now, can't find it on brew, should I wait?

**Comment by dnkoutso** [comment] 2023-09-23 02:21
We do not manage brew releases. We publish to rubygems.

**Comment by prinkeeras** [comment] 2023-09-23 04:53
even with the latest version issue still persist...

**Comment by fangyuxi** [comment] 2023-09-23 04:57
New error:

Framework 'uv' not found

**Comment by tdermaris** [comment] 2023-09-23 06:39
The error is still here..

**Comment by engrkhalid** [comment] 2023-09-24 10:03
I just install the new version but I guess, it is pointing out to previous version of cocoapods!

gem which cocoapods
/Library/Ruby/Gems/2.6.0/gems/cocoapods-1.13.0/lib/cocoapods.rb

pod --version
1.12.1


What can I do?

**Comment by engrkhalid** [comment] 2023-09-24 11:08
I found the solution 😃
I have to use Homebrew:

`brew upgrade cocoapods`

`pod --version         
1.13.0
`

It's working now 👍

**Comment by for-dev9** [comment] 2023-09-24 20:57
For anyone who still error after upgrade cocoapods to 1.13
- delete exists Pods folder and Podfile at ios folder
- run your app again

**Comment by Tantu194** [comment] 2023-09-25 02:52
> For anyone who still error after upgrade cocoapods to 1.13
> 
> * delete exists Pods folder and Podfile at ios folder
> * run your app again

Thanks @for-dev9 for
It's a good solution, Awesome!!!

**Comment by arindamkb** [comment] 2023-09-25 07:27
Use this instead
```
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
  end
end

**Comment by arindamxd** [comment] 2023-09-25 07:29
Use this instead
```
post_install do |installer|
  installer.generated_projects.each do |project|
    project.targets.each do |target|
      target.build_configurations.each do |config|
        config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
        xcconfig_path = config.base_configuration_reference.real_path
        xcconfig = File.read(xcconfig_path)
        xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
        File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
      end
    end
  end
end

**Comment by leononly** [comment] 2023-09-25 07:33
> For anyone who still error after upgrade cocoapods to 1.13
> 
> * delete exists Pods folder and Podfile at ios folder
> * run your app again

this work for me as well

**Comment by vivekTusiyd** [comment] 2023-09-25 09:37
Still facing the issue but this helped:

`post_install do |installer|

	installer.pods_project.targets.each do |target|
		target.build_configurations.each do |config|
			# For xcode 15+ only
			if config.base_configuration_reference && Integer(xcode_base_version) >= 15
				xcconfig_path = config.base_configuration_reference.real_path
				xcconfig = File.read(xcconfig_path)
				xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
				File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
			end
		end
	end
end`

**Comment by arindamkb** [comment] 2023-09-25 10:08
> Facing the issue after above code but this helped:
> 
> `post_install do |installer| installer.pods_project.targets.each do |target| target.build_configurations.each do |config| # For xcode 15+ only if config.base_configuration_reference && Integer(xcode_base_version) >= 15 xcconfig_path = config.base_configuration_reference.real_path xcconfig = File.read(xcconfig_path) xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR") File.open(xcconfig_path, "w") { |file| file << xcconfig_mod } end end end end`

This is not required anymore, fixed in Cocapods 1.13.0
use `brew upgrade cocoapods`
and add below in Podfile
```
# post install
post_install do |installer|
  # ios deployment version
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '<your_target_version>'
    end
  end
end
```

**Comment by arindamxd** [comment] 2023-09-25 10:09
> Facing the issue after above code but this helped:
> 
> `post_install do |installer| installer.pods_project.targets.each do |target| target.build_configurations.each do |config| # For xcode 15+ only if config.base_configuration_reference && Integer(xcode_base_version) >= 15 xcconfig_path = config.base_configuration_reference.real_path xcconfig = File.read(xcconfig_path) xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR") File.open(xcconfig_path, "w") { |file| file << xcconfig_mod } end end end end`

This is not required anymore, fixed in Cocapods 1.13.0
use `brew upgrade cocoapods`
and add below in Podfile
```
# post install
post_install do |installer|
  # ios deployment version
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '<your_target_version>'
    end
  end
end
```
then `pod install`

**Comment by lewinmuzvonda** [comment] 2023-09-26 11:17
> This help me for now and it it building until new release:
> 
> ```
> # post install
> post_install do |installer|
>   # fix xcode 15 DT_TOOLCHAIN_DIR - remove after fix oficially - https://github.com/CocoaPods/CocoaPods/issues/12065
>   installer.aggregate_targets.each do |target|
>       target.xcconfigs.each do |variant, xcconfig|
>       xcconfig_path = target.client_root + target.xcconfig_relative_path(variant)
>       IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
>       end
>   end
> 
>   installer.pods_project.targets.each do |target|
>     target.build_configurations.each do |config|
>       if config.base_configuration_reference.is_a? Xcodeproj::Project::Object::PBXFileReference
>           xcconfig_path = config.base_configuration_reference.real_path
>           IO.write(xcconfig_path, IO.read(xcconfig_path).gsub("DT_TOOLCHAIN_DIR", "TOOLCHAIN_DIR"))
>       end
>     end
>   end
> end
> ```

Worked well, thanks!

**Comment by vnl** [comment] 2023-09-26 19:56
> ### **SOLUTION✅:**
> For all the users who :-
> 
> * Have _no preference_ for XCode version : **Simply downgrade your XCode version to 14.x.x**
> * Have _preference for XCode 15_ : **Use commands:-**
> 
> 1. `brew upgrade cocoapods`
> 2. Delete Pod directory in your App(if present)
> 3. `pod install`
> 4. Done🚀

I am just modifying a bit for those who did not install cocoapods using brew. `gem update cocoapods`

**Comment by bnikolaev1993** [comment] 2023-09-26 20:09
> ### **SOLUTION✅:**
> For all the users who :-
> 
> * Have _no preference_ for XCode version : **Simply downgrade your XCode version to 14.x.x**
> * Have _preference for XCode 15_ : **Use commands:-**
> 
> 1. `brew upgrade cocoapods`
> 2. Delete Pod directory in your App(if present)
> 3. `pod install`
> 4. Done🚀

In case you have several Xcode versions install, check if Xcode 15 is default `xcode-select --print-path` and make it default in case `sudo xcode-select -s /Applications/Xcode.app`

**Comment by hamzakocinkag** [comment] 2023-09-27 13:54
`sudo gem update cocoapods`
`pod install`

**Comment by Sayum24** [comment] 2023-09-27 14:30
The error was for Firebase:
`DT_TOOLCHAIN_DIR cannot be used to evaluate LIBRARY_SEARCH_PATHS, use TOOLCHAIN_DIR instead`
It worked for me after I updated the pods.
`pod update`

**Comment by jogendra-zokudo** [comment] 2023-09-29 06:06
> I found the solution 😃 I have to use Homebrew:
> 
> `brew upgrade cocoapods`
> 
> `pod --version -> 1.13.0 `
> 
> It's updated now 👍 But, my app need this before it works: [pichillilorenzo/flutter_inappwebview#1735 (comment)](https://github.com/pichillilorenzo/flutter_inappwebview/issues/1735#issuecomment-1728169566)

Thanks mate it's working now

**Comment by isshort** [comment] 2023-10-09 14:20
> Use this instead
> 
> ```
> post_install do |installer|
>   installer.generated_projects.each do |project|
>     project.targets.each do |target|
>       target.build_configurations.each do |config|
>         config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = '12.1'
>         xcconfig_path = config.base_configuration_reference.real_path
>         xcconfig = File.read(xcconfig_path)
>         xcconfig_mod = xcconfig.gsub(/DT_TOOLCHAIN_DIR/, "TOOLCHAIN_DIR")
>         File.open(xcconfig_path, "w") { |file| file << xcconfig_mod }
>       end
>     end
>   end
> end
> ```
> 
> $ pod repo update $ pod install

This one worked for me
