### ISSUE TITLE
Issue increasing pod version while developing library

### ISSUE THREAD

**Issue by mwaterfall** [CocoaPods/CocoaPods#3780] opened 2015-07-05 16:57 UTC
When using the default pod template to create a library, if you update the version of your podspec and then need to run `pod install`, you get mismatch issues with the lock file:

```
[!] Unable to satisfy the following requirements:

- `MyLib (from `../`)` required by `Podfile`
- `MyLib (from `../`)` required by `Podfile`
- `MyLib (= 0.1.0)` required by `Podfile.lock`
```

So you are required to wipe the pods dir and the lock file (or edit the lock file — although I'm sure this isn't recommended) if you want to ever run `pod install` after changing the version.

What is the recommended solution to this problem?

**Comment by orta** [comment] 2015-07-05 16:59
Dupe of https://github.com/CocoaPods/CocoaPods/issues/3764

For now I'd recommend running `pod update [podname]` to get around it

**Closed by orta** 2015-07-05 16:59 UTC
