### ISSUE TITLE
1.0.0 beta 7 NameError - uninitialized constant Pod::Command::Trunk::Push::SourcesManager

### ISSUE THREAD

**Issue by iulukaya** [CocoaPods/CocoaPods#5161] opened 2016-04-15 16:36 UTC
> ℹ Please fill out this template when filing an issue.
> All lines beginning with a quotation mark (`>`),
> instruct you with what info we expect.  
> Please remove this paragraph.

* [x ] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod trunk push

### Error

```
NameError - uninitialized constant Pod::Command::Trunk::Push::SourcesManager
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0.beta.3/lib/pod/command/trunk/push.rb:114:in `update_master_repo'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-trunk-1.0.0.beta.3/lib/pod/command/trunk/push.rb:58:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.3/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.7/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.7/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'

```
   CocoaPods : 1.0.0.beta.7
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.4 (15E65)
       Xcode : 7.3 (7D175)
         Git : git version 2.7.4
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib

**Comment by iulukaya** [comment] 2016-04-15 16:43
### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.2
cocoapods-stats       : 1.0.0.beta.4
cocoapods-trunk       : 1.0.0.beta.3
cocoapods-try         : 1.0.0.beta.3
```

**Comment by segiddins** [comment] 2016-04-15 17:18
Duplicate of https://github.com/CocoaPods/cocoapods-trunk/issues/61.

**Closed by segiddins** 2016-04-15 17:18 UTC
