### ISSUE TITLE
Errno::EEXIST - File exists - .../Pods/Target Support Files/AWSCore

### ISSUE THREAD

**Issue by cbrandsma-cs** [CocoaPods/CocoaPods#5870] opened 2016-09-14 15:27 UTC
* [ x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Ran `pod install`  with `pod AWSS3` listed as a dependancy.

After trying the first time, I deleted the folder /AWSCore and reran `pod install`, but the same error came right back.

## What did you expect to happen?

Expected no errors 

### Error

```
Errno::EEXIST - File exists - /Users/cbrandsma/git/connect-iphone/connect/Pods/Target Support Files/AWSCore
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `mkdir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:92:in `create_support_files_dir'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:21:in `block in install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb:19:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:155:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:153:in `block in install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:152:in `install_libraries'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer/xcode/pods_project_generator.rb:64:in `generate!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:179:in `block in generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:178:in `generate_pods_project'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/installer.rb:115:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command/install.rb:37:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/command.rb:50:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.1.0.rc.2/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

### Stack

```
   CocoaPods : 1.1.0.rc.2
        Ruby : ruby 2.0.0p648 (2015-12-16 revision 53162) [universal.x86_64-darwin15]
    RubyGems : 2.0.14.1
        Host : Mac OS X 10.11.6 (15G1004)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 54b46b9fac905ef8e117280ac842f433ce1f3b70
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, "10.0"
use_frameworks!

target 'MyApp1' do
    pod 'Alamofire'
    pod 'Locksmith'
    pod 'Localytics'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'CocoaLumberjack'
    pod 'AWSS3'
    pod 'MBProgressHUD'
    pod 'WZLBadge'
    pod 'IQKeyboardManagerSwift'
    pod 'RSKImageCropper'
    pod 'RESideMenu'
    pod 'CRToast'
    pod 'RazzleDazzle'
    pod 'FiksuSDK'
    pod 'XWebView'

end

target 'MyApp1Tests' do
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'AWSS3'
    pod 'WZLBadge'
    pod 'CRToast'

end

target 'MyApp2' do
    pod 'Alamofire'
    pod 'Locksmith'
    pod 'Localytics'
    pod 'Fabric'
    pod 'Crashlytics'
    pod 'CocoaLumberjack'
    pod 'AWSS3'
    pod 'MBProgressHUD'
    pod 'WZLBadge'
    pod 'IQKeyboardManagerSwift'
    pod 'RSKImageCropper'
    pod 'RESideMenu'
    pod 'CRToast'
    pod 'RazzleDazzle'
    pod 'FiksuSDK'
    pod 'XWebView'

end
```

**Comment by DanToml** [comment] 2016-09-14 15:43
closing this as a duplicate of #5864

**Closed by DanToml** 2016-09-14 15:43 UTC

**Comment by cbrandsma-cs** [comment] 2016-09-14 15:46
Thank you.
