### ISSUE TITLE
Can't find my pod on CocoaPods.org or use pod search

### ISSUE THREAD

**Issue by pgbo** [CocoaPods/CocoaPods#9381] opened 2019-12-03 04:03 UTC
Several days ago I upload my pod to cocoapods, and I can see this output in Terminal. however, I still can't find my pod on CocoaPods.org or use pod search now. 

![image](https://user-images.githubusercontent.com/4122686/70019514-7a6da200-15c4-11ea-80f3-8554aba3720e.png)

What's the problem?

**Comment by dnkoutso** [comment] 2019-12-03 16:12
This is a known issue with our search indexer for a while that is broken. New pods are not showing up in search.

Duplicate of https://github.com/CocoaPods/CocoaPods/issues/9366

**Closed by dnkoutso** 2019-12-03 16:12 UTC
