### ISSUE TITLE
Can't see download counts, install counts of my repo

### ISSUE THREAD

**Issue by lingol** [CocoaPods/CocoaPods#8363] opened 2018-12-17 09:31 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have a [repo](https://cocoapods.org/pods/MMKV) published for over 3 months. With a full readme, license, wiki and stuff. And get over [5.7k stars](https://github.com/Tencent/mmkv) on GitHub.

## What did you expect to happen?

Download counts, install counts should be non-trivial.

## What happened instead?

Yet I can't see those counts on [CocoaPods](https://cocoapods.org/pods/MMKV). And the GitHub data like stars and forks are wrong too.

### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.2 (18C54)
       Xcode : 10.1 (10B61)
         Git : git version 2.17.1
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 747d63e2cc2b578ac6e6a499071f6c02f69473da
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

**Comment by amorde** [comment] 2018-12-19 05:17
Hi @lingol, I think this is a duplicate of https://github.com/CocoaPods/metrics.cocoapods.org/issues/45 - this has been an issue for quite a while but no one has been able to take the time to look into it further.

I'm going to close this but please let me know if you believe this issue is different 👍

**Comment by amorde** [comment] 2018-12-19 05:18
If you have time to look into it, PRs to that repo would be very welcome!

**Closed by amorde** 2018-12-19 05:17 UTC
