### ISSUE TITLE
Bad Podfile, no workspace created when using pod lib create without example project

### ISSUE THREAD

**Issue by letvargo** [CocoaPods/CocoaPods#5171] opened 2016-04-18 10:48 UTC
* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Using Cocopods version `0.39.0`, I ran...

    pod lib create MyPod

...and answered the setup questions like this:

    What language do you want to use?? [ Swift / ObjC ]
     > Swift

    Would you like to include a demo application with your library? [ Yes / No ]
     > No

    Which testing frameworks will you use? [ Quick / None ]
     > None

    Would you like to do view based testing? [ Yes / No ]
     > No

(Basically, I'm using `pod lib create MyPod` to create a new development pod and I don't want a demo project and I'm only using `XCTest` for testing.)

## What did you expected to happen?

Initialize a new CocoaPod template directory that would include a workspace under the `Example` directory that would include a project that could be used for testing, but not as an Example Project.

## What happened instead?

After answering the install questions, I got the following error message:

    [!] Invalid `Podfile` file: syntax error, unexpected end-of-input, expecting keyword_end. Updating CocoaPods might fix the issue.

     #  from /path/to/MyPod/Example/Podfile:8
     #  -------------------------------------------
     #    
     >  end
     #  -------------------------------------------

It appears that the script for generating the new podfile generated an invalid podfile, which prevents the automatic creation of a workspace in the `Example` directory. The podfile that is generated is included below. It includes a target, `MyPod_Example`, with no `end` tag which may be what is producing the error.

Note that everything else in the library is created correctly, but there is no workspace. I can generate a workspace manually by editing the podfile and removing the `target MyPod_Example...` line.

## Podfile

```ruby
    use_frameworks!

    target 'MyPod_Example', :exclusive => true do
    target 'MyPod_Tests', :exclusive => true do
      pod 'MyPod', :path => '../'
    end
```

**Comment by orta** [comment] 2016-04-18 10:48
This is a dupe of #5170 - though it has more information, so should probably be the canonical answer

**Comment by orta** [comment] 2016-04-18 10:51
Fixed by https://github.com/CocoaPods/pod-template/pull/159

**Closed by orta** 2016-04-18 10:51 UTC

**Comment by letvargo** [comment] 2016-04-18 10:56
Wow, amazingly fast fix. How can I apply this fix to my Cocoapods installation?

**Comment by orta** [comment] 2016-04-18 10:56
It happens by default, running `pod lib create` will use the new version straight away 👍

**Comment by joaonascimentto** [comment] 2016-09-21 11:43
Hey guys, I'm having the exact same issue with pod lib create, now workspace is created. Did you manage to fix it @letvargo?
