### ISSUE TITLE
Xcode build fails after upgrade to cocoa pods 1.0.1

### ISSUE THREAD

**Issue by PrasadUmmadisetty** [CocoaPods/CocoaPods#5703] opened 2016-08-02 14:30 UTC
Hi Team

I have one iOS project in objective-c with cocoa pods 0.39.0 version in one machine. My Xcode build is success and generating .ipa file after pod install.
now i installed to cocoa pods 1.0.1 in another machine and trying to build the existing project. The same project which is executed with 0.39.0 now getting "xxx duplicate symbol "error and not able to resolve.
error:  ld: 388 duplicate symbols for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)

Please help me to resolve this issue.

**Comment by samjohn** [comment] 2016-08-02 19:20
I have the same issue: https://github.com/CocoaPods/CocoaPods/issues/5696
It's related to specific pods that have static binaries and using frameworks in your project. 

It seems like there might be a workaround but I have not figured it out yet. I am planning to open another issue to add the workaround to the docs since I think this is a common use-case.

**Comment by neonichu** [comment] 2016-08-04 17:08
Closing as a dupe of #5699, then.

**Closed by neonichu** 2016-08-04 17:08 UTC
