### ISSUE TITLE
Errno::EINVAL - Invalid argument @ io_fread framework. x.framework/x is more then 2G

### ISSUE THREAD

**Issue by linhuaibai** [CocoaPods/CocoaPods#8556] opened 2019-02-25 03:25 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

ℹ  `pod install --verbose --no-repo-update`

## What did you expect to happen?

ℹInstall all pod dependencies correctly.

## What happened instead?

ℹ x.framework/x is more then 2G. What does that have to do with it ?
### Error

```
Errno::EINVAL - Invalid argument @ io_fread - /Users/linkunfa/worklibs/toB/M+/iOS_Unity2Build/libMTlabKit/iOS/MTlabKit.framework/MTlabKit
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.2.0/lib/macho/fat_file.rb:62:in `read'
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.2.0/lib/macho/fat_file.rb:62:in `open'
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.2.0/lib/macho/fat_file.rb:62:in `initialize'
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.2.0/lib/macho.rb:31:in `new'
/Library/Ruby/Gems/2.3.0/gems/ruby-macho-1.2.0/lib/macho.rb:31:in `open'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:431:in `dynamic_binary?'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:164:in `block in vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:163:in `select'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:163:in `vendored_dynamic_frameworks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/sandbox/file_accessor.rb:172:in `vendored_static_frameworks'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:122:in `add_static_dependency_build_settings'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:89:in `block in add_settings_for_file_accessors_of_target'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:86:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:86:in `add_settings_for_file_accessors_of_target'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:424:in `block in generate_vendored_build_settings'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:422:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/xcconfig_helper.rb:422:in `generate_vendored_build_settings'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:79:in `generate'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/generator/xcconfig/aggregate_xcconfig.rb:39:in `save_as'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb:107:in `update_changed_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:96:in `block in create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:93:in `create_xcconfig_file'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:18:in `block in install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator/aggregate_target_installer.rb:14:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:181:in `block (2 levels) in install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `each'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:179:in `block in install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:142:in `message'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:167:in `install_libraries'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer/xcode/pods_project_generator.rb:65:in `generate!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:184:in `block in generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/user_interface.rb:64:in `section'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:183:in `generate_pods_project'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/installer.rb:119:in `install!'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command/install.rb:41:in `run'
/Library/Ruby/Gems/2.3.0/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/lib/cocoapods/command.rb:52:in `run'
/Library/Ruby/Gems/2.3.0/gems/cocoapods-1.5.3/bin/pod:55:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by dnkoutso** [comment] 2019-02-25 17:43
There is insufficient information to debug this issue. Please provide more details and a sample app that reproduces. Closing and can re-open with more info.

**Closed by dnkoutso** 2019-02-25 17:43 UTC

**Comment by axxeny** [comment] 2020-04-03 10:49
The source of the problem looks like this: ruby-macho is trying to read the whole Mach-O binary into memory, which fails if the binary is over around 2 GiB. This has not been fixed yet. See another issue, ruby-macho's author has commented there: https://github.com/CocoaPods/CocoaPods/issues/8786#issuecomment-588043215

**Comment by amorde** [comment] 2020-04-03 22:11
Ah yep, looks like it. `ruby-macho` maintainer is open to contributions if you're interesting in helping to fix it :)
