### ISSUE TITLE
cannot archive and submit app in 0.39.0.beta.4

### ISSUE THREAD

**Issue by kraag22** [CocoaPods/CocoaPods#4174] opened 2015-09-13 13:28 UTC
When I deleted my pods directory and did pod install, I couldn't archive my app any more. It was in "Other items" and not "iOS apps" in onganizer. Maybe it is something similar to this issue "https://github.com/CocoaPods/CocoaPods/pull/3898"

When I downgraded to 0.38.2 everything was OK.

I used xcode 7 GM

**Comment by segiddins** [comment] 2015-09-13 14:30
This is a know issue with beta 4.

**Comment by neonichu** [comment] 2015-09-13 21:35
Dupe of #4119

**Closed by neonichu** 2015-09-13 21:35 UTC

**Comment by georgbachmann** [comment] 2015-09-17 20:27
I am having the same issue but also with 0.38.2
Is there a way to fix the problem? I need to submit an update to an app but can't :(
Any help is so much appreciated!!!
