### ISSUE TITLE
pod install adds Debug and Release configurations even though my project is using different naming for these

### ISSUE THREAD

**Issue by MANassar** [CocoaPods/CocoaPods#7813] opened 2018-06-05 10:43 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have 3 build configurations in my project: Development, Production and Enterprise. When I perform a 'pod install', the Pods project has these aforementioned configs + Debug and Release configs. Which confuse Xcode and cause it to fail the build until they are deleted

Moreover, in the podfile, I added:
`project 'My project', 'Development' => :debug, 'Production' => :release, 'Enterprise' => :release`

## What did you expect to happen?

I expect to have only the 3 build configurations I configured

## What happened instead?

I had 5 build configs, Debug, Release + the 3 I defined

## CocoaPods Environment

`
### Stack

```
   CocoaPods : 1.5.3
        Ruby : ruby 2.3.3p222 (2016-11-21 revision 56859) [universal.x86_64-darwin17]
    RubyGems : 2.5.2
        Host : Mac OS X 10.13.3 (17D102)
       Xcode : 9.3.1 (9E501)
         Git : git version 2.15.1 (Apple Git-101)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 4be2bd5ade7d67f129a4ebd168f22f1a05181c15
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
platform :ios, '8.0'
use_frameworks!

project 'My project', 'Development' => :debug, 'Production' => :release, 'Enterprise' => :release

inhibit_all_warnings!

#My pods`

**Comment by MANassar** [comment] 2018-06-06 06:04
Thanks for your response dnkoutso. I dont think they are added by Xcode because of the following train of thought/evidence:

1. Xcode only had 3 configurations: Development. Production and Enterprise.
![screen shot 2018-06-06 at 07 57 53](https://user-images.githubusercontent.com/1597951/41019640-d0dcbc7e-695f-11e8-98a2-c109860e54ed.png)

2. When I perform a pod install, I get these in the _Pods_ project: (In addition to my own 3, I get Debug and Release auto created)
![screen shot 2018-06-06 at 07 59 28](https://user-images.githubusercontent.com/1597951/41019682-f821752c-695f-11e8-9dd2-cd090d9ea107.png)

3. When I build, I get this warning ⚠️ 

> Target 'Pods-MyProject' of project 'Pods' was rejected as an implicit dependency for 'Pods_DynatraceMobile.framework' because its architectures 'x86_64' didn't contain all required architectures 'i386 x86_64'

**Comment by dnkoutso** [comment] 2018-06-06 13:56
@MANassar if you delete these configurations manually (Debug and Release) then compilation works?

I was under the impression that the Scheme you choose to build includes the configuration to build for and everything trickles down from there. 

All I am saying is that yes it might look weird that Debug and Release are present (and most probably Xcodeproj gem adds these default configs) but they shouldn't affect compilation since your scheme uses a different configuration.

Is it also possible for you to upload a quick sample app?

**Comment by jshier** [comment] 2018-06-12 17:03
This appears to be a duplicate of my issue #7780.

**Closed** 2018-09-17 18:22 UTC
Labels: s1:awaiting input, s6:need sample
