### ISSUE TITLE
Can't pod install

### ISSUE THREAD

**Issue by wdibi** [CocoaPods/CocoaPods#4939] opened 2016-02-24 13:15 UTC
### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.2
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /usr/local/Cellar/ruby/2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ ca717ea9c9e5fa706d6046434e5614d0a7662e1d
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
# use_frameworks!


target 'test' do
	pod 'AFNetworking', '0.9.1'
end

target 'testTests' do

end

target 'testUITests' do

end
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="AFNetworking">
Did you mean?  to_query
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:22:in `load'
/usr/local/bin/pod:22:in `<main>'
```

**Comment by neonichu** [comment] 2016-02-24 13:25
Duplicate of #4891 — Ruby 2.3 is not supported by CocoaPods 0.39

**Closed by neonichu** 2016-02-24 13:25 UTC

**Comment by wdibi** [comment] 2016-02-24 14:07
@neonichu how can I change to an older version? Sorry new to all of this

**Comment by neonichu** [comment] 2016-02-24 14:13
There are different methods for that, but if you're not already familiar with them, I would rather recommend using the CocoaPods app, which you can download from here: https://github.com/CocoaPods/CocoaPods-app/releases/tag/0.39.0 — that comes bundled with the correct version of Ruby and other dependencies, so that you don't have to care about it.

**Comment by wdibi** [comment] 2016-02-24 14:48
Thanks for your help!

On Wed, Feb 24, 2016 at 22:13, Boris Bügling <notifications@github.com> wrote:
There are different methods for that, but if you're not already familiar with
them, I would rather recommend using the CocoaPods app, which you can download
from here: https://github.com/CocoaPods/CocoaPods-app/releases/tag/0.39.0
[https://github.com/CocoaPods/CocoaPods-app/releases/tag/0.39.0] — that comes bundled with the correct version of Ruby and other dependencies,
so that you don't have to care about it.

—
Reply to this email directly or view it on GitHub
[https://github.com/CocoaPods/CocoaPods/issues/4939#issuecomment-188271876] .[https://github.com/notifications/beacon/AMOkYxK4MB_DVggfmivARszAptEsCYadks5pnbIngaJpZM4Hhqrc.gif]
