### ISSUE TITLE
Unit test targets no longer embed transitive dependencies, fail to load at runtime

### ISSUE THREAD

**Issue by lilyball** [CocoaPods/CocoaPods#8868] opened 2019-05-30 20:39 UTC
* [X] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

CocoaPods 1.6 introduced a regression where unit test targets without a host app no longer embed the dependencies of the framework target that they inherit search paths from.

In CocoaPods 1.5.x and earlier, a unit test target with `inherit! :search_paths` and no host app will embed the frameworks whose search paths it inherits. In CocoaPods 1.6.x (I tested 1.6.2) this changed so unit test targets that use `inherit! :search_paths` do not embed any inherited dependencies, which means the test bundle cannot be loaded into the test runner and the tests fail.

The default `Podfile` created with `pod init` uses `inherit! :search_paths` for these unit test targets, which tells me that this is the expected configuration.

I've tested this on both CocoaPods 1.6.2 and CocoaPods 1.7.1.

## Project that demonstrates the issue

[PodInherit.zip](https://github.com/CocoaPods/CocoaPods/files/3238661/PodInherit.zip)

This sample project was created by making  new iOS Framework w/Unit Tests project in Xcode, running `pod init` (with 1.7.1), and adding the single `pod 'PMJSON'` line to the `Podfile`. I then added some code to the project to actually use the dependency.

Running `pod install` with CocoaPods 1.5.3 properly adds the `[CP] Embed Pods Frameworks` build phase to the unit test target, but running `pod install` with CocoaPods 1.6.x or later eliminates that build phase entirely (assuming the unit test target has no direct dependencies of its own).

**Comment by dnkoutso** [comment] 2019-05-30 23:39
looks like a bug yes. Not sure if its intentional or not. Need someone to spend time with it.

**Comment by dnkoutso** [comment] 2019-05-30 23:52
Regressed here which was meant to fix another regression https://github.com/CocoaPods/CocoaPods/pull/7992

**Comment by segiddins** [comment] 2019-05-31 16:43
I think you need to not use `inherit! :search_paths` if you're not linking the target thats being inherited from

**Comment by dnkoutso** [comment] 2019-05-31 16:46
Actually that might be true ^

**Comment by lilyball** [comment] 2019-05-31 17:12
But I am linking it. This is a unit test target, it's absolutely linking the library it's testing.

**Comment by segiddins** [comment] 2019-06-02 20:36
Maybe I wasn’t understanding the scenario, I’ll try to take another look

**Comment by lilyball** [comment] 2019-06-03 00:51
In fact, the unit test target doesn't even try to use the transitive dependency directly. It simply calls a method in the framework, which uses the dependency internally.

**Comment by dnkoutso** [comment] 2019-06-27 21:43
A couple of things here: The test target gets `-framework PMJSON` even though it has `inherit! :search_paths` which is a bit weird...However you are integrating this test target into a dynamic framework instead of an app so something must embed the framework and so you must remote `inherit! :search_paths` in order for this to happen.

**Comment by lilyball** [comment] 2019-06-27 22:31
`inherit! :search_paths` comes from the default Podfile that CocoaPods constructs for this configuration. As a result of this default configuration, it also ends up being (in my experience) a common configuration to see.

CocoaPods 1.5.x (and earlier) was able to handle this correctly. I'm rather curious as to why this behavior broke.

**Comment by dnkoutso** [comment] 2019-06-28 11:14
This PR https://github.com/CocoaPods/CocoaPods/pull/7992 fixed a different issue. I think the default Podfile that is constructed needs to be updated and that is the bug. Did you use `pod lib create` for this or `pod init`?

**Comment by lilyball** [comment] 2019-06-29 02:20
`pod init`, because I was setting up a `Podfile`, not a `podspec`.

That said, using `inherit! :search_paths` has been the de-facto recommended configuration for unit tests since forever, so I'm not happy about just saying "oops, well, this is now the new behavior". Especially because I have no idea what else the unit test target picks up by dropping the `inherit! :search_paths` (the documentation doesn't really explain what other behavior is inherited).

**Comment by dnkoutso** [comment] 2019-06-29 02:28
The original behavior had a bug which was fixed. It seems like that the `pod init` generated template is wrong which is what this issue is and it should be fixed.

**Comment by dnkoutso** [comment] 2019-07-10 03:07
Fixed in https://github.com/CocoaPods/CocoaPods/pull/8984

**Closed** 2019-07-10 18:50 UTC
Labels: s2:confirmed, t2:defect
