### ISSUE TITLE
where is 'classes' folder in new pod created with 'lib create'

### ISSUE THREAD

**Issue by mklybor** [CocoaPods/CocoaPods#8774] opened 2019-05-07 02:57 UTC
* [ ] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

pod lib create MyPodName

## What did you expect to happen?

New pod structure is created and opened in Xcode, showing a "classes" folder where I would place/create the code for my pod.

I have seen several examples, tutorials, etc. that show this folder in Xcode, as being the place to put the pod's code.

## What happened instead?

No classes folder/group is present in Xcode. 

the directory DOES seem to be present in the file system, just not showing up in Xcode

thanks!

## CocoaPods Environment

$ pod env

### Stack

```
   CocoaPods : 1.6.0
        Ruby : ruby 2.3.7p456 (2018-03-28 revision 63024) [universal.x86_64-darwin18]
    RubyGems : 2.5.2.3
        Host : Mac OS X 10.14.4 (18E226)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.20.1 (Apple Git-117)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.3/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ cfd34cfeaff584293cefd902281f9a223455732b
               mklybor - https://github.com/mklybor/MacIOSFramework @ 32913f9bfa223dd8eccc1ef21e35e7b8d2f3be26
               MKPodSpecs - https://github.com/mklybor/MKPodSpecs @ cfd23e57fd1cb9b9a03b2435ce3c50a07db4eafa
               mkpodspecs-1 - /Users/michaelklybor/.cocoapods/repos/MKPodspecs @ 83931520ca5d3ecc717ec9da2056e327ad60b633
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.1.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
use_frameworks!

target 'EmptyPod_Example' do
  pod 'EmptyPod', :path => '../'

  target 'EmptyPod_Tests' do
    inherit! :search_paths

    
  end
end
```

## Project that demonstrates the issue

https://github.com/mklybor/EmptyPod

the pod lints and builds. but has no classes, since I do not see where to put the code.

I have created other pods that did not use the template from pod lib create, and they came out just fine.  however, I would like to follow the 'standard' template.

**Comment by dnkoutso** [comment] 2019-05-07 05:27
<img width="1512" alt="Screen_Shot_2019-05-07_at_12_25_13_AM" src="https://user-images.githubusercontent.com/310370/57273762-a04abc80-705e-11e9-96ee-0eb33b92364c.png">

It's hidden unless a subfolder exists.

Can try `install! 'cocoapods, :preserve_pod_file_structure => true`.

Either way this is not a bug or enhancement so I am closing.

**Closed by dnkoutso** 2019-05-07 05:27 UTC
