### ISSUE TITLE
`MODULEMAP_FILE` build setting set incorrectly

### ISSUE THREAD

**Issue by rakuyoMo** [CocoaPods/CocoaPods#8856] opened 2019-05-28 10:28 UTC
* [x]  I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

After adding the following code to the `Podfile` file, execute the `pod install` command

```Ruby
install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true
```

## What did you expect to happen?

Project compiled successfully

## What happened instead?

Xcode error：

`RxCocoaRuntime.h file not fount` at Rxcocoa-umbrella.h, and **Could not build Objective-C module RxCcocoa**

### Stack

```
   CocoaPods : 1.7.0
        Ruby : ruby 2.4.0p0 (2016-12-24 revision 57164) [x86_64-darwin18]
    RubyGems : 2.7.7
        Host : Mac OS X 10.14.5 (18F132)
       Xcode : 10.2.1 (10E1001)
         Git : git version 2.18.0
Ruby lib dir : /Users/mbcore/.rvm/rubies/ruby-2.4.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a290235db195ad9de49821f755a45b4aa475d617
               MBCModuleSpecs - https://git.mbcore.com/iOSModuleSwift/MBCModuleSpecs.git @ 27f2ff008593d4994e99640b56db2a52e95cb932
               mbcore-iosmodule-mbcspecs - https://git.mbcore.com/iOSModule/MBCSpecs.git @ f1f8fe3c2aae39c08e8b5f3de41b277a258c66eb
               MBCSpecs - git@git.mbcore.com:iOSModule/MBCSpecs.git @ f1f8fe3c2aae39c08e8b5f3de41b277a258c66eb
```

### Installation Source

```
Executable Path: /Users/mbcore/.rvm/rubies/ruby-2.4.0/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.4
cocoapods-playgrounds : 1.2.2
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.1
cocoapods-try         : 1.1.0
```

## Other

I think I need to provide my Podfile file.

```Ruby
source 'https://git.mbcore.com/iOSModuleSwift/MBCModuleSpecs.git'
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods',
         :generate_multiple_pod_projects => true
         :incremental_installation => true

target 'MBCHelper' do

  pod 'MBCExtension.swift'

end
```

Where `MBCExtension.swift` is a private library that relies on RxCocoa.

The `podspec` file of `MBCExtension.swift` is as follows (I omitted some unimportant information.)

```Ruby
Pod::Spec.new do |extension|

  extension.name          = 'MBCExtension.swift'

  extension.version       = '1.3.2'

  extension.homepage      = 'git url'

  extension.license       = 'MIT'

  extension.source        = { :git => 'git url', :tag => extension.version.to_s }

  extension.requires_arc  = true
  
  extension.platform      = :ios, '10.0'
  
  extension.swift_version = '5.0'
  
  extension.static_framework = true
  
  extension.module_name   = 'MBCExtension'

  extension.default_subspecs = 'Extendable', 'Extension'
  
  extension.subspec 'Extendable' do |extendable|
      extendable.source_files = 'MBCExtension/MBCExtension/Core/Extendable/'
  end
  
  extension.subspec 'Extension' do |extension|
      
      extension.source_files = 'MBCExtension/MBCExtension/Core/Object/', 'MBCExtension/MBCExtension/Core/UI/'
      
      extension.dependency 'MBCExtension.swift/Extendable'
      extension.dependency 'MBCLog.swift/MBC'
      
      extension.dependency 'RxCocoa'
  end
  
  extension.subspec 'YYText' do |text|
      
      text.source_files = 'MBCExtension/MBCExtension/Core/YYText/*.swift'
      
      text.dependency 'MBCExtension.swift/Extension'
      
      text.dependency 'YYText'
  end

end
```

Where `YYText` is an Objective-C library

So how can I make my program run successfully?

**Comment by rakuyoMo** [comment] 2019-05-28 10:30
When I remove the following code, the program can run

```Ruby
install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true
```

But I want to use these features

**Comment by sebastianv1** [comment] 2019-05-28 16:43
@rakuyoMo Do you mind attaching a sample project we can use to debug?

**Comment by rakuyoMo** [comment] 2019-05-29 01:02
@sebastianv1 I can provide an example, please wait a moment. First I will streamline my project and upload it to the public Cocoapods and make sure this bug will be reproduced.

**Comment by rakuyoMo** [comment] 2019-05-29 06:31
@sebastianv1  I have already done the demo and reproduced the bug. The `Podfile` file looks like this:

```Ruby
source 'https://github.com/CocoaPods/Specs.git'

platform :ios, '10.0'

use_modular_headers!
inhibit_all_warnings!

install! 'cocoapods',
         :generate_multiple_pod_projects => true,
         :incremental_installation => true

target 'Example' do

  pod 'RKOSimpleExample.swift' # Like MBCExtension.swift

end
```

**Comment by dnkoutso** [comment] 2019-05-29 17:19
@rakuyoMo `RKOSimpleExample.swift` is not a pod available anywhere.

**Comment by rakuyoMo** [comment] 2019-05-30 01:43
I guarantee that it is a usable pod, as shown below. How are you integrated?

![1559180430755](https://user-images.githubusercontent.com/16268770/58602338-299c8a00-82bf-11e9-845b-481380a37e38.jpg)

Or you can use [this project](https://github.com/rakuyoMo/SimpleExample), which is the data source for `RKOSimpleExample.swift`

**Comment by rakuyoMo** [comment] 2019-06-03 01:52
@dnkoutso Excuse me, can the project I showed above be used?

**Comment by rakuyoMo** [comment] 2019-06-04 08:03
This issue still exists in version 1.7.1

**Comment by rakuyoMo** [comment] 2019-06-05 03:58
My problem was solved by modifying `use_modular_headers!` in the `Podfile ` file to `use_frameworks!`.

But actually I don't want to make the above changes, I still want to use `use_modular_headers!`...

**Comment by rakuyoMo** [comment] 2019-06-10 10:01
@dnkoutso @sebastianv1 

I am very sorry to bother you many times, but this question is really important to me and you have not responded to me for a long time.

I want to know the current status of this problem, is my example not working, or you have no time to troubleshoot this problem?

I don't quite understand the meaning of 

> is not a pod available anywhere.

Can you give me a reply, thank you!

**Comment by sebastianv1** [comment] 2019-06-10 16:50
@rakuyoMo Apologies for the delay. I'll take a look into this today.

**Comment by rakuyoMo** [comment] 2019-06-12 01:26
> @rakuyoMo Apologies for the delay. I'll take a look into this today.

@sebastianv1  thank you very much! Look forward to your good news

**Comment by sebastianv1** [comment] 2019-06-12 17:05
It appears that the `MODULEMAP_FILE` build setting is getting set incorrectly (irregardless of `generate_multiple_pod_projects` installation option). When using modular headers it is set as `Headers/Public/RKOSimpleExample/RKOSimpleExample.swift.modulemap`, but the file exists in: `Target Support Files/RKOSimpleExample.swift/RKOSimpleExample.swift.modulemap`.

Seems like the root of this issue is because inside `target_installer.rb` we write to `target.module_map_path_to_write` but read from `target.module_map_path` when setting the build setting. Thoughts @dnkoutso or @segiddins ?

**Comment by dnkoutso** [comment] 2019-06-12 22:12
Seems like we should fix that. We are writing the file to a different path compared to the one the build setting points to.

**Comment by rakuyoMo** [comment] 2019-06-13 05:48
It’s great to be able to find the problem, I hope to fix it as soon as possible.

Express my thanks again

@sebastianv1 @dnkoutso

**Comment by dnkoutso** [comment] 2019-06-23 22:57
@sebastianv1 did we ever ship a fix for this?

**Comment by dnkoutso** [comment] 2019-06-28 15:02
@sebastianv1 since this is not a 1.7 issue with multi pods generator I am moving to 1.8.x

**Comment by rakuyoMo** [comment] 2019-07-01 04:03
This is really bad news. I have to wait until 1.8.0 to fix this bug.

It seems that I still need to wait a few more months.😭

**Comment by dnkoutso** [comment] 2019-07-09 01:54
it's not months but it could be 1-3 weeks from now.

**Comment by amorde** [comment] 2019-07-09 04:14
We use symlinks for this currently, here's some code that handles this

https://github.com/CocoaPods/CocoaPods/blob/46b3f3625476d12b8077d365c9c033fdc8d832dd/lib/cocoapods/installer/xcode/pods_project_generator/pod_target_installer.rb#L804-L829

not sure why it is done this way (although I have touched this code myself) but this was last modified as part of #8196

**Comment by dnkoutso** [comment] 2019-07-09 16:28
@amorde is this maybe about a custom module map file?

**Comment by amorde** [comment] 2019-07-09 17:28
Oh yep, but the generated module map behaves similarly as well

https://github.com/CocoaPods/CocoaPods/blob/46b3f3625476d12b8077d365c9c033fdc8d832dd/lib/cocoapods/installer/xcode/pods_project_generator/target_installer.rb#L157-L177

**Comment by rakuyoMo** [comment] 2019-07-30 01:15
@dnkoutso @amorde  Is this problem fixed?

**Comment by amorde** [comment] 2019-07-30 02:25
We haven’t made any changes here - we currently write the module map to a particular directory and then symlink it to the build setting value. I haven’t gotten the chance to look into this further

**Comment by amorde** [comment] 2019-07-31 04:06
Manually copying the module map into the location specified by `MODULEMAP_FILE` (in this case `Headers/Public/RKOSimpleExample/RKOSimpleExample.swift.modulemap`) doesn't solve the issue, so I don't think this is related to the symlinking of module maps.

**Comment by amorde** [comment] 2019-07-31 04:12
In this example I believe the issue is with `HEADER_SEARCH_PATHS`, adding `${PODS_ROOT}/Headers/Public/RxCocoa` to `HEADER_SEARCH_PATHS` to the `.xcconfig` of the `RKOSimpleExample` target resolves the issue. I'm not familiar enough with this to know why this might not be setup correctly.

@segiddins any ideas here?

**Comment by ArmsZhou** [comment] 2019-07-31 06:24
In my Podfile, i define a function to solve this problem.

```ruby
...

def append_header_search_path(target, path)
    target.build_configurations.each do |config|
        # Note that there's a space character after `$(inherited)`.
        config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
        config.build_settings["HEADER_SEARCH_PATHS"] << path
    end
end

post_install do |installer|
  installer.pod_target_subprojects.flat_map { |p| p.targets }.each do |t|
    # `RxDataSources` is a pod lib which depends the `RxCocoa` lib.
    if t.name == "RxDataSources"
        append_header_search_path(t, "${PODS_ROOT}/Headers/Public/RxCocoa")
    end
  end
end

```

**Comment by rakuyoMo** [comment] 2019-07-31 07:03
> In my Podfile, i define a function to solve this problem.
> 
> ```ruby
> ...
> 
> def append_header_search_path(target, path)
>     target.build_configurations.each do |config|
>         # Note that there's a space character after `$(inherited)`.
>         config.build_settings["HEADER_SEARCH_PATHS"] ||= "$(inherited) "
>         config.build_settings["HEADER_SEARCH_PATHS"] << path
>     end
> end
> 
> post_install do |installer|
>   installer.pod_target_subprojects.flat_map { |p| p.targets }.each do |t|
>     # `RxDataSources` is a pod lib which depends the `RxCocoa` lib.
>     if t.name == "RxDataSources"
>         append_header_search_path(t, "${PODS_ROOT}/Headers/Public/RxCocoa")
>     end
>   end
> end
> ```

@amorde Maybe you can refer to this?

**Comment by amorde** [comment] 2019-07-31 07:04
Thanks, but it's more that I'd like someone else on the CocoaPods team to weigh in on _why_ this might be happening

**Comment by rakuyoMo** [comment] 2019-08-28 01:34
I hope this problem can be solved in a beta version of 1.8.0 - I hope the author has not forgotten this bug

@amorde @dnkoutso

**Comment by amorde** [comment] 2019-09-04 04:04
While adding `${PODS_ROOT}/Headers/Public/RxCocoa` to the library's `HEADER_SEARCH_PATHS` works, it doesn't seem to be necessary when using single project generation. I haven't quite figured out why that's the case though

**Comment by rakuyoMo** [comment] 2019-12-23 02:30
There is no mention in the latest 1.9.0 beta update that addresses this issue. 

I am not convenient to upgrade to the test version now, have you solved this problem @dnkoutso  ? Or has anyone else verified this after upgrading to the beta? @amorde

**Comment by dnkoutso** [comment] 2019-12-23 03:39
The issue is not fixed. We are in 1.9.0 beta phase so it might be fixed for 1.9.0.

**Comment by Nemocdz** [comment] 2020-05-22 02:43
Is this problem fixed? Does anyone has solution？

**Comment by rakuyoMo** [comment] 2020-05-22 02:45
> Is this problem fixed? Does anyone has solution？

I also want to know

**Comment by rakuyoMo** [comment] 2020-05-22 02:46
> Is this problem fixed? Does anyone has solution？

I also want to know

**Comment by amorde** [comment] 2020-05-22 03:21
No, it’s still open which means it’s not fixed

**Comment by Nemocdz** [comment] 2020-05-22 03:24
> > Is this problem fixed? Does anyone has solution？
> 
> I also want to know

I add `use_frameworks! :linkage => :static'` from Cocoapods 1.9. And it can solve this problem magically. But it will cause another archived problem if you use different `subspec` in multiple targets. It's a bug caused by Xcode and Cocoapods together, more information in #8206.

**Closed** 2020-10-04 04:59 UTC
Labels: help wanted, s1:awaiting input

**Comment by LKR1996** [comment] 2022-03-02 07:38
> There hasn't been any activity on this issue recently. Due to the high number of incoming GitHub notifications, we have to clean some of the old issues, as many of them have already been resolved with the latest updates.

 Hi, I encountered the same problem, can you tell me how it was finally solved

**Comment by yunluoxin** [comment] 2023-02-02 06:58
@dnkoutso @amorde Hi, It seems this problem was not solved yet. Help us plz.
