### ISSUE TITLE
Generated xcconfig should require framework imports to include framework name.

### ISSUE THREAD

**Issue by dnkoutso** [CocoaPods/CocoaPods#3734] opened 2015-06-25 23:33 UTC
Consider the case of the `err.h` header in `OpenSSL`. 

Right now, if you `#include <err.h>` in a consumer of the `OpenSSL` pod, you'll include the OpenSSL `err.h`. This is particularly a problem because there is a system header `err.h` as well. 

We want to require that pod consumers specify the framework itself when importing a header from a framework. E.g., we want: `#include <err.h>` to include the system `err.h` and `#include <openssl/err.h>` to include the OpenSSL one. This solves such name conflicts. 

In our `OpenSSL.podspec` I am specifying a `header_dir` value but that seems to be included in the header search paths, it seems that it should not.

![screen_shot_2015-06-25_at_4_18_12_pm](https://cloud.githubusercontent.com/assets/310370/8367765/922e85ca-1b56-11e5-97eb-5b5630782653.png)

Thanks.

**Comment by dnkoutso** [comment] 2015-06-25 23:40
Here's a sample app demonstrating the issue.

https://www.dropbox.com/s/g7m45r96qoaql8e/HeadersBugOpenSSL.zip?dl=0

**Comment by segiddins** [comment] 2015-06-25 23:43
I'm pretty sure this is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/1437 ?

**Comment by dnkoutso** [comment] 2015-06-25 23:48
Seems like it, yes.

**Closed** 2015-06-25 23:52 UTC
