### ISSUE TITLE
Archiving (or building) an app that uses XCFrameworks built with Xcode 12 do not work in Xcode 12

### ISSUE THREAD

**Issue by radazzouz** [CocoaPods/CocoaPods#9990] opened 2020-08-19 13:52 UTC
* [x] I've read and understood the [*CONTRIBUTING* guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

Using the following steps to reproduce:

- Download the sample project below and run `pod install`
- Open `SwiftExample.xcworkspace` in Xcode 11.6
- Archive on “Generic iOS Device”
- Notice that the archive succeeded.
- Quit Xcode 11.6.
- Open `SwiftExample.xcworkspace` in Xcode 12 beta 5
- Archive on “Any iOS Device (arm64)”

## What did you expect to happen?

The archive should have succeeded in Xcode 12, just like it does in Xcode 11.6.

## What happened instead?

The archive failed. Here's the Archive output log: [Archive SwiftExample_2020-08-19T09-45-01.txt](https://github.com/CocoaPods/CocoaPods/files/5096812/Archive.SwiftExample_2020-08-19T09-45-01.txt)

## CocoaPods Environment

1.10.0.beta.2, but it also happens with the stable version 1.9.3

## Project that demonstrates the issue

[SwiftExample-CocoaPods.zip](https://github.com/CocoaPods/CocoaPods/files/5096792/SwiftExample-CocoaPods.zip)

## Additional Information:

1. The same sample project works great in Xcode 12 when using XCFrameworks built with Xcode 12.
2. If we use a different podspec that uses fat `.framework` files built with Xcode 12 (see the various commented out podspecs in the Podfile) it also works fine.
3. Could be related to #9794

**Comment by amorde** [comment] 2020-08-19 20:46
```
<unknown>:0: error: unable to load standard library for target 'arm64-apple-ios13.1-macabi'
/Users/radazzouz/Downloads/SwiftExample-CocoaPods/Pods/PSPDFKit/PSPDFKitUI.xcframework/ios-arm64/PSPDFKitUI.framework/Modules/PSPDFKitUI.swiftmodule/arm64-apple-ios.swiftinterface:5:8: error: failed to build module 'PSPDFKit' from its module interface; the compiler that produced it, 'Apple Swift version 5.3 (swiftlang-1200.0.25.2 clang-1200.0.27.1)', may have used features that aren't supported by this compiler, 'Apple Swift version 5.3 (swiftlang-1200.0.28.1 clang-1200.0.30.1)'
```

any chance this is the cause? 

unfortunately I don't have much time to dig into this in the near future

**Comment by radazzouz** [comment] 2020-08-19 20:57
> any chance this is the cause?

Yes it is. The strange part is that this only happens when the XCFramework is integrated via CocoaPods. If we integrate the XCFramework manually (drag and drop) it works without any issues.

**Comment by paulb777** [comment] 2020-08-19 22:48
That error looks like the `.xcframework` was generated by a later version of Xcode than the app trying to link it.

**Comment by radazzouz** [comment] 2020-08-20 00:28
It certainly seems so. The (current) XCFrameworks were built with Xcode 12 beta 4. The same issue happens when I try and use beta 4 to archive the app. I also tested this with XCFrameworks that were built with Xcode 12 beta 5 on my local machine. In other words, the issue persists even if we use the matching versions of Xcode 12.

This is indeed very weird since it only happens in Xcode 12 and with the CocoaPods integration.

It all works fine when using Xcode 11.6 + CocoaPods, or the manual integration of the XCFrameworks with Xcode 12.

**Comment by radazzouz** [comment] 2020-08-26 13:59
Quick update: I just retested the attached sample project in Xcode 12 beta 6 using CocoaPods artifacts (XCFrameworks) built with Xcode 12 beta 6. The issue persisted.

**Comment by radazzouz** [comment] 2020-09-15 20:49
**Update:** This is still an issue with Xcode 12 GM.

**Comment by dnkoutso** [comment] 2020-09-15 20:54
This is a long shot but an update to the regex was merged on `1-10-stable` branch. Is it related and does that help?

**Comment by amorde** [comment] 2020-09-15 21:19
I haven't had any time to work on CocoaPods lately, and don't expect to have time in the near future. I wish I had a better answer.

https://github.com/CocoaPods/CocoaPods/pull/10027 improved xcframework slice selection in the 1.10 beta and is the fixe mentioned above. It's possible that could improve this

**Comment by radazzouz** [comment] 2020-09-15 21:22
@amorde @dnkoutso thank you so much for the heads up!

I just checked out `1-10-stable` and used it to retest and the issue is gone! 🎉

**Comment by amorde** [comment] 2020-09-15 21:26
Awesome! Thank you for trying and for this report. Appreciate all of your bug reports 🙏

**Closed** 2020-09-15 21:27 UTC

**Comment by dnkoutso** [comment] 2020-09-16 03:47
Shipped with 1.10.0.rc.1

**Comment by arvkmr** [comment] 2020-10-12 13:19
So while 1.10.0.rc.1 solves the problem for Xcode 12. XCFrameworks build and distributed using Xcode 12 on cocoapods do not work on Xcode 11. In Xcode 11.7 version for ex, I get an error "dyld: dependent dylib ‘@rpath/my.framework/my’ not found for "Myapp"
could not use "path/to/lib" because it was not built for platform iOS". 
Additionally none of the iOS devices are listed as run targets. It's possible some clients might still be on older versions of Xcode and would have no idea what the problem is or the fact that they might have to upgrade.

**Comment by bhushan-shinde-cpd** [comment] 2021-09-23 11:04
I am using Xcode 13 and getting this issue again with XCFramework when trying to install via cocopods. I am having cocoa pods version 1.11.2 installed. But still this issue happens.
[CP] Unable to find matching .xcframework slice in 'ios-i386_x86_64-simulator ios-arm64_armv7' for the current build architectures (arm64 x86_64 i386).
    - NOTE  | [iOS] xcodebuild:  clang: error: linker command failed with exit code 1 (use -v to see invocation)
