### ISSUE TITLE
Header file not found when install pods using CocoaPods 0.38

### ISSUE THREAD

**Issue by tang3w** [CocoaPods/CocoaPods#3822] opened 2015-07-14 15:34 UTC
If  I use CocoaPods 0.37 to install pods, everything is OK.

I note that, CocoaPods 0.38 introduce a breaking change:

* The CocoaPods environment header has been removed.

So, my question is:

How to update the .podspec file to solve this problem in CocoaPods 0.38?

**Comment by segiddins** [comment] 2015-07-14 15:38
You just can't rely on that header or its preprocessor definitions being available any more.

**Comment by tang3w** [comment] 2015-07-15 01:42
Does it mean that `public_header_files` is not available any more?

I found headers do not get symlinked in CocoaPods 0.38.

Is there a solution can make my pod to work in both CocoaPods 0.37 and 0.38?

Can I specify the framework search path in podspec file?

**Comment by segiddins** [comment] 2015-07-15 01:54
Hm, if that's happening it's a big. Can you share a project that reproduces the issue with us? Thanks!

**Comment by tang3w** [comment] 2015-07-15 03:48
I host the demo project at here: http://www.datafilehost.com/d/fe8cbe2d

In the Podfile, I just use the Parse SDK.

In the project, if I use CocoaPods 0.37 to install, the `#import <Parse/Parse.h>` will be OK.

However, if I use CocoaPods 0.38 to install, `#import <Parse/Parse.h>` will show a file not found error.

**Comment by danielnordh** [comment] 2015-07-16 12:14
I have the same issue with pod 'ParseFacebookUtils'
#import <ParseFacebookUtils/PFFacebookUtils.h> not found

Works fine in 0.37.2 but not in 0.38

**Comment by alistra** [comment] 2015-07-16 12:41
Same

**Comment by alistra** [comment] 2015-07-16 12:44
For me it crashes when I have a local pod A. 

pod 'A' depends on pod 'Parse'

When I try to build App that has pod 'A' in the Podfile then building of pod A fails with Parse files not found inside of other Parse files.

**Comment by nlutsenko** [comment] 2015-07-16 23:08
This is very strange, I can see that `0.38.2` doesn't symlink the headers anymore, on the other hand `0.37.2` does.
@segiddins Repro steps: Emtpy ObjC project with Podfile:
```
pod 'Parse'
pod 'ParseUI'
```

Make sure you don't use frameworks, but rather static libraries. The problem appears with compiling ParseUI, since it depends on `Parse` and references a symbol from there, but fails to find a header since there are non under `Pods/Headers/Public/Parse`.

**Comment by segiddins** [comment] 2015-07-18 17:33
The issue here is with the Parse podspec -- it would be fixed by merging https://github.com/CocoaPods/Specs/pull/13253.

**Closed by segiddins** 2015-07-18 17:33 UTC
