### ISSUE TITLE
Archives broken in Xcode 7β6 by containing public pod headers

### ISSUE THREAD

**Issue by tomislav** [CocoaPods/CocoaPods#4119] opened 2015-09-02 16:39 UTC
I'm getting "Generic Xcode archives" when archiving in Xcode 7 beta 6 and using cocoapods 0.39 beta 4. When inspecting the archive I've noticed that public headers from the pods are included in the archive.

<img width="897" alt="screen shot 2015-09-02 at 18 35 18" src="https://cloud.githubusercontent.com/assets/656/9637492/626901f4-51a1-11e5-9b7b-aa5633827a45.png">

If I manually go through the pods and move all the headers from public/private to project that makes the archive valid.

But I'm sure that's not the proper way. Am I missing something?

**Comment by tomislav** [comment] 2015-09-02 16:56
In each pod, under `Packaging`, `Private Headers Folder Path` and `Public Headers Folder Path` is set to `/usr/local/bin`. If I clear them then I get a valid archive.

<img width="1072" alt="screen shot 2015-09-02 at 18 48 49" src="https://cloud.githubusercontent.com/assets/656/9638009/3f64acb4-51a4-11e5-80df-38dd871692c2.png">

**Comment by neonichu** [comment] 2015-09-03 02:21
Interesting, is that a new issue that popped up with Xcode beta 6?

**Comment by segiddins** [comment] 2015-09-03 02:29
@tomislav what version of CocoaPods are you using?

**Comment by tomislav** [comment] 2015-09-03 02:54
Yes, I've been using Cocoapods with this project for the past year without a problem. Today I was updating for iOS 9 and ran into it. Not sure if it was in prior betas of Xcode. 

Cocoapods 0.39 beta 4. 

I've tried deleting my Pods folder and installing from scratch, but no go.

**Comment by segiddins** [comment] 2015-09-03 02:56
Hm, CocoaPods beta 4 did make a change to giving headers accessibility attributes... might that be the cause of this?

**Comment by tomislav** [comment] 2015-09-03 08:44
Yes, I've downgraded to beta 3 and it works properly. All the headers are listed under `Project`. So I presume it's 07c804de06e1c51d95ec11ca3f5369467a2a7582. Which I guess is fine as long as `Public/Private Headers Folder Path` is not set to `/usr/local/include` (seems like an Xcode default).

What's interesting is that under the main Pods project those paths are blank, they are set only under the individual pods.

**Comment by neonichu** [comment] 2015-09-03 14:05
I guess we can just set those build settings to empty?

**Comment by livsik** [comment] 2015-09-04 15:13
I've got same issue on Cocoapods 0.39 beta 4.
Cocoapods 0.38.2 works fine

**Comment by paul-delange** [comment] 2015-09-08 03:45
us too

**Comment by segiddins** [comment] 2015-09-08 04:45
We just need to fix the private headers location.

**Comment by jhabdas** [comment] 2015-09-19 00:19
@tomislav you're a god damn genius

**Comment by neonichu** [comment] 2015-09-19 10:47
I have fixed this in #4217 — would be good if some could verify that this works for you as well

@tomislav Thanks for figuring out the fix for this!

**Comment by 942v** [comment] 2015-09-20 23:07
Thx @tomislav worked for me with the last version of CP beta.

**Comment by vipom** [comment] 2015-09-21 10:30
@neonichu Great ! #4217 fixes the archiving here :ok_hand:

**Closed** 2015-09-27 18:37 UTC
Labels: s4:awaiting validation

**Comment by pontusm** [comment] 2015-09-29 14:05
I have run into this problem as well and tried to follow the steps described here, i.e. I cleared the header folder paths from all pod projects and moved the header files from Public to Project under Build Phases. However, now I get the following error during the "Copy Pods Resources" step when trying to create the archive:

rsync: mkdir "/Users/pontusm/Library/Developer/Xcode/DerivedData/Rapid2-fpvggibcggtnaugcksjdfealbhcc/Build/Intermediates/ArchiveIntermediates/Rapid2/InstallationBuildProductsLocation/usr/local/lib" failed: No such file or directory (2)

Anyone know why?

**Comment by segiddins** [comment] 2015-09-29 14:06
@pontusm try deleting derived data and building again?

**Comment by pontusm** [comment] 2015-09-29 14:09
Nope that does not help. I get the same error.

**Comment by segiddins** [comment] 2015-09-29 14:10
¯\_(ツ)_/¯ please open a new issue with a project we can use to reproduce the problem?

**Comment by pontusm** [comment] 2015-09-29 14:14
I'm pretty sure this wouldn't show up in a new project. It is probably some weird setting somewhere in this project which has been upgraded many times since Xcode 3 or something. Isn't there any good way to debug what CocoaPods is doing and maybe I could solve it myself?

**Comment by segiddins** [comment] 2015-09-29 14:24
Sure, you can try debugging it yourself, but I don't really know whats going wrong, other than not having actually removed the bad build settings properly from the project.

**Comment by clibbz0r** [comment] 2015-10-12 22:31
@pontusm I had the same thing as you after doing @tomislav's fix. I just searched the build settings for /usr/local/lib and found that it was also set for the Installation Directory setting (under Deployment). Once I removed this from all my pods targets the archive was successful.
