### ISSUE TITLE
Linker Error with specific Pods in nested Targets

### ISSUE THREAD

**Issue by iv-mexx** [CocoaPods/CocoaPods#6834] opened 2017-06-27 12:31 UTC
I'm using CocoaPods 1.3.0-beta.2

* [X] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

**tl;dr**: I'm getting a `ld: library not found for -lGoogleAnalyticsServices` linker error for my (unit / ui) test targets (but not the normal debug run target) with a specific setup.

I reproduced the Issue with an empty project, I have published this project [on github](https://github.com/iv-mexx/CocoaPodsBugRepro)

The problematic situation seems to be the following
1. Multiple Targets (e.g. `App` and `AppTests`) are nested in the Podfile
2. [`GoogleAnalytics-iOS-SDK`](https://github.com/mutualmobile/Google-Analytics/blob/master/GoogleAnalytics-iOS-SDK.podspec) Pod is used
    *  I guess the Problem is that this Pod is distributed as precompiled framework, but I did not verify this

This Podfile produces the described issue

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

def ads_pods
    pod 'GoogleAnalytics-iOS-SDK'
end

def debugging_pods
    pod 'HSTestingBackchannel'
end

target 'iZurvive' do
    inhibit_all_warnings!
    ads_pods
    debugging_pods

    target 'iZurviveTests' do 
        # Pods for testing
        inherit! :search_paths        
    end

    target 'iZurviveUITests' do
        # Pods for UI testing
        inherit! :search_paths
        pod 'HSTestingBackchannel'
    end
end
```

In a project with this setup, building and running the App works just fine, but when building the unit test target, the linker fails with `ld: library not found for -lGoogleAnalyticsServices`

### Solutions

If one of the mentioned aspects is changed, it works:

* Removing the `GoogleAnalytics-iOS-SDK` resolves the issue
* Duplicating the targets in the Podfile instead of using inheritance resolves the issue

Example of Podfile that does not produce the issue:

```
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

def ads_pods
    pod 'GoogleAnalytics-iOS-SDK'
end

def debugging_pods
    pod 'HSTestingBackchannel'
end

target 'iZurvive' do
    inhibit_all_warnings!
    ads_pods
    debugging_pods
end

target 'iZurviveTests' do 
    # Pods for testing
    inhibit_all_warnings!
    ads_pods
    debugging_pods     
end

target 'iZurviveUITests' do
    # Pods for UI testing
    inhibit_all_warnings!
    ads_pods
    debugging_pods
    pod 'HSTestingBackchannel'
end
```

### Note

The repro project and the Podfile pasted below have an additional build configuration `Testing` (Additional to `Debug` and `Production`). 

At first I thought that this was necessary to reproduce the issue, but then I found out that the issue occurs regardless of this additional configuration. So I *guess* you can just ignore it.

## What did you do?

ℹ Please replace this with what you did.  

* Create Podfile with additional Pods for Test Target
* run `pod install`
* Run App - Working
* Run Unit Tests - Linker Error

## What did you expect to happen?

* Running (Building) Unit Tests should not fail with a linker error

## What happened instead?

* Running (Building) Unit Tests should not fail with a linker error
* `ld: library not found for -lGoogleAnalyticsServices`

### Stack

```
   CocoaPods : 1.3.0.beta.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.4 (16E195)
       Xcode : 8.3.3 (8E3004b)
         Git : git version 2.11.0 (Apple Git-81)
Ruby lib dir : /Users/markuschmelar/.rvm/rubies/ruby-2.3.0/lib
Repositories : devsub-specs - git@gitlab.devsub.net:cocoapods/specs.git @ 5860afd595c8052ea7d268ccf5eaeb179759895e
               innovaptor-specs - git@git.innovaptor.at:cocoapods/specs.git @ 5860afd595c8052ea7d268ccf5eaeb179759895e
               master - https://github.com/CocoaPods/Specs.git @ d21a4aa5912cdf2967ce26b238d4a8b4d6a81fc2
```

### Installation Source

```
Executable Path: /Users/markuschmelar/.rvm/gems/ruby-2.3.0@iosdev/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.2.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '8.0'

def ads_pods
    pod 'GoogleAnalytics-iOS-SDK'
end

def debugging_pods
    pod 'HSTestingBackchannel', :configuration => ['Testing']
end

target 'iZurvive' do
    inhibit_all_warnings!
    ads_pods
    debugging_pods

    target 'iZurviveTests' do 
        # Pods for testing
        inherit! :search_paths        
    end

    target 'iZurviveUITests' do
        # Pods for UI testing
        inherit! :search_paths
        pod 'HSTestingBackchannel', :configuration => ['Testing']
    end
end
```

## Project that demonstrates the issue

https://github.com/iv-mexx/CocoaPodsBugRepro

Note: 
* The `master` branch demonstrates the issue
* The `feature/Working1_NoGai` branch demonstrates that the issue is resolved by removing the GoogleAnalytics-iOS-SDK Pod
* The `feature/Working2_NoTargetNesting` branch demonstrates that the issue is also resolved by not using target inheritance but duplicate each target

**Comment by dnkoutso** [comment] 2017-06-27 12:47
Thanks for the great report @iv-mexx. I can confirm the issue but still investigating the root cause.

**Comment by dnkoutso** [comment] 2017-06-27 13:03
@iv-mexx it appears this is an issue with with the podspec which has been deprecated and you should use `GoogleAnalytics` instead.

The problem arises because the podspec https://github.com/CocoaPods/Specs/blob/d0ec5a65e80656c8d78e12ff19f251df879e0bc2/Specs/3/2/c/GoogleAnalytics-iOS-SDK/3.12/GoogleAnalytics-iOS-SDK.podspec.json#L37-L38 manually wires `libraries` to all targets and also sets the user xcconfig header search paths.

Please use `GoogleAnalytics` pod instead.

**Comment by dnkoutso** [comment] 2017-06-27 13:24
Closing as of now, I believe the deprecated podspec is incorrect for forcing a linkage of `GoogleAnalyticsServices` as a system library. It should be using `vendored_library` instead.

**Closed by dnkoutso** 2017-06-27 13:24 UTC

**Comment by iv-mexx** [comment] 2017-06-27 14:26
@dnkoutso Oh alright. I was aware that the `GoogleAnalytics-iOS-SDK` Pod is deprecated but thought maybe the problem was a more general one. 

But if its really just this one pod I'll gladly update to `GoogleAnalytics`. 

Thanks!
