### ISSUE TITLE
Could not able to run tests in a workspace target

### ISSUE THREAD

**Issue by soaurabh** [CocoaPods/CocoaPods#5739] opened 2016-08-11 10:41 UTC
* I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?
I’m working on a workspace, which has two frameworks. Say, First.framework and Second.framework
I want to use some pods in each of the framework targets and my Podfile looks like this

```
workspace 'Final.xcworkspace'
use_frameworks!

target "First" do
    platform :osx, '10.7'
    project "First/First.xcodeproj"
    pod 'PubNub', '3.7.11'
    pod 'Typhoon'
    target 'FirstTests' do
        inherit! :search_paths
    end
end

target "Second" do
    platform :osx, '10.7'
    project "Second/Second.xcodeproj"
    pod 'SSZipArchive', '1.2'
    target 'SecondTests' do
        inherit! :search_paths
    end
end
```

Now, the issue is when i reference Second.framework in First.framework my tests of First.framework does not work.

## What did you expect to happen?

I'm expecting test targets of the project should run fine.

## What happened instead?

I'm facing this issue in the test target logs “Test target FirstTests encountered an error (Early unexpected exit, operation never finished bootstrapping - no restart will be attempted)”

## Project that demonstrates the issue
Tests of First.framework runs fine without linking- https://github.com/SoaurabhK/FrameworkCombo

Tests of First.framework fails upon linking First.framework with Second.framework-
https://github.com/SoaurabhK/FailingFrameworkCombo

**Comment by neonichu** [comment] 2016-08-11 11:17
This seems like a duplicate of #4752, see <https://github.com/CocoaPods/CocoaPods/issues/4752#issuecomment-230473242>

**Closed by neonichu** 2016-08-11 11:17 UTC
