### ISSUE TITLE
Optimizing dynamic frameworks with 0.36 for larger projects

### ISSUE THREAD

**Issue by OliverLetterer** [CocoaPods/CocoaPods#3264] opened 2015-03-14 08:50 UTC
I just started migrating one project to dynamic frameworks thanks to the recently released CocoaPods 0.36, great work 🎉✨🎉, and I wanted to ask / discuss about the following problem I have encountered. Please forgive me if I have overlooked any documentation hints or open issue but I haven't found anything related directly.

The project consists of one application target, multiple extension targets and one dynamic framework target which contains all shared code. Before CocoaPods 0.36, I introduced a second dynamic framework named "CocoaPods" where I included _all_ CocoaPod dependencies and hacked together a post_install phase for creating corresponding xcconfig files for all other targets. Now my goal is to remove the second "CocoaPods" framework and ship each pod in its own dynamic framework. I started of with a Podfile which, for simplicity sake, boils basically down to the following:

```
platform :ios, '8.0'
use_frameworks!

target 'Application' do
    pod 'MBProgressHUD', '~> 0.9.0'
end

target 'Framework' do
    pod 'AFNetworking', '~> 2.5.1'
end
```

Now almost all dependencies of the "Framework" target are publicly shared and must be present in the frameworks header files. I ran into some compilation and other problems at first because the "Application" target doesn't "officially" depend on AFNetworking. Therefore, I added AFNetworking to the "Application" target as well:

```
platform :ios, '8.0'
use_frameworks!

target 'Application' do
    pod 'MBProgressHUD', '~> 0.9.0'
    pod 'AFNetworking', '~> 2.5.1'
end

target 'Framework' do
    pod 'AFNetworking', '~> 2.5.1'
end
```

This works but introduces the following two downsides:
- First, I have to declare dependencies twice which is redundant. Right now I worked around this by wrapping all "shared dependencies" in one function def.
- Second, both application targets now compile it's own version of the AFNetworking dependency, namely "Pods-Framework-AFNetworking" and "Pods-Application-AFNetworking". Since I have a lot of so called "shared dependencies", I'm now having a Pods project with well over 100+ frameworks to build which greatly increased compilation time.

For my use case, it would make sense that all targets linking agains the dynamic framework would inherit the frameworks pods while sharing their existing compilation. Is there any way / What would be the best way to achieve this behavior and does it fall into CocoaPod's responsibility or would this be a plugin's responsibility?

**Comment by kommen** [comment] 2015-03-14 12:25
I think I ran into the same/similar issue yesterday, Oliver.

>  I ran into some compilation and other problems at first because the "Application" target doesn't "officially" depend on AFNetworking.

I looked into how Cocoapods bundles the frameworks and found that in the to the Framework dependencies available in the Application, the headers for the dependencies are not included.
The headers are actually striped by Cocoapods when installing:
https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/generator/embed_frameworks_script.rb#L67

For experimenting I removed the Headers filter from the rsync command in `Pods/Target Support/ Files/Pods/Pods-frameworks.sh`, which made the frameworks dependencies available in the application project.

As mentioned, I'm still experimenting and I don't know yet if this is a smart thing to do. E.g what happens when another framework included by the application does the same, but with a different AFNetworking version.

**Comment by neonichu** [comment] 2015-03-15 13:43
This is basically a duplicate of #3095 - the issue doesn't lie in the "unofficial" dependency itself, but in the fact that each target gets its own subdirectory for the produced frameworks and Xcode's build process will not find transitive dependencies there.

**Closed by neonichu** 2015-03-15 13:43 UTC
