### ISSUE TITLE
Missed module generated by CocoaPods in test target.

### ISSUE THREAD

**Issue by Antondomashnev** [CocoaPods/CocoaPods#6066] opened 2016-10-21 21:20 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow 🌈](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md). 

# Report

In the project with the both Swift and Objective-C source files. there is an issue with missing module generated from the CocoaPods dependency in the test target which is not missed in the project target. After some digging into the problem, I found that it's probably related to invalid `framework_search_path` for the test target. 
The project target contains following value in `framework_search_path`: `"${PODS_ROOT}/PaylevenFramework"`, however, the test target has empty `framework_search_path`. And after changing it manually to the same as the project target has, the issue is gone.

## What did you do?

I've added the CocoaPods dependency into the project target and included it into the test source file to be used.

## What did you expect to happen?

The test target can be successfully built.

## What happened instead?

The test target build fails with the error that module is not found.

### Stack

```
   CocoaPods : 1.1.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12 (16A323)
       Xcode : 8.0 (8A218a)
         Git : git version 2.8.4 (Apple Git-73)
Ruby lib dir : /Users/antondomashnev/.rvm/rubies/ruby-2.3.1/lib
Repositories : artsy - https://github.com/artsy/Specs @ 9c305e16a057d3062373aaaa1d8584bbd764fa55
               conichigmbh - git@github.com:conichiGMBH/ios-specs.git @ 482544a1d5e3f02f7122c887520c55d8cd211a3f
               conichigmbh-1 - https://github.com/conichiGMBH/ios-specs @ 482544a1d5e3f02f7122c887520c55d8cd211a3f
               czechboy0 - https://github.com/czechboy0/Podspecs.git @ faebf3543d12ab21efdac4a7af094f05c4a31805
               master - https://github.com/CocoaPods/Specs.git @ a8161c17517135625ed6b7f1d6b7f1f2f8bff69c
               master-1 - https://github.com/CocoaPods/Specs.git @ e8f2ddf369b5d8f6e52d269b40dc9e69b25b5a85
               master-2 - git@github.com:CocoaPods/Specs.git @ e8f2ddf369b5d8f6e52d269b40dc9e69b25b5a85
```

### Installation Source

```
Executable Path: /Users/antondomashnev/.rvm/gems/ruby-2.3.1/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.1.1
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
target 'PaylevenTest' do
  use_frameworks!

  pod 'PaylevenFramework'

  target 'PaylevenTestTests' do
    inherit! :search_paths
  end

end
```

## Project that demonstrates the issue

The project that reproduces the issue could be found [there](https://github.com/Antondomashnev/CocoaPodsIssueProject-2)

**Comment by benasher44** [comment] 2016-10-24 12:54
This is a duplicate of #5512. Going to close this one, but feel free to add any new information to the other ticket. Thanks!

**Closed by benasher44** 2016-10-24 12:54 UTC
