### ISSUE TITLE
Spec repo download is slow

### ISSUE THREAD

**Issue by sryze** [CocoaPods/CocoaPods#7106] opened 2017-10-06 06:51 UTC
Why does `pod install` download the whole spec repo including all history? Is it absolutely necessary? I mean, couldn't it do something like `git clone --depth 1`? It takes a huge amount of time, especially on a slow connection.

CocoaPods version: 1.3.1

**Comment by sryze** [comment] 2017-10-06 06:53
I had to wait for about 10 minutes and in the end I just got an error:

```
  $ /usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master --progress
  Cloning into 'master'...
  remote: Counting objects: 1583033, done.
  remote: Compressing objects: 100% (4533/4533), done.
  error: RPC failed; curl 56 SSLRead() return error -36 | 1.25 MiB/s
  fatal: The remote end hung up unexpectedly
  fatal: early EOF
  fatal: index-pack failed
[!] Unable to add a source with url `https://github.com/CocoaPods/Specs.git` named `master`.
(/usr/local/bin/git clone https://github.com/CocoaPods/Specs.git master --progress

Cloning into 'master'...
remote: Counting objects: 1583033, done.
remote: Compressing objects: 100% (4533/4533), done.
error: RPC failed; curl 56 SSLRead() return error -36 | 1.25 MiB/s
fatal: The remote end hung up unexpectedly
fatal: early EOF
fatal: index-pack failed
)
You can try adding it manually in `~/.cocoapods/repos` or via `pod repo add`.
```

and have to start again. This is very frustrating.

**Comment by orta** [comment] 2017-10-06 11:00
Thanks for the issue, I'm afraid it's a dupe of https://github.com/CocoaPods/CocoaPods/issues/7046 - you're welcome to help out with the problem

**Closed by orta** 2017-10-06 11:00 UTC

**Comment by braysonjohn148** [comment] 2020-01-21 16:26
[cocoapods] anybody with this ziped folder https://github.com/CocoaPods/Specs to provide us the link, taking long to clone from git. Please help, trying to download for month now.
