### ISSUE TITLE
[!] An error occurred on GitHub’s side. Please check GitHub’s status at https://status.github.com and try again later in case the pod is still not published.

### ISSUE THREAD

**Issue by jianghaoyuan2007** [CocoaPods/CocoaPods#6099] opened 2016-10-28 09:01 UTC
<img width="1251" alt="screen shot 2016-10-28 at 16 59 41" src="https://cloud.githubusercontent.com/assets/2723353/19801018/fc6778dc-9d2f-11e6-8dc6-1b51407ce12e.png">
<img width="1262" alt="screen shot 2016-10-28 at 17 00 31" src="https://cloud.githubusercontent.com/assets/2723353/19801038/14518d70-9d30-11e6-9887-370ba37b4bf2.png">

**I don't know how to fix it.**

**Comment by orta** [comment] 2016-10-28 09:06
Dupe of #6098

**Closed by orta** 2016-10-28 09:06 UTC

**Comment by jianghaoyuan2007** [comment] 2016-10-28 09:24
@orta Thank you so much.
