### ISSUE TITLE
NoMethodError - undefined method `name' for nil:NilClass

### ISSUE THREAD

**Issue by ivanruizscm** [CocoaPods/CocoaPods#4814] opened 2016-01-25 08:09 UTC
AFE0806015:MyProject ivan.ruiz$ pod install
Re-creating CocoaPods due to major version update.
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `ReachabilitySwift` from `https://github.com/ashleymills/Reachability.swift`, commit `ec4b33a7e439e5b203b0cae0f71383ca803ad031`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod install
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 1.0.0.beta.2
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 9f6151acfd15a93ddbcded567d6f44fd78bb7c86
               schibsted-sch-cocoapods-specs - git@github.schibsted.io:spt-marketplace/sch-cocoapods-specs.git @ 10354bec9e5a3d0d29a18ff05c2e20cdb51cbdc7
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.2
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
source 'git@github.schibsted.io:spt-marketplace/sch-cocoapods-specs.git'
use_frameworks!
pod 'TPKeyboardAvoiding', '1.2.11'
pod 'SVProgressHUD', '1.1.3'
pod 'ObjectMapper', '1.1.0'
pod "ATInternet-iOS-Swift-SDK/iOS",'2.0.8.2'
pod 'JLToast', '1.3.5'
pod 'Fabric'
pod 'Crashlytics'
pod 'RESideMenu', '4.0.7'
pod 'RealmSwift', '0.97.0'
pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
pod 'RxSwift', '2.0.0'
pod 'RxCocoa', '2.0.0'
pod 'RxBlocking', '2.0.0'
pod 'Moya/RxSwift', '5.3.0'
pod 'AsyncImageView'

def testing_pods
    # If you're using Xcode 7 / Swift 2
    pod 'Quick'
    pod 'Nimble'
end

target 'Tests' do
    testing_pods
end

post_install do |installer|
    plist_buddy = "/usr/libexec/PlistBuddy"

    installer.pods_project.targets.each do |target|

        # Strip alpha/beta notations from build numbers
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip

        stripped_version = /^([\d\.]*)/.match(version).captures[0]

        version_parts = stripped_version.split('.').map { |s| s.to_i }

        # ignore properly formatted versions
        unless version_parts.slice(0..2).join('.') == version

            major, minor, patch = version_parts

            minor ||= 0
            patch = 999

            fixed_version = "#{major}.#{minor}.#{patch}"

            puts "Changing version of #{target} from #{version} to #{fixed_version} to make it pass iTC verification."

            `#{plist_buddy} -c "Set CFBundleShortVersionString #{fixed_version}" "#{plist}"`
        end

        # Set the "Build Active Architecture Only" flag to NO
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `block (2 levels) in spec_is_platform_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `block in spec_is_platform_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `all?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `spec_is_platform_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:185:in `requirement_satisfied_by?'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:130:in `block (2 levels) in <class:Resolution>'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:356:in `attempt_to_activate_new_spec'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:319:in `attempt_to_activate'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:146:in `process_topmost_state'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:71:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolver.rb:41:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:62:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:554:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:552:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:223:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:147:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:146:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:109:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command/project.rb:97:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60name%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by segiddins** [comment] 2016-01-25 17:02
I can't reproduce the issue with the Podfile you provided, are there any other steps necessary to reproduce?

**Comment by ivanruizscm** [comment] 2016-01-26 08:21
Cocoapods beta?

**Comment by orta** [comment] 2016-01-26 09:15
It's also possible that `source 'git@github.schibsted.io:spt-marketplace/sch-cocoapods-specs.git'` could contain some Podspecs that override ones from trunk?

**Comment by ivanruizscm** [comment] 2016-01-26 14:25
I removed that source. Still getting the same. If i install the stable release seems to work. But i get some errors.

AFE0806015:ivan.ruiz$ pod update

---------------------------------------------
Error loading the plugin with path `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-0.2.1/lib/cocoapods_plugin.rb`.

LoadError - cannot load such file -- pod/command/deintegrate
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:135:in `rescue in require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:144:in `require'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-0.2.1/lib/cocoapods_plugin.rb:1:in `<top (required)>'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib/ruby/2.0.0/rubygems/core_ext/kernel_require.rb:55:in `require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:106:in `safe_require'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:32:in `block in load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command/plugin_manager.rb:31:in `load_plugins'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:304:in `block in run'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `each'
/Library/Ruby/Gems/2.0.0/gems/claide-0.9.1/lib/claide/command.rb:303:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
---------------------------------------------

Update all pods
[!] Unable to load a specification for the plugin `/Library/Ruby/Gems/2.0.0/gems/cocoapods-deintegrate-1.0.0.beta.1`
Updating local specs repositories

CocoaPods 1.0.0.beta.2 is available.
To update use: `gem install cocoapods --pre`
[!] This is a test version we'd love you to try.

For more information see http://blog.cocoapods.org
and the CHANGELOG for this version http://git.io/BaH8pQ.

Analyzing dependencies
Pre-downloading: `ReachabilitySwift` from `https://github.com/ashleymills/Reachability.swift`
Downloading dependencies
Using ATInternet-iOS-Swift-SDK (2.0.8.2)
Using Alamofire (3.1.5)
Using AsyncImageView (1.5.1)
Using Crashlytics (3.6.0)
Using Fabric (1.6.4)
Using JLToast (1.3.5)
Using Moya (5.3.0)
Using Nimble (3.1.0)
Using ObjectMapper (1.1.0)
Using Quick (0.9.0)
Using RESideMenu (4.0.7)
Installing ReachabilitySwift 2.3.3 (was 2.3.3)
Using Realm (0.97.0)
Using RealmSwift (0.97.0)
Using Result (1.0.1)
Using RxBlocking (2.0.0)
Using RxCocoa (2.0.0)
Using RxSwift (2.0.0)
Using SVProgressHUD (1.1.3)
Using TPKeyboardAvoiding (1.2.11)
Generating Pods project
Changing version of ATInternet-iOS-Swift-SDK from 2.0.8.2 to 2.0.999 to make it pass iTC verification.
Integrating client project
Sending stats
Sending stats
Pod installation complete! There are 17 dependencies from the Podfile and 20 total pods installed.
AFE0806015:ivan.ruiz$ sudo gem install cocoapods --pre
Password:
Fetching: cocoapods-1.0.0.beta.2.gem (100%)
Successfully installed cocoapods-1.0.0.beta.2
Parsing documentation for cocoapods-1.0.0.beta.2
Installing ri documentation for cocoapods-1.0.0.beta.2
1 gem installed
AFE0806015:ivan.ruiz$ pod update
Update all pods
Re-creating CocoaPods due to major version update.
Updating local specs repositories
Analyzing dependencies
Pre-downloading: `ReachabilitySwift` from `https://github.com/ashleymills/Reachability.swift`

――― MARKDOWN TEMPLATE ―――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

### Command

```
/usr/local/bin/pod update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?


### Stack

```
   CocoaPods : 1.0.0.beta.2
        Ruby : ruby 2.0.0p645 (2015-04-13 revision 50299) [universal.x86_64-darwin15]
    RubyGems : 2.0.14
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2 (7C68)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /System/Library/Frameworks/Ruby.framework/Versions/2.0/usr/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 18d91049c9ae78a895bfcc71dba23de5f51eb1e3
               schibsted-sch-cocoapods-specs - git@github.schibsted.io:spt-marketplace/sch-cocoapods-specs.git @ d24041df86fcc37649933d3c9c3cf527c5e3cf5d
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.2
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
use_frameworks!
pod 'TPKeyboardAvoiding', '1.2.11'
pod 'SVProgressHUD', '1.1.3'
pod 'ObjectMapper', '1.1.0'
pod "ATInternet-iOS-Swift-SDK/iOS",'2.0.8.2'
pod 'JLToast', '1.3.5'
pod 'Fabric'
pod 'Crashlytics'
pod 'RESideMenu', '4.0.7'
pod 'RealmSwift', '0.97.0'
pod 'ReachabilitySwift', git: 'https://github.com/ashleymills/Reachability.swift'
pod 'RxSwift', '2.0.0'
pod 'RxCocoa', '2.0.0'
pod 'RxBlocking', '2.0.0'
pod 'Moya/RxSwift', '5.3.0'
pod 'AsyncImageView'

def testing_pods
    # If you're using Xcode 7 / Swift 2
    pod 'Quick'
    pod 'Nimble'
end

target 'Tests' do
    testing_pods
end

post_install do |installer|
    plist_buddy = "/usr/libexec/PlistBuddy"

    installer.pods_project.targets.each do |target|

        # Strip alpha/beta notations from build numbers
        plist = "Pods/Target Support Files/#{target}/Info.plist"
        version = `#{plist_buddy} -c "Print CFBundleShortVersionString" "#{plist}"`.strip

        stripped_version = /^([\d\.]*)/.match(version).captures[0]

        version_parts = stripped_version.split('.').map { |s| s.to_i }

        # ignore properly formatted versions
        unless version_parts.slice(0..2).join('.') == version

            major, minor, patch = version_parts

            minor ||= 0
            patch = 999

            fixed_version = "#{major}.#{minor}.#{patch}"

            puts "Changing version of #{target} from #{version} to #{fixed_version} to make it pass iTC verification."

            `#{plist_buddy} -c "Set CFBundleShortVersionString #{fixed_version}" "#{plist}"`
        end

        # Set the "Build Active Architecture Only" flag to NO
        target.build_configurations.each do |config|
            config.build_settings['ONLY_ACTIVE_ARCH'] = 'NO'
        end
    end
end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `block (2 levels) in spec_is_platform_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `select'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `block in spec_is_platform_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `each'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `all?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `spec_is_platform_compatible?'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:185:in `requirement_satisfied_by?'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:130:in `block (2 levels) in <class:Resolution>'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:356:in `attempt_to_activate_new_spec'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:319:in `attempt_to_activate'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:146:in `process_topmost_state'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:71:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/molinillo-0.4.1/lib/molinillo/resolver.rb:41:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:62:in `resolve'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:554:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:552:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:223:in `analyze'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:147:in `block in resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/user_interface.rb:63:in `section'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:146:in `resolve_dependencies'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:109:in `install!'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command/project.rb:152:in `run'
/Library/Ruby/Gems/2.0.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/bin/pod:44:in `<top (required)>'
/usr/local/bin/pod:23:in `load'
/usr/local/bin/pod:23:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60name%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

AFE0806015:ivan.ruiz$

**Comment by seltzered** [comment] 2016-01-27 02:57
I'm observing this when installing a pod outside of the target block. Stumbled upon this when trying to install just ReactiveCocoa 4.x globally

### Command

```
/Users/vivek/.rvm/gems/ruby-2.3.0/bin/pod install
```

### Report

* What did you do?

Tried to install ReactiveCocoa ~>4.x to a new xcode project

NOTE: I am intentionally putting the pod outside the target block. My intent is to install it globally for both the project and anything else (in this scenario, I wanted it to link with swift playground files).

It is worth noting that I have installed ReactiveCocoa successfully with having the pod line within the target block.

* What did you expect to happen?

Installation to be successful with no errors.

* What happened instead?

Got an error of undefined method `name' for nil:NilClass

### Stack

```
   CocoaPods : 1.0.0.beta.2
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.2 (15C50)
       Xcode : 7.2 (7C68)
         Git : git version 2.2.1
Ruby lib dir : /Users/vivek/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a941a7938e58e0aaf12a50c96c93b06c01b6be7c
```

### Plugins

```
cocoapods-deintegrate : 1.0.0.beta.1
cocoapods-plugins     : 1.0.0.beta.1
cocoapods-search      : 1.0.0.beta.1
cocoapods-stats       : 1.0.0.beta.3
cocoapods-trunk       : 1.0.0.beta.1
cocoapods-try         : 1.0.0.beta.2
```

### Podfile

```ruby
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
# Uncomment this line if you're using Swift
use_frameworks!

pod 'ReactiveCocoa', '~> 4.x'
target 'ReactiveCocoa-SwiftPlayground' do

end
```

### Error

```
NoMethodError - undefined method `name' for nil:NilClass
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `block (2 levels) in spec_is_platform_compatible?'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `select'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:433:in `block in spec_is_platform_compatible?'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `each'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `all?'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `spec_is_platform_compatible?'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:185:in `requirement_satisfied_by?'
/Users/vivek/.rvm/gems/ruby-2.3.0@global/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:130:in `block (2 levels) in <class:Resolution>'
/Users/vivek/.rvm/gems/ruby-2.3.0@global/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:356:in `attempt_to_activate_new_spec'
/Users/vivek/.rvm/gems/ruby-2.3.0@global/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:319:in `attempt_to_activate'
/Users/vivek/.rvm/gems/ruby-2.3.0@global/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:146:in `process_topmost_state'
/Users/vivek/.rvm/gems/ruby-2.3.0@global/gems/molinillo-0.4.1/lib/molinillo/resolution.rb:71:in `resolve'
/Users/vivek/.rvm/gems/ruby-2.3.0@global/gems/molinillo-0.4.1/lib/molinillo/resolver.rb:41:in `resolve'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:62:in `resolve'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:554:in `block in resolve_dependencies'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/user_interface.rb:63:in `section'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:552:in `resolve_dependencies'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer/analyzer.rb:73:in `analyze'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:223:in `analyze'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:147:in `block in resolve_dependencies'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/user_interface.rb:63:in `section'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:146:in `resolve_dependencies'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/installer.rb:109:in `install!'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command/project.rb:67:in `run_install_with_update'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command/project.rb:97:in `run'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/claide-1.0.0.beta.1/lib/claide/command.rb:312:in `run'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/command.rb:48:in `run'
/Users/vivek/.rvm/gems/ruby-2.3.0/gems/cocoapods-1.0.0.beta.2/bin/pod:44:in `<top (required)>'
/Users/vivek/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/vivek/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/vivek/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/vivek/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=undefined+method+%60name%27+for+nil%3ANilClass&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

**Comment by orta** [comment] 2016-01-27 06:46
These podfiles shouldn't be able to work with pods outside a target definition I think

**Comment by segiddins** [comment] 2016-02-25 04:45
I believe this has been fixed in beta 4?

**Comment by ivanruizscm** [comment] 2016-02-25 07:33
@segiddins nope

**Comment by segiddins** [comment] 2016-03-10 17:17
I can't reproduce this issue with any of the podfiles posted in this thread.

**Comment by cjcaufield** [comment] 2016-03-15 09:41
I got the exact same error message in a simpler case: #5032.  Not sure if it's related.

**Comment by neonichu** [comment] 2016-05-01 17:14
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Closed by neonichu** 2016-05-01 17:14 UTC

**Comment by vinceis1337** [comment] 2016-05-02 21:56
/Library/Ruby/Gems/2.0.0/gems/cocoapods-1.0.0.beta.2/lib/cocoapods/resolver.rb:432:in `spec_is_platform_compatible?'

led me to believe it might have to do with 

```
# Uncomment this line to define a global platform for your project
# platform :ios, '8.0'
```

Indeed when I uncommented it, it stopped throwing this error.
