### ISSUE TITLE
Git Submodule Regression(?)

### ISSUE THREAD

**Issue by RLovelett** [CocoaPods/CocoaPods#5539] opened 2016-06-16 21:02 UTC
🌈

* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I tried to install some pods. One had a git submodule.

## What did you expect to happen?

Install all pod dependencies correctly.

## What happened instead?

It tried to perform a shallow clone of the submodule and that failed. I think this is a regression of [Shallow clone for submodule doesn't work for some Git repo](https://github.com/CocoaPods/cocoapods-downloader/issues/32). Though I'm not 100% sure.

To isolate the issue from CocoaPods I tried running the following Git commands. The first succeeded the second did not. The second fails with the same error shown in the CocoaPods error message. Notice that `--depth 1` is all that changed between the two commands.

```
✅ git clone https://github.com/RLovelett/Argo.git --single-branch --depth 1 --branch rl-swift-3 --recursive && rm -rf Argo
⛔️ git clone https://github.com/RLovelett/Argo.git --single-branch --branch rl-swift-3 --recursive && rm -rf Argo
```

Full CocoaPods error below.

```
$ bundle exec pod install                                                                                                                                                                                  
Analyzing dependencies
Pre-downloading: `Argo` from `https://github.com/RLovelett/Argo.git`, branch `rl-swift-3`, submodules `true`

[!] Error installing Argo
[!] /usr/local/bin/git clone https://github.com/RLovelett/Argo.git /var/folders/cv/6rpdnxyn7qv8vql_5gbvpjz00000gn/T/d20160616-24572-6kdfqn --template= --single-branch --depth 1 --branch rl-swift-3 --recursive

Cloning into '/var/folders/cv/6rpdnxyn7qv8vql_5gbvpjz00000gn/T/d20160616-24572-6kdfqn'...
Submodule 'Carthage/Checkouts/Curry' (https://github.com/RLovelett/Curry.git) registered for path 'Carthage/Checkouts/Curry'
Submodule 'Carthage/Checkouts/Runes' (https://github.com/RLovelett/Runes.git) registered for path 'Carthage/Checkouts/Runes'
Cloning into '/private/var/folders/cv/6rpdnxyn7qv8vql_5gbvpjz00000gn/T/d20160616-24572-6kdfqn/Carthage/Checkouts/Curry'...
Cloning into '/private/var/folders/cv/6rpdnxyn7qv8vql_5gbvpjz00000gn/T/d20160616-24572-6kdfqn/Carthage/Checkouts/Runes'...
error: no such remote ref 0acc6075ab338c65bad75cddf41ba4c9d1df1fdb
Fetched in submodule path 'Carthage/Checkouts/Curry', but it did not contain 0acc6075ab338c65bad75cddf41ba4c9d1df1fdb. Direct fetching of that commit failed.
```

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.1.5p273 (2014-11-13 revision 48405) [x86_64-darwin14.0]
    RubyGems : 2.4.3
        Host : Mac OS X 10.11.5 (15F34)
       Xcode : 8.0 (8S128d)
         Git : git version 2.9.0
Ruby lib dir : /Users/lovelett/.rvm/rubies/ruby-2.1.5/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 56460a0758055947b5b8b9745be65d7e7545d476
```

### Installation Source

```
Executable Path: /Users/lovelett/.rvm/gems/ruby-2.1.5/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.0.0
slather               : 2.2.1
```

### Podfile

```ruby
source 'https://github.com/CocoaPods/Specs.git'
platform :ios, '9.0'
use_frameworks!

def shared_pods
  pod 'zipzap', '~> 8.1.0'
  pod 'Argo', git: 'https://github.com/RLovelett/Argo.git', branch: 'rl-swift-3', submodules: true
  pod 'Curry', git: 'https://github.com/RLovelett/Curry.git', branch: 'rl-swift-3'
end

target 'Tools' do
  shared_pods

  target 'ToolsTests' do
    inherit! :search_paths
    shared_pods
  end
end
```

**Comment by RLovelett** [comment] 2016-06-16 21:11
Based on the change in PR [#33 Avoid shallow cloning git submodules](https://github.com/CocoaPods/cocoapods-downloader/pull/33). I changed [git.rb](https://github.com/CocoaPods/cocoapods-downloader/blob/0803d2280c14347e03cc5753efdca04e3697552c/lib/cocoapods-downloader/git.rb#L107) to be `if shallow_clone && !options[:commit] && !options[:submodules]`. After doing that the `pod install` works again.

It's a work-around to get me going. Though I don't know if this is an acceptable patch.

**Comment by colindean** [comment] 2016-06-20 21:54
I encountered this, as well. I documented it on sonsongithub/reddift/issues/190.

**Comment by segiddins** [comment] 2016-06-21 00:25
all of the https://github.com/CocoaPods/cocoapods-downloader specs pass with git 2.9...

**Comment by DanToml** [comment] 2016-06-24 17:29
This is a duplicate of https://github.com/CocoaPods/CocoaPods/issues/5555 and has been fixed in https://github.com/CocoaPods/cocoapods-downloader/pull/58

**Closed** 2016-06-24 17:29 UTC
