### ISSUE TITLE
Code signing error on macOS

### ISSUE THREAD

**Issue by AndriyGo** [CocoaPods/CocoaPods#8719] opened 2019-04-17 16:03 UTC
I am completely puzzled as to why I get a code signing error AFTER my binary is uploaded to the Mac App Store. I thought that this error is related to Firebase and opened an issue [there](https://github.com/firebase/firebase-ios-sdk/issues/2836). However, it was suggested to reopen it here because it seems that CocoaPods processes [gRPC-Core.podspec](https://github.com/grpc/grpc/blob/master/gRPC-Core.podspec) incorrectly.

I have the following pods attachec to my macOS app:

```
pod 'FirebaseCore'
    pod 'FirebaseAuth'
    pod 'FirebaseFirestore'
    pod 'FirebaseFunctions'
```

after I upload my binary I receive the following error in an email:

```
Dear Developer,

We identified one or more issues with a recent delivery for your app, "Driving Theory Test 2019 (UK)". Please correct the following issues, then upload again.

Invalid Signature - The main app bundle Driving Theory Test 2019 (UK) at path Driving Theory Test 2019 (UK).app has following signing error(s): --prepared:/Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/GoogleUtilities.framework/Versions/Current/. --validated:/Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/GoogleUtilities.framework/Versions/Current/. --prepared:/Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework/Versions/Current/. --validated:/Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework/Versions/Current/. /Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app: embedded framework contains modified or invalid version In subcomponent: /Volumes/data01/app_data/dstr/mz_2944365260435506569dir/mz_252358220600660519dir/MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

Invalid Signature - The nested app bundle grpc at path Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework has following signing error(s): bundle format unrecognized, invalid, or unsuitable . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

Invalid Signature - The nested app bundle grpcpp at path Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpcpp.framework has following signing error(s): bundle format unrecognized, invalid, or unsuitable . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

Invalid Signature - The nested app bundle openssl_grpc at path Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework has following signing error(s): bundle format unrecognized, invalid, or unsuitable . Refer to the Code Signing and Application Sandboxing Guide at http://developer.apple.com/library/mac/#documentation/Security/Conceptual/CodeSigningGuide/AboutCS/AboutCS.html and Technical Note 2206 at https://developer.apple.com/library/mac/technotes/tn2206/_index.html for more information.

Unable to Sign - This package doesn't meet the current code signing requirements. For more information, see the Code Signing and Application Sandboxing Guide and Technical Note 2206.

Specifically, codesign generated the following error:

        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework/Versions/src: bundle format unrecognized, invalid, or unsuitable
        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpcpp.framework/Versions/src: bundle format unrecognized, invalid, or unsuitable
        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/crypto: bundle format unrecognized, invalid, or unsuitable
        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/ssl: bundle format unrecognized, invalid, or unsuitable
        MY_BUNDLE.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/third_party: bundle format unrecognized, invalid, or unsuitable
Malformed Framework - The framework bundle grpc (Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpc.framework) Info.plist for Versions/src is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Malformed Framework - The framework bundle grpcpp (Driving Theory Test 2019 (UK).app/Contents/Frameworks/grpcpp.framework) Info.plist for Versions/src is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Malformed Framework - The framework bundle openssl_grpc (Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework) Info.plist for Versions/crypto is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Malformed Framework - The framework bundle openssl_grpc (Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework) Info.plist for Versions/ssl is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Malformed Framework - The framework bundle openssl_grpc (Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework) Info.plist for Versions/third_party is either missing or malformed. Please provide a valid Info.plist. Refer to the Anatomy of Framework Bundles for more information.

Best regards,

The App Store Team
```

I am not surre if this is a right place to post my issue, but I hope that someone will be able to assist me or redirect me to the right place.

**Comment by dnkoutso** [comment] 2019-04-17 16:05
Most likely not the right place or at least requires a sample app clearly demonstrating the issue and a list of steps for us to repro.

Recommend opening in StackOverflow under `cocoapods` tag.

**Comment by paulb777** [comment] 2019-04-17 16:54
Looks like #7788, except that both private and public headers are copied from the wrong place in macOS style frameworks.  See the [workaround](https://github.com/CocoaPods/CocoaPods/issues/7788#issuecomment-441753907) there.

It's not clear to me why any of the copies are needed.

**Comment by AndriyGo** [comment] 2019-04-17 21:56
@paulb777 I have added the code below to my PodFile (which I thought was the mentioned workaround), but the error still remains :(

```
post_install do |installer|
    installer.pods_project.targets.each do |target|
        if target.name.start_with?('BoringSSL') or target.name.start_with?('gRPC')
            # Ensure uniqueness of the files listed in the "Copy Headers" steps.
            target.build_phases.each do |phase|
                if phase.is_a?(Xcodeproj::Project::Object::PBXHeadersBuildPhase)
                    path_to_ref = {}
                    phase.files_references.uniq.each do |file|
                        path_to_ref[file.path] = file
                        phase.remove_file_reference file
                    end
                    path_to_ref.values.each do |ref|
                        phase.add_file_reference ref
                    end
                end
            end
        end
    end
end
```

**Comment by paulb777** [comment] 2019-04-17 21:59
@AndriyGo Did the Copy Headers Build phases go away in the gRPC build targets?

**Comment by AndriyGo** [comment] 2019-04-17 23:09
@paulb777 yes it did. Here is what I see in build phases:

<img width="939" alt="Screenshot 2019-04-18 at 02 08 38" src="https://user-images.githubusercontent.com/7107815/56326487-e9ee6880-617e-11e9-9b70-a7bdede9d96e.png">

**Comment by paulb777** [comment] 2019-04-18 00:39
@AndriyGo Just to confirm, that is one of the gRPC build targets? And you might need to wipe DerivedData.  All of the `Copy ../../`'s in the following screenshot should be deleted:

<img width="873" alt="Screen Shot 2019-04-17 at 5 36 16 PM" src="https://user-images.githubusercontent.com/73870/56329246-7b39ec80-6137-11e9-8572-e09f068782b8.png">

**Comment by AndriyGo** [comment] 2019-04-18 14:06
Here is what I have now:

<img width="1111" alt="Screenshot 2019-04-18 at 16 58 14" src="https://user-images.githubusercontent.com/7107815/56366196-37a8b680-61fb-11e9-8aad-2e04cb18772b.png">

I am still getting an email with error, although this time it says:

```
Specifically, codesign generated the following error:

        XXX.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/crypto: bundle format unrecognized, invalid, or unsuitable
        XXX.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/ssl: bundle format unrecognized, invalid, or unsuitable
        XXX.pkg/Payload/Driving Theory Test 2019 (UK).app/Contents/Frameworks/openssl_grpc.framework/Versions/third_party: bundle format unrecognized, invalid, or unsuitable

```

**Comment by paulb777** [comment] 2019-04-18 14:12
I believe those come from the `BoringSSL-GRPC-macOS` target.

**Comment by AndriyGo** [comment] 2019-04-18 15:48
@paulb777 yes, it works! Thank you very much

**Comment by paulb777** [comment] 2019-04-20 22:32
Glad it's working for you. I'll close this and continue any subsequent discussion of the root cause and solution in #7788

**Closed by paulb777** 2019-04-20 22:32 UTC
