### ISSUE TITLE
CocoaPods leaves dSYMs for unused architectures in archive

### ISSUE THREAD

**Issue by chefnobody** [CocoaPods/CocoaPods#7111] opened 2017-10-06 19:49 UTC
## What did you do?
1. Created a new empty iOS project with Xcode 9.0. Then closed it.
2. Ran `pod init`.
3. In the pod file, I added one framework `TealiumIOS` ([docs here](https://github.com/tealium/tealium-ios))
4. Ran `pod install` to bring in TealiumIOS.
5. Opened the `SampleApp.xcworkspace` with Xcode and archived my application.
6. Next, I inspected the symbols for each architecture in the archive's `dSYMs` directory. Here they are after `cd`-ing to my archive and running `dwarfdump`:

```
dSYMs $ cd ~/Library/Developer/Xcode/Archives/2017-10-06/SampleApp\ 10-6-17\,\ 3.21\ PM.xcarchive/dSYMs
dSYMs $ dwarfdump --uuid *
UUID: C56F7ABF-DFD7-3ABC-A9F6-0B172E7B9F10 (arm64) SampleApp.app.dSYM/Contents/Resources/DWARF/SampleApp
UUID: EA990B6D-CAF9-3B87-8D99-D04A4FA36537 (i386) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: 1306BCB7-953D-3FC5-956E-40B85B8986A1 (x86_64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: CF845CCB-4E31-379F-8835-DA3B16734722 (armv7) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
UUID: B353F154-B6B4-3FCA-AA18-C18E400EC139 (arm64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
```

## What did you expect to happen?

I would expect that in addition to stripping the invalid architectures here, that CocoaPods would also strip the invalid symbol files (if any):
https://github.com/CocoaPods/CocoaPods/blob/2fb2db21016f82806d3940013bda30ffa941151b/lib/cocoapods/generator/embed_frameworks_script.rb#L123-L138 

More precisely I would expect that the symbol files left in my archive with UUIDs `EA990B6D-CAF9-3B87-8D99-D04A4FA36537` (`i386`) and `1306BCB7-953D-3FC5-956E-40B85B8986A1` (`x86_64`) would be stripped from my archive because the App Store does not need or expect symbols for these architectures. In fact, iTunes Connect now warns about uploads of symbols that don't correspond to any binaries:
```
Too many symbol files - These symbols have no corresponding slice in any binary [1306BCB7-953D-3FC5-956E-40B85B8986A1.symbols, EA990B6D-CAF9-3B87-8D99-D04A4FA36537.symbols]
```

## What happened instead?

The `i386` and `x86_64` symbols were left in the archive.

### Stack

```
   CocoaPods : 1.3.1
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin16]
    RubyGems : 2.5.1
        Host : Mac OS X 10.12.6 (16G29)
       Xcode : 9.0 (9A235)
         Git : git version 2.13.5 (Apple Git-94)
Ruby lib dir : /Users/aconnolly/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ 5a6cc2e32ae83d327d318296c4fb69125e8fc3ab
```

### Installation Source

```
Executable Path: /Users/aconnolly/.rvm/gems/ruby-2.3.0/bin/pod
```

### Plugins

```
claide-plugins        : 0.9.2
cocoapods-deintegrate : 1.0.1
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.3.0
cocoapods-try         : 1.1.0
```

### Podfile

```ruby
# Uncomment the next line to define a global platform for your project
platform :ios, '10.0'

target 'SampleApp' do
  # Comment the next line if you're not using Swift and don't want to use dynamic frameworks
  use_frameworks!

  # Pods for SampleApp
  pod 'TealiumIOS', '5.3.0'

  target 'SampleAppTests' do
    inherit! :search_paths
    # Pods for testing
  end

  target 'SampleAppUITests' do
    inherit! :search_paths
    # Pods for testing
  end

end
```
## Project that demonstrates the issue
https://github.com/chefnobody/SampleApp

## Thoughts / Findings:
- It seems Carthage had a similar problem back in 2016 and resolved it (I think): https://github.com/Carthage/Carthage/pull/1023
- This issue has been identified elsewhere by other Framework makers: https://github.com/mapbox/mapbox-gl-native/issues/10137
- I think this is the step in the generated `-frameworks.sh` where the copy of all dSYMs happens. But I could be wrong: https://github.com/CocoaPods/CocoaPods/blob/2fb2db21016f82806d3940013bda30ffa941151b/lib/cocoapods/generator/embed_frameworks_script.rb#L98-L105

**Comment by dnkoutso** [comment] 2017-10-06 19:50
Interesting thanks! Will take a look.

**Comment by dnkoutso** [comment] 2017-10-06 19:57
@chefnobody excellent report. Confirmed the same and working on a fix.

**Comment by chefnobody** [comment] 2017-10-06 19:58
For sure. Stoked!

**Comment by dnkoutso** [comment] 2017-10-06 22:25
@chefnobody fix https://github.com/CocoaPods/CocoaPods/pull/7112

Do you use bundler? If so you can point to my branch and verify this? I did

**Comment by chefnobody** [comment] 2017-10-07 00:52
@dnkoutso Thanks for knocking that out! Quickly though, you'll have to forgive me, I'm new to some of this.... 

I started using bundler in my sample app like so and pointed the CocoaPods gem at your branch:
```
gem "cocoapods", :git => 'https://github.com/dnkoutso/CocoaPods.git', :branch => 'strip_dysm'
```
Next, I ran `bundle install` and everything seemed to go well. Bundler reported that CocoaPods was pointing at your last commit on your branch (https://github.com/dnkoutso/CocoaPods/commit/0b8fd4cf2f69f50d7a7f105736f93cf36be8bb97), .... so that seems right.
```
...
Using cocoapods 1.4.0.beta.1 from https://github.com/dnkoutso/CocoaPods.git (at strip_dysm@0b8fd4c)
Bundle complete! 1 Gemfile dependency, 28 gems now installed.
Use `bundle info [gemname]` to see where a bundled gem is installed.
```
However, running `pod install` threw the following error and stack trace:
```
NoMethodError - undefined method `script_phases' for #<Pod::Specification::Consumer:0x007fad8d2016f0>
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/target/pod_target.rb:191:in `map'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/target/pod_target.rb:191:in `script_phases'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/target/pod_target.rb:197:in `contains_script_phases?'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/target/pod_target.rb:166:in `should_build?'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer/xcode/target_validator.rb:50:in `block (3 levels) in verify_no_duplicate_framework_and_library_names'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer/xcode/target_validator.rb:50:in `select'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer/xcode/target_validator.rb:50:in `block (2 levels) in verify_no_duplicate_framework_and_library_names'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer/xcode/target_validator.rb:45:in `each'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer/xcode/target_validator.rb:45:in `block in verify_no_duplicate_framework_and_library_names'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer/xcode/target_validator.rb:44:in `each'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer/xcode/target_validator.rb:44:in `verify_no_duplicate_framework_and_library_names'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer/xcode/target_validator.rb:35:in `validate!'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer.rb:406:in `validate_targets'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/installer.rb:118:in `install!'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/command/install.rb:41:in `run'
/Users/aconnolly/.rvm/gems/ruby-2.3.0@global/gems/claide-1.0.2/lib/claide/command.rb:334:in `run'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/command.rb:52:in `run'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/bin/pod:55:in `<top (required)>'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bin/pod:23:in `load'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bin/pod:23:in `<main>'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `eval'
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bin/ruby_executable_hooks:15:in `<main>'
```

There's a good chance I'm not utilizing your branch correctly. Any tips?

**Comment by amorde** [comment] 2017-10-07 01:07
@chefnobody you need to use the executable found in at `bin/pod` in the bundler checkout. One handy way to use it is to make an alias, like `alias dpod=/path/to/cocoapods/bin/pod` then do `dpod install`

**Comment by chefnobody** [comment] 2017-10-07 01:47
@amorde If I understand correctly, you're saying that when I run `pod install` from my SampleApp bundler-managed project that is specifying @dnkoutso's branch of the CocoaPod project, that `pod` is not the correct executable? If that is so, why does the stack trace seem to point to the custom `cocoapods` gem?
```
/Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/lib/cocoapods/target/pod_target.rb:191:in `map'
```
At any rate, I tried referencing that specific executable directly per the path specified by `bundle info cocoapods`:
```
SampleApp $ bundle info cocoapods
  * cocoapods (1.4.0.beta.1 0b8fd4c)
	Summary: The Cocoa library package manager.
	Homepage: https://github.com/CocoaPods/CocoaPods
	Path: /Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69
SampleApp $ ls -al /Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69
```
But I get the following:
```
$ /Users/aconnolly/.rvm/gems/ruby-2.3.0/bundler/gems/CocoaPods-0b8fd4cf2f69/bin/pod install
Could not find rake-10.5.0 in any of the sources
Run `bundle install` to install missing gems.
```
Running `bundle install` again doesn't resolve this missing gem issue. I've also created an alias per your recommendation that points at the same custom CocoaPods gem but I get the same error. 

I'm missing something simple here.

**Comment by amorde** [comment] 2017-10-07 01:57
Oh oops! Sorry I missed that - ignore what I said :)

**Comment by justinseanmartin** [comment] 2017-10-07 03:07
I think you'll also need to point at the latest SHA of cocoapods-core as well for some other changes to be kept in sync.

**Comment by dnkoutso** [comment] 2017-10-07 15:46
@chefnobody, @justinseanmartin is correct you also need to bump and use master branch of `cocoapods-core` gem.

This is the repo https://github.com/CocoaPods/Core

**Comment by chefnobody** [comment] 2017-10-07 16:42
@justinseanmartin @dnkoutso Pretty sure I've got it now. 

1. Added the CocoaPods Core gem to my Gemfile and pointed at `master`. Which should be good looking at the commits there.
2. Ran `bundle install` and `pod install` successfully.
3. Archived the SampleApp project. 
4. Drilled into archive's dSYMS and viola. No simulator slices 👍 

```
dSYMs 🍔  $ dwarfdump --uuid *
UUID: C56F7ABF-DFD7-3ABC-A9F6-0B172E7B9F10 (arm64) SampleApp.app.dSYM/Contents/Resources/DWARF/SampleApp
UUID: B353F154-B6B4-3FCA-AA18-C18E400EC139 (arm64) TealiumIOS.framework.dSYM/Contents/Resources/DWARF/TealiumIOS
```

**Comment by dnkoutso** [comment] 2017-10-07 17:07
perfect! should land this this coming week and hopefully get a 1.4.0.beta.2 out.

**Comment by chefnobody** [comment] 2017-10-07 17:10
Awesome! Thanks

**Comment by dnkoutso** [comment] 2017-10-08 15:35
Merged.

**Closed** 2017-10-08 15:35 UTC
Labels: d1:easy, s2:confirmed, s3:detailed

**Comment by chefnobody** [comment] 2017-10-16 20:40
@dnkoutso Any idea when this will ship?

**Comment by dnkoutso** [comment] 2017-10-16 20:41
@chefnobody possibly this week with 1.4.0.beta.2.

**Comment by chefnobody** [comment] 2017-10-17 14:19
@dnkoutso One last question, if I wanted to leverage this beta would I do so the same way I did before with my Sample project and Bundler and your branch that has this fix? By that I mean pointing at a git branch or tag for both CocoaPods and CocoaPods Core? If so where do I find those branch/tag names?

**Comment by dnkoutso** [comment] 2017-10-17 14:49
@chefnobody see this http://bundler.io/v1.12/git.html

**Comment by dnkoutso** [comment] 2017-10-17 14:50
Can use
```
gem 'cococapods', :git => 'https://github.com/cocoapods/cocoapods.git', :ref => 'SHA'
```

**Comment by Yourney** [comment] 2018-04-29 15:26
I use Cocoapods 1.5.0 and today I again received the 'Too many symbol files' email from Apple.
Is there anything that I should do after updating cocoapods? I did:
- pod update
- pod install
- clean build folder
- archive

pod --version returns 1.5.0.

Thanks!
Wouter

**Comment by dnkoutso** [comment] 2018-04-29 17:08
@Yourney please provide a sample app and demonstrate the issue clearly.

**Comment by chefnobody** [comment] 2018-05-08 16:41
@Yourney You should be able to create a vanilla iOS app ([or fork mine](https://github.com/chefnobody/SampleApp)) and follow my steps above (using whatever version of CocoaPods you think has this issue) to verify.

**Comment by armcknight** [comment] 2018-05-08 23:40
I've been looking into this for myself and just found this ticket. Using cocoapods 1.5.0 and Xcode 9.3.

I listed all the UUIDs in my archive with this command: `find /path/to/.../archive/dSYMs -type d -name "DWARF" | xargs -I@ find @ -type f | xargs -tI@ dwarfdump -u @`

That'll show you: dSYM and path on disk, architecture, UUID. In my project, I noticed that there were both `arm64` _and_ `armv7` slices for targets in `Pods.xcodeproj`, whereas my app target only has `arm64` slices.

Then I looked at the architectures being build with `xcodebuild`:
```
# my app
$ xcodebuild -showBuildSettings | grep ARCHS
    ARCHS = arm64
    ARCHS_STANDARD = arm64
    ARCHS_STANDARD_32_64_BIT = armv7 arm64
    ARCHS_STANDARD_32_BIT = armv7
    ARCHS_STANDARD_64_BIT = arm64
    ARCHS_STANDARD_INCLUDING_64_BIT = arm64
    ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
    VALID_ARCHS = arm64 armv7 armv7s

# cocoapods
$ xcodebuild -project Pods/Pods.xcodeproj/ -showBuildSettings | grep ARCHS
    ARCHS = armv7 arm64
    ARCHS_STANDARD = armv7 arm64
    ARCHS_STANDARD_32_64_BIT = armv7 arm64
    ARCHS_STANDARD_32_BIT = armv7
    ARCHS_STANDARD_64_BIT = arm64
    ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
    ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
    VALID_ARCHS = arm64 armv7 armv7s
```

A problem I see is that `ARCHS` resolves to different values between my app and cocoapods framework targets, even though they are all set to `$(ARCHS_STANDARD)`. I don't observe this if I create a new Xcode project, create app and framework targets and run the same check:
```
$ xcodebuild -showBuildSettings -scheme test-fw | grep ARCHS
    ARCHS = arm64
    ARCHS_STANDARD = arm64
    ARCHS_STANDARD_32_64_BIT = armv7 arm64
    ARCHS_STANDARD_32_BIT = armv7
    ARCHS_STANDARD_64_BIT = arm64
    ARCHS_STANDARD_INCLUDING_64_BIT = arm64
    ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
    VALID_ARCHS = arm64 armv7 armv7s
```

Here's my workaround in my Podfile:
```
post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['ARCHS'] = 'arm64'
    end
end
```

I've confirmed this produces an xcarchive without the frameworks' armv7 slices, just waiting to hear back from iTunes Connect.

**Comment by segiddins** [comment] 2018-05-09 03:28
huh, what are the object versions for your project vs the pods project, out of curiosity?

**Comment by dnkoutso** [comment] 2018-05-09 03:39
Gut feeling tells me the users xcodeproj is on Xcode 9 which is 64bit only and the one generated from pods is with 8 or earlier hence the discrepancy between the `$(ARCHS_STANDARD)` value.

**Comment by Yourney** [comment] 2018-05-09 06:38
@dnkoutso  Gut feeling is right!
My project is iOS 11 only, built on xcode 9.3.
Dependencies have for instance
  s.platform     = :ios, "10.0"
in their podspec file.
I will try the armyknight workaround to see if that satisfies iTunesConnect.

Would it be an idea to set the validArchs (of the main project) to arm64 and changing armcknight's workaround so that all dependencies get the main project's validArch?

Side question: Is thee a performance isue on the iPhone 5S when building arm64 only?

**Comment by armcknight** [comment] 2018-05-09 13:51
Both my project and pods project have object version 46.

Not sure if it's relevant but I created my project in Xcode 8 IIRC. I ran `pod deintegrate` and `pod install` after upgrading to cocoapods 1.5.0. My podfile declares a platform version of iOS 11, but not sure how podspecs' platform versions would affect this... I'm sure there are several that go before iOS 11.

**Comment by anonym24** [comment] 2018-05-16 10:00
so why I meet this error? 

is it fixed or not?

```
platform :ios, '11.0'
use_frameworks!
target 'MyApp'
pod 'OpenCV'
pod 'VGPlayer', '~> 0.2.0'
pod 'TesseractOCRiOS'

post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
    end
  end
end
```

**Comment by anonym24** [comment] 2018-05-16 10:03
@armcknight how can I set more cpus using your solution?:

```
post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['ARCHS'] = 'arm64'
    end
end

```

**Comment by anonym24** [comment] 2018-05-16 10:07
I will also try (only with arm64, who needs those 32 cpus anyway?):

```
post_install do |installer|
  installer.pods_project.targets.each do |target|
    target.build_configurations.each do |config|
      config.build_settings['ENABLE_BITCODE'] = 'NO'
      config.build_settings['ARCHS'] = 'arm64'
    end
  end
end
```

**Comment by anonym24** [comment] 2018-05-16 10:37
yes, no errors from apple anymore

also don't forget to remove all other cpus in your target settings:

![screenshot at may 16 13-37-25](https://user-images.githubusercontent.com/8851301/40112327-4fa60cac-590e-11e8-837a-b0110e119648.png)

**Comment by Yourney** [comment] 2018-05-16 14:47
I have changed the ValidArchs of my main project to Arm64 only.

Now Cocoapods generates the dependency-projects with 'only arm64' too ... brilliant.

dwarfdump --uuid *  gives me just one dSYM per dependency.
So that looks great!
No need to add the bit of scripting to the Podfile.

I still think that there is a problem somewhere. I think it might be a bug @ Apple. It seems like xcode generates one dSYM file per architecture, and iTunesConnect does not want that.
However, this problem only occurs if an app should still support 32 bit code, for instance to be able to run on an iPhone 5 or older.

Apple reports it as a warning, so it does not break anything.

**Comment by navaneet** [comment] 2018-07-02 15:12
This issue is still happening, when will this get fixed?

**Comment by SebastianBoldt** [comment] 2018-08-02 09:01
Same issue over here. The fix of @Yourney does not solve the issue for me. I changed the supported architectures of my main target to arm64 but if i archive and dwarfdump later armv7 is still present.
My Deployment-Target is iOS11 so there is no need for Xcode to create those files. I will stick to the post install phase.

**Comment by SebastianBoldt** [comment] 2018-08-03 06:28
@amorde Awesome. So Cocoapods 1.6.0 will provide this fix if i see this right, correct?

**Comment by amorde** [comment] 2018-08-03 16:45
Yup!

**Comment by xaphod** [comment] 2019-02-18 02:25
I had this issue and after much frustration, found my problem required different steps.

Background: project settings for `Valid Architectures` were "arm64 arm7 arm7s" which was fine until minimum iOS level was raised from iOS 11 -> iOS 12, but that's not correct for iOS 12 because no arm7 or arm7s devices support iOS 12, so then Apple starts emailing "too many symbols..." on any archive upload

To fix:
- update Cocoapods to at least 1.6.0
- ... so I changed the _target_'s Valid Architectures to "arm64 arm64e". That was my mistake: I needed to change the _Project_'s Valid Architectures instead of the target's
- ... then my Apple Watch targets caused problems when uploading the archives to Apple. I needed to override both the Watch and Watch Extension's valid archs to "arm64_32 arm7k"

Then finally, all was well.
Anyways, hope this helps someone. Including me, if I forget and end up here again.

**Comment by DevAndArtist** [comment] 2019-04-04 15:11
I had this issue today. I used @armcknight method to check the arch's and had the similar issue with `ARCH`. In my case I have three targets in our project, two are release targets with a slightly different slice of the app. First release target was set to have minimal deployment target `iOS 10.3` while the other target was set to `iOS 11`. The one with `iOS 11` deployment target had of course only `ARCHS = arm64` while the shared pods had `ARCHS = armv7 arm64`. I decreased the deployment target of the second target to `iOS 10.3`, recompiled it and now it reports `ARCHS = armv7 arm64` as well. Will see if this resolves the issue in app store connect now.

**Comment by acedened** [comment] 2019-08-29 09:29
After adding `config.build_settings['ARCHS'] = 'arm64'` I started to get bunch of warnings saying "Mapping architecture arm64 to x86_64"
Does anybody know how to fix that?

**Comment by rpassis** [comment] 2020-01-13 15:09
2 things about this issue:

1. Rather than change the valid ARCHS setting, it's probably best to change the deployment target of your Pods to whatever version you support, and Xcode will infer the correct/valid architectures for that OS version.

Overriding architectures is problematic - for example the above suggestion of setting it to `arm64` is no longer correct because the new A12 chips are `arm64e`.

2. If you are using the new `generate_multiple_pod_projects` flag your post_install script needs to iterate over one level deeper otherwise the deployment target setting is only applied to the main Pods project, not the projects internal to it:

```
minimum_deployment_target = 11.4

platform :ios, minimum_deployment_target
...

post_install do |installer|
    installer.generated_projects.each do |project|
        project.targets.each do |target|
            target.build_configurations.each do |config|
                # Ensure we set all Pods to match the minimum deployment target specified by the app
                config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_deployment_target
            end
        end
    end
end
```

**Comment by Megal** [comment] 2020-01-27 21:25
> Gut feeling tells me the users xcodeproj is on Xcode 9 which is 64bit only and the one generated from pods is with 8 or earlier hence the discrepancy between the `$(ARCHS_STANDARD)` value.

I can confirm that. Should we re-open this issue?
Without overriding IPHONEOS_DEPLOYMENT_TARGET using [snippet](https://github.com/CocoaPods/CocoaPods/issues/7111#issuecomment-573709158)
I have

```
$ xcodebuild -showBuildSettings -project Pods/Pods.xcodeproj | grep ARCHS
    ARCHS = armv7 arm64
    ARCHS_STANDARD = armv7 arm64
    ARCHS_STANDARD_32_64_BIT = armv7 arm64
    ARCHS_STANDARD_32_BIT = armv7
    ARCHS_STANDARD_64_BIT = arm64
    ARCHS_STANDARD_INCLUDING_64_BIT = armv7 arm64
    ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
    VALID_ARCHS = arm64 arm64e armv7 armv7s
```

With overriding:
```
$ xcodebuild -showBuildSettings -project Pods/Pods.xcodeproj | grep ARCHS
    ARCHS = arm64
    ARCHS_STANDARD = arm64
    ARCHS_STANDARD_32_64_BIT = armv7 arm64
    ARCHS_STANDARD_32_BIT = armv7
    ARCHS_STANDARD_64_BIT = arm64
    ARCHS_STANDARD_INCLUDING_64_BIT = arm64
    ARCHS_UNIVERSAL_IPHONE_OS = armv7 arm64
    VALID_ARCHS = arm64 arm64e armv7 armv7s
```

---
I'm using
Xcode Version 11.3.1 (11C504)
```
$ pod --version
1.8.4
```
My main target is 12.0

My Podfile looks like this:
```
platform :ios, '12.0'
minimum_deployment_target = 12.0
inhibit_all_warnings!

def pods_list

  pod 'PluggableAppDelegate', '1.3.0'

  pod 'RxSwift', '~> 5.0.0'
  pod 'RxCocoa', '~> 5.0.0'
  pod 'RxSwiftExt', '~> 5.0.0'
  pod 'RxDataSources', '~> 4.0.1'
  
  pod 'Moya/RxSwift'
  pod 'Moya', '~> 14.0.0-beta.6'
  
  pod 'SwiftLint', '~> 0.35.0'
  pod 'SnapKit', '~> 5.0.0'
  pod 'SwiftKeychainWrapper', '~> 3.4.0'
  pod 'Kingfisher', '~> 5.8.0'
  pod 'ReachabilitySwift', '~> 4.3.0'
  pod 'IQKeyboardManagerSwift', '~> 6.5.0'
  pod 'JWTDecode', '~> 2.4'
  pod 'SkeletonView', '~> 1.8.2'
  pod 'SwiftEntryKit', '~> 1.2.3'

end

target '<reducted>' do
  use_frameworks!

  pods_list

  target '<reducted>' do
    inherit! :search_paths
    # Pods for testing
  end

end

# # Workaround for AppStore issue
# # ITMS-90381: Too many symbol files 
# # https://github.com/CocoaPods/CocoaPods/issues/7111
# post_install do |installer|
#     installer.generated_projects.each do |project|
#         project.targets.each do |target|
#             target.build_configurations.each do |config|
#                 # Ensure we set all Pods to match the minimum deployment target specified by the app
#                 config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = minimum_deployment_target
#             end
#         end
#     end
# end
```

Some pods have min deployment target of 8.0, which may cause the issue.

**Comment by tapwork** [comment] 2020-02-20 13:59
@Megal is right...it's an issue when some Pods have a deployment target below iOS 12. 
so setting it to 
```
config.build_settings['IPHONEOS_DEPLOYMENT_TARGET'] = 12.0
```
Should fix this

**Comment by jshier** [comment] 2020-03-28 00:45
We've been seeing this as well. It would be great if CocoaPods could inherit our project settings automatically, but the workaround mentioned works. Only issue with manually setting the deployment target is that it will bring up any warnings from the pods that don't appear at the pod's  normal deployment target, which can be quite annoying.

**Comment by manivelnagarajan** [comment] 2020-06-23 09:52
In case, if we have multiple architectures supported. For.e.g: arm64 and arm64e.

You can have the script like this,

```
post_install do |installer|
    installer.pods_project.build_configuration_list.build_configurations.each do |configuration|
        configuration.build_settings['ARCHS'] = 'arm64 arm64e'
    end
end
```

Can someone please clarify on below questions,
1. Do we need to set `ARCHS` or `VALID_ARCHS`? What is the difference?
2. Is arm64e needed all the time? or this is needed only on specific purposes?
