### ISSUE TITLE
Error Installing BURelyFoundation_Global with command pod install in Xcode project

### ISSUE THREAD

**Issue by raycaststudio** [CocoaPods/CocoaPods#12257] opened 2024-02-05 10:31 UTC
Errno::EACCES - Permission denied @ rb_sysopen - /Users/squarepixelstudio/Library/Caches/CocoaPods/Pods/Release/BURelyFoundation_Global/0.1.1.3-1d181/Frameworks/SDK/BURelyFoundationGlobalFoundation/BURelyFoundationGlobalFoundation.xcframework/ios-arm64_armv7/Headers/NSArray+PAGUtilities.h
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2279:in initialize' /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2279:in open'
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2279:in block in copy_file' /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2278:in open'
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2278:in copy_file' /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2243:in copy'
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:1048:in block in copy_entry' /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2385:in wrap_traverse'
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:1045:in copy_entry' /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:990:in block in cp_r'
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2469:in block in fu_each_src_dest' /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2478:in block in fu_each_src_dest0'
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2476:in each' /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2476:in fu_each_src_dest0'
/usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:2467:in fu_each_src_dest' /usr/local/Cellar/ruby/3.3.0/lib/ruby/3.3.0/fileutils.rb:989:in cp_r'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:343:in block (2 levels) in copy_files' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in each'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:341:in block in copy_files' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:128:in lock'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:99:in write_lock' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:332:in copy_files'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:269:in block (2 levels) in uncached_pod' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in each'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:265:in block in uncached_pod' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:291:in in_tmpdir'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:238:in uncached_pod' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader/cache.rb:33:in download_pod'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/downloader.rb:42:in download' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_downloader.rb:69:in download!'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:117:in download_source' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer/pod_source_installer.rb:67:in install!'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:621:in install_source_of_pod' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:539:in block (2 levels) in install_pod_sources'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:86:in titled_section' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:538:in block in install_pod_sources'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in each' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:535:in install_pod_sources'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:258:in block in download_dependencies' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/user_interface.rb:64:in section'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:257:in download_dependencies' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/installer.rb:163:in install!'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/command/install.rb:52:in run' /usr/local/lib/ruby/gems/3.3.0/gems/claide-1.1.0/lib/claide/command.rb:334:in run'
/Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/lib/cocoapods/command.rb:52:in run' /Users/squarepixelstudio/.gem/ruby/3.3.0/gems/cocoapods-1.15.0/bin/pod:55:in <top (required)>'
/usr/local/bin/pod:25:in load' /usr/local/bin/pod:25:in 

'

――― TEMPLATE END ――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――――

[!] Oh no, an error occurred.

Search for existing GitHub issues similar to yours:
https://github.com/CocoaPods/CocoaPods/search?q=Permission+denied+%40+rb_sysopen+-+%2FUsers%2Fsquarepixelstudio%2FLibrary%2FCaches%2FCocoaPods%2FPods%2FRelease%2FBURelyFoundation_Global%2F0.1.1.3-1d181%2FFrameworks%2FSDK%2FBURelyFoundationGlobalFoundation%2FBURelyFoundationGlobalFoundation.xcframework%2Fios-arm64_armv7%2FHeaders%2FNSArray%2BPAGUtilities.h&type=Issues

If none exists, create a ticket, with the template displayed above, on:
https://github.com/CocoaPods/CocoaPods/issues/new

Be sure to first read the contributing guide for details on how to properly submit a ticket:
https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md

Don't forget to anonymize any private data!

**Comment by paulb777** [comment] 2024-02-05 15:49
Dupe of #12226

**Closed by paulb777** 2024-02-05 15:49 UTC

**Comment by felipecastrosales** [comment] 2024-09-06 19:09
how fix it? i'm with: `Library 'BURelyFoundationGlobalAFN' not found`
