### ISSUE TITLE
No such module in UITests using 1.2.1.beta.1

### ISSUE THREAD

**Issue by kristiyandobrev** [CocoaPods/CocoaPods#6599] opened 2017-03-29 12:28 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

I have installed two libraries called `Nimble` and `Quick` and I want to use them in my UITests.

Here how my `Podfile`:

```
........//more pods
  use_frameworks!
  target 'TrackunitGoUITests' do
    inherit! :search_paths
    pod 'Quick'
    pod 'Nimble'
  end
```

## What did you expect to happen?

The app should build without problems.

## What happened instead?

It builds successfully but it shows `No such a module Quick` and `No such module Nimble` error while opening my UITesting file that imports the two libraries.

Also when I look under `Pods->Products`  folder I see that the two libraries are in **_red_**.

I tried Cleaning the project, Deleting the Derived Data and Cleaning the build folder. None of them helped.

**Comment by dnkoutso** [comment] 2017-03-31 05:14
@kristiyandobrev can you provide a sample project please?

**Comment by adamsmaka** [comment] 2017-04-19 18:46
I have the same problem. All libraries imported only to Test target as marked as swift compiler error "no such module xxx"

what interesting, everything works as expected. project build, use libraries and test properly, but this error red exclamation mark visible on top is annoying. tested with rxtest and fbsnapshottests

**Comment by jhihguan** [comment] 2017-05-16 07:41
I'm having the same issue with RxTest,
It can actually run the test but it doesn't have autocomplete with RxTest syntax. (will have a red mark with No such module 'RxTest')
The hard thing is that I can't reproduce this error if I opened a new project with almost the same Podfile.

**Comment by kristiyandobrev** [comment] 2017-05-16 08:48
Alright. I have found a workaround. I have selected `Manage Schemes`, then selected `Pods-MyFancyAppUITests` scheme and then I `Build` that scheme. The error was gone and the autocomplete was working after that somehow...

**Comment by jhihguan** [comment] 2017-05-16 11:53
@kristiyandobrev this is awesome!! this does works for me. it took me 2 days try to change my Podfile with nothing.

I guess it does build the framework when testing but somehow it doesn't really exists in deriveddata folder?so my RxTest.framework is still red(not exist) in `Pods/Products` folder, others are black

**Comment by adamsmaka** [comment] 2017-05-17 07:45
@kristiyandobrev i think it works! we will see if error will not appear again in different situations but for now he's gone ! thank you man :D it was so annoying hehe

**Comment by ffittschen** [comment] 2017-06-02 19:21
But this is still just a workaround and no solution I won't be able to do that on my CI system..

@dnkoutso I created a sample project and used the `Firebase/Crash` dependency as instructed in https://firebase.google.com/docs/crash/ios

If you clone or download the project, just run `bundle exec pod install` and run the tests to get the _Missing required module 'Firebase'_ error.

Sample project: https://github.com/ffittschen/cocoapods-inherit-searchpaths-tests

**Comment by kristiyandobrev** [comment] 2017-06-06 09:28
@ffittschen if you add `YourAppUITests ` scheme to the project, can't you build it on the CI before running the tests ?

**Closed** 2017-09-12 06:48 UTC
Labels: s1:awaiting input

**Comment by Carpemeid** [comment] 2018-09-21 11:50
Xcode 10, iPhone 8 iOS 12 simulator used for UITests [project was created with Xcode 10]

What fixed it for me is:

1) setting the inheritance in the podfile for UITests to "complete" instead of "search paths"
2) setting the "Always Embed Swift Standard Libraries" flag in the pods project to "YES"
