### ISSUE TITLE
please help me

### ISSUE THREAD

**Issue by codestoryWY** [CocoaPods/CocoaPods#5068] opened 2016-03-21 07:02 UTC
### Command

```
/Users/apple/.rvm/rubies/ruby-2.3.0/bin/pod install --verbose --no-repo-update
```

### Report

* What did you do?

* What did you expect to happen?

* What happened instead?

### Stack

```
   CocoaPods : 0.39.0
        Ruby : ruby 2.3.0p0 (2015-12-25 revision 53290) [x86_64-darwin15]
    RubyGems : 2.5.1
        Host : Mac OS X 10.11.3 (15D21)
       Xcode : 7.2.1 (7C1002)
         Git : git version 2.5.4 (Apple Git-61)
Ruby lib dir : /Users/apple/.rvm/rubies/ruby-2.3.0/lib
Repositories : master - https://github.com/CocoaPods/Specs.git @ a4dbfa7f7380e145bf71d53f8503a801216fa3fe
```

### Plugins

```
cocoapods-plugins : 0.4.2
cocoapods-search  : 0.1.0
cocoapods-stats   : 0.6.2
cocoapods-trunk   : 0.6.4
cocoapods-try     : 0.5.1
```

### Podfile

```ruby
platform :ios, '7.0' 
pod 'MBProgressHUD', '~> 0.8'
```

### Error

```
NoMethodError - undefined method `to_ary' for #<Pod::Specification name="MBProgressHUD">
Did you mean?  to_query
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver/lazy_specification.rb:14:in `method_missing'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `flatten'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:64:in `block in resolve'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `tap'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/resolver.rb:63:in `resolve'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:539:in `block in resolve_dependencies'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:537:in `resolve_dependencies'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer/analyzer.rb:70:in `analyze'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:213:in `analyze'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:136:in `block in resolve_dependencies'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/user_interface.rb:59:in `section'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:135:in `resolve_dependencies'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/installer.rb:105:in `install!'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:71:in `run_install_with_update'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command/project.rb:101:in `run'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/claide-0.9.1/lib/claide/command.rb:312:in `run'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/lib/cocoapods/command.rb:47:in `run'
/Users/apple/.rvm/gems/ruby-2.3.0@global/gems/cocoapods-0.39.0/bin/pod:44:in `<top (required)>'
/Users/apple/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `load'
/Users/apple/.rvm/rubies/ruby-2.3.0/bin/pod:23:in `<main>'
```

**Comment by jafara** [comment] 2016-03-21 07:03
lol, this has been opened as an issue 20 times by now. Do a google search its not hard.

**Comment by codestoryWY** [comment] 2016-03-21 07:10
ok ，i will try

**Comment by orta** [comment] 2016-03-21 08:08
Closing as a duplicate of [these results](https://github.com/CocoaPods/CocoaPods/issues?utf8=✓&q=is%3Aissue+to_ary)

**Closed by orta** 2016-03-21 08:08 UTC
