### ISSUE TITLE
0.38.x - upgrading a Pod breaks another one that's got nothing to do with the first

### ISSUE THREAD

**Issue by tanis2000** [CocoaPods/CocoaPods#3958] opened 2015-08-03 13:58 UTC
Here's my original Pod file

```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

# Hide cocoapods project warnings
inhibit_all_warnings!

source 'git@gitlab.altralogica.it:altralogica/cocoapods-spec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Foo' do
pod 'AFNetworking', '~> 2.5'
pod 'ALTFacebook', '~> 0.0'
pod 'ALTTwitter', '~> 0.1'
pod 'ALTGooglePlus', '~> 0.1'
pod 'ALTPinterest', '~> 1.0'
pod 'ALTLocation', '~> 0.1'
pod 'ALTContacts', '~> 0.1'
pod 'ALTNotification', '~> 0.1'
pod 'BlocksKit', '~> 2.2'
pod 'CrashlyticsFramework', '~> 2.2'
pod 'DTCoreText', '~> 1.6'
pod 'FMDB', '~> 2.5'
pod 'FMDBMigrationManager', '~> 1.2'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'GRMustache', '~> 7.3'
pod 'iCarousel', '~> 1.8'
pod 'Mantle', '~> 2.0'
pod 'MKUnits', '~> 2.2'
pod 'MTDates', '~> 0.11.0'
pod 'MZFormSheetController', '~> 3.0'
pod 'NGAParallaxMotion', '~> 1.1'
pod 'pop', '~> 1.0'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'ReactiveViewModel', '~> 0.3'
pod 'SDWebImage', '~> 3.7'
pod 'SVProgressHUD', '~> 1.1'
pod 'TPKeyboardAvoiding', '~> 1.2'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
pod 'UIColor-HTMLColors', '~> 1.0.0'
pod 'iCarousel', '~> 1.8'
pod 'FormatterKit', '~> 1.8'
end

target 'FooWidget' do
    pod 'AFNetworking', '~> 2.5'
    pod 'ALTLocation', '~> 0.1'
    pod 'CrashlyticsFramework', '~> 2.2'
    pod 'FMDB', '~> 2.5'
    pod 'FMDBMigrationManager', '~> 1.2'
    pod 'GRMustache', '~> 7.3'
    pod 'Mantle', '~> 2.0'
    pod 'MKUnits', '~> 2.2'
    pod 'MTDates', '~> 0.11.0'
    pod 'ReactiveCocoa', '~> 2.4.7'
    pod 'ReactiveViewModel', '~> 0.3'
    pod 'UIColor-HTMLColors', '~> 1.0.0'
    
end

target 'FooTests' do

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == 'Pods-FooWidget-AFNetworking'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'AF_APP_EXTENSIONS=1'
            end
        end
    end
end

```

With the aforementioned Podfile everything works fine.

I upgraded the old CrashlyticsFramework Pod to the new Fabric as the old one has been deprecated.
So in the end the new Podfile is the following (I only changed a the Crashlytics line):

```
# Uncomment this line to define a global platform for your project
# platform :ios, '6.0'

# Hide cocoapods project warnings
inhibit_all_warnings!

source 'git@gitlab.altralogica.it:altralogica/cocoapods-spec.git'
source 'https://github.com/CocoaPods/Specs.git'

target 'Foo' do
pod 'AFNetworking', '~> 2.5'
pod 'ALTFacebook', '~> 0.0'
pod 'ALTTwitter', '~> 0.1'
pod 'ALTGooglePlus', '~> 0.1'
pod 'ALTPinterest', '~> 1.0'
pod 'ALTLocation', '~> 0.1'
pod 'ALTContacts', '~> 0.1'
pod 'ALTNotification', '~> 0.1'
pod 'BlocksKit', '~> 2.2'
pod 'Fabric', '~> 1.2.8'
pod 'DTCoreText', '~> 1.6'
pod 'FMDB', '~> 2.5'
pod 'FMDBMigrationManager', '~> 1.2'
pod 'Google-Mobile-Ads-SDK', '~> 7.0'
pod 'GoogleAnalytics-iOS-SDK', '~> 3.10'
pod 'GRMustache', '~> 7.3'
pod 'iCarousel', '~> 1.8'
pod 'Mantle', '~> 2.0'
pod 'MKUnits', '~> 2.2'
pod 'MTDates', '~> 0.11.0'
pod 'MZFormSheetController', '~> 3.0'
pod 'NGAParallaxMotion', '~> 1.1'
pod 'pop', '~> 1.0'
pod 'ReactiveCocoa', '~> 2.4.7'
pod 'ReactiveViewModel', '~> 0.3'
pod 'SDWebImage', '~> 3.7'
pod 'SVProgressHUD', '~> 1.1'
pod 'TPKeyboardAvoiding', '~> 1.2'
pod 'UIAlertView-Blocks', '~> 1.0'
pod 'UIActivityIndicator-for-SDWebImage', '~> 1.2'
pod 'UIColor-HTMLColors', '~> 1.0.0'
pod 'iCarousel', '~> 1.8'
pod 'FormatterKit', '~> 1.8'
end

target 'FooWidget' do
    pod 'AFNetworking', '~> 2.5'
    pod 'ALTLocation', '~> 0.1'
    pod 'Fabric', '~> 1.2.8'
    pod 'FMDB', '~> 2.5'
    pod 'FMDBMigrationManager', '~> 1.2'
    pod 'GRMustache', '~> 7.3'
    pod 'Mantle', '~> 2.0'
    pod 'MKUnits', '~> 2.2'
    pod 'MTDates', '~> 0.11.0'
    pod 'ReactiveCocoa', '~> 2.4.7'
    pod 'ReactiveViewModel', '~> 0.3'
    pod 'UIColor-HTMLColors', '~> 1.0.0'
    
end

target 'FooTests' do

end

post_install do |installer_representation|
    installer_representation.pods_project.targets.each do |target|
        if target.name == 'Pods-FooWidget-AFNetworking'
            target.build_configurations.each do |config|
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] ||= ['$(inherited)']
                config.build_settings['GCC_PREPROCESSOR_DEFINITIONS'] << 'AF_APP_EXTENSIONS=1'
            end
        end
    end
end

```

Then I run the usual `pod install`.
Next I changed my prefix file to include <Fabric/Fabric.h> instead of <Crashlytics/Crashlytics.h> and adapted the code to initialize it (but I can as well just comment it out as the result doesn't change).
Next I build the project and the error is the following:

    ALTGooglePlus.h:10:9: 'google-plus-ios-sdk/GTLPlus.h' file not found

It looks like it can't find the header files of the google-plus-ios-sdk Pod for an unknown reason. I can't understand why adding Fabric actually breaks a different Pod.
Has this ever happened to anyone else?

**Comment by fluidsonic** [comment] 2015-08-03 15:09
`CrashlyticsFramework` is deprecated. The Pods `Fabric` and `Crashlytics` are the official ones which belong together.

Although the error message is unrelated I also had a lot issues getting Fabric & Crashlytics to work with CocoaPods since both Pods are messed up at the moment.

- on CocoaPods.org [Fabric](https://cocoapods.org/?q=Fabric) is listed with `1.3.2` as the latest version which does not exist (neither a podspec exists nor does a downloadable archive)
- the latest downloadable archive is [1.3.0](https://kit-downloads.fabric.io/ios/io.fabric.sdk.ios/1.3.0/io.fabric.sdk.ios-default.zip) which does not have a corresponding Pod version
- the latest downloadable archive which is also available through CocoaPods is [1.2.8](https://github.com/CocoaPods/Specs/blob/master/Specs/Fabric/1.2.8/Fabric.podspec.json)

I made a simple Podspec to support version 1.3.0:
```
pod 'Fabric' :podspec => 'https://gist.githubusercontent.com/fluidsonic/5c82accb37b4ae3a43d9/raw/e375f2b521739fadc00b4ca94350325a180c03cc/Fabric.podspec.json' # 1.3.0 missing in CocoaPods repo
```

The next problem is the `Crashlytics` Pod which is even worse. When a project is built using frameworks the Pod won't compile because it uses headers from a different Pod (Fabric). This leads to the annoying `non-module header` error.

I set up an [alternative version](https://github.com/fluidsonic/Crashlytics) until the Crashlytics issue is officially resolved by Fabric:

```
pod 'Crashlytics', :git => 'https://github.com/fluidsonic/Crashlytics.git', :tag => 'v3.1.0'
```

-------

Regarding your error: Do you have a case-sensitive file system?
The pod's name is `GoogleAnalytics-iOS-SDK` while the path in your error message says `google-plus-ios-sdk`.
Also the Pod `GoogleAnalytics-iOS-SDK` is deprecated.

**Comment by tanis2000** [comment] 2015-08-03 15:12
@fluidsonic thanks for the tips. I'm going to try your podspecs to see if that fixes the problem.
Nonetheless, I guess that Cocoapods should check for problems like mixing up static libraries and frameworks.

The one giving problem is `google-plus-ios-sdk` and not the analytics one. It does not appear in the Podfile because it's being included by the ALTGooglePlus pod.

I came up with a sample repo. Try to build that project and you'll get my error:
https://github.com/tanis2000/broken-pods

**Comment by fluidsonic** [comment] 2015-08-03 15:21
Oh right, I mixed up the two Google Pods.

Looking at the the `Pods` directory the correct path of `GTLPlus.h` is `google-plus-ios-sdk/GoogleOpenSource/GTLPlus.h`.

`google-plus-ios-sdk/GTLPlus.h` is wrong even when I remove the `Fabric` pod.

**Comment by tanis2000** [comment] 2015-08-03 15:28
But if you open the folder `Pods/google-plus-ios-sdk` in the Pods projects, you can see that the headers are right there (I suppose they're symlinked). It used to work fine before upgrading Cocoapods to the 0.38.x series. 

Anyway you're right, the real place where the headers live and should be is inside the two frameworks included by that pod. I'm going to patch my code hoping this behavior doesn't change in the following releases.

Thanks for the help mate!

**Comment by fluidsonic** [comment] 2015-08-03 15:32
The folder `Pods/google-plus-ios-sdk` is not relevant for header lookup.
Look at `Pods/Headers/Public/google-plus-ios-sdk` instead.

It may indeed be a bug in CocoaPods 0.38.x if the header path structure changed. Just compare the structure of `Pods/Headers/Public/google-plus-ios-sdk` between the different CocoaPods versions.

**Comment by tanis2000** [comment] 2015-08-03 15:55
I downgraded as much as to 0.36.4 but the folder structure seems exactly the same. I don't get why it used to work before. But it looks like downgrading cocoapods isn't downgrading all the dependencies as well.. so it might have been one of the gems it depends on and I'll never know.

**Comment by neonichu** [comment] 2016-05-02 08:46
This issue has been inactive for a long time and will be closed because we want to move forward with a clean slate after our 1.0 release. If you believe this is still relevant, please retest with the 1.0 release candidate and comment with a reproducible project in order for this to become actionable again. Thanks!

**Closed by neonichu** 2016-05-02 08:46 UTC
