### ISSUE TITLE
pod lib lint  error 

### ISSUE THREAD

**Issue by shimminZ** [CocoaPods/CocoaPods#10750] opened 2021-07-02 02:25 UTC
### error message 
  - WARN  | source: Git SSH URLs will NOT work for people behind firewalls configured to only allow HTTP, therefore HTTPS is preferred.
    - WARN  | [iOS] swift: The validator used Swift `4.0` by default because no Swift version was specified. To specify a Swift version during validation, add the `swift_versions` attribute in your podspec. Note that usage of a `.swift-version` file is now deprecated.
    - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
    - NOTE  | xcodebuild:  note: Using new build system
    - NOTE  | xcodebuild:  note: Building targets in parallel
    - NOTE  | xcodebuild:  note: Using codesigning identity override: -
    - NOTE  | [iOS] xcodebuild:  note: Planning build
    - NOTE  | [iOS] xcodebuild:  note: Constructing build description
    - NOTE  | [iOS] xcodebuild:  warning: Skipping code signing because the target does not have an Info.plist file and one is not being generated automatically. (in target 'App' from project 'App')
    - WARN  | xcodebuild:  /Users/zhang/Desktop/podPriLib/Personfuction/Personfuction/Classes/XZDemo1.swift:13:13: warning: initialization of immutable value 'obView' was never used; consider replacing with assignment to '_' or removing it
    - NOTE  | [iOS] xcodebuild:  /Users/zhang/Desktop/podPriLib/Personfuction/Personfuction/Classes/XZObDemo.m:10:9: fatal error: 'Personfuction/Personfuction-Swift.h' file not found

Pods workspace available at `/var/folders/fc/d3tbnld97cjct5ybzqc_4n3m0000gn/T/CocoaPods-Lint-20210702-88758-112vs9o-Personfuction/App.xcworkspace` for inspection.

[!] Personfuction did not pass validation, due to 1 error.

**Comment by dnkoutso** [comment] 2021-07-02 02:29
Without a sample app we cannot reproduce.

Those look suspicious:

```
WARN | [iOS] swift: The validator used Swift 4.0 by default because no Swift version was specified. To specify a Swift version during validation, add the swift_versions attribute in your podspec. Note that usage of a .swift-version file is now deprecated.
ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code.
```

Please file a sample repo demonstrating the issue. Closing for now.

**Closed by dnkoutso** 2021-07-02 02:29 UTC

**Comment by shimminZ** [comment] 2021-07-02 02:48
@dnkoutso       i add    s.swift_version = '4.0'   in my podspec file .  The warning disappears but the error remains 。 
I think the main error message is this ：`fatal error: 'Personfuction/Personfuction-Swift.h' file not found `

**Comment by dnkoutso** [comment] 2021-07-02 02:52
still without a podspec we are unable to diagnose further. Use `--no-clean` method and then open the generated project cocoapods makes to lint and see if you can inspect and find the issue.

**Comment by shimminZ** [comment] 2021-07-02 03:09
this is my  podspec. @dnkoutso 

```
Pod::Spec.new do |s|
  s.name             = 'Personfuction'
  s.version          = '0.1.0'
  s.summary          = ' Personfuction.'

  s.description      =' Personfuction. 一个测试库啊'

  s.swift_version = '4.0'

  s.homepage         = 'https://hehuoren1.coding.net/'
  # s.screenshots     = 'www.example.com/screenshots_1', 'www.example.com/screenshots_2'
  s.license          = { :type => 'MIT', :file => 'LICENSE' }
  s.author           = { 'shimminZ' => '272110599@qq.com' }
  s.source           = { :git => 'git@e.coding.net:hehuoren1/ceshiku/base1Link.git', :tag => s.version.to_s }
  # s.social_media_url = 'https://twitter.com/<TWITTER_USERNAME>'

  s.ios.deployment_target = '9.0'

  s.source_files = 'Personfuction/Classes/**/*'
  
  # s.resource_bundles = {
  #   'Personfuction' => ['Personfuction/Assets/*.png']
  # }

  # s.public_header_files = 'Pod/Classes/**/*.h'
  # s.frameworks = 'UIKit', 'MapKit'
  # s.dependency 'AFNetworking', '~> 2.3'
end

**Comment by dnkoutso** [comment] 2021-07-02 03:10
Sorry I meant we need a podspec and a repo that i can clone and try to run `pod lib lint` can you provide that?

**Comment by shimminZ** [comment] 2021-07-02 04:46
@dnkoutso   Thank you very much. You can download my code here   https://github.com/shimminZ/BaseToolTest

**Comment by TalentLifeFeng** [comment] 2022-02-21 15:40
Same issue here. My project is a framework template mixed with oc and swift. When oc call swift, have to import headers as `#import <MyFramework/MyFramework-Swift.h>`. But pod lib lint will report an fatal error as follows `xcodebuild:  /Users/frank/MyZone/workspace/ios/mtextension/Source/Classes/MyOCObj.m:10:9: fatal error: 'MTCommonExtension/MTCommonExtension-Swift.h' file not found`
