### ISSUE TITLE
CocoaPods is unable to read YAML files when Psych 2.0.13 is installed

### ISSUE THREAD

**Issue by kylef** [CocoaPods/CocoaPods#3539] opened 2015-05-08 10:38 UTC
See #2908 and #3490.

We should investigate why it's broken in Psych and potentially fix the problem. If that's not easily achievable we should perhaps pin to Psych 2.0.0 in our gem spec.

**Comment by segiddins** [comment] 2015-05-08 14:30
@kylef if we pin psych, that will force people to compile a c extension.

**Comment by kylef** [comment] 2015-05-08 14:43
@segiddins even if we pin to the version that's included on the system by default?

**Comment by segiddins** [comment] 2015-05-08 14:48
Different ruby versions come bundled with different versions of psych

-Samuel E. Giddins

On May 8, 2015, at 7:43 AM, Kyle Fuller <notifications@github.com> wrote:

@segiddins even if we pin to the version that's included on the system by default?

**Comment by neonichu** [comment] 2015-05-08 15:02
Current system rubies we support are: 2.0.0-p481, 2.0.0-p451 and 2.0.0-p247, right? Maybe those happen to ship with the same version of Psych?

**Comment by segiddins** [comment] 2015-05-08 15:14
No clue, I use 2.3.0-dev day to day.

**Comment by segiddins** [comment] 2015-05-31 08:00
I can't reproduce this with Psych 2.0.13, an in multiple ruby versions

**Comment by cbowns** [comment] 2015-06-01 23:27
A big :+1:, I just hit this error as well. I think another `gem` I installed today (via `rbenv`) brought in `psych`.

```
[!] There was an error reading '/Users/cbowns/.cocoapods/repos/master/CocoaPods-version.yml'

cbowns at Atlas in ~ ☃
% ○ gem uninstall psych              
Successfully uninstalled psych-2.0.13

cbowns at Atlas in ~ ☆
% ○ pod setup                        
Setting up CocoaPods master repo
Already up-to-date.
Setup completed
```

**Comment by cbowns** [comment] 2015-06-01 23:40
Via https://github.com/CocoaPods/CocoaPods/issues/2908#issuecomment-107746574:

"Also reported at https://github.com/bbatsov/rubocop/issues/1510 -- someone said it might be a RubyGems bug?"

**Comment by steakknife** [comment] 2015-07-27 06:56
- Ruby 2.2.2
- gem (RubyGems) 2.4.8
- psych 2.0.13 (and 2.0.8 which cannot be uninstalled because it's a system gem)
- cocoapods 0.38.2

The trick seems to be `gem update --system` (to update RubyGems to a recent version itself which patches some Psych-related things):

So start clean:

```
rm -rf ~/Library/Caches/CocoaPods ~/.cocoapods; \
gem update --system && \
gem update && \
gem cleanup && \
pod setup
```

**Comment by wkoszek** [comment] 2015-11-23 23:42
Got the same error today:

```
Setting up CocoaPods master repo
Already up-to-date.
[!] There was an error reading '/Users/xxxxx/.cocoapods/repos/master/CocoaPods-version.yml'.
Please consult http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/ for more information.
```

I had to use @steakknife fix to un-break my system.

This website:

http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/

should be extended to mention this bug case, since the original fix suggested there didn't work for me.

**Comment by 3lvis** [comment] 2015-12-09 10:59
Got this error today after updating my gems. I agree with @wkoszek, would be nice to have this bug mentioned on http://blog.cocoapods.org/Repairing-Our-Broken-Specs-Repository/

**Comment by segiddins** [comment] 2015-12-09 16:57
A PR updating the guides page would be much appreciated!

**Comment by 3lvis** [comment] 2015-12-09 17:00
@segiddins Could you please help me find where to do the contribution? GitHub search is not helping :disappointed:

**Comment by segiddins** [comment] 2015-12-09 17:01
Arg it's the blog, sorry. GitHub.com/CocoaPods/blog.cocoapods.org

**Comment by 3lvis** [comment] 2015-12-09 17:22
Added a small paragraph regarding this issue, might not be the best wording but I'm open to improve it until you guys think it's good enough for people that have this same problem.

https://github.com/CocoaPods/blog.cocoapods.org/pull/110

cc @segiddins

**Comment by neonichu** [comment] 2016-05-02 08:50
Let's close this since this problem is mentioned in guides now.

**Closed by neonichu** 2016-05-02 08:50 UTC
Labels: d1:easy, t2:defect
