### ISSUE TITLE
Pod lint fails when containing dynamic-frameworks without simulator architectures

### ISSUE THREAD

**Issue by eldewy** [CocoaPods/CocoaPods#5854] opened 2016-09-13 11:58 UTC
Currently `pod trunk` is not usable for us as `pod lint` fails because simulator architectures (i386 and x86_64) are missing. BUT Apple rejects apps containing dynamic-frameworks with simulator architectures.

We deploy two variants of dynamic-framworks
- one with all device and simulator architectures (for debugging)
- one with device-only architectures (for app-submission).

`pod lint` fails with the following errors:

> x86_64 in file SampleSDK/iOS/Sample.framework/Sample (3 slices)
> - NOTE  | [SampleSDK/SampleSDK and more...] xcodebuild:  fatal error: lipo: -remove's specified would result in an empty fat file
> - NOTE  | [iOS] [SampleSDK/SampleSDK] xcodebuild:  ld: warning: ld: warning: ignoring file SampleSDK/iOS/Sample.framework/Sample, missing required architecture x86_64 in file 

We were forced to provide device-only architectures as Apple rejects app-submissions containing any simulator-architectures with

> ERROR: ERROR ITMS-90087: "Unsupported Architectures. The executable for Sample.app/Frameworks/Sample.framework contains unsupported architectures '[x86_64, i386]'."

Similar issues: 
https://github.com/CocoaPods/CocoaPods/issues/5275
http://stackoverflow.com/questions/36618252/cocoapods-podspec-push-without-build-simulator-architecture

**Comment by Philipp372** [comment] 2016-09-15 07:04
I am also affected by this problem, that I aim to distribute a dynamic framework pod without the simulator architectures as they are not allowed when submitting an app to the AppStore.
Cocoapods team, pls advise.

**Comment by LeT0C** [comment] 2016-09-15 13:45
Thank you benasher44, it indeed is the same problem for me :
https://github.com/CocoaPods/CocoaPods/issues/5877

We haven't submit to Apple yet, so I can't confirm eldewy's problem, but if it's the same here, it's a huge issue for my team.

Cocoapods team, could you please do something or advise us a working solution ?

Thanks

**Comment by orta** [comment] 2016-09-15 13:57
I'm not really sure of the answer here, 1.0 now has more strict linting rules because successfully working with other people's projects is becoming more complicated due to things like code-signing, frameworks and code-signing.

Perhaps a PR improving the linter specifically towards binary/dynamic framework pods that can take into account it's constraints better could be a way to move forwards?

**Comment by eldewy** [comment] 2016-09-19 07:59
@orta
This is a problem only with dynamic.frameworks...
What are the next steps required by us? How should we proceed to enforce a change?
We want to move our podspecs to the public github repository, but cannot because of this issue.

**Comment by orta** [comment] 2016-09-20 09:44
> Perhaps a PR improving the linter specifically towards binary/dynamic framework pods that can take into account it's constraints better could be a way to move forwards?

I think the next step is to look [at validator.rb](https://github.com/CocoaPods/CocoaPods/blob/master/lib/cocoapods/validator.rb) and make improvements specific to dynamic frameworks 👍

**Comment by eldewy** [comment] 2016-09-22 10:40
how can I start a initiative that this improvement is made?

**Comment by orta** [comment] 2016-09-22 10:42
This project is open source and ran by volunteers in their spare time, you could start contributing by going through the [getting started guide](https://guides.cocoapods.org/contributing/dev-environment.html)

An alternative is to commission an individual to add that feature for you instead.

**Comment by ernya** [comment] 2016-09-22 12:44
@eldewy I managed to go around this issue by replacing the code inside the xcodebuild function of validator.rb by that one : 
```
def xcodebuild
      require 'fourflusher'
      command = ['clean', 'build', '-workspace', File.join(validation_dir, 'App.xcworkspace'), '-scheme', 'Pods-App', '-configuration', 'Release']
      case consumer.platform_name
      when :ios
        command += %w(-sdk iphoneos10.0 -destination=generic/iOS ONLY_ACTIVE_ARCH=NO ARCHS=armv7)
      when :watchos
        command += %w(CODE_SIGN_IDENTITY=- -sdk watchsimulator)
        command += Fourflusher::SimControl.new.destination(:oldest, 'watchOS', deployment_target)
      when :tvos
        command += %w(CODE_SIGN_IDENTITY=- -sdk appletvsimulator)
        command += Fourflusher::SimControl.new.destination(:oldest, 'tvOS', deployment_target)
      end
 
      output, status = _xcodebuild(command)
 
      unless status.success?
        message = 'Returned an unsuccessful exit code.'
        message += ' You can use `--verbose` for more information.' unless config.verbose?
        error('xcodebuild', message)
      end
      output
    end
```
I basically replicated the behaviour of 0.39 to allow our team to push pods. Please note that this is a quick and dirty fix, will only work for ios targets, is only working with xcode8, and might not work for you, but I thought it might help you while waiting for an official fix ;)

**Comment by mdsb100** [comment] 2016-10-25 01:43
@orta 
I see you are going to make improvements specific to dynamic frameworks.

The famous third-party framework maybe is a static library. So could you provider a way to solve 'pod lint' from both static and dynamic, both library and framework?

Not only solve this issue, but also we can ignore i386 or x86_64 to reduce time when 'pod lint' or 'pod repo push'.

**Comment by mdsb100** [comment] 2016-10-25 01:46
What version are you going to release it?

**Comment by seanyue** [comment] 2016-10-25 08:55
If cocoapods 0.39.0 have already been installed, the command 'pod _0.39.0_ spec/lib lint' or 'pod _0.39.0_ repo push' can be used for a workaround.

**Comment by mdsb100** [comment] 2016-10-25 09:03
A temporary solution：use rvm.
For example：
rvm install ruby 2.2.2. Use 2.2.2 and install cocoapods 0.39.0.

rvm install ruby 2.3.1. Use ruby 2.3.1 and install cocoapods 1.1.1

You can flexibly switch pod's version by using 'rvm use'

**Comment by qingxuluo** [comment] 2016-11-15 04:26
I have the same question yet,Can you tell me how you solved it?

**Comment by zeusent** [comment] 2017-02-08 14:33
I'm having this issue as well. Is there any update on this?

**Comment by zeusent** [comment] 2017-02-08 14:53
@ernya do I have to compile my own version of CocoaPods for that? Or where can I find the `validator.rb` file?

**Comment by LeT0C** [comment] 2017-02-08 17:45
@zeusent 
moved from Cocoapods for Carthage with, no more trouble ;)

**Comment by zeusent** [comment] 2017-02-08 17:47
Thanks @LeT0C !

I've manually added the Podspec to my own private repo, thus skipping the `pod lint`. Installing and compiling the Pod works. So this definitely needs to be fixed in CocoaPods.

**Comment by ernya** [comment] 2017-02-08 17:59
@zeusent 
To use my hotfix you have to edit your validator.rb file (On my machine it is located in /usr/local/lib/ruby/gems/2.3.0/gems/cocoapods-1.1.0.rc.2/lib/cocoapods/validator.rb , change the versions if needed), and replace the old xcodebuild function (should be located near the end of the file) by my snippet of code.

A word of warning though : I didn't check that this fix is still working, I have switched to Carthage like @LeT0C , and have not used my fix recently, you might have to change stuff ;)

**Comment by dnkoutso** [comment] 2017-02-15 15:49
1.2.0 supports an option to `skip-import-validation` if you do not want to link your pod. This is the same as 0.39.0 behavior.

**Comment by dnkoutso** [comment] 2017-02-15 15:50
Actually I take it back, this is merged here https://github.com/CocoaPods/CocoaPods/issues/5670 but it has not been released yet.

**Comment by akramShokri** [comment] 2017-04-28 11:13
Hi,
This issue still exists. Do anyone have a fix for it. I tried ernya hack and also [this solution](http://stackoverflow.com/questions/38670976/how-to-build-cocoa-touch-framework-for-all-architectures-dependent-on-other-fram), but no luck and still get the same error:
`  - ERROR | [iOS] xcodebuild: Returned an unsuccessful exit code. You can use `--verbose` for more information.
    - NOTE  | [iOS] xcodebuild:  ld: warning: ignoring file mylib/mylib.framework/mylib, missing required architecture i386 in file mylib/mylib.framework/mylib (2 slices)
    - NOTE  | [iOS] xcodebuild:  ld: warning: ignoring file mylib/mylib.framework/mylib, missing required architecture x86_64 in file mylib/mylib.framework/mylib (2 slices)
    - NOTE  | [iOS] xcodebuild:  fatal error: lipo: -remove's specified would result in an empty fat file
`

**Comment by jgongo** [comment] 2017-07-27 14:38
This is still happening and still an issue for me, so please don't close it.

**Comment by dnkoutso** [comment] 2017-07-27 15:15
Will not close.

**Comment by DanToml** [comment] 2017-07-27 15:37
I've just added the defect label which will stop it from auto closing.

**Comment by minuscorp** [comment] 2017-09-16 18:43
Any advance on this topic? It is common in third-party frameworks to have device-only slices to slim the framework size. It's very interesting for us developers to make podspec wrappers around those frameworks and push them into private specs, but the validation checks fails. Have to upgrade every version manually due to the linting using only simulator archs.

I think that adding some kind of flag in lint, like `--device-only` or `--archs="arm64 armv7"` might be flexible and useful in many use-cases.

Thank you!

**Comment by PhilippOtto89** [comment] 2017-10-11 09:18
Any news on this? I agree to minuscorp that it is good to have device-only frameworks to slim the framework size. But what makes the device-only frameworks more important is the fact that fat binaries seem to be rejected when submitting apps to the appstore.

There is an open radar on this:
http://www.openradar.me/radar?id=6409498411401216
Or is this app store submission issue not relevant anymore? Does anyone know about this?

Thanks!

**Comment by zhihuitang** [comment] 2017-10-17 13:05
Still, exist.
But I was wondering how do the other framework handle this issue? like Fabric, Pushwoosh framework, how did they manage to upload the framework to Cocoapods?

Fabric also includes simulator architectures:

```
$ file Fabric.framework/Fabric
Fabric.framework/Fabric: Mach-O universal binary with 5 architectures: [arm_v7:current ar archive] [arm64]
Fabric.framework/Fabric (for architecture armv7):	current ar archive
Fabric.framework/Fabric (for architecture armv7s):	current ar archive
Fabric.framework/Fabric (for architecture i386):	current ar archive
Fabric.framework/Fabric (for architecture x86_64):	current ar archive
Fabric.framework/Fabric (for architecture arm64):	current ar archive
```

**Comment by jgongo** [comment] 2017-10-17 13:40
They probably didn't use `pod lint` or `pod push` and instead uploaded the podspec using the API

**Comment by paulb777** [comment] 2017-10-17 13:41
@zhihuitang Fabric is built with static library frameworks. With static frameworks, the linker chooses the correct architectures at build time.  This issue is about dynamic frameworks.

**Comment by zhihuitang** [comment] 2017-10-17 20:01
Thanks @paulb777 .

I am using Xcode9+Swift4. I tried to create a static Swift framework. The framework with 2 architectures(x86_64/i386+armv7/arm64) works well with Swift project. 
But it doesn't work with Objective-C project. It says `ld: library not found for -lswiftCore for architecture x86_64`. I have no idea what it is talking about.

Is it because Xcode doesnt support **Objective-C App + Swift static framework** ? Sigh......

```
Ld /Users/zhihuitang/Library/Developer/Xcode/DerivedData/demo8-gcigfrcdagsrxafknzmpkozjcfyq/Build/Products/Debug-iphonesimulator/demo8.app/demo8 normal x86_64
    cd /Users/zhihuitang/repo/ios/demo8
    export IPHONEOS_DEPLOYMENT_TARGET=11.0
    export PATH="/Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/usr/bin:/Applications/Xcode.app/Contents/Developer/usr/bin:/usr/local/bin:/usr/bin:/bin:/usr/sbin:/sbin"
    /Applications/Xcode.app/Contents/Developer/Toolchains/XcodeDefault.xctoolchain/usr/bin/clang -arch x86_64 -isysroot /Applications/Xcode.app/Contents/Developer/Platforms/iPhoneSimulator.platform/Developer/SDKs/iPhoneSimulator11.0.sdk -L/Users/zhihuitang/Library/Developer/Xcode/DerivedData/demo8-gcigfrcdagsrxafknzmpkozjcfyq/Build/Products/Debug-iphonesimulator -F/Users/zhihuitang/Library/Developer/Xcode/DerivedData/demo8-gcigfrcdagsrxafknzmpkozjcfyq/Build/Products/Debug-iphonesimulator -F/Users/zhihuitang/repo/ios/demo8/demo8 -filelist /Users/zhihuitang/Library/Developer/Xcode/DerivedData/demo8-gcigfrcdagsrxafknzmpkozjcfyq/Build/Intermediates.noindex/demo8.build/Debug-iphonesimulator/demo8.build/Objects-normal/x86_64/demo8.LinkFileList -Xlinker -rpath -Xlinker @executable_path/Frameworks -mios-simulator-version-min=11.0 -dead_strip -Xlinker -object_path_lto -Xlinker /Users/zhihuitang/Library/Developer/Xcode/DerivedData/demo8-gcigfrcdagsrxafknzmpkozjcfyq/Build/Intermediates.noindex/demo8.build/Debug-iphonesimulator/demo8.build/Objects-normal/x86_64/demo8_lto.o -Xlinker -export_dynamic -Xlinker -no_deduplicate -Xlinker -objc_abi_version -Xlinker 2 -fobjc-arc -fobjc-link-runtime -Xlinker -sectcreate -Xlinker __TEXT -Xlinker __entitlements -Xlinker /Users/zhihuitang/Library/Developer/Xcode/DerivedData/demo8-gcigfrcdagsrxafknzmpkozjcfyq/Build/Intermediates.noindex/demo8.build/Debug-iphonesimulator/demo8.build/demo8.app.xcent -framework iddc -Xlinker -dependency_info -Xlinker /Users/zhihuitang/Library/Developer/Xcode/DerivedData/demo8-gcigfrcdagsrxafknzmpkozjcfyq/Build/Intermediates.noindex/demo8.build/Debug-iphonesimulator/demo8.build/Objects-normal/x86_64/demo8_dependency_info.dat -o /Users/zhihuitang/Library/Developer/Xcode/DerivedData/demo8-gcigfrcdagsrxafknzmpkozjcfyq/Build/Products/Debug-iphonesimulator/demo8.app/demo8

ld: library not found for -lswiftCore for architecture x86_64
clang: error: linker command failed with exit code 1 (use -v to see invocation)
```

**Comment by zhihuitang** [comment] 2017-10-18 09:12
Finally, I found another workaround.
Basically, the idea we keep using the universal framework in Cocoapods.
But when achieving our host App in Xcode, we remove simulator achitectures (i386/x86_64) from the framework, and restore the framework after achieving.

Steps:
1. Add  [script](https://gist.github.com/zhihuitang/1046b71bf7fe6c169a29405c37f99a66) to Archieve/pre-actions:
![image](https://user-images.githubusercontent.com/5066926/31710370-13f9d9b8-b3f5-11e7-8785-36dfcfcb7821.png)


2. Add [script](https://gist.github.com/zhihuitang/69fc4784df749137b5ecf890b3c591e9) to Archieve/post-actions:
![image](https://user-images.githubusercontent.com/5066926/31710322-ebb6ed56-b3f4-11e7-9ff2-04e021d1e700.png)


That is it. Then just achieve as usual.

BTW: remember to use **your own framework name** in the scripts.

**Comment by dnkoutso** [comment] 2017-11-03 17:51
This is related to https://github.com/CocoaPods/CocoaPods/issues/7196 and I might make a change to make lipo a bit more lenient for both dSYM stripping and framework stripping.

**Comment by dnkoutso** [comment] 2017-11-03 17:55
@paulb777 and others just to clarify the issue, this only happens on pre-build dynamic vendored frameworks in which they do not offer every single architecture.

The script then tries to strip invalid architectures and by doing so results in an empty fat file causing a failure in the script. 

Am I understanding this correctly?=

**Comment by minuscorp** [comment] 2017-11-03 18:06
@dnkuotso You got it!

**Comment by dnkoutso** [comment] 2017-11-03 20:50
So in order to solve this I decided to mimic Xcode's behavior (and specifically Xcode 9). Xcode will emit a warning if you try to link a library that does not contain the supported architecture. This should happen today because CocoaPods always adds `-framework framework_name`but the problem is that our custom script phase will attempt to lipo every architecture out. 

There is a more strict mode for `ld` to make Xcode compilation actually fail if a framework is missing the architecture required for the current target. This can be enabled by `OTHER_LDFLAGS = -Xlinker -arch_errors_fatal` but it is not the default behavior of Xcode. Even if it does become the default behavior linking occurs before our script phases so the build would fail.

I am going to be updating the shell script phases to be more lenient when it comes to stripping architectures for both the `.framework` and `.framework.dSYM` itself.

**Comment by dnkoutso** [comment] 2017-11-04 02:00
Merged. Closing this!

**Closed by dnkoutso** 2017-11-04 02:00 UTC
Labels: r:vendored, t2:defect

**Comment by lumialxk** [comment] 2018-03-13 07:45
I got `Undefined symbols for architecture i386`. It seems ` --skip-import-validation` didn't work for Swift host project.

**Comment by dvdblk** [comment] 2018-06-03 13:33
The exact same thing still happening here, 3rd party framework with only armv7 and arm64 archs. Cant get past the linting stage...

**Comment by MarcoBrescianini** [comment] 2018-06-08 08:15
@dnkoutso The same thing happening to @lumialxk is happening to me too. I'm trying to push to a private repo a podspec for a project written in objective c, linking against a swift project and linking against an objective c project that is missing i386 architecture, and i cannot get past through the linting stage.

**Comment by dnkoutso** [comment] 2018-06-08 13:38
@MarcoBrescianini can you please upload a sample repo demonstrating the issue?

**Comment by jgongo** [comment] 2018-10-25 10:53
@lumialxk @dnkoutso I've created #8224 as this seems to be still present for Swift projects

**Comment by ingocraft** [comment] 2018-11-30 06:13
I almost have the same case with @hberenger . But the third-party in my private pod does not include both i386 and x86_64 libraries.
I add `pod_target_xcconfig` like this:

`
    s.pod_target_xcconfig = {                                                                
        'VALID_ARCHS[sdk=iphonesimulator*]' => ''
    }
`

after that, `pod lib lint --skip-import-validation` works for me.

I just hope "the lint" can ignore architecture i386 and x86_64. I'm not sure whether it is the right way, though it works.

**Comment by caixindong** [comment] 2019-01-11 07:53
This [link](https://github.com/CocoaPods/CocoaPods/issues/5854)  tells how to fix
```
when :ios
        command += %w(CODE_SIGN_IDENTITY=- -sdk iphonesimulator ARCHS=x86_64)
```

**Comment by yuanjilee** [comment] 2019-11-18 08:42
> I almost have the same case with @hberenger . But the third-party in my private pod does not include both i386 and x86_64 libraries.
> I add `pod_target_xcconfig` like this:
> 
> `s.pod_target_xcconfig = { 'VALID_ARCHS[sdk=iphonesimulator*]' => '' }`
> 
> after that, `pod lib lint --skip-import-validation` works for me.
> 
> I just hope "the lint" can ignore architecture i386 and x86_64. I'm not sure whether it is the right way, though it works.

only the `pod lib lint --skip-import-validation` is useful, with out set `pod_target_xcconfig`

**Comment by anivaros** [comment] 2020-04-08 15:47
Issue still exists. 
Last versions of Xcode even don't compile frameworks in 32 bit arch. Please, make ability to skip validation of 32bit arch without Podspec modification.

**Comment by krpatelit** [comment] 2021-06-11 04:15
For me it works after adding --use-libraries along with --skip-import-validation , without  add s.pod_target_xcconfig = { 'VALID_ARCHS[sdk=iphonesimulator*]' => '' }

pod repo push --skip-import-validation --allow-warnings --use-libraries  mavspec XXXX.podspec
