### ISSUE TITLE
Warning with Fresh Library Project: "ld: warning: directory not found for option"

### ISSUE THREAD

**Issue by benmarten** [CocoaPods/CocoaPods#5759] opened 2016-08-17 18:20 UTC
* [x] I've read and understood the [*CONTRIBUTING guidelines and have done my best effort to follow](https://github.com/CocoaPods/CocoaPods/blob/master/CONTRIBUTING.md).

# Report

## What did you do?

```
~/d/pod_test_3 $ pod lib create lib3                                                                                 11:14:42
Cloning `https://github.com/CocoaPods/pod-template.git` into `lib3`.
Configuring lib3 template.

------------------------------

To get you started we need to ask a few questions, this should only take a minute.

If this is your first time we recommend running through with the guide: 
 - http://guides.cocoapods.org/making/using-pod-lib-create.html
 ( hold cmd and double click links to open in a browser. )


What language do you want to use?? [ Swift / ObjC ]
 > ObjC

Would you like to include a demo application with your library? [ Yes / No ]
 > 
yes
Which testing frameworks will you use? [ Specta / Kiwi / None ]
 > None

Would you like to do view based testing? [ Yes / No ]
 > No

What is your class prefix?
 > LP

Running pod install on your new library.

Analyzing dependencies
Fetching podspec for `lib3` from `../`
Downloading dependencies
Installing lib3 (0.1.0)
Generating Pods project
Integrating client project

[!] Please close any current Xcode sessions and use `lib3.xcworkspace` for this project from now on.
Sending stats
Pod installation complete! There is 1 dependency from the Podfile and 1 total pod installed.

 Ace! you're ready to go!
 We will start you off by opening your project in Xcode
  open 'lib3/Example/lib3.xcworkspace'

To learn more about the template see `https://github.com/CocoaPods/pod-template.git`.
To learn more about creating a new pod, see `http://guides.cocoapods.org/making/making-a-cocoapod`.

~/d/p/l/Example (master) $ pod install                                                                               11:16:30

```
## What did you expect to happen?

No warning shows up.

## What happened instead?

The following warning is thrown in the tests target:
<img width="1512" alt="screen shot 2016-08-17 at 11 17 11 am" src="https://cloud.githubusercontent.com/assets/5960238/17748078/95c840d0-646c-11e6-8a4e-019170d00f9e.png">

### Stack

```
   CocoaPods : 1.0.1
        Ruby : ruby 2.3.1p112 (2016-04-26 revision 54768) [x86_64-darwin15]
    RubyGems : 2.6.6
        Host : Mac OS X 10.11.6 (15G31)
       Xcode : 7.3.1 (7D1014)
         Git : git version 2.9.2
Ruby lib dir : /usr/local/Cellar/ruby/2.3.1/lib
Repositories : CocoaPods-Test-Repository - https://github.com/benmarten/CocoaPods-Test-Repository.git @ b87ff1dcde766ac9b2db6cafbc2b559146df84b4
               leanplum - https://github.com/Leanplum/CocoaPods.git @ 271ec364b8395382771c9ca37ecd081f5435f5db
               Leanplum-CocoaPods-Private - https://github.com/leanplum/CocoaPods-Private.git @ fatal: ambiguous argument 'HEAD': unknown revision or path not in the working tree.
Use '--' to separate paths from revisions, like this:
'git <command> [<revision>...] -- [<file>...]'
HEAD
               master - https://github.com/CocoaPods/Specs.git @ 5a98665b91ca53c2c5038898024e9d2e0f475bed
```

### Installation Source

```
Executable Path: /usr/local/bin/pod
```

### Plugins

```
cocoapods-deintegrate : 1.0.0
cocoapods-packager    : 1.4.0
cocoapods-plugins     : 1.0.0
cocoapods-search      : 1.0.0
cocoapods-stats       : 1.0.0
cocoapods-trunk       : 1.0.0
cocoapods-try         : 1.1.0
```

## Project that demonstrates the issue

https://github.com/benmarten/lib3

## Possible Fix
Changing Framework Search Paths in the target from:
`$(SDKROOT)/Developer/Library/Frameworks`
to
`$(SDKROOT)/Developer/Library/PrivateFrameworks`

<img width="1552" alt="screen shot 2016-08-17 at 11 25 10 am" src="https://cloud.githubusercontent.com/assets/5960238/17748242/4d3846e8-646d-11e6-92b4-acf9adca5450.png">

Fixes the warning, not sure if that's the correct fix though...

**Comment by neonichu** [comment] 2016-08-18 07:58
This is a dupe of #4651

**Closed by neonichu** 2016-08-18 07:58 UTC
